### ISSUE TITLE
Changing color scheme of comiler and symbols setting

### ISSUE THREAD

**Issue by amirteymuri** [geany/geany#1006]
Is it also possible to change the color scheme in symbols (left) and compilers (down of the page) window?
How can i add -std=c++11 flag to the compiler?
How could i do these on geany?

**Comment by elextr** [comment]
> Is it also possible to change the color scheme in symbols (left) and compilers (down of the page) window?

The theme of any other than the edit window is set by the normal GTK theme, which you should be able to set from your desktop.

> How can i add -std=c++11 flag to the compiler?

See [this section of the manual](http://www.geany.org/manual/current/index.html#build-menu)

Please ask these questions on the mailing list.  This is not an issue.

**Comment by teymuri** [comment]
Thank you. Could you please send me the linke to the mailing list. I will then close this page.

**Comment by elextr** [comment]
http://www.geany.org/Support/MailingList

**Comment by codebrainz** [comment]
Closing as this is supported using GTK+ theming.
