### ISSUE TITLE
Keybinding not working

### ISSUE THREAD

**Issue by teymuri** [geany/geany#1009]
I want to bind the commenting to Ctrl+e. I go to Edit>Preferences>Keybinding dobble-click on **Toggle line commentation** and in the field i press Ctrl+e, nothing happens. I have also written <Primary>e inside the field, this also doesn't help. Can any one please help?

**Comment by elextr** [comment]
Works for me, and <primary>e is the default for toggle line continuation anyway.

**Comment by b4n** [comment]
Once you selected the item you want to change the key binding for, you should click the _Change_ button below, and the press the key binding you want, then validate the dialog.
Alternatively you can indeed manually edit the keybinding field in the list, but you then need to enter a valid description string, including the modifiers you want.  In your example, it would be `<Primary>e`.  But I highly recommend using the change dialog as it will capture the keybinding automatically, as needed.

**Comment by teymuri** [comment]
@b4n Thanks, i have managed it. 2 general questions yet:
Where can i close this question if it is finished, 2- What exactly is the mailing-List email , since if i ask questions on this adress: users@lists.geany.org i get no answers. I am not sure if this is the right mailingList adress?

**Comment by elextr** [comment]
You need to be subscribed to the ML, blame the spammers.  See http://www.geany.org/Support/MailingList
