### ISSUE TITLE
Execute button has no effect with windows 10

### ISSUE THREAD

**Issue by tulatows** [geany/geany#1028]
I up graded to Windows 10 and my Geany was fine.
Now with a new computer and a full install of Windows 10, the execute button doesn't work with Geany 1.22 or 1.27
I reconfigured the Execute action in Build->Set Builds Commands to this:
D:\Comodo\Dragon\dragon.exe %d\%f && exit
Now it executes my HTML but there is an annoying double flash from opening and closing a DOS window.
Any suggestions?

**Comment by elextr** [comment]
Duplicate of #1018 re-opening that so history is visible.
