### ISSUE TITLE
Crashes in Scintilla when Geany is idling 

### ISSUE THREAD

**Issue by eht16** [geany/geany#1033]
Since a few days, I experienced crashes in Geany.
I didn't find a way to reproduce it yet, mostly it happens after switching from another workspace back to the workspace where Geany is running. If the crash happens, it occurs directly after switching to the workspace with Geany.

Here is the backtrace:
```
Starting program: /usr/bin/geany
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffef631700 (LWP 26983)]
[New Thread 0x7fffeee30700 (LWP 26984)]
[New Thread 0x7fffd39cd700 (LWP 26985)]
[New Thread 0x7fff930c8700 (LWP 26986)]
Vector smash protection is enabled.
[New Thread 0x7fff8b034700 (LWP 26989)]
[New Thread 0x7fff8a833700 (LWP 26990)]
[New Thread 0x7fff8a032700 (LWP 26991)]
[New Thread 0x7fff89831700 (LWP 26992)]
[New Thread 0x7fff88c30700 (LWP 26993)]
[New Thread 0x7fff73fff700 (LWP 27035)]
[New Thread 0x7fff737fe700 (LWP 27036)]
[New Thread 0x7fff72ffd700 (LWP 27037)]
[New Thread 0x7fff727fc700 (LWP 27038)]
[New Thread 0x7fff71ffb700 (LWP 27039)]
[New Thread 0x7fff71186700 (LWP 27042)]
[New Thread 0x7fff70985700 (LWP 27043)]
[New Thread 0x7fff5bfff700 (LWP 27044)]
[New Thread 0x7fff5b7fe700 (LWP 27045)]
[Thread 0x7fff727fc700 (LWP 27038) exited]
[Thread 0x7fff5bfff700 (LWP 27044) exited]
[Thread 0x7fff72ffd700 (LWP 27037) exited]
[Thread 0x7fff73fff700 (LWP 27035) exited]
[Thread 0x7fff70985700 (LWP 27043) exited]
[Thread 0x7fff5b7fe700 (LWP 27045) exited]
[Thread 0x7fff71186700 (LWP 27042) exited]
[Thread 0x7fff71ffb700 (LWP 27039) exited]
[Thread 0x7fff737fe700 (LWP 27036) exited]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffffffe10a in ?? ()
(gdb) bt
#0  0x00007fffffffe10a in ?? ()
#1  0x00007ffff79f01dd in ScintillaGTK::StyleIdle (pSci=<optimized out>) at gtk/ScintillaGTK.cxx:2964
#2  0x00007ffff705fd67 in ?? () from /usr/lib/x86_64-linux-gnu/libgdk-x11-2.0.so.0
#3  0x00007ffff50e1fea in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff50e2390 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff50e26b2 in g_main_loop_run () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff74275b7 in gtk_main () from /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#7  0x00007ffff79b46f7 in main_lib (argc=1, argv=0x7fffffffdd38) at libmain.c:1229
#8  0x00007ffff4af7610 in __libc_start_main () from /lib/x86_64-linux-gnu/libc.so.6
#9  0x00000000004006f9 in _start ()
```

This issue is mostly to have the crash reported.

For me this happened on an up2date Debian Testing system at work and on an up2date ArchLinux system at home.

I don't have time to debug this further at the moment but might have a deeper look at it at the weekend. From the fact that the crash seems to happen in Scintilla, it might be related to the recent Scintilla update in master?

**Comment by b4n** [comment]
https://sourceforge.net/p/scintilla/bugs/1827/

**Comment by b4n** [comment]
I encountered this myself through the GitChangeBar plugin, which creates a Scintilla widget in a tooltip, which GTK2 creates and destroys fairly quickly (when the mouse moves over the area?  not sure, but it does create and remove quickly).
To reproduce it, just change or delete a line in a Git-tracked file opened in Geany, and hover the plugin's color strip in the margin: boom.

The issue isn't visible with GTK3, but probably only because it doesn't create and destroys the tooltip widgets so aggressively.

**Comment by eht16** [comment]
Wow, thanks @b4n for analysis, upstream reporting and providing three possible solutions.
For now, I chose patch v1 and being happy :).

And yes, I forgot to mention: the crashes I experienced happened on GTK2 too.
