### ISSUE TITLE
Full screen issues

### ISSUE THREAD

**Issue by lucamir** [geany/geany#1046]
Geany has some bug in full screen on OSX, like if you open the search window you can't close the full screen with the green button or the search window doesn't close anymore... and some crash when you try to save the project (always on full screen)

**Comment by techee** [comment]
Yes, I know the full screen is a bit strange on OS X - unfortunately this seems to be a GTK bug. In the future I might switch to GTK 3 on OS X which could fix this issue (but at the moment it's still too buggy).

**Comment by techee** [comment]
I believe this issue is fixed in the latest release based on GTK 3. Feel free to reopen this issue if you still experience the issue.
