### ISSUE TITLE
Geany loses executable bit with use_atomic_file_saving

### ISSUE THREAD

**Issue by grippon** [geany/geany#1049]
Also described here
https://bugs.launchpad.net/ubuntu/+source/geany/+bug/1572182

As I enabled use_atomic_file_saving, when the file is saved the executable bit is lost (and other special files attributes), the new file follows umask.

After removing use_atomic_file_saving to fix this problem, I remember why I needed it: because sometimes, instead of saving, geany tells me it couldn't save, so i have to press ok and save again and this time it works.

Can you copy file attributes from the old file to apply it to the new file with the atomic option please?

**Comment by elextr** [comment]
This is a known situation, and is documented in detail [here](https://wiki.geany.org/config/all_you_never_wanted_to_know_about_file_saving).

Use GIO saving to copy the metadata.
