### ISSUE TITLE
keyword "font" in a html document

### ISSUE THREAD

**Issue by xuanzon** [geany/geany#1051]
platform: windows 7 x64
geany version: 1.27
issue: every time I delete(from end of string and backspace) the keyword "font" in a html document, geany will crash.

add:
1. the keyword "image" in a html document has same issue.
2. keyword as a tag name

**Comment by codebrainz** [comment]
Do you have any plugins enabled?

**Comment by xuanzon** [comment]
oh, I re-check this issue.
it's an issue for pair tag highlighter plugin.
sorry about that.

**Comment by codebrainz** [comment]
@xuanzon no problem, the issue tracker for plugins is here:
https://github.com/geany/geany-plugins/issues
