### ISSUE TITLE
Crash on ubuntu 14.04 32bits when typing <>

### ISSUE THREAD

**Issue by Laurent3170** [geany/geany#1056]
When I type "<" it's automatically completed by ">" so I use the delete touch and it crashes. Not really important. It has more relation with  auto-close plugin.

**Comment by elextr** [comment]
Do you have any plugins enabled? try without any plugins.  Then if the problem has gone away enable them one by one and when you find the troublesome one please report it to the plugin maintainer on the [plugins issues](https://github.com/geany/geany-plugins/issues)

**Comment by b4n** [comment]
I would tend to incriminate the pair-tag-highlighter plugin that has already a few crash reports.

**Comment by Laurent3170** [comment]
The thing is that the "auto-close" plugin is the only place (for me) where we can set auto-complete for "<>", so if I disable the plugin, I won't have anymore this problem. But I don't know if the problem comes from the plugin or not. In my case I have removed the possibility to auto-complete "<". Should I "copy-paste" this in the plugin part ?

**Comment by elextr** [comment]
Do you have tag-pair-highlighter enabled, if so, as b4n says, it has been reported as possibly causing crashes.  From your OP you are getting the crash on the delete which is not the autoclose plugin inserting the >.

Make sure you only have one plugin enabled so you know which is the cause then report it.

**Comment by b4n** [comment]
I just tried, and I can't reproduce this with current dev version, nor with Geany-Plugins 1.27.
Apparently Ubuntu 14.04 has a fairly old version of Geany Plugins (1.23), so it might be interesting to test with a newer one.

**Comment by b4n** [comment]
If it doesn't help, try and give us exact steps to reproduce (does removing the inserted `>` *always* crash, no matter where?), and a debugger backtrace (`bt` at the GDB prompt).

**Comment by Laurent3170** [comment]
@elextr Yes I have tag-pair-highlighter enabled. @b4n I use Ubuntu 14.04 but version 1.27 of Geany. it does not always crash, but really often (90-95%). I have unchecked the completion of "<" in auto-close, then re-checked and try to reproduce... But it doesn't. What do you mean by 
> (bt at the GDB prompt)
I also use a special "tool" but I don't remember what and where to find it :-( to colorized the django templates (used for twig) and it more often crashes when I am in a twig file than in a php file. If it can helps.

**Comment by elextr** [comment]
Does the crash occur with pair-tag-highlighter disabled?

**Comment by Laurent3170** [comment]
It seems not

**Comment by elextr** [comment]
Then you should report the problem to tag-pair-highlighter on the [geany plugin](https://github.com/geany/geany-plugins/issues) issues, plugins is a separate project from Geany itself.

**Comment by Laurent3170** [comment]
Thanks! I did it at [#442](https://github.com/geany/geany-plugins/issues/442)
