### ISSUE TITLE
Cannot change theme for some filetypes

### ISSUE THREAD

**Issue by thdoan** [geany/geany#1059]
Steps to reproduce:

1. Unzip Geany Portable 1.27 to a folder and run it
2. Open a CSS or XML file
3. Select View / Change Color Scheme

I got this prompt:

![image](https://cloud.githubusercontent.com/assets/4110567/15926973/69d944dc-2e71-11e6-8091-b77c3be1ddf5.png)

No matter what theme I select, the theme for CSS and XML files is stuck on Default (though for other filetypes the theme is updated properly).

**Comment by thdoan** [comment]
Never mind -- I had to go into `Geany\Data\settings\filedefs` and manually remove the styles defined in the files there in order to fix this.

**Comment by elextr** [comment]
Yes, those filetypes specifically define styles, because they have syntactic entities that are special to those filetypes and not (or unlikely to be) covered by most colour schemes.

**Comment by thdoan** [comment]
Instead of adding the overriding styles there, can we add a comment instead, e.g.:

`# To override a style, copy the styles from the respective file inside Geany\App\DefaultData\settings\filedefs`

Perhaps this is something for the PortableApps team to consider.

**Comment by codebrainz** [comment]
I don't know what this issue is about, but that comment is not accurate. It's extremely rare that any user should modify any style mappings in the filedefs/filetypes.* files, those mappings are only there for legacy reasons. CSS and XML should work with all colour schemes out-of-the-box, barring any bugs in the Portable version.

**Comment by thdoan** [comment]
I think this is an issue with the portable version. When I removed all the files in `GeanyPortable\Data\settings\filedefs` and restarted Geany, I was able to change themes without any issues.

**Comment by codebrainz** [comment]
@thdoan where do you get a zip file for Geany Portable? I was going to see if maybe they had a problem with the configuration files, but all I could find was a Win32 .exe file (definitively not portable :)

**Comment by thdoan** [comment]
@codebrainz Here's how you can reproduce this using Geany Portable:

1. Downloaded it from http://portableapps.com/apps/development/geany_portable
2. Install into any folder
3. Start Geany

You should see bunch of files in `GeanyPortable\Data\settings\filedefs` with overriding styles that prevent you from changing the theme. Geany Portable should not copy over these files on first start, or at least leave out the overriding styles, which could be confusing for first-time users.

**Comment by codebrainz** [comment]
I got from your original PR description that there was a zip file I could unzip on my Linux. If not, I'll try and remember to check it out next time I'm in the Windows.
