### ISSUE TITLE
Incorrecting Folding and Marking for <<

### ISSUE THREAD

**Issue by blooregardskotch** [geany/geany#1063]
Sample Code in Bash below.
The problem is with <<EOL.
All text after the <<EOL is green and a fold point is created.
The fold point and green text only ends if I put EOL at the beginning of a line. If there is any space or tab geany does not register the EOL and continues to use green text.

```bash
function myFunction() {
	echo "This is my function"
	if [ -n "${LEGACY+1}" ]; then
		OUTPUT="command1\n"
		OUTPUT+="command2"
		someinput_program <<EOL
			$(echo -e $OUTPUT)
			quit
		EOL
	else
		OUTPUT="command1 with command2"
		anotherinput_program $OUTPUT
	fi
	echo -e $OUTPUT
}
```

(tab and returns does not appear to be working for me on this form)

**Comment by b4n** [comment]
> (tab and returns does not appear to be working for me on this form)

You need to use a comment block, I edited your post.

**Comment by b4n** [comment]
Your snippet is correctly highlighted, but is wrong.  Just try and run it you'll see Bash agrees it's malformed.  To allow indenting the terminator line, use `-` prefix, e.g. `-EOL`.
