### ISSUE TITLE
brace_good and brace_bad styles cannot be changed

### ISSUE THREAD

**Issue by thdoan** [geany/geany#1065]
I changed the `brace_good` foreground color to green (`0x00ff00`) in `filetypes.common`, but the color is still stuck on white. The same applies to the `brace_bad` style.

**Comment by thdoan** [comment]
UPDATE: I found out that the styles in `filetypes.common` were being overwritten by the style definitions in the theme configuration file inside `Geany\data\colorschemes`.

Although this is not a bug, I found it confusing that there are multiple levels of overrides in different locations.

**Comment by codebrainz** [comment]
The default scheme being called `filetypes.common` in the config dir instead of `default.conf` in the schemes dir like every other scheme is indeed confusing.
