### ISSUE TITLE
Add path to goto definition/declaration popup

### ISSUE THREAD

**Issue by techee** [geany/geany#1069]
At the moment if symbols of the same name are defined in identically named files, it's hard to distinguish which file is which because there's no path in the popup.

The popup should show part of the path until a directory where the paths differ so it's possible to distinguish the different files. At the same time there should probably be some top limit for the length of the paths as they can make the popup too wide.

**Comment by elextr** [comment]
Maybe elide some of the path to get something like

```
.../different_path/.../file
```
