### ISSUE TITLE
The directory name is not valid

### ISSUE THREAD

**Issue by TheVitagor** [geany/geany#1076]
Hello, I am trying to work with geany in Windows 10, I already have python installed (which is the programming language I will be using), the problem is that when I just try to run a program in geany the cmd doesnt open, and the geany gives me the error message: "Could not find the command «cmd.exe /Q /C%c»: The name of the directory is invalid. Check de route in «Preferences».
What can I do to fix this issue?
Thank you.

**Comment by TheVitagor** [comment]
The full message is: Cannot execute terminal command «cmd.exe /Q /C%c»:The directory name is invalid. Check the path setting in Preferences.

**Comment by codebrainz** [comment]
Can you please give some additional information:

- What version of Geany
- What are your settings in the Build->Set Build Commands dialog (screenshot if possible)
- What language is your operating system set to (French?)
- What is the full path to file you have open in Geany when this happens
- Can you paste the contents of Help->Debug Messages dialog here

Thanks.

**Comment by elextr** [comment]
On 18 June 2016 at 12:04, Matthew Brush <notifications@github.com> wrote:

> Can you please give some additional information:
>
>    - What version of Geany
>    - What are your settings in the Build->Set Build Commands dialog
>    (screenshot if possible)
>    - What language is your operating system set to (French?)
>
>
​And is it a UTF-8 locale or another one?​

**Comment by eht16** [comment]
`«cmd.exe /Q /C%c»` there is a space between `/C` and `%c` missing, that might be the cause for the problem.
The default command has this space: https://github.com/geany/geany/blob/master/src/keyfile.c#L78

**Comment by TheVitagor** [comment]
Introducing a space between /C and %c didnt work.

**Comment by TheVitagor** [comment]
-My version of Geany is 1.27
-This are my settings in the Build->Set Build Commands dialog https://gyazo.com/4da1a9cde488201a3da46b4b1520a100
-As you could see in the sceenshot, my operating system is set to Spanish.
-The file running was just a test to know if Geany was working, I just have introduced "print('f')", but I have many other files .py which doesn't work either, I mean, it never works.
-My debugg dialog is:
01:53:07: Geany INFO		: Geany 1.27, C
01:53:07: Geany INFO		: GTK 2.24.28, GLib 2.46.2
01:53:07: Geany INFO		: System data dir: C:\Program Files (x86)\Geany\data
01:53:07: Geany INFO		: User config dir: C:\Users\---\AppData\Roaming\geany
01:53:07: Geany INFO		: System plugin path: C:\Program Files (x86)\Geany\lib\geany
01:53:07: Geany INFO		: Added filetype Clojure (61).
01:53:07: Geany INFO		: Added filetype CUDA (62).
01:53:07: Geany INFO		: Added filetype Cython (63).
01:53:07: Geany INFO		: Added filetype Genie (64).
01:53:07: Geany INFO		: Added filetype Graphviz (65).
01:53:07: Geany INFO		: Added filetype JSON (66).
01:53:07: Geany INFO		: Added filetype Scala (67).
01:53:07: Geany INFO		: C:\Users\---\Desktop\el.py : Python (UTF-8)
01:53:07: Geany INFO		: Loaded C:\Program Files (x86)\Geany\data\python.tags (Python), 5965 symbol(s).

**Comment by eht16** [comment]
`C:\Users---\Desktop\el.py` looks strange. Is this what Geany reports or did you anonymize your username? In the latter case, does your username contain any non-ASCII characters?
Could you try to save and run the file in another path, like `C:\` ?

**Comment by TheVitagor** [comment]
No, don't worry, I just anonymize it, the username is just my full name, so contains plenty ascii characters

**Comment by codebrainz** [comment]
@TheVitagor does your full name contain any _non_ ASCII characters (ex. with Spanish accents or such)? The reason I asked for the full path to the file you're running and @eht16 asked about non-ASCII characters is to check if maybe there is a bug in character encoding.

**Comment by TheVitagor** [comment]
I just realised that I got an accent on my username, may that be the problem?

**Comment by codebrainz** [comment]
@TheVitagor if you can put the file in any other place like in `C:` as @eht16, that only has ASCII characters in the path, it would determine if it's related to the non-ASCII characters.

**Comment by eht16** [comment]
I'd like to keep this open as it is a real bug and it is not resolved. There is just a workaround.

I can reproduce it and am working on a solution.

**Comment by eht16** [comment]
@TheVitagor if you are curious to test:
http://download.geany.org/snapshots/geany-1.28nightly20160703_pr1095_setup.exe
This is current development version of Geany which is meant to be released next week plus a possible fix of your problem.
It is probably best to also install also the new plugins from http://download.geany.org/snapshots/geany-plugins-1.28nightly20160703_setup.exe because the old ones are probably not compatible anymore with the new build. Just de-install Geany and Geany-Plugins before, your settings will not be removed.

**Comment by eht16** [comment]
This should be fixed now in Geany 1.29 (released today).
We merged #1095 which fixes locale issues when spawning external commands.
