### ISSUE TITLE
Error message could be improved

### ISSUE THREAD

**Issue by codebrainz** [geany/geany#1077]
This error message is not very good, IMO.

https://github.com/geany/geany/blob/1.27.0/src/build.c#L907

**Comment by elextr** [comment]
+1 its probably trying to provide a hint of a common problem, but instead it is often irrelevant or misleading.

**Comment by eht16** [comment]
What about something like:
```
gchar *utf8_term_cmd = utils_str_replace_all(&tool_prefs.term_cmd, "%c", run_cmd);
ui_set_statusbar(TRUE, _("Cannot execute build command \"%s\": %s. "
"Check the path setting for Terminal in the Tools tab in Preferences."), utf8_term_cmd, error->message);
```
?

**Comment by elextr** [comment]
@eht16 the standard error message is printed saying exactly what is wrong, so whatever we add should be very general or it may contradict the specific error.  IMHO it shouldn't mention "path" at all, just "Check the Terminal setting in Preferences".

**Comment by codebrainz** [comment]
> Check the path setting for Terminal in the Tools tab in Preferences.

That's much better, except maybe `s/path/command/`.

**Comment by eht16** [comment]
See #1080, I used Lex' suggestion.
