### ISSUE TITLE
Symbols list with symbols grouped by scope

### ISSUE THREAD

**Issue by misopeth** [geany/geany#1082]
When writing LaTeX, symbols in the Symbols list are grouped by type (Environment, Section, Paragraph, Chapter, ...), so it is not immediate to understand the structure of the document.
It would be nice if the Symbols list could have a third sorting mode (besided "by Name" and "by Appearance") that makes the Symbol list like a Table of Contents.

**Comment by elextr** [comment]
Other markups like Asciidoc or markdown show the document structure.  Its not simply a sort but a proper hierarchy with nested parts being able to be rolled and unrolled.  Unfortunately sort then only works inside the hierarchy level.
