### ISSUE TITLE
Feature Request: Ability to remove a key binding

### ISSUE THREAD

**Issue by box293** [geany/geany#1088]
I have a bad habit of accidentally hitting CTRL + Q and it closes Geany.

It would be great if I could remove this key binding. 

I went into the preferences menu however I could only see an option to change a key binding to something else, there was no option to remove an existing key binding.

**Comment by b4n** [comment]
You can change it and then not hit any key before validating the new one, which will result in no keybinding bound to that action.  You can also manually edit the Keybinding column and empty it.

I myself have rebound Quit to <kbd>Ctrl+!</kbd> though :)

**Comment by box293** [comment]
Ahhh I didn't realise I could edit the column. Nice, easily solved :)

Thanks for the quick response.
