### ISSUE TITLE
:last-child

### ISSUE THREAD

**Issue by snob09** [geany/geany#1102]
In my css file the pseudo class :last-child doesn't change color like all the others. Is this a small bug? 

![screenshot from 2016-06-30 18 06 44](https://cloud.githubusercontent.com/assets/19384359/16497459/0177fcf6-3eef-11e6-9d3c-4254711011ae.png)

I'm using Geany "Rezer" (built on or after 2016-03-13) in Linux Mint 17.3

Thank you

**Comment by elextr** [comment]
Confirmed on latest git.  Possibly the Scintilla lexer, or a bug in sending it the names since the last-child appears in the symbol list.

**Comment by b4n** [comment]
@elextr it's simply missing from *filetypes.css* `pseudoclasses`' keyword list

**Comment by elextr** [comment]
So why do keywords appear in the symbols list?

**Comment by b4n** [comment]
@elextr what do you mean, which symbol list?  (don't mix it with `nth-last-child`)

**Comment by elextr** [comment]
Ok, the symbol isn't just "last-child" its the whole selector "article
p:last-child", is that useful? But anyway thats not part of this issue.

**Comment by b4n** [comment]
> Ok, the symbol isn't just "last-child" its the whole selector "article p:last-child", is that useful?

Well, at least it's what the parser is supposed to give you, so that's a start.
And IMO yes, it's the best it can do (but possibly make a hierarchy out of it, but that's tricky), as the whole selector is relevant to know on what the rule will apply.

> But anyway thats not part of this issue.

nope, indeed it's not :)

@snob09 thanks for the report, it's now fixed.

**Comment by b4n** [comment]
@snob09 BTW you can fix it on your side by altering your CSS filetype file.  Just remember that all user overrides (in ~/.config/geany) will stay even when the system gets a new version of the related system files, so you might want to watch for updated if you override any.

**Comment by snob09** [comment]
Thank you both.
