### ISSUE TITLE
windows geany1.27 grep error

### ISSUE THREAD

**Issue by BrightRubik** [geany/geany#1113]
change the grep.exe than can search other dir files.

**Comment by elextr** [comment]
The grep is set by the Menu->Edit->Preferences->tool->grep setting.

**Comment by codebrainz** [comment]
This Issue makes no sense. @BrightRubik can you elaborate, like what error you encounter, or what kind of improvement you suggest or something actionable?

**Comment by eht16** [comment]
Closing due to lack of information.
@BrightRubik feel free to re-open with more details.
