### ISSUE TITLE
Tags messages

### ISSUE THREAD

**Issue by elextr** [geany/geany#1122]
```
13:33:27: Geany INFO		: Unknown filetype for file '/data/newgitgeany/share/geany/tags/pascal.tags'.
13:33:27: Geany INFO		: Unknown filetype for file '/data/newgitgeany/share/geany/tags/php.tags'.
13:33:27: Geany INFO		: Unknown filetype for file '/data/newgitgeany/share/geany/tags/html_entities.tags'.
13:33:27: Geany INFO		: Unknown filetype for file '/data/newgitgeany/share/geany/tags/python.tags'.
13:33:27: Geany INFO		: Unknown filetype for file '/data/newgitgeany/share/geany/tags/c99.tags'.
```
 Geany git version 93977f4ad10cb767ff40c9575ce9dc6e696d6542.

**Comment by elextr** [comment]
@techee @b4n, something you fiddled with?

**Comment by codebrainz** [comment]
https://github.com/geany/geany/commit/854a5d5af826c7dfbebc50dbcf687e508d7444c5

**Comment by eht16** [comment]
Yeah, that commit should have fixed the issue.
Maybe you need to delete the old files or the whole installation directory and install again to get rid of the old files.

**Comment by elextr** [comment]
Ok, yeah, clearing the tags dir and `make install`ing fixed it.

Will distro packages do that?

**Comment by eht16** [comment]
Yes, as they keep a list of installed files which will then be removed on deinstallation and upgrade.

**Comment by elextr** [comment]
ok, fixed.
