### ISSUE TITLE
Long line marker flickers when typing fast

### ISSUE THREAD

**Issue by pisceswolf96** [geany/geany#1123]
Hello everyone. The long line marker in geany flickers while typing fast(and also sometimes when highlighting with the mouse and when using the arrows keys to navigate text)

**GTK** 2.24.30, **GLib** 2.48.1

[Edit: additional info from IRC, Ubuntu Mate 16.04]

**Comment by codebrainz** [comment]
Are you using any plugins?

**Comment by pisceswolf96** [comment]
I've Installed the package geany-plugins from ubuntu 16.04 repos. I've uninstalled it to no avail.

**Comment by pisceswolf96** [comment]
The problem seems to be not exclusive to geany. It happened to me while using emacs, so I guess it's a GTK problem.

**Comment by pisceswolf96** [comment]
After enabling compton compositor, the problem seems to be resolved.
