### ISSUE TITLE
Transferring files all at once into Geany from 1st computer to 2nd computer

### ISSUE THREAD

**Issue by Robbyorolo** [geany/geany#1127]
Hi Guys/Gals:
Running windows 7 64 bit here.
 Have installed Geany on another / 2nd computer.

Have transferred the .py files from one/1st computer to another/2nd computer that I was working on in Geany.

When I bring up Geany on the original/1st computer, the documents section of Geany ( left hand side of the Geany interface) shows all of the .py files that I was working on.
The documents/files task bar near the top of Geany, but below the normal task bar ( File, Edit, Search, etc…) also show the files that I was working on as well.

How can I get the 2nd computers Geany to show all of the files in the documents section and the documents/files task bar in one quick command ?

Otherwise I have to hunt for each file and bring it up then save each one in order to get the same view I have on the 1st computer. 

Thanks, Rolo

**Comment by elextr** [comment]
These show files that have been opened in Geany.  Since you havn't opened them on the new computer they don't show.

If the files are in exactly the same place on both computers you can copy the geany.conf file from one computer to the other (with geany closed or it will be overwritten).  The manual (Menu->help->help) tells you where its located on Windows.

If the files are located in a different place you are probably better to just go find them.

**Comment by Robbyorolo** [comment]
Thanks elextr,
 Just tried what you suggested but had no effect on the 2nd computers Geany interface as far as files are concerned. 
But appreciate your help.

**Comment by elextr** [comment]
If geany.conf it was copied correctly to the right place when you open Geany it should open the same files as the original one had open and have the same recent files list.

You can check by looking at the geany.conf `[files]` section where recent_files and open files are listed.

If the copied file has the right things in it, then it hasn't been put in the right place, it should overwrite the geany.conf on the new machine.

**Comment by Robbyorolo** [comment]
Thanks elextr,
I'll just pull the files from the folder one by one since the scenario didn't work.
Thanks for your help in this.
 This case is closed.
