### ISSUE TITLE
[Feature request] Documents sidebar, right-click rename

### ISSUE THREAD

**Issue by Fordi** [geany/geany#1138]
What it says in the title.  I'd like for the files in the Documents sidebar to be renamable from that location.

**Comment by elextr** [comment]
Note that there is the treebrowser plugin which tries to provide full filemanager type functionality.  Past discussions have generally been against expanding the built-in tree to be a filemanager.

**Comment by codebrainz** [comment]
See also: https://github.com/geany/geany/pull/138
