### ISSUE TITLE
[Feature request] Live delete/rename tracking

### ISSUE THREAD

**Issue by Fordi** [geany/geany#1139]
If possible, I'd like for geany to use an inotify hook (where available) to detect delete/rename of open files in real-time.

**Comment by elextr** [comment]
IIUC `inotify` is a Linux only capability.  

An attempt was made to use the glib wrapper functions around the various platform specific notify libraries, however it generates extra spurious notifications on Linux that of course generated annoying extra user notifications, and it proved too hard to filter these out, so it was disabled.  I think the code is still there if anyone wants to try to fix it.

**Comment by andy5995** [comment]
Because inotify is Linux-only, would [Gamin](https://people.gnome.org/~veillard/gamin/index.html) ever be considered a suitable substitute? Though I've never used it, and don't see that it works under Windows.

**Comment by elextr** [comment]
Gamin doesn't work on windows, so no it probably won't be used.

**Comment by codebrainz** [comment]
What advantage/portability benefit does Gamin bring over GIO's [FAM](https://git.gnome.org/browse/glib/tree/gio/fam), [inotify](https://git.gnome.org/browse/glib/tree/gio/inotify), [kqueue](https://git.gnome.org/browse/glib/tree/gio/kqueue), and [win32](https://git.gnome.org/browse/glib/tree/gio/win32) GFileMonitor backends?

**Comment by andy5995** [comment]
I don't know much about file monitoring API's; that's why I was asking ;)

**Comment by codebrainz** [comment]
The one in GLib/GIO is pretty nice, but it has problems (at least with the inotify backend) which @elextr mentioned, that nobody has provided a work-around for yet.
