### ISSUE TITLE
Syntax highlighting problem in PHP

### ISSUE THREAD

**Issue by ncabanes** [geany/geany#1143]
Syntax highlighting fails in PHP files when a parameter is a string more than one line long. It happens since (at least) several versions ago.  To repeat the bug:

Type or copy/paste a PHP file with a function parameter of type string, more than one line long, such as this:

```
<p>Paragraph 1</p>

<?php function("1
2", 'sql') ?> 

<p>Paragraph 2</p>
```

Save it as "example.php" and the syntax highlighting will be correct. 

Now modify the second line of the function (for example, to change the 2 to a 3 or to add some text or a few extra lines) and the paragraph 2 (and all the following ones if they existed) will be "highlighted" in green color as if they still were part of the parameter.

**Comment by elextr** [comment]
@ncabanes this is a problem with Scintilla the editing component we use. It is a separate project and if @b4n hasn't already you should report this [here](https://sourceforge.net/p/scintilla/bugs/)

**Comment by b4n** [comment]
https://sourceforge.net/p/scintilla/bugs/1849/
