### ISSUE TITLE
Possible Data Loss if a file save fails during close

### ISSUE THREAD

**Issue by elextr** [geany/geany#1147]
Found by inspection, needs to be checked.

Both the plain C file IO and GIO (g_file_replace_contents) can leave the original file damaged if a failure occurs during a write.  The normal advice is to "don't panic, you still have the buffer contents to save somewhere else", but if the save fails during a close Geany will still close, so now both the original file and the buffer are lost.

Basically `libmain.c` in `main_quit` should not ignore the return from `document_close_all()`.

**Comment by b4n** [comment]
I don't see it.  `main_quit()` calls `document_account_for_unsaved()`, which itself uses `dialogs_show_unsaved_file()`, that properly return the value of `document_save_file()` if asked to save the file.  What's wrong here?

**Comment by elextr** [comment]
But it doesn't abort the close AFAICT

**Comment by b4n** [comment]
> ```C
/* Returns false when quitting is aborted due to user cancellation */
gboolean main_quit(void)
{
	main_status.quitting = TRUE;
>
	if (! check_no_unsaved()) // if there are some unsaved files
	{
		if (document_account_for_unsaved()) // if saving them was successfully dealt with
		{
			do_main_quit(); // quit!
			return TRUE;
		}
	}
	/* […] */
>
	// abort quit
	main_status.quitting = FALSE;
	return FALSE;
}

**Comment by elextr** [comment]
ahhh, I'm confusing `main_quit()` and `do_main_quit()`, stupid Geany spaghetti late at night.

Thats a relief :smile:

Slightly OT, looking at `main_quit()` it appears that if there are unsaved files the user is never asked to confirm the quit?

**Comment by b4n** [comment]
> Slightly OT, looking at `main_quit()` it appears that if there are unsaved files the user is never asked to confirm the quit?

No, but IMO it makes sense: if you're asked whether you want to save files because you're quitting, you can cancel instead, no need for a second dialog.
