### ISSUE TITLE
Create a new file error

### ISSUE THREAD

**Issue by artem-check** [geany/geany#1151]
After last update, Geany 1.27

When i push "Create new file", there is no possibility to specify the file name. The file is opened immediately. To enter the file name, it is necessary to rename it.

**Comment by elextr** [comment]
This is the intended behaviour.  `Create New File` creates a buffer named `untitled`, it creates the file on save when a name will be requested by showing the `Save-As` dialog.

**Comment by artem-check** [comment]
No, new file with name "new file" creates immediately. It is problem.

I have to press a lot of buttons, simply create a new file. It is very hinders the work.

**Comment by elextr** [comment]
This is not the normal behaviour of Geany.  Do you have any plugins enabled?  If so please try without *any* plugins enabled.

**Comment by artem-check** [comment]
> This is not the normal behaviour of Geany. 

I knew.

I do it with plugin "Files tree". Sorry, I meant this particular plugin.

How I can fix it behavior?

**Comment by elextr** [comment]
The Geany plugins is a separate project with its own issues at https://github.com/geany/geany-plugins/issues please report it there noting the plugin so the appropriate maintainer will notice it.

**Comment by artem-check** [comment]
Thank You!

**Comment by artem-check** [comment]
When it gets to Ubuntu's update?

**Comment by elextr** [comment]
When what gets to ubuntu update?

**Comment by codebrainz** [comment]
I presume @artem-check means "When will the fix in https://github.com/geany/geany-plugins/pull/473 be available in Ubuntu?" ... if so, I would defer the question to @hyperair :)

**Comment by elextr** [comment]
Oh, ok, well, GP-473 isn't in 1.28, so it will be 1.29 (targeted at Nov 12) plus @hyperair release delays.
