### ISSUE TITLE
[Feature Request] Show more lines beneath Cursor

### ISSUE THREAD

**Issue by fdg-org** [geany/geany#1152]
I would like to have the possibility to see more lines beneath the cursor when the cursor is near the bottom of the text edit pane.

 @b4n mentioned in the last paragraph of [his comment](https://github.com/geany/geany/issues/1116#issuecomment-230763662) to issue #1116 
> However, we could indeed set [the Y caret policy](http://www.scintilla.org/ScintillaDoc.html#SCI_SETYCARETPOLICY) with an offset so the last line is never on the bottom, something like `SCI_SETYCARETPOLICY(CARET_SLOP | CARET_STRICT | CARET_EVEN, 1).`
> I guess that'd be reasonable, but may require a setting.

So my feature request is: Please implement such a setting, but please with more than just one single line - it would be nice to be able to freely set the number of lines.

**Comment by elextr** [comment]
See the eht16 comment on #1116

**Comment by fdg-org** [comment]
This does not do what I would like to have. What I suggest is that the cursor never goes to the bottom line of the text editor pane, but instead the content of this pane is scrolled already when the cursor is on the Nth last line, so that there are always N - 1 lines of text being displayed beneath the line in which the cursor is.

**Comment by elextr** [comment]
Ok, pull requests are welcome.  Note it would definitely need a setting, not everybody is going to want that behaviour.

**Comment by fdg-org** [comment]
> it would definitely need a setting, **not everybody is going to want that behaviour**

That's for sure!

Unfortunately, I'm not experienced enough to implement that myself, but I never expected it to be of high priority for the Geany team - I just wanted it to be written down, so if someone experienced enough to program this can implement it, if (s)he has nothing else to do and wants to fight boredom. :smirk:

**Comment by elextr** [comment]
>  I just wanted it to be written down, so if someone experienced enough to program this can implement it, if (s)he has nothing else to do and wants to fight boredom.

Yep, its marked "enhancement", but unfortunately its only one of many looking for those bored masses :smile:

**Comment by b4n** [comment]
See #1154.
