### ISSUE TITLE
Improper colorizing of multiline bash statements with interspersed comments

### ISSUE THREAD

**Issue by stoneguy** [geany/geany#1153]
Environment is geany 1.27 on 64-bit Ubuntu 14.04

Confusion results when script.sh contains multi-line statements with some intervening lines commented out with #.  Sample:

`statement start \`
`# statement continue \`
`statement final`

The 2nd and 3rd line both display in red.

Deleting the **\** on line 2 gives shows it red and line 3 black. I believe that's the correct result.
My intent is to activate / deactivate the 2nd line by removing / inserting the leading **#**

**Comment by elextr** [comment]
This is a problem with Scintilla, the editing component that Geany uses and which does the highlighting.  The same problem occurs in Scite the Scintilla reference editor.  Scintilla is a separate project.  Please report this at [its bugtracker](https://sourceforge.net/p/scintilla/bugs/) and report the bug number back here for tracking.
