### ISSUE TITLE
Indistinguishable active tab - GTK3 - Ubuntu

### ISSUE THREAD

**Issue by hongquan** [geany/geany#1156]
I built Geany with GTK3 and try under default theme of Ubuntu. Looking in the tab, I cannot see which one is active.

![selection_121](https://cloud.githubusercontent.com/assets/314607/17275980/be34f14c-5744-11e6-8468-bee4a95265f5.png)

**Comment by elextr** [comment]
This is likely to be related to the theme.  Geany does not specify what an active tab looks like (see [geany.css](https://github.com/geany/geany/blob/master/data/geany.css)), so whatever the theme defines will be used.

On my Mint (Ubuntu based) system with GTK 3.18.9, the active tab is clearly defined with an out-of-the-box Geany.

**Comment by hongquan** [comment]
I want to contribute a patch to [geany-3.0.css](https://github.com/geany/geany/blob/master/data/geany-3.0.css) to make it look better, like this

![selection_122](https://cloud.githubusercontent.com/assets/314607/17276209/2a30cacc-574c-11e6-858f-be601c0f83b2.png)

Is it OK?

**Comment by elextr** [comment]
Best to make a pull request, but it should not interfere with themes on systems where it currently works.

**Comment by b4n** [comment]
As we don't style the tabs, it's IMO not our problem but the Ubuntu's theme one.  How does other apps look like?  FWIW, the default GTK3 theme works just fine in that regard.

And as @elextr's pointed out, *if* we did anything, it would have to be compatible with *any* theme -- or specific to one, if that's even possible.  It wouldn't be acceptable to e.g. set a background color ourselves, as it would conflict with all themes.

And BTW, I don't see much difference between the 2 captures.  I don't think it's a worthy improvement if it's still that subtle to distinguish.
