### ISSUE TITLE
Find regex multi-line does not work

### ISSUE THREAD

**Issue by EricViala** [geany/geany#1165]
Setting : 
geany 1.27 (built on Apr 17 2016 with GTK 2.24.30, GLib 2.48.0)
Linux 4.4.0-31-generic #50-Ubuntu SMP Wed Jul 13 00:07:12 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

Consider the following plain text

> Sed ut perspiciatis, unde omnis iste natus error sit uoluptatem
> accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae
> ab illo inuentore ueritatis et quasi architecto beatae uitae dicta
> sunt, explicabo. nemo enim ipsam uoluptatem, quia uoluptas sit,
> aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos,
> qui ratione uoluptatem sequi nesciunt, neque porro quisquam est, qui
> dolorem ipsum, quia dolor sit, amet, consectetur, adipisci uelit, sed
> quia non numquam eius modi tempora incidunt, ut labore et dolore magnam
> aliquam quaerat uoluptatem. ut enim ad minima ueniam, quis nostrum
> exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex
> ea commodi consequatur? quis autem uel eum iure reprehenderit, qui in
> ea uoluptate uelit esse, quam nihil molestiae consequatur, uel illum,
> qui dolorem eum fugiat, quo uoluptas nulla pariatur?

It has two occurences of the word _qui_ followed by the word _dolorem_ : one where _qui_ is at the end of line 6 and _dolorem_ at the beginning of line 7, and one at line 13.

Using Search/Find
Search for : qui.*?dolorem
x Use regular expressions
x Use multi-line matching

I would expect two matches. I get only the last one.
It seems to me that this behaviour contradicts the tooltip "newline characters are part of the input and can be captured as normal characters by the pattern." and also what I'm used to in <other editor>.

On the other hand, `qui(\s)*?dolorem` matches both.

**Comment by elextr** [comment]
As [documented](https://developer.gnome.org/glib/stable/glib-regex-syntax.html) dot does not match line ends by default, and in the "Internal Option Setting" section it is documented that `multiline` and `dotall` are separate options.  If you set `dotall` by `(?s)qui.*?dolorem` you get two matches, though not the ones you seem to expect :)

The `\s` matches some line end characters so it will find the examples you seek.

**Comment by b4n** [comment]
The link to the Geany manual: https://www.geany.org/manual/#multi-line-regular-expressions

So this is not a bug.  Maybe we could come up with a better tooltip though, suggestions welcome.
