### ISSUE TITLE
C:\Program Files (x86)\Geany\Geany.lnk should not have "Start in:" set

### ISSUE THREAD

**Issue by gigadude** [geany/geany#1183]
Invoking `C:\Program Files (x86)\Geany\Geany foo.txt` for some existing file `foo.txt` in your current dir (or at any relative path) fails because the link has a "Start in:" value set; leaving this empty makes it work as expected.

**Comment by codebrainz** [comment]
I don't know much about NSIS, but I think [this](https://github.com/geany/geany/blob/master/geany.nsi.in#L172) is where the shortcut is created, and according to [the docs](http://nsis.sourceforge.net/Reference/CreateShortCut) it seems to be set automatically to $OUTDIR, if I understand correctly. Maybe it's possible to use [SetOutPath](http://nsis.sourceforge.net/Reference/SetOutPath) with an empty argument to clear $OUTDIR, then use CreateShortCut to create the shortcut, then set $OUTDIR back to $INSTDIR afterwards? I really have no clue.

**Comment by kugel-** [comment]
The link is not meant to be used from the command line. It was put there for compatibility when the actual binary was moved to the bin subir.

So please use the actual binary, as in `C:\Program Files (x86)\Geany\bin\geany foo.txt`. This is not a bug to me.

**Comment by eht16** [comment]
I agree with @kugel- and he already provided the solution.
