### ISSUE TITLE
CTRL+L not working

### ISSUE THREAD

**Issue by ComputingFroggy** [geany/geany#1189]
Hi,

I am running Geany 1.27 with GTK 2.24.30, GLib 2.48.1 on Ubuntu Gnome 16.04.

When I try to go to a specific line with CTRL+L, that does not work ! I have to use the Menu "_Search => Go to Line..._"  ... which is a real pain !
If anyone has a clue, how to solve this problem, I will be grateful.

Cheers.

**Comment by b4n** [comment]
<kbd>Ctrl+L</kbd> focuses the *Go to line* entry in the toolbar if it's visible instead of opening the extra dialog.

Doesn't it do this for you?

If you wanna force opening the dialog, you can remove the *Go to line* entry from the toolbar (in the preferences under *Interface → Toolbar*).

**Comment by ComputingFroggy** [comment]
Indeed, that works well ! ! My bad: I did not notice that focus changed 
to the toolbar, I was expecting the dialog to open.

This is even better and quicker ... once you know it ! As we say "better 
one who knows than one hundred who are searching !"

Thanks a lot !
