### ISSUE TITLE
More info about file.

### ISSUE THREAD

**Issue by psrafo** [geany/geany#1196]
I think it's can be a useful info; showing size of a file in bytes to the right of **scope: main**

![geany-bytes](https://cloud.githubusercontent.com/assets/5071289/18026480/50569ae8-6c59-11e6-89f8-de2a2a9f876a.png)

**Comment by elextr** [comment]
Sure if somebody wants to add `%b` to the [statusbar placeholders](http://www.geany.org/manual/current/index.html#statusbar-templates) then you can add it to your statusbar in your preferred position.

**Comment by psrafo** [comment]
Thank you for response.

I just noticed, I can select all content of file, with CTRL+A, and look on "sel" value in statusbar, it's equivalent of my need.
