### ISSUE TITLE
Keybinding 'Switch to Message Window' problem

### ISSUE THREAD

**Issue by gcz1** [geany/geany#1198]
If the message window is showing the Terminal section then pressing the key which is bound to 'Switch to Message Window' from the editor window produces the error messages:

(geany:10502): GLib-GObject-WARNING **: invalid cast from 'GtkHBox' to 'GtkBin'

(geany:10502): Gtk-CRITICAL **: IA__gtk_bin_get_child: assertion 'GTK_IS_BIN (bin)' failed

(geany:10502): Gtk-CRITICAL **: IA__gtk_widget_grab_focus: assertion 'GTK_IS_WIDGET (widget)' failed

and no switch of windows occurs. If the message window is showing the Scribble section then the bound keys works as intended.

O/S is Fedora 23 on x86_64
Version is geany 1.28 (built on 2016-07-11 with GTK 2.24.30, GLib 2.46.2)

**Comment by elextr** [comment]
Confirmed with current git.
