### ISSUE TITLE
Problems with text "Search for:" field in "Replace" pop up

### ISSUE THREAD

**Issue by pwil3058** [geany/geany#1204]
Using Geany 1.28 on Korora 24 (Fedora 24 derivative) under Cinnamon 3.0.7 I'm experiencing strange problems with the text in the "Search for:" field in the "Replace" pop up that aren't show stoppers but are quite annoying.

At the end of a search that is unsuccessful this field is cleared and then becomes unusable in that I can't edit text in the field, paste into the field or restore text using the drop down list of previous searches.  This can be quite annoying if one is trying to do a search with a complex regular expression which isn't quite right yet and needs testing and editing/refinement.

Closing the pop up and starting again yields a working pop up again so all is not lost.

This behaviour has only started recently and I have not noticed it before.

However, out of curiosity, I checked the equivalent field in the "Find" pop up and found the same problem is occurring there.

**Comment by elextr** [comment]
Versions of GTK? Is this #1135?

**Comment by elextr** [comment]
@pwil3058 you would have been better commenting here not on the closed issue #1135.

Can you try building from the latest Git version that contains the fix to see if it fixes your issue?  There is a nightly tarball that minimises the build dependencies you need.

**Comment by pwil3058** [comment]
I'll give it a go.

**Comment by elextr** [comment]
On 3 September 2016 at 10:26, Peter Williams <notifications@github.com>
wrote:

> I'll give it a go.
>

​Don't forget you have to manually select --enable-gtk3 to the configure.​

If you untared the tarball into /some/dir giving /some/dir/geany adding
--prefix=/some/dir to the configure as well will allow you to install in
/some/dir and not touch your system install

**Comment by pwil3058** [comment]
When I do:

./configure

I get "No such file or directory" so things aren't going well.

Peter

**Comment by elextr** [comment]
did you do that inside the geany directory that was created by untaring the tarball?

**Comment by pwil3058** [comment]
OK, I figured out that I need autoconf etc.  So installed them and ran 
./autogen.sh and started installing the libraries that it complained 
about but ran into a problem with glib.  It kept complaining about 
needing glib even after I installed it so I installed glib-devel as well 
but it still complained.  I did the same with glibc in case it was a 
package name error but still no joy.

So I'm more or less stymied.
Peter
PS This experience has reinforced my belief the PyGObject is the best 
way to do GUIs as it hides all these difficult setup issues :-)

**Comment by pwil3058** [comment]
No, I did in the geany.git directory that I got by doing a git clone.

Peter

**Comment by elextr** [comment]
On 3 September 2016 at 10:51, Peter Williams <notifications@github.com>
wrote:

> No, I did in the geany.git directory that I got by doing a git clone.
>

​Oh well, ok, then yeah you need to do autogen.sh first as you found.  The
tarball has some things done for you.

RE glib did you put --enable-gtk3 on the configure?  As I said the default
is gtk2.​

**Comment by pwil3058** [comment]
I haven't got that far yet.  It keeps failing looking for glib even 
though I have both glib and glib-devel (1.2.10) installed.

Peter

**Comment by codebrainz** [comment]
What is the exact message it prints? What command are you running exactly when the error occurs?

**Comment by codebrainz** [comment]
Note also that `autogen.sh` will forward arguments to `configure` script which it calls automatically, so `./autogen.sh --prefix=/some/where --enable-gtk3` or whichever options you want.

**Comment by pwil3058** [comment]
~/.../GITHUB/geany.git $ sudo dnf install glib
[sudo] password for peter:
Last metadata expiration check: 0:39:04 ago on Sat Sep  3 10:13:11 2016.
Package glib-1:1.2.10-47.fc24.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
~/.../GITHUB/geany.git $ sudo dnf install glib-devel
Last metadata expiration check: 0:42:21 ago on Sat Sep  3 10:13:11 2016.
Package glib-devel-1:1.2.10-47.fc24.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
~/.../GITHUB/geany.git $ ./autogen.sh

**Error**: You must have `glib' installed.
You can get it from: ftp://ftp.gtk.org/pub/gtk
~/.../GITHUB/geany.git $ ./autogen.sh --enable-gtk3

**Error**: You must have `glib' installed.
You can get it from: ftp://ftp.gtk.org/pub/gtk

**Comment by codebrainz** [comment]
GLib 1.2 is something like 17 years old. I think you need at least 2.38 or so.

**Comment by codebrainz** [comment]
Try glib2-devel.

**Comment by elextr** [comment]
@pwil3058 where did you get the versions you posted in #1135?  The glib and gtk versions Geany is using are shown near the top of the menu->help->debug messages.  Can you post that line (looks like `11:16:07: Geany INFO		: GTK 3.18.9, GLib 2.48.1`)

**Comment by pwil3058** [comment]
From dnf. From geany I get:

11:11:26: Geany INFO		: Geany 1.28, en_AU.utf8
11:11:26: Geany INFO		: GTK 2.24.30, GLib 2.48.2

**Comment by elextr** [comment]
OK, your problem is nothing to do with #1135, thats a GTK3 problem IIUC (@b4n correct?).  So no need to make geany I don't think.

Your geany is built with gtk2.

It may be something to do with your theme, can you try a different one or two?

**Comment by pwil3058** [comment]
I would say that it's either both a Gtk3 and Gtk2 problem or neither as 
the symptoms are identical for me as they are for #1135.

My attempts to build are still failing as your auto configure stuff 
can't find gtk+-3.0 on my system even though it's there.  I tried 
without the --enable-gtk3 option  and after in installed gtk2-lib it 
seems to be building.

I guess because they install packages that use both gtk+-2.0 and 
gkt+-30, Fedora installs both of these versions of gtk+ (and even 
provide version 1 as an optional package) using the names gtk2 and gtk3 
(and gtk) respectively.  Can your scripts handle that?

Peter
PS I actually prefer gtk2 programs to gtk3 as the interface has a better 
appearance IMHO but in order to make GUIs using Python3 im switching to 
PyGObject (which is gtk3) so I guess that I'll have to get used to it.

**Comment by pwil3058** [comment]
OK.  Built successfully against gtk2 and installed in /usr/local :-)

Perfunctory tests (usually the best you can expect for a GUI) indicate 
that the problem is indeed fixed :-).  I'll keep this installed and use 
it as my default for the time being in order to test it more extensively.

Thanks
Peter

**Comment by elextr** [comment]
Ok, neat, thanks for testing, that fix will be in 1.29 when its released in a month or so.

**Comment by b4n** [comment]
> OK, your problem is nothing to do with #1135, thats a GTK3 problem IIUC (@b4n correct?). 

No, it does affect GTK2 only actually.  The GTK3 part of the fix is merely for the selection to be custom-colored again in >3.20, but it wouldn't be a problem unless the theme's selection background was white anyway.

**Comment by elextr** [comment]
@b4n, yeah, ok, thats visible when I read the actual patch
