### ISSUE TITLE
Md5 sum in status bar

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#1208]
Please consider adding the current md5 sum of the file being editted in the status bar.  Thanks!

**Comment by b4n** [comment]
No.

Why would it be useful to compute a dynamic checksum of the current buffer?  If it is, someone should likely write a plugin because it doesn't seem like a feature useful enough to the majority to add it to the core.

However, feel free to explain your use case, etc, maybe I'm wrong.
