### ISSUE TITLE
Typo in german translation

### ISSUE THREAD

**Issue by Heihon** [geany/geany#1219]
Geany 1.28 Release (Windows and Linux) and also Geany 1.29 "Jowar" (Windows)

"Document/Set Lineend/Set to CR/LF and convert"

is in german translation
"Dokument/Zeilenenden festlegen/Auf CR/LF setzen und umwandeln (Winows)"
should be
"Dokument/Zeilenenden festlegen/Auf CR/LF setzen und umwandeln (Windows)"

**Comment by b4n** [comment]
Already fixed by #1167, but thanks for reporting

**Comment by Heihon** [comment]
Sorry for the noise. I did search in Issues but didn't search in Pull requests.
I am not at all familiar with the Geany Nightly build process, but I assumed that merged Pull requests in branch master should be reflected in the Geany Nightly Build.
I saw the fixed file po/de.po in branch master, but the typo is still in Geany Nightly.
