### ISSUE TITLE
Geany hangs up when clicking 'replace and find' button in 'replace' dialog while the 'end of document' dialog is open

### ISSUE THREAD

**Issue by orwell96** [geany/geany#1232]
geany 1.24.1 (kompiliert am 2014-04-19 mit GTK 2.24.23, GLib 2.40.0)
OS: antix 16 (debian, no systemd)

to reproduce:
- open any file
- open 'replace' dialog
- enter something and keep on replacing until the '... not found, restart search from beginning?' dialog appers
- DON'T close that dialog but click again on 'replace and find'
  -> geany hangs up and does not accept any inputs, but painting still works, and fortunately it still reacts to external SIGTERMs. Unsaved progress is lost.

**Comment by elextr** [comment]
Doesn't hang with latest Git, but the wrap search dialog is modal, nothing will work until it is dismissed. 

That hasn't confused you?

**Comment by orwell96** [comment]
Seems to be issue of window manager then

**Comment by LarsGit223** [comment]
@orwell96: I also cannot reproduce this. Any news? Can this be closed?

**Comment by elextr** [comment]
No communication for a year, closed
