### ISSUE TITLE
Syntax Highlighting: Using > as comment_single not working

### ISSUE THREAD

**Issue by mathiasbockwoldt** [geany/geany#1240]
I wanted to build a minimal syntax highlighting for fasta files. Such files are used commonly in biology/bioinformatics and may look like this:

```
>Description of first element
TAGCGACTACGACTACGATCAGCATCTACGAT

>Description of second element
TGAGCTACGACGTGAGCGGGGAGCGGCGCCTAG
```

I wanted to highlight the description lines and thought that marking it as "comment" should work. However, it looks like it is not possible to use `>` as character for a comment.

/home/myuser/.config/geany/filedefs/filetypes.Fasta.conf:
```
[styling=Conf]

[settings]
lexer_filetype=Conf
extension=fasta

comment_single=>
```

The `filetype_extensions.conf` was adjusted accordingly and the *.fasta files are recognized as Fasta files according to the menu `Document` -> `Set filetype`

This does not work as intended. Lines starting with `#` or `;` are highlighted as comments, but lines starting with `>` are not.

Did I do anything wrong? Could you please help me with this (seemingly simple) issue?

**Comment by elextr** [comment]
The `comment_single`, `comment_open` and `comment_close` settings only control the `menu->edit->format->comment ...` commands.  They do not affect the syntax lexing, its coded in the properties lexer in C++ to use `#`, `;`, `!`.  The syntax lexing is part of the [Scintilla project](www.scintilla.org) which we simply use.

You could ask on Scintilla that it be made a property of the properties lexer as well as being coded.

**Comment by mathiasbockwoldt** [comment]
OK, thank you! I will see what I can do at Scintilla.
