### ISSUE TITLE
The blank space to the left of the line numbers

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#1247]
![numberspacing](https://cloud.githubusercontent.com/assets/7548378/18925682/d83a5708-85ac-11e6-8838-1bc11b24e47a.png)

Please consider removing the blank space to the left of the line numbers.  Thanks!

**Comment by b4n** [comment]
I don't see that here.  But how many lines does your file have?  The line number margin is set as wide as necessary to display any of the line numbers in the file.  Your screenshot looks just like would a file with at least 1000 lines, perhaps 10000.

Otherwise, maybe you have a plugin that adds extra margin/space?  Could you try with a clean configuration, e.g. `geany -c /tmp/tempconf`?

**Comment by philiprbrenan** [comment]
The problem only occurs in files with lots of lines - the largest line number is used to determine the width of this area as can be seen by starting with a window with one line in it and duplicating it 1000 times (very easy to do in Geany with Ctrl-D). In files that do have a large number of lines say 100,001 lines, then most lines will have at least one redundant space and if one tends to  work at the top of the file most of the time there are 4 redundant spaces in this area.

**Comment by b4n** [comment]
The only way then would be to change the width of that margin depending on which lines are shown, which is likely to be annoying behavior when near a boundary (e.g. going up/down a line could shift the whole display to the left).

IMO this is at most a feature request, and I'd be tempted to close as WONTFIX.  But maybe someone else would find this important enough to come up with a patch or a plugin that changes that (if it's a core patch, if would likely need a preference).

**Comment by elextr** [comment]
Scintilla does not allow variable margin widths, it is set for the entire buffer.  If the space before the number is removed it will have to be put back somewhere else to keep alignment of the text.

Agree with @b4n this is not a sensible change.

**Comment by codebrainz** [comment]
> The only way then would be to change the width of that margin depending on which lines are shown, which is likely to be annoying behavior when near a boundary

+1. Even when going from 9 to 10 lines or 999 to 1000 lines I find the automatic adjustment distracting, it would much more so if it happened while scrolling.

Moreover, in terse languages like Perl, I would imagine a 100,000 line file would be extremely rare (unless auto-generated or something).

**Comment by codebrainz** [comment]
> Scintilla does not allow variable margin widths, it is set for the entire buffer.

Actually scintilla doesn't handle any margin widths at all, leaving it entirely up to the application. Geany just follows the approach recommended in the Scintilla documentation and that taken by other (non-Scintilla) editors.

**Comment by stepaniuk** [comment]
What about this:

![screenshot from 2018-01-19 23-12](https://user-images.githubusercontent.com/24701640/35172965-6711f4ac-fd72-11e7-9739-d319de5930ca.png)

**Comment by codebrainz** [comment]
@stepaniuk I think it's from [the underscore here](https://github.com/geany/geany/blob/1.32.0/src/sciwrappers.c#L107). My guess would be that it was added to allow for using variable-width fonts or such.

**Comment by elextr** [comment]
I have the sidebar on the left and visible, then the space @stepaniuk points to is the resize handle, it seems to only be "space" when the sidebar is right or hidden, so possibly its then the pane border as that edge of the edit pane is now on the outside of the pane?

**Comment by stepaniuk** [comment]
![screenshot from 2018-01-20 11-27-45](https://user-images.githubusercontent.com/24701640/35181995-12b72c98-fdd5-11e7-8c19-82391296ca65.png)

**Comment by elextr** [comment]
Clearly theme dependent
![screenshot from 2018-01-20 19-33-15](https://user-images.githubusercontent.com/811085/35182050-2bf7278c-fe19-11e7-8f87-893d2661bf12.png)
