### ISSUE TITLE
The space to the right of the line numbers takes up a lot of space

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#1248]
![numberspacing](https://cloud.githubusercontent.com/assets/7548378/18927300/43ac0c4c-85b3-11e6-98f3-f35943a0fa70.png)

Please consider removing the space to the right of the line numbers as most of the time it is not used.  The presence of a bookmark could be shown much more efficiently by colorizing or bolding or underlining the line number. 

 Thanks!

**Comment by b4n** [comment]
Display->Show marker margin (also available in the Editor tab in the preferences)
