### ISSUE TITLE
Can't apply bold font in CentOS 7

### ISSUE THREAD

**Issue by subhammridha** [geany/geany#1250]
Changing the default font from 'something.regular' to 'something.bold' has no effect. This happens in any font that I choose.

**Comment by elextr** [comment]
Selecting a font only selects the family and size.  The buffer styling controls the face (regular, bold, italic).

**Comment by codebrainz** [comment]
A workaround for this bug is to create a separate colour scheme and setting each style to bold. I do this for a few of my most used colour schemes.

**Comment by codebrainz** [comment]
Similar bugs related to the GUI letting you select options that do not work:
About the Font Style as well: https://github.com/geany/geany/issues/608
About the Font Size: https://github.com/geany/geany/issues/772 and https://github.com/geany/geany/issues/703

**Comment by subhammridha** [comment]
Right. Thanks by the way.
