### ISSUE TITLE
text content disappeared after I resizing the window

### ISSUE THREAD

**Issue by buchten** [geany/geany#1254]
I typed somthing in geany. Then I resized the window, the content disappeard!. However, they show up again after I maximizing the window. It's Geany 1.23.1 in Ubuntu 14.04.

**Comment by elextr** [comment]
Unfortunately 1.23.1 is over three years old and not supported any more.  Can you try with a more modern version?

**Comment by buchten** [comment]
I re-installed it with version 1.28, but the problem keeps coming up

**Comment by elextr** [comment]
ok, what versions of Glib and GTK is it using (menu->help->debug messages near the top) and what desktop are you using?

**Comment by buchten** [comment]
GTK 2.24.23,  GLib 2.40.2, unity 7.2.6

**Comment by buchten** [comment]
OK, I found the problem. Just go to VMware's "virtual machine settings-hardware-display", and uncheck "accelerate 3D graphics".
