### ISSUE TITLE
Spawn tests incorrect value?

### ISSUE THREAD

**Issue by elextr** [geany/geany#1256]
In `spawn.c` [here](https://github.com/geany/geany/blob/master/src/spawn.c#L1158) condition is tested against `G_IO_FAILURE` but [this](https://developer.gnome.org/glib/stable/glib-IO-Channels.html#GIOCondition) does not list that as one of the values.

Instead I believe the return from the `g_io_channel_write_chars()` should be checked or the `error` used if more precision is needed.

Thoughts?

**Comment by codebrainz** [comment]
It's just a [poorly named local macro](https://github.com/geany/geany/blob/1.28.0/src/spawn.c#L100).

**Comment by elextr** [comment]
Quick change it to `SPAWN_IO_FAILURE` or the wrath of G* will descend on Geany, the use of the `G_` namespace is completely reserved for them :)

Still should check the returns better though.

**Comment by codebrainz** [comment]
Agree it should be renamed. Obviously it's confusing if it fooled you and I (until I googled for that identifier and found matches for geany's spawn code) ... also the G* wrath.
