### ISSUE TITLE
Geany 1.28 takes a lot of time to open on macOS Sierra

### ISSUE THREAD

**Issue by ugurcanpolat** [geany/geany#1277]
While Geany was opening up in about 1-2 seconds on El Capitan, it takes for about 5-6 seconds to open up on Sierra.

**Comment by ugurcanpolat** [comment]
I've just updated to 1.29, there are no improvements.

**Comment by techee** [comment]
Sorry, I didn't notice you opened this bug until now.

I've seen something similar and frankly have no idea what the reason could be. It doesn't seem to be CPU-bound as CPU doesn't seem to be used much during start. Neither anything I/O-intensive seems to happen. I also thought it might be related to signature verification but I get the same times also without signing the binary.

Assigning to myself though no idea what to do about it.

**Comment by eht16** [comment]
Are plugins enabled? Maybe some Webkit-enabled plugin tries to do some network I/O and fail or timeout in some way?

On Windows, there is a noticeable delay when loading any Webkit-enabled plugin whereas there it seems to be just loading the libraries which needs CPU time (and so probably not the same issue as here).

**Comment by techee** [comment]
No, this also happens without any plugins activated. Also the same binary works fine on previous versions of OS X without any delay (have older versions of OS X in virtual machines).

**Comment by eht16** [comment]
Ok, then I'm out of ideas as well :(.

**Comment by techee** [comment]
Alright, just tried to put some traces into Geany and it seems to have something to do with the socket that Geany uses to open an existing instance if it's already running - when I remove the code,  it starts faster. It's also something I noticed on the latest macOS release that Geany always opens a new instance instead of existing instance so there seems to be something broken with the socket.

I'll investigate more.

**Comment by techee** [comment]
OK, some more info: it's gdk_display_get_name() here

https://github.com/geany/geany/blob/master/src/socket.c#L288

which is slow. After commenting-out and leaving NODISPLAY, it starts fast. I'll try to put traces into GDK if I find something. In the worst case the gdk_display_get_name() call could just be ifdefed on OS X.

**Comment by techee** [comment]
I asked on gtk-osx list:

https://mail.gnome.org/archives/gtk-osx-users-list/2017-February/msg00000.html

**Comment by techee** [comment]
For reference, here's the GTK bug I created for this issue:

https://bugzilla.gnome.org/show_bug.cgi?id=778754
