### ISSUE TITLE
Status bar showing scope: unknown unexpectedly

### ISSUE THREAD

**Issue by elextr** [geany/geany#1279]
As pointed out by @kugel- on IRC some functions show scope "unknown" when the cursor is inside them, but they would be expected to show the function name, eg `document_open_file()`

I found it seems to be if the function declaration is more than one line, the scope shows "unknown" when the cursor is in the function body, change the declaration to one line and the scope shows correctly.

**Comment by kugel-** [comment]
> it seems to be if the function declaration is more than one line

Apparently only if the function parameters are split. Other functions that have the return value on a separate line are fine.

@techee Any idea?

**Comment by b4n** [comment]
As mentioned on IRC, I guess it's because Scintilla now folds on `()`, which probably confuses the algorithm.
