### ISSUE TITLE
Unexpected "invalid character in identifier"

### ISSUE THREAD

**Issue by Arie-vw** [geany/geany#1290]
Hi,
running Geany 1.28 on Windows 10 (latest updates applied).

When running a Python script, Geany stumbles upon the double quote character:

 File "testen.py", line 1
    x = ¨abc¨
                 ^
SyntaxError: invalid character in identifier
Press any key to continue . . .

I use a US International keyboard with dead keys, so I type:
   1. the double quote
   2. a space to make that double quote visible

Also strange that it signals an error on the SECOND double quote ...

**Comment by Arie-vw** [comment]
Found just out it is a long standing GTK buig:  https://bugzilla.gnome.org/show_bug.cgi?id=569581

**Comment by elextr** [comment]
You are aware that you have generated the diaresis character not the ASCII quotes character that delimits a Python string?  As is noted in the second post, input methods are beyond Geany's control.

The diaresis is of course invalid Python, note that Geany does not stumble over it, Python does and its up to it where it indicates an error.

**Comment by LarsGit223** [comment]
IMHO this can be closed.
