### ISSUE TITLE
"not found" hides text in find dialog

### ISSUE THREAD

**Issue by grighi** [geany/geany#1296]
It seems that whenever I search for some text that is not in the document, the text in the Find dialog disappears and I need to reopen the application to have text showing in the box again. 

The text is there because I can see it when I highlight, but otherwise it is not visible. Am I missing something?

**Comment by elextr** [comment]
Glib and GTK version Geany uses? (help->debug messages) and you are sure its not #1135?

**Comment by grighi** [comment]
I'm pretty sure that's it. Sorry I didn't find it earlier.

GTK 2.24.31, GLib 2.50.1
