### ISSUE TITLE
How to use Geany?

### ISSUE THREAD

**Issue by mrkaban** [geany/geany#1299]
How to use Geany?

Download and install the following:
geany-1.28_setup.ehe
fpc-3.0.0.i386-win32.cross.x86_64-win64.ehe

and I tried to compile

program untitled;

uses crt;
var i: byte;

BEGIN

writeln ( 'Hello, World!');
END.

In the tab following status messages:
12:59:30: It Geany 1.28.
12:59:30: A new file "without a name".
13:00:00: The file is closed without a name.
13:00:00: A new file "without imeni.pas".
13:00:22: C File: \ Users \ Alex \ the Desktop \ 111 \ without imeni.pas saved.
13:00:52: C File: \ Users \ Alex \ the Desktop \ 111 \ without imeni.pas saved.
13:00:52: The process has failed (Invalid specified folder name)
13:01:06: The process has failed (Invalid specified folder name)

I tried on three different PCs running Windows 7 x64. Everywhere one and the same.

**Comment by elextr** [comment]
With Geany 1.28 no paths to any files may contain non-ASCII characters.  #1095 is an attempt to fix it, but I don't know if it will make it into 1.29 in two days time.

**Comment by mrkaban** [comment]
Thanks for the answer!

Moved the file, he is now here C: \ 111 \ 1.pas

but still it does not work ...

13:35:06: It Geany 1.28.
13:35:06: Unable to load one or more files of the session.
13:35:06: File C: \ 111 \ 1.pas open (1).
13:35:27: C File: \ 111 \ 1.pas saved.
13:35:27: The process has failed (Can not find the file specified)


Or should I wait for the next version of IDE?

**Comment by b4n** [comment]
Do you have the `fpc` in your `PATH`?  If not, you'll need to alter Geany's build command (*Tools → Set Build Commands* when looking at a Pascal file) to point to the full location of the `fpc` executable.
Finally, you probably know it but you need to compile the program before running it, so if you were trying to *Execute* before *Build*ing, it won't work as the executable won't exist yet.

**Comment by mrkaban** [comment]
Thanks for the answer!

in the "Tools" I did not find such an item, in the "build" found. In the command to Pascal in the item "compile" in the working directory specified "C: \ FPC \ 3.0.0 \ bin \ i386-win32 \".

Here is the log.

21:18:52: It Geany 1.28.
21:18:53: File C: \ 111 \ 1.pas open (1).
21:19:16: The configuration files are loaded again.
21:20:37: A new file "C: \ Users \ Alex \ AppData \ Roaming \ geany \ snippets.conf".
21:21:09: C File: \ Users \ Alex \ AppData \ Roaming \ geany \ snippets.conf closed.
21:21:58: The process has failed (Can not find the file specified)
21:25:55: The process has failed (Can not find the file specified)

**Comment by codebrainz** [comment]
Closing due to age, now old Geany version, and such a core feature people use often.

@mrkaban feel free to re-open if you still haven't solved this.
