### ISSUE TITLE
Port Windows installer to NSIS 3.x

### ISSUE THREAD

**Issue by eht16** [geany/geany#1302]
NSIS 3.0 is out for a while and there are MSYS2 packages for NSIS 3.x which would make the release process on Windows easier.

**Comment by elextr** [comment]
@eht16 is this gonna be your last minute windows change for 1.30 or should we move the milestone to 1.31? :wink:

**Comment by eht16** [comment]
As tempting as it is, I think I can resist this time :).

**Comment by kugel-** [comment]
@eht16 What about this?

**Comment by eht16** [comment]
We should still port the installer to NSIS 3. This would also ease creating full installers from the nightly builds as NSIS 3 is available as Debian package (not tested but might work to build full installers from nightly builds).

Though it is unlikely I will work on this myself in the next months.

**Comment by b4n** [comment]
@eht16 should I move that to 1.35 milestone?

**Comment by eht16** [comment]
Did it myself, thanks for reminding me.

**Comment by b4n** [comment]
Once more? :)

**Comment by elextr** [comment]
Just move it to Geany 5.0 :-P

**Comment by eht16** [comment]
Come on, this is only 2.5 years old :)

I still like to get this done (not necessarily by myself) as then we can build the installer from within the MSYS2 environment which eases the release process. And it might even help to cross-build the installer in some more far future.

**Comment by b4n** [comment]
Sound great, but I'll still move it one milestone forward :)

**Comment by eht16** [comment]
@b4n I know you didn't believe this will ever happen but here we are: #2181.

The migration of the installer script was way easier than expected, I just had to start doing it :).
As a bonus, I added a script to update the keywords in the NSIS filetype definition.

Sometime before 1.36, I will update the G-P installer as well.
