### ISSUE TITLE
Geany snd ESLint

### ISSUE THREAD

**Issue by NTMan** [geany/geany#1304]
I try use ESLint as linter for Javascript files.

I am using this regular expression "(.+) ([0-9]+):([0-9]+)" for highlight error lines, but it not working for me.

Expected behaviour when I click on error message in compiler tab it must navigate me to related line in editor area.

Actual behaviour nothing happens.

![15 11 2016 15-28-55-613](https://cloud.githubusercontent.com/assets/200750/20302574/a2bc33d6-ab49-11e6-9518-14cf89097d10.png)

**Comment by elextr** [comment]
The problem appears to be that the error messages from the linter do not have the filename on the same line as the error message.  The error expression is only applied to one line at a time, so it doesn't recognise and lines as errors, so they are not clickable.

The only thing you can do is to see if there is an option to have ESLint place the messages all on one line.

**Comment by NTMan** [comment]
Ok, I found this option:
"eslint.cmd" -f compact "%f"

How reset to defaut "Error regular expression"?
