### ISSUE TITLE
Regression: No syntax highlighting for bash lists with one item

### ISSUE THREAD

**Issue by radioactiveman** [geany/geany#1308]
Bash lists with only one string item are not applying syntax highlighting.
It worked correctly with an older version of Geany, but I cannot say when this regression was introduced.

Example:
```
#!/bin/bash

var1=('foo')
var2=('foo: works')
var3=('foo', 'bar')
```
Expected syntax highlighting:
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/audacious
See line 13, 16-20, 22.

System information:
* Arch Linux
* Geany 1.29

**Comment by radioactiveman** [comment]
The issue persists with Version 1.30.1.

**Comment by elextr** [comment]
Highlighting is provided by the editing widget Geany uses from the Scintilla project.  Please report the issue [there](https://sourceforge.net/p/scintilla/bugs/).

Though I am not sure its a bug, being assigned to a variable, it can also correctly be considered an expression in parens not a command list as I read the bash manual, so it should not be list highlighted.

**Comment by radioactiveman** [comment]
Thank you, reported as https://sourceforge.net/p/scintilla/bugs/1944/. Feel free to close this issue.

**Comment by elextr** [comment]
Thanks for reporting back the Scintilla issue, we normally leave issues open until we see what Scintilla does.

**Comment by radioactiveman** [comment]
Fixed upstream: https://sourceforge.net/p/scintilla/code/ci/7619719dd43233dbf9f440cfbf5e4d4a48fe552d/

Do you plan to update Scintilla with the next release?

**Comment by elextr** [comment]
If there is a Scintilla release in time it should be included.

**Comment by radioactiveman** [comment]
Version 3.7.5 of Scintilla has been released now.

**Comment by elextr** [comment]
Yes, when someone has time to import the new version it will be added to Geany.
