### ISSUE TITLE
geany-plugin-git-changebar not functionnal

### ISSUE THREAD

**Issue by jallary** [geany/geany#1309]
Since last upgrade on Debian sid, plugin geany-plugin-git-changebar is not working anymore.

    geany 1.29 (construit le Nov 16 2016 avec GTK 2.24.31, GLib 2.50.2)
    ii  geany-plugin-git-changebar            1.28+dfsg-1                        amd64

**Comment by b4n** [comment]
It's been fixed on Geany-Plugins' side in the last release 1.29.  See [Debian bug #844745](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=844745) and https://github.com/geany/geany-plugins/issues/493.

Also, this repository is for Geany issues, and Git-Changebar is part of [geany-plugins](https://github.com/geany/geany-plugins/).
