### ISSUE TITLE
Geany does not use native "file opener" for Mac

### ISSUE THREAD

**Issue by thewhitetulip** [geany/geany#1310]
Hello!

I had totally forgot that Geany is available for Mac. The small issue which I am facing is that the "open file" dialog does not show me a native file opener dialog. The reason I want the native file opener dialog is that I have bookmarked a lot of things in Finder and I have to dig into a lot of folders to find the folder I want to open with Geany.

Plus, nice work! I was introduced to Geany few years ago, and this being an IDE takes less RAM + battery than normal text editors 👍

**Comment by techee** [comment]
Fixed by https://github.com/geany/geany/pull/3861.
