### ISSUE TITLE
Support for the Go language

### ISSUE THREAD

**Issue by thewhitetulip** [geany/geany#1312]
I do not see support for Go language. I can help in adding support for the same. Please let me know

**Comment by elextr** [comment]
Geany has built-in Go filetype support.  Not knowing Go I can't say how good it is but it recognises the `.go` extension as a Go filetype.

**Comment by thewhitetulip** [comment]
Okay, I was actually asking about "create file" portion, we do not have a Go file there. Plus is there a Go plugin for geany? I wasn't able to find it on the plugins website.

**Comment by elextr** [comment]
No there is no Go plugin, languages are not plugins in Geany they are either built-in (as is Go) or based on a built-in language (for example Clojure is based on the built-in Lisp).

You can write your own template file and have it appear in the create menu, see the manual.  You can then make a PR to add it to Geany, see the HACKING file for further info.

**Comment by thewhitetulip** [comment]
Yes, I checked the Go support. It is great. Just one more question. What do I have to do to get auto complete for Go?
