### ISSUE TITLE
Failed to identify functions marked with __THROW.

### ISSUE THREAD

**Issue by nemaakhilesh** [geany/geany#1314]
geany version - 1.29

Most of the function declarations in glibc header files are marked with __THROW. 
Geany cannot identify or incorrectly identifies these functions. 
(sample files /usr/include/pthread.h, /usr/include/unistd.h).
![geany](https://cloud.githubusercontent.com/assets/16345956/20472456/5465619a-affd-11e6-8d28-04c838f59374.png)

**Comment by elextr** [comment]
The online parsing does not apply macro substitutions, so macros used to modify the language syntax can confuse it.

For system files like pthread.h or unistd.h it is recommended to make offline global tags using the C pre-processor to generate symbols. (see the manual, and check the wiki to be sure tags havn't already been produced).

**Comment by b4n** [comment]
You can use [ignore.tags](https://www.geany.org/manual/#c-ignore-tags) to mitigate the issue, it's here for just that.
