### ISSUE TITLE
Wrap Lines In Overview Plugin

### ISSUE THREAD

**Issue by 483768903474589** [geany/geany#1319]
Hi

The lines do not wrap in the Overview plugin when line wrapping is enabled in the editor. Would making the lines wrap in the Overview be possible to implement?

I have the latest version of Geany.

Thanks
Fred

**Comment by b4n** [comment]
Moved to geany/geany-plugins#506: the Overview plugin is par of the Geany-Plugins package, not core Geany.

**Comment by 483768903474589** [comment]
@b4n

Thank you for looking into it.
