### ISSUE TITLE
GTK3: scrolling doesn't work

### ISSUE THREAD

**Issue by gyeben** [geany/geany#1320]
In the GTK3 version, scrolling in the code editor with a touchpad doesn't work.

**Comment by programmin1** [comment]
By "doesn't work" you mean it jumps 5 lines or so rather than scrolling fluidly like Gedit and other native GTK3 apps?

If so I agree, this is annoying and I hope Geany updates to using GTK3+ soon.

**Comment by elextr** [comment]
@programmin1 Geany already supports GTK3, note GTK3 and GTK3+ is the same thing, just many of us lazy people omit the +.

@gyeben some information would be helpful, what operating system and version, what versions of Geany, Glib and GTK from the top few lines of `Menu->help->debug messages` please.  Does the touchpad scrolling work for any other applications?

**Comment by b4n** [comment]
As @elextr said, we need more info.  And @programmin1 point might also be what you're referring to.

FWIW, scrolling with the touchpad on my laptop works just fine, just like does my mouse wheel on my desktop.  And yes it's with GTK3.

---
> @programmin1 Geany already supports GTK3, note GTK3 and GTK3+ is the same thing, just many of us lazy people omit the +.

Okay, let's nitpick : it's actually [GTK+](https://www.gtk.org/) 3 :)

**Comment by gyeben** [comment]
By "doesn't work" I mean that nothing happens when I try scrolling with the touchpad.

Geany 1.30 (git >= b29a973)
GTK 3.22.5, GLib 2.50.2

**Comment by gyeben** [comment]
By "doesn't work", I mean that nothing happens when I try scrolling with the touchpad in the code editor.
I'm using Gnome 3 with Wayland on Fedora 25 and I found out that my issue is somehow related to Wayland because if I run Geany with GDK_BACKEND set to x11, scrolling works fine.
I am using Geany 1.30 (git >= b29a973, built with GTK 3.22.5 and GLib 2.50.2).

**Comment by b4n** [comment]
Could you test whether SciTE works?  If it doesn't (I imagine it won't), it'll be a Scintilla issue that should be forwarded there.

**Comment by gyeben** [comment]
It seems like this is a Scintilla issue as I have the same problem with SciTE.

**Comment by zerocrates** [comment]
I encountered this same problem after switching to Wayland: touchpad scrolling fails, only for the editor widget.

Is there a bug filed against Scintilla I should be looking at, or does it need to be reported there still?

**Comment by elextr** [comment]
If you find a bug report on Scintilla or submit one yourself please post its ID here for tracking

**Comment by zerocrates** [comment]
I didn't see any issue that looked on point so I filed a new one: https://sourceforge.net/p/scintilla/bugs/1901/

**Comment by zerocrates** [comment]
This should be fixed in Scintilla 3.7.3.

**Comment by b4n** [comment]
Should be fixed in master (which imported Scintilla 3.7.3)
