### ISSUE TITLE
how i use SCLEX_AS?

### ISSUE THREAD

**Issue by Azq2** [geany/geany#1322]
https://github.com/geany/geany/blob/7ae1d031efe8dd1b967c89ee404ab6fb2172ec4c/scintilla/lexers/LexAsm.cxx#L466

I tried
```
lexer_filetype=As
```

but not working ;( (expect # as comments)

**Comment by elextr** [comment]
the filetype name is "ASM"

**Comment by b4n** [comment]
…but that uses `SCLEX_ASM`.  @Azq2 if you really want to use the `SCLEX_AS` lexer, you'll have to add a new builtin filetype to Geany, e.g. modify the source code.  AFAIK, the only difference between `SCLEX_ASM` and `SCLEX_AS` is that the former uses `;` for comments, and the latter `#`.
We'd probably accept a patch adding that ASM variant.

On a technical note, I wonder why the comment character isn't a lexer property on Scintilla's side… that would be easier for us.
