### ISSUE TITLE
Dismiss "Deleted from Disk" Infobar on Reload

### ISSUE THREAD

**Issue by codebrainz** [geany/geany#1330]
When an open document's file is deleted from disk the infobar pops up to let the user know. The infobar doesn't have a Reload option (which kind of makes sense). Often I'll have a generated file open which is frequently deleted and re-created from scratch, which of course triggers the infobar. I'll then generate the file and want to reload it in Geany so I press the Reload button. Doing this should dismiss/cancel the infobar that is effectively wrong now instead of having to press Cancel manually after reloading.

A further enhancement would be for Geany to detect the file is back on disk and switch the infobar out for the one notifying of a change on disk, which does have a Reload option and is also dismissed on reload.

**Comment by elextr** [comment]
> Doing this should dismiss/cancel the infobar that is effectively wrong now instead of having to press Cancel manually after reloading.

Makes sense.
