### ISSUE TITLE
Geany 1.29 crashes on OS X 10.10.5 when launched.

### ISSUE THREAD

**Issue by ccpetersen** [geany/geany#1335]
Code sig for libgeany invalid.  V1.28 is fine. Here's the crash report:

Process:               geany-bin [818]
Path:                  /Users/USER/Desktop/Geany.app/Contents/MacOS/geany
Identifier:            org.geany.geany
Version:               ???
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           geany-bin [818]
User ID:               501

Date/Time:             2016-12-09 11:33:23.953 -0700
OS Version:            Mac OS X 10.10.5 (14F2009)
Report Version:        11
Anonymous UUID:        3DAC015E-5E46-DA3E-255F-D863D3257A18

Sleep/Wake UUID:       AA9FB665-4373-4E9B-BEC4-077868495CD8

Time Awake Since Boot: 12000 seconds
Time Since Wake:       2300 seconds

Crashed Thread:        0

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Application Specific Information:
dyld: launch, loading dependent libraries
DYLD_LIBRARY_PATH=/Users/carl/Desktop/Geany.app/Contents/Resources/lib

Dyld Error Message:
  Library not loaded: @executable_path/../Resources/lib/libgeany.0.dylib
  Referenced from: /Users/USER/Desktop/Geany.app/Contents/MacOS/geany-bin
  Reason: no suitable image found.  Did find:
	/Users/carl/Desktop/Geany.app/Contents/Resources/lib/libgeany.0.dylib: code signature invalid for '/Users/carl/Desktop/Geany.app/Contents/Resources/lib/libgeany.0.dylib'

	/Users/carl/Desktop/Geany.app/Contents/MacOS/../Resources/lib/libgeany.0.dylib: code signature invalid for '/Users/carl/Desktop/Geany.app/Contents/MacOS/../Resources/lib/libgeany.0.dylib'

	/Users/carl/Desktop/Geany.app/Contents/MacOS/../Resources/lib/libgeany.0.dylib: code signature invalid for '/Users/carl/Desktop/Geany.app/Contents/MacOS/../Resources/lib/libgeany.0.dylib'

Binary Images:
    0x7fff6331f000 -     0x7fff6335592f  dyld (353.2.4) <708E385E-50C6-32A3-983C-42E97BEE4346> /usr/lib/dyld

Model: iMac7,1, BootROM IM71.007A.B03, 2 processors, Intel Core 2 Duo, 2.8 GHz, 6 GB, SMC 1.21f4
Graphics: ATI Radeon HD 2600 Pro, ATI,RadeonHD2600, PCIe, 256 MB
Memory Module: BANK 0/DIMM0, 4 GB, DDR2 SDRAM, 667 MHz, 0x7F7F7F7F7F9B0000, -
Memory Module: BANK 1/DIMM1, 2 GB, DDR2 SDRAM, 667 MHz, 0x7F7FBAFFFFFFFFFF, 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x88), Broadcom BCM43xx 1.0 (5.10.131.36.16)
Bluetooth: Version 4.3.6f4 17916, 3 services, 26 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en1
Serial ATA Device: OWC Mercury Electra 3G SSD, 480.1 GB
Parallel ATA Device: MATSHITADVD-R   UJ-85J
USB Device: My Book 1230
USB Device: Built-in iSight
USB Device: USB2.0 Hub
USB Device: CP2102 USB to UART Bridge Controller
USB Device: Bluetooth USB Host Controller
USB Device: IR Receiver
Thunderbolt Bus:

**Comment by techee** [comment]
@ccpetersen Does the crash happen also when your copy the binary under /Applications? (Apple is stricter about executing binaries outside /Applications, that said, this problem shouldn't happen as I believe I sign the binaries correctly).

Do you get the same problem with previous Geany OS X releases or is it 1.29 specific?

**Comment by ccpetersen** [comment]
Hi,

Version 1.28 works fine. V1.29 crashes whether launched from the Applications folder or outside of it. Same error in both cases. 

Here’s the relevant section when launched from with the Applications folder:

Dyld Error Message:
  Library not loaded: @executable_path/../Resources/lib/libgeany.0.dylib
  Referenced from: /Applications/Geany.app/Contents/MacOS/geany-bin
  Reason: no suitable image found.  Did find:
	/Applications/Geany.app/Contents/Resources/lib/libgeany.0.dylib: code signature invalid for '/Applications/Geany.app/Contents/Resources/lib/libgeany.0.dylib'

	/Applications/Geany.app/Contents/MacOS/../Resources/lib/libgeany.0.dylib: code signature invalid for '/Applications/Geany.app/Contents/MacOS/../Resources/lib/libgeany.0.dylib'

	/Applications/Geany.app/Contents/MacOS/../Resources/lib/libgeany.0.dylib: code signature invalid for '/Applications/Geany.app/Contents/MacOS/../Resources/lib/libgeany.0.dylib’

I can’t explain the “no suitable image found”

**Comment by techee** [comment]
Well, it complains about code signature - I'll have to check if I have the certificate installed correctly. Still strange it works for me and nobody else has complained so far.

**Comment by ccpetersen** [comment]
Just tried it on my laptop running 10.12.1 and it works fine.  Must be something with Yosemite (10.10) but I,m not sure what.

**Comment by techee** [comment]
Would you try

```
codesign --verify --deep --strict --verbose=2 /Applications/Geany.app
```

if it gives some strange results? It should simulate the signature verification process that happens during execution. I get

```
--prepared:/Applications/Geany.app/Contents/MacOS/geany-bin
--validated:/Applications/Geany.app/Contents/MacOS/geany-bin
/Applications/Geany.app: valid on disk
/Applications/Geany.app: satisfies its Designated Requirement
```

on my computer.

**Comment by ccpetersen** [comment]
I had to remove the ‘—strict’ option.  Must be a 10.10 thing.  Anyway here’s the output which looks sane but geany still crashes.  I did do a clean reinstall of 10.10.5 thinking I screwed something up but it didn’t change anything.

iMac:~ carl$ codesign --verify --deep  --verbose=2 /Applications/Geany.app
--prepared:/Applications/Geany.app/Contents/MacOS/geany-bin
--validated:/Applications/Geany.app/Contents/MacOS/geany-bin
/Applications/Geany.app: valid on disk
/Applications/Geany.app: satisfies its Designated Requirement
iMac:~ carl$

**Comment by techee** [comment]
Well, I tried to re-build the binaries from scratch in case something wrong happened during the last build and put them here

http://download.geany.org/snapshots/

The dmg with the _nosign extension contains Geany without any signature at all - it will probably work for you but to run it you'll have to right-click the .app and select Open after which it will permit you to run it.

It would be interesting to know if the new signed binary works or if you still get the same problem.

No other ideas really. There seem to have been many changes related to binary signatures in the last OS X releases, at least judging from

https://developer.apple.com/library/content/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG207

So each version makes slightly different checks.

**Comment by ccpetersen** [comment]
The new image gets us passed the library not loading issue, as you explained, but it now fails with

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000

and an extremely long crash report.

I tried going back to my macbook where everything worked and I booted it with 10.10 Yosemite just to see if it was somehow hardware related but geany 1.29 refused to run with the same library fault as before in the iMac.  Rebooting the macbook back to MacOS (10.12) and geany runs and everything is fine again.  I didn’t try your new image in the macbook.

Sorry I can’t be of more help.

**Comment by techee** [comment]
EXC_BAD_INSTRUCTION could mean the compiler used some instructions which aren't present on your machine but I saw this one also in other cases where it had nothing to do with it. I'm compiling with a newer version of XCode's LLVM than for the previous builds and it might be possible that it now defaults to newer processor instructions.

What's the model of the Mac with 10.10 and what CPU do you have? Maybe I could add some command-line parameters so it generates code for older processors.

**Comment by ccpetersen** [comment]
The machine is:

  Model Name:	iMac
  Model Identifier:	iMac7,1
  Processor Name:	Intel Core 2 Duo
  Processor Speed:	2.8 GHz
  Number of Processors:	1
  Total Number of Cores:	2
  L2 Cache:	4 MB
  Memory:	6 GB
  Bus Speed:	800 MHz
  Boot ROM Version:	IM71.007A.B03
  SMC Version (system):	1.21f4

Bear in mind that 1.29 runs perfectly will on my new Macbook Pro running the latest MacOS but fails if I boot the Macbook with an older (10.10) release of OS X . Go back to the MacOS and everything works again.

Just as an experiment I upgraded the iMac to 10.11.6 (El Capitan) and the current 1.29 release to see if it made any differents but it fails with the “EXC_BAD_INSTRUCTION”.  The signed library issue seems to be gone with the os upgrade.

**Comment by elextr** [comment]
On 13 December 2016 at 02:13, Carl Petersen <notifications@github.com>
wrote:

> The machine is:
>
> Model Name: iMac
> Model Identifier: iMac7,1
> Processor Name: Intel Core 2 Duo
> Processor Speed: 2.8 GHz
> Number of Processors: 1
> Total Number of Cores: 2
> L2 Cache: 4 MB
> Memory: 6 GB
> Bus Speed: 800 MHz
> Boot ROM Version: IM71.007A.B03
> SMC Version (system): 1.21f4
>
> Bear in mind that 1.29 runs perfectly will on my new Macbook Pro running
> the latest MacOS but fails if I boot the Macbook with an older (10.10)
> release of OS X . Go back to the MacOS and everything works again.
>
> Just as an experiment I upgraded the iMac to 10.11.6 (El Capitan) and the
> current 1.29 release to see if it made any differents but it fails with the
> “EXC_BAD_INSTRUCTION”. The signed library issue seems to be gone with the
> os upgrade.
>

​If I read Intels data right the core 2 duo didn't support SSE
instructions, but LLVM certainly uses that if it can to expand its register
set (even if it doesn't do streaming).  ​And it could be in Glib or GTK
which would use math more heavily than Geany would.

​
​
Jiří is there an option for generating plain vanilla 686 ​code?



>
>
> > On Dec 12, 2016, at 5:07 AM,
> ​​

**Comment by techee** [comment]
@elextr I originally thought it was because of the wrong instructions for the processor but as @ccpetersen said, even on the machine where it runs under 10.12 it doesn't run when 10.10 is booted. So it looks like something else is wrong, I just don't know what :-(.

By the way I support only 64-bit processors in the bundle - 386 Macs existed only very briefly (Apple used PowerPC processors before when 386 was common) and these are unsupported by Apple anyway now and it doesn't make much sense to make the binary twice as big because of them.

**Comment by techee** [comment]
@ccpetersen I re-uploaded the _nosign version compiled with different options - would you please try it? I believe it might work for you.

I also installed 10.10.5 into a virtual machine and can reproduce the signature verification issue - but so far no idea what could be wrong.

**Comment by ccpetersen** [comment]
YES, that works!!!  Thanks for all your hard work.  I hope you find out about the signature thing but that’s not a show stopper here.

Thanks again,

**Comment by techee** [comment]
For reference, these are bugs raised against the gtk-osx project related to this issue:

https://bugzilla.gnome.org/show_bug.cgi?id=776216
https://bugzilla.gnome.org/show_bug.cgi?id=776219
https://bugzilla.gnome.org/show_bug.cgi?id=776295

I've updated the instructions and made changes to the build here

https://github.com/geany/geany-osx

so the generated binaries should be usable on any OS X 10.6 or newer. I've also re-uploaded the binary here

http://download.geany.org/geany-1.29_osx.dmg

so everything should work now.

**Comment by ccpetersen** [comment]
Works great! Thanks again…
