### ISSUE TITLE
Symbols with non-ASCII Unicode names are not detected by "Symbols"

### ISSUE THREAD

**Issue by ioistired** [geany/geany#1337]
# Abstract
When naming a variable something that isn't ASCII, but is still a valid Python3 identifier, the variable doesn't show up in the symbols list.

### Test case:

```python
#!/usr/bin/env python3
# coding: utf-8

correct = bool()
对不对='对' if correct else '错'
```
Load up that file in Geany, then open the Symbols tab.

### What I expected to see

"correct" and "对不对" both show up in the Symbols list.

### What happened

Only "correct" shows up in the Symbols list.

## Extra info

1. <output>geany 1.27 (built on 2016-04-17 with GTK 2.24.30, GLib 2.48.0)<output>
2. OS: Ubuntu 16.04.1 LTS

**Comment by elextr** [comment]
Confirmed with latest git

**Comment by bmintz** [comment]
Furthermore, a symbol name containing non-ASCII symbols is cut off at the first one.

## Test case

```python
#!/usr/bin/env python3
# encoding: utf-8

def ackermann_péter(m, n):
	if m == 0: return n + 1
	elif m > 0 and n == 0: return ackermann_péter(m - 1, 1)
	elif m > 0 and n > 0: return ackermann_péter(m - 1, ackermann_péter(m, n - 1))
	else: raise ValueError("{name}({}, {}) is not defined.").format(__name__, m, n)
```

## Steps to reproduce

1. Type `acker` with autocomplete on.
2. Press <kbd>Enter</kbd>
3. Type a left paren "("

## Expected behavior

3. `ackermann_péter (m, n)` gets suggested

## Actual behavior

3. `ackermann_p (m, n)` gets suggested

**Comment by elextr** [comment]
This is a known problem with the [ctags](https://github.com/universal-ctags/ctags/search?q=unicode&type=Issues&utf8=%E2%9C%93) parsers.  As you can see there are various issues open about it, but no recognised solution.  (well it is after all **C**-tags and C doesn't allow non-ascii characters in identifiers).

**Comment by bmintz** [comment]
@elextr It seems that we actually use [Exuberant Ctags](https://sourceforge.net/projects/ctags/), which is no longer maintained.
[Universal Ctags](https://github.com/universal-ctags/ctags) supports UTF-8, [although not multi-byte characters such as Emoji](https://github.com/universal-ctags/ctags/issues/1275).

P.S. Issue #1337!!

**Comment by elextr** [comment]
@bmintz My link was to UCtags.  Geany actually uses its own copy initially forked from exuberant ctags.  During the period that ECtags was unmaintained the Geany copy has diverged, to the extent that c.c has several extra languages.  Some effort is underway to re-harmonise Geany and UCtags, see #1263, but is not complete.

> P.S. Issue #1337!!

This IS #1337???

**Comment by b4n** [comment]
> Some effort is underway to re-harmonise Geany and UCtags, see #1263, but is not complete.

Once it will, we'll be able to import the new Python parser which fixes several things, including this IIRC.
