### ISSUE TITLE
Python3 class code indentation not correct

### ISSUE THREAD

**Issue by PythonJim** [geany/geany#1343]
I was using Geany to write a python class with functions.  I created a test class, and got a compile error using <f8> indicating an indentation error.  When I looked at the file in IDLE3 the file displayed with identation errors saved by Geany, and found by Geany during compile, but not displayed on the edit screen , and not really fixable.  I have attached screen captures for information.  I am using Geany version 1.27, GTK 2.24.30, GLib 2.48.0
![idle3-1](https://cloud.githubusercontent.com/assets/24641368/21297867/979481f4-c53c-11e6-97f4-180884beeeec.png)
![idle3 compile error](https://cloud.githubusercontent.com/assets/24641368/21297869/a018496e-c53c-11e6-9b75-586cca01898f.png)
![geany](https://cloud.githubusercontent.com/assets/24641368/21297871/a7635664-c53c-11e6-85cf-8cf38a2d6c90.png)
![geany error log](https://cloud.githubusercontent.com/assets/24641368/21297875/afb039f4-c53c-11e6-9b30-d22bf9a254bc.png)

**Comment by elextr** [comment]
Don't mix tabs and spaces.  Don't use tabs at all in Python.  The default python filetype file says spaces, but you can override that by user settings, which you must have done.

To fix your broken file open it, set `Menu->Document->Indent type->spaces` and convert the nasty tabs you already have in the file to spaces `Menu->Document->Convert tabs to spaces`.

If you use other languages with different indentation rules set `Menu->Edit->Preferences->Editor->Indentation->detect type from file` so each will get the right type.

**Comment by PythonJim** [comment]
Thanks, that solved the problem.
