### ISSUE TITLE
Apply Theme to Side Bar

### ISSUE THREAD

**Issue by AnthonyVO** [geany/geany#1344]
I love the ability to theme the edit area and I prefer a darker theme.

The problem is that the theme does not apply to the side bar which to my mind is a bit inconsistent.  Especially when there is a strong light / dark contrast.

I am sure there are users that would prefer it to stay the way it is but for myself at least I would optionally like the relevant portions of the theme to apply to the side bar.

Thanks

**Comment by codebrainz** [comment]
The theme inside the editor widget uses a completely different mechanism than the GTK+ theme for the rest of the application. You could find or make a GTK+ theme to use for Geany which matches the colour scheme used in the editor widget.

An analogy would be like wanting a web browser's chrome (menus, tabs, toolbars, address bar, etc) to follow the CSS theme of a particular web page.

**Comment by elextr** [comment]
You don't say what OS you are using, on my Linux Mint the system theme applies to the symbols tab just fine.

**Comment by AnthonyVO** [comment]
My OS is Windows 7.

I get what both codebrainz and elextr are saying.  And I understand... to an extent....

The thing is that code is not like a web page.  In a webpage the layout and color scheme are all designed by the content creator to create a message.

Source code does not have its own color scheme.  The color scheme is chosen by the developer who is working with the code.   The primary purpose is to make their work more efficient and pleasant by creating helpful contrast between different types of elements and content and to reduce eye strain since we stare at code long and hard.

My system colors are lighter for regular use but when working with code I like my IDE colors to be more muted (bespin).   That creates an overly strong contrast between the Code window and the Geany side bar and Scratch area.

Notepad++ deals with that by having the styling also apply to the search area and the function list.

I was hoping that Geany could do something similar.

**Comment by elextr** [comment]
The "theme" in the source code pane is a mapping between syntactic entities and colours/faces that changes from language to language.  The symbols pane does not have the same syntactic entities so there is no obvious way to apply that theme to the symbols pane.  

But GTK themes allow you to specify settings that apply to Geany only, so you should be able to define theme settings for Geany that are different from the rest of the GTK themes.

Unfortunately GTK themes don't talk to windows themes, but thats GTK's problem not Geany's.

**Comment by codebrainz** [comment]
Closing since this is already supported, albeit not exactly as requested.

**Comment by jkyeung** [comment]
For clarity, what exactly *is* the workaround here? OP is on Windows 7 (as am I). @elextr seems to indicate that futzing with the GTK theme is not effective for Windows.

And granted, there is no obvious and direct correspondence between programming syntax elements and GUI elements, but at a minimum there could at least be an "overall dark UI" setting, even if it is not specifically matched to the syntax coloring.

Question for @AnthonyVO - did you ever find an acceptable workaround?

**Comment by AnthonyVO** [comment]
@jkyeung, I did not find a work around.

**Comment by jkyeung** [comment]
@b4n - I think you are right that the Windows Geany is not GTK3. I see a `gtk-2.0` directory which was apparently created during Geany installation.

**Comment by elextr** [comment]
@jkyeung `Menu->Help->Debug Messages` near the top will tell what GTK and Glib versions.

**Comment by Xoristzatziki** [comment]
Ok. It is Gtk's problem. But for people downloading the version for windows with gtk included we should provide an workaround either in the help or inside the .md. Just marking the issue with a tag "workaround" is not very helpful. 
Changing the theme in Windows does not affect the gtk theme. So there is no analog with «...wanting a web browser's...»  (unless the reference is for browsers that do not use window's theme but gtk's ) as codebrainz stated. Users do not know where installation program installed the gtk runtime that will be used with Geany. So they cannot easily change the theme for the very specific gtk run-time.

**Comment by codebrainz** [comment]
> But for people downloading the version for windows with gtk included we should provide an workaround either in the help

Agreed. Either a [wiki entry](https://wiki.geany.org) or even better a pull request improving [the manual](https://www.geany.org/manual/current/index.html#defining-own-widget-styles-using-gtkrc-2-0) would be much appreciated. I suspect most users don't fiddle with the GTK+ theme on Windows, so it hasn't been well documented yet.

> So there is no analog with «...wanting a web browser's...» (unless the reference is for browsers that do not use window's theme but gtk's ) as codebrainz stated. 

The analogy was to compare website CSS and browser window/widget themes to Scintilla editor widget themes and Geany window/widget themes. In the same way that CSS in a webpage doesn't control the appearance of the browser chrome/widgets, the Scintilla/editor area colour scheme in Geany doesn't affect the GTK+ theme. I stand by my apt analogy :smiley_cat:

**Comment by elextr** [comment]
@Xoristzatziki you should be able to create a GTK RC file in your Geany config directory IIUC, you don't need to do anything in the GTK directory.  There is some information in the Geany manual.  It would appear that nobody running Geany on Windows does much with the GTK theme, or they have not contributed back how to do it.  But most of the regular contributors don't use windows regularly, so we havn't done it either so we can only provide general guidance.

@codebrainz does apt run on windows?

**Comment by mario-giovinazzo** [comment]
Apply a Dark Theme to Geany (windows version). I just want share my experience.
1)
Google and download a GTK2 dark theme (you can find dozens).
As example this one (Nodoka-dark):
https://www.gnome-look.org/content/show.php/Fedora+Dark?content=85946
2)
Unpack anywhere let us say C:\TMP and navigate to gtk-2.0 folder
Copy file :
   C:\TMP\Nodoka-Dark\gtk-2.0\gtkrc
to:
   C:\Program Files (x86)\Geany\share\themes\MS-Windows\gtk-2.0\gtkrc
(save the original one if you plan to roll back)
3)
This may be enough, anyway you can play with gtkrc file changing colors to full match your requirements
![image](https://user-images.githubusercontent.com/30755972/76414044-da7b9d80-6396-11ea-88d8-b05e4e615b3f.png)

**Comment by CantoroMC** [comment]
Apply a Dark Theme to Geany (windows version). I just want share my experience.
Following the suggestion of @mario-giovinazzo +
Dark theme for Inkscape on Windows:
https://www.gnome-look.org/p/1304466/

**Comment by abrahamdsl** [comment]
I confirm that @mario-giovinazzo 's tips work. Thanks!

**Comment by calculuslmvt** [comment]
@mario-giovinazzo  Thanks dude .

**Comment by chenyulue** [comment]
@mario-giovinazzo 's approach works. Thanks!

**Comment by howdev** [comment]
wait for Geany to use gtk3 which has css

**Comment by elextr** [comment]
Geany already uses GTK3 most places and it is intended (time permitting) that the next Windows release will be GTK3 as well.

**Comment by goney3** [comment]
@mario-giovinazzo THANK YOU! I spent today searching for a solution, a lot of outdated ones out there. I really hope a simple Light/Dark can be added to Geany for Windows users sanity. Nothing like seeing a dark mode on the Geany website and then being suckered into figuring it out for each user, Windows users probably don't adopt Geany because of this issue.

**Comment by garydavenport73** [comment]
I took this approach:

I edited the geany.css file as follows:
```
/* Add these rules to the top of geany.css file to make dark */

* {
    background-color: rgb(25, 25, 25);
    border-color: rgb(25, 25, 25);
    color: rgb(150, 150, 150);
}

button,
button *,
*:hover,
*:hover>* {
    background-color: rgb(150, 150, 150);
    color: black;
}
```
and here is the result:
![simpleDarkGeany](https://user-images.githubusercontent.com/73868567/173250098-a865d962-0c05-4c6e-a550-7fb1f3726818.png)

**Comment by elextr** [comment]
@garydavenport73 (and everybody else) don't edit system files!!!

It will be overwritten by a new release of Geany and you will lose your changes.

Create a `geany.css` in your user config directory (~/.config/geany by default on Linux, not sure where on Windows or Macos) and only put the things you want to override in it, its _Cascading_ Style sheets :-)

Or use `Tools->Configuration files->geany.css` and a version of the system file will be put in your user config wherever it is even on Windows or Macos.  Just remember that if you do that the existing entries in the system files are overridden by the entries in this copy so changes with new versions won't be seen, so best to comment them out unless you specifically want to change them.

**Comment by garydavenport73** [comment]
Thank you for the help.  This sure beats manually updating this style at every release.  I copied `/usr/share/geany/geany.css` to `home/myusername/.config/geany/geany.css` and then added the extra styling code above and it worked!  (I also reverted the original geany.css to its original state.)

**Comment by Johnson2772** [comment]
> 

It worked for me after including the CSS styles at the bottom of the file, because there were some rules that overwritten this changes.

**Comment by Johnson2772** [comment]
It worked for me after including the CSS styles at the bottom of the file, because there were some rules that overwritten this changes.

> ```
> /* Add these rules to the top of geany.css file to make dark */
> 
> * {
>     background-color: rgb(25, 25, 25);
>     border-color: rgb(25, 25, 25);
>     color: rgb(150, 150, 150);
> }
> 
> button,
> button *,
> *:hover,
> *:hover>* {
>     background-color: rgb(150, 150, 150);
>     color: rgb(25, 25, 25);
> }
> ```
