### ISSUE TITLE
g++ any x64 version available in geany?

### ISSUE THREAD

**Issue by Roboball** [geany/geany#1352]
Hi I want to use Geany with C/C++ on win7 x64
https://wiki.geany.org/howtos/win32/getting-started

I followed instructions above, however TDM-GCC (the compiler)  32bit gives me an error "procedure __printf__ in libintl-8.dll was not found" while as the 64 version works fine (in the cmd command). As I actually need to compile opencv projects in 64 bit, I am satisfied with this compiler. 

So my question is there any way to use the 64 version of the compiler in Geany?  Or does it mean for c/c++ x64 projects I cannot use geany?

**Comment by elextr** [comment]
I presume you did something to make it use the 64 bit compiler in cmd, eg specifying the path to the compiler.  Just do the same in Geany `Menu->Build->set build commands`.

**Comment by Roboball** [comment]
Thanks after reboot the 64 Version worked
