### ISSUE TITLE
Snippets accelerator callback appears to be the wrong prototype.

### ISSUE THREAD

**Issue by elextr** [geany/geany#1354]
Snippet keybindings use `on_snippet_keybinding_activate()` as the [callback](https://github.com/geany/geany/blob/master/src/editor.c#L242) and it returns [void](https://github.com/geany/geany/blob/master/src/editor.c#L194) but the callback should return [boolean](https://developer.gnome.org/gtk3/stable/gtk3-Keyboard-Accelerators.html#GtkAccelGroupActivate).

This may account for the observation in #1353 that Scintilla keybindings are activated as well as the snippet, since the callback does not return true to prevent further signal emissions.

"Somebody" who knows GTK as well as @b4n should check my logic :smile:

**Comment by b4n** [comment]
@elextr sounds like a good investigation and a reasonable explanation :)
