### ISSUE TITLE
Changing Editor line break column requires document close and reopen

### ISSUE THREAD

**Issue by elextr** [geany/geany#1358]
If a document has line breaking set then changing the line breaking column (edit->preferences->editor->Features->Line breaking column) won't apply to a reflow in the document, but if the document has line breaking off the new settings will apply to a reflow.

[Edit: in fact reflow seems to switch between the old value and the new value of the line breaking column in the same document by switching automatic line breaking on/off. 

Edit to the edit: In fact it seems that when the document automatic line breaking is selected the reflow is switching between the system setting of the line breaking column and the project setting of the  _line wrapping_ column, even when the project line wrapping setting is selected off] 

I tried to trace the path for reflow to get the setting but got lost among multiple function local static copies of GeanyEditorPrefs :(

**Comment by b4n** [comment]
I can't seem to reproduce.  What are your exact steps?

**Comment by elextr** [comment]
Ok, I can explain it, its not a bug, just a confusing interaction between settings.

The `line break column` setting is system wide or project and `long line marker` setting is system wide, but reflow switches between `line break column` and `long line marker column` depending on the per-document `line breaking` setting (this behaviour is documented).  

Since I had a project open, those documents with `line breaking` on ignored the changes to system settings of `line breaking column` and `long line marker column` and used the unchanged project value of `line breaking column` (but I was unaware at the time that it was a project setting), but closing and reopening documents turned off theper  document `line breaking` setting and made reflow in those documents use the `long line marker column` system setting instead of the `line breaking` project setting.

Very confusing, the `preferences` dialog really should indicate when a setting is being overridden by a project setting, like the `set build commands` dialog does. #1363 opened for that enhancement.
