### ISSUE TITLE
Github website links broken

### ISSUE THREAD

**Issue by step-** [geany/geany#1360]
This is an online documentation issue. Due to the text you write to reference issue numbers in your release page, all the resulting HTML links are broken (404). You write `Issue#NN` and Github translates that into a link to URL `.../issue/NN`, but the correct URL is `.../issues/NN`. For instance, look at https://github.com/geany/geany/releases/tag/1.29.0

**Comment by elextr** [comment]
Yes, IIUC only #NN is needed to address PRs and Issues as the numbers are all unique, so if the writer wants to distinguish they need to put a space between the Issue and the # and it would probably be good to do it for PRs too.

**Comment by b4n** [comment]
Oops.  I generate this mostly automatically with the `scripts/github-news` script, and I made that typo.

@step- did you find some other place than your specific link where it was incorrect?  I fixed those, and am unaware of other (I started using a script for the last release), but I might miss some.

(PS: BTW, it's pretty inconsistent URL naming scheme on GitHub's part, as *pull* is a singular in this case… anyway, fixed)

**Comment by b4n** [comment]
> Yes, IIUC only #NN is needed to address PRs and Issues as the numbers are all unique, so if the writer wants to distinguish they need to put a space between the Issue and the # and it would probably be good to do it for PRs too.

As mentioned those links are generated.  This was for keeping the current format; but we can change that and rely on autolinking on GitHub if we want.

**Comment by elextr** [comment]
> This was for keeping the current format; but we can change that and rely on autolinking on GitHub if we want.

If this is only usually visible in Github it makes sense to let Github do the linking, if it is exported to the tarball or somewhere else then its probably better to have static links.
