### ISSUE TITLE
Top/Bottom of file

### ISSUE THREAD

**Issue by pepa65** [geany/geany#1372]
Feature request: allow a keybinding for Top of Document and Bottom of Document to go to the first resp. the last line in the file.

**Comment by elextr** [comment]
`Ctrl+Home` and `Ctrl+End`

**Comment by pepa65** [comment]
Thanks! I was looking at the Preferences/Keybindings, and couldn't find the option, so I thought it wasn't implemented.

**Comment by elextr** [comment]
Some keybindings are provided by Scintilla, the editing widget, these are noted in the [manual](http://www.geany.org/manual/current/index.html#scintilla-keyboard-commands).
