### ISSUE TITLE
Do not hardcode foreground colors in message window

### ISSUE THREAD

**Issue by Rakksor** [geany/geany#1376]
Currently the foreground colors of all colored lines in the message window are hardcoded in the get_color function in msgwindow.c. This works fine on white background, but with a dark GTK-theme the compiler error messages are barely readable. Would it be possible to make these colors configurable in the colorscheme?

**Comment by elextr** [comment]
Sounds like a good idea, just needs somebody to do it.  Pull requests are welcome.

**Comment by Rakksor** [comment]
Ok, I gave it a shot: #1377

**Comment by codebrainz** [comment]
Supported in 6b973bc70b6118c1d904d6d21626843b5e70beaa
