### ISSUE TITLE
Underscore doesn't appear

### ISSUE THREAD

**Issue by simo98** [geany/geany#1387]
Underscore doesn't appear.
I try it in many programming leanguages and with many themes.

![screenshot](https://cloud.githubusercontent.com/assets/18686996/22714992/5145e1e0-ed8f-11e6-8e3c-44c3f9cb065c.png)

**Comment by elextr** [comment]
You mean that the underscore does not show in the edit window?

What font are you using (Menu->View->Change Font)?

**Comment by codebrainz** [comment]
wat

**Comment by simo98** [comment]
Yes I mean that the underscore does not show in the edit window
The first image is for de font
The second image show how underscores don't show

2017-02-08 3:35 GMT+01:00 Matthew Brush <notifications@github.com>:

**Comment by simo98** [comment]
Yes I mean that the underscore does not show in the edit window
The first image is for the font
The second image shows how underscores don't show

2017-02-08 0:52 GMT+01:00 elextr <notifications@github.com>:

**Comment by b4n** [comment]
> The second image show how underscores don't show

I'm afraid I can only see the terminal image.

**Comment by codebrainz** [comment]
It definitively sounds like a specific font issue. Scintilla uses a fixed line height and I've experienced in the past where it makes the lines too short and it cuts off stuff like underscores which descend below the baseline. @simo98 did you try other fonts with the same result or is it only a specific font? All I could see was a screenshot of a terminal application and showing underscores in the font (hence my "wat" comment).

**Comment by elextr** [comment]
@simo98 and please verify the font GEANY is using as I requested above, it is not necessarily the same as the terminal.

**Comment by simo98** [comment]
It works with another font, thank you.

2017-02-10 1:18 GMT+01:00 elextr <notifications@github.com>:

**Comment by codebrainz** [comment]
@simo98 what is the name of the font you were using? Also do the underscores appear very low below the baseline of the other text and/or are the descenders of letters like p or q cut off also? This is either a bug in the fonts' metrics or in Scintilla, the editor widget Geany uses.

**Comment by simo98** [comment]
It was Monospace

2017-02-10 23:14 GMT+01:00 Matthew Brush <notifications@github.com>:

**Comment by HybridDog** [comment]
l noticed that the underscores disappear or become cut when increasing the font size to specific values.
![2017-03-18-104811_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3192173/24071016/bd21312e-0bc8-11e7-8929-3896bc174085.png)
When putting solely underscores in a line, they are invisible. When a space or some letter is added to the line, the underscores are slightly visible. l use sub-pixel-geometry, thus that the slightly visible underscore is green means it's the top part and the lower pixels (or whatsoever) are cut.
line 934: 3 underscores, 1 space
line 935: 3 underscores

**Comment by elextr** [comment]
@HybridDog did you try another font?

**Comment by HybridDog** [comment]
Yes, it didn't happen with the other font.

**Comment by HybridDog** [comment]
Yes, it didn't happen with the other font.
#
l'm not sure whether other letters, e.g. g, are also cut:
![2017-03-18-115428_1920x1080_scrot](https://cloud.githubusercontent.com/assets/3192173/24071501/bc421344-0bd3-11e7-90cb-3e2eef0d7858.png)

**Comment by elextr** [comment]
Some fonts write underscores below descenders but don't include that in the declared font height, this is technically incorrect and confuses the layout software in Scintilla (the editing widget Geany uses) so insufficient height is allowed for underscores.

To accomodate this you can set some space between lines by editing `Menu->Tools->Configuration Files->filetypes.common` and changing the values on the `line_height` setting, or just use the font that works :smile:.

**Comment by elextr** [comment]
What you are seeing when the bottom of the characters is "erased" is the same thing, but this time its because drawing the characters anti-aliased "smears" them outside the line height and they get written over by the next line.  Same solution as above.

**Comment by b4n** [comment]
I think Scintilla has a new (slower) drawing mode where all background are drawn before all foreground, in which case it might solve the issue at the cost of slightly overflowing on the line below.  Someone could give that a shot if indeed Scintilla has the option -- or as @elextr pointed maybe add some interline space manually.

**Comment by elextr** [comment]
Yes Scintilla has the option, though of course "giving it a go" means modifying the Geany source.  The "somebody" shoudl be sure to read the Scintilla docs as there is information on other settings to reduce the speed impact of the option.

**Comment by HybridDog** [comment]
```$ fc-match Monospace``` should tell the default font
l had dejavu: https://github.com/dejavu-fonts/dejavu-fonts
There are many dead links for any reason…

**Comment by HybridDog** [comment]
Is it that bug?
https://bugs.freedesktop.org/show_bug.cgi?id=10693

**Comment by HybridDog** [comment]
I couldn't reproduce it with fonts-dejavu-core 2.37-1.

**Comment by elextr** [comment]
@HybridDog so the font appears to be fixed?

**Comment by simo98** [comment]
Yep

Il giorno sab 9 dic 2017 alle 23:21 elextr <notifications@github.com> ha
scritto:

**Comment by bencaradocdavies** [comment]
(Copied from https://github.com/geany/geany/issues/2466)

I just got the `line_height` workaround to work with excellent results. The `line_height` setting can be found in "Tools" > "Configuration Files" > "filetypes.common". To change this setting from its default `line_height=0;0;` there are two things to note:

* `#~` lines are commented and have no effect.
* The file format is an [INI file](https://en.wikipedia.org/wiki/INI_file) so uncommenting the `line_height` line is insufficient because the `[styling]` section is also required; either uncomment this line or add a new `[styling]` section at the end.

The only uncommented lines in my filetypes.common are now:

```
[styling]
line_height=0;2;
```

With this setting and DejaVu Sans Mono Book size 12, underscores are visible. Using `line_height=0;1;` also works, but `line_height=0;2;` gives me, for the first time ever, exact agreement (as far as I can tell) with the line height in xfce4-terminal.

**Comment by tomuta** [comment]
I just ran into this after upgrading from Ubuntu 19.10 to 20.04. I use Geany all the time and never had this issue until now. Ubuntu 20.04 is using version 1.36. I don't know if this a problem with Ubuntu or with Geany. I believe I was using the same "Monospace Regular" font before.

**Comment by codebrainz** [comment]
@tomuta as @HybridDog mentions above, you can see which actual font "Monospace" maps to using `$ fc-match Monospace` command. Almost surely it's using the affected "Deja Vu Sans Mono" font that everyone is having problems with. You can work around using the method posted by @bencaradocdavies above or simply use a different font.

**Comment by tomuta** [comment]
@codebrainz Yes I successfully used the `line_height` work-around. I just wanted to report this here because Ubuntu 20.04 will probably be released this month, and this was one of the issues I ran into. Did not have this issue on 19.10 and prior. And yes, it maps to this font:
> DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"

**Comment by elextr** [comment]
@tomuta Thanks for reporting, but as you can see from the related issues and the fix, there is something wrong with that font (or Pango) that reports the height wrong so lines are smaller than they should be.

**Comment by Xianic** [comment]
I've just had the same issue after a fresh install of Xubuntu 20.04 (replacing Xubuntu 19.10)  and worked around with the config:
```
[styling]
line_height=0;2;
```
Thanks to @elextr and @bencaradocdavies.
Anecdotally, After the upgrade the lines in the editor looked more squashed together and now after configuring the `line_height` it looks as it did before the upgrade.

The editor font is set to Monospace Regular size 10
```
$ fc-match Monospace
DejaVuSansMono.ttf: "DejaVu Sans Mono" "Book"

**Comment by sigg3** [comment]
I have the same issue, using (default?) monospace regular size 10, on pop_os 20.04 (replacing 19.10).

![geany_bug_2020-05-08 10-45-25](https://user-images.githubusercontent.com/12447374/81388943-55ec9780-9119-11ea-9c6d-0e3446e8f457.png)

The 2nd line there has underscores instead of spaces.

Changing the font does work as a workaround, but monospace is a good default :(
I added line_height=0;2; to ~/.conf/geany/geany.conf but it didn't change anything. @Xianic did you have to activate it somehow?

**Comment by elextr** [comment]
@sigg3 As noted above:

"Tools" > "Configuration Files" > "filetypes.common"

not geany.conf.

**Comment by Hasan-Jinan** [comment]
This issue doesn't happen  while using monospace if you use font size "10"

**Comment by deadpahn** [comment]
Having this issue too.

**Comment by gaellafond** [comment]
Same issue, after migrating from Ubuntu 18.04 to 20.04

I was reluctant to change the font because I like the default one.

bencaradocdavies answer fixed my issue:
```
[styling]
line_height=0;2;
```

**Comment by joshas** [comment]
Same issue on Fedora 32. Fixed by changing font, but would be better if everything just worked correctly out of the box.

**Comment by elextr** [comment]
Folks, there is no point in keeping on commenting on a closed issue, its known that it occurs. Thats why its pinned at the top of issues with the workaround.

A change in the editing widget Geany uses _may_ improve it, but other changes mean it can't be upgraded without possibly large changes to Geany, and since the widget is undergoing another round of API changes the decision has been taken to wait until that is released and make all the changes in one step.

**Comment by tomuta** [comment]
Well, the fact that the underscore with this font works just fine in just about any other application suggests that it is an issue with this widget somehow. I don't know for sure, and I certainly don't know how difficult or easy it would be to fix it, but it certainly confused me until I realized what was going on.
