### ISSUE TITLE
reload_clean_doc_on_file_change=true Does not work.

### ISSUE THREAD

**Issue by exebook** [geany/geany#1388]
![selection_145](https://cloud.githubusercontent.com/assets/3821217/22738305/f05ea8ce-ee17-11e6-816c-ba29a0b56ae5.jpg)

What's wrong here? I expected the file to be auto reloaded now.
```
$ cat ~/.config/geany/geany.conf|grep reload_clean
reload_clean_doc_on_file_change=true
```

**Comment by shiftee** [comment]
Did you add the option yourself?
The pull request hasn't been merged yet #1246

**Comment by exebook** [comment]
Ok, I decided to start my own small investigationhere.

```
$ cd geany
$ git pull
Already up-to-date.
$ ag reload_clean_doc_on_file_change

```

The substring `reload_clean_doc_on_file_change` is not even in the master branch. Do I need to pull another branch to get this feature? Was the option renamed?

**Comment by exebook** [comment]
@shiftee, thanks. I thought it was. Probably because of three shiny green bullets "Checks passed", "No conflict detected", "Feature approved".

**Comment by exebook** [comment]
@shiftee, any suggestion how to checkout your branch?
I know this is silly, but I tried all suggestions from Stackoverflow already.

```
$ history
  550  git fetch shiftee:auto_reload
  551  git fetch origin shiftee:auto_reload
  552  git checkout --track origin/shiftee:auto_reload
  553  git checkout shiftee:auto_reload
  554  git checkout auto_reload
  555  git checkout 'shiftee:auto_reload'
  556  git checkout --track -b shiftee:auto_reload origin/shiftee:auto_reload
  557  git fetch shiftee:auto_reload
  558  git fetch 'shiftee:auto_reload'
  559  git fetch remote 'shiftee:auto_reload'
  560  git fetch origin 'shiftee:auto_reload'
```
Nothing works.

**Comment by shiftee** [comment]
I'm have little to no experience but the following seems to work:
`git remote add shiftee https://github.com/shiftee/geany.git
git fetch shiftee
git checkout shiftee/auto_reload`

**Comment by elextr** [comment]
@exebook github recommends

```
git checkout -b shiftee-auto_reload master
git pull https://github.com/shiftee/geany.git auto_reload
```

as part of the instructions for manual merging, which sadly it doesn't display if you don't have merge access.  It doesn't need adding extra remotes for each pull request provider.

**Comment by elextr** [comment]
#1246 now merged, closing.
