### ISSUE TITLE
Damaging edited files from Chrome

### ISSUE THREAD

**Issue by exebook** [geany/geany#1413]
When drag-drop text inside Chrome (i.e. NOT leaving Chrome! Not really dragging into Geany), the text actually ends up in Geany at a random position. It happens silently, so my source code sometimes unnoticed gets into a company Git repository. 

In fact I have `pref_editor_disable_dnd=true`

Steps to reproduce:

1. Open a file in Geany
2. Open Chrome
3. Select any piece of text in Chrome
4. Start dragging this text
5. Stop dragging few millimeters or an inch away fromt he starting point
6. Switch to Geany and get scared, the selected text is already inserted at the random position.

This only happens if Geany window was the previous active window prior to swtich to Chrome window.

Please see the screenshot, this is drastic.

![Screenshot][Screenshot]

[Screenshot]: https://s16.postimg.org/ddp04pkmd/geany_issue.jpg

**Comment by exebook** [comment]
I am using Ubuntu 16. Geany is built from latest github source. Window manager IceWM if that matters. Latest Chrome. Same happens with Yandex Browser, but not with Firefox.

**Comment by elextr** [comment]
Which ubuntu 16? 16.04 or 16.10?

**Comment by elextr** [comment]
Can't replicate here on Ubuntu 16.04 based Mint with Cinnamon with git versions of GTK2 Geany or GTK3 Geany and latest Chrome (not -ium).

**Comment by exebook** [comment]
@elextr 
Ubuntu 16.04 LTS
Ceany 1.30 (git >= 6f9b34d)
"Calron"
(built on or after 2017-02-09)

Chromium (thanks for reminding that Chrome is not Chromium)
Version 55.0.2883.87 Built on Ubuntu , running on Ubuntu 16.04 (64-bit)

Yandex Browser: Version 17.1.1.266 beta (64-bit)

**Comment by b4n** [comment]
Is this still happening?  I can't reproduce here, but I don't have the exact same setup at hand.

**Comment by exebook** [comment]
Switched to Firefox a year ago, so do not know if this is still the issue.
