### ISSUE TITLE
Feature: switch between filetypes quickly

### ISSUE THREAD

**Issue by akonon** [geany/geany#1415]
Hi) Geany is great and I love it but one thing is driving my nuts:

When I work with inline CSS in an HTML document, I switch the document's type to activate highlighting and autocompletion for CSS. If there is inline JS code then again I go to the menu and look for the JS filetype. But it takes too long to find the necessary filetype on the 3rd level of the menu among 30+ other types even when I remember where my items are located approximately.

Is there a way to make the switching process faster?

Thanks,
Alex

**Comment by b4n** [comment]
Not sure it'll please you, but I can suggest you trying the Commander plugin, which allows you to quickly trigger any menu item through a quick text-based command.

**Comment by akonon** [comment]
Commander is what I needed! 

[shortcut]+html+Enter  switches to HTML filetype
[shortcut]+javasc+Enter  switches to JS filetype
[shortcut]+sty+Enter  switches to CSS filetype
Now it's not 10 seconds but 1!

Changed Geany's locale to LANG=C to make this work properly (it didn't suggest CSS filetype on top of the list whatever command I tried in my locale) but it's OK.

Thank you :)

**Comment by b4n** [comment]
> Changed Geany's locale to LANG=C to make this work properly (it didn't suggest CSS filetype on top of the list whatever command I tried in my locale) but it's OK.

The plugin uses fuzzy matching on the menu item labels, so you need to type something that is there.  E.g. in French locale, it's *Feuille de style en cascade*, translated from the "Cascading stylesheet".
You can check on your locale and see.

Also, Commander matches the whole menu hierarchy fuzzily, and splits at words, which means that you can match e.g. *Objective-C source file* with `dsfoc`: ***D**ocument **S**et **F**iletype Programming Languages **O**jective-**C** source file* or the like.

Ultimately you'll find the short strings you like and that work best in your locale.

**Comment by ntrel** [comment]
> it takes too long to find the necessary filetype on the 3rd level of the menu among 30+ other types

For completeness, there is a way. I updated the manual with a tip to explain it, put commonly used filetypes in the None group:
https://www.geany.org/manual/dev/index.html#id211
