### ISSUE TITLE
OS kill signal does not save tabs. 

### ISSUE THREAD

**Issue by novel-yet-trivial** [geany/geany#1416]
When shutting down the OS while geany is open, geany closes but does not remember the open tabs like it does when the user closes geany normally.

**Comment by codebrainz** [comment]
It used to be handled and worked fine but was commented out in fbb89f523af47b35e238678d348cfa98e56c760a as it was technically incorrect. There was a PR #1255 to re-enable it, but it hasn't been merged yet.

**Comment by elextr** [comment]
Note that #1255 won't guarantee it if the system doesn't allow enough time for the save to happen, many send SIGTERM then clobber the process if it doesn't finish soon enough.  It really needs session management.

**Comment by dandv** [comment]
Geany should first save the line position in each file, when being exited normally (#1117). This is a super commonly used feature with any files that are edited frequently: when you open a source file you've been working on, you want the cursor to be where you left it, but Geany resets its position to line 1, column 1.

**Comment by elextr** [comment]
@dandv why comment the same thing on multiple issues?

**Comment by dandv** [comment]
@elextr: for extra exposure, since my initial issue hadn't received much attention in 2 years. Thanks for your comment.

**Comment by elextr** [comment]
@dandv Geany is a totally volunteer project, people work on what they want to.  Given human nature, appearing to demand attention from volunteers is a fast way of having people not do anything.

As the discussion on #1860 concluded, there is no guarantee that things can be saved at shutdown but moving the session to earlier may help it happen, or the session files could also be saved intermittently by the save actions plugin.

But in both cases somebody has to do it, and to date nobody has had the time or interest to do so.

**Comment by elextr** [comment]
Done in #2114
