### ISSUE TITLE
multiline function arguments showing up as variables on the sidebar

### ISSUE THREAD

**Issue by novel-yet-trivial** [geany/geany#1417]
Using python, this code should only report 1 variable. 

```
data = dict(
	en = "beer",
	de = "bier",
	es = "cerveza"
)
```

But 4 variables are reported in the sidebar: 

![geany](https://cloud.githubusercontent.com/assets/23124853/23534369/51b2d7f2-ff6c-11e6-8dca-0afc01a818ab.png)

Thanks for all your work!

**Comment by elextr** [comment]
If [universal ctags](https://github.com/universal-ctags/ctags) has the same problem please report it there (and post the bug report here for tracking), otherwise it will get fixed when the parser update phase of the syncing of Geanys fork of ctags happens after #1263.
