### ISSUE TITLE
Geany 1.29 toolbar no longer fits (spills over to ellipsed dropdown) status bar 2X as tall as 1.24

### ISSUE THREAD

**Issue by drankinatty** [geany/geany#1419]
All,

  I have geany 1.24 of raspberryPi and it looks great. The toolbar icons all fit in the allotted space and the statusbar is elegantly sized at the bottom of the window. I have geany 1.29 on opensuse Leap 42 and it looks horrible. The toolbar height is 2x what it should be, the tabs on top of edit window are so huge they are unusable, the icons on the toolbar do not fit on the toolbar and spill out into an overflow ellipsed dropdown menu on the far-right of the toolbar and the status bar is 2x the size wasting critical edit window real-estate.

  I have checked and made sure the `~/.config/geany` and `~/.config/gtk-3.0/settings.ini` are the same and set to use the same theme. However, no matter what I do, 1.29 on opensuse refuses to look like 1.24 on raspberrypi, but instead looks like some clunky gtk tutorial app you would put together trying to learn gtk. That's not what geany is supposed to look like, it is a fine app.

  What do I need to do to get 1.29 to be usable. I've turned the toolbar off completely to regain 1-inch of screen (I'm on a laptop, so it matters), but that takes away from the efficiency the toolbar provides. What can I do to get 1.29 to use the same settings that 1.24 is using on raspberrypi?

**Comment by elextr** [comment]
Well, you are looking n the right place, those things are set by your theme.  

But are you sure you are using a GTK-3 version of Geany, IIUC most distros still provide a GTK2 one, check `menu->help->debug messages` near the top.

If its gtk2 you need to check gtkrc files IIUC.

**Comment by drankinatty** [comment]
Uugh. You are right:

    21:47:46: Geany INFO		: Geany 1.29, en_US.UTF-8
    21:47:46: Geany INFO		: GTK 3.20.9, GLib 2.48.2
    21:47:46: Geany INFO		: System data dir: /usr/share/geany
    21:47:46: Geany INFO		: User config dir: /home/david/.config/geany
    21:47:46: Geany INFO		: System plugin path: /usr/lib64/geany

On the raspberrypi

    21:48:47: Geany INFO		: Geany 1.24.1, en_US.UTF-8
    21:48:47: Geany INFO		: GTK 2.24.25, GLib 2.42.1
    21:48:47: Geany INFO		: System data dir: /usr/share/geany

This is bad news, and this is the reason I try and stay with Gtk+2, there are just no themes for Gtk+3 that give a decent look, and if you find one, there is no guarantee it will work tomorrow when the next rapid fire, rabbit pellet release of Gtk+3 pops up and deprecates what was the latest new gotta have theme approach last week.

Is there any way I can tweak the 1.29 code or provide a make option to have it use the Gtk+2 theme so the interface is usable again?

**Comment by drankinatty** [comment]
Here is what I'm seeing:

[Geany 1.2.4 Interface](https://www.rlfpllc.com/dl/geany/geany_1.24.png)

[Geany 1.2.8 Interface](https://www.rlfpllc.com/dl/geany/geany_1.29.png)

The usability differences on a laptop are huge. If you have any problems with the links (iptables is set tight) let me know and I'll e-mail them or provide them in another manner.

**Comment by elextr** [comment]
Well, Mint and Mint's themes work pretty well, my toolbars are 1cm high,  (and they match gtk2 and gtk3) but of course its a stable/LTS distro so you don't have the churn you mentioned.  Opensuse IIUC is a rolling release so churn is normal.  Interesting they are providing a GTK3 release, I thought only Arch was doing that (and, well, you EXPECT Arch to be bleeding edge :)

No you can't swap from GTK2 to GTK3, they are not binary compatible, or even compile API compatible, apps have to be compiled with one or the other.

I'm afraid all you can do is have a go at overriding the theme for Geany using GTK3 not-quite-CSS as I call it.

**Comment by elextr** [comment]
Or of course compile your own Geany using GTK-2

**Comment by codebrainz** [comment]
@drankinatty did you change the Prefs->Interface->Toolbar settings? It lets you set how big the toolbar buttons are, whether they have text or just icons, and has a Customize Toolbar button that lets you add/remove/re-order toolbar items.

**Comment by elextr** [comment]
Also I guess a KDE based distro doesn't make as much effort with GTK themes as a GTK based distro does.

**Comment by drankinatty** [comment]
No, that comment went more to the new KDE4 philosophy of taking something perfectly good (KDE3) and destroying it in the name of progress (KDE4/FW5) while denying the user any control of the changes `:)`.

**Comment by kugel-** [comment]
So this is not a (1) Geany bug and (b) resolved for the reporter. Lets close this.

**Comment by elextr** [comment]
@kugel- seems fair
