### ISSUE TITLE
Rust markup error on 'usize' suffix 

### ISSUE THREAD

**Issue by BenWiederhake** [geany/geany#1421]
Small reproducing example:

```
static SOMETHING : usize = 4usize;
```

Expected behavior: recognize `4usize` as the number.

Actual behavior: the `4usize` doesn't get parsed correctly, and geany only marks `4us` as the number, apparently parsing `ize` as a different, stand-alone identifier.

As this is technically a bug in scintilla, I guess, I already [created a bug there](https://sourceforge.net/p/scintilla/bugs/1919/).

**Comment by elextr** [comment]
Yep, scintilla problem, [here](https://github.com/geany/geany/blob/3303bde75844033e4262f649a3437e0dbcc316d0/scintilla/lexers/LexRust.cxx#L270) checks the `u` and [here](https://github.com/geany/geany/blob/3303bde75844033e4262f649a3437e0dbcc316d0/scintilla/lexers/LexRust.cxx#L274) checks the `s` and then does nothing else, should also munch the `ize`.

**Comment by SiegeLord** [comment]
This is fixed in Scintilla 4.0.0.

**Comment by elextr** [comment]
@SiegeLord Scintilla 4 requires C++17 which means newer compilers than Geany wants to require, if the fix is available in the 3.x series then somebody can make a PR to upgrade Geany to use Scintilla 3.10 (as of writing this).
