### ISSUE TITLE
Calltips incorrectly positioned

### ISSUE THREAD

**Issue by elextr** [geany/geany#1422]
Updated to git just after 1.30 release:

20:42:01: Geany INFO		: Geany 1.31 (git >= f5be2fa), en_AU.UTF-8
20:42:01: Geany INFO		: GTK 3.18.9, GLib 2.48.2

now calltips are located far off to the left actually partially off the screen (see screenshot).

![screenshot from 2017-03-06 20-45-48](https://cloud.githubusercontent.com/assets/811085/23606802/06586282-02ae-11e7-96c2-69d8ddbfa822.png)

**Comment by elextr** [comment]
I wonder if its anything to do with this being the right hand monitor of a two monitor desktop, and it thinks thats the centre, though it used to work.

**Comment by elextr** [comment]
Same thing with GTK2

21:10:50: Geany INFO		: Geany 1.31 (git >= 3303bde), en_AU.UTF-8
21:10:50: Geany INFO		: GTK 2.24.30, GLib 2.48.2

**Comment by elextr** [comment]
Same problem with symbol completion list, if the cursor is on the right hand monitor the popup horizontal position is limited to near the left of the monitor.

**Comment by elextr** [comment]
Not surprisingly git bisect says its:

commit 2219ab720cf69362f08bc4506ae6cb6b58007368
Author: Colomban Wendling <ban@herbesfolles.org>
Date:   Tue Feb 21 14:16:23 2017 +0100

    Update Scintilla to version 3.7.3

**Comment by b4n** [comment]
OK, reproduced with Geany on a second monitor.  This is due to some confusion about monitor and screen in 3.7.3.  I have a patch I'll submit later today.

**Comment by b4n** [comment]
@elextr could you please test the above commit?  It's in the https://github.com/b4n/geany/compare/scintilla/monitor-placement branch.  Fixes it for me.

**Comment by elextr** [comment]
@b4n, WFM both gtk2 and gtk3.

**Comment by b4n** [comment]
Forwarded upstream https://sourceforge.net/p/scintilla/bugs/1920/

**Comment by klaxian** [comment]
I imagine we will have to wait for Scintilla 3.7.4 and Geany 1.31 before this is resolved? I have downgraded to Geany 1.29 in the meantime. Thanks for the quick response.
