### ISSUE TITLE
Macos Sierra : Geany 1.30 close project - geany falls

### ISSUE THREAD

**Issue by miltar** [geany/geany#1423]
When I want to close a project to create another, when closing the project geany falls, it closes unexpectedly.
Thanxs!

**Comment by miltar** [comment]
It's just an incompatibility with the project plugin .... nothing to do with geany ... sorry.

**Comment by techee** [comment]
@miltar With what plugin does this happen? If some plugin crashes Geany, it should be fixed.

**Comment by miltar** [comment]
Hi Jiří Techet:

When I upgrade geany 1.29 to geany 1.30, the Geanyprj plugin gave me
problems. Then I uninstall the plugin and geany worked very well, I
reinstalled the plugin and it did not give me problems, that's why I
closed the issue. Sorry, next time I'll be more concrete. Good job
with Geany, it's great !!!


2017-03-08 21:30 GMT+01:00 Jiří Techet <notifications@github.com>:

**Comment by techee** [comment]
OK, thanks.
