### ISSUE TITLE
Fixed sidebar size

### ISSUE THREAD

**Issue by al-info** [geany/geany#1435]
Hi,
I like using geany, and i use a specific sidebar width to get a nice preview of my document using plugin-markdown. And i could'nt find a way to fix the sidebar width, so i have to adjust it manually at every startup...
Is it possible / easy / desirable to add a configuration option to fix the width of the sidebar ?

Thank you very much for your nice software !

**Comment by elextr** [comment]
If Geany is shut down politely by its menu quit or the window close button then the sidebar width is saved and restored on next start.

If Geany is shutdown by logging out or shutting down the machine you are effectively crashing it and there is no time to save the session data including the width of the sidebar.

**Comment by al-info** [comment]
I should notice that i'm using i3wm, a tilling window manager. So window management would be different as in standart environments.
And I confirm that sidebar always take the same width at startup, even if I move it before closing. Is there a file where I could put the size parameter, I could use a workaround with  a init script to write my settings to geany ?

**Comment by elextr** [comment]
If you move the sidebar and then close Geany once using its own Menu->file->quit it should save that position in its configuration, then it should open with the right width, and it should keep the width since it will save the value it loaded at startup if it writes the config at any time, and if its killed by your WM then that value should already be in the config ready for re-opening.

**Comment by al-info** [comment]
It doesn't.

1 - Open

![Open geany](https://tila.im/~al/opengeany.png)

2 - Change size

![Open geany](https://tila.im/~al/changesize.png)

3 - Close

![Open geany](https://tila.im/~al/closegeany.png)

4 - Open again

![Open geany](https://tila.im/~al/openagaingeany.png)

Same thing whith window manager kill. Thanks for your time and your answers !

**Comment by elextr** [comment]
Works for me, it appears that you are using the markdown plugin, please try it without any plugins active.

**Comment by al-info** [comment]
Same thing without mardown plugin. The open files are loaded after closing / starting geany, but no sidebar width.

I can add i don't use any *dm but systemd autologin then start i3 through .xinitrc

**Comment by elextr** [comment]
Just to be sure, if you do nothing but move the sidebar position, close Geany from it File->Quit and restart Geany the sidebar width is not restored?

**Comment by elextr** [comment]
I don't suppose you have de-selected `General->Startup->Shutdown->Save window position and geometry` in preferences?  It appears that also disables saving of _internal_ positions as well.

**Comment by al-info** [comment]
It was de-selected and select it solved the problem. Thank you!
