### ISSUE TITLE
[PHP] 1.30.1 don't autocomplete require.

### ISSUE THREAD

**Issue by IlyaIndigo** [geany/geany#1436]
The latest version (1.30.1) in PHP don't autocomplete **require**.

**Comment by MatrixMike** [comment]
Try going to the geany website and downloading the latest - which is now 1.30.1 ...
From a working geany go to help website (which takes you to http://www.geany.org/  )
I had similar issues but just built 1.30.1 on my platforms and all working OK again now. 
Maybe this is just slightly un-related but latest is 1.30.1

**Comment by IlyaIndigo** [comment]
Now update to 1.30.1
[https://build.opensuse.org/package/show/home:13ilya:GTK2/geany](https://build.opensuse.org/package/show/home:13ilya:GTK2/geany)
Nothing happens.
![geany](https://cloud.githubusercontent.com/assets/2612812/24126025/65ec7752-0dd4-11e7-8c8a-d65712f885b0.png)

**Comment by codebrainz** [comment]
@IlyaIndigo which version did auto-complete `require`? It wasn't in the tags file from before the last change (~2 years ago) and it's not in the tags file after that, and it's always been in the `filetypes.html` keyword list, as far as I can tell. Is it possible you had some customized tags/filetypes before that you don't have now?

**Comment by IlyaIndigo** [comment]
I'm using theme vibrant-ink and my fildefs/filetypes.html

```
# For complete documentation of this file, please see Geany's main documentation
[styling]
# styling for PHP/HTML is done in filetypes.xml


[settings]
# default extension used when saving files
#extension=html

# the following characters are these which a "word" can contains, see documentation
#wordchars=_abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789

# if only single comment char is supported like # in this file, leave comment_close blank
# these comments are used for PHP, the comments used in HTML are in filetypes.xml
comment_open=<!--
comment_close=-->

# set to false if a comment character/string should start at column 0 of a line, true uses any
# indentation of the line, e.g. setting to true causes the following on pressing CTRL+d
	#command_example();
# setting to false would generate this
#	command_example();
# This setting works only for single line comments
comment_use_indent=true

# context action command (please see Geany's main documentation for details)
context_action_cmd=

[build_settings]
# %f will be replaced by the complete filename
# %e will be replaced by the filename without extension
# (use only one of it at one time)
# use a syntax checker and ignore the formatted output
compiler=tidy %f >/dev/null

# the file will be opened with the default browser which can be set in the preferences dialog
run_cmd=builtin

```

How can I modify it so that "require" appears in the autocomplete?

**Comment by b4n** [comment]
FWIW (on that super old report):
* [`require`](https://www.php.net/manual/en/function.include.php) is a keyword, not a function
* Geany doesn't auto-complete keywords (yet)
* You can workaround this by creating a PHP [tags file](https://www.geany.org/manual/current/index.html#global-tags-files) including this as whatever type you like (function, constant, or anything that would work).
