### ISSUE TITLE
Markdown: "matching" underscores have priority over code block

### ISSUE THREAD

**Issue by BenWiederhake** [geany/geany#1439]
Given that Markdown has lots of undefined semantics, this may very well be a valid interpretation of certain broken Markdown documents. But I guess most would agree that the priority should be the other way around.

Example:  (Save as `something.md` and open with Geany)

    _This is "underlined"
    
    ```
    should_be code
    ```
    
    This sentence is considered code, because the
    "matching" underscores had priority (?)

Note that the "stray underline" can also occur in HTML inline-comments, where they don't stand for underlining anyway.

**Comment by elextr** [comment]
Yes well, markdown is only defined by the processor you use, "no the one I use", "no the other one"...

[full disclosure, as an Asciidoc maintainer I am required to diss Markdown at every opportunity :wink: ]

The Markdown lexer is part of the editing component we use, Scintilla.

Can you describe what "rule" you suggest to decide that the underscore is not going to be matched and propose it to the [Scintilla project](https://sourceforge.net/p/scintilla/bugs/) if it isn't already listed.

**Comment by BenWiederhake** [comment]
[Reported upstream,](https://sourceforge.net/p/scintilla/bugs/1216/) but I'm not too optimistic about it getting any attention.

**Comment by rdipardo** [comment]
Patched in a forthcoming release of `lexilla`: https://github.com/ScintillaOrg/lexilla/commit/ca976aaa2d505e5d7fe5f11a2d7be9b610e2fac0

![Screenshot_2021-06-28_20-40-13](https://user-images.githubusercontent.com/59004801/123720187-80377200-d851-11eb-8bfd-9340cacfa1f3.png)

![Screenshot_2021-06-28_20-41-48](https://user-images.githubusercontent.com/59004801/123720203-888fad00-d851-11eb-870e-96455ea7a19a.png)

**Comment by eht16** [comment]
Since we already use Scintilla 5.1.5 where this bug is fixed, I'll close this issue.

Just re-open if you disagree.
