### ISSUE TITLE
TypeScript syntax highlighting

### ISSUE THREAD

**Issue by jhpratt** [geany/geany#1449]

**Comment by elextr** [comment]
If typescript is close enough to an existing language you can make a custom filetype, see the manual.

If typescript is not close enough to another language first you need to have a lexer added to the [Scintilla](http://www.scintilla.org/) editing widget then if needs to be integrated into Geany and a filetype created.

**Comment by diegogarromolina** [comment]
For syntax highlighting only add "*.ts;" to "Javascript=*.js;" in filtype_extensions.conf in geany installation directory
