### ISSUE TITLE
"Find" highlighting default color

### ISSUE THREAD

**Issue by vincent-legoll** [geany/geany#1453]
I use a dark background, and the grey highlighting used to highlight "find" matches is barely visible.

I searched how to change that (a few times already) and couldn't make it work (something like yellow BG).

I think adding a FAQ entry would be sufficient, but not something like "go read X thousands lines theme source code", or anything like that.

**Comment by elextr** [comment]
You didn't say what colour scheme you are using.

The find highlighting uses the "selection" style set by your colour scheme.  So you have to edit the "selection" setting in the colour scheme to change it (and/or complain to the theme creator for making it too faint).

**Comment by vincent-legoll** [comment]
OK, so this is in fact two different issues:
* bad colors from the scheme
* missing FAQ entry to help user customize their color scheme for just a single/simple thing. (I don't even know if this is possible...)

Your question about the color scheme I use made me go look, I use the default one. D'oh !
But with the Preferences/Editor/Display/Invert syntax highlighting color config box checked.

I think that may be the cause of the "Bad color scheme" assumption. And may also explain why my previous attempts a "fixing" the bad color scheme by following the was not successful.

I'll go find a real "dark" color scheme and will disable the "invert highlighting" and get back here.

Thanks for the prod in the right direction.

**Comment by shiftee** [comment]
To fix the bad colors from the scheme issue you can change

-selection=0x000000;0xc0c0c0;false;true
+selection=0x000000;0xffff00;false;true

in data/colorschemes/alt.conf

**Comment by elextr** [comment]
@vincent-legoll same thing but (for historical reasons) the default colour scheme lives in "filetypes.common" in the filedefs directory.

Change the line @shiftee said, but as you have inverted colours you make it it darker to make it lighter :)

Many colour schemes are [here](https://github.com/geany/geany-themes)

@shiftee changing "alt.conf" only works if you are using that colour scheme.

**Comment by vincent-legoll** [comment]
OK, so I used that config because there was only the default and alt themes in my setup at the time, and then I forgot about it and couldn't "fix" it. So the right fix was to disable that and get a real color theme (in fact I got the whole git repo...

And the rant about missing FAQ entry is now also kind of moot (a quick'n'dirty entry wouldn't hurt)

Thanks all
