### ISSUE TITLE
Geany 1.30.1 and 1.30 do not work on windows 8.1

### ISSUE THREAD

**Issue by DiepEsc** [geany/geany#1454]
On my computer:
Windows 8.1 x64. there versions do not work  but version 1.29.9 work.
(include changing of compatibility)

**Comment by codebrainz** [comment]
Can you elaborate on how it does not work? Is there any error message or anything?

**Comment by TranTienTung** [comment]
When I double click on geany.exe, nothing showed. No error message.
I check in windows task manager, the process geany.exe appear for a few seconds and then disappear.

**Comment by eht16** [comment]
Could you open a terminal (cmd.exe) and run `\path\to\geany\bin\geany.exe --verbose`?
This should start Geany with another terminal window opening, hopefully you can see anything useful in there before it crashes.

Also, try to disable all plugins (either by editing geany.conf directly or by renaming the plugins folder in the installation path).

In 1.30 there were no relevant changes as far as I remember which could cause the crash. So I assume it could be caused some GTK or other dependency library update.

**Comment by kugel-** [comment]
> Also, try to disable all plugins (either by editing geany.conf directly or by renaming the plugins folder in the installation path).

geany.exe -p also works for disabling plugins.

**Comment by TranTienTung** [comment]
![image](https://cloud.githubusercontent.com/assets/14236104/24766233/bc65d832-1b24-11e7-9368-2ea9ed039c57.png)
This is the notification on windows 7 (x64). 
The terminal show nothing, no other terminal window opening.

**Comment by codebrainz** [comment]
@TranTienTung didyou try @eht16's suggestion of disabling all plugins? Usually crashes like that are caused by plugins rather than Geany itself.

**Comment by TranTienTung** [comment]
I can't find the config file geany.conf. But when I try geany.exe -p --verbose, I got the same result.

**Comment by codebrainz** [comment]
@TranTienTung can you try this `geany -v -c "C:\SomeWhereYouCanWriteToLikeYourDesktop"` to use a new config directory for testing.

**Comment by TranTienTung** [comment]
@codebrainz ,
I tried using the command `C:\Program Files (x86)\Geany\bin\geany.exe" -v -c . --ver
bose`, where the current directory is my desktop folder and has no conf file. Then I got the same result.

**Comment by codebrainz** [comment]
@TranTienTung can you use the instructions here:

http://winaero.com/blog/how-to-edit-environment-variables-quickly-in-windows-8-1-and-windows-8/

And paste the complete value of the `PATH` variable listed under "system variables"? It might be another app conflicting supporting libraries with Geany.

**Comment by TranTienTung** [comment]
The system PATH variable:
 `C:\ProgramData\Oracle\Java\javapath;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;%JAVA_HOME%;%GIT%;%ADB%;%ANDROID_HOME%;C:\ProgramData\chocolatey\bin;C:\Program Files\nodejs\;C:\tools\python2;C:\Program Files (x86)\Heroku\bin;C:\Program Files (x86)\git\cmd;C:\Program Files (x86)\Git\cmd;C:\Program Files (x86)\Skype\Phone\;.;%JAVA_HOME%\bin\;C:\Program Files (x86)\GTK2-Runtime\bin`

**Comment by TranTienTung** [comment]
I don't think it is a conflict. Because I ran geany on 3 computer, with windows 7 x64, windows 8 x64, windows 10 x64, and got the same result.

**Comment by codebrainz** [comment]
> I don't think it is a conflict. Because I ran geany on 3 computer, with windows 7 x64, windows 8.1 x64, windows 10 x64, and got the same result.

I wonder if it's something you are running on each computer though. A lot of people use Geany on all those platforms (myself with existing and clean installs on win7 and win10) without this issue, though I'm not sure what's causing your problem.

**Comment by elextr** [comment]
@TranTienTung just to confirm you downloaded and ran the geany-1.30.1_setup.exe installer from [here](http://www.geany.org/Download/Releases)?

**Comment by colrose** [comment]
I have had exactly the same experience as @DiepEsc . Geany 1.30 will not run on either of my two Win 7 64 bit machines. No trouble with 1.29

**Comment by kugel-** [comment]
@DiepEsc Your PATH has C:\Program Files (x86)\GTK2-Runtime\bin. This is potentially incompatible with Geany.

@colrose Have you attempted the workarounds, such as running geany.exe -p or geany.exe -c "C:\some dir"? Please also paste your PATH variable.

**Comment by colrose** [comment]
@kugel- I tried:
geany.exe -p
geany.exe --verbose
geany.exe -p --verbose
geany.exe -v -c "C:\ ..."
Renamed geany.conf

Geany starts (as seen in processes), its memory usage increases until it crashes but it never opens. No error messages.

My current Path (after playing around with other GTK versions) is:

C:\ProgramData\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Microsoft Application Virtualization Client;C:\Program Files (x86)\Lithnet\Lithnet.MpUpdate;C:\Program Files (x86)\Google\Google Apps Sync\;%systemroot%\System32\WindowsPowerShell\v1.0\;C:\Program Files\Calibre2\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;C:\Program Files (x86)\QuickTime\QTSystem\;C:\Program Files\GTK2-Runtime Win64\bin

(This path was working o'k with Geany 1.29)

**Comment by codebrainz** [comment]
@colrose could you try it after removing `C:\Program Files\GTK2-Runtime Win64\bin` from the PATH? Geany should use its own bundled GTK+ since it's in the same directory as the `Geany.exe` executable, but it would help rule out that it's trying to link up with a wrong version of GTK+ or one that was compiled with a different calling convention/ABI. Both you and @DiepEsc seem to have other GTK+ runtimes in your PATH, so it might be related.

**Comment by colrose** [comment]
@codebrainz  - I uninstalled GTK2-Runtime Win64 and it was removed from PATH . I reinstalled Geany 1.30.1 (after working with 1.29 last night)  - again the process starts but fails (with and without plugins)

No error messages, but did notice that the Windows error reporting runs briefly as a process just before Geany fails.

**Comment by kugel-** [comment]
Did you reboot after removing it from PATH, just to be sure?

**Comment by colrose** [comment]
Sorry @kugel- I had overlooked that! Have done that now and I'm afraid it hasn't made any difference. It must be a local issue or there would be many more reports of this problem. I'm happy to use 1.29 on my laptop and 1.31 on my Linux desktop.

**Comment by codebrainz** [comment]
@colrose can you paste the output from the command prompt that opens when running `"C:\Program Files (x86)\Geany\bin\geany.exe" -v`? It will contain a bunch of lines starting with "Geany:".

**Comment by kugel-** [comment]
@colrose is this still a problem with 1.33?

**Comment by colrose** [comment]
@kugel- 1.33 installed without problem on the same machine
