### ISSUE TITLE
Alphabetic character "<" makes Geany close

### ISSUE THREAD

**Issue by Nilsb13** [geany/geany#1455]
Hi !

on the attached (sorry, I cannot attach PHP file) PHP file, at line 1583,
I have the following code (started before by /*, and finishing after by */)  :
 ` *	V...|.......................Jour courant..................................>|<...................................Lendemain.................................................>|`
When I write the "<" character, on this line 1583, Geany closes.

In /var/log/syslog there is : 
Mar 30 12:58:29 PRINCIPAL kernel: [ 2151.269486] geany[12005]: segfault at 0 ip 00007f1b1a5cf9de sp 00007ffe7d451aa8 error 4 in libc-2.23.so[7f1b1a531000+1bf000]
Mar 30 13:05:45 PRINCIPAL kernel: [ 2586.680237] geany[13373]: segfault at 0 ip 00007fd0b0b929de sp 00007fffe225d0b8 error 4 in libc-2.23.so[7fd0b0af4000+1bf000]
Mar 30 13:08:16 PRINCIPAL kernel: [ 2737.718143] geany[13586]: segfault at 0 ip 00007fd4ff5ae9de sp 00007ffcc369f738 error 4 in libc-2.23.so[7fd4ff510000+1bf000]
and more ...

On this line 1583, " *	V...|.......................Jour courant.....".

I removed the first "<", before the words "Jour courant", just after the first "|" character, and I cannot write it back, because Geany closes each time I trie.

Original was : "V...|**<**.......................Jour courant....."."

If I clic before the second "<" (do not look for the first one, it does not exist anymore), before the word "Lendemain", nothing happen.

If I clic after the second "<"  (do not look for the first one, it does not exist anymore), Geany closes.

If I clic after the last ">" Geany does not close.

Let me know if you want my PHP file.
Thank you for looking about it ...
Nils

**Comment by Nilsb13** [comment]
I removed the "tag pair highlighter plugin for Geany" plugin,
the bug disappeared.

So, this plugin is bugged with "<" Character.

**Comment by Nilsb13** [comment]
I re installed and enabled "tag pair highlighter plugin for Geany" plugin,
bug came back.

I disabled "tag pair highlighter plugin for Geany" plugin,
bug disappeared again.

Yes, the issue is coming from this plugin.

**Comment by elextr** [comment]
Good that you have debugged it to the plugin, now you should report it to the plugins [issues](https://github.com/geany/geany-plugins/issues) list (sorry I don't think Github can transfer issues).

Plugins are maintained by individuals who may not watch the Geany issues.  

Also please include version of Geany and platform you are running on.

**Comment by Nilsb13** [comment]
Done !

=> https://github.com/geany/geany-plugins/issues/553

**Comment by Nilsb13** [comment]
Maybe it would be useful to add https://github.com/geany/**geany-plugins**/issues/ link to https://www.geany.org/Support/Bugs page.

**Comment by eht16** [comment]
> Maybe it would be useful to add https://github.com/geany/**geany-plugins**/issues/ link to https://www.geany.org/Support/Bugs page.

Done.

**Comment by Nilsb13** [comment]
Great !

When I read this page first, I focused my eyes on the first paragraph : 

"Bugs
If you think you found a bug in Geany or if you have a feature to request, please file bugs at the Github issue tracker. You can also feel free to subscribe and write to our mailing list."

I did not read the http links above.

Maybe, add something near "please file bugs at the Github issue tracker".

Like : "please file bugs for Geany at the Github issue tracker, or file bugs for Geany-plugins at the Github issue tracker".

**Comment by Nilsb13** [comment]
and the email I sent to vm at kononenko dot ws

as I loose 2 or 3 hours to find this bug out.
Might be nice to remove this plugin ...


Hi,

if I not wrong you developed "tag pair highlighter" plugin for Geany.
https://plugins.geany.org/pairtaghighlighter.html => The complete up to date list of contacts can be found at <http://kononenko.ws/en/contacts>.

Please, remove this plugin from Geany plugins list.
(or debug it, as you want, can ...)

I lost 2 or 3 hours to understand this plugin was bugged => It makes Geany close.
And it looks like I am not alone in that case.

Have a look to https://github.com/geany/geany-plugins/issues/553
 and at the bottom => Possible duplicate of #442, #446, #130, #989, and #1016.

Thank you.
Nils

**Comment by eht16** [comment]
Ok, I removed the top link to the issue tracker and added a note "see below" so users hopefully see the two links below and can choose which one to use.

**Comment by Nilsb13** [comment]
Cool !

**Comment by codebrainz** [comment]
> as I loose 2 or 3 hours to find this bug out.

This is annoying, yeah.

> Might be nice to remove this plugin ...

The best thing to do when encountering bugs is to update to the latest version (1.27 is 3 releases old and bug fixes aren't backported). This bug was already fixed in [#446](https://github.com/geany/geany-plugins/issues/446). The reason there's so many duplicates is because a lot of people use the plugin and nobody searches the issue tracker before reporting a bug :)

**Comment by Nilsb13** [comment]
Hi codebrainz,

thank you very much for your comment.

I am newbie in world of developing in a group, especially for tools like GitHub and others, as I am working alone, I do not know group's good way of working.
I don't know yet how to use group's tools. That's why I did not search anything in the issue tracker.

For Ubuntu I use, I thought packages where near the last version.
So you are teaching me, it's not the case.

So you encourage me strongly, not to follow Ubuntu packages version, and use the latest stable one of Geany ?

Do you know if there is a PPA for Geany ?
(I will search for it).

Again, thank you to had enlight my point of view.
Nils

**Comment by elextr** [comment]
@Nilsb13 http://www.geany.org/Download/ThirdPartyPackages

**Comment by Nilsb13** [comment]
thank you !

**Comment by Nilsb13** [comment]
I have setup PPA ppa:geany-dev/ppa and update to 1.30.1.
Everything is ok, and plugin pair tag highlighter works well, for sure you were right.

A last question.
I seek the web site, for download pages to find a list of version, unstable, stable, testing.
I did not find this page, where could I know which version is the stable one ?
Where can I find this information ?
Is the ppa:geany-dev/ppa version always the stable one ?

Thanks.

**Comment by elextr** [comment]
@Nilsb13 Geany only releases stable versions (errors and omissions excepted) so just choose the latest

**Comment by Nilsb13** [comment]
Ok, thank you @elextr.
So using PPA, I do not have to choose, I will always get the latest stable one when apt-get update / apt-get upgrade.
If I am not wrong ?

**Comment by elextr** [comment]
I think thats how PPAs work
