### ISSUE TITLE
Column mode not working

### ISSUE THREAD

**Issue by ilpiero** [geany/geany#1468]
Hello,

I'm trying Geany under a fresh Lubuntu install.

SHIFT+ALT+arrow keys has no effect,  not sure what's due to I will try on a clean xubuntu install as soon as possible.

lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 17.04
Release:	17.04
Codename:	zesty

desktop manager is LXDE (lubuntu)

geany -V
geany 1.29 (built on 2016-11-16 with GTK 2.24.31, GLib 2.50.2)

Marco

**Comment by MatrixMike** [comment]
Surely it is only fair to use latest version which is 1.30.1 at the moment - it might not make any diff but ...

Sent by Mike from his i device but you could SMS him on his mobile

**Comment by elextr** [comment]
Not sure what window manager Lubuntu has, but it may be that the window manager is eating the Alt key, some reserve it for their purposes.

**Comment by ilpiero** [comment]
i tried a couple of shortcuts like SHIFT+ALT+W and SHIFT+ALT+L and they both work.
Is there a way i can remap this shortcut for a test? I could not find it in the preferences.
Thanks.

I will try also the latest version.

**Comment by elextr** [comment]
Unfortunately the keyboard selection functions cannot be set by Geany.  Those functions are part of the editing widget that Geany gets from the Scintilla project, they are not our bindings to set.

Strange that other shift+alt codes work but not those, are your arrow keys separate keys or are you using the arrows in the numeric keypad?  If the latter you may need to select/unselect num-lock to make them work.

What keyboard layout are you using?  What locale are you using?

**Comment by ilpiero** [comment]
Hello elextr

I tried both the netbook keyboard and a usb keyboard, same behavior.
Locale is Italian, but I have never faced a problem with this before.
In a few days I'll do some more tests, also I'll try the latest version once the 17.04 Ubuntu PPA is added.

Not a big deal anyway, Geany is a great editor.

Thanks

Marco

**Comment by ilpiero** [comment]
Found the issue, as you suggested the key combination was stolen by the windows manager.
LXDE uses SHIFT ALT ARROW to move the active window between desktops, I'm quite new to LXDE, I didn't knew that.

Marco
