### ISSUE TITLE
Conflicting GLib requirements in HACKING

### ISSUE THREAD

**Issue by vfaronov** [geany/geany#1476]
The [HACKING](https://github.com/geany/geany/blob/master/HACKING) file has this:

> Geany requires GTK >= 2.24 and GLib >= 2.32.

but also this:

> Your code should build against GLib 2.27.3

and this:

> You might want to pass the `-DGLIB_VERSION_MAX_ALLOWED=GLIB_VERSION_2_28` C
preprocessor flag to get warnings about newer symbols from the GLib.

So which is it? 2.32 or 2.28/2.27?

**Comment by elextr** [comment]
Reading the documentation!! Who ever heard of such a thing ;-D  

The code says [2.32](https://github.com/geany/geany/blob/c296efed642611f3dba238c5c576b712786b424e/configure.ac#L73) but clearly some errors have accumulated in the docs.  Feel free to make a pull request correcting them now you have found them.
