### ISSUE TITLE
Shortcut key assignment for a custom command

### ISSUE THREAD

**Issue by exebook** [geany/geany#1483]
I successfully add custom commands to a menu, I have to call them by typing Alt+E+F+S, then selecting a command with arrows and press Enter. But I seem to be unable to assign a mnemonic shortcut key to a label, I am not talking about a global hot key like Control+F11, just a local underscored character, so I can for instance type Alt+E+F+S+B for "Beautify". I tried to set a label with an underscore in it, like "_Beautify" and many other characters, but it does not work.

**Comment by exebook** [comment]
Control+1(2,3) does not work as well.

**Comment by elextr** [comment]
You assign keybindings to up to 9 custom commands in `Menu->Edit->Preferences->Keybindings`.

`CTRL+(123)` are just the defaults for the first three, check they havn't been changed.

**Comment by codebrainz** [comment]
I think for it to work, it has to use [`gtk_menu_item_new_with_mnemonic`](https://developer.gnome.org/gtk3/stable/GtkMenuItem.html#gtk-menu-item-new-with-mnemonic) [here](https://github.com/geany/geany/blob/1.30.1/src/tools.c#L564) instead of `gtk_menu_item_new_with_label`.

**Comment by elextr** [comment]
Yeah, though who wants to type Alt+E+F+S+<something>.  Might as well be using Emacs :wink:.

**Comment by elextr** [comment]
@exebook if your checking shows the default keybindings in place and they don't work, please post the version of Geany and the OS you are using.

**Comment by exebook** [comment]
@elextr geany 1.30 (git >= 6f9b34d)
Ubuntu 16.04 LTS

**Comment by exebook** [comment]
Ok, I got it, it was disabled in preferences. Thank you for the hint.
