### ISSUE TITLE
Scope: unknown?

### ISSUE THREAD

**Issue by LadyAleena** [geany/geany#1484]
Hello.

One the status bar where one can see the line number, column, selection, etc. there is a value called Scope. When I am within a perl subroutine the scope is the subroutine. However, if the cursor is not within a subroutine, the scope would be the whole file but not unknown in my opinion.

Thanks for reading.
LA

**Comment by LarsGit223** [comment]
Sorry, but I voted for not changing this.

IMHO the scope shows the context inside of the file. And the filename is already shown in the title of the tab. So I think it shouldn't be duplicated in the scope field.

**Comment by kugel-** [comment]
I agree with @LarsGit223, will close this in a week unless somebody objects.

**Comment by elextr** [comment]
I don't know about Perl, but in many languages a file is not a scope, so "unknown" is more correct, and in other languages the scope is a module or package name that derives from the filename, eg Java and in others its derived from the path eg Python.  So unless someone is going to make the message filetype dependent I agree with @kugel- and @LarsGit223 that this isn't a good idea.

**Comment by LarsGit223** [comment]
@kugel-: please close this.

**Comment by kugel-** [comment]
Closing as it's working as expected. I'm open to a PR that displays a module-level scope (as suggested by @elextr).

**Comment by elextr** [comment]
@kugel- at least in C++ it already shows namespace (the closest C++ currently comes to modules) scopes.  Are you proposing that when the cursor is outside any explicit construct the scope will say "File xxx" for C/C++ since it isn't a named scope, "Module xxx" for those languages where that is the case etc?
