### ISSUE TITLE
Spell check marks words in single quotes as misspelled

### ISSUE THREAD

**Issue by LadyAleena** [geany/geany#1486]
When spell check is on, any word in single quotes is seen as misspelled. If the word is in double quotes it is not. Please see the screen shot.

Thanks for reading,
LA

![geanyspellcheck](https://cloud.githubusercontent.com/assets/123256/25632335/47424582-2f41-11e7-8066-cb5a42007f6a.png)

**Comment by elextr** [comment]
Spellcheck is a plugin in the geany plugins project which has its own issue tracker, please report it [there](https://github.com/geany/geany-plugins/issues).
