### ISSUE TITLE
ctrl + l does not open Go to line... dialog box

### ISSUE THREAD

**Issue by LadyAleena** [geany/geany#1488]
When I try to use ctrl + l go open the Go to line... dialog box, the box does not appear.

**Comment by frlan** [comment]
It's not a dialogue that appears, but cursor jumps to a little box inside tool bar where you can enter the line number. See screenshot where I've put 22 in
![gotoline](https://cloud.githubusercontent.com/assets/1010248/25637872/b5887ea4-2f86-11e7-878c-591d88d5ca1a.png)

**Comment by LadyAleena** [comment]
I didn't even know that box was there. I hardly look that far right on that bar.
