### ISSUE TITLE
Geany prevents launching multiple instances

### ISSUE THREAD

**Issue by chrisspen** [geany/geany#1493]
I'm trying to work on multiple projects at the same time, and currently Geany makes this a little difficult.

If I specify the project file in the Geany call, e.g.

    geany myproject.geany &

Geany will re-use the running process and force me to close the current project before loading the new one.

If I launch a blank geany process:

    geany &

then I can run an arbitrary number of Geany instances, but I have to manually load the project via the Project->Open dialog.

Can you please remove the check to re-use the current running Geany instance, and close the current project? I can't imagine why anyone would want or need that, since a single Geany instance can't handle more than a single project at once.

**Comment by codebrainz** [comment]
did you try `-i, --new-instance         Don't open files in a running instance, force opening a new instance`?

**Comment by elextr** [comment]
Or -c to use a different configuration in each instance, then each will remember which project was open.
