### ISSUE TITLE
Geany generates files with random extension when saving it

### ISSUE THREAD

**Issue by DiyuanLu** [geany/geany#1506]
The version number of Geany: 1.27
The version number of GTK+ (can be printed with geany -V): geany 1.27 (built on 2016-04-17 with GTK 2.24.30, GLib 2.48.0)
Your OS details: Ubuntu 16.04 LTS
The filetype the bug occurred with (if applicable): every type, .py, .txt. ...
Problem description: geany generates a new file(with a lock and a cross symbol ) with a random extension after the original extension every time when I save the file. And I can't delete the new-generated files. When I do, it shows "testtest.txt.GU4Q0Y” can't be put in the Rubbish Bin. Delete it permanently instead?" and the error details is "Error moving file to wastebasket: No such file or directory"

**Comment by elextr** [comment]
Check you do not have backups enabled on the save-actions plugin.

**Comment by DiyuanLu** [comment]
In my save-actions, nothing is enabled.

**Comment by elextr** [comment]
Hmm, save_actions uses a time and date extension anyway, not a random one.

By default Geany does not generate those files, so it must be some plugin or setting.

Try a completely default Geany by running `geany -c /tmp/non_existant` and see if it still generates those files.

If it doesn't then compare the settings and plugins with your normal ones to see what you have that is not default and causes it.

**Comment by DiyuanLu** [comment]
Hi,
I compared the settings, there is no abnormality.

this is the screenshot of the generated files. Still it has this problem.

the utilfunctions.py is the original file.

**Comment by elextr** [comment]
Just to be completely clear running `geany -c /tmp/something_that_does_not_exist` opening a file, making a change and saving it generates a version with the random extension?

If that happens it is something outside Geany that is doing it, if you ran Geany with the command above it will use totally default settings, and nothing in Geany's default settings generates such files.

**Comment by DiyuanLu** [comment]
sorry that was not clear.
When I run
>>geany -c /tmp/something_that_does_not_exist
it opened a file and after saving it, it didn't have that problem.
Only with my own files.

How can I go back to default settings?

**Comment by elextr** [comment]
On a Linux system the normal Geany user configuration is  in `~/.config/geany` and the easiest way is to delete it  when geany is NOT running (note its a directory, not just a file, you should delete the directory and all its contents). When you next start Geany it will create a new configuration with default values.
