### ISSUE TITLE
Feature Request: opening binary files

### ISSUE THREAD

**Issue by SarenT** [geany/geany#1508]
Hi,

Most text editors allow binary files to be opened. Most of the text is gibberish but they display it. But Geany simply rejects to display it because the file is binary. I think it would be nice if Geany would also show the file. One possible use case is to see file headers (for instance for PDFs the first couple of characters indicating that it is PDF).

Best,
SarenT

**Comment by elextr** [comment]
This has been rejected before.  Geany and its libraries are C and use null terminated strings.  Therefore file contents cannot contain zero bytes, so any file that contains zero bytes is rejected.

To accept zero bytes would require a considerable re-write of Geany.

**Comment by rogerjames99** [comment]
It only takes a single null character to throw geany. This means it frequently won't open linux syslog files.
Why not of to to make temporary copy of the file with the offending chars decded to <0xnn> and open that instead. That cannot be too difficult.,

**Comment by nazar-pc** [comment]
@rogerjames99, I agree with that.
Even read-only mode for binary files would be already useful.

**Comment by codebrainz** [comment]
Duplicate of #618, #1708, #1709 and surely others.
