### ISSUE TITLE
Geany crashes on Project > Open

### ISSUE THREAD

**Issue by Laurent3170** [geany/geany#1509]
Using Ubuntu 16.04 and Geany 1.30.1, when I have an opened project and I want to open a new one, I go under `Project > Open` then it displays the dialog box, and crashes 1-2 seconds after by closing its window.
When I use `Recent projects` it works well, but the list is not long enough to keep all my projects.

**Comment by elextr** [comment]
Needless to say it doesn't happen here.

Can you run geany under gdb and get a backtrace when it crashes.

**Comment by Laurent3170** [comment]
@elextr I'm not familiar with gdb, as I didn't know about it, but I think I have what you need, if not, let me know
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/i386-linux-gnu/libthread_db.so.1".
[New Thread 0xb62ceb40 (LWP 12545)]
[New Thread 0xb58ffb40 (LWP 12546)]
[New Thread 0xb50feb40 (LWP 12547)]
[New Thread 0xaf7ebb40 (LWP 12550)]
[New Thread 0xaeec6b40 (LWP 12551)]
[New Thread 0xab99ab40 (LWP 12554)]
[New Thread 0xab199b40 (LWP 12555)]
[New Thread 0xaa998b40 (LWP 12556)]
[New Thread 0xaa197b40 (LWP 12557)]
[New Thread 0xa9996b40 (LWP 12558)]
[New Thread 0xa9195b40 (LWP 12559)]
[New Thread 0xa8994b40 (LWP 12560)]
openjdk version "1.8.0_131"
OpenJDK Runtime Environment (build 1.8.0_131-8u131-b11-0ubuntu1.16.04.2-b11)
OpenJDK Server VM (build 25.131-b11, mixed mode)

(geany:12544): Pango-WARNING **: Invalid UTF-8 string passed to pango_layout_set_text()
[New Thread 0xa6ce9b40 (LWP 12585)]
[New Thread 0xa644bb40 (LWP 12607)]
[New Thread 0xa5c4ab40 (LWP 12608)]
[Thread 0xa5c4ab40 (LWP 12608) exited]
[Thread 0xa6ce9b40 (LWP 12585) exited]

Thread 1 "geany" received signal SIGSEGV, Segmentation fault.
0xa7098c77 in ?? () from /usr/lib/i386-linux-gnu/geany/projectorganizer.so
```

**Comment by elextr** [comment]
It shows the crash is in the project organiser plugin, please confirm this by testing with and without the plugin enabled.

Project organiser is part of the geany-plugins project which has its own issues [here](https://github.com/geany/geany-plugins/issues) if its confirmed above please report there as each plugin has its own maintainer who may or may not be watching the main Geany issues.

**Comment by Laurent3170** [comment]
I was not sure it was a plugin. As I can't test opening a project without the plugin enabled, I will report on plugin page.
Thanks
