### ISSUE TITLE
Translation error : italian

### ISSUE THREAD

**Issue by francescosassi** [geany/geany#1511]
I'm using the italian translated version of Geany 12.23.1 on lubuntu.
When i compile a .c program, it displays this line on the compiler text area:
gcc -Wall -o "prova" "prova.c" (nel direttorio: /home/user)
but this translation is completely wrong. It should be changed with
gcc -Wall -o "prova" "prova.c" (nela directory: /home/user)
or
gcc -Wall -o "prova" "prova.c" (nella cartella: /home/user)

**Comment by elextr** [comment]
1.23.1 I presume you mean, that is a very old version.  The current version it.po uses "nella cartella". 
 Thank you for your input.
