### ISSUE TITLE
Running a program (F5) doesn't work with terminal command with quotes

### ISSUE THREAD

**Issue by HybridDog** [geany/geany#1515]
![2017-06-12-211637_1920x1080_scrot](https://user-images.githubusercontent.com/3192173/27050964-ad9e17d2-4fb4-11e7-9159-fa44998f28be.png)

Building and Compiling works, but running doesn't. When I press F5, a lxterminal window appears with nothing in it.
https://github.com/lxde/lxterminal/issues/23
The problem doesn't occur after removing the quotes.

**Comment by elextr** [comment]
What command is in menu->build->set build commands->execute and does that command work on the command line?

**Comment by LifeSoftServ** [comment]
Have you installed LUA since your re-install?

**Comment by HybridDog** [comment]
elextr, LifeSoftServ, the execute command is the same as when l didn't have the problem yet. Running in geany doesn't work with any programming language.

l think the problem has something to do with the terminal command: `x-terminal-emulator -e "/bin/sh %c"`
When l e.g. execute `x-terminal-emulator -e "/bin/sh /bin/ls"` in a terminal, l get the same problem.

**Comment by elextr** [comment]
@HybridDog `x-terminal-emulator -e "/bin/sh /bin/ls"` is wrong, the argument to /bin/sh needs to be a script with shell commands in it, not an executable program.

**Comment by HybridDog** [comment]
You're right.
Anyway, when l run `/bin/sh tmp.sh`, the script is executed in the terminal, but when executing `x-terminal-emulator -e "/bin/sh tmp.sh"`, a new terminal window appears which does nothing.

**Comment by elextr** [comment]
Well probably best to raise that on x-terminal-emulators issues.

**Comment by HybridDog** [comment]
x-terminal-emulator just executes the default terminal, which is lxterminal in my case.
If l replace `x-terminal-emulator` with e.g. `xterm`, the problem doesn't appear.

l just saw, there's already an issue: https://github.com/lxde/lxterminal/issues/23
The problem doesn't appear if l remove the quotes. Executing multiple commands seems also to work without quotes.

**Comment by elextr** [comment]
So solved.

**Comment by DS-Minetest** [comment]
I changed the execute command in the settings from `"./%e"` to `./%e` but somehow it doesn't fix the problem, do I have to remove the quotes somewhere else?
