### ISSUE TITLE
Line Content and Line Number is displayed twice or Lines disappear 

### ISSUE THREAD

**Issue by RalphBike** [geany/geany#1521]
With "Visueller Zeilenumbruch" (Visual Linebreak/LineWrap/Wordwrap?) activated, sometimes lines and line numbers are displayed twice or not at all.

How to do it with double lines:
A) Create a document with 6 lines:
1: some content
2: blank
3: some other content
4: blank
5: some other content
6: blank

B) type more content in line 1 until the visual linebreak kicks in. then remove some content from line one until the text fits again into line 1. now line 3 is displayed twice. no navigate through the lines and watch line 3 being corrected and line 5 being displayed twice.

Sorry, I do not have a howto for missing lines. Will provide it once I have it.

Version is 1.30.1

**Comment by RalphBike** [comment]
Howto for missing line:

1:Veryveryverylongline
2:AAAA
3:BBBB
4:CCCC

Now again, type in line one until the linebreak starts, then remove content until the text fits into one line again. Then this is displayed:

1:Veryveryverylongline
2:AAAA
3:BBBB
3:BBBB

When going through the lines with the cursor, I even get this ( not the additonal line#4 without content):

1:Veryveryverylongline
2:AAAA
3:BBBB
4:CCCC
4:

**Comment by codebrainz** [comment]
I can't reproduce, it sounds like maybe a flaky plugin. Can you try and run Geany with plugins disabled (ie. `geany -p`)?

**Comment by elextr** [comment]
And what system are you running on and what version of Glib and GTK (near top of menu->help->debug messages)?

**Comment by RalphBike** [comment]
With geany -p the effect is still present.

07:51:31: Geany INFO		: Geany 1.30.1, de_DE.utf8
07:51:31: Geany INFO		: GTK 2.24.31, GLib 2.52.2 

System is Manjaro XFCE 64 Bit, with the latest updates.

**Comment by RalphBike** [comment]
Here is an animted version. Towards the end, I am navigating down with the cursor (cursor is not visible in the screenshots)

![geany-1521](https://user-images.githubusercontent.com/17691743/27369762-b4a8fa96-5659-11e7-85e9-10000feef2fb.gif)

**Comment by vfaronov** [comment]
I have some form of this problem, too (Geany git, GTK 2.24.30, GLib 2.48.2):

![lines-bug](https://user-images.githubusercontent.com/300211/27369865-8a0a20c2-5662-11e7-8464-eb17342be24e.gif)

This used to happen to me often with Geany 1.27. I thought I got rid of the problem on Geany master, but apparently not.

**Comment by elextr** [comment]
Confirmed with git version GTK 2.24.30, GLib 2.48.2

Its the blank line thats the key

**Comment by elextr** [comment]
Does not happen with Geany git and GTK 3.18.9, GLib 2.48.2

**Comment by elextr** [comment]
@vfaronov @RalphBike does either of you have a GTK 2 version of Scite in your distributions repos? The one in mine is GTK3 and as I said above that works.  If so can you try it in Scite?

**Comment by elextr** [comment]
Still happens with Scintilla 3.7.5.

**Comment by b4n** [comment]
https://sourceforge.net/p/scintilla/bugs/1949/ ?

**Comment by vfaronov** [comment]
I built SciTE with GTK+2 and I can reproduce [the problem](https://github.com/geany/geany/issues/1521#issuecomment-309974845) there. But applying the patch from [Scintilla #1949](https://sourceforge.net/p/scintilla/bugs/1949/) doesn’t fix it (although it does fix the problem described in Scintilla #1949).

**Comment by elextr** [comment]
@vfaronov in that case can you report it to Scintilla with your description of the problem.

**Comment by vfaronov** [comment]
@elextr Done. I was mistaken, [Scintilla #1949](https://sourceforge.net/p/scintilla/bugs/1949/) is not fixed for me after all, so I added a comment there.

**Comment by codebrainz** [comment]
This was [fixed in Scintilla](https://sourceforge.net/p/scintilla/code/ci/ebec660dcf48ec92301441140550f67d3e7ceb29/). Can anyone confirm the fix is now in Geany so we can close this issue?

**Comment by RalphBike** [comment]
Hi, seems to be fixed. Tested with V. 1.34.1
