### ISSUE TITLE
running 2 commands on same line build compile execute

### ISSUE THREAD

**Issue by nextlamecoder** [geany/geany#1524]
hi
im trying to use geany on winxp to run 2(multiple) commands on same(execute) line like so
`bcc32 "%f" && "./%e" && del *.obj *.tds`
and it does not work; the cmd windows that pops spits a message like 
`&& was unexpected this time`
ive also tried running with mingw with same result
the command linkage works for geany 1.24 - 1.28; it does not for 1.29 - 1.30.1

**Comment by elextr** [comment]
The previous versions of Geany used the `system()` call to run commands on Windows.  That passes the command to the command parser so it will understand the `&&`.  But using `system()` had many other problems, losing the build command output, inconsistent quoting etc.

So now Geany spawns a single executable directly the same as was always done on Linux and OSX, which provides better control and reliability but loses the ability to run more than one command (which never existed on Linux and OSX anyway).

To run more than one command you either need to make the command run a script, or use make.

**Comment by nextlamecoder** [comment]
i dont know you .. but i HAVE to use that feature.. it saves me at least 1 extra key press
the feature is available on linux debian8 geany 1.24 .. old version..
as it is i downgraded to 1.28.. ill think about using a script later
ty for help

**Comment by codebrainz** [comment]
You could just send the command to the shell directly, ex: `cmd /C bcc32 "%f" && "./%e" && del *.obj *.tds`

**Comment by nextlamecoder** [comment]
i dont want to switch windows back and fort its a hassle.. i barely settle on geany from to many editors.. i was looking for something fast loading and basic(accessible) IDE commands

**Comment by codebrainz** [comment]
I don't understand, just stick `cmd /C ` on the front of your given command and it should work (I only tested it directly from the command prompt).

**Comment by nextlamecoder** [comment]
so basically theres no way to execute more then one command on a line with new geany.. very bad.. really sad.. old is gold.. issue closed

**Comment by codebrainz** [comment]
Well, no there isn't, except for the 3 ways suggested to you.

**Comment by codebrainz** [comment]
Confirmed prepending `cmd /C ` allows running multiple commands the same as on the command prompt. Am I missing something? Do you want to do something different than run multiple programs in a single build command?

**Comment by nextlamecoder** [comment]
@codebrainz ive tested `cmd /C bcc32 "%f" && "./%e" && del *.obj *.tds` inside geany>set build commands>execute and it doesnt work, are you sure it works for you? maybe i miss something

it does work on windows>cmd.exe window;

**Comment by codebrainz** [comment]
It works with `cmd /C echo "Hello" && echo "World"`.

**Comment by nextlamecoder** [comment]
@codebrainz ive just redownloaded geany portable 1.30.1 from portableapps.com and retested your solution inside geany>set build commands>execute line and it does not work;
i am on winxp sp3..

**Comment by codebrainz** [comment]
I don't know about WinXP or portable app, but it works for the example I gave above. Does that work for you? If not, what does it do?

**Comment by nextlamecoder** [comment]
@codebrainz the example you gave me has same output described in my first post

anw
workaraund1 > use geany 1.28 - works as required
workaround2 > geany>set build commands>execute line `cmd /c c:\bat.bat "%f" "%e"`
the content of c:\bat.bat is `cmd /c bcc32 %1 && "./%2"`

**Comment by codebrainz** [comment]
Maybe try using the real Geany release rather than some 3rd party thing. It's possible they do some weird patches or stuff. I tested on Win7, but I don't expect there to be any difference for this.

**Comment by nextlamecoder** [comment]
@codebrainz ive also tested latest and greatest from geany.org and it doesnt work on winxp; ive also tested on win7 and it doesnt work; are u sure you have geany version 1.30.1 or 1.29+

**Comment by codebrainz** [comment]
Yes, I tested my above `echo` test on Windows 7 64-bit with Geany 1.30.1 and it prints "Hello" and "World" on two separate lines. If it doesn't do that for you on Win7, then something else is going on.

**Comment by nextlamecoder** [comment]
@codebrainz can you try a clean virtualbox setup because for me it sure doesnt work; maybe you have something extra; both my test environments(xp-32 and w7-64) are clean(just os and vbox additions) virtualbox on debian8-64; ive also installed all vc++ redistributable and still doesnt work
