### ISSUE TITLE
Laggy scrolling on Wayland

### ISSUE THREAD

**Issue by wmww** [geany/geany#1526]
OS: Arch Linux
version: 1.30.1 gtk3 from Arch's AUR

With GTK3 on Wayland, vertical scrolling is laggy. When scrolling slowly, its fine but as soon as I scroll faster (possibly one line per frame is the threshold) it starts lagging. It immediately comes to the correct position when I stop scrolling, and occasionally updates while I'm scrolling (about 1fps). Everything works if the window is smaller then half the screen (screen resolution is 2560x1600), but there is still high CPU usage while scrolling.

I encounter the problem on Sway and Gnome on Wayland, but there is no issue on XFCE4 with X11.

Based on the high CPU usage and dependence on window size, my guess is that it is CPU rendering and, if more scroll events have come in before it is done rendering, it renders the next frame and keeps going until it has caught up.

**Comment by codebrainz** [comment]
As Geany doesn't do anything with the scrolling or rendering, this is almost surely an issue in [Scintilla](https://sourceforge.net/p/scintilla/bugs/) or [GTK+](https://bugzilla.gnome.org/). It might also be related to some kind of Xlib compatibility mode in Wayland, unless Geany and Scintilla don't use any Xlib calls, it's probably a kind of emulation or something.

**Comment by elextr** [comment]
As @codebrainz said the scrolling is done by the Scintilla editing widget we use.  Possibly try the Scite editor which is the reference platform for Scintilla and see if the problem exists there too.

One thought is that IIRC GTK on X11 aggregated mouse moves and scrolls, but maybe that isn't working on Wayland, so Scintilla is responding to every scroll event individually.

Also I thought Scintilla had a smooth scrolling setting, but maybe thats only on its OSX port since I can't see it just now.

**Comment by elextr** [comment]
@william01110111 note also that AFAIK none of the regular contributors use wayland, so you will probably need to do the search for possible solutions.

**Comment by william01110111** [comment]
I disables line wrap and most other features with little to no effect. I don't have a problem when using a normal mouse scroll wheel, only with high precision touch pad scrolling (which presumably sends many more scroll events). I can't find a GTK3 version of Scite, so I can't test that on Wayland.

**Comment by elextr** [comment]
Wow, Arch, the bleeding edgest of distros only has GTK2 Scite, but Ubuntu LTS the boring edgest of distros has only GTK3 Scite :grin:

I'm afraid I don't know anything about wayland to suggest where to go from here, maybe someone else has ideas?

**Comment by william01110111** [comment]
Strange there is no GTK3 SciTE in the AUR. I tried to compile SciTE from the latest source, which worked but still gave me GTK2. No instructions on how to build for or run with GTK3. Anyway, this but doesn't make Geany unusable, its just annoying.

**Comment by elextr** [comment]
`make GTK3=1` or something similar according to the README

**Comment by william01110111** [comment]
Thanks. Got it running, but something strange is happening. SciTE is not scrolling at all. Everything else works fine.

**Comment by elextr** [comment]
Not even with the mouse?

I suspect Scite hasn't been tried  much on Wayland either.

**Comment by william01110111** [comment]
No, mouse works. Just not with scroll wheel.

**Comment by william01110111** [comment]
Looks like I'm an idiot and cloned an old, non official version of SciTE. I'm running into https://sourceforge.net/p/scintilla/bugs/1901/. I have to go to bed now, but I will try to get newer SciTE up and running and test it out when I have a chance.

**Comment by elextr** [comment]
Scintilla uses hg, not Git, so unless you want to use  hg just grab the TGZ file off the Scintilla website.

**Comment by wmww** [comment]
Update: this problem appears to now be completely resolved. The `geany-gtk3` in the AUR (version 1.31-1) still has the problem, but it is fixed when building from source or using `geany-gtk3-git`.
