### ISSUE TITLE
Feature Request: Open geany with search dialog in xfce panel

### ISSUE THREAD

**Issue by krizoek** [geany/geany#1538]
If i leave geany for another application(for example firefox) and click on the tasklist in the panel/taskbar for to reopen geany, then only the search dialog appear on the screen without the main editor window. the same doesn't happen if i use alt+tab to go back to geany; then both the main editor window of geany and search dialog appear together

**Comment by krizoek** [comment]
i noticed this with another application (qalculate), which i also compiled with gtk3. i'm not sure if it's a general x-problem, gtk problem, or xfce. but i'm contacting something to do with xfceith xfce now

**Comment by elextr** [comment]
Cannot reproduce with Cinnamon desktop, suspect its an xfce error.

**Comment by eht16** [comment]
Did you have the search dialog opened before?
Or did clicking on the Geany item in the tasklist open the search dialog initially?

Just asking to have a precise way to reproduce.

**Comment by krizoek** [comment]
yes, i had the dialog open after going into the editor. but if i click the tasklist after going to another software and back, i only get the search dialog. which i have to close in order to get back to the main editor.

i have tried some different versions/new ones of xfce. but the situation remains the same, ty

**Comment by krizoek** [comment]
dev-util/geany-plugins gtk3 automark commander gtkspell defineformat enchant overview
dev-util/geany gtk3

here is a list of the flags used during compilation

**Comment by elextr** [comment]
The search dialog is non-modal to allow mixed searching/editing without reopening the dialog.

It would appear that XFCE may be getting confused by that, as I said it works on Cinnamon.

**Comment by codebrainz** [comment]
@krizoek what version of Geany are using? Also what version of GTK+ 3, and which window manager are you using, as well as which distro?

**Comment by codebrainz** [comment]
Also, are you using multiple desktops?

**Comment by codebrainz** [comment]
Also, are you on Linux or another *nix?

**Comment by eht16** [comment]
The output of `xfconf-query --list -c xfwm4 -v` could also be interesting. I suspect a specific Xfwm4 setting which is causing this bevahior.
Interesting candidates are: `/general/activate_action`, `/general/focus_hint`, `/general/focus_new`, `/general/prevent_focus_stealing`.

**Comment by krizoek** [comment]
i'm not really sure what i did, but i got it working. maybe some test packages from xfce made it not fully functional, i did revert back to some former versions of xfwm; but i compiled both xfce and geany with a new gcc as well (currently gcc 6.4). i had tried 7.1 and 6.3 before when i had the trouble. i'm running gentoo

ty for all your help. 

This is xfwm4 version 4.12.3 (revision 7fdcb53) for Xfce 4.12
        Released under the terms of the GNU General Public License.
        Compiled against GTK+-2.24.31, using GTK+-2.24.31.

xfconf-query --list -c xfwm4 -v
/general/activate_action                 bring
/general/borderless_maximize             true
/general/box_move                        false
/general/box_resize                      false
/general/button_layout                   O|SHMC
/general/button_offset                   0
/general/button_spacing                  0
/general/click_to_focus                  true
/general/cycle_apps_only                 false
/general/cycle_draw_frame                true
/general/cycle_hidden                    true
/general/cycle_minimum                   true
/general/cycle_preview                   true
/general/cycle_tabwin_mode               1
/general/cycle_workspaces                false
/general/double_click_action             maximize
/general/double_click_distance           5
/general/double_click_time               250
/general/easy_click                      Alt
/general/focus_delay                     250
/general/focus_hint                      true
/general/focus_new                       true
/general/frame_opacity                   100
/general/full_width_title                true
/general/horiz_scroll_opacity            false
/general/inactive_opacity                100
/general/maximized_offset                0
/general/mousewheel_rollup               false
/general/move_opacity                    100
/general/placement_mode                  center
/general/placement_ratio                 45
/general/popup_opacity                   100
/general/prevent_focus_stealing          false
/general/raise_delay                     0
/general/raise_on_click                  true
/general/raise_on_focus                  false
/general/raise_with_any_button           true
/general/repeat_urgent_blink             false
/general/resize_opacity                  100
/general/scroll_workspaces               true
/general/shadow_delta_height             0
/general/shadow_delta_width              0
/general/shadow_delta_x                  0
/general/shadow_delta_y                  -3
/general/shadow_opacity                  50
/general/show_app_icon                   true
/general/show_dock_shadow                true
/general/show_frame_shadow               true
/general/show_popup_shadow               false
/general/snap_resist                     false
/general/snap_to_border                  true
/general/snap_to_windows                 false
/general/snap_width                      12
/general/sync_to_vblank                  true
/general/theme                           Elberg
/general/tile_on_move                    true
/general/title_alignment                 center
/general/title_font                      Sans Bold 11
/general/title_horizontal_offset         0
/general/titleless_maximize              false
/general/title_shadow_active             false
/general/title_shadow_inactive           false
/general/title_vertical_offset_active    2
/general/title_vertical_offset_inactive  2
/general/toggle_workspaces               false
/general/unredirect_overlays             true
/general/urgent_blink                    false
/general/use_compositing                 true
/general/workspace_count                 1
/general/workspace_names                 <<UNSUPPORTED>>
/general/wrap_cycle                      true
/general/wrap_layout                     true
/general/wrap_resistance                 10
/general/wrap_windows                    true
/general/wrap_workspaces                 false
/general/zoom_desktop                    true
