### ISSUE TITLE
[Minor enhancement] Easily show the status of vte-support in the given geany-instance at hand (whether vte was found, whether geany was compiled with vte support etc..)

### ISSUE THREAD

**Issue by shevegen** [geany/geany#1545]
Hello Geany Devs,

Feel free to close this issue if you feel that the time 
investment or the functionality is not worth to be had
for the geany codebase.

Situation: I have just compiled geany successfully (again,
on a new computer actually).

I am not yet sure whether vte was found or not by geany.
I assume that it should work on my system; mate-terminal
starts fine and I can use it, and I think that mate-terminal
also makes use of vte.

Would it be possible to somewhere add some indicator as
to whether geany:

(a) has been compiled with VTE support or not
(b) whether libvte.so was found?

The reason I would like to have these two parts as indicator
whether everything worked fine, as far as geany is concerned.
Right now I am trying to find vte ... :D

I do not have a personal preference as to where the information
is stored. Perhaps a small mini-widget could be added that
displays this information, e. g. compile-time information
how geany was compiled. Vim has something similar on the
commandline, e. g. if you do "vim --version", you get a 
lot of information such as a "Compilation:" setting that
tells you with which options vim was compiled.

As for whether libvte.so was found, perhaps a simple widget
in preferences could be used, in the "Terminal" subsection.

For example, if libvte.so (or vte.so, whatever the name was)
was not found, a simple mini-widget could be shown under
the Terminal subsection part, at Preferences, notifying
the user that vte is unavailable in some red colour, or
red colour of the widget's border.

I am not sure if this is actually worth to file an issue
request but as stated above, just feel free to close it
at any moment in time!

**Comment by elextr** [comment]
If Geany has been compiled with VTE support on startup `Help->debug messages` will show the version of libvte loaded, or a message saying could not load or "Disabling terminal support" if its disabled by the preference or CL option.  No message means it was not built with support.

Support is added if libvte is found at configure time and VTE is enabled (the default).  Configure summary shows if it will be built with VTE support.  If it says "no" there may be more useful information buried in the detail of the configure run.

**Comment by eht16** [comment]
@shevegen do you agree that the log messages in `Help->debug messages` are enough for debugging the VTE libary loading or do you still need more?
IMO this is enough; the most obvious thing to check is the existence of the terminal tab. And if it is missing, the user knows there is something wrong or she just disabled the VTE in the preferences which is easy to check.

IMO 2, some widget to show whether the VTE library could be loaded or not is not necessary at all, as you already know that it isn't loaded properly if the terminal tab is missing.
