### ISSUE TITLE
Missing PHP Keywords

### ISSUE THREAD

**Issue by klaxian** [geany/geany#1546]
Many PHP keywords are missing from the definition. Some of the missing keywords are new for PHP 7.x, but others are old.

**Comment by klaxian** [comment]
The patch to fix this is attached:
[geany_php7_keywords_patch.txt](https://github.com/geany/geany/files/1156411/geany_php7_keywords_patch.txt)

**Comment by klaxian** [comment]
Patch attached:
[geany_php7_keywords_patch.txt](https://github.com/geany/geany/files/1156416/geany_php7_keywords_patch.txt)

**Comment by eht16** [comment]
Would you mind to update your patch with:
- sort the list alphabetically, this makes future changes easier and less error-prone
- mention the source of the keywords
- ideally make a pull request for your change

Thanks.

**Comment by klaxian** [comment]
I already sorted the list alphabetically. Did you find a mistake? I created PR #1547 for this. I will post a comment with justification as you requested.

**Comment by eht16** [comment]
Sorry about the note about sorting, I confused myself while reading the diff :(.
Thanks for the PR.
