### ISSUE TITLE
Feature Request: Allow adding toolbar icons for frequent custom build / compile / etc actions

### ISSUE THREAD

**Issue by willbprog127** [geany/geany#1550]
Geany is my all-time favourite IDE for C, C++, Python, HTML, JavaScript and just about anything else that requires a high-powered text-editor.  Thanks!

What would make Geany even better is if part of the main toolbar (maybe passed the search boxes) could be used to add additional buttons for build commands that aren't just 'Build' or 'Compile'.  Just like the build commands are customisable, I'd like to add toolbar buttons for custom per-project build commands that I use often.  Maybe make it a plug-in!

Thanks for a great IDE! 😄

**Comment by willbprog127** [comment]
Languished too long and no interest.  Closing.

**Comment by codebrainz** [comment]
Thanks for updating the issue.
