### ISSUE TITLE
White text when printing, if "highlighting_invert_all=true"

### ISSUE THREAD

**Issue by fox0** [geany/geany#1551]
```
$ geany -V
geany 1.24.1 ((собрано Apr 19 2014 или позднее)GTK 2.24.23, GLib 2.40.0)
$ uname -a
Linux 207-dev 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) i686 GNU/Linux
$ cat test.txt
It is text.

Просто текст.
$ cat .config/geany/geany.conf | grep inv
highlighting_invert_all=true
fif_invert_results=false
$ geany test.txt
```
1) Ctrl+P
2) print in file:
[test.pdf](https://github.com/geany/geany/files/1161171/test.pdf)

**Comment by elextr** [comment]
I presume you are using the default colour scheme where text is black, so inverting it is white and the background is black.

But for printing the background is deliberately forced to white to avoid emptying the black toner cartridges or ink tanks by printing the whole background black.  So you get white on white, and as PDF is a faithful(ish) representation of the printed page it does the same.

So this is the intended result.
