### ISSUE TITLE
Filetype file editing overrides filetype changes with new versions of Geany

### ISSUE THREAD

**Issue by elextr** [geany/geany#1552]
When `Tools->Configuration Files ...` is used to edit a config file it is copied in its entirety to the buffer, so when it is saved it overrides all the settings in the system filetype file, not just the ones that the user changes.  So system filetype files distributed with new versions of Geany will be ignored.

Suggest when the file is loaded into the buffer it be prefixed by `# ` to make all contents comments, so the user only need uncomment those they edit and so only those entries will override new system files.

**Comment by eliardocosta** [comment]
@elextr I was trying to set Julia in Geany in `Tools -> Configuration Files`, I open and save `filestypes.common` for accident and now I can't open Geany. Just try reinstall but with no success. When I try open Geany in terminal I see this:
```
Geany:ERROR:highlighting.c:861:styleset_from_mapping: assertion failed: (ft_id != GEANY_FILETYPES_NONE)
```
Can someone help me fixing it? Thanks!

**Comment by elextr** [comment]
The edited `filetypes.common` is saved in your user config directory and overrides the system file.  Delete the one in the user config.

**Comment by eliardocosta** [comment]
Thank you for your reply! I deleted the file but the problem continues :/

**Comment by elextr** [comment]
@eliardocosta then make a specific issue, stop hijacking this one.
