### ISSUE TITLE
How to open a new file in a concrete Geany instance?

### ISSUE THREAD

**Issue by fjvico** [geany/geany#1553]
There are two or more Geany instances running in a given X display. When `geany file` is invoked, `file` always opens up in the same instance (the oldest one, no matter if another one is the active window). Similarly, `geany --list-documents` refers only to the oldest one. This Geany supports sockets.
PIDs and window PIDs are available for all instances, how to open `file` in the instance given by, say, its window PID?

**Comment by elextr** [comment]
An instance is identified by the socket file, so you can either specify socket files with [`--socket-file=`](http://www.geany.org/manual/current/index.html#command-line-options) on the command line or if your instances use different config directories (recommended) then specifying the config will do the same as a link to the socket file is made in the config dir as well.

**Comment by fjvico** [comment]
Yes, they use different configuration directories. Then, `geany --socket-file <configdir>/geany_socket_HP2__0 file` is the way to open in a concrete instance.

**Comment by elextr** [comment]
Just specify the config dir with -c and Geany will find the socket link.

**Comment by fjvico** [comment]
That put it crystal clear. Thanks for being there.
