### ISSUE TITLE
Plugin Manager causes Geany to crash when opened more than once at a time

### ISSUE THREAD

**Issue by dmaphy** [geany/geany#1563]
Currently Geany allows you to open the Plugin Manager dialog more than once at a time. If you do that, and enable/disable a plugin in one dialog, and then enable/disable plugin in the other dialog, Geany crashes. My personal suggestion to solve this would be to check if an instance of this dialog is already open and, if so, just set the focus on the dialog again and bring it to the foreground.

This issue has been reported against the Fedora package of Geany here:
https://bugzilla.redhat.com/show_bug.cgi?id=1473527

I'm going to close the RedHat bug in favor of this upstream one. :-)

**Comment by elextr** [comment]
Confirmed.

IIUC the plugin manager is non-modal so you can change plugin prefs and check their effects with it still open but its not intended to be re-entrant.

Should just de-sensitize `tools->Plugin Manager` menu item when open.

**Comment by b4n** [comment]
> Should just de-sensitize `tools->Plugin Manager` menu item when open.

I don't think so, it makes some sense to have a mean to call upon the dialog if it's already open, and disabling the item isn't necessarily totally safe if there was another way of triggering it (like keybinding not taking the sensitivity into account).

I like @dmaphy's suggestion better.

**Comment by elextr** [comment]
ok, fine.
