### ISSUE TITLE
Colors for selected text changing when color scheme activated

### ISSUE THREAD

**Issue by Kangalioo** [geany/geany#1566]
**I have encountered an issue with selections in multiple documents in Geany when a color scheme is activated.** I am running Arch Linux 4.11.9 64 bit with XFCE4 Desktop environment, Geany 1.31 and a custom Geany color scheme (although I could reproduce it with any other scheme as well, except the default one). When you select something in one document and another thing in another document, the text in the first document looks completely different. I have been able to reproduce this every time I tried.

When I just made two screenshots, I noticed this issue also happening when dialog boxes for file saving open. When the "Save Image" dialog of the xfce4-screenshooter plugin (screenshot tool) popped up, the text changed the same way it did before. That also happened when I selected the "Save As" option in the "File" submenu in Geany itself.

I hope you'll be able to fix this. I can provide more information for you, if you want. :)

Normal view
![screenshot_2017-07-30_21-31-03](https://user-images.githubusercontent.com/21220820/28756486-f2066cc4-755e-11e7-81bb-514bfeb03d8d.png)

Weird changed colors
![screenshot_2017-07-30_21-31-24](https://user-images.githubusercontent.com/21220820/28756485-f204a510-755e-11e7-908f-65914395b62d.png)

**Comment by elextr** [comment]
The colours are not changing, only the background.  This is to indicate that this is no longer the primary X selection (the thing that gets pasted by middle mouse click) but it is still the selection for window specific actions when this is the current window, eg it gets copied to the clipboard on `ctrl-c`.

IIRC there is not a setting to change this value, there was a PR but it has not been updated to comments so its not merged yet.

**Comment by Kangalioo** [comment]
But why does it happen when saving dialogs are opened?

**Comment by elextr** [comment]
Because the save dialog selects the filename portion of the path, so the primary selection is no longer the buffer selection.  There is only one primary selection in the whole of an X display.

**Comment by Kangalioo** [comment]
Okay, thanks for the clarification :)
