### ISSUE TITLE
Scintilla future change to rectangular selction key binding

### ISSUE THREAD

**Issue by codebrainz** [geany/geany#1568]
Scintilla will be changing the key/mouse binding for rectangular selection, as per:

https://groups.google.com/d/msg/scintilla-interest/kZcE8firI3A/dsBn0joZAwAJ

Since Geany doesn't support multiple selections, and almost every X11 window manager captures <kbd>Alt</kbd>+<kbd>Mouse drag</kbd> for moving a window (has saved my bacon on a number of occasions), before this change lands in Geany, I propose we change Scintilla's new default back to the existing behaviour. While it's annoying that the Windows and non-Windows behaviour would remain inconsistent, it will probably save a lot of bug reports about this feature not working, and avoid having to change any related documentation as well.

Ideally anyone interested would make this user configurable (if it is already, I couldn't find it) in the process.

**Comment by elextr** [comment]
Yes, and accidental multiple cursor creation needs to be disabled since Geany does not support multiple cursors.

**Comment by elextr** [comment]
Saucefudge is hard to use, but I think Neil committed it to Scintilla 4 not the long term 3 branch, so we have some time, just look out for backports.

**Comment by sagarchalise** [comment]
Nobody planning to implement this feature into geany ? :disappointed: I think the multi-cursor is a killer feature that should be available in geany as it is available in scintilla.

**Comment by elextr** [comment]
@sagarchalise nice of you to volunteer to change every line of editing code in Geany to handle multiple cursors instead of only one :wink:

**Comment by codebrainz** [comment]
Fixed in #2011.
