### ISSUE TITLE
Always on Visible Workspace sometimes lost

### ISSUE THREAD

**Issue by ifthatisyourdensity625** [geany/geany#1576]
I'm using    geany 1.30.1 (built on 2017-03-21 with GTK 2.24.23, GLib 2.40.2)
on Linux Mint 17.3 (based on Ubuntu 14.04). I like to have Geany visible on all workspaces,
but once in a while, a couple of times a day, it will lose that setting and I have to switch around workspaces looking for it. This seems to happen more after changes are made to an open file, but not always. I've got about 13 tabs of ordinary text files open all the time.

**Comment by elextr** [comment]
Geany knows nothing about workspaces and does not control which one(s) it appears on, that will be the a function the window manager performs.  So the problem is likely to be your window manager (which you don't name).

**Comment by ifthatisyourdensity625** [comment]
mdm is my window manager. I also run smplayer with Always on Visible Workspace and it stays that way. But, nothing ever gets changed and save in a player like in an editor. Thanks for the hint. I think I saw this misbehaviour on another editor before deciding on Geany.
