### ISSUE TITLE
json tree looks broken

### ISSUE THREAD

**Issue by lrnzo** [geany/geany#1583]
i only have a screenshot of the problem, but i think it speaks for itself. can you help me create some printable output regarding this? just a geany user not a developer.

[url](http://i.imgur.com/YbRCJ8g.png)

geany verison: 1.29
OS: debian 9.1

[Note: edited to make your url work]

**Comment by elextr** [comment]
Unfortunately your image doesn't show the status bar or the file extension, what filetype is Geany seeing the file as?

**Comment by lrnzo** [comment]
.json

**Comment by elextr** [comment]
And what filetype is Geany showing in the status bar?

**Comment by lrnzo** [comment]
[http://i.imgur.com/ejKaFwm.png](url)

;)

**Comment by lrnzo** [comment]
JSON
but shouldn't make a difference, should it?

**Comment by elextr** [comment]
You have the link format wrong, please edit it to match the changes I made to your first post so it will work.

**Comment by elextr** [comment]
Well, the filetype decides what parser is used, so yeah its important that its correct.

**Comment by lrnzo** [comment]
[url=http://i.imgur.com/ejKaFwm.png]
  [img]http://imgur.com/ejKaFwml.png[/img]
[/url]

this should work :)

**Comment by elextr** [comment]
Nope, see https://guides.github.com/features/mastering-markdown/

**Comment by lrnzo** [comment]
[my screenshot](http://imgur.com/ejKaFwml.png)

**Comment by elextr** [comment]
Looks like a bug in the ctags parser which is from the [separate project](https://github.com/universal-ctags/ctags).  Not sure if the one there is any improvement on the one in Geany.

**Comment by lrnzo** [comment]
thanks anyway. ill take a look at ctags

**Comment by lrnzo** [comment]
btw & fyi: the bug is still there in version 1.31 on debian buster

**Comment by elextr** [comment]
@lrnzo the ctags parsers are only rarely updated due to the effort involved, so yes its likely that there would be no change even if ctags knew about and had fixed the problem.

**Comment by b4n** [comment]
@elextr actually it's a Geany bug in its symbols tree building.  I know what's happening (wrong parent tag is selected, because we don't check the hole hierarchy but only the direct parent name), but fixing this will be tricky (as not all parsers report full hierarchy, hence we need to support both).

**Comment by b4n** [comment]
Proposed fix in #1598.
