### ISSUE TITLE
Feature Request: Remember made code-foldings

### ISSUE THREAD

**Issue by Johndeep** [geany/geany#1587]
_Story/Problem:_
After working quite a while on some lengthly codes (+1000 lines per file) you surely don't want to miss these great code-foldings, unfortunately, the next time you start up Geany again, all code-folding done during coding are lost.

_Suggesting:_
One of the features which would really improve efficiency is that Geany actually **remembers all code-foldings made during coding**, even if the code file is closed and later opened again (it only has to be the same path). This could be made optional in the options, if people don't want this.

**Comment by codebrainz** [comment]
It an often requested feature. I believe the [GeanyNumberedBookmarks](http://plugins.geany.org/geanynumberedbookmarks.html) offers this feature, though I've never tested it myself.

Related/duplicate:
https://github.com/geany/geany/issues/307
https://github.com/geany/geany/issues/793
https://sourceforge.net/p/geany/feature-requests/458/
https://sourceforge.net/p/geany/feature-requests/727/

I think there was a few others too, or maybe it was discussion on the mailing list.

**Comment by Johndeep** [comment]
Ah, didn't know that, even though I got through the Issues to make sure this isn't suggested yet, my bad.

**Comment by codebrainz** [comment]
No worries, I knew exactly what I was searching for :)

**Comment by JanAxelsson** [comment]
GeanyNumberedBookmarks works well **except** when working in Projects.  

It would be a great feature if it worked always.

I understood that one issue was that if a file had changed externally, the folding would be unreliable.  You asked for suggestions somewhere in this forum (https://github.com/geany/geany/issues/793), so I have two suggestions which you may very well have contemplated before :
1) Save a hash of the file together with the state information about the fold points.  If hash doesn't match file when opened,  don't honor saved fold status
2) Alternatively, save fold point together with the text of its row, and somehow match this with the opened file.  I guess this is much harder than 1), and I think 1) would suffice

Thanks for your work with this great eidtor
