### ISSUE TITLE
Wrong translation of Button Label in Search&Replace Dialog (Ctrl-H) "Найти и Заменить", when in fact it is doing "Заменить и Найти" (Replace and Search)

### ISSUE THREAD

**Issue by fossil** [geany/geany#1589]
Wrong translation of Button Label in Search&Replace Dialog (Ctrl-H) "Найти и Заменить", when in fact it is doing "Заменить и Найти" (Replace and Search)

**Comment by elextr** [comment]
Can you indicate the English string on the button, and what language are you complaining about?

**Comment by frlan** [comment]
I think it's about the Russian translation but I was not able to find that string in translation file. However, I think its about static void create_replace_dialog(void) from search.c tehre we got the button

`button = gtk_button_new_with_mnemonic(_("Replace & Fi_nd"));`

**Comment by frlan** [comment]
Ah.. got it:
```
#: ../src/search.c:634
msgid "Replace & Fi_nd"
msgstr "Найти _и заменить"
```

will update it.

**Comment by evgeni** [comment]
Shouldn't the English string be "Find & Replace"? Because you first search, then replace? ;-)

**Comment by fossil** [comment]
Once again. The english sentence "Replace & Search" is correct, because it
is exactly, what it i doing. The russian translation is wrong "Найти и
Заменить", when in fact it is doing "Заменить и Найти" (Replace and
Search). There is a big difference in it. Suppose, that you found already
using search. The "R&S" replaces the current occurense and search the next
one. The "S&R" will search and replace, when found as you might suppose.
However, it doesn't make sense to replace the new found occurense whithout
conformation. The user just didn't see the found new context of found word
before and cannot decide appriory to replace or not.

28 авг. 2017 г. 11:10 ДП пользователь "Evgeni Golov" <
notifications@github.com> написал:

**Comment by evgeni** [comment]
Right, that's why I updated my comment. All good :)
