### ISSUE TITLE
Is there an easy way to increase line spacing?

### ISSUE THREAD

**Issue by paul1149** [geany/geany#1592]
I edit large text files in geany, and the wall of text is tiring on the eyes. A bit of white space would help tremendously. I've come across the Scintilla command, sci_setextradescent, but have no idea how to implement it. I wonder if there's an easy way to achieve this.

Thanks.

**Comment by elextr** [comment]
`filetypes.common` has a `line_height` setting that sets extraascent and extradescent.

**Comment by paul1149** [comment]
Awesome. That was easy. Thanks so much!

**Comment by Wrawller117** [comment]
My apologies but am I doing something wrong? It does not seems to be having any effect.
![Screenshot from 2021-06-16 05-46-41](https://user-images.githubusercontent.com/63629630/122139323-57cd7200-ce66-11eb-9daf-0820efd257fb.png)

**Comment by Wrawller117** [comment]
My apologies, but am I doing something wrong ? It doesn't seem to be working properly. I even tried uncomenting [styling] but no luck there either. 
![Screenshot from 2021-06-16 05-46-41](https://user-images.githubusercontent.com/63629630/122139833-7aac5600-ce67-11eb-82fe-1e0ba7349516.png)

**Comment by elextr** [comment]
@Wrawller117 did you also uncomment the `[settings]` heading?

**Comment by Wrawller117** [comment]
Thank you so much for the response but is this what you mean?

https://user-images.githubusercontent.com/63629630/122148108-a7686980-ce77-11eb-953b-eb8a69e0ff4e.mp4

**Comment by elextr** [comment]
WFM, as soon as I uncomment those two lines and save filetypes.common it applies.

**Comment by Wrawller117** [comment]
@elextr Could you be kind enough to show me the video of your settings please ? There must be something I am doing wrong. 
You can use ctrl+alt+shift+r to start the recording which will be saved in your videos dir. You can rename the extension from "webm" to "mp4" for GitHub to detect it.

**Comment by elextr** [comment]
`Menu->Tools->Configuration Files->filetypes.common`  delete all characters before `[styling]` in the symbols tab a Section `styling` should appear, delete all characters before `line_height=2;2;` and a `line_height` appears in symbols as a child of styling.

Save the file `<ctrl>+s` or use the menu, and the spacing changes.

Do not post videos of file contents, post the actual file in a gist and link to it (do not paste directly in the issue) that way it can be checked for invisible characters or other anomolies that are not visible on a video.

Also post the version of Geany and the OS you are using (post the lines near the top of `Menu->Help->debug messages`) on all queries issues etc.
