### ISSUE TITLE
Possible to disable syntax highlighting?

### ISSUE THREAD

**Issue by paul1149** [geany/geany#1596]
I think this is my last question for a while. Is it possible to turn off the syntax highlighting? I have no need for it in the text files I edit, and it's a bit distracting.

Thanks much.

**Comment by elextr** [comment]
Text files don't have highlighting, so Geany must be thinking its some other filetype.

**Comment by paul1149** [comment]
The file has an **.nt** extension, if that makes a difference.

**Comment by elextr** [comment]
Edit `Menu->tools->configuration files->filetype_extensions.conf` and remove the `*.nt;` entries.

**Comment by paul1149** [comment]
Great minds :) As you were writing I did just that. It was under Batch files. But saving the file and restarting, the syntax is still there.

**Comment by codebrainz** [comment]
Add it to `None` group.

**Comment by elextr** [comment]
Yes the modified copy will be saved in your user config so the system file isn't changed.

**Comment by paul1149** [comment]
I'm confused at this point. There is a "None" line at the end of the Extensions section. I made it None=*.nt; and that didn't work. Then I went to the Groups section and made it None=None, and that didn't work either. So I don't know how to accomplish this.

elextr - I understand what you're saying, but my modifications should have taken effect if they are correct, I would think.

**Comment by elextr** [comment]
Removing `*.nt;` worked for me, close and re-open the file, the session list keeps the filetype for files that are open

**Comment by paul1149** [comment]
elextr - Perfect. That's something I didn't consider.

Thanks much to both of you! Blessings.
