### ISSUE TITLE
geany 1.31 Ctrl+F crashes && bugs in about.c 

### ISSUE THREAD

**Issue by llpub** [geany/geany#1601]
geany1.31 crashed if press Ctrl+F to find, error message is 'Segmentation fault'.
It was successfully compiled and installed on debian 9:
`./configure --program-suffix=131 --disable-deprecated --prefix=$PWD/0exe`
Also, something in 'src/about.c' is mis-written:
Line 71: 
`'&ltbervianto.leo@gmail.com&gt'`
 ';' was missing after '&lt', causing a warning when open geany1.31' about dialog.
md5sum:
`386000be6b26972c6a699939c37cda34  geany-1.31.tar.bz2`
Is this version problematic :-)

**Comment by elextr** [comment]
Nobody else has reported failure of ctrl-f, more information needed, versions of Glib, GTK, Wayland?

The about.c bug is already fixed in the [git](https://github.com/geany/geany/commit/df2a99f2751b9601e37b69bcde71a8dda908904d#diff-3e897322f360ebf32db1d236a60a40a2), thanks.

**Comment by shevegen** [comment]
I just tested it on my self-compiled system (ok ok slackware base but most is by now self-compiled), also geany. I do not seem to get any crashes at all whatsoever pressing Ctrl+F. I have not tried with the same configure line though, but perhaps the git variant should be tested.

By the way, is it possible to get a full stack trace of the segfault? (This is an open question, not to anyone in particular, just general)

**Comment by elextr** [comment]
@shevegen @llpub  backtrace by:

```
gdb geany
run geany options
```
do whatever causes crash
```
bt
```
and return to continue if its more than one page.

Paste it somewhere.

@llpub also try with `geany -c /tmp/file_that_does_not_exist` if ctrl-f works there it is a setting or plugin.

**Comment by llpub** [comment]
Ctrl+F crashed only when built with '--disable-deprecated'.
If configure from normal way, there was no crash anymore:
`./configure --program-suffix=131 --prefix=$PWD/0exe`
I did not try your suggested debug ways due to limited spare time, sorry.
System info: Debian 9, xfce4 4.12, configure log (same for with --disable-deprecated or not):
```
Install Geany in                 : /home/aa/tools/src/geany-1.31/0exe
Using GTK version                : 2.24.31
Enable binary relocation         : no
Build with plugin support        : yes
Use (UNIX domain) socket support : yes
Use virtual terminal support     : yes
Build HTML documentation         : no
Build PDF documentation          : no
Build API documentation          : no
Generate GtkDoc header           : yes
```

**Comment by elextr** [comment]
GTK3 Geany will not compile without deprecation warnings, but AFAIK GTK2 Geany will, so disabling deprecated interfaces should not affect a GTK2 compile if I understand `G_DISABLE_DEPRECATIONS` correctly.  But since GTK3 Geany uses deprecated features anyway, I don't think the `--disable-deprecations` is tested any more, so it appears there are problems with it, either on the Geany or GTK side.  It is more likely that the option will be removed rather than effort spent on fixing it until the GTK3 deprecations are removed (and its not clear how to do that and keep functionality in some cases).

Why were you setting that option? If you have no need to, then simply build Geany without the option (and probably `make clean` after changing it).

**Comment by elextr** [comment]
Follow up, compiles and runs fine for me with `--disable-deprecations` with  GTK 2.24.30, GLib 2.48.2

**Comment by llpub** [comment]
@elextr , thanks, we can re-discuss this issue if someone else report it in future.

**Comment by ToraTengu** [comment]
Good Afternoon, 
I hate to be the bearer of bad news but, this bug is also happening to me. 
I'm runnin Geany on a Win 7 64 bits laptop and every time I hit Ctrl+F it crashes with any error message...

I've attached :
 - a txt file with the debug messages prior to hitting Ctrl+F (the badly formatted email is only warning, shouldn't cause the crash) 
 - a Capture Screen of the messages issued when loading the Find Dailog ( aparrently if complains about some fonts ???).. 

hope it helps.

![geany debug printscreen](https://user-images.githubusercontent.com/16839696/30976017-a4eb58fa-a46b-11e7-9cb8-e08229259c14.png)

[Geany.debug.messages.txt](https://github.com/geany/geany/files/1341449/Geany.debug.messages.txt)

**Comment by elextr** [comment]
@ToraTengu please see if it happens without ANY plugins enabled.  

Is this the standard install from the Geany website?

**Comment by codebrainz** [comment]
I get the bad email thing too on Windows, agree it's unlikely to cause the crash.

It's possibly a bad font causing the crash. I don't think `DejaVu Sans Mono` is installed by default on Windows, perhaps a corrupt font was downloaded? I would try to delete that font (or move it out of the Fonts directory at least). I believe `Monospace` defaults to `Courier New` on Windows.

**Comment by ToraTengu** [comment]
@elextr, sorry for the delay in the feedback. I disabled ALL plugins and tryed again, the editor crashed too, no joy... The Debug Messages dialog spews out the same warnings.

Yes, both editor and plugins are standard install versions from the Geany website, downloaded via the Ketarin Application Manager but manually installed. The only deviation from a standard install is that I installed it on a custom folder outside of the %ProgramFiles% folder but, of course,  it never was an issue before... The bug infortunatly got introduced in this last version.

@codebrainz, in my case, the missing font can't be the problem I already had the DejaVu Sans Mono font installed in my laptop and like you sayed, in an Win OS, Monospace resolves to Courrier New... 

Just spitballing here but, the Monospace warning states "Monospace 9" and not "Monospace", unlike the DejaVu Sans Mono warning... Couldn't it be something as simples as mistyped font in the glade xml file or source code?

**Comment by eht16** [comment]
I cannot reproduce the crash on a Windows 7 box.
I built Geany with `--disable-deprecated` but it still does not crash.

@ToraTengu could you test with the snapshot binaries below (these are built from GIT master so be careful though they should be stable)?
Geany: https://download.geany.org/snapshots/geany-1.32nightly20171015_setup.exe
Plugins: https://download.geany.org/snapshots/geany-plugins-1.32nightly20171015_setup.exe

**Comment by ToraTengu** [comment]
@eht16 , did a quick install of the nightly build and  the Find dialog works!!! :+1: :+1:  :+1:  
It took some time to load but that's a non-issue for me  (suppose it's due to the fact it's a nightly build).

**Comment by eht16** [comment]
Nice to hear it doesn't crash anymore.
Even though we still don't know what was causing it, as there was no explicit fix for it.

Btw, it shouldn't be much slower than usual, "nightly" technically is not the correct term for the builds, I just created them in the same way as release binaries. So if the build is noticeable slower, this might be a new problem, I assume, rather in the updated GTK stack than in Geany itself.

**Comment by ToraTengu** [comment]
Found the reason the slow load of Geany... My AV and firewall are set to on paranoid mode (and my C crive is filled and fragmented up to the top) so between loading, scanning the exe for viruses and online validating the app, it takes MY laptop a loooong while to display Geany... :wink:
