### ISSUE TITLE
Colors

### ISSUE THREAD

**Issue by caltrop-3** [geany/geany#1604]
more a request than issue

>>> wish panel color was configurable from in Geany

>>> huh, there are two 'Project' tabs in sidebar
	one is empty
	the other has more files than are in my project
	the 'Documents' tab has my correct project files

pretty good app
good as the old Turbo C I used 15 years ago
now that I got 'make' working I'm really liking it - F8 and BOOM! it's all done

keep up the good work!

**Comment by codebrainz** [comment]
@caltrop-3 would it be possible to elaborate a bit, like what the way is now, how you'd like it to be, etc. Also useful to include a screenshot showing which part of the the GUI you're talking about ("panel" is heavily overloaded and isn't used in the particular GUI toolkit Geany uses).

As for the sidebar, there's only "Symbols" and "Documents" by default, the others are provided by whichever plugins you've activated.

**Comment by elextr** [comment]
The "project" tabs in the sidebar are created by plugins, they are not part of base Geany.  Try disabling all the project plugins and see if they go away.  Note I don't think that the various project plugins are made to work together, just choose one.  The project plugins are part of the [geany-plugins](https://github.com/geany/geany-plugins) project so any suggestions or problems with them should be reported there.

**Comment by caltrop-3** [comment]
Probably going to have to dig into the Desktop Theme to get the colours to change.
Many apps allow changing the default theme colours which is what my question is about.Horrid trying to view some of the default Geany colours in the side panes with the default theme colour.

This has nothing to do with Plug-Ins but Geany itself.

**Comment by codebrainz** [comment]
> Many apps allow changing the default theme colours which is what my question is about.

Can you give some examples of this, preferably GTK+ apps so we can steal their code :)

**Comment by caltrop-3** [comment]
Linux Mint Mate edition.

'xed' has its' own configurationsI was able to edit the XML for that to get it to do what I wanted.
'mate-terminal' is customizable from the preferences, though the colors are not labeled and take some experimentation.



I like a dark background, uses less poser too, and it has always been an issue getting the colours right no matter the Operating System. I quit Micro$oft and am totally Linux now and liking it better every day.
I have been enjoying your IDE. I have not done any 'C' programming for many years since I was at University. Nothing but Java Script and VBA for M$ Office for the last 15 years.

**Comment by elextr** [comment]
> 'xed' has its' own configurationsI was able to edit the XML for that to get it to do what I wanted.
'm
For me on Linux Mint Cinnamon both GTK2 Geany and GTK3 Geany and Xed follow the selected desktop theme.  A majority of developers seem to think this is the "right thing" to do.

If you don't want an application to follow the theme you can have your own settings for the application in your personal GTK settings.

For GTK2 Geany the widget colours can be customised for specific apps using the selectors that are noted in the Geany manual in `~/.config/gtk2.0/.gtkrc`.

For GTK3 Geany colours can be customised for specific applications using the CSS based syntax in `~/.config/gtk3.0/gtk.css`

There is lots of guidance on how to use the GTK theming available on the web.

But desktop themes don't have settings for programming language syntactic elements, thats why Geany has its own filetype specific theming just for the editing window.

**Comment by codebrainz** [comment]
Closing since this is already possible using GTK+ theming.
