### ISSUE TITLE
Unix Domain Socket

### ISSUE THREAD

**Issue by Meresmata** [geany/geany#1615]
Hi,

 now every time I try to open Geany I get the error message that translates to somewhat like: "Geany tried to use the Unix domain Socket of another instance.

Only changes since yesterday installed anaconda for Python 3, 64-bit...

Platform : Xubuntu 16.04
geany 1.27 (kompiliert am 2016-04-17 mit GTK 2.24.30, GLib 2.48.0)

**Comment by elextr** [comment]
Are you running Geany as root?

**Comment by Meresmata** [comment]
No, I was not!

**Comment by eht16** [comment]
Is the socket file on a filesystem which does not support file ownerships? E.g. a CIFS/SMB mount or a FAT/NTFS filesystem?

The socket file is stored in $TMPDIR, which is usually /tmp.
Can you post the contents of Help->Debug Messages of a running Geany instance?
Also post the output of :
```
stat -l ~/.config/geany/*socket*
stat `realpath ~/.config/geany/*socket*`
```

**Comment by elextr** [comment]
@eht16 the thing that matters is the location of the socket link, not the socket itself, see #1411.

@Meresmata can you check the type of filesystem where your configuration is stored (or if you don't specify it with `-c`, then the filesystem where your home directory is stored).

**Comment by Meresmata** [comment]
Hi,
 at first as partion I use a crypt-luks.


@eht16 

stat ~/.config/geany/*socket* output is:

  Datei: '/home/basti/.config/geany/geany_socket_TravelMate-B117-M__0' -> '/tmp/geany_socket.7da22a6e'
  Größe: 26        	Blöcke: 8          EA Block: 4096   symbolische Verknüpfung
Gerät: 2eh/46d	Inode: 3288257     Verknüpfungen: 1
Zugriff: (0777/lrwxrwxrwx)  Uid: (    0/    root)   Gid: (    0/    root)
Zugriff    : 2017-09-27 02:19:41.900293165 +0200
Modifiziert: 2017-09-27 02:19:41.900293165 +0200
Geändert   : 2017-09-27 02:19:41.900293165 +0200
 Geburt    : -


Sorry (in German)

stat `realpath ~/.config/geany/*socket*`

stat: Aufruf von stat für '/tmp/geany_socket.7da22a6e' nicht möglich: Datei oder Verzeichnis nicht gefunden

(means file or directory not found)

@elextr  Whose -c option?

Thanks, a lot!

**Comment by elextr** [comment]
It looks like Geany was not shut down properly and it has left a socket link in your config directory `~/.config/geany/geany_socket_*this part varies*`, make sure all Geanys are closed then delete that link, and try again.

**Comment by Meresmata** [comment]
I tried to delete it. Can you specify in more details, what to delete?

**Comment by Meresmata** [comment]
@elextr thanks alot. I tried it out with krusader. That worked very well.

**Comment by daniel-barrows** [comment]
For future reference, the short version of this issue is that it is almost always caused by running geany via [`sudo`](https://kb.iu.edu/d/amyi) on systems which have configured `sudo` not to change `$HOME`, and that it can be resolved by closing geany and then running this in a terminal:

    rm ~/.config/geany/geany_socket*

Previously reported in #294 and #1411
Long discussion of the issue at #1150
Request for more user-friendly recovery from the issue at #2102
