### ISSUE TITLE
Is it possile to change geany icon (solved)

### ISSUE THREAD

**Issue by llpub** [geany/geany#1616]
I compiled several geany versions on debian(xfce4), for different use (e.g. one for coding, another for text viewing ... lots of files).
But when opening them on same workspace, the taskbar icons for these geany instances were the same between each other, leading to a mess. It is very inefficient.
So, Is it possile to change the icon for each geany instance/version? 
I changed icons in icon dir within geany_src, and then compile, but the final icon did not change.
Thanks.

**Comment by elextr** [comment]
Since you are compiling your own you can change it by finding where the icon is set and changing it to a different one.

**Comment by llpub** [comment]
@elextr , I'm not sure whether I have found where the icon is set?
I have change these geany.png/svg before ./configure:
`geany-1.xx/icons`
but not succeed.

**Comment by elextr** [comment]
> geany title bar and desktop taskbar were unchanged.

Oh, those are desktop things, not Geany, I don't know XFCE, but maybe one of the XFCEists can tell you how to change it.

**Comment by codebrainz** [comment]
You just need multiple [desktop entries](https://specifications.freedesktop.org/desktop-entry-spec/desktop-entry-spec-latest.html). You also don't need separate Geany binaries, just need to specify separate configuration directories (`-c` command-line option), which you can put in the `Exec` field of the desktop entry. I do something similar for my "normal" Geany and a simplified one I use for my Git editor.

**Comment by llpub** [comment]
@codebrainz , I did use desktop entries && '-c ', but the problem is that when opening them on same desktop, the icons for these instances are the same, resulting difficulties to distinguish them. I want to use different icons for different instances.

**Comment by codebrainz** [comment]
Did you set the `Icon` field in the desktop entry files to different icons? If that doesn't work, I'd file a bug against whichever part of Xfce is showing the wrong icon (ex. if it's in the window titlebar, xfwm4, if it's in the panel, the "window buttons" (or whatever it's called) plugin for xfce4-panel, if it's in the virtual desktop switcher, against that panel plugin, etc.)

**Comment by llpub** [comment]
> those are desktop things
It is not. geany read and accepted system icon theme, if there was geany.png/geany.svg in desktop icon theme, geany could use them. But the qustion was that all geany instances use the geany icon from icon theme, so the icons for them are still the same.

**Comment by llpub** [comment]
I got it, geany should have changed its icon when '$prefix/share/icons' changed. It was not changed because a geany was installed from debian repository, that put geany icons to /usr/share/icons. In that case, geany will read icons from /usr/share/icons firstly, '$prefix/share/icons' were ignored. Deleting geany icons from /usr/share/icons or remove debian_repo's_geany fixed this.
As a suggestion, maybe geany should not write icons to /usr/share/icons?

**Comment by codebrainz** [comment]
> As a suggestion, maybe geany should not write icons to /usr/share/icons?

It's the Debian package that does that (by building with `--prefix=/usr`, presumably).

**Comment by codebrainz** [comment]
As a side note, apparently icons in the desktop entry files are completely ignored except in menus and the file manager. I didn't try anything but Xfce, but I suspect this is the way the spec was designed (or that it can't override what the application sets its own window icon to).

**Comment by elextr** [comment]
Geany only sets the window icons for general dialogs and about dialog, not the main window (that fif can find) but here on Cinnamon those icons don't show, presumably overridden by the theme.

**Comment by b4n** [comment]
> Geany only sets the window icons for general dialogs and about dialog, not the main window (that fif can find)

```console
$ git grep -E '"icon_name"|window_set_icon_name'
data/geany.glade:    <property name="icon_name">geany</property>
data/geany.glade:    <property name="icon_name">geany</property>
data/geany.glade:    <property name="icon_name">geany</property>
src/about.c: gtk_window_set_icon_name(GTK_WINDOW(dialog), "geany");
src/dialogs.c:   gtk_window_set_icon_name(GTK_WINDOW(dialog), "geany");
src/dialogs.c:   gtk_window_set_icon_name(GTK_WINDOW(dialog), "geany");
```

**Comment by b4n** [comment]
Anyway, changing those also works, as well as not having a `geany` icon in the default icon search path (as you guys noticed).

> As a suggestion, maybe geany should not write icons to /usr/share/icons?

That's the standard location for this; and it was already argued earlier but I believe the theme should be allowed to change the Geany icon like any other app icon.

**Comment by elextr** [comment]
> > Geany only sets the window icons for general dialogs and about dialog, not the main window (that fif can find)
> $ git grep -E '"icon_name"|window_set_icon_name'
data/geany.glade:    <property name="icon_name">geany</property>
data/geany.glade:    <property name="icon_name">geany</property>
data/geany.glade:    <property name="icon_name">geany</property>
src/about.c: gtk_window_set_icon_name(GTK_WINDOW(dialog), "geany");
src/dialogs.c:   gtk_window_set_icon_name(GTK_WINDOW(dialog), "geany");
src/dialogs.c:   gtk_window_set_icon_name(GTK_WINDOW(dialog), "geany");

ok, Geany _code_ only sets the window icons for general dialogs and about dialog, not the main window (that fif can find) :)

Which is the last three shown above, the icons set in Glade are GTK's problem.

**Comment by b4n** [comment]
> Which is the last three shown above, the icons set in Glade are GTK's problem.

?  We set icon name in all locations, so it's just telling GTK to look for a icon in the theme named like that.  We add our own path to the icon theme so it can find our icons if they aren't installed in a default location, but that's all, there's no difference on how the icon is loaded whether it's from the Glade file or the code setting the property.

**Comment by elextr** [comment]
> there's no difference on how the icon is loaded whether it's from the Glade file or the code setting the property.

Ok, and anyway as I said above, some desktops overrule it anyway.
