### ISSUE TITLE
can NOT edit "Set Build Commands"

### ISSUE THREAD

**Issue by badluckstarter** [geany/geany#1620]
Geany 1.31, Windows 10

I'm learning python, set a folder on desktop and saved Geany file as hello_world.py. 
Then I tried to execute [print ("hello world")], didn't work. 

So I tried to edit "set build commands", and found I can NOT type in anything into the Command boxes next to Labels, nor paste anything. I can only delete the default commands. I cannot type into the working directory boxes either.

I tried reinstalling Geany for 3 times, same issue. Is this a bug or I'm not doing it right? 

thanks.

**Comment by badluckstarter** [comment]
it's alright, i fixed it. Changed the default language/region of OS from chinese to english and reboot the computer...

**Comment by LarsGit223** [comment]
Can this be closed?
