### ISSUE TITLE
Dialogs don't take focus

### ISSUE THREAD

**Issue by Kommynct** [geany/geany#1623]
if i hit ctrl+f, I don't immediately start typing in the field, rather, I continue typing wherever I previously was, the dialog just appears.

I'm on geany-gtk3, my wm is i3, on arch, if that helps. I might just be an idiot and changed a setting though.

**Comment by elextr** [comment]
Works here on Geany GTK3 on Mint Cinnamon, what window manager are you using?

**Comment by that1communist** [comment]
I'm on i3wm.

**Comment by mywtfmp3** [comment]
I don't have this issue with geany gtk2 on Debian i3.

**Comment by that1communist** [comment]
I've discovered that it only occurs if I close the window using i3's built in close command.

If I push "close" on the dialog box, it works fine the next time.

**Comment by that1communist** [comment]
Tested it on gtk2 geany, still occurs.

**Comment by elextr** [comment]
@that1communist since @mywtfmp3 doesn't see the problem, it appears its something i3 has changed, did you upgrade or re-configure it recently.

**Comment by that1communist** [comment]
I have actually downgraded, and the issue still occurs, I will try the
default configuration in a bit to make sure it's not my configuration. I'll
be back with that result in a few hours when I have my computer. If that
fixes it I'll identify what setting has broken it and report it to i3.
