### ISSUE TITLE
Spell Check dictionaries problem

### ISSUE THREAD

**Issue by paul1149** [geany/geany#1627]
I've installed the spell check plugin, here on Linux. I see in its Preferences dialog one can specify the folder to place the dictionaries in.

From [this page](http://plugins.geany.org/spellcheck.html) I read:

> On Windows, you might need to install the dictionaries (the files containing the information for spell checking) manually. First, you need to download the dictionary files for the languages you want, e.g. from http://extensions.services.openoffice.org/en/dictionaries. Be sure to download the "Spelling" archives from this site. The downloaded archive should contain one or more .dic and .aff files.
> Instructions:
> Download the archive you want to use
> The downloaded archive with the extension .oxt is actually a ZIP archive, so extract it as usual (e.g. with 7-Zip or another ZIP unpacker). Extract the contents into a folder of your choice, e.g. C:dictionaries
> Then open to the Spell Check plugin preferences dialog in Geany and choose the folder you just created. You may need to restart Geany and then the installed dictionaries should be available

Admittedly, that's for Windows, not Linux, but I thought the procedure would be similar for adding dictionaries in Linux. So I first pointed the plug in to my existing LibreOffice dictionary folder. From trying spell check, I saw it didn't register. Then I copied the LO dictionary folder over to the geany home folder, to avoid permissions and file lock, but that didn't work either.

Is there any way to load custom dictionaries for this plug in?
Thanks!

**Comment by elextr** [comment]
Spell check is a plugin that is part of the plugins project which has its own issues [here](https://github.com/geany/geany-plugins/issues) its not part of Geany itself.  Please report plugin issues there because many plugins have their own developers and maintainers who are not part of the Geany project itself.

Do you have the right enchant backend installed on Linux for open office dictionaries (sorry don't know which one)?  As the readme says just before the part you quoted:

```
For the plugin to work at all, you need to have the Enchant
library installed together with at least one backend (Aspell, Myspell,
Hunspell, ...)
```
These are installed from the distribution, not bundled as they are on windows.

**Comment by paul1149** [comment]
Ok, thanks much. I wasn't aware of that. I don't know which spell check LO uses. 

I found that the plugin wasn't recognizing the custom folder location that I specced, so I moved my dictionaries over to the enchant dictionary folder, consolidated them under the name _en_US.dic_, and it's working fine now. Will close thread. Thanks again.

**Comment by eht16** [comment]
Just for completeness, loading dictionaries from the configured directory is supported only by the "myspell" backend (the tooltip in the preferences dialog documents this).
This is a limitation of the other backends supported by Enchant.
On non-Windows and non-OSX systems, this is not a big issue as you can usually easily install dictionaries by your distribution package manager and they are installed in the proper location by default.

**Comment by paul1149** [comment]
I see that now. At the time I was unaware of the whole back end thing. Thanks. What I wish is that it would see dics with names other than in the format xx_YY.dic, and that I could use multiple dics simultaneously, but that's all it seems to be looking for, and it looks like one dic at a time. Still, the workaround is very workable for me.

**Comment by volcik** [comment]
Key comments that helped me from here : https://portableapps.com/node/21685

> open up the Readme.windows.txt, it will tell you where to get the enchant libraries that are needed. I downloaded enchant_1.5.0-2_win32.zip
> Extract the file.
> Copy the folder bin, lib and share to GeanyPortable\App\Geany\. Windows will warn you about overwriting existing files in the folders. Go ahead and copy it as it won't overwrite anything because there's no other files with the same name to overwrite.
> 
> If you try to run it right now, it will complain about not having dictionaries. Let's set those up

Then:

> I had to download Firefox ones (Marco Pinto) rename all "en-gb" to "en_gb" - so underscore is either required or simply dash not allowed in the file names for hunspell

Plus I have extracted them straight to "hunspell" folder, so I had ".../Programs/geany/hunspell/en_gb.aff/

**Comment by volcik** [comment]
... and also in the Pugin preferences point to `.../Programs/geany`  and **_NOT_** to `.../Programs/geany/hunspell`

**Comment by eht16** [comment]
Can you elaborate on what exactly you mean and what the problem is?
Ideally in a new issue.

**Comment by volcik** [comment]
I have encountered Spell Checking plugin awkward setup behaviour.  It comes down to proper config however - so It is **solved** but it is problematic because there is ambiguous information on how to setup it.

1st
as explained in here:  https://plugins.geany.org/spellcheck.html

> Note: if you are using Enchant 2.0 or later (the library used by the SpellCheck plugin), you need to move the dictionaries into a subfolder called "hunspell" in the directory you created above. To check which Enchant version you are using, check "Help->Debug Messages" in Geany and find the appropriate log message telling about the Enchant version. 

Files need to be in the _hunspell_ directory

2nd
I've downloaded .dic and .afc  but I had to substitute dash for underscore in their filenames

ex:
> en-GB.aff -> en_GB.aff
> en-GB.dic -> en_GB.dic

after that I've put both of these in
> C:\Programs\Geany\dict\hunspell

_dict_ -is a newly created folder, for my own convenience

3rd
In geany spell checker plugin preferences however I had to point to 
> C:\Programs\Geany\dict

and NOT to

> C:\Programs\Geany\dict\hunspell

in order to spell checker to detect **en_GB**

**Comment by eht16** [comment]
Ok, I find the hunspell directory portion not that confusing but anyway, I tried to make it more clear:
https://gist.github.com/eht16/d2bfcb69a2d095fe6f5c3d427f8455fe

And also added a note about replacing hyphens by underscores.
What do you think?

By the way, `C:\Programs\Geany\dict` is not a good choice to store custom data as it might be removed when Geany is upgraded. Better find a place outside of Geany's installation directory.

**Comment by volcik** [comment]
Looks fantastic to me. Cheers

**Comment by eht16** [comment]
Done in https://github.com/geany/geany-plugins/commit/37b1ebf3826b95a19281c9047b0de617a51b10ab.
