### ISSUE TITLE
Saving a file in Geany does not trigger SBT continuous command

### ISSUE THREAD

**Issue by ViliusN** [geany/geany#1629]
SBT has this [nice feature](http://www.scala-sbt.org/0.12.4/docs/Getting-Started/Running.html#continuous-build-and-test), that it can run commands automatically when some source file gets changed.

This used to work until about 2-3 months ago. However now SBT does not detect changes saved from Geany. It works fine with other text editors, though.

(I'm running Geany version 1.31 and SBT version 1.0.2 on Arch Linux)

**Comment by ViliusN** [comment]
As I said, this feature works fine with other text editors (namely, I tested with Nano and Xfce's Mousepad). And until recent update, it used to work fine with Geany too. So, I'm 99% sure that the problem is on Geanie's side.

**Comment by elextr** [comment]
99% of other editors do not provide you with multiple methods of saving files as Geany does. 

One just writes over the original file, one writes to a temporary file then renames it over the original, one tries the first also copying the original metadata and if it doesn't work tries the second.

These will appear to monitoring software as different actions, some of which may not trigger it.

All this is explained in detail in the wiki article.  As suggested above, trying the different saving settings may solve your problem.

**Comment by ViliusN** [comment]
Finally, I figured it out myself. Disabling "use_gio_unsafe_file_saving" option in "Various preferences" did the trick.
