### ISSUE TITLE
no shadowing of current line for geany 1.31 on Suse 

### ISSUE THREAD

**Issue by hackerAusHeidelberg** [geany/geany#1635]
Hi all, 

I have the problem, that the shadowing of the current line does not work, not matter which filetype. I can not find any setting for this and on my windows machinge where I installed geany from binaries the shadowing works out of the box. Is that a bug?

I have a machine with OS SUSE Linux Enterprise Desktop 12 SP2 64-bit and just installed the latest geany from source. geany -V:
geany 1.31 (built on 2017-10-12 with GTK 2.24.31, GLib 2.48.2)

Cheers and thanks,
Stephan

**Comment by elextr** [comment]
This is controlled by the colour scheme `current_line` setting (or filetypes.common for default).

Check its colour isn't the same as your background and the third parameter is `true`.

**Comment by hackerAusHeidelberg** [comment]
this is great, thanks a lot!
