### ISSUE TITLE
bug: code formater for all type of code, not olny C

### ISSUE THREAD

**Issue by mckaygerhard** [geany/geany#1638]
when i try to reestructure code/lines using menu,all the code are unidented and lost format

i noted the code identation only works with C, for php u other fail

its a problem due users does not know why the command fail with others source files..

a solution its to provide a way to redefine a alternate way as a general command , or geany project provide a scritp that call respective code formater based on file extension

**Comment by Vector08** [comment]
I also have the same problem

**Comment by Vector08** [comment]
I also have the same problem

**Comment by elextr** [comment]
Geany indentation is very simple so that it will work for as many styles and languages as possible.  As such it does not "know" anything about your language or the style you are using.

Building in indentation knowledge for all supported languages and all styles of those languages is beyond the scope of a lightweight IDE.

Running external language formatting programs is covered in the [Geany manual](http://www.geany.org/manual/current/index.html#sending-text-through-custom-commands) or userscan also write plugins to access formatters such as the one at https://github.com/codebrainz/code-format.

**Comment by mckaygerhard** [comment]
i using php, when i format the lines/code all the lines goes to column 1

**Comment by elextr** [comment]
How do you "format" the lines?

**Comment by mckaygerhard** [comment]
yeah! all the code based on scripting are bad formating when using the geany tool, all the lines go to column 1 and identation are loss

also the code identation that you cited only works for 4 langs..  very poor

**Comment by elextr** [comment]
Geany is an open source project worked on by volunteers in their own time.

As such you can contribute an improved formatting plugin for PHP.

**Comment by mckaygerhard** [comment]
by using menu->editor->format->reformat/lines/code all lines goes to collumn 1

the plugni do you cited are vert poor, only support 4 langs, C/C++ and VALA, geany suppost to help and ident many much more or not?

**Comment by mckaygerhard** [comment]
@elextr  i not have the skills but i can made a bash scripts that detect the file extension and parse the code, and then you as debelopers can impelmenting

**Comment by mckaygerhard** [comment]
also noted @elextr that this its a oficial bug due the code does not are formated when that command are performed (by using menu->editor->format->reformat/lines/code)

@elextr i not have the skills but i can made a bash scripts that detect the file extension and parse the code, and then you as debelopers can impelmenting

**Comment by codebrainz** [comment]
@mckaygerhard can you run Geany from the command-line like `LANG=C geany` and tell the exact wording of the menu item you're using?

**Comment by mckaygerhard** [comment]
sorry for that , you have right, that0s the menu entry path:

edit->format->reflow lines/block

**Comment by elextr** [comment]
yeah, reflow is not indenting.  So the translators for your language (unknown) seem to have misunderstood the translation

**Comment by codebrainz** [comment]
@mckaygerhard "reflow" means like to turn like

```
Hello world,
how are you doing today.
I'm fine
```

into 

```
Hello world, how are you doing today. I'm fine
```

Is that what you would call `Reestructurar`, or is that wrong translation?  (I'm assuming you are using Spanish language).

**Comment by mckaygerhard** [comment]
ok i understant the root problem its translation mistake, 

but now, ummm so there's no ident facilty for geany ? whqat its the entry in the menu, i can see "smart line ident"

**Comment by codebrainz** [comment]
@mckaygerhard according to the manual it means:

> Indents the current line or all selected lines with the same indentation as the previous line.

**Comment by elextr** [comment]
Sounds like false advertising, maybe the "Smart indent" menu item should be renamed "Same indent" or something.

**Comment by codebrainz** [comment]
I opened #1639 for the translation bug. Closing this issue now.

**Comment by codebrainz** [comment]
> ummm so there's no ident facilty for geany ?

Not built in, but you can use "Send Selection to Command" to make something workable using an external formatter, or write a plugin to do it, similar to my code-format plugin but for your preferred language(s).
