### ISSUE TITLE
Context Action: no reaction if empty

### ISSUE THREAD

**Issue by LarsGit223** [geany/geany#1641]
If the item "Context Action" is selected from the context menu then nothing happens if no action is configured for the current filetype.

It would be more user friendly if a little message window pops up, pointing to the corresponding section in the geany manual.

**Comment by elextr** [comment]
Hate popups, they should die!!! :) But a status line message would be ok, but nothing that needs dismissing.

**Comment by LarsGit223** [comment]
:grin: Ok, will possibly create a PR for it.
