### ISSUE TITLE
Text color/background for hints

### ISSUE THREAD

**Issue by kolorafa** [geany/geany#1651]
![image](https://user-images.githubusercontent.com/921517/31686538-b564bf58-b386-11e7-9348-c27fcdfd234c.png)

Other GTK apps have hints white text over black background, is the background color hardcoded?
![image](https://user-images.githubusercontent.com/921517/31686719-375f149a-b387-11e7-85e7-c915948eac01.png)

Arch (Antergos) KDE Plasma
geany 1.31 (kompilacja: Jul 19 2017GTK 2.24.31, GLib 2.52.3)

**Comment by codebrainz** [comment]
Are you sure you're not using a GTK+3 build of Geany? I had this problem as well with KDE but I thought it was only when using GTK+3 Geany, not GTK+ 2.

**Comment by elextr** [comment]
No its not hard coded, it follows the GTK theme.  Perhaps @codebrainz KDE distro didn't put much effort into the GTK themes after GTK3 when all the tools to translate KDE themes to GTK2 would have broken.

Add:

```
.tooltip {
  background-color: #00ff00;
}
```

to `~/.config/gtk-3.0/gtk.css` and get minty green.

**Comment by kolorafa** [comment]
Okey ... that didn't help, but i did found that if I run geany from terminal it has this bad background, but if I run from start menu or krunner it loads and it get correctly black background.

Thanks for your help, so i need to look into theme and probably hit plasma team.
