### ISSUE TITLE
Paypal donation broken

### ISSUE THREAD

**Issue by mperkel** [geany/geany#1659]
Link from donate returns

> ## donate%%40geany.org

> We cannot process this transaction because there is a problem with the PayPal email address supplied by the seller. Please contact the seller to resolve the problem. If this payment is for an eBay listing, you can contact the seller via the "Ask Seller a Question" link on the listing page. When you have the correct email address, payment can be made at www.paypal.com.

**Comment by codebrainz** [comment]
It's also broken from the `Help->Donate` menu item too, but it instead says `donate0geany.org` instead of `donate%%40geany.org`. Something must've changed recently as we just received a donation on the 17th of October.

**Comment by codebrainz** [comment]
I think it might be a problem with nginx 301 redirect on the server, the address it redirects to has the two `%%` in the email part of the URL. @eht16 any ideas?

**Comment by eht16** [comment]
I fixed the double `%%`, this was a left over when migrating from Lighttpd to Nginx recently.
Sorry about that.

Could you test whether it works now?
I spend the last hour in testing and trying various things while it should work as it is. Currently, a clean 301 status is returned with the appropriate `Location` header and this is the same as before.
For some reason, when testing with my Firefox instance, I always get an error but this must be related to its history. I tested with fresh profiles in Chromium and Firefox and then it seems to work.

**Comment by codebrainz** [comment]
Works for me now on website and from `Help->Donate...` in Geany. Thanks @eht16!
