### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mperkel** [geany/geany#1660]
I really like your editor.  It's now my main editor. But I'm like to ask for a simple feature that I see in other editors.

When doing a find I'd like a "wrap search" checkbox to automatically wrap around from end to beginning/ And have it remember that choice.

**Comment by eht16** [comment]
Do you mean something like "Always wrap search" (see https://geany.org/manual/#search)?
It's in the main preferences dialog in the General tab.

**Comment by codebrainz** [comment]
Related:
https://github.com/geany/geany/issues/1192
https://github.com/geany/geany/pull/252
