### ISSUE TITLE
Feature Request - Sort

### ISSUE THREAD

**Issue by mperkel** [geany/geany#1661]
Some editors have a sort function. Some even are smart enough to sort marked text. Can that be added?

**Comment by elextr** [comment]
You can pass selected text through the systems sort command using the "custom command" feature.

**Comment by mperkel** [comment]
ok - did that and it works.

Ideally - I should be able to edit the menu system itself and add the sort command. Of course that's kind of ambitious.

**Comment by elextr** [comment]
Well, you can set the menu label for the command, so you could call it "Sort" no matter what command you used and you can re-order the command list.  Also you can assign a keybinding so you don't need to use the menu.

If you are looking for the whole menu to be user configurable so yo can put the "sort" anywhere, well you can edit the source :)

**Comment by frlan** [comment]
There is also a plugin for it supporting little more than just sorting https://plugins.geany.org/lineoperations.html

**Comment by frlan** [comment]
Going to close this  Please reopen at will ;)
