### ISSUE TITLE
caught signal: 6  (geany crash on vnc over ssh)

### ISSUE THREAD

**Issue by relayman357** [geany/geany#1668]
Hi,

I'm running geany 1.29 "jowar" on a fresh Linux install.  It is running Debian 4.9.511 (2017-09-28) x86_64 GNU/Linux on an AMD Athlon II X2 250 Processor.  This is a headless system so I initiate an SSH connection to it and then start x11vnc with this command:  "x11vnc -shared -display :0 -geometry 1920x1080".  Next I remote in with RealVNC over localhost so it uses the SSH tunnel (I'm on a Windows 7 box).

This has worked fine for everything I've done so far except geany.  In the middle of editing a code file the VNC window just goes away.  The SSH terminal window gives me a "caught signal: 6" and puts me back at the bash prompt.

A "kill -l" shows that this is an abort signal coming from geany itself (I think).  Since it only occurs with geany I think that may be a good assumption.

thanks,
relayman357

**Comment by elextr** [comment]
Geany itself does not call abort() but any of the libraries it uses might if something goes very wrong, to find out run geany under gdb and after the crash get a backtrace to see where it happened and post the backtrace here (if its a long backtrace don't forget to press return to continue it before pasting).

**Comment by elextr** [comment]
Correction, Geany doesn't call abort() directly, but it does use assert() which calls abort(). But still same thing is needed, the backtrace.

**Comment by relayman357** [comment]
Hi elextr - how do I run geany under gdb?  I've done a little gdb but only with code I've written and can compile.  I don't know how to do what your asking.  Also, note that I wasn't compiling, building, or executing any code in geany when it crashed.  I was just using the editor.   - thank you

**Comment by elextr** [comment]
```
gdb geany
```
at the gdb prompt

```
run <the options you normally give to geany>
```

when the crash occurs and you are back at gdb prompt

```
bt
```

and return as many times it asks to continue.

**Comment by codebrainz** [comment]
Could also be a crash in `x11vnc` there are [many hits on Google for "x11vnc signal 6"](https://www.google.com?q=x11vnc+signal+6).

**Comment by relayman357** [comment]
Ok, I don't get a backtrace on geany because it doesn't crash.  The crash is happening in x11vnc.  I can make it happen frequently when typing "if (syst" in geany.  That is when I get the popup suggesting I'm going to type "system".  

All I get from gdb on geany is this:

**Comment by relayman357** [comment]
I did a gdb backtrace on x11vnc and I got the attached.  I don't know what is special about geany but nothing else leads to this x11vnc crash.
[gdb_on_x11vnc.txt](https://github.com/geany/geany/files/1427336/gdb_on_x11vnc.txt)

**Comment by elextr** [comment]
It may be that Geany/Scintilla just calls things in a different order to others (but still legal for a real GTK/X11).

You mentioned the problem seems to be the autocomplete suggestions popup, thats a custom popup generated by Scintilla and it might do the calls to create it in a slightly different order to another GUI.  And its also resized, which may confuse things.

**Comment by relayman357** [comment]
Ok, I've gone into geany preferences under "Editor" and tab "Completions" and disabled Snippet completion and Autocomplete symbols.  This stopped the issue of x11vnc dying while I'm editing code in geany.  So, naturally, I tried clicking around further to make it crash and I can - by clicking on the geany File menu item.  It doesn't happen every time but frequently.  When I restart x11vnc and reconnect my vnc session I see the opened up File menu and can access it fine.  This is weird.

**Comment by elextr** [comment]
The `File` menu is a bog standard GTK menu, nothing special there.  Perhaps the other GTK apps you use are GTK3, but AFAIK Debian still only provides Geany GTK2, check `Help->Debug Messages` near the top.

If you can build Geany from source you can configure it with `--enable-gtk3` and try that.

**Comment by relayman357** [comment]
Help-Debug shows: "GTK 2.24.31, GLib 2.50.3"

I'm assuming I can compile with gcc.  Can you recommend a complete command I should run to recompile?

I did a "dpkg --get-selections | grep gtk3" and got the following:

libavahi-ui-gtk3-0:amd64                        install
libcanberra-gtk3-0:amd64                        install
libcanberra-gtk3-module:amd64                   install
libdbusmenu-gtk3-4:amd64                        install
libreoffice-gtk3                                install

**Comment by elextr** [comment]
> Help-Debug shows: "GTK 2.24.31, GLib 2.50.3"

Yeah GTK2

Your package list shows that there is not a GTK3 package for Debian, thats why I said you need to compile to test it.

You will need the debian `build-essentials` package installed and the GTK3 `-dev` packages.

Download the Geany source tarball and extract it to a new empty directory, lets say `/some/where` so you get `/some/where/geany`.

```
cd /some/where/geany; ./configure --prefix=/some/where --enable-gtk3 --disable-html-docs; make install; cd ../bin; ./geany -c ../config
```

(well you said you wanted one command :)

That gives a completely isolated Geany in `/some/where` for testing that does not interfere with your installed one or your normal user config.

**Comment by relayman357** [comment]
This fixed the problem.  I did have to "apt-get install intltool" before I could successfully build geany but that was simple.  No more crashing when going to the File menu and I've also re-enabled "Snippet completion" and "Autocomplete symbols" without any problems.

Here is a snip from my new geany's "Help-> Debug Messages":  
09:14:02: Geany INFO		: Geany 1.31, en_US.UTF-8
09:14:02: Geany INFO		: GTK 3.22.11, GLib 2.50.3
09:14:02: Geany INFO		: System data dir: /home/rwp/geany_russ/share/geany

After I quit geany I see some Gtk-WARNING messages in the shell window from where I started geany.  I've attached them to this post.  They seem benign.

Much obliged to you elextr.

relayman357
[errs.txt](https://github.com/geany/geany/files/1430837/errs.txt)

**Comment by elextr** [comment]
> This fixed the problem. 

Neat :)

> I did have to "apt-get install intltool" 

Sorry, I can never remember which tools you need for git but don't need for the tarball.

>  some Gtk-WARNING messages

The markup one I know is fixed in git, not sure about the first two.
