### ISSUE TITLE
New warning with GCC 7

### ISSUE THREAD

**Issue by codebrainz** [geany/geany#1683]
```
../../src/build.c: In function ‘build_load_menu_grp’:
../../src/build.c:2271:19: warning: ‘__builtin___sprintf_chk’ may write a terminating nul past the end of the destination [-Wformat-overflow=]
   sprintf(cmdbuf, "%02u", cmd);
                   ^~~~~~
In file included from /usr/include/stdio.h:862:0,
                 from ../../src/tagmanager/tm_source_file.h:13,
                 from ../../src/tagmanager/tm_tag.h:32,
                 from ../../src/app.h:31,
                 from ../../src/build.c:35:
/usr/include/x86_64-linux-gnu/bits/stdio2.h:33:10: note: ‘__builtin___sprintf_chk’ output between 3 and 4 bytes into a destination of size 3
   return __builtin___sprintf_chk (__s, __USE_FORTIFY_LEVEL - 1,
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
       __bos (__s), __fmt, __va_arg_pack ());
       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I believe this to be a false positive as the affected code is explicitly guarded to prevent said overflow. The new warning is [described a bit here](https://gcc.gnu.org/gcc-7/changes.html).

Making the buffer one byte larger works around the warning.

My version: gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0

**Comment by elextr** [comment]
Yeah, looks like GCC can't propogate the value limitation from the check to the sprintf, or has a bug that it doesn't notice that cmd is unsigned and can never get a minus sign.

Anyhow easy solution is add a char to the buffer.

As discussed on IRC maybe also look at removing the initialisation, I can't remember why its there now, but seems useless.

I don't have gcc7 to test yet.

**Comment by codebrainz** [comment]
GCC no longer warns about this for some reason even though I still have the same version.

Closing for now.

**Comment by codebrainz** [comment]
Needs `-O3` to trigger.

**Comment by elextr** [comment]
Its still spurious, just add a byte to the buffer to shut it up.
