### ISSUE TITLE
Record mouse cursor/selection in macros

### ISSUE THREAD

**Issue by BarbzYHOOL** [geany/geany#1691]
I often use macros in geany, and I need to do everything with the keyboard (moving the cursor etc).
Sometimes it's impossible to do what I want.

On notepad++ I could record macros while putting the cursor on whichever line i wanted, highlighting text with the mouse, etc

It would be handy

**Comment by codebrainz** [comment]
I believe this was meant to be a [Geany-Plugins](https://github.com/geany/geany-plugins/issues) issue, against the [Macros plugin](https://plugins.geany.org/geanymacro.html).

**Comment by BarbzYHOOL** [comment]
Ok I posted there

**Comment by codebrainz** [comment]
https://github.com/geany/geany-plugins/issues/647
