### ISSUE TITLE
Set the min-width of the line numbers?

### ISSUE THREAD

**Issue by luigifab38** [geany/geany#1694]
Is there a way to set the min-width of the line numbers column?
Just because line 1 to 9 doesn't have the same width of line 100 to 999.

**Comment by elextr** [comment]
No, its only automatic.

The margin width is automatic based on the number of lines in the file so space isn't wasted for small files and it still allows stupidly huge log files to be opened.

**Comment by B4PzwL3YVGa6** [comment]
> No, its only automatic.
> 
> The margin width is automatic based on the number of lines in the file so space isn't wasted for small files and it still allows stupidly huge log files to be opened.

lie



> Is there a way to set the min-width of the line numbers column?
> Just because line 1 to 9 doesn't have the same width of line 100 to 999.

yes we can
compare function below with source
src/sciwrappers.c:99

```C
void sci_set_line_numbers(ScintillaObject *sci, gboolean set)
{
  if (set)
  {
    gchar tmp_str[15];
    gint len = (gint) SSM(sci, SCI_GETLINECOUNT, 0, 0);
    gint width;

    g_snprintf(tmp_str, 15, "_%d", len + 4);
    width =  sci_text_width(sci, STYLE_LINENUMBER, "_99999");
    SSM(sci, SCI_SETMARGINWIDTHN, 0, width);
    SSM(sci, SCI_SETMARGINSENSITIVEN, 0, FALSE); /* use default behaviour */
  }
  else
  {
    SSM(sci, SCI_SETMARGINWIDTHN, 0, 0);
  }
}
```

**Comment by codebrainz** [comment]
> lie

What? You referred to the exact part of the code where it's automatically computed.

> yes we can

I'm pretty sure the OP was asking if there's a way for _users_ to do this. You can do anything if you change the source code and rebuild it, of course.

**Comment by elextr** [comment]
@B4PzwL3YVGa6 There is no need to be rude.  If you think a comment is wrong, explain why, do not insult the commenter.  Your comment has been hidden.

As @codebrainz said, the assumption is that the OP was talking about a user changing it without modifying the code.

**Comment by B4PzwL3YVGa6** [comment]
> @B4PzwL3YVGa6 There is no need to be rude. If you think a comment is wrong, explain why, do not insult the commenter. Your comment has been hidden.
> 
> As @codebrainz said, the assumption is that the OP was talking about a user changing it without modifying the code.

oh, there were no offense, sorry. just plain functional JIRA-style text :<



> > lie
> 
> What? You referred to the exact part of the code where it's automatically computed.
> 
> > yes we can
> 
> I'm pretty sure the OP was asking if there's a way for _users_ to do this. You can do anything if you change the source code and rebuild it, of course.

My own, personal problem were editor pane resizing after every next line get.
