### ISSUE TITLE
F. Req.: better way(s) of handling tabs/windows - 3 alternate suggestons

### ISSUE THREAD

**Issue by Lew-Rockwell-Fan** [geany/geany#1700]
I use large fonts & long file names. If I get more than 2 tabs I can't tell what files are in what tab. If I get more than 3 some aren't even visible, let alone identifiable. Any of the following 3 things would improve Geany a lot for people like me. In order of preference:

1.  A drop down menu showing the full path/name for each open file, allowing the width to go all the way across the monitor. Click on an item and that file becomes the focused tab. Actually with this you wouldn't even need the tab bar & it would be nice if we could turn it off.

and/or

2. A command line option that causes the file to be opened in a new window.

and/or

3. When right clicking on a tab and selecting "open in new window", the tab in the first window would close.

People who don't use something like the Openbox native menus may not see why I consider these multi-window options as acceptable substitutes for a drop down menu. That's because separate windows are automatically put on a drop down menu when using the OB native menus, kind of like task bar, but way better.

**Comment by elextr** [comment]
> A drop down menu showing the full path/name for each open file, allowing the width to go all the way across the monitor. Click on an item and that file becomes the focused tab. Actually with this you wouldn't even need the tab bar & it would be nice if we could turn it off.

Have you tried the document list in the sidebar?  You can turn tabs off see preferences.

> A command line option that causes the file to be opened in a new window.

`geany -i filename`

**Comment by codebrainz** [comment]
There's also the super handy drop down/context menu when you right click on anywhere in the tab strip area that shows a list of the open documents, but presumably you knew this since you mentioned the "open in new window" feature which is located there.

**Comment by Lew-Rockwell-Fan** [comment]
Jeez, what a maroon i am. Don't know how I missed it that the requested features are already there. Sorry.
