### ISSUE TITLE
Grid pattern support in editor area

### ISSUE THREAD

**Issue by arigit** [geany/geany#1704]
Feature request: "Display Grid Pattern" support.
Both gEdit (optional) and gnome-Builder (by default) support displaying a subtle grid pattern in the editor area.

The pictures below show how the grid looks like with different solarized theme flavors. I understand this is a matter of taste but since this became Builder's default I guess this is popular with devs; I don't use builder but I find myself using it in gEdit all the time and I miss it in Geany. 

I couldn't find any open or closed feature requests on geany so here it goes. Some research shows this was a feature added by gtksourceview.

![image](https://user-images.githubusercontent.com/652673/33519213-709e2b44-d770-11e7-9b0d-5fb7e147647e.png)

![image](https://user-images.githubusercontent.com/652673/33519253-5e057de2-d771-11e7-81a0-06d87dd4ab3f.png)

**Comment by elextr** [comment]
I think this would need to be implemented by Scintilla, the editing widget Geany uses which is a separate project [here](www.scintilla.org).  Then Geany would then only need an option to turn it on (off by default).

**Comment by b4n** [comment]
I'm still puzzled one what is the purpose of this pattern, esp. as on your screenshots the grid doesn't even seem to match line boundaries or something.

But anyway, as @elextr mentioned, if Scintilla gets support for it we could add a setting easily (or a plugin could add it, even).  And implementing this without modifying Scintilla itself, while I believe would be theoretically possible, would likely be a pain and a lot less efficient -- and in any case not worth the hassle IMO.

**Comment by b4n** [comment]
@elextr wasn't it VTE background that was removed because newer versions of the VTE lib dropped the feature, and dealing with it manually was too much trouble?

**Comment by elextr** [comment]
Yes, might have been VTE.

**Comment by kugel-** [comment]
I'm with @b4n here. It doesn't seem useful if it doesn't even align to line heights / characters. And it would be a lot of work, and needs to be implemented in scintilla (we like to avoid invasive local changes to it).
