### ISSUE TITLE
Add css grid properties to filetypes.css

### ISSUE THREAD

**Issue by nicktrosnant** [geany/geany#1705]
Suggest adding these to the list of css3 properties.  Specifically:
grid grid-area grid-auto-columns grid-auto-flow grid-auto-rows grid-column grid-column-end grid-column-gap grid-column-start grid-gap grid-row grid-row-end grid-row-gap grid-row-start grid-template grid-template-areas grid-template-columns grid-template-rows

**Comment by b4n** [comment]
Thanks, updated with MDN's property list, which combines W3's TR and CSSWG's draft (and matches your list, I believe).
I also removed the `grid-columns` and `grid-rows` properties that were introduced in 474e60b6fad22c75c57af3a6700d7bc47fceee10 but can't seem to be referenced anywhere on the Internet nowadays.
