### ISSUE TITLE
Problem with opening a faulty file

### ISSUE THREAD

**Issue by Kzer-Za** [geany/geany#1708]
It can't be called problem that is totally on the Geany side, because something is definitely wrong with the file, but still, less and cat can read it and micro can read and edit it. Geany at first can't open the file at all.

One of the things that are wrong is that the file does not end with a newline, but usually that is not a problem for Geany, something else is the matter, but I don't know what. When I add a newline in the end with micro, Geany is able to open the file but the contents are mojibake (actually it should be ASCII). If I then use File -> Reload as, and choose UTF-8 or Without encoding, Geany displays the content correctly, but only down to the 909th line, then the file is cut off, while actually it consists of 1264 lines + the end newline.

[Haldar's Mods Pack.txt](https://github.com/geany/geany/files/1528369/Haldar.s.Mods.Pack.txt)

**Comment by elextr** [comment]
Less and cat just copy bytes, they are encoding agnostic.

Does not open in xed either.

>  UTF-8 or Without encoding, Geany displays the content correctly, but only down to the 909th line, then the file is cut off, 

Then there is probably a zero byte at the 909th line.  Probably it has mixed encodings. Try looking at the file with a hex decoder.

**Comment by b4n** [comment]
Looks like your file has a NUL byte at the 910th line (after the `a`).  Geany currently does not support NUL bytes in files, so it causes some issues, like cutting the file after the first NUL byte, and preventing automatically loading it successfully.  See @elextr's answer and https://github.com/geany/geany/issues/618#issuecomment-133426114

**Comment by Kzer-Za** [comment]
@elextr, @b4n - thanks!
