### ISSUE TITLE
Some parts of the UI can't scale text size (or can they?)

### ISSUE THREAD

**Issue by magicgoose** [geany/geany#1713]
After I've set all 3 available font size settings to size 20, the UI looks like on this screenshot:

<img width="824" alt="screen shot 2017-12-08 at 22 22 11" src="https://user-images.githubusercontent.com/1442206/33783771-c46c3036-dc66-11e7-9c18-5e1cfdbdc85d.png">
Areas marked with green rectangles still have small text.

It would be a lot better if all text could be enlarged.

**Comment by elextr** [comment]
These are all set by the GTK theme.
