### ISSUE TITLE
Entry point _time32 not found in msvcrt.dll - Win XP SP3

### ISSUE THREAD

**Issue by Alecsis-1** [geany/geany#1715]
Geany v1.32 fails to run on WinXP SP3 giving message
![geamy_v1-32](https://user-images.githubusercontent.com/34489767/33905838-03235908-df91-11e7-9486-9aac6abb8704.PNG)

Versions 1.31 and earlier run all right as well as v1.32 on Win7+

**Comment by codebrainz** [comment]
Sounds like a bug in MSYS/MinGW msvcrt. All I could find online is [this](https://sourceforge.net/p/mingw-w64/support-requests/133/), which if related, gives the impression the problem may be resolved.

**Comment by elextr** [comment]
From msys2 homepage "Current MSYS2 can't be installed on Windows XP anymore.".

**Comment by codebrainz** [comment]
@elextr that only affects whoever's using the toolchain to build msys2 binaries though, Geany just uses a few libraries which should (in theory) still work fine, unless they did something like using a newer symbol that didn't exist in XP's msvcrt.

@Alecsis-1 I don't think any of Geany's developers have/use XP anymore, so you're probably on your own. You could try a tool like [Dependency Walker](http://www.dependencywalker.com/) and see if you can find out what's using the undefined symbol.

**Comment by elextr** [comment]
On 13 December 2017 at 12:24, Matthew Brush <notifications@github.com>
wrote:

> @elextr <https://github.com/elextr> that only affects whoever's using the
> toolchain to build msys2 binaries though, Geany just uses a few libraries
> which should (in theory) still work fine, unless they did something like
> using a newer symbol that didn't exist in XP's msvcrt.
>

​Yes, thats what I mean.​

**Comment by elextr** [comment]
A quick google shows that current Microsoft operating systems have made `time()` an alias for `_time64()` so those libraries Geany uses (probably Glib) have to use `_time32()` to explicitly get a 32 bit time even on a 64 bit system.  So they will not run on any version thats so old that `_time32()` does not exist.

This cannot be fixed by Geany as its buried in the libraries.

**Comment by elextr** [comment]
If someone wants to determine what versions of windows that excludes we can add it to the download page.

**Comment by eht16** [comment]
Even if someone would be able to make Geany working on Windows XP, this OS is very outdated and not supported anymore by its vendor. I don't see any reason in spending time supporting such an old and insecure system.

**Comment by codebrainz** [comment]
People can use [the wiki](https://wiki.geany.org/doku.php) to share patches/tricks/workarounds to get Geany running on obscure/exotic platforms.

**Comment by codebrainz** [comment]
@eht16 could you update [the releases page](https://www.geany.org/Download/Releases) to say "For Windows XP or newer."? I don't remember how to edit the website wiki.

**Comment by eht16** [comment]
Done. I even set Windows 7. Do we know for sure which version is the minimum?

**Comment by codebrainz** [comment]
> Do we know for sure which version is the minimum?

For Geany itself (and Gtk2) it's Windows XP.

It's totally a guess, but I suspect that the latest Geany Windows release used newer version of GLib or other dependency (from updated/upgrade msys2) that has stopped working on XP. One could probably take all the .dlls from the previous Geany release and copy them into the Program Files directory of latest release and it would work again.

**Comment by elextr** [comment]
> One could probably take all the .dlls from the previous Geany release and copy them into the Program Files directory of latest release and it would work again.

"Somebody" can share it on the wiki as you said.
