### ISSUE TITLE
Double-clicking folder in the Tree Browser plugin opens all files in that folder

### ISSUE THREAD

**Issue by adamplumb** [geany/geany#1716]
I'm running Geany 1.31 on Fedora 27 (GNOME 3.26) and I've installed the Tree Browser plugin.   When I try to move into a folder, I double-click on it to open the folder (I set that in the preferences).  When I do that, it seems to open every file in my current folder first.  When I was using Geany on Fedora 26 it didn't have this behavior.

I'm attaching a screencast (unfortunately in gif form) to show what's going on.
![screencast from 12-13-2017 09_45_48 am](https://user-images.githubusercontent.com/101376/33944771-12ed092e-dfeb-11e7-9190-04b40a7ac00b.gif)

**Comment by codebrainz** [comment]
I guess this was meant to be reported against the [Geany-Plugins](https://github.com/geany/geany-plugins) project where TreeBrowser plugin is from?

**Comment by adamplumb** [comment]
Yeah that would make sense, I didn't know that was a separate thing.  I can open the ticket there.

**Comment by codebrainz** [comment]
Thanks. Happens all the time.

**Comment by codebrainz** [comment]
https://github.com/geany/geany-plugins/issues/658
