### ISSUE TITLE
Horizontal scrollbar flashing

### ISSUE THREAD

**Issue by codebrainz** [geany/geany#1717]
With Geany 1.33 built against GTK+ 3.22.25, probably any theme but at least with Adwaita, Adwaita Dark, Arc and Arc Darker, Scintilla's internal horizontal scrollbar trough keeps flashing off then on, almost as if its adjustment is being re-calculated or something.

I cannot figure out what triggers it, it seems to be pretty random. I tried to capture it with screen capture software but it didn't show up, likely due to the way screen capture on X works. I think I'd have to use my cell phone to record my monitor to capture it.

It's not a huge deal but it's distracting since in my DE I have the panel on the bottom and the window buttons for each app will blink when they need your attention. The scrollbar flashing has the same effect of grabbing my attention if I'm not focusing my vision on it.

I don't remember ever seeing this with GTK+ 2 build, but it might've just been so fast as to not be visible or something.

**Comment by codebrainz** [comment]
I also get the following warnings which may be related on terminal:

```
(geany:12415): Gtk-WARNING **: Allocating size to GtkScrollbar 0x56521d6711e0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(geany:12415): Gtk-WARNING **: Allocating size to GeanyMainWindow 0x56521d48c540 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

(geany:12415): Gtk-WARNING **: Allocating size to GtkScrollbar 0x56521d6711e0 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
```

**Comment by elextr** [comment]
Doesn't happen here with GTK3.18.9 so its probably a GTK 3.22 problem.

**Comment by codebrainz** [comment]
The above warnings are [caused by the VTE widget](https://bugzilla.gnome.org/show_bug.cgi?id=773814) and go away when the Terminal is disabled.

**Comment by b4n** [comment]
I don't see the flickering on Debian 9, GTK 3.22.11, GLib 2.50.3, Adwaita, X11.  But I didn't work much since I upgraded to 3.22, so I'll keep an eye on it.

**Comment by kugel-** [comment]
@codebrainz is this still a problem?

**Comment by codebrainz** [comment]
It's pretty random, and I haven't been doing any serious coding in Geany for the last couple months, so I'm not really sure. Closing for now since it's unlikely to actually be a Geany problem (more likely GTK+ or at least Scintilla). Will re-open if I notice it again.

**Comment by carl-di-ortus** [comment]
Can confirm a very randomly appeared flickering. Non other open program with scrollbars does it only Geany. My setup - Debian Testing, XFCE, breeze-gtk-theme.

Scrollbar appears to be flickering from top to bottom, it may start at middle, but it will go down. Blinking about 1-5 centimeters at a time, second blink appears a little lower, not necessarily exactly below the first, but it may be that way also. Currently it blinks in 2 of 3 tabs open. All files are saved at my home directory.

Tried to record a gif - flickering is not visible there, don't have any amateur cameras at hand, and not sure if this would be appropriate to attach.
