### ISSUE TITLE
Save file counter (file versions)

### ISSUE THREAD

**Issue by KubisGroup** [geany/geany#1730]
Hello please..
I have on linux Pluma bash script for save file what when i save the file that script create file with a filename.ver and save data with counting of save file... 

Its possible make it in variable setting and in autosave or manual save can be created this files with versions? I dont want use git but only just file version without use git/svn etc... 

for example... 
I've file "index.php" and this file was been 158x saved... In file "index.php.ver" will be saved 
`<?php
$version_index.php = 158;
`
code must be same as original file...

Thank you

**Comment by elextr** [comment]
You can write a plugin to perform actions on file save.

**Comment by KubisGroup** [comment]
I know but I am not good in C/C++... I just starting learn it... ;-)

**Comment by Skif-off** [comment]
You can try to use existing plugins: GeanyPy or GeanyLua.
