### ISSUE TITLE
Cross size

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#1733]
Please tell me if there is some way I can make the very useful line marker (the cross) on line number 1, shown below, 
![smallcross](https://user-images.githubusercontent.com/7548378/34533758-859ab0ce-f0b3-11e7-8b06-f04f7bd0e48e.png)
larger as it is very difficult to find visually?

**Comment by b4n** [comment]
It is [currently fixed to 16px width](https://github.com/geany/geany/blob/1f71ccd40ac4e6754d7609bec7f81773fa181146/src/sciwrappers.c#L153), but I guess a setting could be added by someone to fix this.

OTOH it could possibly be interesting to have it dynamically follow the line height by default, so it would feel natural -- and the same could apply to the fold margin.  That'd be a little more work, and would probably need to check if it actually works well, but it seems like a good idea from the top of my head.

**Comment by philiprbrenan** [comment]
Or perhaps the line number could have a different back ground color to make it the line in question easier to pick out?
