### ISSUE TITLE
Unable to change compiler window font colors with themes, gtkrc, or css.

### ISSUE THREAD

**Issue by fofz** [geany/geany#1737]
I've wasted my whole morning on this problem. My compiler window uses red text for errors which is unreadable on my dark-gray background. [According to this](https://github.com/geany/geany/pull/1381/commits/7306501cdbb96eb047d76d183d16cbd152b2c524), I may be able to put lines in my theme files to change these colors I tried using this method, but nothing changed. [According to this](https://github.com/geany/geany/pull/1381/commits/33a8cc906caf6224a2c7820747cd956d8902bfec#diff-a443a393d799f396d769a2281c9c4803), I can put lines in a geany.css file in .config or in geany.gtkrc I tried both of these methods and both gave the same result. The font color is still red. Please help me, I'm color blind and the red font is completely unreadable on anything other than a white background. I need to change the compiler colors from blue and red to gray and yellow for example.  I'm using Geany 1.31 with GTK 2.24.31 on Ubuntu 17.10.

**Comment by elextr** [comment]
There is currently no way of changing the colour other than altering the source code.

The links you showed above (both are the same PR?) are proposed changes that were not accepted.  

The current proposed changes are [here](https://github.com/geany/geany/pull/1382) though that also has not been accepted yet.  But if you can build Geany you could apply the PR which seems to have been done successfully by the last person to comment.

**Comment by codebrainz** [comment]
Supported in 6b973bc70b6118c1d904d6d21626843b5e70beaa
