### ISSUE TITLE
[Feature Request] -- Graphics for Cut/Copy/Paste

### ISSUE THREAD

**Issue by AdamDanischewski** [geany/geany#1739]
I think it would help productivity and reduce stress if there were little graphics that kind of sauntered up when doing things that are presently met with invisibility. 

For instance when you copy something, you hit Ctrl-C that's fine, most people know that it works and are somewhat comfortable, but your brain could construct the idea that you hit the wrong key that causes an invisible quasi-imperceptible amount of stress. That stress could be removed making the editor much more enjoyable to work with by adding a graphic. 

For example,  a cutesy little graphic that appears to the right hand side of the editor border, a gradient trail of smaller versions of it self (. .o 0 O 0 o .) while swerving back and forth before disappearing off the edge of the editor (with a label - for example Copy).  Something like hello-kitty meets ICQ would probably be pleasant, yet if you could make it a skin style that could be changed that would probably be ideal. 

This behavior should probably be capable of being turned off in the settings, yet would probably make a decent default.

**Comment by codebrainz** [comment]
![clippy](https://user-images.githubusercontent.com/181177/34895625-799c9244-f79b-11e7-865c-ea377f6f7b5c.jpg)

**Comment by b4n** [comment]
😨 

---

Cut and Paste both have visible results.  Cut could be confused with delete, but that's about all.
Anyway, this kind of thing should likely better be integrated higher in the platform's clipboard handling than inside a specific app (here, Geany) as you probably want the same behavior in all apps.

This won't likely be implemented in Geany, but you can likely either write a Geany plugin or a standalone app reacting to clipboard changes.

**Comment by AdamDanischewski** [comment]
You seem to have not really wrapped your brain around the idea here. What I meant to articulate is a way to provide visuals with regards to ANY editor behavior. Ideally you could launch a notifications editor and select the skins for various items and attach them to any functionality and perhaps have an overlay grid of the editor to pin point where they should appear - sound effects wouldn't hurt either that way you don't need to move your eyes to know that what you wanted to happen has happened. 

At the moment, this editor seems fine the way it is, no one thinks its odd or weird to have such a quiet editor. Yet if you implemented this feature in the appropriate way, my guess is that people would not be capable of letting go of them and would be locked in/hooked on them. I think its useful not for purposes of locking users into Geany, yet for the reduction in stress and I think that is a big reason why it would lock people in. When you eliminate sources of hidden stress you are alleviated into a higher state of well being.

**Comment by codebrainz** [comment]
@AdamDanischewski such functionality could be done in a Geany plugin. If you or someone feels like pursuing this, and needs any help/support, you can join the [development mailing list](https://www.geany.org/Support/MailingList) or there's usually a number of developers familiar with Geany's code and plugin system [on IRC](https://www.geany.org/Support/IRC). I don't imagine anyone would oppose adding such a plugin to the [Geany-Plugins](https://github.com/geany/geany-plugins) project to help get it distributed to end-users.
