### ISSUE TITLE
Missing SCN_DWELLSTART and SCN_DWELLEND events

### ISSUE THREAD

**Issue by LarsGit223** [geany/geany#1742]
I wanted to work on https://github.com/geany/geany-plugins/pull/664 and noticed that hovering over a color is not showing the color tip any more.

After some research without finding any solution or reason I decided to put a simple debug output in ```editor.c``` in geany itself:
``` c
static gboolean on_editor_notify(G_GNUC_UNUSED GObject *object, GeanyEditor *editor,
								 SCNotification *nt, G_GNUC_UNUSED gpointer data)
{
	ScintillaObject *sci = editor->sci;
	GeanyDocument *doc = editor->document;

	ui_set_statusbar(TRUE, "Other: %d", nt->nmhdr.code);

	switch (nt->nmhdr.code)
```

It seems like events SCN_DWELLSTART and SCN_DWELLEND are not reported any more. I cloned a fresh master of geany, compiled and installed it, no difference.

This worked before so I assume I am overseeing something simple but I am stuck here.

**Comment by elextr** [comment]
Where do you SETMOUSEDWELLTIME?

**Comment by LarsGit223** [comment]
I think nowhere. Just saw it myself. I assume that in my previous tests SETMOUSEDWELLTIME was set by other activated plugins. I will check and report the results...

**Comment by LarsGit223** [comment]
Yep. After setting SCI_SETMOUSEDWELLTIME it works again. Sorry for the wrong alarm.
