### ISSUE TITLE
Tab seperators

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#1743]
https://user-images.githubusercontent.com/7548378/35068140-132da854-fbce-11e7-94b9-20cbd38b87ce.png

Is there some way that I can make the divisions into tabs more obvious?

**Comment by b4n** [comment]
Your theme is responsible for the look of notebook tabs, so you should
change/tune it.  If you want to manually alter it for Geany only, it
provides widget names/CSS classes to ease this (see the manual).

**Comment by philiprbrenan** [comment]
I have tried all the fascinating themes in: https://github.com/codebrainz/geany-themes but none of them seem to affect the tabs.

**Comment by elextr** [comment]
Ummm, I think @b4n means your GTK theme which applies to widgets outside the editor window, such as the tabs, not your Geany theme which applies only to text inside the editor window.

**Comment by codebrainz** [comment]
@philiprbrenan this is exactly what happened to all my themes after GTK+ 3.20 broke theming again. You need to upgrade your GTK+ themes; a lot of the popular ones were fixed after GTK+ broke them all this last time.

**Comment by kugel-** [comment]
This is a GTK theme issue, can't do anything in Geany
