### ISSUE TITLE
Symbols tree for Ruby files rendered incorrectly if assigning result of if / else block

### ISSUE THREAD

**Issue by tambeta** [geany/geany#1744]
The class / method hierarchy in Ruby files is parsed incorrectly if assigning the result of an `if` / `else` block:

![geany-incorrect](https://user-images.githubusercontent.com/9417744/35111123-2c8f0a08-fc83-11e7-9e46-e273e5a86f2d.png)

After removing the assignment, all methods are grouped under the enclosing class, as expected:

![geany-correct](https://user-images.githubusercontent.com/9417744/35111140-3a54dd66-fc83-11e7-9e99-f4ff76fff1f3.png)

Tested with the very latest state of the `master` branch (as of 2018-01-18), Arch Linux up to date. Might be related to #587.

**Comment by techee** [comment]
Fixed with the updated parser.
