### ISSUE TITLE
Vala's for snippet miss type declaration of i 

### ISSUE THREAD

**Issue by medeotl** [geany/geany#1747]
Not sure it is really an issue or a wanted behaviour. Anyway, for snippet doesn't include the "int" type declaration

Current snippet: 
for=for (i = 0; i < %cursor%; i++)%block_cursor%

Expected snippet:
for=for (int i = 0; i < %cursor%; i++)%block_cursor%

**Comment by kugel-** [comment]
This is on purpose. The snippets are shared with other languages, not all of which support that syntax. Also, the user may want to use an existing variable i.

You can override the snippets config locally if the syntax doesn't suit you.
