### ISSUE TITLE
Geany closing on i3wm restart

### ISSUE THREAD

**Issue by paulomagnum** [geany/geany#1755]
Issue: Geany is closing when i3 is restarted.

Steps to reproduce:
1. Open geany
2. Restart i3 repeatedly using keybind $mod+Shift+r (default)
3. Geany will then close

Error message: 
`(geany:6353): Gdk-ERROR **: The program 'geany' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadWindow (invalid Window parameter)'.
  (Details: serial 7012 error_code 3 request_code 2 (core protocol) minor_code 0)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Trace/breakpoint trap (core dumped)`

Details:
- OS:          Arch Linux
- Kernel:    4.14.15-1-ARCH
- Geany:    1.32 (built on 2018-01-29 with GTK 3.22.26, GLib 2.54.3)
- i3:            4.14.1 (2017-09-24)

Please let me know if you need any additional information. I'm happy to help. Thank you.

**Comment by shevegen** [comment]
May this be related to i3wm and/or gtk/glib? I compiled geany from source and use icewm and it works very well. I do remember having seen the above error elsewhere though. I have the same gtk3 version as you have, also glib 2.54.3, same version of geany too. Guess one of the geany devs may know which part receives these xorg-handlers.

**Comment by elextr** [comment]
Its not entirely surprising that you get a window system error when you keep restarting the window manager.  Any request for window management services while it is stopped will fail.  GDK (the low level component of GTK) will then fail and will exit the program and there is nothing the application (Geany) can do about it.

> Please let me know if you need any additional information. I'm happy to help. Thank you.

You could try following the advice the error message gave you and post the results of a backtrace here but I doubt there is much we can do about it.

**Comment by codebrainz** [comment]
> Its not entirely surprising that you get a window system error when you keep restarting the window manager.

This is generally not a problem on X since the WM is just another client. You don't even need to be running a window manager and everything should more or less work (except window placement/sizing/etc obviously).

That being said, this almost surely not a bug in Geany. As @shevegen said, it's probably something with i3 (most likely) or GTK+/GDK. The message from X server is misleading at best, either GDK (in process) or i3 (out-of-process) could also make X give such a message.

**Comment by paulomagnum** [comment]
> You could try following the advice the error message gave you and post the results of a backtrace here but I doubt there is much we can do about it.

I don't think I have the skill to do that. Sorry.

I tried reinstalling geany and I'm not having the issue anymore, I think. Anyway, maybe this is not a geany bug as mentioned since I'm using it on openbox before and it just works fine. I'll just close this issue then.
