### ISSUE TITLE
FEATURE: Add language field to templates info

### ISSUE THREAD

**Issue by pmralbuquerque** [geany/geany#1759]
Hi

I think it could be useful to have a language field on the general info for templates, instead of assuming en globally.
I know I prefer pt wherever it's applicable. HTML, for instance (<html lang="pt">).
Regards,
Pedro

**Comment by elextr** [comment]
The template info does not assume any language, you can write anything you want there.

**Comment by pmralbuquerque** [comment]
Maybe I didn't explain correctly.
I mean Menu Edit->Preferences->Templates
There is no field for language, and yet some of the templates create by Menu File->New (with template) do use 'en' as language, namely html, html5, php...

**Comment by elextr** [comment]
Essentially there are an unlimited number of fields that could be substituted into templates.  If you want to contribute good code to add such a field its likely to be accepted (at least until the dialog is full).

But in the meantime you can edit the template files to set the language you want, just copy the template file to your `config directory/templates` from the systems `share/geany.templates` and edit. You can even have several versions of the same template so long as the names are different, maybe `file.en.html` and `file.fr.html`.

**Comment by pmralbuquerque** [comment]
Great, thank you for your time!
