### ISSUE TITLE
geany hangs when the file isn't longer accessible

### ISSUE THREAD

**Issue by HybridDog** [geany/geany#1760]
I've used sshfs to be able to access files on another computer and opened a text file with geany there. After I shut it down without unmounting, geany stopped and I had to kill it with sigkill.
My file browser also hanged when I opened the folder which shouldn't longer exist.

**Comment by elextr** [comment]
This is almost certainly not a Geany problem, it is blocking waiting for a response from the filesystem (which still thinks its mounted).  That it is not a Geany problem is illustrated by the file browser doing the same thing.

**Comment by HybridDog** [comment]
l think you're right
