### ISSUE TITLE
Removal of Recent Files and Projects from geany.conf

### ISSUE THREAD

**Issue by mbrandis** [geany/geany#1763]
Hi!

I would like to propose an enhancement/feature request: 

* At the moment the recent files/projects are saved in geany.conf. 
* I would like to save geany.conf in a revision control system, so I can share the configuration between different computers. 
* The recent files from different computers lead often to merge conflicts of the configuration file.
* E.g. I do this very successfully with vi, one configuration over many computers.

Is is possible, to move the recent files/projects to a separate (local) state file?

Regards,
Mark

**Comment by elextr** [comment]
Well, its probably possible to separate settings from session, but somebodys got to do it.  Pull requests are welcome.

**Comment by mbrandis** [comment]
I thought about that. I would not miss the recent files after a new start, but the recent projects are really useful. 
If geany was written in Perl or Python I would try my luck. I'm not versed in C at all.

**Comment by elextr** [comment]
> If geany was written in Perl or Python I would try my luck. I'm not versed in C at all.

Well, geany.conf is just a plain text file, so you can write a script to remove the entries from a copy that you VCS and put geany.conf in .gitignore.  And a script to restore all but the session info.

In general storing tool configs for general purpose tools like editors in shared VCS is frowned upon, not everyone wants to use the same editor, though you can of course do anything with your own stuff.

**Comment by campisano** [comment]
I'm doing something like @elextr suggestion (ugly I know):

`rm -rf ~/.cache/geany_config; cp -L -r ~/.config/geany/ ~/.cache/geany_config; geany -c ~/.cache/geany_config; rm -rf ~/.cache/geany_config`

Maybe there are other configs statements to 'extract', like geometry, for the scope of put geany.conf in a VSC. In addiction, the geany.conf file is generated at first start with a lot of default configs. I did a try removing them and keep just what I did change, but the editor will put them again.

I think that can be a useful feature to have a way to add just a subset of instructions/configs in a file to enhance/customize the behavior of geany, like themes or external commands. Maybe a better way to do so can be the use of something like a geany.d folder with custom files to be read when exist, and that can overwrite the configs in geany.conf... What do you think?

**Comment by elextr** [comment]
> I did a try removing them and keep just what I did change, but the editor will put them again.

Yes, the Glib library that writes `.conf` files writes the whole file.

**Comment by abmorris** [comment]
I started a PR which I hope will resolve this issue. I need help tracking down a GUI bug I introduced.

**Comment by elextr** [comment]
@abmorris what is your use-case for not using Geany projects?

**Comment by abmorris** [comment]
I want to back-up and synchronise my settings ([dotfiles](http://dotfiles.github.io/)-style) across all computers where I use geany. Since my `$HOME` path is different on each, and I generally work on different projects on each, the recent files list from one computer is pretty meaningless on another. I believe this is the use-case that @mbrandis is describing at the top of this issue.

**Comment by kugel-** [comment]
This is addressed in the session_split branch which should be merged before the next release

**Comment by kugel-** [comment]
session_split branch merged 6856edd6511e8aa9a225098ac2aab9171b10167f
