### ISSUE TITLE
How to change default theme ?

### ISSUE THREAD

**Issue by Rockvole** [geany/geany#1765]
I am using Geany 1.27 on Linux Mint 18 Sarah.

I have a dark theme installed everywhere due to eyestrain.
In Geany I can choose my darcula theme in View > Change Color Scheme ...
Unfortunately I have to choose that again every time I run Geany.

I have looked in preferences but cannot see a default setting. I have looked in the Geany install directory, but cannot see a default.conf to replace.

**Comment by elextr** [comment]
The colour scheme is saved when Geany is shut down, so you should not have to select it every time.  Are you shutting Geany down properly and not logging out or shutting down the computer without closing Geany?

**Comment by Rockvole** [comment]
I am just closing Geany by pressing the X at the top right of the window.

**Comment by codebrainz** [comment]
A few things you could try:

1. Try running Geany from the command line like `geany -v` and then changing the theme and exiting Geany as you normally do. Take note of the messages printed to the terminal and paste them here.

2. Try setting the theme and closing Geany using `File->Quit`, just in case the window manager is doing something weird and killing Geany or making it crash.

3. Try running Geany from the command line, specifying a different configuration directory, in case there is something wonky with your default one, like this `geany -v /tmp/geany-test-config`. Change the theme and exit normally and re-open to see if the setting was saved.

4. With no instances of Geany running, make a copy of the file `~/.config/geany/geany.conf` to somewhere else, open Geany, change the theme, and exit normally. Make another copy of that same file, and compare them manually, using diff, or your favourite compare tool.

**Comment by Rockvole** [comment]
Thanks codebrainz - it turns out geany was not able to write some config files, so I changed their ownership and now it retains my scheme.
