### ISSUE TITLE
Geany 1.32 does not respect the Xfce 4 desktop theme

### ISSUE THREAD

**Issue by hacatu** [geany/geany#1766]
I have a dark theme for my desktop (Xfce-dusk) and all versions of Geany I have used <= 1.31 have displayed the editor tabs, menu bar, status bar, status area, and other ui elements according to this theme.  Geany 1.32 always displays with a light ui theme.  The editor theme still works though, and I do not see anything unusual in the console output.
Geany 1.31:
![geany1 31](https://user-images.githubusercontent.com/4614167/36050287-f475d54c-0db3-11e8-9f71-6d658ccf256e.png)
Geany 1.32:
![geany1 32](https://user-images.githubusercontent.com/4614167/36050424-8266d68a-0db4-11e8-81bc-eea168a73a21.png)

**Comment by intact** [comment]
Xfce-dusk is probably Gtk+2 only (1.32 theme looks like Adwaita for Gtk+3).

**Comment by elextr** [comment]
@intact is probably right

@hacatu check which version of GTK Geany is using `menu->help->debug messages` near the top.

**Comment by hacatu** [comment]
Ah, Xfce-dusk is indeed GTK 2 only, which is a bit surprising since it is the only built in dark theme, but Xfce 4 is still updating to GTK 3 I suppose.  Installing a 3rd party theme fixed it.  Thank you!
