### ISSUE TITLE
Geany & Nim-language

### ISSUE THREAD

**Issue by r3d9u11** [geany/geany#1772]
Hi. Wich status of nim-language support?

I'm found this [PR](https://github.com/geany/geany/pull/193) and I'm tried Geany 1.27 (available in repos of Linux Mint 18.3), but it haven't syntax highlighting and autocompletion :(
![1](https://user-images.githubusercontent.com/15020827/36339299-318ef4ca-13d3-11e8-8f86-abe278fd508c.png)

Thanks!

**Comment by elextr** [comment]
@r3d9u11 #193 has not been applied, you will have to apply it yourself.  The OP announced no time to continue it back in 2015 and nobody has taken it over, or announced they have tested it or anything.

Basically the biggest problem I suspect is that none of the Geany devs are Nim users, so they don't know enough to test it more than extremely superficially.  If Nim users want it, they can take it over (or propose a new PR) and a number of people who use Nim should post that they have tested the PR fairly well and it works for them.

**Comment by r3d9u11** [comment]
@elextr thanks for answer!

**Comment by eht16** [comment]
JFTR, Nim was added in #2085.
