### ISSUE TITLE
Notebook tabs mouse scroll support  

### ISSUE THREAD

**Issue by hugleo** [geany/geany#1778]
The mouse scroll button support can speed up switch between tabs.
That's was easier in previous geany versions.

**Comment by elextr** [comment]
Please always post version of Geany and Glib and GTK.  I assume your new version is GTK3.

The mouse tab switching was removed by the GTK toolkit in GTK3, nothing we can do about it.

**Comment by hugleo** [comment]
yes, gtk3.
