### ISSUE TITLE
vertical line

### ISSUE THREAD

**Issue by juliojulian** [geany/geany#1779]
geany 1.32 (compilado el día Jan 29 2018 conGTK 3.22.26, GLib 2.54.3)
ArchLabs Minimo

saludos!

![archlabs_2018-02-22-30_1024x768](https://user-images.githubusercontent.com/36741075/36554165-2be25b3a-17dd-11e8-891b-ee53bc567ac7.png)

**Comment by elextr** [comment]
Edit->preferences->editor->display->long line marker uncheck enabled

**Comment by juliojulian** [comment]
sorry and thanks!
