### ISSUE TITLE
Perhaps missing space

### ISSUE THREAD

**Issue by scootergrisen** [geany/geany#1789]
Is this string missing a space?
`File %s opened(%d%s).`
Like so:
`File %s opened (%d%s).`

**Comment by frlan** [comment]
Hmmm... I think so. Going to change that.

**Comment by scootergrisen** [comment]
Another string with missing space:
`Print only the basename(without the path) of the printed file`

**Comment by elextr** [comment]
Programmers writing function calls in their messages :)

**Comment by scootergrisen** [comment]
Here is one with double space.
`Perform regular expression matching on the whole buffer at once rather than line by line, allowing matches to span multiple lines.  In this mode, newline characters are part of the input and can be captured as normal characters by the pattern.`

**Comment by elextr** [comment]
English as she are wrote around the world.  In some parts of the world its common to separate sentences by two spaces, in other places its not.

I don't think Geany has a proclamation on this, probably just make them all the same where it matters, and as Github neatly demonstrates, it doesn't matter with most rendering engines :)

**Comment by b4n** [comment]
I don't think it really matters, but I would go with single space in anything I want "formal".  I usually put two spaces (like I just did writing this comment, actually), just out of habit, likely in an attempt to make sentences easier to discriminate in a fixed-width font email world, but that's about it.  Also, we apparently have only one double space in a translatable sentence, so let's stick with single ones.
