### ISSUE TITLE
Perhaps change fold/unfold to collapse/expand

### ISSUE THREAD

**Issue by scootergrisen** [geany/geany#1793]
We have strings like:
```
_Fold All

_Unfold All

_Expand All

_Collapse All

Fold/unfold all children of a fold point

Fold or unfold all children of a fold point. By pressing the Shift key while clicking on a fold symbol the contrary behavior is used.
```

Perhaps they should all use collapse/expand.
And perhaps use the same strings multiple places.

**Comment by elextr** [comment]
Please show where these strings are from, without any context its impossible to say.

**Comment by scootergrisen** [comment]
![1](https://user-images.githubusercontent.com/1836590/36844819-7e43423c-1d54-11e8-9172-3e8adc4dc37c.jpg)
![2](https://user-images.githubusercontent.com/1836590/36844820-7e70d166-1d54-11e8-983d-6665ed2bbadf.jpg)

**Comment by b4n** [comment]
Interesting point.  Here, "fold" refers to hiding some part of the document, while "collapse" refers to a tree list view.  Not sure if we should keep the distinction, or unify the similar concepts.

**Comment by elextr** [comment]
Well, its a similar concept from differing domains, code editing, and tree viewing (commonly filesystems).

IME the former uses "fold/unfold" for the hiding of contiguous blocks of code whilst the latter uses "expand/collapse" for an information hierarchy.  Certainly the underlying widgets do so:

http://www.scintilla.org/ScintillaDoc.html#Folding

https://developer.gnome.org/gtk3/stable/GtkTreeView.html#gtk-tree-view-expand-all

Emacs, Qt creator use fold/unfold, Eclipse does not have folds on the text buffer, but shows the structure in a tree view in a separate pane and uses expand/collapse in that tree view to fold/unfold the text, yes it uses both terms to describe the action.

I think its fine for Geany to follow the historical usage and leave both terms.

**Comment by kugel-** [comment]
I agree and would rather not change those terms, especially since they are in place since forever.
