### ISSUE TITLE
Geany and Tcl/Tk: how they can help each other

### ISSUE THREAD

**Issue by aplsimple** [geany/geany#1808]
There below is a zip file providing a context help on Tcl/Tk commands and keywords while editing Tcl script in Geany IDE.

By context help I mean the following: while editing a file.tcl in Geany you can set the caret on desirable Tcl command/keyword and press Ctrl+F1 (or F1, if you map it to Geany's context action) - after that you should get a help (man) page for the Tcl command/keyword.

Man pages of www.tcl.tk are remarkable with their giving a separate man page (as html file) for each single entry. So, we can organize their viewing on context base.

And Geany is remarkable with its customizing options and one of them is a context action. The action  may be tuned and called for a word or text selection from popup menu or with a hotkey.

-------------------------

Now let's customize Tcl/Tk context help in Geany IDE. As a bonus you'll get a menu of commands to use in Geany IDE unrelated to Tcl/Tk directly, thus Geany and Tcl/Tk would **help each other** as declared.

Please try this:

**1**. If you do not have Tcl/Tk on your system, install it from [www.tcl.tk](http://www.tcl.tk). Linux users have it preinstalled, most likely.

**2**. Unpack the below attached zip to save files:
```
    e_help.tcl
    e_menu.tcl
    rarrow.png
    run_pause.bat
    run_pause.sh
    ...etc...
```
   into some directory, e.g. /home/me/UTILS (for Windows it may be C:\Users\me\UTILS).

**3**. Go to Geany's menu 'Edit/Settings', then to 'Tools' page and enter in the 'Context action' field:
```
    wish /home/me/UTILS/e_menu.tcl "s=%s"
```

Uff. Now you should be able to call the context help. While editing your Tcl/Tk script, select a Tcl/Tk command or simply place the caret on it and call "Context action" from popup menu. You should see something like:

![e_menu1](https://user-images.githubusercontent.com/37333988/37696643-462c69c4-2ce9-11e8-8498-4a7e40447848.png)

where 1st line calls Tcl/Tk help for "selection" (i.e. foreach, string, grid, panedwindow etc. - about 200 Tcl/Tk man pages and 26 pages of Tcl keywords from A.htm to Z.htm)

Other lines execute "selection" as an executable program by itself and by shell in console, with or without waiting their completion.

You can also attach a menu file to process your selected Geany text by external commands / programs. Of course, they may be absolutely unrelated to the Geany's selection, being called as you need them in Geany seance.

For example, you might desire to view a word in English-Russian (-Deutsch, -Hindi, -Arabic etc.) dictionary as above in the picture. You are just setting a caret on an English word and calling Geany's context to view its translation.

You can also make hierarchical menus as seen below:

![e_menu2](https://user-images.githubusercontent.com/37333988/37754229-ac31fe6e-2db1-11e8-8a64-f17b3ab954dd.png)

A child menu may be called with or without waiting it, with or without closing a parent menu. All menus can be called (or made afterwards) as 'stayed on top'.

For details of menu attachment see readme.md of zip file below. The menu is rather simply organized and passed to e_menu.tcl as "m=menu.txt" parameter.

Below there are few screenshots esp. made to illustrate how all this mechanics could work in a real seance of development with Geany IDE:

![2018-03-30-204941_1680x1050_scrot](https://user-images.githubusercontent.com/37333988/38160917-b24a9e3c-34cd-11e8-9b6f-26d5d0c662ec.png)

... these ones are obsolete a bit:

![2018-03-24 15-28-29](https://user-images.githubusercontent.com/37333988/37864303-7b0b1352-2f7d-11e8-8c75-3f345ccfc2c2.jpg)

![2018-03-24 15-29-05](https://user-images.githubusercontent.com/37333988/37864304-83d9933c-2f7d-11e8-8d43-0ce90f3513b7.jpg)

![2018-03-24 15-29-21](https://user-images.githubusercontent.com/37333988/37864306-8abde450-2f7d-11e8-949d-1f19b86102fd.jpg)

![2018-03-24 15-29-35](https://user-images.githubusercontent.com/37333988/37864307-942bf464-2f7d-11e8-9b80-5a590f8d62cf.jpg)

![2018-03-24 15-31-45](https://user-images.githubusercontent.com/37333988/37864309-9c74715a-2f7d-11e8-9740-ea6135529648.jpg)

![2018-03-24 15-32-13](https://user-images.githubusercontent.com/37333988/37864311-a3edfd5c-2f7d-11e8-87e9-d916fa4a3cea.jpg)

![2018-03-24 15-32-22](https://user-images.githubusercontent.com/37333988/37864313-ad62b2b0-2f7d-11e8-98b8-5dca26aa37c9.jpg)

![2018-03-24 15-34-02](https://user-images.githubusercontent.com/37333988/37864316-b4e25a7c-2f7d-11e8-99ac-9249410e2378.jpg)

![2018-03-24 15-34-53](https://user-images.githubusercontent.com/37333988/37864319-bc26677e-2f7d-11e8-9ae1-3384763e6cb2.jpg)

![2018-03-24 15-59-31](https://user-images.githubusercontent.com/37333988/37864321-c3bd69ba-2f7d-11e8-8470-e26a3d5605df.jpg)

_(to be continued...)_

---------------------

Regretfully, there are some BUGS with Geany's passing of selected text to its context command.

E.g. there is a problem of calling the context action in Windows version of Geany, namely a hotkey doesn't work if you select something more complex than just Latin letters (e.g. ## or {}) though the popup menu copes with this selection OK.

But even Geany's popup menu never works if your selection includes an odd number of double quotes (e.g. -"-).

The probable reason is that Geany never escapes any special character (e.g. # or ") with backslash before passing selection to shell.

Another thing is that Geany only call the context action if something were selected. Empty selections are ignored. It's a pity because the empty selection may be as meaningfull as non-empty one. Cases as well as tastes differ.

You should take this into account, being aware of this behaviour of Geany.

---------------------

[tcl_geany.zip](https://github.com/geany/geany/files/1865351/tcl_geany.zip)

**Comment by codebrainz** [comment]
Could you provide a concise description of what the bug is here?

**Comment by aplsimple** [comment]
OK, bugs have been added, if they are what you wanted.
Thank you very much for your scrupulousity. Them users highly appreciate it.

**Comment by codebrainz** [comment]
For each potential bug you encounter, you should make a single Github Issue with enough details that someone wanting to fix the bug could understand and reproduce it on its own, using the same version, OS, etc. as you're using. Putting multiple bug reports into a single Issue makes it more difficult to find and work on any of them.

This issue sounds more like a tutorial - which is fantastic, we need more of those - but this is the wrong place to post it. There is [a wiki](https://wiki.geany.org/howtos/start) for people to post helpful tutorials like this.

**Comment by codebrainz** [comment]
I have made a [wiki page](https://wiki.geany.org/howtos/start/using_with_tcl_tk) for this tutorial, if anyone feels like moving the contents over.

**Comment by aplsimple** [comment]
Thank you a lot!
I would try and fill this wiki page. After that, I'll close this one. It's all must be well prepared.
So till that I'll be exercising on this page.

E.g. I have another remark on Geany's context :)
