### ISSUE TITLE
Geany logs user out when colour picker is used

### ISSUE THREAD

**Issue by rahbcca** [geany/geany#1818]
Geany Version: 1.33, OS: Fedora 27 Reproducable: yes
When the Colour Picker is clicked on a sample, I am logged out. The issue triggers abrt, which after a few minutes asks if I would like to report the bug. I press report and a trace is started. It then comes back stating there is nothing in the trace to report. As long as this tool is not used, everything works fine.

**Comment by b4n** [comment]
I can't reproduce this under Debian.

Could you try and see if you can get a GDB backtrace?

**Comment by dmaphy** [comment]
I have Fedora 27 and Geany 1.33 here as well, unfortunately I am not able to reproduce this issue here as well. Probably you can provide us with more details, e.g. what kind of files you're editing and so on?

**Comment by LarsGit223** [comment]
Also not happening here on Ubuntu 16.04 (git build of geany and geany-plugins).

@rahbcca: only for clarification: with _"when the Colour Picker is clicked on a sample"_ you mean that you use the new feature in the **AddOns** plugin?

**Comment by elextr** [comment]
@LarsGit223 there is also a colour picker eyedropper in the `Tools->colour chooser` dialog if your distro hasn't debased it, but that also works for me on Mint 18.3 (a variant of Ubuntu 16.04).  Dan't have addons on this machine to test it.

**Comment by LarsGit223** [comment]
@elextr: ahh, thanks - never used it before :-) Anyway, still nothing happening after waiting a few minutes after using the eyedropper.

**Comment by rahbcca** [comment]
The issue happens when the eyedropper is clicked in the color chooser dialog. I can reproduce it 100% of the time. 
When I log in after, abrt wants to report the issue. The message log is as follows:
--- Running report_uReport ---
('report_uReport' completed successfully)

--- Running analyze_CCpp ---
Ok to upload core dump? (It may contain sensitive data). If your answer is 'No', a stack trace will be generated locally. (It may download a huge amount of data). 'YES'
Querying server settings
Preparing an archive to upload
You are going to upload 34.0 MiB. Continue? 'YES'
Uploading 34.0 MiB
Uploading 56%
Upload successful
Retrace job started
Preparing environment for backtrace generation
.........
Generating backtrace
Cleaning environment after backtrace generation
Retrace job finished successfully

--- Running analyze_BodhiUpdates ---
Looking for similar problems in bugzilla

After a few minutes, a comment appears at the bottom of the dialogue box stating that "Reporting disabled because the backtrace is unsusable."

My only option is to close the dialog box.
I'm sure that there are files on my machine that would help, and I would be happy to provide them. However, I have a brain injury and require explicit instructions.

Thanks,

Richard

**Comment by rahbcca** [comment]
The only files open are html, css and php files. When Geany is restarted, none of the previous files are opened, despite the option to open previous files is enabled in preferences.

I can use the eyedropper in ColorZilla on either Chrome or Firefox without issuel

Thanks,

Richard

**Comment by elextr** [comment]
@rahbcca  Did you intend to close or just hit the wrong button (I have done that before :)

All the reporting stuff is part of Fedora, nothing to do with Geany, can't help you with it, and anyway the report goes to Fedora, not us.

If it is logging you out it looks more like its your desktop of display server thats crashing, not just Geany.

Can you post the top few lines of `Help->Debug Messages` to show versions of Glib and GTK.

Are you using Wayland or X11?
