### ISSUE TITLE
Geany CPU load (Arch Linux; xfce4 desktop environment)

### ISSUE THREAD

**Issue by victoriastuart** [geany/geany#1819]
Adding this as a comment, for anyone similarly affected.

Geany was using ~20% CPU, constantly and consistently when idle -- when launched from the XFCE "Whiskers" menu (which is the way I normally start it), but NOT from terminal (e/g/ xfce4-terminal)!

Solution: edit the Whiskers menu launcher for Geany >> uncheck "Use startup notification."  Geany CPU usage (Geany idle) now 0%.

**Comment by elextr** [comment]
Thanks for the info.
