### ISSUE TITLE
Toolbar Icons Spacing Painfully Wide with Gtk+3 on openSuSE

### ISSUE THREAD

**Issue by drankinatty** [geany/geany#1825]
All,

I installed geany 1.33 on the latest opensuse leap 15 beta. One thing that is a bit awkward to work with when using Geany in a VM  (display res 1382x864) is the toolbar icon width which is much much wider than earlier releases causing the Search box, Jumpto Line input, Jumpto button and Quit to be pushed off toolbar adn ellipsed (or actually the down triangled). I know this (as well as icon height spacing, and height of edit-entry box, combo-box, etc.. has been a challenge with Gtk+3, but are there any tweak that can be added to condense the icons to more of a normal toolbar spacing so that all the icons fit again?

Since they all work, this isn't a bug, but it is more a feature request - if possible, to regain some of the toolbar real estate lost in the Gtk+2 -> Gtk+3 update.

**Comment by Skif-off** [comment]
Same problem: [#1746](https://github.com/geany/geany/issues/1746)

**Comment by drankinatty** [comment]
Here is a screenshot of the problem:

[Screenshot on OpenSuSE Leap 15 Beta - Build 187.1](http://paste.opensuse.org/66000052)

**Comment by elextr** [comment]
Closed as duplicate as @Skif-off pointed out.  Also as #1746 says its a GTK problem, not one we necessarily can fix.

**Comment by codebrainz** [comment]
@drankinatty you can reduce the spacing by changing the GTK+ CSS/theme (outside the scope of Geany). But also a possible simple workaround if you weren't aware: you can customize the layout of the toolbar, so if there are more important items being overflowed, you can move them forward in the toolbar so they don't overflow.

**Comment by drankinatty** [comment]
Thanks codebrainz, I just went ahead and rebuilt it with Gtk+2, and everything is perfect without having to mess with any CSS, etc. I cannot find any Gtk+3 theme that makes Geany usable in the limited space of a VM. All Gtk+2 themes are fine. 

Here is the comparison screenshot. All buttons fit with "Room to Spare":

[Screenshot on OpenSuSE Leap 15 Beta (Gtk+2)](http://paste.opensuse.org/14174908)

**Comment by codebrainz** [comment]
@vstepaniuk I don't know much GTK+ CSS and it's probably specific to the version of GTK+ 3 since CSS is unstable and changed at many different versions. A search [like this](https://www.google.ca/search?q=gtk+css+reduce+padding) seems to have a fair bit of info though.

**Comment by vstepaniuk** [comment]
@codebrainz Ok, thanks.

**Comment by drankinatty** [comment]
I'll have to build the current code and see how it looks on SuSE. If Adwaita is dead-tortoise, then that is what you get. The problem is primarily a themes issue, but it seems like a .gtkrc for the gtk3 builds of Geany may be able to minimize the damage. Having all the toolbar icons scroll of the right of the editor window and be ellipsized is just awkward. Thank you for your help here.

**Comment by drankinatty** [comment]
I will try that. The SuSE .spec file uses GTK3 by default, but that causes the icons to run off the right side of the toolbar, so I generally rebuild Geany with GTK2 so it looks right. There are about 1000 good GTK2 themes that work well with Geany, I have yet to find one acceptable GTK3 theme (that goes to the whole complexity issue of the GTK3/css themes compared to the GTK2 themes -- which means virtually no one puts out GTK3 themes where in the past thousands of people made good quality GTK2 themes and made them available via Gnome-Look, etc..)

I will definitely work with the geany.css. The problem has always been that icon spacing generally aren't handled and the GTK3 defaults are abysmal. While I am familiar with the .gtkrc adjustments as they have been well documented for years, the GTK3 and the css used has been somewhat of a moving target and black box for non GTK programmers. Finding the css setting to fix, e.g., the GTK3 statusbar height, input widget height and icons spacing has been a mystery.

Thank you again. Any sane defaults you can set in geany.css that makes the icon spacing and widgets heights more theme agnostic so whether they fit within the window is a bit of GTK3 theme Russian Roulette, the better it will be. I tried all the GTK3 themes I could find on SuSE and geany was still a mess compared with the GTK2 defaults (literally any GTK2 theme made all the widgets fit)

**Comment by elextr** [comment]
> Any sane defaults you can set in geany.css that makes the icon spacing and widgets heights more theme agnostic

In this era of hidpi screens and HD screens and plain screens, probably not while everything is done in pixels, you are likely to get icons teeny on one screen and huge on another.  And it will override the theme, and as I said, my Mint is fairly sane out of the box, so I wouldn't want Geany to override it.

As I have always said, allowing themes to mess with the look and feel of your app is a bad idea, what would they know about how its meant to work (and in fact would they even know of its existence).  Of course not, so how do they theme it, and who says Gimp wants things laid out the same as Geany as Inkscape?  grumble mumble  </my usual rant> :grin:
