### ISSUE TITLE
Rust syntax: question mark operator

### ISSUE THREAD

**Issue by JohnBSmith** [geany/geany#1827]
Please take into account that the question mark is now a valid operator: a postfix operator.

**Comment by elextr** [comment]
The rust language highlighting lexers used by Geany are part of the [Scintilla](https://www.scintilla.org/) project and the symbol parsers are part of the [uctags](https://github.com/universal-ctags/ctags) project.

First you need to check if those upstreams have been changed, and if not then raise a request to them.  Better you do that directly, you know Rust, the Geany team not so much.

When the upstreams have been upgraded then a pull request can be made to include them into Geany.

**Comment by SiegeLord** [comment]
Scintilla 3.6.5 supports this, and Geany has that version already. I can't reproduce this in Geany 1.34.

**Comment by elextr** [comment]
@SiegeLord thanks, closed fixed
