### ISSUE TITLE
Please use HTTPS URL in GitHub description

### ISSUE THREAD

**Issue by paulmenzel** [geany/geany#1839]
Could you please update the GitHub description to use the HTTPS URL. This also saves one redirect.

```
$ curl -I http://www.geany.org/
HTTP/1.1 301 Moved Permanently
Server: nginx/1.13.3
Date: Mon, 23 Apr 2018 15:08:39 GMT
Content-Type: text/html
Content-Length: 185
Connection: keep-alive
Location: https://www.geany.org/

```

**Comment by LarsGit223** [comment]
Seems to be fixed by commit 592c68b123a5414360581e2552dfcb5749745bee. Can this be closed?

**Comment by paulmenzel** [comment]
Yes, it’s fixed but unrelated to the commit, as you have to do it manually in the GitHub Web interface.

**Comment by b4n** [comment]
Looks like it's updated as well, isn't it?

**Comment by paulmenzel** [comment]
Am 11.06.2018 um 00:53 schrieb Colomban Wendling:
> Looks like it's updated as well, isn't it?

Yes, it is. That’s what I meant by “Yes, it’s fixed …”. ;-)
