### ISSUE TITLE
Formatting difference between shell and geany

### ISSUE THREAD

**Issue by ryanmusante** [geany/geany#1845]
Geany displays text differently from shell view inside a terminal.  cat outputs my fstab file with alignment as perfect while geany does not. I have tried  monospace, indentations, tabs to spaces to fix.

![geany](https://user-images.githubusercontent.com/26808646/39358223-6025a15e-4a50-11e8-9721-0b931a6db1ff.jpg)

White-space enabled shows the discrepancies I suppose but I don't understand why it would show via the gui inside of geany and not shell (vice versa).

![geany2](https://user-images.githubusercontent.com/26808646/39358336-afba3efa-4a50-11e8-9c14-b9fb43b95e70.png)

**Comment by elextr** [comment]
Try setting `Document->Indent Width` to 8

**Comment by ryanmusante** [comment]
Fixed. I'll keep that in mind.

![geany2](https://user-images.githubusercontent.com/26808646/39359007-2b5ff340-4a53-11e8-9209-40f1ed05c1b4.png)
