### ISSUE TITLE
Reload configuration by command line

### ISSUE THREAD

**Issue by webdev23** [geany/geany#1849]
Is there a way to reload the config by command line.

Same as `Tools` -> `Reload Configuration`?

Found no capability by the command `geany --help`, nor any keyboard shortcut (to automate with `xdotool`. 

**_Hint_**: I am building a dynamic color scheme editor, by modifying my config files. it works fine, but I am currently forced to reload the config at any action. I am looking to keep the same instance running, with the new config?

**Comment by elextr** [comment]
can your tool do mnemonic keystrokes?  `<alt>T R`

**Comment by webdev23** [comment]
Thanks you shown me the right direction with **alt+t**

Problem was first the **F2** (foocus on editor) is remaped with **Super+space** in my distribution.

So from the geany terminal, to reload the configuration using `xdotool`.

`xdotool key Super+space alt+t KP_Enter`

It is a bit hacky, looking forward for a better solution.

**Comment by elextr** [comment]
Its very unlikely that reloading configuration remotely is going to happen unless somebody contributes the code, and maybe not even then.  

Alternatively you could make a plugin that listened on some IPC mechanism of your choice and did a reload, or the plugin could even spawn the editor and just listen to the stdout of the child process for reload commands.  That would make a nice integrated facility.

**Comment by webdev23** [comment]
Thank you very much for the replies.
When I mean from another shell, i mean on the same machine.

I think a little gif is worth the explanation!
 
![gif1525132592_optimized](https://user-images.githubusercontent.com/2503337/39455878-2ba7b2b0-4ce3-11e8-82f0-15b0c424ccdb.gif)

As you can see a simple way to reload the configuration from the command line would be better.

**Comment by elextr** [comment]
Why do you want the user to have to execute a command to update Geany?  As I said in the previous post a plugin that spawned the editor can listen to its output for commands to reload and execute the reload command via the plugin and it will all happen automatically without user action.

**Comment by webdev23** [comment]
I am looking to reload the config by script, not by an user action.

My config change -> (auto) reload. 

For this, i need to find a way to automate the reload!

**Comment by webdev23** [comment]
Okay answering back for anyone.

From another subshell, to focus Geany and reload the config automagically.

`wmctrl -xa Geany && xdotool key Super+space alt+t KP_Enter`

Now my little workaround works perfect! 

I have no idea how to create a Geany plugin otherwise, while not knowing anything about C/C++, i always find my way quickly with php and took me no more than 2-3 hours to create it. ;)

![gif1525134983_optimized](https://user-images.githubusercontent.com/2503337/39456700-d10baef0-4ce8-11e8-9a0b-5d919e98da43.gif)

I would be glad to share.

**Comment by codebrainz** [comment]
@webdev23 nice work! @b4n had written something similar at one point as native GTK+ plugin/window, IIRC.
