### ISSUE TITLE
"Delete Current Line" doesn't delete the last line in multiline document

### ISSUE THREAD

**Issue by vstepaniuk** [geany/geany#1869]
"Delete Current Line" doesn't delete the last line in multiline document

Geany 1.31

**Comment by elextr** [comment]
There has to be somewhere to show the cursor that indicates that content will be added after the newline that ends a file, or for a totally empty file, that content is to be added at the start of the file.  In these situations there is no "line" to be deleted, it is simply the cursor being placed on screen where new content will be placed.

If the last line has content but does not end in a newline then you can delete the content.
