### ISSUE TITLE
Moving away from Github

### ISSUE THREAD

**Issue by Deimos715** [geany/geany#1870]
Dear developers and creators of Geany!

For GitHub, its darkest hour has come. It has been bought by the company
that has stained reputation within the open-source community - Microsoft
(https://blogs.microsoft.com/blog/2018/06/04/microsoft-github-empowering-developers/).
Yes, now this company spreads its motto "Microsoft Loves Open Source!"
(https://open.microsoft.com/), but its words have nothing to do with
their deeds and has to be red as "Embrace, Extend and Extinguish"
(https://en.wikipedia.org/wiki/Embrace,_extend,_and_extinguish).
It uses its software patents to push free software developers
(http://techrights.org/2016/03/10/charm-offensives-distract/). Many
projects that was involved to any collaboration with them, have been
discontinued or brought to the state of unusability (Skype, Nokia,
Linkedin etc). And Microsoft has already had its own code hosting -
Codeplex (https://en.wikipedia.org/wiki/CodePlex), that is the irony.
It's not so difficult to assume that Github will share its fate. You can
not reason with a tiger when your head is in his mouth.
So, the best way now is not to wait of worsening situation, find an
alternative (GitLab, BitBucket etc) and move this project to it. It's
easier to avoid the problem than to solve it.

This text can be changed, used and distrubited without any restriction
and the authorship.

**Comment by codebrainz** [comment]
Please discuss this on [the mailing list](https://www.geany.org/Support/MailingList), this issue tracker is for bugs/enhancements for Geany itself.

**Comment by VictorelPetrovich** [comment]
As long as people can still use this site as is, why move? 
And skype.. unusable??
