### ISSUE TITLE
dialogs lost on non-existent X11 screens

### ISSUE THREAD

**Issue by tempest766** [geany/geany#1872]
PLEASE PLEASE PLEASE restrict popup dialogs to the active display/screen where the main editor window is located...Far too often I lose the search dialog when I reconfigure my system from twinview back to a single monitor display.  This is a PITA to work around!

**Comment by elextr** [comment]
Geany only ever uses one display, it records the position of dialogs on that display as provided by X11 via GTK.  When restoring the dialog it requests the same position.  Geanty is not aware of screens or display sizes.  

It is a problem with the window manager and possibly GTK/X11 that a position off screen is accepted.  

The window manager should put the dialogs on screen if the display has been re-sized, so please complain to them.

**Comment by codebrainz** [comment]
@tempest766 what window manager are you using? This was always a problem on Windows because it allowed placing windows off-screen, but I was pretty sure (popular) X11 windows managers handled this properly.

**Comment by tempest766** [comment]
@codebrainz - using fvwm2, a legacy (liteweight) window manager.  I understand the issue.  Just wish the app would validate saved popup positions at startup, based upon queried  geometry.  Maybe the dimensions from xdpyinfo? I cannot remember the xlib mechanism for querying screen dimensions, but it cannot be overly difficult, right?

**Comment by elextr** [comment]
@tempest766 Geany isn't an X11 app, its a GTK app, and as such it also runs on Wayland IIUC (though I havn't done it myself).  So X11 only code is unlikely to be accepted.

The low level layer under GTK, GDK, can supply the screen dimensions for but  those calls are deprecated and removed in GDK4, so not sure if thats a solution either.

**Comment by b4n** [comment]
@tempest766 could you try https://github.com/b4n/geany/tree/wip/no-offscreen-dialogs and see if it fixes it?  In theory it should, but I can't reproduce the issue for the moment so I can't be sure.

**Comment by tempest766** [comment]
cleaning up old stuff --- closed!

**Comment by b4n** [comment]
@tempest766 has this been fixed magically for you, does the mentioned branch work, or your setup changed so you don't encounter the issue anymore?

**Comment by tempest766** [comment]
changed to multiple X screens due to too many programs not correctly interpretting fullscreen mode restricted to a single monitor in twinview.  now the issue is all the programs that cannot map specific windows to a particular X screen, but insted assume  all windows should use the same DISPLAY value.  As long as I can find the geany popup locations in the config files then there's a non-optimal work-around.
