### ISSUE TITLE
Fast code highlighting via keyboard shortcut

### ISSUE THREAD

**Issue by pgp** [geany/geany#1873]
It would be useful to add a keyboard shortcut, followed by a text search of the target code highlighter to use, without using menu every time... This is especially useful when pasting several code snippets into Geany, possibly belonging to different programming/scripting languages.
Example: Assuming shortcut is Ctrl Shift C, after pressing it, I type 'XML' and Enter, and code highlighting changes to XML

**Comment by codebrainz** [comment]
Have you tried the [Commander plugin](https://plugins.geany.org/commander.html)? This should make it pretty quick to switch filetypes without using mouse or remembering obscure keybindings/mnemonics.

**Comment by pgp** [comment]
Thank you! That was just what I was looking for.
