### ISSUE TITLE
Geany list symbols multiple times under Haskell

### ISSUE THREAD

**Issue by ChristopherKing42** [geany/geany#1874]
Given the file

```
func False = True
func True = False
```

Geany lists the function `func` twice under the symbols list. The above code only defines one function.

Note that although this appears to be an edge case, it is not. It is quite normal in Haskell and other functional programming languages to define functions using multiple lines like above.

**Comment by elextr** [comment]
A bit more information and an example would be useful, also version of Geany.

**Comment by ChristopherKing42** [comment]
Okay, at least it isn't a bug. I would prefer if had a range of values (due to how common multiline definitions are in Haskell), but that's just me.
