### ISSUE TITLE
Will not execute

### ISSUE THREAD

**Issue by TryingButCantPrint** [geany/geany#1879]
Will not execute.  Any file, even one line of "#" or "print(x)" results in below error.  Installed on Windows 10.  Geany 1.3.2 worked.  1.3.3 created the problem.  Uninstalled 1.3.3 and installed 1.3.2  Error remains.
Help.  Thank you.
****
'.' is not recognized as an internal or external command,
operable program or batch file.
------------------
(program exited with code: 9009)

**Comment by elextr** [comment]
It appears that you have modified an entry in the `menu->build->set build commands->execute` to `.`.  Such a change is saved in your user configuration that will be used by whichever Geany and so remains after you changed the version.

**Comment by TryingButCantPrint** [comment]
This page https://wiki.geany.org/howtos/configurebuildmenu describes the build menu and its function, but doesn't tell you what to put in the boxes.  Where can you find what to put in the boxes?

**Comment by codebrainz** [comment]
https://superuser.com/a/143121

**Comment by TryingButCantPrint** [comment]
Thank you.  Solved.
