### ISSUE TITLE
bug: line wrapping cannot be disabled

### ISSUE THREAD

**Issue by Fornost461** [geany/geany#1881]
I cannot disable line wrapping, whether or not I activate the relevant checkbox in the panel `Preferences > Editor > Features`. Long lines are always displayed in several lines.

I tested this bug with the filetypes None and Sh.

ArchLinux, geany 1.33 (built on 2018-03-06 with GTK 3.22.28, GLib 2.54.3)

**Comment by shiftee** [comment]
It is probably overridden by project settings: https://github.com/geany/geany/issues/1363

Try Project > Project Properties > Editor instead

**Comment by Fornost461** [comment]
Thank you for this good idea, line wrapping was indeed activated in the project properties, but unchecking it still does not solve the issue.

**Comment by b4n** [comment]
@Fornost461 each open document has a setting in the *Document* menu, and the setting in the preferences is only the value to set when loading.

**Comment by Fornost461** [comment]
Ok, that makes sense now, thank you.
