### ISSUE TITLE
Renaming a C++ source code symbol (variable, function, class, etc.)

### ISSUE THREAD

**Issue by vstepaniuk** [geany/geany#1883]
Is replacing **"symbol_old_name"** string with **"symbol_new_name"** string with **"Match only a whole word"** option selected in a C++ source code file actually a renaming of that symbol (variable, function, class, etc.) in Geany?

**Comment by codebrainz** [comment]
It doesn't do semantic renaming, just textual replacement. For example if you did such a replacement and had one class with a member variable named `Size` and another class with a static method `Foo::Size()`, and you replace `Size`, both will get renamed, in addition to the word `Size` in any comments, parameter names, etc. Not sure if that's what you were asking?

**Comment by vstepaniuk** [comment]
Yes, that's what I was asking about. So is it possible to rename symbols in C++ **semantically**?

**Comment by vstepaniuk** [comment]
Thank you very much for the elaboration...
