### ISSUE TITLE
Clicking on Save opens a folder

### ISSUE THREAD

**Issue by HybridDog** [geany/geany#1906]
I'm using Lubuntu 18.04, geany 1.32.
When saving a new file, this window appears (the screenshot is cropped):
![2018-07-26-230714_887x496_scrot](https://user-images.githubusercontent.com/3192173/43288779-386ae8f2-9129-11e8-9ad6-d38877ca5bc5.png)
If I click on save now, the file is saved in this folder. 

However, if I click on the white background (or somewhere similar), the first folder is automatically selected. (Nothing happens if there are only files but no folder) I can not unselect the folder, I can only select a file instead, but then my target filename is changed to this file's name.
![2018-07-26-230716_887x496_scrot](https://user-images.githubusercontent.com/3192173/43288782-3b7072f6-9129-11e8-8acf-b2a56a4e410e.png)
If I click on Save and the folder is selected, instead of saving the file in the current folder, the selected folder is opened:
![2018-07-26-230720_887x496_scrot](https://user-images.githubusercontent.com/3192173/43288790-3ec378ae-9129-11e8-9b11-de538f6eb849.png)

So if I want to save a file in a folder which contains a folder, I somehow need to take care to not accidentally click there. 
I have this problem not only with geany but also with other programs, e.g. firefox.

**Comment by elextr** [comment]
The file dialogs are the standard GTK dialogs and the way they operate is determined by the GTK toolkit.  Thats why other applications act the same.

**Comment by codebrainz** [comment]
If you build Geany from source by default you will get usable dialogs since it will link to GTK+2 which has a much better user experience in the various dialogs (file, colors, fonts, etc).

Closing since this a GTK+ and/or packaging issue.
