### ISSUE TITLE
Unable to perform version check.

### ISSUE THREAD

**Issue by Beyarz** [geany/geany#1909]
Unable to perform version check.
Error code: 6 
Error message: »Unacceptable TLS certificate«

Here's the debug:
19:57:29: Updatechecker MESSAGE	: Checking for updates (querying URL "http://geany.org/service/version.php")
19:57:30: Updatechecker WARNING	: Connection error: Code: 6; Message: Unacceptable TLS certificate

**Comment by b4n** [comment]
This is an issue in the Updatechecker plugin, which is part of the [Geany-Plugins project](https://github.com/geany/geany-plugins/), not stock Geany.  Could you [report your issues there](https://github.com/geany/geany-plugins/labels/plugin%2Fupdatechecker) instead?  thank you!

**Comment by Beyarz** [comment]
Done!
