### ISSUE TITLE
Ability to change language.

### ISSUE THREAD

**Issue by Beyarz** [geany/geany#1910]
Is there a way to change the language (not programming language) on Geany through the settings?

**Comment by b4n** [comment]
No, Geany uses the OS' configured locale for the current user.  You can alter this by setting the `LANGUAGE` (or `LANG`) environment variable before starting Geany though, e.g. on an UNIX-like environment:
```shell
$ LANGUAGE=de geany
```

**Comment by Beyarz** [comment]
Fixed it, thanks!
