### ISSUE TITLE
Cannot create user-interface - Failed to open file “geany.glade” - No such file or directory

### ISSUE THREAD

**Issue by srb623** [geany/geany#1915]
I have been attempting to compile geany from git and although it appears to build successfully, when I try to run it, the following error is displayed:

> (geany:29825): Geany-ERROR **: 16:14:48.297: Cannot create user-interface: Failed to open file “geany.glade”: No such file or directory
Trace/breakpoint trap

I have configured the build with './autogen.sh --prefix=/opt/geany' and when I type in the following:

> /opt/geany/bin/geany --print-prefix

the following is displayed:

> /opt/geany
/opt/geany/share
/opt/geany/lib
/opt/geany/share/locale

Due to the error, I tried to install from the repository for my linux distribution (Debian testing/buster) on a 64 bit machine and even their version has the same problem.

I can change to the /opt/geany/share/geany directory and then run the program and it will start up (as the glade file is in that directory) but then it will not load the plugins that I have also built from git.

I note that in the Makefile that GEANY_DATA_DIR is being set to /opt/geany/share/geany which seems to be correct but it does not seem to be getting taken into account in the final executable or libraries.

Any help in this matter would be much appreciated.

**Comment by elextr** [comment]
Geany has to be installed, it can't be run from the build directory, `make install`

**Comment by elextr** [comment]
Please provide the exact sequence of commands you ran.

**Comment by srb623** [comment]
Firstly I ran the autogen.sh script:

> ./autogen.sh --prefix=/opt/geany

then I ran 'make'.  I then opened up a 'root' terminal and typed in 'make install'.  The git repository was cloned to a directory under /home/xxx (ie $HOME on linux) and as per the above I wanted to install it to /opt/geany.

Then I tried to run the program with /opt/geany/bin/geany and it fails as per the above comments.

**Comment by elextr** [comment]
Well, that looks ok, `/opt/geany` isn't a common location, but there is no reason it shouldn't work that I know of.

`geany.glade` should be in `/opt/geany/share/geany`, is it? and is it readable to you?

**Comment by srb623** [comment]
Using /opt for 'optional' software is something that I have always done and as you have mentioned it should not make any difference.  I have done an 'ls -l' on /opt/geany/share/geany/geany.glade and it returns the following:

> -rw-r--r-- 1 root root 607K Aug  2 16:08 /opt/geany/share/geany/geany.glade

which should be readable to me as my account would get the 'other' access permission which is 'r'.

Odd thing is that when I install the distribution version of geany it fails with the same problem and the distribution version installs it to /usr.

**Comment by elextr** [comment]
Weird, @b4n I guess your Debian builds are working or we would hear about it :)

@srb623 did you build with gtk2 (default) or gtk3 `--enable-gtk3`) (the system package I think is gtk3)

**Comment by srb623** [comment]
I used the default of gtk2 to do the build.

**Comment by srb623** [comment]
Checked the version of gtk2, via pkg-config, and the following was returned:

> pkg-config --modversion gtk+-2.0

> 2.24.32

I run the testing version of Debian.

**Comment by srb623** [comment]
Kept playing around with this one today as I felt it must be something with my configuration and not geany as otherwise it would have already been discovered and fixed.  Re-installed all gtk2 related packages - the '-dev' versions as well.  Did a 'make clean' and then ran the autogen.sh again.  Then did the usual make/make install and this time geany started up as expected !  No real idea what was wrong but I do thank all that read and contributed to this issue.  I did note that if you use the '--enable-binrelocs' option to autogen.sh then geany will not start up - so maybe that is how the debian package was built and why that one does not run.  Closing this as resolved.

**Comment by tsgyure** [comment]
I experienced this issue when installing in Ubuntu Software manager (the desktop thing).
I removed Geany using the Ubuntu Software manager (the desktop thing).
I worked when installed using
sudo apt install geany
at the command line.

**Comment by ArsThaumaturgis** [comment]
To add to tsgyure's comment above:

In Ubuntu, and specifically in the App Center, I found that installing Geany from the "Snap Packages" view produced the above error; switching over to the "Debian Packages" view and installing the version found there, however, worked.
