### ISSUE TITLE
New file autofocus

### ISSUE THREAD

**Issue by toxpal** [geany/geany#1925]
Couldn't find such enhancement/improvement request, so am I the only who doesn't want to perform extra clicks every time new document is created?

I mean, when new document (file) is created in Geany, mouse cursor isn't moved to text field. As as result, you must manually click empty text area every time you want to start typing. Is there some specific reason why Geany doesn't allow typing text right after creating new file?

**Comment by elextr** [comment]
Works for me, `Menu->File->New` or `Ctrl-n` or file new button on toolbar I can start typing immediately.

It may be because your window system settings, but since you havn't mentioned version of Geany and which OS you are using its not possible to help.

**Comment by codebrainz** [comment]
In addition to basic info like Geany version and OS/desktop environment, also whether you're running any plugins, and if so, which ones. It would be easy for a plugin to steal focus like that.

**Comment by toxpal** [comment]
Thanks for your suggestions, the problem was caused by plugin. After reading your comments, I disabled all the plugins, restarted Geany, and it worked fine. Then I started re-enabling plugins one after one and found that Overview plugin causes this problem. Once I disable it, autofocus starts working. Enable - no autofocus again.

In case you need more details, I'm running latest version of Geany on antergos KDE.
