### ISSUE TITLE
Build: Could not resolve host: win32builder.gnome.org

### ISSUE THREAD

**Issue by Skif-off** [geany/geany#1930]
[scripts/cross-build-mingw.sh](https://github.com/geany/geany/blob/master/scripts/cross-build-mingw.sh):
```sh
GTK3_BUNDLE_ZIP="http://win32builder.gnome.org/gtk+-bundle_3.8.2-20131001_win32.zip"
```
Iink died.

**Comment by elextr** [comment]
Yeah, windows GTK is now only available via msys2 https://www.gtk.org/download/windows.php.  There no longer seems to be a cross build support but maybe someone elses googling will be more successful.

**Comment by eht16** [comment]
Some days ago it worked (grabbed some random Travis check: https://travis-ci.org/geany/geany/jobs/414064315#L934). Hopefully it will come back soon.
If not, we still have a copy on the server where the nightlies are built.

IIRC we thought about hosting the bundle ourselves on download.geany.org but I don't remember why we didn't do it so far. Maybe licensing issues.

Anyway, it's not totally critical I'd say as this is currently only used for Travis CI builds and only for the GTK3-Windows combination.

**Comment by Skif-off** [comment]
> and only for the GTK3-Windows combination.

It's strange, but GTK2-Windows [too](https://travis-ci.org/geany/geany/builds/420184731?utm_source=github_status&utm_medium=notification).

**Comment by eht16** [comment]
Oh ok, see https://github.com/geany/geany/pull/1931.

**Comment by Skif-off** [comment]
@eht16 Thanks! Can I close this issue or waiting of commit will better?

**Comment by eht16** [comment]
No need to close it, just wait for the merge.
