### ISSUE TITLE
Dark toolbar and file explorer

### ISSUE THREAD

**Issue by Bleety** [geany/geany#1935]
Hi I'm on a raspberrry with the latest version of Raspian and I use Geany.
I want to know how to change the color of the menu and the toolbar in dark because it's very bright.
Thanks !
Bleety.

**Comment by b4n** [comment]
The UI elements (apart from the editing area) are using the configured GTK look and feel, so changing that will change the ones in Geany.
However, if you're using GTK3, there is a setting that asks for a dark variant of the theme, and there is a Geany plugin that enables the setting for Geany if you wanna try it out: https://github.com/b4n/geany-plugin-dark-theme

**Comment by Bleety** [comment]
Thanks but I Absolutely didn't understand how to install that. Can you help me please ?

**Comment by elextr** [comment]
First check if your Geany is GTK2 or GTK3 `Menu->Help->Debug Messages` near the top says GTK version, since the plugin only works for GTK3 IIUC.

**Comment by Bleety** [comment]
My geany is on GTK 2.24.31. 
That can't work. ;_;

**Comment by Bleety** [comment]
Thanks everybody I have find how to change the global theme on my rpi !
Problem solved !

**Comment by elextr** [comment]
Afraid you can't use @b4n's plugin, no.

But you can use the standard GTK2 themeing which isn't really a part of Geany, but is documented as part of GTK.  Note that the simplest is of course if you select a dark theme for your desktop Geany should follow (assuming the person who wrote the theme did a good job).
