### ISSUE TITLE
Menu option Build writes "Lint" in place of "Link" when doing Document>Set Filetype>Programming Language>C++.

### ISSUE THREAD

**Issue by neelabhdutt** [geany/geany#1938]
When we make a .cpp document, Build option in the menubar writes Lint (the 3rd menu option) in place of Link. Please see it. 
When Filetype is set to programming language C++, the third menu option under Build menu writes Lint in place of Link.
Please check it.

**Comment by codebrainz** [comment]
That's intentional, see [Linting](https://en.wikipedia.org/wiki/Lint_(software)).

**Comment by elextr** [comment]
Just to point out that the second option `Build` does both compile and link.
