### ISSUE TITLE
"Process failed (The system cannot find the specified file)"?

### ISSUE THREAD

**Issue by gammaman8267** [geany/geany#1939]
I've installed Geany and loaded up a homework assignment so I don't have to be on campus to work. When I try to compile any of the .java files, however, I get the error message in the title. I'm using version 1.33.

**Comment by elextr** [comment]
You may not have the java compiler installed, or it might not be in your PATH.

**Comment by gammaman8267** [comment]
What should I do to find out which one?

**Comment by codebrainz** [comment]
You didn't say what operating system you're using, but that sounds like a Windows error message. The first bunch of [results here](https://www.google.ca/search?q=installing+javac+windows&oq=installing+javac+windows) explain it.

**Comment by elextr** [comment]
Closed, question appears resolved
