### ISSUE TITLE
Does not See Python Symbols with PEP484 Type Hints

### ISSUE THREAD

**Issue by DevynCJohnson** [geany/geany#1943]
When applying [PEP484](https://www.python.org/dev/peps/pep-0484/) (Type Hints) to variables, the list of "symbols" in the current file no longer displays the variables using type hints. The parser should be modified to recognize Python symbols using the format `VARIABLE: TYPE = VALUE`, rather than just `VARIABLE = VALUE`.

**Comment by elextr** [comment]
PEP-484 is still provisional, its API may change.  The parser comes from the [Universal Ctags](https://github.com/universal-ctags/ctags) project.  The latest version of that appears to support PEP 526 annotations, but not PEP 484.  

Updating parsers in Geany is "in progress" but is a big job and somewhat slow, but when complete those PEP526 annotations should not break the parser.

You should open an issue with the Universal Ctags project to discuss adding the full PEP 484, perhaps when it is finalised.

**Comment by b4n** [comment]
UCTags supports both, we just don't have the latest synced here -- and it awaits the global uctags synchronization.

**Comment by elextr** [comment]
Ok, my search didn't find any reference to pep 484 on uctags, clearly @b4n has better googling.

**Comment by DevynCJohnson** [comment]
Okay, so if UCTags supports both, but all of the code is still being synchronized, then that works for me. Geany is the best IDE (for me anyway) and I look forward to when it receives the newest updates from UCTags. 

True @elextr , PEP-484 may still be provisional, but PEP526 and PEP3107 are labeled as "final".
