### ISSUE TITLE
Shortcut for copy (Ctrl+c) is not equivalent to right click "copy"

### ISSUE THREAD

**Issue by fyah** [geany/geany#1945]
Hello,

Running 1.33 under Windows 10.

I notice the following behavior:
* select text in Geany
* hit Ctrl +C: it seems that the text is copied to some internal clipboard of Geany. Meaning I can paste in Geany, but in other apps (Firefox, Outlook, notepad), I get nothing out of a paste
* if I do the copy using right click and copy, everything works as expected, I can paste in Geany or outside

thanks for your help

**Comment by fyah** [comment]
More details: seems ctrl+c is intercepted somewhere
If I keep ctrl +c pressed for long time, the copy works.

**Comment by elextr** [comment]
> If I keep ctrl +c pressed for long time, the copy works.

might be that it starts repeating, but why that makes it work I don't know.  Maybe try pressing ctrl+c several times and see if it works then.

**Comment by fyah** [comment]
yes several times it can work

what is really weired: I installed dito, to "see" the clipboard

sometime I press ctrl+c, the copied text do not appear in the clipboard (so if I ctrl+v in other app, I get the previous copied text)
however, inside geany, if I paste, i get the text that was just copied, fine....

it looks like geany is keeping a kind of internal clipboard

**Comment by b4n** [comment]
Form past memory, it *might* be an issue with another app holding the clipboard, IIRC on Windows the clipboard can be held and then requests to update it can fail.  IIRC there was a discussion on that in Scintilla, I'll have to check what's the difference between the menu and the shorcut (likely none) but if it's that timing issue you can either just be lucky with the menu, or opening a menu does something on the Windows side.
If it's a locking issue, it's unsure we can do anything about it, or if we should -- if another app was holding it, why would we override it? Well, one cuold argue that if it's already locked we're trying to change it last and should win, but then why having a locking API anyway? Meh.

Either way, please check if you don't have another software running that is the cause of this (clipboard manager, or any other app that would get setuff in the clipboard).

**Comment by fyah** [comment]
thanks for the feedback

what I can tell for sure, is that I only experience this with geany
all other apps are fine with copy paste, be it browser, ms office or else

I only installed a clipboard manager so that I could check what is in the clipboard visually but this did not introduce any change in the behavior of ctrl+c

**Comment by fyah** [comment]
following more investigations
Excel seems affected as well

seems all linked to VirtualBox & shared clipboard

https://www.virtualbox.org/ticket/16192#comment:8
