### ISSUE TITLE
Markdown: Bad recognition of link end for some unicode chars

### ISSUE THREAD

**Issue by BenWiederhake** [geany/geany#1947]
Minimal reproducing example:

    This is displayed as normal text.
    [ク](https://google.com)
    This isn't.!

Steps to reproduce: Save it as `foo.md`, and open it in geany.  Then delete the last exclamation mark to get around #971.

Expected behavior: Both normal text lines are displayed using the "normal text" style.

Actual behavior: The last line's style indicates that it is somehow still part of the link.  Not visible in the short example: This affects the entire rest of the document.

Screenshot:
![Screenshot of the faulty behavior](https://user-images.githubusercontent.com/2690845/45174089-3b5a7080-b20a-11e8-83cd-fa3c49ec0c44.png)

Note that even before this "remove the last exclamation mark" step, one can see faulty behavior.  Specifically, the `T` is styled wrong.

**Comment by elextr** [comment]
Highlighting is provided by the [Scintilla](https://www.scintilla.org/) editing widget Geany uses.  Does the problem also occur with Scite (the Scintilla test editor)?  If so best to file a bug on Scintilla, if not probably will get fixed during some Scintilla update.

Note still happens with Scintilla 3.10 PR so not fixed there.
