### ISSUE TITLE
Need to add registers directives and keywords 

### ISSUE THREAD

**Issue by elemanhillary** [geany/geany#1949]
i want to add all 16-bit and 32-bit registers, directives and keywords to filetype Assembly but dont know which file to contribute too help please

**Comment by codebrainz** [comment]
Did you look in the [manual](https://www.geany.org/manual/current/index.html#configuration-files)?

**Comment by elemanhillary** [comment]
i already did it and my geany has all, want i mean is editing the source
(main) to be shipped with all registers directives and keywords

**Comment by codebrainz** [comment]
You don't specify which assembly you want to add, but given that there is one variant per kind of architecture ever made, I guess it wouldn't be feasible to add them all.

**Comment by elemanhillary** [comment]
Best of you thanks, i wont do it though i have a list of all Archs

**Comment by codebrainz** [comment]
Even [Wikipedia](https://en.wikipedia.org/wiki/List_of_instruction_sets) doesn't have a complete list :)

**Comment by elemanhillary** [comment]
surely without lying i have the dope list
