### ISSUE TITLE
html automatic close tags don't work with 'autoclose' plugin

### ISSUE THREAD

**Issue by pqanc** [geany/geany#1954]
I use a [Autoclose](https://plugins.geany.org/autoclose.html) plugin and i set for close `< >`.  Apart from that, i have active the option `Automatic close XML/HTML tags` (Preferences > Editor > Complet...).

The issue is that when i write `<` the autoclose plugin works and type ` >`, and i expect that the html tag autoclose but nothing happens. When i deactivate in autoclose plugin the signs `<>` and i write each one characters geany autocomplete the html tag.

This situation is so frustrating when i edit a lot of html files, ¿Is possible fix this behavior?

**Comment by elextr** [comment]
Autoclose is part of the Geany plugins collection that has its own tracker [here](https://github.com/geany/geany-plugins/issues).  Please report it there.
