### ISSUE TITLE
Can't paste from Gtk app after I close the window

### ISSUE THREAD

**Issue by cunidev** [geany/geany#1956]
Might as well be a Gtk bug, and that would be more serious. I've opened a Geany and a Gedit window, and the text I typed on Gedit isn't in the clipboard anymore after closing that window... Thanks!

Example: https://imgur.com/a/UyJukr3

**Comment by elextr** [comment]
Works for me, what OS, desktop, versions of apps, GTK and Glib.

**Comment by b4n** [comment]
Works for me too.  But it depends how you quit the apps, if you kill either GEdit or Geany, the clipboard is indeed lost.  I'm not sure what's the deal here, but if anything it's a GTK+ shortcoming I guess.

**Comment by elextr** [comment]
TBH given X11s asynchronous clipboard handling I wasn't expecting it to work, but maybe some other part caches the copy (Gnome/cinnamon, GTK, etc).

**Comment by eht16** [comment]
One can workaround this by using a clipboard manager (like ClipIt, xfce4-clipman-plugin, etc.) as they are capable of also managing the primary clipboard. This also brings a lot of other advantages and better use of the clipboard.

**Comment by cunidev** [comment]
I'm using Solus 3, GNOME on Wayland, Geany 1.33, GTK 3.22.28, GLib 2.54.3. The bug unfortunately looks to be external to Geany, but rather something in Gtk itself, as I can also replicate it using gnome-terminal instead of geany.

**Comment by b4n** [comment]
@cunidev might be related to GTK on Wayland then, as I'm on X11 and I believe @elextr as well.
