### ISSUE TITLE
Document line breaking works incorrect with cyrillic text

### ISSUE THREAD

**Issue by wrgcpp** [geany/geany#1958]
When "Document -> Line Breaking" is turned on, and user types cyrillic symbols and words and reaches assumed end of line (72 chars by default), Geany breaks the line, but not at the last word. While typing english symbols and words, line breaking works perfectly.
Screenshot with bug (cyrillic words)
![geany_bug_cyrillic](https://user-images.githubusercontent.com/6756060/45754463-31d2fe80-bc35-11e8-84f9-1781e0ecce74.PNG)

Screenshot without bug (english words)
![geany_no_bug_english](https://user-images.githubusercontent.com/6756060/45754522-4f07cd00-bc35-11e8-8e4c-8839e267839c.PNG)

This bug reproduces in Geany 1.33 on Windows 7 and Geany 1.28 on Debian 8 Jessie.

geany 1.28 ((собрано 2016-11-01 или позднее)GTK 2.24.25, GLib 2.42.1)

**Comment by elextr** [comment]
> not at the last word

Where does it break?

AFAICT line breaking just looks for a byte == ASCII space (0x20) to break after, it doesn't care what multibyte chars exist in the text.  This works because the buffer is UTF-8 and so ASCII space is itself and won't exist in any other multibyte chars.

**Comment by b4n** [comment]
@elextr I didn't check, but it looks like the code would be computing the length of the line in bytes rather than characters, and as Cyrillic will always use >1 byte per character in UTF-8, it'll break lines at halfway through or so.  Just a guess, but it sounds plausible.

**Comment by elextr** [comment]
Oh I see, so it breaks at a space, but a much earlier space than expected.  Yeah it counts in bytes so that makes sense.

**Comment by elextr** [comment]
@wrgcpp can you try #1960 works for you, seems ok, but I don't use multibyte chars much.

**Comment by wrgcpp** [comment]
@elextr It works! tested on 1.29 from Debian 9 Stretch.

**Comment by elextr** [comment]
Thanks for testing, I'm sure @b4n will commit it soon to get rid of the annoying branch in the main repo :smile:
