### ISSUE TITLE
Geany V1.29 - Python - Raspian no longer running

### ISSUE THREAD

**Issue by hollisterca** [geany/geany#1965]
Latest version of Geany V1.29 on Raspian 4.14.72
with Python 3.5.3-1
I can not get "Hello World" to run anymore.

Program: 
print ("Hello World")

Build cmd:
python3 -m py_compile "%f"

Execute cmd:
python3 "%d/%f"

Python Version:
sudo apt install python3
-> python3 is already the newest version (3.5.3-1).

When executing python program "Hello World"
it creates a cmd window:
see attachment
![cmd_hello_2018-10-01](https://user-images.githubusercontent.com/23412806/46272584-fa782200-c551-11e8-98d1-eb076bd92a5a.png)

Any suggestions?

**Comment by elextr** [comment]
Does `python3 program_path` work on the command line and is `python3` in the PATH for Geany?

**Comment by hollisterca** [comment]
yes python3 works

pi@raspberrypi:~ $ python3
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 

Within Geany, when I compile:
python3 -m py_compile "helloworld.py" (in directory: /home/pi/Documents/Geany Projects/Hello)
Compilation finished successfully.

**Comment by codebrainz** [comment]
Instead of `"%d/%f"` in the Command field you could try putting the `%d` (or `%p`) in "Working Directory" field. Also for testing you could try with hardcoded paths.

**Comment by hollisterca** [comment]
Terminal:
pi@raspberrypi:~ $ python3 '/home/pi/Documents/Geany Projects/Hello/helloworld.py'
Hello World
pi@raspberrypi:~ $ 

Geany - Execute commands
python3 '/home/pi/Documents/Geany Projects/Hello/helloworld.py' 
or
python3 "/home/pi/Documents/Geany Projects/Hello/helloworld.py"

just produces the blanc screen. Its weird, I did not have that a few months ago. (so before a few updates)

**Comment by hollisterca** [comment]
Sorry did not mean to close

**Comment by hollisterca** [comment]
here the screenshot with the option "Don't use run script" in the Edit - Preferences - Terminal
![image](https://user-images.githubusercontent.com/23412806/46330966-f1e91f80-c615-11e8-8350-9a6cbc80cc10.png)

**Comment by elextr** [comment]
As @b4n asked, what is the command configured for Terminal in `Edit->Preferences->Tools`?

**Comment by b4n** [comment]
As the run script seems to work fine, my guess is that the configured terminal doesn't have xterm-compatible options.  It's a known issue with some terminals emulators (especially Konsole).  And now this bug looks like a dusplicate of https://github.com/geany/geany/issues/1624 ;)

(and https://www.raspberrypi.org/forums/viewtopic.php?f=66&t=191818#p1203549, although don't edit the config file manually, use the preferences instead)

**Comment by hollisterca** [comment]
Sorry must have overlooked it.
Edit - Pref -Terminal: x-terminal-emulator -e "/bin/sh %c"

I installed xterm
sudo apt install xterm
then replaced the Terminal string to : xterm -e "/bin/sh %c"
and now it works 

![image](https://user-images.githubusercontent.com/23412806/46345555-52dc1c00-c645-11e8-844b-5b552780ecfa.png)

thanks

**Comment by b4n** [comment]
@hollisterca what is x-terminal-emulator actually running? You can likely check with the command `realpath "$(which x-terminal-emulator)"` in a terminal.

**Comment by hollisterca** [comment]
pi@raspberrypi:~ $ which x-terminal-emulator
/usr/bin/x-terminal-emulator

**Comment by elextr** [comment]
@hollisterca the command you were asked to run is:

```
realpath "$(which x-terminal-emulator)"
```

**Comment by elextr** [comment]
Closed, the usual non-standard xterm replacement problem, not a Geany problem.
