### ISSUE TITLE
Cannot display file correctly

### ISSUE THREAD

**Issue by cws999** [geany/geany#1978]
The following file cannot be displayed correctly。vi，nano，uemacs，is ok
- https://github.com/torvalds/uemacs/blob/master/UTF-8-demo.txt

Comparison chart is here https://github.com/cws999/BFCA/blob/master/99.jpeg

This is my configuration  https://github.com/cws999/BFCA/blob/master/geany.conf

**Comment by b4n** [comment]
Indeed, the editing component we use (Scintilla) has issues with some characters that are wider than usual.
It might or might not be caused by the underlying library used, Pango.

Other GTK apps like the GTK text view or GEdit also behave suboptimally here.

**Comment by elextr** [comment]
I suspect it is font related, not Scintilla or Geany related, on my system (Geany Git HEAD, so Scintilla 3.10) I only see only an error on the first line of "Mathematics and Sciences", all the rest looks ok.

**Comment by elextr** [comment]
Aaaaand I finally found what the system monospace font is, Noto Sans Monospace Regular, on  GTK 3.18.9, GLib 2.48.2

**Comment by codebrainz** [comment]
> I suspect it is font related...

I agree. I can get various levels of working from completely wonky, to perfect by trying different fonts. AverageMono seems to fare very well. Also, looking at the plain text in Firefox is not great.

**Comment by cws999** [comment]
> > I suspect it is font related...
> 
> I agree. I can get various levels of working from completely wonky, to perfect by trying different fonts. AverageMono seems to fare very well. Also, looking at the plain text in Firefox is not great.

Have you tried it?  I tried,Become more chaotic

**Comment by cws999** [comment]
> I suspect it is font related, not Scintilla or Geany related, on my system (Geany Git HEAD, so Scintilla 3.10) I only see only an error on the first line of "Mathematics and Sciences", all the rest looks ok.

I change the font，Become more chaotic

**Comment by elextr** [comment]
> I change the font，Become more chaotic

So clearly the effect is font dependent.

**Comment by cws999** [comment]
> > I change the font，Become more chaotic
> 
> So clearly the effect is font dependent.

Also explained  Change fonts does not solve the problem

**Comment by elextr** [comment]
> Also explained Change fonts does not solve the problem

To explain more clearly, the problem is not Geany, its the font or the system rendering libraries that use the font.

And yes I have tried it, as I said in my first post I don't see the same problems as you see, did you try the font I posted above?

**Comment by cws999** [comment]
> > Also explained Change fonts does not solve the problem
> 
> To explain more clearly, the problem is not Geany, its the font or the system rendering libraries that use the font.
> 
> And yes I have tried it, as I said in my first post I don't see the same problems as you see, did you try the font I posted above?

Yes, I have tried it.

**Comment by elextr** [comment]
> Yes, I have tried it.

And it was better/worse/the same?
