### ISSUE TITLE
Add option to reload file after running build command

### ISSUE THREAD

**Issue by malaire** [geany/geany#1983]
In Elm-community it is the norm to use a command `elm-format` to automatically format the file according to formatting standards.

While I can add this command to Build Commands and then run it, after that I need to either
A) press Ctrl-R and answer the prompt to reload the file
B) wait until Geany detects that file has changed and answer the prompt to reload the file

To use `elm-format` properly there should be an option for Geany to reload the file after running the build command without any prompts.

**Comment by shiftee** [comment]
Take a look in **Preferences -> Various**
at the setting **reload_clean_doc_on_file_change**

I think it might solve your issue

**Comment by malaire** [comment]
@shiftee Yes, that seems to be exactly what I want. Still I also need for Geany to check if file did change immediately after running the Build Command, instead of waiting some time before checking.

**Comment by elextr** [comment]
You could also use the `elm-format --stdin` as a custom command and Geany will send the selection (ctrl+a for select all) to it and replace the selection with the result.  No files are harmed in the performance of this action :)

**Comment by elextr** [comment]
Closed workarounds available.
