### ISSUE TITLE
python: method shown as function in symbol tree

### ISSUE THREAD

**Issue by lazka** [geany/geany#1996]
The following code results in every method after the first one being shown as a top level function:

```python
class A:
    def method1(self):
        foo = (
)
    def method2(self):
        pass
```

![screenshot from 2018-11-25 14-30-51](https://user-images.githubusercontent.com/991986/48979716-2ed60d80-f0bf-11e8-90e9-770106da2a75.png)

**Comment by b4n** [comment]
Yes, this is a bug in the Python parser.  The new one we plan on using comes from @universal-ctags and doesn't suffer from this, but it's quite some work that is going on in #1263 and friends.
