### ISSUE TITLE
Add translations for Windows installer (NSIS)

### ISSUE THREAD

**Issue by scootergrisen** [geany/geany#2008]
For a more fully translated experience the translations for the NSIS Windows installer could be included.
And then have .nsi files for people to translate the strings that are specific to Geany.

**Comment by eht16** [comment]
Basically yes.
IIRC we discussed this a couple of years ago and abandoned the idea.

My concerns:
- more overhead in maintaining Windows builds (none of the Geany developers actively use Windows)
- more work for the translators for a rather small target user group
- the installer is pretty basic and most of the texts are very common and so probably can be read/understood even by non-English speaking people or at least the installer can be used successfully

Adding the NSI translations only would be an easy task, of course. One could argue so we have at least most of the texts translated. I would argue it would result in a half-translated installer with mixed languages. This is in my experience much more annoying than a complete English localized software.

Anyway, if you think we should add it, feel free to open a PR.

**Comment by scootergrisen** [comment]
Its ok if you dont think its worth the effort i just look for ways to make something i have translated a more complete translation experience for the users.

One option would be to include the strings for the .nsi files in the .po files and them extract them some how. I dont recall seeming this in other software for e.g. for .desktop files i sometimes see the strings for the .desktop file included in the .po for easy translations.

But i dont know how to do the stuff i just translate the strings.
