### ISSUE TITLE
Multi line edit not work

### ISSUE THREAD

**Issue by GFdevelop** [geany/geany#2010]
With lastest commits multi-line edit was broken, step to reproduce:
shift+alt+left click     **WORK**
shift+alt+left click     **NOT WORK**
**alt+shift**+left click     **DO NOTHING**
shift+alt+left click     **WORK AGAIN**
shift+alt+left click     **NOT WORK**
.......

**Comment by elextr** [comment]
Please post platform, version, glib and gtk version, Geany version.

**Comment by GFdevelop** [comment]
platform: arch linux
glibc: 2.28-5
gtk2: 2.24.32-1
geany: 1.34 (git >= 2fdf45730)

I'm using AUR package because gtk2 version have more plugins.

**Comment by elextr** [comment]
alt+shift+click is on windows, on linux its ctrl+shift+click see [here](https://www.geany.org/manual/current/index.html#column-mode-editing-rectangular-selections)

**Comment by GFdevelop** [comment]
I can use alt+shift or ctrl+shift but they have same results....

**Comment by elextr** [comment]
Its not intentional that they have the same result on Linux as the manual states.

But yes I can confirm ctrl+shift+click no longer creates a column selection here with GTK 3 either.

ctrl+shift+click works on a Geany with Scintilla 3.7.5 so its Scintilla 3.10.

Ping @b4n this needs addressing prior to 1.34 release.

**Comment by b4n** [comment]
Hum indeed that changed in 4.0/3.10:

> On Linux, both for GTK+ and Qt, the default modifier key for rectangular selection is now Alt. This is the same as Windows and macOS. This was changed from Ctrl as window managers are less likely to intercept Alt+Drag for moving windows than in the past. 

Ideally we'd have a setting for this, but yeah we should revert to the previous behavior.

**Comment by elextr** [comment]
> window managers are less likely to intercept Alt+Drag for moving windows than in the past.

Which window managers were they smoking?  Alt drag is move window on all Gnomic WMs AFAIK.

**Comment by GFdevelop** [comment]
I can confirm that alt+drag work...but old behaviour is better.

**Comment by b4n** [comment]
@elextr GNOME and others are using <kbd>Super</kbd> by default nowadays.

**Comment by GFdevelop** [comment]
With my window manager Mutter(Budgie) I can move window with Super+Drag or Alt+F7+move mouse.

**Comment by b4n** [comment]
@elextr  @GFdevelop could you please test #2011 and verify it works as expected for you?

**Comment by GFdevelop** [comment]
> I must say I like the new default, because it's consistent with the binding for creating rectangular selections with the keyboard (Alt+Shift+Up, Alt+Shift+Down, etc.). But I agree that we should revert to the long-time previous default, and if want to change it add an option.
> 
> @elextr I'm on it.

New behaviour is best for rectangular selections but you can't scroll page;
old behaviour is best when you need to scroll the page...

I can't choose between old or new, is possible to keep both?

**Comment by b4n** [comment]
> I can't choose between old or new, is possible to keep both?

I don't think it's currently possible to allow both at the same time.  However, we can at least add a setting later for selecting the preferred one.

**Comment by GFdevelop** [comment]
> @elextr @GFdevelop could you please test #2011 and verify it works as expected for you?

@b4n it work!!!

**Comment by elextr** [comment]
@GFdevelop just to confirm thats on GTK 2

**Comment by kugel-** [comment]
On KDE alt+drag moves windows, windows+drag does nothing.

**Comment by elextr** [comment]
Same on Cinnamon, so looks like its only Gnome thats egregiously changed the default to use the __Windows__ key :)

**Comment by codebrainz** [comment]
Yeah, <kbd>Alt</kbd>+drag has been standard on X for probably more than 30 years and it still used by all non-crummy desktops AFAIK.
