### ISSUE TITLE
How to change bookmark marker icon?

### ISSUE THREAD

**Issue by erkinsergey** [geany/geany#2020]
Please tell me how can I change the default bookmark marker icon?

![default](https://user-images.githubusercontent.com/27002236/50148441-90a62380-02c9-11e9-983b-fd6d6bfe15e5.png)

For me, this icon is too small and inconspicuous.
I would like something like

![default](https://user-images.githubusercontent.com/27002236/50148881-b7b12500-02ca-11e9-8bc0-b0fc52a9a3bc.png)

**Comment by erkinsergey** [comment]
It is a pity, while it is necessary to solve this problem with the help of color schemes.

**Comment by elextr** [comment]
You could try the numbered bookmark plugin, it might be more visible.
