### ISSUE TITLE
Force black text when printing with "invert syntax highlighting colors"

### ISSUE THREAD

**Issue by Kzer-Za** [geany/geany#2023]
Currently when the option "invert syntax highlighting colors" is on and you send a document to printer, white text on white background is printed. I understand the part about [the background is deliberately forced to white to avoid emptying the black toner cartridges](https://github.com/geany/geany/issues/1551), however, shouldn't the text be forced to black then? Currently the [intended result](https://github.com/geany/geany/issues/1551#issuecomment-316597547) is printing white on white.

So if you are using inverted colors, then each and every time before printing you have to go to Preferences -> Editor -> Display, untick the option, print the document, then go back to turn inverted colors back on again.

Why don't I use one of dark themes then, instead of inverting colors? Because (probably, because fewer people use them than the default theme?) they are less detailed than the default theme. When I was trying to find a dark theme, I was constantly seeing examples of "missed" elements of highlighting compared to the default theme (when some syntax element is highlighted in the default theme but not in the selected theme) in many filetypes.

So could please the text be forced to black (the same as background beind forced to white) when printing with the option "invert syntax highlighting colors" on?

I think avoiding the juggling with the options, as described above, is reasonable justification. Another reason is that when your printer just pushes out white sheets of paper, the first thing you think is that something is off with your printer options. It took me some time to figure out why with all CUPS options being set correctly, nothing was printed nevertheless.

**Comment by elextr** [comment]
Closed as duplicate
