### ISSUE TITLE
Find opens in new tab in Mac

### ISSUE THREAD

**Issue by denevin** [geany/geany#2024]
When I try to use find/replace in geany on Mac, it always opens in new tab on my computer and the size of find window is always the same as the current text edit window. In addition, close, previous and next buttons are always almost hidden. I tried deleting left over files and reinstalling geany but the issue persists after reinstall.

**Comment by elextr** [comment]
dup of #1729?

**Comment by denevin** [comment]
Thanks @elextr that was it. I had System Preferences > Dock > Prefer set to "Always". Changing it to any other setting fixed the issue.
