### ISSUE TITLE
Publish 1.34 package for Ubuntu

### ISSUE THREAD

**Issue by dandv** [geany/geany#2030]
I could only download 1.33 by following the instructions at https://www.geany.org/Download/ThirdPartyPackages

**Comment by elextr** [comment]
Despite its name the "Geany developer" PPA is not run by the Geany project, you need to prompt the PPA owner to update it.

**Comment by dandv** [comment]
Ping @hyperair

**Comment by hyperair** [comment]
Sorry about that, I haven't gotten around to updating Geany in Debian either. I'm still catching up on my backlog.

**Comment by elextr** [comment]
@hyperair as I said on IRC, maybe hold off for a bit looks like there will be a 1.34.1 bugfix soon

**Comment by elextr** [comment]
@hyperair ping Geany 1.34.1 is released, plugins still 1.34

**Comment by fightthepower** [comment]
@hyperair Can you add **WebHelper**  to the plugins. In 1.33 it was not included in PPA

**Comment by elextr** [comment]
It was not included in 1.33 because a library it needed was no longer available, IIUC thats fixed now, so @hyperair could add it back in now.

**Comment by hyperair** [comment]
@elextr `webkitgtk-3.0` isn't present in Debian or Ubuntu either -- you'll need to use `webkit2gtk-4.0`, as the markdown plugin already does.

**Comment by elextr** [comment]
@hyperair oh I thought it had been done, my mistake.

**Comment by elextr** [comment]
Oh, geanyplugins 677 was reverted because of markdown, and no replacement webhelper only replacement was committed.

**Comment by hyperair** [comment]
Anyway, I just published Geany 1.34.1 and Geany Plugins 1.34 on the PPA. Sorry for the delay and thanks for the reminder.

**Comment by fightthepower** [comment]
Sorry didn't saw both of your comments. @hyperair I think you have unintentionally added 4 more packages of geany and geany-plugins for 14.04 instead of other versions of ubuntu in the [PPA](https://launchpad.net/~geany-dev/+archive/ubuntu/ppa)


geany | 1.34.1-1~14.04 (Newer version available) | Chow Loong Jin (2019-03-11)
-- | -- | --
geany | 1.34.1-1~14.04 | Chow Loong Jin (2019-03-11)
geany | 1.34.1-1~14.04 | Chow Loong Jin (2019-03-11)
geany | 1.34.1-1~14.04 | Chow Loong Jin (2019-03-11)
geany | 1.34.1-1~14.04 | Chow Loong Jin (2019-03-11)

**Comment by dandv** [comment]
Thanks, great to see 1.34.1! Just a small note - the copyright year could be updated to 2019.

![image](https://user-images.githubusercontent.com/33569/54497949-d2496900-48ce-11e9-9c20-709e99bfae65.png)

**Comment by fightthepower** [comment]
@dandv @hyperair Can't seem to install geany-plugins `sudo apt-get install geany-plugins`

```
The following packages have unmet dependencies.
 geany-plugins : Depends: geany-plugin-git-changebar (>= 1.34+dfsg-1~14.04) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

```

But can install geany-plugins individually `sudo apt-get install  geany-plugin-plugin_name`

**Comment by codebrainz** [comment]
@fightthepower see geany/geany-plugins#805

**Comment by jangorecki** [comment]
@hyperair any chance to update PPA to 1.37? Thanks

**Comment by hyperair** [comment]
On Sun, Oct 25, 2020 at 11:18:54AM -0700, Jan Gorecki wrote:
> @hyperair any chance to update PPA to 1.37? Thanks

Working on it. I'm currently stuck on the geany-plugins tarball being released with
an unknown PGP key[1]. Did someone forget to upload it?

http://keys.gnupg.net/pks/lookup?search=B7A4039D0630EA07&fingerprint=on&op=index

**Comment by frlan** [comment]
*sigh* It's mine -- manually uploaded to gnupg.net -- Will update plugin's page, too
