### ISSUE TITLE
refactoring mode in geany

### ISSUE THREAD

**Issue by laoshaw** [geany/geany#2037]
Is it possible to add a refactoring flag to geany in that:

if it is in refactoring mode than we can reformat the original code(along with my new code changes) based on newline/tab-space/rules in geany at either editing time, or saving time, or both.

if it is in non-refactoring mode, then our new added code can follow whatever format rules defined by geany, however, the previous code base, even though its format is messy, we don't reformat them to avoid a noisy diff file. For example, I have a 1000 lines of messy.c code, I added 100 lines on top of that, only the 100 lines will have new formats but the old 1000 lines will not be reformatted by geany in anyway, so my git-diff/svn-diff do not lose focus when old code is involved, which is the majority of the time these days.

I see no editor can do this

**Comment by elextr** [comment]
`menu->Edit->Preferences->Files->Ensure consistent line endings`?

**Comment by codebrainz** [comment]
@laoshaw can you give some examples of document-wide changes that Geany makes? All of the things that come to mind (line endings, indentation, etc) have to be explicitly applied to have them affect the whole document (ex. replace tabs with spaces) or explicitly enabled in preferences (ex. strip trailing spaces on save), no?

**Comment by laoshaw** [comment]
```
menu->Edit->Preferences->File
menu->Edit->Preferences->Indentation
Plugins-->Addons (trailing whitespaces)
Project-->Properties
```

Yes I did use project-organizer and add-on plugins, the issue is that I had to switch on/off multiple areas when I need work on existing code vs writing code from scratch.

I can have both modes working, until I forgot then geany will reformat the old code and make the git-diff messy.

can geany support multiple profiles, each profile can have a different configuration(refactoring, new code, inverted color theme, etc)

**Comment by codebrainz** [comment]
You could achieve something similar by using a different configuration directory for each "profile". You could make an alias/shell script/launcher/shortcut to launch Geany with the given profile. To specify the configuration directory use the `-c` option when running Geany.

**Comment by elextr** [comment]
Appears solved
