### ISSUE TITLE
Ruby wrong syntax highlighting

### ISSUE THREAD

**Issue by Redouane555** [geany/geany#2038]
Geany wrongly colors sequences starting with a percentage sign (%).
Program that illustrates some issues:
```
n = 1337;
w = r = 5
x = n%w + 1; # "%w " is recognised as the beginning of an array of words, like %w[ ... ]
y = n%r ;   # "%r " is recognised as the beginning of a regular expression
string = %= this is a string = ;  # this one is correctly colored
n %= w;  # this is the most important issue, the expression is equivalent to n = n % w; but it's recognised like the previous line
print x%r  # %r is also recognised like a beginning of regex, but in this case, the %= of the previous line is still not terminated (no equal sign encoutered).
```

Tested on Geany 1.33 on Linux (Debian).

**Comment by elextr** [comment]
The highlighting is done by lexers that are part of the Scintilla editing component Geany uses, which is a separate [project](https://www.scintilla.org). Test highlighting problems in the Scite reference editor for Scintilla if you can, report them directly to Scintilla (NB Geany uses version 3.10 not version 4 when you report, but that should not affect the Ruby lexer).  Geany devs are not Ruby experts, better for you to directly communicate with the lexer maintainer.  Please post the issue number here for tracking.

**Comment by elextr** [comment]
Closed as no Scintilla bug has been raised.
