### ISSUE TITLE
Geany is changing the group ownership of remote file (stfp) when saved. [Ubuntu 16.04]

### ISSUE THREAD

**Issue by deanresin** [geany/geany#2039]
Geany is changing the group ownership of my file to the user owner when saved. This is only happening in Ubuntu 16.04 with a file over sftp.

**Comment by elextr** [comment]
Well, Geany does not do any remote operations, it only accesses local files.  So you have set up something else that does the remote operations, but you havn't said what or how.  

The wiki article referenced above describes that actual file operations performed by each of the saving methods, and notes that some create new files, which would get the default metadata for new files, and that may include a different group from that of the original.  

Without knowing how you do your remote access it not possible to suggest which may work better than the others, but in the end its a function of that setup, not Geany.

**Comment by deanresin** [comment]
I did mention the files are opened via sftp in nautilus on Ubuntu 16.04.  I tried Atom, Nano and Gedit and Vim and none of them exhibit this behaviour.

**Comment by elextr** [comment]
> I did mention the files are opened via sftp in nautilus on Ubuntu 16.04.

Thats not prescriptive, it could be GVFS, FUSE or sftpfs.

Gedit is known to use gvfs internally, but there was insufficient interest by anyone capable of testing it for a PR adding it to be included in Geany, and the PR is now well out of date.

As I said Geany only opens local files, so Nautilus must set up a FUSE or sftpfs mount for Geany when you open the file.  Check the settings for whatever mechanism it uses and see if they cause the problem.

I don't know what vim and atom do thats different, you could look and see.

**Comment by deanresin** [comment]
If you read my comment it says GVFS.  .
