### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by CheckB** [geany/geany#2040]
[config.log](https://github.com/geany/geany/files/2739616/config.log)

The problem manifests itself with any of the versions on ubuntu 18.04

How to solve?

**Comment by elextr** [comment]
`configure:3793: error: C compiler cannot create executables`''

Does gcc actually work, try it separately from configure?  If it does then are you trying to run the build in a directory you don't have write access to?

**Comment by CheckB** [comment]
Separately works, not a single package assembled.
There are rights to write / read. I have unlimited rights (root, only for building packages).

**Comment by b4n** [comment]
The interesting part is
```
configure:3744: gcc    conftest.c  >&5
/tmp/ccr38YUW.s: Assembler messages:
/tmp/ccr38YUW.s:8: Error: unsupported instruction `push'
/tmp/ccr38YUW.s:11: Error: unsupported instruction `movq'
/tmp/ccr38YUW.s:14: Error: unsupported instruction `pop'
configure:3748: $? = 1
```

I've never seen this, and my best guess is indeed that the compiler setup is broken (emitting assembly for another arch?).  Can you try manually building the same thing the *same way* (e.g. just `gcc file.c`)?
```console
$ cd /tmp
$ cat > conftest.c <<EOF
/* confdefs.h */
#define PACKAGE_NAME "Geany"
#define PACKAGE_TARNAME "geany"
#define PACKAGE_VERSION "1.35"
#define PACKAGE_STRING "Geany 1.35"
#define PACKAGE_BUGREPORT "https://github.com/geany/geany/issues"
#define PACKAGE_URL ""
#define PACKAGE "geany"
#define VERSION "1.35"
/* end confdefs.h.  */

int
main ()
{

  ;
  return 0;
}
EOF
$ gcc conftest.c
```

**Comment by CheckB** [comment]
Same...

```
/tmp/ccr38YUW.s: Assembler messages:
/tmp/ccr38YUW.s:8: Error: unsupported instruction `push'
/tmp/ccr38YUW.s:11: Error: unsupported instruction `movq'
/tmp/ccr38YUW.s:14: Error: unsupported instruction `pop'
```

uname -a
```
Linux VBuild-Packages 4.15.0-43-generic #46-Ubuntu SMP Thu Dec 6 14:45:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by codebrainz** [comment]
If you're compiling as root, you could try using a regular user instead, with a clean checkout/tarball.

Also if you could run try and compile above `conftest.c` like this:

```bash
$gcc -S -o result.S conftest.c
```

And paste the contents of `result.S` to see if it's generating valid assembly for your architecture.

**Comment by b4n** [comment]
> Same...

So this definitely isn't a Geany issue, but a compiler problem.  The code above is extremely simple, and doesn't contain any Geany code at all (you can even remove all the `#define`s, they are unused).

I'd try reinstalling gcc and friends and see how it's going.  One interesting bit that might or might not be related is that `uname` reports processor and hardware architecture, which it does not for me.  It might be interesting because apparently from the config.log `configure` tries to obtain it through `/usr/bin/uname -p`, but as `uname` is `/bin/uname` it didn't work; and likely the majority of software are using the same Autotools bit for detection.

**Comment by elextr** [comment]
>  One interesting bit that might or might not be related is that uname reports processor and hardware architecture, which it does not for me.

Nah, I get the same almost identical string.

**Comment by CheckB** [comment]
Sorry friends! Problem found. GCC broke GDB from ICC
