### ISSUE TITLE
request feature : be able to change visualisation of tab for currently opened file

### ISSUE THREAD

**Issue by piscvau** [geany/geany#2046]
Several times ran into serious problems (scratching a file) because I confuse  the highlight in red of the unsaved files' tab with the highlight of the currentlly displaid file. I would like to be able to inverse the parameters, that is:
have in red the tab's title of the currentlys displaid file 
have inversed background for the tab of not yet saved files.

**Comment by elextr** [comment]
Need more info, please post the first three lines of `Menu->Help->Debug Messages`

**Comment by b4n** [comment]
@piscvau https://www.geany.org/manual/#customizing-geany-s-appearance-using-gtk-3-css should help you, you can define yourself how they should look.

**Comment by piscvau** [comment]
Sorry for the delay in answering
here is the information about my configuration
14:22:56: Geany INFO		: Geany 1.32, fr_FR.UTF-8
14:22:56: Geany INFO		: GTK 3.22.30, GLib 2.56.3
14:22:56: Geany INFO		: System data dir: /usr/share/geany
Thanks for the info. I followed the instructions : copy the CSS fie into ~.config.geany . But it does not seem to be loaded. Any modification to do in preferences?
Another problem is that it does not seem possible to change the display of the current tab.

**Comment by elextr** [comment]
@b4n where is the Geany CSS used to set tab text colour, [this](https://github.com/geany/geany/blob/f3a85525aeff921097209d6ade6f9bb1cf2b7097/src/document.c#L3278) suggests to me it uses the theme colour, not the geany setting?

**Comment by elextr** [comment]
@b4n, Ignore my last, I found it.

**Comment by elextr** [comment]
@piscvau changing the geany-status-changed value WFM.  Geany only controls the tab text colour, not the tab, you will have to set that by the normal GTK theme name/path for the active tab.  Not sure what its called.

**Comment by elextr** [comment]
Closed because its working existing functionality.
