### ISSUE TITLE
[wiki] Create a section for building geany on BSD

### ISSUE THREAD

**Issue by andy5995** [geany/geany#2053]
I'm going to start a section on the wiki for building Geany on BSD (follow-up to https://github.com/geany/geany/issues/2049).

At https://wiki.geany.org/howtos/start when I click to edit the page, hardly any of the existing data shows up (see screenshot). Is this a permissions issue?

![image](https://user-images.githubusercontent.com/16764864/51322415-09181580-1a2b-11e9-9b4c-a566c1610053.png)

**Comment by eht16** [comment]
> At https://wiki.geany.org/howtos/start when I click to edit the page, hardly any of the existing data shows up (see screenshot). Is this a permissions issue?

No, this is the overview page and its contents are generated dynamically from all pages in the same namespace. You might have noticed the "<nspages>" tags which are responsible for expanding with sub pages in the namespace.
In short: this is on purpose.
