### ISSUE TITLE
Characters appear in the text when pressing alt+page_down having the cursor outside the line

### ISSUE THREAD

**Issue by HybridDog** [geany/geany#2066]
I noticed that when I set the cursor right of the line end (ctrl and click), and then press alt+page_down to swap the line with the next one, strange characters appear. I use geany 1.33 (built on 2018-04-16 with GTK 3.22.30, GLib 2.56.1) on Lubuntu 18.04.

![2019-01-25-154310_1920x1056_scrot](https://user-images.githubusercontent.com/3192173/51752553-0fa42e00-20b8-11e9-8fc0-bfb3178c259b.png)
![2019-01-25-154328_1920x1056_scrot](https://user-images.githubusercontent.com/3192173/51752557-129f1e80-20b8-11e9-8d3f-92530950005c.png)

**Comment by elextr** [comment]
Can't reproduce on 
```
10:37:53: Geany INFO		: Geany 1.35 (git >= 4452b36), en_AU.UTF-8
10:37:53: Geany INFO		: GTK 3.18.9, GLib 2.48.2
```

**Comment by HybridDog** [comment]
My file is quite small. I don't know if it's fixed in a newer version of geany; when I created the Issue, I thought that lubuntu 18.04 still has the newest stable version.

**Comment by elextr** [comment]
@HybridDog I don't suppose you can share your file for us to test with?  Also what filetype is it?

The latest Geany release is 1.34.1 which came out well after 18.04.

**Comment by b4n** [comment]
I just reproduced this in a quite small patch file.  I couldn't reproduce it twice, but it definitely happened to me a minute ago (1.35 ≥ c825b581b, GTK 3.24.4, GLib 2.58.2).

**Comment by elextr** [comment]
So, since I have never seen it, its an intermittent bug in GTKs newer than 3.18.9, that should be easy to find, not. :smiling_imp:

**Comment by HybridDog** [comment]
> I don't suppose you can share your file for us to test with? Also what filetype is it?

It happens everywhere, not only with a specific file. I've also tried it with the default configuration for me, it still happened.

**Comment by b4n** [comment]
OK I should have noticed the OP edition (unfortunately mails don't show them…).  Actually, it happens reliably (under  with rectangular selection, or possibly any kind of non-stream selection.  There's invalid memory manipulation inside Scintilla's `SCI_MOVESELECTEDLINESDOWN`/`UP`.

**Comment by b4n** [comment]
Forwarded: https://sourceforge.net/p/scintilla/bugs/2078/

**Comment by b4n** [comment]
Imported upstream fix.  Now moving lines with a rectangular selection will not do anything.  It's not perfect, but it way better than invalid memory access and messing up the buffer.
