### ISSUE TITLE
Feature request: please provide a 64 bit version for Windows

### ISSUE THREAD

**Issue by 9527KGG** [geany/geany#2072]
geany-1.34_setup.exe from https://download.geany.org/ is intalled to "C:\Program Files (x86)\Geany". It's a 32bit application. Please provide a 64 bit version for Windows.

Reason: 32bit exe can only use 4GB memory while 64 bit version exe does not have this limitation. 64 bit exe is useful when open large files, especially for an IDE.

**Comment by 9527KGG** [comment]
1. I find x86 window geany can easily  crashed when opening big file. Simple repro: open a 200 MB text file. Ctrl-A, Ctrl-C. Then exe crashed. Not sure if memory related or not.
2. 64bit is by default on Linux/Mac. And it's the future of Windows if not default. So I think it should be supported.
3. 64bit exe generally has better perf when opening big file comparing 32 bit exe. (You can compare 64bit notepad++ to 32bit notepad++ when opening big file on Windows)

**Comment by 9527KGG** [comment]
BTW, notepad++ 64 bit can copy & paste 200 MB text file without issue.

**Comment by codebrainz** [comment]
@eht16 would making a 64-bit binary for Windows only be using the 64-bit msys2 shell now, or is it still more complicated?

(I think I asked about this before and got a reasonable response but I can't find it or remember the details.)

**Comment by eht16** [comment]
I guess so a 64-bit MSYS2 shell is enough to create a 64-bit build of Geany.
But I didn't test it now and I think I never did before.

I don't remember the previous answer, too :(.

Just to be clear: I personally won't do this as it is too much work, IMO. Better just don't stress your clipboard with 200MB data.
Anyone is welcome to maintain the Windows builds and then he/she can also build and provide 64-bit builds.
