### ISSUE TITLE
Open files even if the encoding cannot be determined

### ISSUE THREAD

**Issue by vkmaheshbhat** [geany/geany#2081]
This is an enhancement request.

When I open a file whose character encoding can't be determined, maybe it can be assumed to be UTF-8 and display whatever can be. I have tried to open some self-extracting installer shell-scripts to alter them a bit to my needs and Geany doesn't open them saying the character encoding can't be determined.

Notepad++, for example, opens such files assuming UTF-8 encoding and displays unknown characters as "NUL". I find this feature very useful.

**Comment by elextr** [comment]
Geany does not open files containing NULs because a lot of the code uses C NUL terminated string libraries, so a lot of functionality is likely to not work or not work correctly for a file with NULs in it.

At the moment changing this is unlikely to happen.
