### ISSUE TITLE
HomeBrew Cask Upgrading doesn't work

### ISSUE THREAD

**Issue by Tricky1975** [geany/geany#2086]
I've installed Geany through HomeBrew on my mac, and that never was a problem... Until the last version of Geany. HomeBrew throws me this error when trying to upgrade

~~~
Updating Homebrew...
==> Casks with `auto_updates` or `version :latest` will not be upgraded
==> Upgrading 2 outdated packages:
Error: Cask 'geany' definition is invalid: invalid 'depends_on macos' value: ":lion"
~~~

Now uninstalling Geany and just downloading a zip goes a bit far, I think, but my problem is also, that as soon as the error pops up HomeBrew stops so my other applications do not upgrade anymore, as well, unless I do that manually (for which I must use "brew cask outdated" to find out which apps that concerns), so this bug in the Geany install scripts for HomeBrew does basically affect all my casks, and thus I'd be very very grateful if this can be fixed. :)

**Comment by frlan** [comment]
This looks like an issue on homebrew to me. We do not package for homebrew here ... Maybe report it direct at homebrew?

**Comment by Tricky1975** [comment]
Fair enough, and it appears you are right, now that I found this issue on one of the HomeBrew repositories: Homebrew/homebrew-cask#58046 (posted by a HomeBrew crew member). 

Although this appears to be a HomeBrew issue, maybe it's a good idea to leave this issue open for awhile so other Geany users, updating though HomeBrew will be aware of this. It appears that all apps with pre-mavericks references suffer here (but as Geany is the only app (which got a new version since this bug came in) I had, I wasn't sure if where the blame was). 😉

**Comment by codebrainz** [comment]
If you aren't set on using a package manager, there is an officially supported [MacOS bundle here](https://www.geany.org/Download/Releases), in case you weren't aware.

**Comment by techee** [comment]
I'm closing this as I believe it is (or rather was) a homebrew issue and has nothing to do with Geany itself.
