### ISSUE TITLE
find and replace broken

### ISSUE THREAD

**Issue by terauck21** [geany/geany#2091]
Since a recent update, Find & Replace no longer works.  I search for 'h2>' (to replace with 'h3>') and I am asked ""h2>" was not found. Wrap search and find again?" even though the sought expression is right in front of the cursor and appears again at the end of that line.  That line was a heading such as `<h2>Retraction Of Production Target Jan 2019</h2>`.

[Edited to stop github rendering the html]

**Comment by elextr** [comment]
> Since a recent update,

Versions?

**Comment by b4n** [comment]
> I am asked ""h2>" was not found. Wrap search and find again?"

Does accepting to wrap result in finding an occurrence?  You could have mistakenly checked *Search backwards* in the search dialog.
If not, does this happen all the time, or does it happen sometimes, with some documents, some searches or other specifics?

**Comment by terauck21** [comment]
Version is Geany 1.34.  Accepting to wrap search results in the string NOT being found although there are many instances in the document.  No, I didn't check _Search backwards_.  Somehow _Match only a whole word_ **was** checked; unchecking it led to a correct result.  The report is in error.
