### ISSUE TITLE
Regex. Empty line not fond in text with repeated subpattern

### ISSUE THREAD

**Issue by shiwron** [geany/geany#2096]
Good day.
Found the following.

Geany: Geany 1.34.1, Russian_Russia.1251
Geany: GTK 2.24.32, GLib 2.58.1

**1.**
Consider the following plain text:

```
123




456

```

After 123 follow five empty lines, field 456 follows one empty line.

**2.**
Open **Search/Find**
**Search for**: `(?s)^(.*)\n(.*\1)`
**Replace for**: `\2`
[v] Use regular expressions
[v] Use multi-line matching

**3**.
Repeat pressed button "In document" while replace not stoped and get next text:
```
123

456

```

**4.**
Create a new empty file and paste the text from step 3

**5.**
Repeat the procedure from steps 2 and 3. The line between 123 and 456 will be deleted.
Can you tell me what is wrong?

**Comment by elextr** [comment]
> Can you tell me what is wrong?

Looks correct to me, what did you expect it to do?

**Comment by shiwron** [comment]
> > Can you tell me what is wrong?
> 
> Looks correct to me, what did you expect it to do?

I expect all blank lines to be deleted as in step 5.

**Comment by elextr** [comment]
If you run the search and replace again _from the start of the document_ it does remove the remaining newlines.

**Comment by shiwron** [comment]
I tried to do it, but it does not work. This is only possible if you are creating a new file and inserting text to replace it again.

**Comment by elextr** [comment]
Works for me?

**Comment by shiwron** [comment]
Try on this [file](https://drive.google.com/file/d/1mhfeNKW195Gb2oIxTNcU9invh--w57L5/view?usp=sharing).

**Comment by elextr** [comment]
Your file has CRLF line endings, but you only match LF (`\n`) so you leave several CRs in the file, do `View->Show Line Endings` to see whats happening.

**Comment by shiwron** [comment]
Thanks, now everything works as it should.
