### ISSUE TITLE
Dead keys lost

### ISSUE THREAD

**Issue by anacharsis** [geany/geany#2105]
Can't type ê nor ë in edit window of
`      geany 1.34.1 (built on 2019-05-01 with GTK 3.24.1, GLib 2.58.2) 
`
using `GNOME 3.30.2` on my old laptop ASUS N73JF with a french keyboard running 
`      Fedora 29 (kernel 4.20.15-200.fc29.x86_64)
`
I just get e.
GNOME Terminal accept those unicode (UTF8 encoded chars), I can type them in  Geany's terminal plugin, copy-paste them in the edit window, but not type them in edit window.

On the same device (mutliboot) 
`      geany 1.32 (built on 2018-08-01 with GTK 3.22.26, GLib 2.54.1)
`
`GNOME 3.28.2` running
`      Ubuntu 18.04.1 LTS (kernel 4.15.0-46-generic)
`
works fine.

I love old Geany but new rolling Fedora is attractive.

**Comment by elextr** [comment]
Sounds more likely to be the GTK or Gnome versions, can you try the same version of Geany on both systems.

**Comment by anacharsis** [comment]
Thanks for your prompt comment **elextr**.
I build from source (on Fedora 29):
`./geany -V`
`geany 1.32 (built on Mar 19 2019 with GTK 3.24.1, GLib 2.58.3)
`
(GLib  2.58.2 updated to 2.58.3 last night!).
The problem is still there.

Going to study GTK-3.24.1 behavior with dead keys in edit windows (as it seems the easiest place to dig in).

**Comment by anacharsis** [comment]
I download  source of SciTE and run
`make GTK3=1`
under scintilla/gtk/  and scite/gtk (on Fedora 29).
SciTE runs almost fine from the command line... But the problem is still there, and it shows:
`Gdk-Message: 21:36:23.603: Window 0xee4c80 is a temporary window without parent, application will not be able to position it on screen.`
each time I type " or ^ dead key.
A curious thing: I can type `^e` in a search/find dialog without any problem (I get `ê`).

Where to dig now?

**Comment by elextr** [comment]
@anacharsis since the problem is GTK version dependent probably you have to dig into GTK keyboard handling.  Also I don't suppose that your locale and your keyboard layout are different, that is likely to cause problems?

**Comment by anacharsis** [comment]
I install a dayly build Ubuntu 19.04 (kernel 5.0) under VBox, and a (not snap) Geany:
`geany -V`
`geany 1.34.1 (built on 2019-30-01 with GTK 3.24.5, GLib 2.59.3)
`
It runs fine. My problem is not GTK version.

**Comment by elextr** [comment]
@anacharsis if I read your above correctly you have:

| Geany | GTK   | Works? |
| --- | --- | --- |
| 1.32    | 3.22.6 | yes        |
| 1.32    | 3.24.1 | no         |
| 1.34.1 | 3.24.1 | no         | 
| 1.34.1 | 3.24.5 | yes       |

which looks like 3.24.1 is a dud GTK version to me.

**Comment by codebrainz** [comment]
@anacharsis does it work if you run Geany like [this](https://unix.stackexchange.com/a/65755)?

```bash
XMODIFIERS="@im=none" geany
```

**Comment by jpralves** [comment]
> I download source of SciTE and run
> `make GTK3=1`
> under scintilla/gtk/ and scite/gtk (on Fedora 29).
> SciTE runs almost fine from the command line... But the problem is still there, and it shows:
> `Gdk-Message: 21:36:23.603: Window 0xee4c80 is a temporary window without parent, application will not be able to position it on screen.`
> each time I type " or ^ dead key.
> A curious thing: I can type `^e` in a search/find dialog without any problem (I get `ê`).
> 
> Where to dig now?

I've got the same problem in the official binary of fedora 29 distro. Solved by running geany with the following command:
`GDK_BACKEND=x11 geany`

It seems to be a problem with wayland gdk.

**Comment by anacharsis** [comment]
@elextr
See João Alves: I think gtk <-> wayland interactions need some more care.

@Matthew Brush
Command line
`XMODIFIERS="@im=none" geany`
produces
`Gdk-Message: ... : Window ... is a temporary window without parent, application will not be able to position it on screen.`
dead keys still lost.

@João Alves
Command line
`GDK_BACKEND=x11 geany`
runs geany fine (no dead key lost).

Thanks so much: I love Geany for so long...

**Comment by anacharsis** [comment]
To use Geany directly, add
`export GDK_BACKEND=x11`
in my .bashrc, et voilà.
