### ISSUE TITLE
Sidebar tab positions: Add left/right-vertical options

### ISSUE THREAD

**Issue by gsantner** [geany/geany#2107]
Currently there are only options to change the location of the sidebar tabs to

* 1: bottom/top (tab in one line). When you have more than ~3 enabled you usually don't see all and have to click like 5 times to get where you want...to do there what you really wanted to do
* 2: and left/right for a layout with one tab per line (which wastes a lot of horizontal space)

It would be great if there would be a left/right vertical sidebar option, so the tab names are written are written vertically and the tabs are ordered vertically.

**Example (Android studio):**
![Screenshot_20190321-161651](https://user-images.githubusercontent.com/6735650/54762690-7b080900-4bec-11e9-9ea0-3d6081571b6f.png)

 

#### 1

![Screenshot_20190321-160909](https://user-images.githubusercontent.com/6735650/54762122-624b2380-4beb-11e9-9242-f5bf67673c02.png)

##### 2

![Screenshot_20190321-160825](https://user-images.githubusercontent.com/6735650/54762113-60816000-4beb-11e9-9d74-fd8866a3f773.png)

**Comment by elextr** [comment]
The tab options are those provided [by GTK](https://developer.gnome.org/gtk3/stable/gtk3-Standard-Enumerations.html#GtkPositionType) the GUI toolkit Geany uses.

**Comment by elextr** [comment]
Note that right click on a tab shows a popup list of tabs to select from.

**Comment by codebrainz** [comment]
You can call [`gtk_label_set_angle(label, 90)`](https://developer.gnome.org/gtk3/stable/GtkLabel.html#gtk-label-set-angle) to make the tab like that. It would probably be prudent to do it from a callback on [`GtkNotebook::page-added`](https://developer.gnome.org/gtk3/stable/GtkNotebook.html#GtkNotebook-page-added) so it can be automatically applied to each tab like those added by plugins.

**Comment by elextr** [comment]
Would probably have to change packing of the close icon to below not beside.

**Comment by codebrainz** [comment]
There is no close icon (button) in the sidebar tabs.

**Comment by elextr** [comment]
> There is no close icon (button) in the sidebar tabs.

Ahh, yes, thinking of file tabs, ok, just needs "somebody" to do it then.

**Comment by gsantner** [comment]
@elextr  @codebrainz 

This code applies rotation accordingly and works for Geany-own tabs as well tabs inserted by plugins.

```
  GtkNotebook *sidebarNotebook = GTK_NOTEBOOK(ui_lookup_widget(geany->main_widgets->window, "notebook3"));
  for (GList *iterator = gtk_container_get_children(sidebarNotebook); iterator; iterator = iterator->next) {
      GtkLabel *sidebarLabel = gtk_notebook_get_tab_label(sidebarNotebook, iterator->data);
      gtk_label_set_angle(sidebarLabel, 90);
  }
```
You can do what you want with that piece, public domain.

**Comment by gsantner** [comment]
As noted it's definitely possible and not hard to-do. As I did on my own in the plugin closing.
