### ISSUE TITLE
Make ellipsization configurable

### ISSUE THREAD

**Issue by eht16** [geany/geany#2112]
In certain places (window title, some dialog titles, tab bar, ...) we shorten the document name to 30 or sometimes 100 characters by removing characters in the middle of the document name and replace it by "…".

This was initially introduced by a request in https://sourceforge.net/p/geany/bugs/298/ and committed in f1eb8dc22df5f27606acf6a49b90f05edade43c.

On the mailing list (https://lists.geany.org/users/2019-March/010970.html), it was requested to disable this feature.

One possible implementation could add two new "Various preferences" to make the currently used constants (30 and 100) configurable, with `0` as disabling the feature and add some documentation for these settings.

**Comment by elextr** [comment]
Since there is plenty of space in the `Interface->Notebook Tabs` page at least the tabs number probably should go there.

**Comment by codebrainz** [comment]
This could probably also be done in such a way that users could use GTK+ theme to configure it, avoiding the need for super obscure various or other preferences for something which seems at least mildly theme-dependent.
