### ISSUE TITLE
Don't ask to save an empty and unsaved file

### ISSUE THREAD

**Issue by xird** [geany/geany#2117]
This has been asked before:

https://github.com/geany/geany/issues/1832
https://github.com/geany/geany/issues/1710

I'm asking for it again, as I'm used to opening a new file, using it as a scratch pad, and then emptying and closing it. Geany won't let me do that, but pops up the file save dialogue instead.

Clearly there are other people out there who have a similar way of working, based on the previous issues about the same thing. One reason given (https://github.com/geany/geany/issues/1710#issuecomment-349499548) for not implementing the change is that then one would not be able to open a new file and immediately close it, in order to save an empty named file on disk. I would argue that that is a much rarer use case than using a new file as a scratch pad, as was also previously argued.

Could this be implemented as an option, then? You could allow the "scratch pad users" to check a checkbox in the preferences labeled "Don't ask to save an empty and unsaved file".

**Comment by elextr** [comment]
@xird its a perfectly reasonable request when an option means that one persons use-case doesn't prevent another persons use-case, all it needs is somebody to implement it.  Pull requests are welcome.

**Comment by codebrainz** [comment]
No need for a new issue, you can just comment on the existing issue #1710 you mentioned.
