### ISSUE TITLE
Geany 1.35: (Win10) enchant_voikko.dll': The specified module could not be found

### ISSUE THREAD

**Issue by djhenderson** [geany/geany#2136]
When I saw the announcement for Geany 1.35, I uninstalled 1.34 plugins and 1.34. I found a user only install and also uninstalled it. Then I installed Geany 1.35 and plugins on Win10. The debug log contains the following messages:

`11:51:36: (NULL) WARNING	: Error loading plugin: 'C:\Program Files (x86)\Geany/lib/enchant-2\enchant_aspell.dll': The specified module could not be found.`

`11:51:36: (NULL) WARNING	: Error loading plugin: 'C:\Program Files (x86)\Geany/lib/enchant-2\enchant_voikko.dll': The specified module could not be found.`

I have had the latest version of Geany currently available (which has both Geany and plugins for Win10) installed on this machine since Aug 2017. The named DLL does not appear to belong to any of the plugins currently available through the plugin manager. I do not recall installing a spell checker to Geany, and I would not typically install it to my programming editor as a matter of principle.

Any suggestions on how to get rid of these messages?

TIA
Doug

**Comment by eht16** [comment]
These messages come from the SpellCheck plugin and are harmless. The SpellCheck plugin uses the `enchant` library to perform spell checking and `enchant` is trying to load its `voikko` and `aspell` backends which are not available on Windows.
This is completely OK.

The SpellCheck plugin is not enabled by default, so you must have had enabled it in the past.
Uninstalling Geany removes all application data but not the user configuration (this is on purpose), so even after completely re-installing Geany, your previous settings and enabled plugin configuration is preserved.

To get rid of the messages and all spell checking functionality, simply disable the SpellCheck plugin in the plugin manager.
