### ISSUE TITLE
Test with more compiler versions on travis

### ISSUE THREAD

**Issue by elextr** [geany/geany#2139]
As was recently found with a Scintilla update Geany on Travis is only compiled with a very old compiler (Actually pre-c++11).  Even the nightlys use newer.

Travis can allow multiple compilers, so maybe we should, see https://docs.travis-ci.com/user/languages/cpp/#c11c11-and-beyond-and-toolchain-versioning.

**Comment by codebrainz** [comment]
Related: #2067

If we just wanted to bump to a GCC version that actually supports C++11 properly, I think we could just change `dist` to `xenial` to get GCC 5.4.

**Comment by elextr** [comment]
> Related: #2067

Ahh, its a pull request not an issue, thought I had seen it. @codebrainz searching wins again.

> If we just wanted to bump to a GCC version that actually supports C++11 properly, I think we could just change dist to xenial to get GCC 5.4.

Thats the simple way to at least get C++11.  

As the link shows it should be possible to go up to gcc7 with trusty and I suspect up to 8 with xenial.  The way the link does it using Travis built in capabilities is neater than #2067 so I would suggest that @andy5995 .

**Comment by andy5995** [comment]
Agreed. I've revised #2067

**Comment by andy5995** [comment]
This can be closed due to https://github.com/geany/geany/pull/2948
