### ISSUE TITLE
Split view: editing on the right window cannot be saved directly by pressing Ctrl + S

### ISSUE THREAD

**Issue by ytx21cn** [geany/geany#2141]
Geany version: 1.32
OS: Ubuntu 18.04 LTS

**Problem:** When I split window and view two different text documents in the two windows, after I do some edit on the right window, pressing Ctrl+S does not save the document on the right, but instead saves the document on the left.
**Expected result:** Since when pressing Ctrl+S, my cursor is in the right window, the document in the right window shall be saved, instead of the one in the left window.

![Screenshot from 2019-05-06 08-13-31](https://user-images.githubusercontent.com/5900105/57235054-e2302000-6fd6-11e9-9597-6af760bca0b3.png)

Gedit, on the other hand, does not have this problem.
![Screenshot from 2019-05-06 08-17-19](https://user-images.githubusercontent.com/5900105/57235302-6d111a80-6fd7-11e9-8238-2dab8d129839.png)

**Comment by codebrainz** [comment]
Moved to Geany repository since this plugin is (confusingly) not in the Geany-Plugins project.

There are many similar issues with the Split Window plugin (search issues for "[split](https://github.com/geany/geany/issues?utf8=%E2%9C%93&q=split)"), including #1523.

**Comment by elextr** [comment]
To do clear, closed as duplicate.
