### ISSUE TITLE
libsecret-1.so.0 cannot be loaded

### ISSUE THREAD

**Issue by CyberKlyde** [geany/geany#2147]

**Comment by CyberKlyde** [comment]
trying to install  tillix on a windows computer linux subsystem

**Comment by CyberKlyde** [comment]
Library libsecret-1.so.0 cannot be loaded, related functionality will not be available
Unable to init server: Could not connect: Connection refused

(tilix:6799): Gtk-WARNING **: 20:02:03.102: cannot open display:

**Comment by elextr** [comment]
I'm presuming that the message is when you start Geany?

Do any other GTK apps work?

**Comment by DanyDodson** [comment]
@CyberKlyde what was your fix ? I'm getting the same error after installing X410.

**Comment by trueloveb88** [comment]
I have the same problem can u please tell me how did u fix it ? thanks im advance

**Comment by raidryramirez** [comment]
Hi! I'm getting the same error. Can u please tell me what can i do?

> I have the same problem can u please tell me how did u fix it ? thanks im advance

**Comment by elextr** [comment]
This is not the tilix project, please post there.
