### ISSUE TITLE
Search interface/functionality improvements

### ISSUE THREAD

**Issue by rubyFeedback** [geany/geany#2148]
I am currently testing geany a lot, which explains the various issues
created.

Anyway, this time I have a bug report; or, rather than a bug per se, perhaps
a strange behaviour feature instead.

I will try to explain what I did:

- I was trying to search for a specific word/substring in a somewhat
large file (~10.000 lines or so).

- I was clicking on the expander in that search widget, for "Find All"
too.

- There, I was clicking on "In Document". (If you want to see it,
just click on the part that expands that widget downwards.)

Next result was that suddenly the bottom pane flapped upwards
and occupied like 60% of the space. With bottom pane I mean
the notebook-like thing that has the entries such as "Status",
"Compiler", "Messages", "Scribble", "Tasks".

The content in that first tab (Status) showed:

  No matches found for "abhn".

(That was the sub-word I was trying to find.)

Alternatively it will show the result of the match when it found
something, which is useful.

Anyway, the bottom pane unfortunately does not have a simple way
for me to move it downwards, so 60% is now occupied with this
status/compiler/messages/scribble/tasks widget and I can not resize
it.

I restarted geany, and that bottom pane did not show up, so I assume
that it can only be triggered (or at the least one way to trigger)
through that search-functionality.

I am not against the functionality as such, but here are two things
or three that I think are not ideal; or could be changed.

1) First, it would be great if we could resize that widget. I was
trying to find an up-and-down arrow appearing but I could not find
one. No clue why. Perhaps my gtk-version is broken, but either way
an up-and-down arrow to resize this would help.

2) Second, and perhaps more importantly ... I did not have any bottom
bane widget at all (actually I was even trying to find vte yesterday,
but I guess I don't have vte installed or geany can not find it, so
I was confused when a bottom pane suddenly showed up altogether).

To me this is by far the most surprising part. Consider that I am
working mostly full screen in a text file. Now I am trying to 
search something and I have this cute small search widget. Then
I hit "Document" and BAM, suddenly this strange bottom pane flaps
open to like 60% ... this was unexpected to me. I don't really
dislike it (only that I can not resize it) but it is unexpected
and perhaps not intuitive. First, I would like to suggest to
perhaps make it a bit smaller, right now it really occupies about
the bottom 60%; may be better to occupy only 40% or less by
default. But more importantly, I actually don't think this should
appear at all. IMO it may be better if the search widget itself
could show or indicate whether something has been found or not.
(I have not looked at the code but I assume that it shows up
in "Status" may be indicative that it is somehow registered
there first, and then geany or gtk may assume that the user wants
to see this; which is an ok assumption per se, but it does not
make a whole lot of sense to me when we were already using only
the search-widget).

3) This one probably requires more changes; the whole search
widget interface redesigning. But I don't want to suggest any
big work either. I only find the search widget/interface a 
bit confusing. Perhaps this could be a separate issue, like
asking several users of geany how they use it, what they don't
use, what they use a lot, and then eventually make some changes
in the future. The options are fine, in principle, but the
defaults seem a bit strange. For example, right now when I 
want to continue to search, I have to select the "Find"
button; the "Cancel" button is the default focus, so when I
hit enter, rather than searching again, that sub-widget
is closed. That confuses me too; was different in my old editor.
I can see people want to prefer cancel, but it may be better
to be able to allow users to tweak it. Or to actually make
an "In Document" search also part of the top-options, rather
the expanded ones, without showing up the status at all. I
usually need to search the whole document so the search 
interface is a bit sub-optimal for me right now.

**Comment by elextr** [comment]
This is a recorded message, please always provide the version of Geany, Glib and GTK (see lines near the top of Help->Debug Messages) and the operating system and version you are using.

> With bottom pane I mean
the notebook-like thing that has the entries such as "Status",
"Compiler", "Messages", "Scribble", "Tasks".

Might be the "message window" described in the [manual](https://www.geany.org/manual/current/index.html#the-geany-workspace)

> Anyway, the bottom pane unfortunately does not have a simple way
for me to move it downwards, so 60% is now occupied with this
status/compiler/messages/scribble/tasks widget and I can not resize
it.

It has a resize handle available for resizing it located at the top of the message window.  If you can't see it discuss it with your operating systems desktops themes, thats what controls the look of it.

Also in the Manual section linked above it points to the `view` menu which can hide/unhide the message window. 

Finding next can be done by:

1. de-selecting the "close dialog" so it stays open and you can keep clicking on "next"
2. menu Search->find next
3. the keybinding as the [manual](https://www.geany.org/manual/current/index.html#search-keybindings) describes.

**Comment by b4n** [comment]
>  Anyway, the bottom pane unfortunately does not have a simple way for me to move it downwards, so 60% is now occupied with this status/compiler/messages/scribble/tasks widget and I can not resize it.

As @elextr mentioned, you should be able to resize it, but lately we heard of people having desktop themes making it both hard to see (close to no visual indicator) an operate (about a 1px line triggering the feature).  Unfortunately there's nothing we can do about that, apart telling out users to use a more sensible theme and tell the authors of the offending theme to go fix it.

Also, this area doesn't take up "60%".  It takes up a configurable amount (via the handle your theme is hiding from you), and the default size is an unfortunate conflict between how this resizes with the window size and the default Geany window size.  But again, this should be easily configured by a mouse drag, and stays there where you put it across Geany runs.

> 2. Second, and perhaps more importantly ... I did not have any bottom bane widget at all (actually I was even trying to find vte yesterday, but I guess I don't have vte installed or geany can not find it, so I was confused when a bottom pane suddenly showed up altogether).

As @elextr mentioned there's an option to hide it.  Having it hidden also explains why it popped up after a *Search all in document*.  Maybe you hid this area because you couldn't find how to resize it?

> […] right now when I want to continue to search, I have to select the "Find" button; the "Cancel" button is the default focus, so when I hit enter, rather than searching again, that sub-widget is closed. That confuses me too; was different in my old editor. I can see people want to prefer cancel, but it may be better
to be able to allow users to tweak it.

There already is an option to always wrap search, see *Edit → Preferences →General → Miscellaneous → Search → Always wrap search*.  Also, you can use <kbd>\<Alt\>+f</kbd> in to find.
This said, it's also possible to cancel this dialog with <kbd>Esc</kbd> so it might not be a problem to change it, but it might also have been made this way to prevent accidental wraparound.

 
> Or to actually make an "In Document" search also part of the top-options, rather the expanded ones,

The expanded state of the *Find all* section is remembered across runs, so it shouldn't be a problem: if you like it better having it, just leave it open.
