### ISSUE TITLE
Please allow users to sort files alphabetically in the left tree list for each folder

### ISSUE THREAD

**Issue by roboirc** [geany/geany#2152]
Please allow users to view files sorted alphabetically in the left tree list for each folder. Basically for each new folder in which files are open, display the list of files open sorted by alphabet. That way its easier dealing with a huge list of open files. Thanks!

**Comment by kugel-** [comment]
I think you are looking for #1813 / #259

**Comment by elextr** [comment]
AFAICT it is already sorted alphabetically within each folder.

**Comment by roboirc** [comment]
So it sorts names of files open per directory automatically by a-z?

**Comment by LarsGit223** [comment]
@roboirc: yes, in the "Documents" tab the files of each folder are sorted alphabetically.
