### ISSUE TITLE
[feature request] syntax highlighting for device tree source files (DTS)

### ISSUE THREAD

**Issue by vinibali** [geany/geany#2164]
**Is your feature request related to a problem? Please describe.**
Syntax highlighting doesn't turn of when I open a file with dts extension

**Describe the solution you'd like**
Geany to pick C-like source highlighting

**Describe alternatives you've considered**

**Additional context**
https://www.kernel.org/doc/Documentation/devicetree/booting-without-of.txt
line:1129:"The format of the .dts "source" file is "C" like, supports C and C++"

**Comment by elextr** [comment]
Your link 404s

You can add extension to be handled as C or C++ by editing `Tools->Configuration files->filetype_extensions.conf` as described in the [manual](https://www.geany.org/manual/current/index.html#filetype-extensions)

**Comment by vinibali** [comment]
The link has been fixed and thank you for the information.
Anyway, I think somebody should take care of this request in the master branch.

BR

**Comment by codebrainz** [comment]
This kind of esoteric format is exactly why stuff like `filetype_extensions.conf` exists.

I'm closing this for now as it's already supported, just not by default. Feel free to re-open or comment more on it.
