### ISSUE TITLE
Rectangular signs in side and status window 

### ISSUE THREAD

**Issue by hlech65730** [geany/geany#2185]
Geany shows only rectangular signs instead of readable letters.
The letter types for the python code  files i could change in view menu, but the signs in the side and the status windows are not changed. How can i change this ? 
![Geany_Fehler_Win10](https://user-images.githubusercontent.com/34654103/59268922-0de59c00-8c4e-11e9-87c0-6ab684500e48.jpg)

**Comment by elextr** [comment]
This is a recorded message, please always provide the version of Geany, Glib and GTK (see lines near the top of Help->Debug Messages) and the operating system and version you are using.

**Comment by hlech65730** [comment]
the font must be  changed !
