### ISSUE TITLE
Native Emacs style caret moving keybindings

### ISSUE THREAD

**Issue by ivan-avalos** [geany/geany#2193]
Hello! I think it would be nice to have Emacs-style caret moving keybings such as:

```
C-f  Move to left
C-b  Move to right
C-n  Move down
C-p  Move up
C-e  Go to end of line
C-a  Go to start of line
```

How can I configure such keybindings? I'm not asking for general Emacs keybindings, but just the ones used to navigate through text. Thanks.

**Comment by elextr** [comment]
Similar to the Vim plugin, somebody could make an Emacs plugin.

**Comment by ivan-avalos** [comment]
I would like to tweak the Vim plugin to create my own Emacs plugin, but I don't know how.

**Comment by ivan-avalos** [comment]
I found this in `Geany.app/Contents/Resources/share/themes/Mac/gtk-2.0-key/g\
tkrc`, that seems to be the Emacs-like keybindings, but I don't know how to enable them:
```
binding "gtk-mac-emacs-like"
{
  bind "<ctrl>a" { "move-cursor" (paragraph-ends, -1, 0) }
  bind "<shift><ctrl>a" { "move-cursor" (paragraph-ends, -1, 1) }
  bind "<ctrl>e" { "move-cursor" (paragraph-ends, 1, 0) }
  bind "<shift><ctrl>e" { "move-cursor" (paragraph-ends, 1, 1) }

  bind "<ctrl>b" { "move-cursor" (logical-positions, -1, 0) }
  bind "<shift><ctrl>b" { "move-cursor" (logical-positions, -1, 1) }
  bind "<ctrl>f" { "move-cursor" (logical-positions, 1, 0) }
  bind "<shift><ctrl>f" { "move-cursor" (logical-positions, 1, 1) }
}
```

**Comment by codebrainz** [comment]
Related: #596

**Comment by ivan-avalos** [comment]
Well, now I think this is irrelevant.
