### ISSUE TITLE
How to hide a particular folder from history in geany?

### ISSUE THREAD

**Issue by fightthepower** [geany/geany#2194]
I am coding an important personal project and I dont want anything from this particular folder or its content  to be seen. Currently geany remembers our files in **recent files** and also while freshly opening geany. I dont want this for the files in a particular folder but wants to retain this function in others. Is there any way I can do this in geany?

**Comment by elextr** [comment]
You could edit the recent files list in the geany.conf, or your project.geany file, but with Geany closed, so you need to use another editor.

**Comment by fightthepower** [comment]
I saw the [files] section in geany.conf but I have to manually remove those histories. I want to know if an inbuit system or plugin available for this task.

**Comment by codebrainz** [comment]
You could probably hack something with [the `-c` option](https://www.geany.org/manual/current/index.html#command-line-options) to Geany.

Something like this not well tested shell script comes to mind:

```bash
#!/bin/sh
set -e
temp_dir=$(mktemp -d -t geany-config-XXXXXXXX) || exit 1
trap "rm -rf ${temp_dir}" EXIT
cp -r "${HOME}"/.config/geany/* "${temp_dir}"
geany -i -c "${temp_dir}"
```

Save it as an executable script somewhere and then run that when you want to hack on the super secret stuff. You could also just write a simple wrapper script that opens Geany normally and after it closes, use `sed` or whatever to delete the `recent_files` or whichever entries from `geany.conf`.

Just a couple workarounds.

**Comment by elextr** [comment]
@fightthepower to be explicit, no there is no built-in or plugin (AFAIK) for this.

**Comment by chrisgraham** [comment]
I don't believe the given workaround will work. In addition to its own config, Geany populates GTK's GtkRecentManager - meaning gedit's recent file list is going to get populate with anything you open in Geany.

**Comment by elextr** [comment]
@chrisgraham the work around should work for the Geany recent files list, but may not work for the GTK recent files list in the open dialog, which isn't under Geany control.
