### ISSUE TITLE
loses ability to change directoy when changing tab for script

### ISSUE THREAD

**Issue by userx-bw** [geany/geany#2198]
this is on 
arcolinux-v19.06.1.iso geany ver 1.35
arcolinux-v19.05.2.iso geany 1.34
Geany comes installed on this distro, the feature to change dir in the terminal with scripts path gets screwed up when I update the system after a fresh install of the distro. I've removed there repo version and installed geany from source both versions of geany mentioned and still get the same error whenever I change the tab to have it change to the dir the script is in in the terminal, I get this error .
```
[userx@archomeo SDCard]$ /home/userxcd 
bash: /home/userxcd: No such file or directory
```
I have no idea where the code is that preforms the steps to call for a directory change to even look at it to see why it is doing this. 
if I change my shell in geany to zsh it works, but bash does not work. I still get that error where the path and the command have been switch around and a space removed making it all one word.

**Comment by elextr** [comment]
Weird, its hard to see what it would be in Geany since zsh works and its the same code in Geany that sends the cd [here](https://github.com/geany/geany/blob/770cda40646e8ebfe6591df03356e2bcb71b875c/src/vte.c#L893).

I presume bash works in a normal terminal?

**Comment by codebrainz** [comment]
Just a guess, but what's `send_cmd_prefix` in the `[VTE]` section of `~/.config/geany.conf` set to? If it was set to `/home/userx`, the above results would be expected I guess.

**Comment by userx-bw** [comment]
yeah to everybody after another fresh reinstall of arcoLinux I held back the vte-common and vte3 updates 
```
vte-common 0.56.2-1 -> 0.56.3-1
vte3 0.56.2-1 -> 0.56.3-1
```
Like five minute ago, and So far it is still working, so yeah I'd say it is vte and this can be closed because I'd say it is an outside interference that is causing this issue.

**Comment by elextr** [comment]
Thanks for reporting back.
