### ISSUE TITLE
Any way to bring mnemonics back?

### ISSUE THREAD

**Issue by 801nz** [geany/geany#2215]
Another Buster victim here. GTK+3 `gtk-auto-mnemonics` and `gtk-enable-mnemonics` are deprecated long time as I see. Is there any workarounds or hacks for that?

**Comment by codebrainz** [comment]
For me with GTK+ 3.22, if I press <kbd>Alt</kbd> it underlines the mnemonics. So pressing say <kbd>Alt</kbd>+<kbd>p</kbd>+<kbd>n</kbd> works fine, even though mnemonics aren't permanently visible.

Is this what you mean, or did I misunderstand?

If not, please mention version of Geany, and GTK+/GLib (Debug->Messages), as well as operating system and desktop environment.

**Comment by 801nz** [comment]
I know that pressing `Alt` underlines "hotkeys". Was hoping that there is some way to make them permanently visible.

`Geany 1.33, C`
`GTK 3.24.5`
`GLib 2.58.3`
Debian Buster, Openbox, no desktop environment.

Also read that there is still option to use GTK2 version, but cannot decide yet. Both have their pros and cons...

**Comment by b4n** [comment]
Don't the settings you mention still work in *~/.config/gtk-3.0/settings.ini* for the moment?
Anyway, I'm afraid there isn't anything Geany can do here, it should be a GTK question.
