### ISSUE TITLE
Buggy Cursor: It is visually offset from the position where it is actually located

### ISSUE THREAD

**Issue by terric** [geany/geany#2217]
When I open a new file and start typing, the visual line representing the cursor starts moving further away from the place where it is actually located. I can click somewhere and the line will move there, but when I start typing it is offset again.

[Here's a Screen recording that shows the issue](https://giant.gfycat.com/FragrantGlitteringLeech.webm)

I'm using Arch Linux with xfce 4.14pre2 and the Mate-dark GTK theme, in case any of that matters.

I had the issue months ago, when I first tried Geany. Then I decided to wait and see, but it's still there.

**Comment by elextr** [comment]
More than that matters, please always provide the version of Geany, Glib and GTK (see lines near the top of Help->Debug Messages).

Also try a different font.

**Comment by terric** [comment]
> Geany 1.35, en_US.utf8  
> GTK 3.24.10, GLib 2.60.5

I changed the font under Edit -> Preferences -> Interface -> Fonts  
from "Monospace Regular" to "Inconsolata Regular".

From typing a bit after this change, it seems that all weirdness with the cursor is gone and works as expected.

This solves the issue, but still leaves me with a question: Why was the cursor so weird in the first place using the default font?

**Comment by elextr** [comment]
Possibly a problem with the font data, or a bug in Pango thats triggered by the font data.

**Comment by b4n** [comment]
It's quite odd that computing the caret position and the glyph position don't agree, but it might indeed be a bug in the fond itself ("monospace" generally is an alias for the default monospaced font), or how one of the component use it.

If you'd like and have time for it, it could be nice to try and debug this further.  For that you should try and find out which font "monospace" resolves to (`fc-match monospace` should tell you), and report your results to [Scintilla](https://sourceforge.net/p/scintilla/bugs/), possibly after trying out whether [SciTE](https://www.scintilla.org/SciTE.html) exhibits the problem (highly likely if Geany does).  Maybe more details are needed that I don't know, and maybe it's specific to your distro in which case more research might be required.

**Comment by terric** [comment]
Thanks for your detailed response! I will investigate this further and report back, if I figure something out...
