### ISSUE TITLE
Ridiculous user interface colors choice

### ISSUE THREAD

**Issue by NetwarSystem** [geany/geany#2237]
The poor contrast orange on white color scheme is, well, _poor_.

I spent five minutes trying to find some sort of dark theme, to no avail. Then I sadly clicked close, because it looks like this is just the thing for reviewing JSON documents.

Would be really great if there were some way to select a dark, minimal theme. Some of us are easily overstimulated ...

**Comment by elextr** [comment]
Absolutely _none_ of these is suitable? https://github.com/geany/geany-themes
