### ISSUE TITLE
Support for more flexible font scaling

### ISSUE THREAD

**Issue by toxpal** [geany/geany#2242]
I don't know if it's a limitation of Geany itself or some other library, so please accept my apologies if the issue is not related to Geany.

Many apps allow setting different font sizes, and Geany is not an exception. However, I miss the option to increase/decrease font sizes by 0.5 (which is possible with some other apps). For example, I use 9pt size for editor, and it's a bit too small, but 10pt is too large. Of course, it also depends on font family (some fonts don't need adjustment by 0.5pt to make them look "right"), but this feature would be useful with many font families.

I can manually enter font size 9.5 into Geany settings, and this value is accepted and saved, but actual font size is not changed. No matter if I enter 9.1 or 9.9, actual size is still 9.

**Comment by elextr** [comment]
The editor widget provides two functions for setting size, by integer points or integer 100th points, [see](https://www.scintilla.org/ScintillaDoc.html#SCI_STYLESETSIZE) and Geany uses the integer one [here](https://github.com/geany/geany/blob/9c91c287803ae05ce0f2aacd605564301e0ef4aa/src/sciwrappers.c#L952).

If somebody provides a PR for a function that uses the 100th point API it should be possible.

**Comment by codebrainz** [comment]
I completely agree this should be supported, and so do others in #407, #703, #772.

The PR in #407 looks completely reasonable if anyone wants to get it merged.
