### ISSUE TITLE
Black window in macOS

### ISSUE THREAD

**Issue by xingjiapeng** [geany/geany#2243]
in macOS, geany sometimes became a black window, and i can't quit it;
when i try to reboot my computer, geany always stop it,
so i force shutdown it;

**Comment by codebrainz** [comment]
@xingjiapeng What are the first two lines of "Help" menu and "Debug Messages" which show versions?

**Comment by xingjiapeng** [comment]
16:28:04: Geany INFO		: Geany 1.35, zh_CN.UTF-8
16:28:04: Geany INFO		: GTK 2.24.32, GLib 2.58.3
16:28:04: Geany INFO		: System data dir: /Applications/Geany.app/Contents/Resources/share/geany
16:28:04: Geany INFO		: User config dir: /Users/xingjiapeng/.config/geany
16:28:05: Geany INFO		: System plugin path: /Applications/Geany.app/Contents/Resources/lib/geany
16:28:05: Geany INFO		: Added filetype Clojure (61).
16:28:05: Geany INFO		: Added filetype Graphviz (62).
16:28:05: Geany INFO		: Added filetype Arduino (63).
16:28:05: Geany INFO		: Added filetype Genie (64).
16:28:05: Geany INFO		: Added filetype Cython (65).
16:28:05: Geany INFO		: Added filetype Scala (66).
16:28:05: Geany INFO		: Added filetype JSON (67).
16:28:05: Geany INFO		: Added filetype CUDA (68).
16:28:05: Geany INFO		: Loaded libvte from libvte.9.dylib
16:28:05: Geany INFO		: unknown : None (UTF-8)
16:28:06: GLib DEBUG	: posix_spawn avoided (workdir specified) (fd close requested) (child_setup specified) 

i found this black window only appear in full-screen mode(control + command + F), when i what to close an untitled file, and not save it, this black window appear

thank you very much

this geany is 1.35 on macOS

(i am a Chinese, so maybe the words have lots of mistakes)

thank you very much

**Comment by techee** [comment]
I'm afraid this will probably be some bug in the GTK implementation and not something on the Geany side. In the future I may switch to GTK 3 which might fix the problem.

**Comment by techee** [comment]
@xingjiapeng Would you try the build here https://download.geany.org/snapshots/geany-1.36_osx.dmg ? I believe it might fix your problem.

**Comment by xingjiapeng** [comment]
Thank you very much, this problem never appear again!
