### ISSUE TITLE
Crash in comments

### ISSUE THREAD

**Issue by ThVo-HuK** [geany/geany#2248]
Wenn I open a file with the content
`
/*--------------------------------------------------------------------------*/
/*!
  \file .BUG.c
*/
/*--------------------------------------------------------------------------*/

//~ //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! to do !!!!!!!!!!!!!!!!!!!!
 //~ /* noch offene Arbeiten
 //~ * /
//~ //!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! END to do !!!!!!!!!!!!!!!!

/*--- #pragma-Anweisungen --------------------------------------------------*/

`
geany crash. (File is in the ZIP archiv)

geany -v print:
Geany: Geany 1.35, German_Germany.1252
Geany: GTK 2.24.32, GLib 2.60.1
Geany: System data dir: C:\Program Files (x86)\Geany\data
Geany: User config dir: C:\Users\test\AppData\Roaming\geany
Geany: System plugin path: C:\Program Files (x86)\Geany\lib\geany
Geany: Added filetype Arduino (61).
Geany: Added filetype Clojure (62).
Geany: Added filetype CUDA (63).
Geany: Added filetype Cython (64).
Geany: Added filetype Genie (65).
Geany: Added filetype Graphviz (66).
Geany: Added filetype JSON (67).
Geany: Added filetype Scala (68).
GLib-GIO: _g_io_module_get_default: Found default implementation winhttp (GWinHttpVfs) for â?~gio-vfsâ?T
Geany: Loaded:   C:\Program Files (x86)\Geany\lib\geany\autoclose.dll (Automatisch SchlieÃYen)
Geany: Loaded:   C:\Program Files (x86)\Geany\lib\geany\addons.dll (Erweiterungen)
Geany: Loaded:   C:\Program Files (x86)\Geany\lib\geany\splitwindow.dll (Fenster teilen)
Geany: Loaded:   C:\Program Files (x86)\Geany\lib\geany\projectorganizer.dll (Project Organizer)
Geany: Converted from CP1252 to UTF-8.
Geany: D:\_Projekte\temp\BUG.c : C (CP1252)
Geany: Loaded C:\Program Files (x86)\Geany\data\tags\std99.c.tags (C), 1618 symbol(s).

![Geany-Error](https://user-images.githubusercontent.com/53895421/62687157-776ff580-b9c6-11e9-93d9-c79227aac608.png)

[BUG.zip](https://github.com/geany/geany/files/3480593/BUG.zip)

**Comment by elextr** [comment]
Please try again without any plugins enabled, if that crashes report here, if that does not crash try enabling plugins one by one until you find which crashes, then report to that plugin on https://github.com/geany/geany-plugins.

**Comment by codebrainz** [comment]
@ThVo-HuK was it a plugin crashing or something else?

**Comment by ThVo-HuK** [comment]
the plugin Addons was crashing. The funktion "Show available Tasks in theMessage Window" was the problem. I change the "Search tokens" and now it works.
old whith problems "TODO;FIXME;HACK;H A C K;!!!;TEMP;??;//~;"
new without problems"TODO;FIXME;HACK;H A C K;!!!;TEMP;??;//~ ;" Last character must a blank.
