### ISSUE TITLE
[Feature request] Select to matching brace

### ISSUE THREAD

**Issue by wiwwo** [geany/geany#2260]
CTRL-b is a great shortcut, but i cannot select text to matching brace using any shortcut like (say) CTRL-B (upper B)

**Comment by ntrel** [comment]
It should be possible to assign ctrl-shift-b to a text selection keybinding in the preferences dialog. What text do you want to be selected?

**Comment by ntrel** [comment]
Nevermind, good idea.

**Comment by LarsGit223** [comment]
As a workaround you can map "Select to previous word part" to a keybinding. You would need to press the combination several times until you get to the matching brace - therefore it is only a workaround.

**Comment by ntrel** [comment]
BTW pull #2264 implements this, please test. The selection doesn't include the enclosing braces.

**Comment by ntrel** [comment]
@wiwwo I have implemented 'Select to enclosing brackets'. If the cursor is just to the left of an opening brace then the new keybinding will actually select any brackets enclosing that opening brace. Does this sound OK?

**Comment by wiwwo** [comment]
Perfect!

**Comment by EauBureau** [comment]
I'd like to see this feature too.
This request should be reopened. It hasn't been implemented.
