### ISSUE TITLE
[Windows 10 Pro] Microsoft Print to PDF freezes

### ISSUE THREAD

**Issue by FilippoPardini** [geany/geany#2265]
Geany 1.35 in Windows 10 Pro (version 10.0.18362 compilation 18362) - PC X64 (Intel Core i7-4770K). When I print to "Microsoft Print to PDF" Geany freezes. Printing to "Microsoft Print to PDF" with any other program do not freezes .

**Comment by FilippoPardini** [comment]
Hi, 
I discovered that the problem is when I adjust the preferences of the printer directly in the print window. If I adjust the preferences with file/configure page the problem do not occur.

**Comment by codebrainz** [comment]
Thanks for the follow up. This sounds likely to be a problem outside of Geany, but who knows. I'll try and remember to reproduce and troubleshoot next time I'm on Windows if no one else can first.

**Comment by rureverek** [comment]
Issue outdated and can be closed..
Tested on Microsoft Windows Pro [Version 10.0.19044.2006] and Geany 1.38
