### ISSUE TITLE
Tab close "x" icon is hard to see with dark theme in linux

### ISSUE THREAD

**Issue by anjari** [geany/geany#2273]
I'm using geany v1.3.5 and arc dark theme in manjaro linux (cinnamon desktop).

See this screenshot image: https://i.postimg.cc/xjJpmmSM/ss1.png

The tab close "x" icon/button is difficult to see due to grey color it uses for dark theme.

I think the "x" icon color should be white or using lighter color.

**Comment by elextr** [comment]
As you said yourself its the theme, not Geany, on Minty-dark theme the Xes are the same colour as the filename.

**Comment by codebrainz** [comment]
@anjari are the X's in other GTK+ apps like that too? I don't know about Cinnamon, but in other DE's I've used, the setting for GTK+ and Icon themes are separate, so if you choose a dark widget theme, you also need to switch to a light icon theme.

**Comment by elextr** [comment]
@codebrainz is correct, Cinnamon can set themes for:

- window borders
- icons
- controls
- mouse ponter
- desktop

independently in Desktop->Preferences->Themes

**Comment by b4n** [comment]
> Also, GTK+3 broke on-the-fly theme changes, so apps have to be restarted when you change the themes

Odd, that should work in GTK3 as well, and does IME (although I did have had to provide a fix for something related to this a few years back, which might suggest they don't pay enough attention to this working properly when refactoring the world).

**Comment by elextr** [comment]
Immediate theme change works for me on Mint Cinnamon and GTK3 Geany, but thats a LTS version, so yeah, maybe it depends on what they broke today (Manjaro IIUC is much closer to the bleeding edge being Arch based).

**Comment by anjari** [comment]
It turns out that I'm using Papirus-Adapta-Maia theme icon which has grey color "x" icon (I'm using arc dark theme for the theme's control). The issue showed up after I did a system update couple days ago, probably there is update on the adapta-maia theme package which changed the icons. Changing the theme's icon fixes the issue.

**Comment by codebrainz** [comment]
> Odd, that should work in GTK3 as well, and does IME...

I've definitely had issues with it, I can't remember if it was just certain (weird) apps like Firefox, or maybe Xfce or KDE specific issue, or possibly just one of GTK+2 or 3 apps not updating when a dual-support theme is selected. Anyway, whenever it happens/happened, restarting the app always fixed it.
