### ISSUE TITLE
Enhancement: Hiding the Folding/unfolding Sidebar in the View-Menu

### ISSUE THREAD

**Issue by hubertmeier** [geany/geany#2289]
Hi, i know, the function of opening and closing functions with clicking on the small sidebar is a very useful feature, i myself use it only accidentally. Mostly i am working on php functions in the body tag, i hit the border and the whole body-tag is closed. After reopening i have to search the position of the function.

Is it possible to hide this small sidebar with unchecking a checkbox in the "View"-Menu.

Since years i was using pspad in windows but now i need an editor which is available for windows, Linux and Raspbian und so is geany my editor of choice.

Thank you

**Comment by LarsGit223** [comment]
This can be changed in the Preferences, see below:

![GeanyCodeFolding](https://user-images.githubusercontent.com/9009011/64441001-4e2dac80-d0cd-11e9-918d-d2acf6f703cd.png)

Disable the option _"Code folding"_, click _"OK"_ and the folding area at the side will disappear.

**Comment by hubertmeier** [comment]
Oh, thank you, i die not found that

**Comment by codebrainz** [comment]
Related #2095
