### ISSUE TITLE
Allow disabling use of GtkRecentManager

### ISSUE THREAD

**Issue by chrisgraham** [geany/geany#2294]
Geany is using GtkRecentManager, GNOME's system for sharing recent documents across apps.

This has the consequence of gedit, and likely many other tools, having files that were opened in Geany in their recent files list.

Developers work across dozens of files, so the recent files list in apps like gedit becomes useless. I am relying on gedits recent file list.

(Also I noted how this affects #2194)

I believe Geany should allow disabling population of GtkRecentManager, which it doesn't need anyway as it maintains its own recent file list in geany.conf.

As an aside/rant, the whole notion of GtkRecentManager seems insane to me. I reported this to them, but having that resolved is going to be a lot harder than just Geany having a config option https://gitlab.gnome.org/GNOME/gtk/issues/2138.

**Comment by elextr** [comment]
> I believe Geany should allow disabling population of GtkRecentManager, which it doesn't need anyway as it maintains its own recent file list in geany.conf.

Makes sense. Pull requests are welcome.

> As an aside/rant, the whole notion of GtkRecentManager seems insane to me. 

Totally agree, but what would we know, we are only users.

**Comment by chrisgraham** [comment]
After discussing the design of GtkRecentManager, I can see actually it's not so bad - it looks more like gedit has a bug where it's not correctly filtering (https://gitlab.gnome.org/GNOME/gedit/issues/217). But it was suggested on my GNOME issue that Geany should not be populating it for files opened whenever a project is opened - and I agree, I think that is a good solution to this.
GtkRecentManager is used for the "Recent files" feature in the GNOME file picker, and working in a project with countless files, you are not going to want the GNOME-wide file picker to be polluted.

**Comment by elextr** [comment]
I disagree, that would mean in most cases nothing from Geany ever gets into the global recents since many have projects open always.  Remember Geany "projects" are just named sessions.  (Aside, maybe Geany should never put anything in the global recents list, clearly its helping use __other__ editors :grin:)

It would probably make some sense if Geany stored a per project recents list.

I suspect Geany "projects" are not understood by Geditors since its different to most IDEs and so their advice on Geany workflow is suspect.

**Comment by chrisgraham** [comment]
Well, as per the original post, I would have no problem if Geany was adding nothing ;-). I already commented it out on my git clone.

I do agree per-project recents would be a good feature, but I see it as a separate issue.

To correct the record, I haven't talked with the gedit folks (just posted an issue) - the suggestion came from the GNOME bug.

**Comment by ntrel** [comment]
> Geany should not be populating it for files opened whenever a project is opened

I haven't used the gnome feature, but maybe geany should only update Gtk recent items when a file is opened directly by the user or saved. So opening files from a session wouldn't add recent items.

**Comment by elextr** [comment]
> I would have no problem if Geany was adding nothing ;-)

And of course its only a problem in Gnome, Cinnamon and its apps don't have a global recents list so no problem :)

**Comment by chrisgraham** [comment]
Closing as I put a merge request through to get gedit fixed.
