### ISSUE TITLE
geany won't open after fresh install on Manjaro

### ISSUE THREAD

**Issue by mathemaat** [geany/geany#2295]
Hi all,

I wanted to try out Geany on my Manjaro system, as a Linux alternative to Notepad++, however the program doesn't start.

I installed Geany using the instructions on the [Snapcraft website](https://snapcraft.io/install/geany-gtk/manjaro). Installation was succesful:

```sh
$ sudo snap install geany-gtk --edge
2019-09-10T10:23:02+02:00 INFO Waiting for restart...
geany-gtk (edge) 1.33.01+git from Felicia Hendrickson (fehfeh1) installed
```

But when I try to open Geany from the start menu, I'm getting the following error:

![image](https://user-images.githubusercontent.com/17109197/64597587-567c3500-d3b6-11e9-8215-6fc24926f50f.png)

My installation doesn't have a `/share` directory, so the error makes sense. Is there a way to solve this? How?

**Comment by elextr** [comment]
Please note that the snap package is not made by the Geany project, so you may not get a solution here.  You may be better off asking the snap creator if there is such a facility on snapcraft.

**Comment by codebrainz** [comment]
> My installation doesn't have a /share directory, so the error makes sense.

It sounds like the package you used is broken. If your `geany` binary is in, say, `/usr/bin` the `geany.glade` file needs to go into `/usr/share/geany`.

> Is there a way to solve this? How?

Geany is pretty easy to compile from source and it will get you the current version instead of one from early last year.

**Comment by mathemaat** [comment]
Thanks for your quick replies. I will try to install Geany by another method. :smile: 

After duckduckgoing around for a bit, my approach seemed to be the recommended one. :thinking:

**Comment by elextr** [comment]
> my approach seemed to be the recommended one.

By who?

**Comment by mathemaat** [comment]
> > my approach seemed to be the recommended one.
> 
> By who?

You got me there. I guess I stopped looking after I found the aforementioned installation guide on that nice looking and convincing Snapcraft website. :blush:

**Comment by elextr** [comment]
And therefore your enquires and complaints should be directed to that site, which, as I said above, is not connected to this project.
