### ISSUE TITLE
Cpp file compiled but not recognized as valid on execute

### ISSUE THREAD

**Issue by lynas685** [geany/geany#2297]
Geany fails to execute Cpp file following compiling with no error.   File was vardef.cpp written in C++ and compiled correctly with no errors, but when trying to execute, execute failed with the following message. 

'"./vardef"' is not recognized as an internal or external command, operable program or batch file
(exited with code 9009)

This has happened with other files with each message beginning with '"./filename"' 

Geany ver 1.35
Lib.gtk-2.0
gdk-pixbuf-2.0
Glib-2.0
Operating system Windows 7
Compile and Execute were performed via buttons on Geany IDE screen
C++ code.

Note:  iostream.h not part of Geany distr.  Added as file in working directory.  File code is printed below.

vardef.cpp file is as follows:

```c++
// vardef.cpp
#include <iostream>
using namespace std;
int index;

int main()
{
int stuff;
int &another_stuff = stuff; // A synonym for stuff

	stuff = index + 14;  // index was initialized to zero
	cout << "stuff has the value " << stuff << "\n";
	stuff = 17;
	cout << "another_stuff has the value " << another_stuff << "\n";
	
int more_stuff = 13;  // not automatically initialized

	cout << "more_stuff has the value " << more_stuff << "\n";
	
	for (int count = 3 ; count < 8 ; count++)
	{
		cout << "count has the value " << count << "\n";
		char count2 = count + 65;
		cout << "count2 has the value " << count2 << "\n";
	}
	
	static unsigned goofy;  // automatically initialized to zero
	
		cout << "goofy has the value " << goofy << "\n";
		
	return 0;
}

// Result of execution
// 
// stuff has the value 14
// another_stuff has the value 17
// more_stuff has the value 13
// count has the value 3
// count2 has the value D
// count has the value 4
// count2 has the value E
// count has the value 5
// count2 has the vallue F
// count has the value 6
// count 2 has the value G
// count has the value 7
// count2 has the value H
// goofy has the value 0
```
iostream.h code used follows:

```c++
// Copyright (C) 1997-1999, 2000 Free Software Foundation, Inc.
//
// This file is part of the GNU ISO C++ Library.  This library is free
// software; you can redistribute it and/or modify it under the
// terms of the GNU General Public License as published by the
// Free Software Foundation; either version 2, or (at your option)
// any later version.

// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License along
// with this library; see the file COPYING.  If not, write to the Free
// Software Foundation, 59 Temple Place - Suite 330, Boston, MA 02111-1307,
// USA.

// As a special exception, you may use this file as part of a free software
// library without restriction.  Specifically, if other files instantiate
// templates or use macros or inline functions from this file, or you compile
// this file and link it with other files to produce an executable, this
// file does not by itself cause the resulting executable to be covered by
// the GNU General Public License.  This exception does not however
// invalidate any other reasons why the executable file might be covered by
// the GNU General Public License.

#ifndef _BACKWARD_IOSTREAM_H
#define _BACKWARD_IOSTREAM_H 1

#include "backward_warning.h"
#include <iostream>

using std::iostream;
using std::ostream;
using std::istream;
using std::ios;
using std::streambuf;

using std::cout;
using std::cin;
using std::cerr;
using std::clog;
#ifdef _GLIBCXX_USE_WCHAR_T
using std::wcout;
using std::wcin;
using std::wcerr;
using std::wclog;
#endif

using std::ws;
using std::endl;
using std::ends;
using std::flush;

#endif

// Local Variables:
// mode:C++
// End:

```

Any help would be appreciated.
Regards, Paul

**Comment by lynas685** [comment]
The second line of code should have shown
#include <iostream>

This is the original code.
Regards,
Paul

**Comment by lynas685** [comment]
In copy and paste from the Geany code page, the #include statement is only copying the #include but not the <iostream> which follows.  The line two text in the original code is 
#include <iostream>
Regards, Paul

**Comment by lynas685** [comment]
Trying this again using the insert code function
`#include <iostream>`
This should be the correct in the second line of the code.
Regards, Paul

**Comment by elextr** [comment]
This is a recorded message, please always provide the version of Geany, Glib and GTK (see lines near the top of Help->Debug Messages) and the operating system and version you are using.

And in your case what the compile and run commands and directories are configured to.

**Comment by codebrainz** [comment]
(@lynas685 fixed the code block, see [here](https://help.github.com/en/articles/creating-and-highlighting-code-blocks))

**Comment by lynas685** [comment]
To confirm the code is valid, downloaded DEV-CPP 5.11 TDM-GCC 4.92 64 bit release and configured it  for latest C++ *-11 and ran the same code unmodified.  All *.CPP files compiled correctly and ran.  Iostream.h worked correctly.  So this DEV-CPP IDE system will work.  DEV-CPP is not a small footprint compiler, requiring 343 MB of disk file storage, so Geany as installed on a Raspberry Pi is useful within it's limitations.
Regards, Paul

**Comment by codebrainz** [comment]
@lynas685 make sure you configure the build command correctly (Build->Set Build Commands). It sounds like your executable is not being found by the OS when Geany tries to execute it. You can set the working directory for the "Execute" command in the "Set Builds Command" dialog (probably set it to `%p`).

**Comment by b4n** [comment]
@lynas685 Geany provides by default 2 separate commands for C++: "Compile" and "Build".  "Compile" will only call the compiler to create an object file (`.o`) which is not an executable by itself but a compiled version of the file that can be used later on to create an executable (you can think of it like a kind of static library if you will). "Build" OTOH will try and create a complete executable, which sounds lie what you want.
Make sure you use the correct one, and as @codebrainz mentioned, maybe check the commands are OK.

**Comment by lynas685** [comment]
codebrainz, b4n, Thanks for the direction.  I went into the Build pull-down settings and all working directories were blank.  I filled all the full path to my working directories and now everything works correctly.  All files compile correctly and execute.  Many thanks.  Glad to get this working correctly.  
Thanks again, Paul
