### ISSUE TITLE
build menu: images missing?

### ISSUE THREAD

**Issue by LarsGit223** [geany/geany#2302]
On looking at the build code I noticed the following table:

``` C
static struct BuildMenuItemSpec {
	const gchar	*stock_id;
	const gint	 key_binding;
	const guint	 build_grp;
	const guint	 build_cmd;
	const gchar	*fix_label;
	Callback *cb;
} build_menu_specs[] = {
	{GTK_STOCK_CONVERT, GEANY_KEYS_BUILD_COMPILE, GBO_TO_GBG(GEANY_GBO_COMPILE),
		GBO_TO_CMD(GEANY_GBO_COMPILE), NULL, on_build_menu_item},
	{GEANY_STOCK_BUILD, GEANY_KEYS_BUILD_LINK, GBO_TO_GBG(GEANY_GBO_BUILD),
		GBO_TO_CMD(GEANY_GBO_BUILD), NULL, on_build_menu_item},
	{NULL, -1, MENU_FT_REST,
		GBO_TO_CMD(GEANY_GBO_BUILD) + 1, NULL, on_build_menu_item},

    /*...more entries... */
```

As I understand the code images are loaded from the stock IDs (e.g. ```GTK_STOCK_CONVERT```). But on my system I do not see any images in the build menu (tested on GTK2 and 3). My question: do other people see any images in the build menu? Might this be a desktop issue?

**Comment by codebrainz** [comment]
![geany_build_menu](https://user-images.githubusercontent.com/181177/64923211-8f3c5580-d78c-11e9-8529-615ea49dddd8.png)

**Comment by LarsGit223** [comment]
@codebrainz: Thanks. I use Ubuntu 18.04.3, Gnome desktop. What OS do you use?

**Comment by codebrainz** [comment]
Ubuntu 18.04.3 with `xubuntu-desktop` and `paper-icon-theme`.

Didn't GNOME disable all icons in menus so that you had to install some kind of tool for tweaking the setting back? Do you have icons in the other menus?

**Comment by LarsGit223** [comment]
You are right! Executing the command
```
gsettings set org.gnome.settings-daemon.plugins.xsettings overrides "{'Gtk/ButtonImages': <1>, 'Gtk/MenuImages': <1>}"
```
and a reboot fixed the problem. Thanks.
