### ISSUE TITLE
Ability to text-edit .geany files

### ISSUE THREAD

**Issue by drws** [geany/geany#2303]
I cannot find a way to manually edit the textual .geany files in, well, Geany. I think there should be a way to open these files as text rather than a project file and apologize in advance in case I missed it.

**Comment by LarsGit223** [comment]
It works if I select it from the file browser inside of Geany or if I use _"File / Open"_ from the menu.

**Comment by codebrainz** [comment]
A workaround for the command line, if you are only opening the one `.geany` file, is to use the line/column notation, for example:

```bash
$ geany "aproject.geany:0:0"
```

**Comment by drws** [comment]
I could've sworn I had a file the first two workarounds didn't work at (I didn't check the line/column notation way on it though). However, I've been unable to reproduce it again and all of the workarounds now work.
