### ISSUE TITLE
Wrong folding mark for SVG file

### ISSUE THREAD

**Issue by hongquan** [geany/geany#2308]
Please see the screenshot

![image](https://user-images.githubusercontent.com/314607/65367815-b221aa80-dc61-11e9-9842-ef1bf2e56b75.png)

Sample SVG file:
[parkingspace_coord.zip](https://github.com/geany/geany/files/3638291/parkingspace_coord.zip)

**Comment by elextr** [comment]
The folding marks are provided by the Scintilla editor widget which is a separate project that Geany just uses.  Please check if the problem exists on the Scite editor which is the reference editor for Scintilla and report to the Scintilla project if it does.

**Comment by b4n** [comment]
@hongquan what's wrong with those?  AFAICS they fold after the `>` of the opening tag, so as your opening tags are spanning multiple lines, you don't see them on the same line as the start of the tag.  The first fold is for the `<xml>` (which `>` is indeed on line 18) open tag, and the second for the `<defs>` (which `>` is on line 20).

It could be argued that it'd be handier for some that the fold is on the *start* of the opening tag, though, but other people might just want this to hide the *contents* like it does now, and not the "lines after the opening tag start" or such.

**Comment by elextr** [comment]
Actually it rolls up the contents and the closing tag, leaving the opening tag visible so you can see what you have rolled up.

**Comment by hongquan** [comment]
@b4n Here is how Geany display 2 XML files, with the right being correct display of folding mark:

![image](https://user-images.githubusercontent.com/314607/65383764-39474f00-dd44-11e9-961a-eccb85b7efff.png)

**Comment by elextr** [comment]
@hongquan note my previous comment "it folds __after__ the opening tag so you can see whats folded" along with @b4n's comment that the folding marks are on the line with the `>` because that is where the fold is, the fold is not on the line with the `<`.

That its exactly what you are demonstrating and the folding is working as intended.

**Comment by b4n** [comment]
@hongquan to try and be clearer, the fold on line 4 on the right side corresponds to the one on line *20* on the left.

**Comment by elextr** [comment]
Or the other way, the one you have outlined on line 18 on the left corresponds to the one on line 3 on the right, not the one you have outlined on line 4 on the right.

**Comment by hongquan** [comment]
Oh, thank you. Sorry I didn't read your comments carefully!
