### ISSUE TITLE
Rust syntax highlighting is not colouring "String" as a type

### ISSUE THREAD

**Issue by liborty** [geany/geany#2314]
all other types, including user defined structs are correctly highlighted but not this basic type

**Comment by codebrainz** [comment]
You can add other types to [user-customizable `filetypes.rust` file](https://github.com/geany/geany/blob/94a944114ba3d9db4e442472c44127fecf642a42/data/filedefs/filetypes.rust) by editing the [`[keywords]` section](https://www.geany.org/manual/current/index.html#keywords-section). It appears to only have primitive types by default.

**Comment by liborty** [comment]
Yes, thanks. It would be nice though if everyone did not have to do this individually and manually. String is as primitive as the types get, being allocated on the heap notwithstanding.

**Comment by elextr** [comment]
> It would be nice though if everyone did not have to do this individually and manually. 

Pull requests are welcome.

**Comment by codebrainz** [comment]
I don't know Rust, but I assume `String` is a library type, like presumably many other types from the standard library which aren't listed (maps, vectors, etc.). From [Rust docs](https://doc.rust-lang.org/std/string/struct.String.html):

> The String type is the most common string type that has ownership over the contents of the string. It has a close relationship with its borrowed counterpart, the primitive str.

**Comment by liborty** [comment]
Yes, I expected some discussion along these lines. While this might be technically true, String is common enough for it to be useful to be highlighted. But yes, by all means highlight all standard library types along with it.

**Comment by codebrainz** [comment]
Then see @elextr's comment :smile:

**Comment by elextr** [comment]
Somebody could make a system tag file for the rust libraries similar to the C/C++/Python ones so the types become known as such.

**Comment by codebrainz** [comment]
There are [some on the wiki](https://wiki.geany.org/tags/start#rust_tags).
