### ISSUE TITLE
Dont send the complete "string" with "contextual action"

### ISSUE THREAD

**Issue by u2andres** [geany/geany#2338]
Hi, I have installed Geany in Windows 10 
- the "**about window**" give me this info : 
  - Geany 1.36
  - (compilado el día Sep 28 2019 o después) => (compiled on Sep 28 2019 or after)
  - GTK+ v2.24.32 & GLib v2.60.6

- **Here the problem**
  - when I **select a "text"** with the mouse and click over it with the **"contextual action"**( from de contextual menu ), the **"text sended"** to the **"command"** is NOT the same that I select with the mouse.

- "Test for the problem"
  - In the widget "Contextual Action" of the "Preference Dialog" I set the value :
    - C:\eid\xampp\htdocs\desarrollo\Sf_cfg\pcontextual.bat %s
  - this is the "content" of "pcontextual.bat" file : 

@ ECHO OFF

ECHO VALUE SELECTED  : %1
PAUSE
  - finally while editing a file inside "Geany" I select the following "text"
    - **/pseudocode/action/open-config/key=/pseudocode/action/:**
    - the value "echoed" by "pcontextual.bat" is :
      - **/pseudocode/action/open-config/key**
    - so, what is happening is that it "delete" everything after "="( also the "=" )
  - I have previously installed Geany( version 1.30) **_in Ubuntu_**, and doing the same process 
    ( with an equivalent "sh" ) gives me the **"complete text"**( **/pseudocode/action/open-config/key=/pseudocode/action/:** )

Thanx in advance, hugs from Andrés Zotelo

**Comment by codebrainz** [comment]
I believe this is [a Batch-ism](https://ss64.com/nt/syntax-esc.html#delimiters) and unrelated to Geany.

You could test it by running in a regular command prompt:

```batch
C:\> pcontextual.bat a=b
```

You'll probably find that `%1` contains `a` and `%2` contains `b`.

**Comment by u2andres** [comment]
Hi Mathew, 
  thanxs for your answer!!!

hugs from Andrés Zotelo

**Comment by kugel-** [comment]
Seems like we could possibly escape the `=` with `^`.

**Comment by codebrainz** [comment]
Might make it hard for people who actually intend to use the delimiters for their shell.

**Comment by elextr** [comment]
Can't the OP put `foo.bat "%s"`?

**Comment by u2andres** [comment]
thanxs elext, 
  on monday in work, I test your suggestion & reply if it is ok...

**Comment by u2andres** [comment]
Hi elextr, Mathew,, 
  this is a "final" report of the issue, 
I use it in this way :  **foo.bat "%s"** , so, on the "recieving app" I have to trim the initial and final quotes and thats all!!!

Thanxs for the help
  Hugs from Andrés
