### ISSUE TITLE
Opening multiple files opens multiple Geanys

### ISSUE THREAD

**Issue by tulsmith** [geany/geany#2357]
On Ubunto 19.04 with Geany 1.34.1, if I select multiple files in Nautilus and select "Open with Geany" from the context menu, each file opens a new instance of Geany instead of all files opening in the existing Geany window.  I don't see anything in the Preferences to control this behavior.  I would always want all files to open in the current window and would expect this to be the default behavior

**Comment by LarsGit223** [comment]
Works fine for me with Geany master branch, Ubuntu 18.04.3, Files (Nautilus) application.

**Comment by elextr** [comment]
What does Nautilus do when multiple files are opened? Does it run `geany filename` for each file or one command `geany list of files` and has this behaviour changed between Ubuntu 18 and 19?

**Comment by Alexmaister** [comment]
I have tried in ununtu 19 with the master branch of geany and it works perfectly by opening all the files in the same instance of the program.

**Comment by elextr** [comment]
Closed due to no response
