### ISSUE TITLE
F8 unbound but still doing something?

### ISSUE THREAD

**Issue by tristenator** [geany/geany#2359]
i have unbound F8 however when i press F8 it causes the cursor in the editor window to lose focus and the cursor disappears, ie: something is still happening despite being unbound.

therefore when i subsequently try to use F8 for a custom macro i find the macro still executes but then the focus is lost and i have to click the editor window again. i thought i'd try and "trick" the focus back to the editor window by adding an F2 to the end of the macro but it was to no avail...

after pressing the unbound F8 i can press TAB 7 times and see focus return back to the editor window.

also i've found after pressing the unbound F8 i can press ENTER or SPACE or ESC and focus returns to the editor window.

hth, also btw i tried pressing F8 in other random applications (browsers, other editors, etc.) just to see if i somehow had a global F8 shortcut key defined, but nothing happens when i press F8 elsewhere...

version: geany 1.35 (built on 2019-05-04 with GTK 3.22.30, GLib 2.56.4)
desktop: LXDE
o/s: 5.0.16-100.fc28

**Comment by elextr** [comment]
Sounds like your desktop is intercepting f8

**Comment by tristenator** [comment]
yeah i wondered that too, but like i said:

hth, also btw i tried pressing F8 in other random applications (browsers, other editors, etc.) just to see if i somehow had a global F8 shortcut key defined, but nothing happens when i press F8 elsewhere...

**Comment by elextr** [comment]
f8 is used by GTK for "shift focus to splitter bar" so when its undefined in Geany it passes it through to GTK and thats what it does.

**Comment by tristenator** [comment]
ah, ok. thank you for the info, i didn't think to look at gtk-specific shortcuts.

and yep i can confirm when i assign F8 to an arbitrary command (eg: "go to start of line") then the gtk event isn't fired and focus stays in the editor as expected. good!

now, it seems to me that perhaps the geanymacro plugin should conform to the same behaviour as the standard geany keybinding. anyhoo, i'll report this over on geany-plugins and see what they say.

many thanks for your help, much appreciated.

**Comment by kugel-** [comment]
Perhaps we need to introduce a special, terminating action to prevent falling through to GTK if it makes problems.

**Comment by elextr** [comment]
@kugel- in Geany I believe its intentional that things fall through, often we want the GTK action to take place, here it seems that the macro processor plugin ([see](https://github.com/geany/geany-plugins/issues/928))  is the thing that shouldn't be doing both its defined action and the GTK action.
