### ISSUE TITLE
Toolbar icons missing; only placeholders showing

### ISSUE THREAD

**Issue by jazcam** [geany/geany#2375]
Geany 1.32 on Kubuntu 18.04 (open GL 2.0); Breeze desktop theme.
I have a strange situation.  Running Geany in user mode (not as root), the toolbar icons are simply missing, with only the system place holders showing.  However, if I run Geany as root to access system files the icons show.
![genie1](https://user-images.githubusercontent.com/13166997/67165338-5c681d00-f349-11e9-81be-f981e7142d3b.png)

as root:

![genie2](https://user-images.githubusercontent.com/13166997/67165348-67bb4880-f349-11e9-8690-5229568b5c78.png)

**Comment by elextr** [comment]
Geany is supposed to use the system theme, as your user version does, so that one is correct.

Why the root user isn't supplied with a theme is a Kubuntu issue.  Maybe a Kubuntu user might be able to help.

Also Geany devs do not support running Geany as root, is a complicated application and your security isn't guaranteed. [required disclaimer]

**Comment by jazcam** [comment]
You have it backwards --running as root the icons show properly.

**Comment by elextr** [comment]
You have labelled the second image "as root" and it shows the default GTK/Geany fallback icons, not the theme icons.

**Comment by codebrainz** [comment]
To be clear, the top screenshot is using the Breeze theme from your KDE, while the bottom one is using what appears the be the default Ubuntu Humanity theme.

I don't think this is a Geany issue at all, just that you're using two different user accounts which have different icon themes configured.

**Comment by jazcam** [comment]
I'm going to let it go at that.  I think you're right, it is a problem with Kubuntu or KDE.  Also, since I posted this I've observed the same issue even with KDE apps.  The old Mint I had with KDE was near perfect but it is now obsolete and I haven't found an OS I like as well.

**Comment by omidraha** [comment]
Same issue, 

<img width="1918" height="131" alt="Image" src="https://github.com/user-attachments/assets/d0051e91-036d-4aa2-8160-3b6e397b7f79" />

```
lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.3 LTS
Release:	24.04
Codename:	noble
```

**Comment by eht16** [comment]
This might be a seperate issue, your screenshot shows basically no icons at all except a few.

Do you see any errors or warnings in Help->Debug Messages?
What icon theme do you use in Gnome?

**Comment by omidraha** [comment]
It seems to be dependent on the theme. Apparently, it automatically behaves differently, last time it was light, but now it’s dark, and it looks like the issue occurs in light mode.

**Help->Debug Messages**
```
01:10:40.736634: Geany INFO		: Geany 2.0, unknown
01:10:40.736687: Geany INFO		: GTK 3.24.41, GLib 2.80.0
01:10:40.736754: Geany INFO		: OS: Ubuntu 24.04.3 LTS (noble)
01:10:40.736766: Geany INFO		: System data dir: /usr/share/geany
01:10:40.736785: Geany INFO		: User config dir: /home/user/.config/geany
01:10:40.740089: GLib-GIO DEBUG	: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
01:10:40.743111: GLib-GIO DEBUG	: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
01:10:40.947033: Geany INFO		: Loaded GTK+ CSS theme '/usr/share/geany/geany.css'
01:10:40.950943: Geany INFO		: System plugin path: /usr/lib/x86_64-linux-gnu/geany
01:10:40.958995: Geany INFO		: Added filetype Kotlin (65).
01:10:40.959010: Geany INFO		: Added filetype TypeScript (66).
01:10:40.959021: Geany INFO		: Added filetype Genie (67).
01:10:40.959031: Geany INFO		: Added filetype Arduino (68).
01:10:40.959041: Geany INFO		: Added filetype JSON (69).
01:10:40.959051: Geany INFO		: Added filetype CUDA (70).
01:10:40.959064: Geany INFO		: Added filetype Clojure (71).
01:10:40.959074: Geany INFO		: Added filetype Meson (72).
01:10:40.959084: Geany INFO		: Added filetype Graphviz (73).
01:10:40.959094: Geany INFO		: Added filetype Scala (74).
01:10:40.959104: Geany INFO		: Added filetype Swift (75).
01:10:40.959114: Geany INFO		: Added filetype Groovy (76).
01:10:40.959123: Geany INFO		: Added filetype Cython (77).
01:10:40.959133: Geany INFO		: Added filetype Nim (78).
01:10:40.974714: Geany INFO		: Loaded libvte from libvte-2.91.so.0
01:10:40.995080: Geany INFO		: unknown : None (UTF-8)
01:10:41.054381: GLib DEBUG	: g_unix_open_pipe() called with FD_CLOEXEC; please migrate to using O_CLOEXEC instead
```

<img width="1920" height="988" alt="Image" src="https://github.com/user-attachments/assets/f9901bd1-a76a-492f-b088-071130912a30" />
