### ISSUE TITLE
change gtk theme for geany in window 7

### ISSUE THREAD

**Issue by diazvictor** [geany/geany#2379]
I have a question and it kills me for a long time, how do I change the theme of gtk in window for geany ????

I've seen several forums on how to do it, but none have helped me

**Comment by codebrainz** [comment]
I'm not on Windows at the moment, but from memory, you put a file called `.gtkrc-2.0` in your `%UserProfile%` directory (ie. `C:\Users\you\.gtkrc-2.0`) and inside that file, put a line like:

```
gtk-theme-name = "YourThemeHere"
```

**Comment by eht16** [comment]
JFTR:
beginning with Geany 1.38, the Windows builds use GTK3 and here is what is needed:

Create or edit the file `C:\Users\<username>AppData\Local\gtk-3.0\settings.ini` with the following content:
```ini
[Settings]
gtk-theme-name=Windows10
```

And your theme files should be located in `C:\Users\<username>\AppData\Local\themes\Windows10`.
Replace "<username>" with your username and "Windows10" with the theme you want to use.
