### ISSUE TITLE
Add Hy (*.hy) syntax highlighting

### ISSUE THREAD

**Issue by superseeker13** [geany/geany#2380]
Hy is a dialect of Lisp which is currently unsupported by geany's .  I plan on creating a filetype.Hy.conf for my own projects and was wondering if anyone else was already working on adding Hy support.

For more information on the language.
http://hylang.org/

**Comment by cmhobbs** [comment]
@superseeker13 Did you ever manage to put together a filetype for this?  I've just been manually setting my file type to lisp.

**Comment by elextr** [comment]
@cmhobbs you can add another extension to lisp, see https://www.geany.org/manual/current/index.html#filetype-extensions so you don't have to do it manually.

**Comment by cmhobbs** [comment]
thanks so much!  that's probably the best path forward for me.
