### ISSUE TITLE
Editor font is always bold

### ISSUE THREAD

**Issue by newhoa** [geany/geany#2382]
The font weight of the editor is always bold. If I go to Edit > Preferences > Interface > Fonts > Editor any font I choose will use the bold weight. Only the editor font does this, the symbols list and message window font both use the font weight selected.

I'm not using any color schemes, and file type is none (which I assume turns off syntax highlighting). I was using Geany 1.35 from the Ubuntu eoan repository. I uninstalled that, deleting all the configs, and just built the latest git version (1.37 Using GTK+ v3.24.12 and GLib v2.62.1 runtime libraries) and the result is the same. Choosing a font and switching between the normal and bold weight will result in no change, it will only use the bold weight.

If it's some obvious setting I missed I apologize. If there's anything more I can add please let me know. Thanks!

**Comment by elextr** [comment]
> The font weight of the editor is always bold.

The font characteristics (bold italic etc) in the editor are controlled by the syntax highlighting.  With filetype none it will follow the default font characteristics in the colour scheme, check that it is not set to bold in the colour scheme.

> Only the editor font does this, the symbols list and message window font both use the font weight selected.

Those are not controlled by the syntax highlighting, so they can be set to anything.

**Comment by newhoa** [comment]
Thank you for the very quick response. I actually came back to edit or delete this issue.

The problem is not that it is stuck in bold, it is that it does not follow the system's colour settings by default. That is what confused me, sorry. [Here is an example](https://i.imgur.com/yzxx3xo.png). So while most system themes use a slightly lighter than black color, and by default most programs and editors inherit this, geany was still using solid black making it look bold. And also the bold/regular font selection was making no difference adding to the confusion.

But almost all other editors by default will follow the system theme unless told not to. Gedit and Mousepad that I just used for that example do support colour schemes but their Default/None options honors the users system settings. Is there any way to have geany do this or to have colour schemes disabled by default? It's a little much for the user to have to create a colour scheme config file and know where to put it simply to have an editor match their already chosen system preferences.

Also I do think it causes some confusion to present the user with an option to change the font and selecting Regular/Bold weight has no change. It isn't stated anywhere, there is no gui to change the colours or font weight of the scheme, so the only option the user is presented with changing this has no affect.

Thanks again.

**Comment by elextr** [comment]
By default Geany uses the Monospace font for the editor, which is normally not actually a font, it is a system wide alias, so you can set it in the system, however on my Mint it seems like its an actual font as well since you can select the system monospace to ... Monospace, hmmm.  So in my case Geany doesn't follow the system selection since it has an actual font selected and its impolite to override user selections, oh well.

This may be happening for you too.

> Also I do think it causes some confusion to present the user with an option to change the font and selecting Regular/Bold weight has no change.

Agree.  The font selector is a standard GTK dialog, probably the weights and styles should be filtered out and only regular shown, but I'm not sure how much control GTK gives, PRs are welcome.

**Comment by newhoa** [comment]
Is there a way to disable the colour schemes? I think that's probably the most confusing part. If colour schemes were disabled would it then just follow the system theme, both font weight and colour?

**Comment by elextr** [comment]
The font isn't part of the colour schemes, you set it in the preferences, or in the View menu.  So disabling colour schemes won't help.

**Comment by newhoa** [comment]
But the colour scheme does hijack the font weight and colour and there is no way to disable that. If the rest of the application follows the system wide theme colours and the weight chosen by the user in the preferences, the editor window should do the same unless the user intentionally selects a colour scheme.

Almost all other Gtk editors (Gedit, Mousepad, Leafpad, Bluefish, Pluma, etc) have schemes that can be disabled, and are all disabled by default and inherit the system theme colours and chosen font weight from the preferences unless explicitly asked not to by the user via colour scheme.

This is a different issue than the initial report, sorry for the initial misunderstanding. If you think this is worth discussing I can open another issue with a proper title and better summary. If not that's okay too, thank you for the help. Either way you can close this if you'd like. Thanks for your responses and thoughts (and work on this program is greatly appreciated, I do love it).

**Comment by codebrainz** [comment]
> But the colour scheme does hijack the font weight and colour...

It doesn't "hijack" it as much as allows the user to override the font weight for specific syntax elements. If the theme doesn't make the fonts bold, they won't be bold.

>  ...and there is no way to disable that

If you want to have "no" colour scheme, you can paradoxically [make a theme to do that](https://gist.github.com/codebrainz/fe5ae89737559c0bf92426a371bccf3b).

**Comment by newhoa** [comment]
Allowing the user overrides as an option is great, forcing it upon them with no way to turn it off is not. Every part of the program honors the system theme except for the editor window. There is no way to do that. Further, the editor window doesn't even honor the user's own preference within the program itself when they choose the font weight. The color scheme linked is a black and white colour scheme with forced normal weighted fonts. That's not off or disabled, it's just another theme that may or may not match a users already chosen theme.

Instead of the user having an option to enable that, it's being automatically overridden and then asking the user to learn where and how to edit a config file. Just imagine if for every program or app you used you had to learn where and how to edit its unique config file just so it matches preferences you've already chosen (both system wide and inside the program itself). And then when you changed a system wide setting you had to go back and reconfigure every program.

It makes things feel broken and confusing. The user is presented with the preference option of Bold/Italic/Thin/Light/Medium/SemiBold/etc fonts and in every regard the option works except for the editor window because the forced colour scheme is overriding their decision with no way to turn it off. And while every other part of the program respects the users chosen theme, the editor window will not.

**Comment by codebrainz** [comment]
No need for a novel, I was just trying to provide a simple work around until someone volunteers to contribute a pull request to fix the issues you're having.

**Comment by codebrainz** [comment]
Just some notes if anyone wants to work on these issues in the future:

  * I think with the newer GtkFontChooser, it would be easier to filter out invalid font styles like bold and italic and such, so they aren't confusingly shown to the user.
  * It would also be possible to add a "None" colour scheme something akin to the one in the Gist linked above, although I expect making it the default would cause more confusion for most users than having syntax highlighting by default.
  * I'm not really sure what more can be done with respect to using the user's default font as Geany, just like Mousepad and Gedit, already defaults to the "Monospace" font to use the system default font, **without it's bold/italic style** (tested on Xfce).

Related: #608, #1250
