### ISSUE TITLE
Syntax highlighting for JSX files  (feature request)

### ISSUE THREAD

**Issue by howmanycharacters** [geany/geany#2388]
Is it possible in foreseeable future to include code highlighting for JSX files ? JSX is JavaScript extension for working with ReactJS. I can imagine syntax highlighting same as for regular Javascript
files. Thus all it should be necessary is the extension recognition. As of now extension recognition on the bottom panel says "filetype: None" when working with JSX files.

**Comment by elextr** [comment]
See https://www.geany.org/manual/current/index.html#filetype-extensions to add `.jsx` to javascript.

**Comment by howmanycharacters** [comment]
Thanks a bunch !
