### ISSUE TITLE
Geany becomes slow and unresponsive when editing tags of large html files?

### ISSUE THREAD

**Issue by fightthepower** [geany/geany#2401]
I have a 2GB memory system and using geany 1.36 with web helper disabled and autoclose plugin enabled. While editing some tags for a web page I noticed that geany becomes slow and unresponsive. In my case its this tag `<div class = "col-xs-12 col-sm-6 col-md-6 col-lg-6" >` , the more I edit these kind of tags the more geany becomes unresponsive and scrolling the page becomes gittery. The problem only occurs in this opened html file and when I change the focus to some other files then geany works normally.  I also tried editing the same file with different editor where it works fine. The problem happens only in geany.

This is the html page https://pastebin.com/vc2J5gcn

**Comment by LarsGit223** [comment]
Do you have any plugins enabled? Does the problem disappear if you disable all plugins?

**Comment by b4n** [comment]
What do you mean by "editing"?  could you describe precisely some steps to reproduce your issue?  Just opening your file and editing some random things in the tag itself (changing properties and values), or its content (adding or modifying child tags and text) don't seem to cause issues for me.

@LarsGit223's question is also relevant, it might very well be a plugin causing trouble (eg. pairtaghighlighter has a history about that, not saying it's that one though, as known issues have been fixed).

**Comment by fightthepower** [comment]
@b4n @LarsGit223 Yep it was caused by a plugin named **Pair Tag Highlighter** ,  geany started acting normally when I disabled this plugin. I will report this plugin in https://github.com/geany/geany-plugins

**Comment by elextr** [comment]
Closed, plugin issue.
