### ISSUE TITLE
Incorrectly show an empty line at the end of a file registered as Mac file (only CR)

### ISSUE THREAD

**Issue by Petrouchka** [geany/geany#2404]
- When I edit a Mac File (registered with only CR at the end of each line), Geany shows a new empty line at the end of the file, like as a LF character was here :
![CR](https://user-images.githubusercontent.com/3955499/69520007-bae17600-0f5b-11ea-871c-3ab5dfaf9072.png)

I agree with this if it's a CRLF or LF file, but with a CR file, the cursor should stay on the last non-empty line and geany shouldn't add an empty line at the end of the file, isn't  it ?
(the file is correctly registered, it's only a problem on the screen)

- It would be even better to show a CR file like mcedit, without any LF :
![image](https://user-images.githubusercontent.com/3955499/69520270-7b675980-0f5c-11ea-8ce1-2d1439900c58.png)

Linux Mint MATE 19.2
geany 1.32
GTK 3.22.26
GLib 2.54.1

**Comment by elextr** [comment]
Seems correct to me, the cursor is positioned where new typing will go if added at the end of the file, on the next line.

**Comment by Petrouchka** [comment]
Indeed. In this case, a new empty line at the end of the file should not be added only if Geany was showing the text like mcedit. But it's not the case, so it's OK for me. Thank you for this explanation.
