### ISSUE TITLE
Terminal Problems in Geany

### ISSUE THREAD

**Issue by Nick-us** [geany/geany#2407]
Compiling the current Github version or even release version 1.36.0 Terminal is not working.
I understand that Terminal needs libvte.
The version I have installed is libvte-2.91.so.0.5800.2
So Geany doesn't recognize her!
If I try to link using the name libvte.so Geany doesn't run

I know if I compile using the option --enable-gtk3 the terminal works
It turns out that Gt3 is different the tab bar is bigger and I didn't like it very much

So I would like to know how do I use Geany Gtk2 with Terminal working, because in the past I used it like this

Any help, information, tip will be very welcome, I appreciate it!

**Comment by elextr** [comment]
libvte2.91 is GTK3, it won't work with GTK2, you need a GTK2 VTE development library.  Since you havn't said what system you are using I can't suggest how you get it, or even if its available for your system.

**Comment by Nick-us** [comment]
> libvte2.91 is GTK3, it won't work with GTK2, you need a GTK2 VTE development library. Since you havn't said what system you are using I can't suggest how you get it, or even if its available for your system.

Your answer has already helped! But that was what I feared!
I use Slackware-Current. Thanks if you can give me a sim Link to the VTE Gtk2 Library.

And if you know how to answer, is it possible to use both versions in the system?
If not, can you tell Geany to read this library from a separate folder for example?

**Comment by Nick-us** [comment]
Another thing I did not understand, was that in Gtk3 that I imagine it should be something better, put spaces, icons so huge!
It's as if they wrote the program for blind people! I feel writing in a matchbox! kkkkkkkkkkk

**Comment by elextr** [comment]
Geany can be built for GTK2 or GTK3, just not both at once in the one executable, although if built with different prefixes you could have both available.

The GTK3 icon size is taken from the system theme, so blame whoever set the theme you use.  Oh wait, that would be you (even if by default :-)   On my Linux Mint there is a cheery dialog that lets me set the icon theme.  I expect Slackware has something similar.

You can also set Geany specific overrides in the geany.css in your config directory.
