### ISSUE TITLE
Search dialog position at Compiz window manager.

### ISSUE THREAD

**Issue by erkinsergey** [geany/geany#2409]
Please hepl me! 

Linux Mint 19.2 Tina 64.
Linux 4.15.0-72-generic x86_64.
MATE 1.22.0.
Compiz 0.9.13.1.

In all versions of Geany, in which I worked until the last, the search dialog constantly moves up and out of the desktop every time it appears. This is very annoying at work... ;(

This is not a Geany bug, as I understand it. I found out that this only happens if the window manager is Compiz. In other window managers (Marco, Metacity) this does not happen.

I would be very grateful for any information on how this can be fixed!

**Comment by elextr** [comment]
I'm not aware of any Geany contributors that use compiz, so you might need to ask somewhere else, I'm using Cinnamon so can't help.

As an aside, comment from LM forums:

```Note that Compiz has been a stability trainwreck since its inception... A spectacular trainwreck, I grant you that, but a trainwreck nevertheless. The digital equivalent of crystal meth.```

**Comment by codebrainz** [comment]
You could try closing Geany and opening up `~/.config/geany/geany.conf` in another editor, and removing the lines like `position_find_*` and those nearby which store the find dialogs' positions.

You might also try enabling or disabling "place windows" in the Compiz settings.

**Comment by erkinsergey** [comment]
Thanks for answers!

The settings in the configuration file are overwritten, so this does nothing.
I turned on "place windows" in Compiz settings. This led to the fact that the dialogue, although it rises up, does not go beyond the desktop.
I am quite happy with this decision! :)
