### ISSUE TITLE
Lua LPeg Lexers

### ISSUE THREAD

**Issue by cup** [geany/geany#2412]
Home page:

https://scintilla.sourceforge.io/LPegLexer.html

Code is available here:

https://sourceforge.net/projects/scintilla/files/scintilla/3.11.2

100 lexers already supported, and more can be added easily via Lua.

**Comment by elextr** [comment]
Pull requests are welcome, don't forget to add the code to Geany to map the Lexer codes for syntactic elements to colour scheme item names, or code to load that dynamically.  Oh and the filetype files for all those filetypes.
