### ISSUE TITLE
Geany keeps opening new instances

### ISSUE THREAD

**Issue by b-olesen** [geany/geany#2417]
Hi there,
Running on MacOS 10.15, Geany 1.36
Seems like behaviour has changed. Whenever I try to edit a txt file by clicking in the finder, Geany spawns a new instance. I did not pay notice to whether an OS upgrade or Geany upgrade caused this, but any ideas on how to get back to the "open in existing instance" behaviour ?

**Comment by motorkap** [comment]
The Geany version available [here](https://download.geany.org/snapshots/geany-1.36_osx.dmg) seems to have fixed this problem for me.

**Comment by b-olesen** [comment]
Thanks, that worked :)

**Comment by techee** [comment]
The latest release is now available from the downloads page and should fix this issue.
