### ISSUE TITLE
The Stripping Function does not seem to work on Geany

### ISSUE THREAD

**Issue by jammy-dodger** [geany/geany#2418]
hi, the rstip() function does not seem to be working on my geany app. please help!! 

![1](https://user-images.githubusercontent.com/59448938/72180052-998ef900-33e6-11ea-9fe0-7eb538d41385.JPG)

![2](https://user-images.githubusercontent.com/59448938/72180066-a01d7080-33e6-11ea-8ef6-8ed12e114e09.JPG)

Thanks for your help.😊

**Comment by elextr** [comment]
This is nothing to do with Geany, its a question about the Python library, and, even if someone here might be able to help you, you would be better to learn to lookup or ask in the right place.

https://docs.python.org/3/library/stdtypes.html?highlight=strip#str.strip
