### ISSUE TITLE
"redo" button (Ctrl+Y) does not work in Geany for Windows

### ISSUE THREAD

**Issue by hiron-jp** [geany/geany#2420]
I think "redo" button (Ctrl+Y) does not work in Geany 1.36 for Windows.
Is this a already known bug ?
(For Linux version, the button works well.)

**Comment by elextr** [comment]
On my Geany Ctrl-Y is "redo", Ctrl-Z is "undo"

**Comment by hiron-jp** [comment]
> On my Geany Ctrl-Y is "redo", Ctrl-Z is "undo"

Oh, thanks.
I edited my comment.

**Comment by elextr** [comment]
What is your locale and keyboard layout?

**Comment by hiron-jp** [comment]
My locale and keyboard layout is Japanese.

**Comment by elextr** [comment]
There has been problems in the past with Cyrillic locales where "Ctrl-Y" is actually "Ctrl+a Cyrillic character", not ASCII Y, is it possible its the same with Japanese layout?

You could try redoing the mapping in Edit->Preferences->Keybindings to map it to whatever the keyboard is sending.

**Comment by hiron-jp** [comment]
I'll check and try it.

But the button on tool bar is not active.
Can I active the button?

**Comment by elextr** [comment]
Are you sure you have something to redo? 

Try open some file, type a character, use undo to remove it and see if the redo is enabled and re-inserts the character if pressed.

**Comment by hiron-jp** [comment]
Yes.
When I use Geany on Linux Mint, I can use the button.
But on Windows, the problem happens.

**Comment by hiron-jp** [comment]
Sorry.
"redo" button works well.
I mistook meanings of "redo" in Japanese.

Thank you.
