### ISSUE TITLE
can't execute ruby files

### ISSUE THREAD

**Issue by RuinChristmas** [geany/geany#2425]
Geany 1.32 on Linux Mint 19.3
just trying to execute a ruby program by pressing F5 like I do for Python and I get this error:

```
/tmp/geany_run_script_2LITE0.sh: 7: /tmp/geany_run_script_2LITE0.sh: ruby: not found
------------------
(program exited with code: 127)
Press return to continue
```
it is just a "hello world" program, when I go to the directory in gnome terminal and type "ruby hello.rb" the program executes.

it does run in VTE mode
I have tried changing the shell from the default /bin/sh to /bin/bash
my execute command is simply: ruby "%f"

not sure why this works for python programs but not ruby. Thank you

**Comment by codebrainz** [comment]
This might be what @elextr described [in this comment](https://github.com/geany/geany/issues/1887#issuecomment-399790385).

**Comment by RuinChristmas** [comment]
Thank you for pointing me to that, @codebrainz 

it did work from running geany from command line btw

Anyway, i copied these lines from .bashrc to .profile and this solved the problem

`export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"`
