### ISSUE TITLE
custom font, foreground/background color for compiler tab in message

### ISSUE THREAD

**Issue by fightthepower** [geany/geany#2427]
Geany: latest version
System: Ubuntu 16.04

This is an already reported issue here https://github.com/geany/geany/issues/1376, I am using a dark theme in my machine and when a program returns a compiling error, it becomes hard to read those errors with dark theme enabled. Please add a way to change the font and foreground/background color of the compiler tab similar to the vte's terminal.

Already tried this 

```
cat ~/.config/geany/geany.css
/* compiler message colors */ 
#geany-compiler-error { 
    color: #F5B1AC; 
} 
#geany-compiler-context { 
    color: #FFFFFF; 
} 
#geany-compiler-message { 
    color: #B5ACF5; 
} 
```

**Comment by codebrainz** [comment]
@fightthepower can you paste the text of `Help->Debug Messages` window. The first several lines show the exact version of Geany, GTK+, GLib as well as where the GTK+ CSS theme is loaded from.

I suspect you're not using Geany built against GTK+3 which is required for the improvements referenced from the issue you linked.

**Comment by fightthepower** [comment]
This is the output ` GTK 2.24.30, GLib 2.48.2`. How can I solve this problem?
I believe in ubuntu gtk2 and gtk3 are both installed as default
```
>>dpkg -l libgtk[0-9]* | grep ^i
libgtk2.0-0:amd64
libgtk2.0-bin
libgtk2.0-cil
libgtk2.0-common
libgtk2.0-dev 
>>dpkg -l libgtk-[0-9]* | grep ^i
libgtk-3-0:amd64
 libgtk-3-bin
libgtk-3-common 
```
 and I didn't compiled geany  in my system. I installed geany through the [official tar file](https://download.geany.org/geany-1.36.tar.gz).

**Comment by elextr** [comment]
You did not show the exact version of Geany as printed in the debug messages.

**Comment by codebrainz** [comment]
I think you should install the `-dev` package for GTK+3. On my more recent Ubuntu version the package is called `libgtk-3-dev` but IIRC it used to be called something else. It's the GTK+3 version of the `libgtk2.0-dev` one you list above.

When compiling with the official tarball, pass `--enable-gtk3` to the `configure` script so it will fail and tell you whether you have the GTK+3 stuff installed.

Most likely when Ubuntu 16.04 was released, the Geany packages were built with GTK+2 so using commands such as `apt-get build-dep geany` probably won't install the GTK+3 stuff you need.

**Comment by fightthepower** [comment]
@elextr its 1.36
@codebrainz yep its giving me this error `No package 'gtk+-3.0' found`, tried installing gtk3-dev using this command `sudo apt install libgtk-3-dev` but returns unmet dependency error. When I tried to install those unmet dependencies its giving another error for unmet dependecy. It seems 16.04 doesn't allow gtk3-dev for my system

**Comment by elextr** [comment]
@fightthepower ok, was just checking, because you said you didn't compile it, but installing from tarball is compiling it, which is why you need all those development dependencies.

You could try the [PPA](https://launchpad.net/~geany-dev/+archive/ubuntu/ppa) instead (note despite the name it isn't run by the Geany devs but by the Ubuntu packager)

**Comment by fightthepower** [comment]
@elextr It seems gtk3-dev cannot be installed in my system. I found a work around; I removed compile code from `Set build commands` and added compile and run command in `Run` with `&&` connecting the two commands. Now I get the error in terminal which is more visible.

**Comment by elextr** [comment]
@fightthepower AFAICT the Geany 1.36 for Xenial on the PPA I posted above is built with GTK-3, why don't you try that instead of building it yourself?

**Comment by fightthepower** [comment]
I used to use this PPA for installing geany but It will not update as fastly as the new release of geany. Now I install geany from the tar files directly from the download section when a new version of geany is released. 

The second thing is some plugins like `webhelper` might not work with PPA version of geany.

**Comment by AnupKumarJha** [comment]
> Geany: latest version
> System: Ubuntu 16.04
> 
> This is an already reported issue here #1376, I am using a dark theme in my machine and when a program returns a compiling error, it becomes hard to read those errors with dark theme enabled. Please add a way to change the font and foreground/background color of the compiler tab similar to the vte's terminal.
> 
> Already tried this
> 
> ```
> cat ~/.config/geany/geany.css
> /* compiler message colors */ 
> #geany-compiler-error { 
>     color: #F5B1AC; 
> } 
> #geany-compiler-context { 
>     color: #FFFFFF; 
> } 
> #geany-compiler-message { 
>     color: #B5ACF5; 
> } 
> ```
if you have gtk3+ then this work.

**Comment by sej7278** [comment]
> if you have gtk3+ then this work.

doesn't work for me, its loading the css file but doing nothing with it. if i edit /usr/share/geany/geany.css as root it works.

Geany 1.38
GTK 3.24.31
GLib 2.70.4

**Comment by elextr** [comment]
@sej7278 please post the top few lines of `Help->Debug messages` down to and including the "OS:" line.

**Comment by sej7278** [comment]
Sorry it is working, seems you have to restart to see changes, can't just reload config
