### ISSUE TITLE
Geany ignores theme name in .gtkrc-2.0

### ISSUE THREAD

**Issue by rovf** [geany/geany#2429]
```
My .gtkrc-2.0 has the following content: 

# Auto-written by gtk2_prefs. Do not edit.
gtk-theme-name = "Nodoka-Squared"
style "user-font"
{
        font_name="Yu Gothic Light, Light 11"
}
widget_class "*" style "user-font"%       
```

When starting Geany, the font is taken from these settings, but the theme seems to be ignored.

Geany 1.36 on Windows 10, with GTK+v2.24.32

**Comment by codebrainz** [comment]
I'm not familiar with this theme, or even GTK+2 theming in general, but from a quick search, it looks like this theme requires Nodoka theme engine, which presumably has to be installed separately.

Two suggestions:
- Test with another GTK+2 application and see if it works. If it doesn't then it's probably unrelated to Geany and should be raised with GTK+ or the theme engine authors. I know the open source application [Hexchat](https://hexchat.github.io/) works on Windows and uses GTK+2, if you can't think of any other GTK+2 windows apps.
- Try some other themes, particularly any which might be shipped by default, and see if they work. If so, it's probably something related to Nodoka like not having it installed.

Most likely there will be some debug messages printed if/when the theme fails to load, which you can see using `Help->Debug Messages`.

**Comment by rovf** [comment]
How can i find, which themes are installed, respectively where does Geany look for them? I thought that, if the GTK theme chooser is offering me a theme for selection, that the theme is there. 

For instance I found on my disk the following locations for the nodoka themes:

C:\p\GTK\2.0\share\themes\Nodoka-Squared
C:\p\gtk2-themes-2009-09-07-win32_bin\share\themes\Nodoka-Squared

My Geany is "C:\Program Files (x86)\Geany\bin\geany.exe"

**Comment by codebrainz** [comment]
> How can i find, which themes are installed

GTK+ has preset paths to look in, usually `$PREFIX/share/themes` and somewhere below your home directory (depends on the platform, on win32 it's a funny path like AppData or such, depending on Windows version). There is probably also an environment variable to control where GTK+ looks.

> respectively where does Geany look for them?

Geany itself isn't involved, but the GTK+ bundled with Geany will look below Geany's installation directory as that's its `$PREFIX`, in addition to the themes directory below your home directory.

> I thought that, if the GTK theme chooser is offering me a theme for selection, that the theme is there.

AFAIK there is no official GTK+ theme chooser, which if true means you may have installed some 3rd party utility (possibly bundled with a 3rd party release of GTK+?).

> C:\p\GTK\2.0\share\themes\Nodoka-Squared

This `C:\p\GTK\2.0` directory doesn't come from Geany, it must be a separate GTK+ distribution that you installed separately, so the GTK+ bundled with Geany won't look there for themes. The GTK+ that comes with Geany would be found under it's directory in `C:\Program Files (x86)\Geany`, and most likely looks for themes in `C:\Program Files (x86)\Geany\share\themes` (can't say for sure as I don't have a win32 installation available).

**Comment by rovf** [comment]
I don't know how official it is with respect to the GTK+ distribution, but I'm using the selector by Alexander Shaduri which officially belongs to a prodget called [pidgin](https://developer.pidgin.im/wiki/Using%20Pidgin#win32_gtk_theme). I don't know however to what extend pidgin is officially related to GTK.
I'll copy the themes over to Geany\share\themes, as you suggested.

**Comment by rovf** [comment]
Copying the themes worked, but it turned out to be more complicated than expected. Geany installs itself by default into "C:\Program Files (x86)", and it turned out that I did not have permissions to modify this directory. I finally started a new shell using "administrator privileges", and copied the theme files from this shell, and now my themes show up.

**Comment by codebrainz** [comment]
> However, since not all Windows users have local admin rights, I suggest that Geany advices the user during installation to choose an install directory where he has full control.

I know on Linux you can put themes in `~/.themes` or `~/.local/share/themes` and they get picked up, there's probably some equivalent hidden directories on Windows that GTK+ looks for themes and stuff, which doesn't require Admin permissions. A quick Google suggests one or more of these might the place to put themes:

* C:/Documents and Settings/username/Local Settings/Application Data/themes/
* C:/Documents and Settings/username/.themes/
* C:/Documents and Settings/All Users/Application Data/themes/
* C:/Documents and Settings/All Users/Documents/themes/
