### ISSUE TITLE
Geany 1.36 unable to launch on Catalina

### ISSUE THREAD

**Issue by skytect** [geany/geany#2430]
My computer is running on MacOS Catalina 10.15.1 (19B88).

I installed Geany from https://download.geany.org/geany-1.36_osx.dmg. However, every time I attempt to launch Geany, it would just automatically close itself. When I execute `/Applications/Geany.app/Contents/MacOS/geany` from the command line, the result is:
```
/Applications/Geany.app/Contents/MacOS/geany: line 17: dirname: command not found
/Applications/Geany.app/Contents/MacOS/geany: line 18: basename: command not found
/Applications/Geany.app/Contents/MacOS/geany: line 30: basename: command not found
/Applications/Geany.app/Contents/MacOS/geany: line 31: dirname: command not found
/Applications/Geany.app/Contents/MacOS/geany: line 32: dirname: command not found
/Applications/Geany.app/Contents/MacOS/geany: line 33: dirname: command not found
/Applications/Geany.app/Contents/MacOS/geany: line 61: defaults: command not found
/Applications/Geany.app/Contents/MacOS/geany: line 89: /Contents/MacOS/-bin: No such file or directory
/Applications/Geany.app/Contents/MacOS/geany: line 89: exec: /Contents/MacOS/-bin: cannot execute: No such file or directory
```

So far I have found a workaround. After launching Geany at least once (to avoid the "app is damaged" error message), one can remove the `-l` from the first line of `/Applications/Geany.app/Contents/MacOS/geany`, `#!/bin/bash -l`. This would allow Geany to launch without issues.

**Comment by codebrainz** [comment]
You could try the snapshot @techee [linked to](https://download.geany.org/snapshots/geany-1.36_osx.dmg) in a comment on [another Catalina bug](https://github.com/geany/geany-osx/issues/13#issuecomment-544683404).

Related #2344

**Comment by techee** [comment]
The latest version available from the Geany downloads page should work fine now.
