### ISSUE TITLE
Geany execute issue Fedora 31

### ISSUE THREAD

**Issue by anonwz** [geany/geany#2432]
When i try to run the code i receive this error:
Cannot execute build command "xterm -e "/bin/sh /tmp/geany_run_script_V87JF0.sh"": No such file or directory. Check the Terminal setting in Preferences
I'm not sure this is geany issue.

**Comment by elextr** [comment]
do you have xterm installed?

**Comment by anonwz** [comment]
> do you have xterm installed?

Oh my thank you very much it helped
