### ISSUE TITLE
'.' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by ljunzju** [geany/geany#2437]
Hi there,

I am a user of Geany for Python. One day I encountered an error when I run the software: '.' is not recognized as an internal or external command, no matter what is the code even though print("Hello world"). I tried to reinstall the software and reboot the computer but the error shows up all the time. It was running perfectly before this happened.

**Comment by elextr** [comment]
Try running Geany with a new configuration, on Linux `geany -c /tmp/something_that_does_not_exist`

If that fixes it you have modified something in your configuration and need to unmodify it.  Note re-installing won't change your config, you need to either delete it and set up again, or find what you broke (probably a build command).  Which is easier will depend on how much you have changed in the config.

**Comment by b4n** [comment]
Given the error message, I'd wager you're on Windows.  So the configuration is somewhere around `C:\Users\YourName\Roaming\geany` or something like that (not being a Windows user myself it's a rough guess)

**Comment by ljunzju** [comment]
> Given the error message, I'd wager you're on Windows. So the configuration is somewhere around `C:\Users\YourName\Roaming\geany` or something like that (not being a Windows user myself it's a rough guess)

Yes, I am using Windows and solved the issue by following your comments. It is because of the configuration. Even though I tried to reload configuration from the TOOLS at the beginning which did not solve the problem. This time what I did was locate to the Roaming\geany folder and delete the geany.conf file and it's working perfectly. Thanks a lot

**Comment by elextr** [comment]
Colsed fixed
