### ISSUE TITLE
Can't run Geany. libatk-1.0-0.dll is missing

### ISSUE THREAD

**Issue by Igor-Arnaut** [geany/geany#2443]
Hello,
I recently installed Geany and every time I try to run it I get an error telling me that libatk-1.0-0.dll is missing. I checked the installation folder and found nothing.
![geany](https://user-images.githubusercontent.com/57326929/74855767-67f04280-5341-11ea-90fa-f9a354ec984d.png)
How do I fix this?

Version: 1.36
OS: Windows 7

**Comment by codebrainz** [comment]
Can you provide the link to the installer file you downloaded?

**Comment by Igor-Arnaut** [comment]
> 
> 
> Can you provide the link to the installer file you downloaded and also whether you changed any options during installation, and if so which ones?
> 
> For example, if you disable the GTK+ runtime, you'll get this exact error.

Downloaded from [there](https://geany.org/download/releases/). Minimal installation.

**Comment by eht16** [comment]
Did you disable installing the GTK runtime in the installer? If so, that's the problem. You need to install the GTK runtime environment except it is already installed globally on your system which seems not to be the case.

Try re-installing Geany with the GTK runtime option enabled.

**Comment by Igor-Arnaut** [comment]
Thank you, that solved it.
