### ISSUE TITLE
Notebook tabs mouse scroll with gtk3

### ISSUE THREAD

**Issue by luigifab** [geany/geany#2455]
This is a duplicate of #1778 #1815 #1848, but here is a solution.
I see that in mate-appearance-properties the mouse scroll works very well like this:

```c
#include <gdk/gdk.h>
#if GTK_CHECK_VERSION (3,4,0) && !GTK_CHECK_VERSION (4,0,0)
// gtk-scroll-tabs for GTK 3.4 to 3.24
gtk_widget_add_events (GTK_WIDGET (n), GDK_SCROLL_MASK);
g_signal_connect (GTK_WIDGET (n), "scroll-event",
				G_CALLBACK (capplet_dialog_page_scroll_event_cb),
				GTK_WINDOW (window));
#endif
```

[source](https://github.com/mate-desktop/mate-control-center/blob/master/capplets/appearance/appearance-main.c#L208) + [capplet_dialog_page_scroll_event_cb function](https://github.com/mate-desktop/mate-control-center/blob/master/capplets/common/capplet-util.c#L173)

**Comment by fakub** [comment]
I suffer from this GTK3 bug very much, too. Would you please describe where I can put this snippet to compile geany myself? Thanks!

**Comment by luigifab** [comment]
You can add this where Geany create notebooks in source file, but I don't know where is it.

**Comment by elextr** [comment]
If somebody makes a Geany pull request it could be considered.

**Comment by codebrainz** [comment]
Note that it's not just the snippet pasted in the description, the whole function in @luigifab's 2nd link also needs to be implemented.

**Comment by luigifab** [comment]
Yes, the entire function must be used, but it is included in a source file that uses the same license as Geany.

Yes, GTK has removed this user interface interaction, but it is useful, perhaps not for you. It's like menu icons, GTK 3 has spent time explaining to everyone that we need to delete them, and it looks like GTK 4 will delete them.

Same thing for the [treeview zebra/even-odd row styling](https://user-images.githubusercontent.com/31816829/81144172-ceb1ef00-8f73-11ea-93d4-c64043350fe2.png), the possibility to use one color for even row and another for odd row from CSS, was removed. But for some people like me, it's useful.

About the proposed snippet, I tried new things. Since GTK 3.24 we can use GtkEventController, but the first scroll event is ignored (example links: [link1](https://github.com/luigifab/awf-extended/blob/a8489cda0196e473da4960e1a5d68ef783015003/src/awf.c#L1560) and [link2](https://github.com/luigifab/awf-extended/blob/a8489cda0196e473da4960e1a5d68ef783015003/src/awf.c#L1648) and [link3](https://github.com/luigifab/awf-extended/blob/a8489cda0196e473da4960e1a5d68ef783015003/src/awf.c#L2160), that's also true, I'm a noob in C language).

**Comment by mmm4m5m** [comment]
FYI, mouse wheel works fine with tabs in xfce-terminal.

**Comment by luigifab** [comment]
This is partially fixed with [gtk3-classic](https://github.com/lah7/gtk3-classic).

**Comment by luigifab** [comment]
Now fixed (I don't know why, but it's not very important), with [gtk3-classic](https://github.com/lah7/gtk3-classic) + geany v2.0.
