### ISSUE TITLE
Raku Syntax Highlighting

### ISSUE THREAD

**Issue by hankache** [geany/geany#2456]
Scintilla 4.30 onward ships with a Raku lexer: https://sourceforge.net/p/scintilla/feature-requests/1328/

Would it be possible to add Raku support in Geany?

**Comment by elextr** [comment]
Geany currently uses Scintilla 3 so as to not require C++17, so until it is decided that  C++17 is widely enough available and somebody provides a PR that upgrades to Scintilla 4 its unlikley unless the Raku support is backported to Scintilla 3.

**Comment by codebrainz** [comment]
https://sourceforge.net/p/scintilla/code/ci/LongTerm3/tree/lexers/LexRaku.cxx
https://github.com/universal-ctags/ctags/blob/master/parsers/perl6.c

**Comment by hankache** [comment]
Hi @elextr,
As pointed out by @codebrainz the Raku lexer was backported and is available on the LongTerm3 branch of Scintilla

**Comment by elextr** [comment]
Ok, so somebody just needs to provide  PR making the filetype that provides all the coding into Geany, see `HACKING` file.
