### ISSUE TITLE
bad variable identification for FreeBasic

### ISSUE THREAD

**Issue by BrennusJ** [geany/geany#2461]
version :+1: OS :
geany 1.32 (construit le 2018-08-01 avec GTK 3.22.26, GLib 2.54.1)

Linux jerome-H310M-S2H-2-0 5.3.0-26-generic #28~18.04.1-Ubuntu SMP Wed Dec 18 16:40:14 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

please see screen capture
the line 
dim filenamecsv as 
![Capture d’écran_2020-03-22_19-18-10](https://user-images.githubusercontent.com/3634605/77257097-700a0d80-6c72-11ea-8918-684ea2568693.png)
string="Export_GIR_FULL_"+mid(date,7)+"_"+mid(date,1,2)+"_"+mid(date,4,2)+".csv"

**Comment by codebrainz** [comment]
Looks like it's probably a bug in [the parser](https://github.com/universal-ctags/ctags/blob/30cd8e034f34b218e9715ad8d406c37dfe8dbcee/parsers/basic.c), if you care to have a crack at fixing it.

Not a solution, but as a work-around you could probably use a line continuation (`_`) after the first string literal (before `mid()` call) to trick it into being parsed correctly.
