### ISSUE TITLE
cannot save changes in geany.conf 

### ISSUE THREAD

**Issue by waynelapierre** [geany/geany#2462]
I changed send_selection_unsafe=false to send_selection_unsafe=true in the geany.conf file, but this geany.conf file kept undoing my change even after I successfully saved the change. 

I am running the most updated geany on Fedora 31.

**Comment by elextr** [comment]
Were all versions of Geany closed when you made the change?  Also why not make the change in the GUI?

**Comment by codebrainz** [comment]
From [the Manual](https://www.geany.org/manual/current/index.html):

> The user preferences file geany.conf holds settings for all the items configured in the preferences dialog. This file should not be edited while Geany is running as the file will be overwritten when the preferences in Geany are changed or Geany is quit.

In this particular case you can just set the preference from the GUI under Preferences->Various.

If you really really want to edit the config file without using another editor, run Geany with a separate/temporary configuration directory (ex. `geany -c /tmp/deleteme`) and use that to edit the original config file from the main configuration directory.

**Comment by waynelapierre** [comment]
thanks!
