### ISSUE TITLE
Editor and Terminal in different windows

### ISSUE THREAD

**Issue by waynelapierre** [geany/geany#2464]
I am using two monitors for my desktop. I would like to know how to make geany show editor and terminal in two windows so I can use my two monitors.

**Comment by elextr** [comment]
Sorry, Geany is a single window application.  If you didn't want terminal and editor connected you could run two instances of Geany but beware of them sharing a config where they will overwrite each other, you can start with different configs using -c.

**Comment by waynelapierre** [comment]
I noticed that geany has a plugin called split window, is it useful in this case?

**Comment by elextr** [comment]
It does what it says on the tin, it splits the single window to show two editors in it (well one editor and one very limited, basically just treat it as display only)

**Comment by elextr** [comment]
To be clear, it splits inside the window, not splits the window into two separate ones.
