### ISSUE TITLE
build error on ubuntu 18.04

### ISSUE THREAD

**Issue by muralikodali** [geany/geany#2465]
building from source code failed with the following error on ubuntu mate 18.04.03

./configure: line 17692: syntax error near unexpected token `$gtk2_package'
./configure: line 17692: `PKG_CHECK_EXISTS($gtk2_package >= $gtk2_min_version, have_gtk2=yes, have_gtk2=no)'

**Comment by elextr** [comment]
Where did you get that configure from?  The one in the source package on the geany download site does not contain that line.

**Comment by muralikodali** [comment]
I have downloaded the source code file from https://download.geany.org/geany-1.36.tar.gz.
please check the log file for detailed information.

[build.log](https://github.com/geany/geany/files/4408938/build.log)

**Comment by elextr** [comment]
So the error occurs when running autogen.sh, not the configure that is provided by the project.  What happens when you run that?  

Autogen.sh is only meant to be run on git downloads to create configure.  Works for me with a git clone on Linux mint which is based on Ubuntu 18.04.

**Comment by muralikodali** [comment]
I have cloned the git repository and run autogen.sh

I have attached the log file showing build errors.

[build_git.log](https://github.com/geany/geany/files/4409210/build_git.log)

**Comment by elextr** [comment]
See the message after the libtoolize ones, google says this is because you don't have the gettext devel installed.

**Comment by muralikodali** [comment]
there is no package like gettext devel in ubuntu. I have compiled and installed gettext version 0.20 from gnu. yet running autogen.sh failed with same error.

**Comment by codebrainz** [comment]
You probably haven't installed the dependencies needed to build. In this case it's probably `libglib2.0-dev` which contains the GLib gettextize macros that appear to be missing, I believe.

Even easier though, just run `sudo apt-get build-dep geany` which should install all the packages and development files required to build Geany from source.

**Comment by muralikodali** [comment]
libglib2.0-dev is already installed and running sudo apt-get build-dep geany giving error:

sudo apt-get build-dep geany                                                                                                                                           
Reading package lists... Done
E: Unable to find a source package for geany

**Comment by elextr** [comment]
`apt-get build-deps` needs access to the source package as the error message notes.  Enable the source packages should fix it.

**Comment by muralikodali** [comment]
enabled source code in software sources. running autogen.sh gave error.

checking for Git revision... f1de94bb
./configure: line 17692: syntax error near unexpected token `$gtk2_package'
./configure: line 17692: `PKG_CHECK_EXISTS($gtk2_package >= $gtk2_min_version, have_gtk2=yes, have_gtk2=no)'

**Comment by elextr** [comment]
did you successfully install geany build-deps?

**Comment by muralikodali** [comment]
yes. installed a package after running sudo apt-get build-dep geany.
Running again the same command gives no errors.

**Comment by elextr** [comment]
do you have pkg-config installed?

**Comment by muralikodali** [comment]
pkg-config is already isntalled with version 0.29.1

**Comment by elextr** [comment]
Dunno then, like I said it works for me on Linux Mint which is Ubuntu 18.04 based, Autofools experts needed.

**Comment by codebrainz** [comment]
You could delete the file `configure` in the root source directory and re-run `autogen.sh` to regenerate it, maybe it got messed up due to the previously missing Autoconf/M4 dependencies.

**Comment by muralikodali** [comment]
I have deleted configure file and re-run autogen.sh.
I have again got the same errors.

**Comment by muralikodali** [comment]
I have compiled geany successfully along with geany plugins. Actual problem is from my side due to compilation errors from autotools. After reinstalling autotools compilation went without errors.
