### ISSUE TITLE
How to configure 'Editor tabs (on the left)' view?

### ISSUE THREAD

**Issue by j1warren** [geany/geany#2468]
![screenshot](https://i.ibb.co/t2qJCPQ/geany.png)

I've got tabs on the left, how can I narrow the height between them?

**Comment by elextr** [comment]
Don't understand the question or the image which shows no tabs?

**Comment by j1warren** [comment]
This list on the left is the opened files tabs.
Usually it's on top, I've set it to the left (Preferences - Interface - Notebook tabs - Editor: Left).

**Comment by elextr** [comment]
Ahh, the tab width is set by GTK, AFAIK it does not provide a way of controlling it.

**Comment by codebrainz** [comment]
What is the white square? Is that to hide some filenames, and/or are those upper tabs under the box really tall?

**Comment by codebrainz** [comment]
It will affect all GtkNotebook widgets, but something like this works (tweak to taste):

```css
notebook > header.top > tabs > tab {
	padding: 0px 12px 0px 12px;
}
```
Simplest way to use is to use `Tools->Configuration Files->geany.css` and paste that at the end and save it.

**Comment by j1warren** [comment]
@codebrainz 
White square was to hide some filenames.

.css works, thank you!
