### ISSUE TITLE
How to change the cursor to an Underscore

### ISSUE THREAD

**Issue by 1CH1GO** [geany/geany#2478]
Hello I am a heavy geany user and I want to make my cursor to an underscore but I did not find any useful resources on the web. Is it possible to change?

**Comment by elextr** [comment]
No, underscore indicates overstrike.

Presumably you mean the caret (the cursor is the thing the mouse moves around).

In insert mode the caret can be a vertical line or a block and in overstrike mode it can be an underscore or a block.

**Comment by 1CH1GO** [comment]
I am sorry for such a dumb question.

**Comment by codebrainz** [comment]
You can set it using colour schemes, there is a `cursor` style which the 3rd argument says if it's a block cursor or an underscore/underline cursor.

**Comment by elextr** [comment]
```
# set the third argument to true to change the caret into a block caret
```

That changes it between a vertical line and a __block__, not an underscore.

**Comment by codebrainz** [comment]
Oh, maybe I'm thinking of GtkSourceView or something, maybe Scintilla can't do it.
