### ISSUE TITLE
find-feature fail to find word

### ISSUE THREAD

**Issue by arnon81** [geany/geany#2479]
19-apr-2020 7:55 pm edt:
(1)copy-paste content of http://wortel.ucoz.com/test4.htm to new-file in geany-1.27
(2)find 'whit' fail but find 'whi' succeed

**Comment by elextr** [comment]
The file contains invalid characters, one exists between the `i` and `t` so the search results are correct.

**Comment by arnon81** [comment]
19 apr 2020 8:16 pm edt:
how can i see those invalid-character in geany ?
how can i delete those invalid-character in geany ?
thanks.
