### ISSUE TITLE
Pascal GEANY doesn't display anything

### ISSUE THREAD

**Issue by jpaulo1010** [geany/geany#2480]
Hello everyone, i'm new in this forum, i'm using ubuntu 18.04 with theme deepin.
When i compile and execute a simple program in pascal language, geany doesn't display anything in terminal window. can someone help me?
![DeepinScreenshot_20200420195205](https://user-images.githubusercontent.com/46799725/79807172-858d5880-8340-11ea-9c72-fedfeef83ba7.png
![terminal](https://user-images.githubusercontent.com/46799725/79807226-af467f80-8340-11ea-9c2b-75e8a5faed76.png)
)

**Comment by codebrainz** [comment]
Does it work from the terminal/command line if you run:

```bash
/usr/bin/fpc "/path/to/novo.pas"
```

I don't know Pascal at all, but you could try making sure the output buffer is flushed, adding something like `Flush(Output)` in between line 5 and 6, not sure if it will help or if that's the right syntax even.

You can also check `Help->Debug Messages` to see if it shows any errors or anything, at the very least it will tell us what version of Geany and GTK/GLib you're using.

**Comment by jpaulo1010** [comment]
I'm using the version below:
Geany 1.32
GTK 3.22.30, GLib 2.56.4

**Comment by jpaulo1010** [comment]
Guys, i solved the problem, i went in preferences>tools and change the path of terminal.
