### ISSUE TITLE
How to add custom snippets?

### ISSUE THREAD

**Issue by gpk2000** [geany/geany#2481]
Hi I am a competitive programmer and I like to reuse parts of the code but I find adding snippets in snippets.conf to be a bit tedious. Does a simple way exist?

**Comment by elextr** [comment]
That _is_ the simple way :grin:

**Comment by 1CH1GO** [comment]
:cry:

**Comment by mega-bots** [comment]
For some one looking for the solution just copy your code and paste in the python code format mentioned by @gpk2000 
and paste the output under the section of the language in the conf file which is at /usr/share/geany/snippets.conf.
like this may be 
hi=the op you got from the python

now when you use the word hi in geany type hi and then press tab to autocomplete the snippet
