### ISSUE TITLE
Open file in geany in current desktop?

### ISSUE THREAD

**Issue by ElizBaldwin** [geany/geany#2489]
New report to re-open issue  #1025 as the latest version of geany, or its interaction with gnome, breaks the existing workaround.

Issue: new invocations of geany open tabs in the original geany window, which may not be in the current desktop.  This is very annoying if one works on different projects in different desktops.  Preferred behaviour: open a new instance if there is not one in the current desktop, otherwise open an additional tab.  (Gedit behaves in this way).  

geany -i does not fix the problem as it always opens a new window.

@nazar-pc offered a workaround on issue #1025 which worked on that version, but it no longer works if you run:
Fedora 31
Gnome 3.34.5
geany 1.36

**Comment by codebrainz** [comment]
No need for a new issue, we can just reopen #1025.
