### ISSUE TITLE
create new file issue

### ISSUE THREAD

**Issue by waynelapierre** [geany/geany#2490]
I am using the most updated geany on Fedora 32. When I create a new file by pressing Ctrl + N, a new file was created with very strange name like gis_CPUOJ0.

Also, this newly created file was automatically saved in my tmp folder. 

I do not have the issue before I upgraded from Fedora 31 to Fedora 32.

**Comment by elextr** [comment]
You have the Save Actions plugin enabled with instant save turned on.
