### ISSUE TITLE
terminal command not found

### ISSUE THREAD

**Issue by waynelapierre** [geany/geany#2491]
I am using Geany 1.36-2 on Fedora 32. In the terminal of Geany, each line starts with [📦 org.geany.Geany CurrentFileName]$. This seems different from 1.36-1, and I am not sure if this is normal. 

When I execute a command in the Geany terminal, a command like ls works well. However, when I execute the name of software like python, R, and Julia, an error message showed up saying:  

`sh: python: command not found 
`
When I use my system terminal instead of the Geany terminal, I do not have this issue.

**Comment by elextr** [comment]
>  each line starts with [package org.geany.Geany CurrentFileName]$.

This is printed by your shell, where it gets it is unknown.

> When I execute a command in the Geany terminal, a command like ls works well. However, when I execute the name of software like python, R, and Julia, an error message showed up saying:

> sh: python: command not found
> When I use my system terminal instead of the Geany terminal, I do not have this issue.

Are you starting Geany from the terminal.  If not whatever starts Geany may not be starting it in a shell and so not getting the `PATH`.  Try starting Geany from a terminal and and see if it works.

**Comment by waynelapierre** [comment]
I reinstalled Geany and this issue is gone
