### ISSUE TITLE
message window customization

### ISSUE THREAD

**Issue by waynelapierre** [geany/geany#2492]
I want to remove the status, complier, messages, scribble, and terminal tabs of Geany message window. Basically, I prefer that when I open the message window Geany automatically opens the terminal window without showing the tabs. How could I get this setup?

**Comment by elextr** [comment]
AFAIK thats not configurable, its either the whole message window or none.

**Comment by codebrainz** [comment]
For disabling the other tabs, you can edit these settings under `Edit->Preferences->Various`:

```diff
--- msgwin1/geany.conf	2020-04-30 23:43:49.877942591 -0700
+++ msgwin2/geany.conf	2020-04-30 23:45:33.495469083 -0700
@@ -45,10 +45,10 @@
 compiler_tab_autoscroll=true
 statusbar_template=line: %l / %L	 col: %c	 sel: %s	 %w      %t      %mmode: %M      encoding: %e      filetype: %f      scope: %S
 new_document_after_close=false
-msgwin_status_visible=true
-msgwin_compiler_visible=true
-msgwin_messages_visible=true
-msgwin_scribble_visible=true
+msgwin_status_visible=false
+msgwin_compiler_visible=false
+msgwin_messages_visible=false
+msgwin_scribble_visible=false
 documents_show_paths=true
 sidebar_page=0
 pref_main_load_session=true
```

For hiding the message window tabs altogether (ie. to hide the lone tab for "Terminal") you could either patch Geany to add an option, make a plugin to do it, or you could use CSS to somewhat okay effect - it would be a lot easier if #2469 gets merged - probably something like:

```css
#notebook_info tab {
  padding: 0px;
  font-size: 0.1em;
  border-width: 0px;
}
```

I don't think GTK+ CSS has a thing like `display: none;` or changing the size like real CSS, but above makes the tabs pretty small here. Someone with more GTK+ theming skills could probably find a better way.

I doubt anyone would oppose a pull request to add a preference to hide message window tabs entirely.

**Comment by waynelapierre** [comment]
Hiding message window tabs is very useful when setting the message window on the right side of Geany. The tabs take a lot of space which could be saved for the editor and terminal parts.

**Comment by codebrainz** [comment]
Sounds reasonable if someone wants to contribute the change. IMO, it would also make sense for the sidebar tabs. Maybe someone could change the combo boxes in `Prefs->Interface->Notebook Tabs->Tab Positions` to each contain a "None" item that hides the tabs (and then remove the "Show editor tabs checkbox").

**Comment by mjkloeckner** [comment]
With these settings I managed to hide all the tabs.

First I set the position of the tabs to the right in `Preferences > Interface > Notebook tabs > Tab Position > Message Window`

Then I added a negative margin as follows:

```css
#notebook_info {
  padding: 1px;
  padding-left: 5px;
  margin-right: -56px;
  font-size: 0.1em;
}
```

The left padding is not necessary but it looks better to me, here is a pic:

![Screenshot_2024-08-24_16-38-10](https://github.com/user-attachments/assets/4a293995-b870-4444-9fb9-904cbe555225)
