### ISSUE TITLE
Wish: S expression highlighter

### ISSUE THREAD

**Issue by ferdymercury** [geany/geany#2493]
I have a text file written in s-expression, pasted below

```
(module VIA-091X03-VE (layer F.Cu) (tedit 5EAC6216)
  (fp_text reference REF** (at 0 0) (layer F.SilkS) hide
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_text value VIA-091X03-VE (at 0 2) (layer F.Fab) hide
    (effects (font (size 1 1) (thickness 0.15)))
  )
  (fp_line (start -0.85344 -0.85344) (end -0.85344 0.85344) (layer F.CrtYd) (width 0.05))
  (fp_line (start -0.85344 0.85344) (end 0.85344 0.85344) (layer F.CrtYd) (width 0.05))
  (fp_line (start 0.85344 0.85344) (end 0.85344 -0.85344) (layer F.CrtYd) (width 0.05))
  (fp_line (start 0.85344 -0.85344) (end -0.85344 -0.85344) (layer F.CrtYd) (width 0.05))
  (pad "" thru_hole circle (at 0 0) (size 0.9144 0.9144) (drill 0.3048) (layers *.Cu *.Mask)
    (solder_mask_margin 0.1016)
    (zone_connect 2))
)
```

If I open it with geany and set the document file type to LISP, the highlighting is a bit inconsistent, especially for negative numbers:
![image](https://user-images.githubusercontent.com/10653970/80870462-95783700-8c74-11ea-8662-42ee3c8abeb3.png)

Is there a better highlighter for this type of document that I am not finding in the list?

Related:
https://sexpdata.readthedocs.io/en/latest/

**Comment by codebrainz** [comment]
I think Clojure allows writing negative numbers like that, but unfortunately it also uses the same Lisp syntax highlighter. Have you tried just using Python filetype? The example above looks OK here with Python.

**Comment by ferdymercury** [comment]
Python filetype does a pretty good job. thanks for the hint.
