### ISSUE TITLE
Appearance tiresome (verion 1.33)

### ISSUE THREAD

**Issue by zounp** [geany/geany#2496]
Thanks for Geany.
I use Geany 1.29 with pleasure. After upgrading my Linux distribution Geany is upgraded to version 1.33. The appearance has changed. Now working with Geany has become tiresome. The text in the not active tabs is light gray on a bit lighter gray and also the theme, syntax highligting, has changed to something more fatiguing colors. Maybe this works for young people with good eyes. If ones eyes are a bit less than that it is not nice, tiresome and timecosuming.
I would like to have a Geany with the look and feel of version 1.29 back or an easy the option to switch back to it.
Thanks.

**Comment by elextr** [comment]
The appearance of everything except the editor window is controlled by the desktop theme, so blame your distro for using a, erm, "tiresome" theme.

**Comment by zounp** [comment]
Thanks for the insult. "Very motivating to file anything here".

I did some deeper investigation. You are right. See the picture. The top is from Debian 10 Buster, the bottom from 9 Stretch. (Sorry no picture, got "Something went really wrong, and we can’t process that file Try again". <rant>Why not some information on what went wrong, in stead of letting me trial en 
error which I am not willing to do? Hmm, I did and solved it, so there is a picture :-)</rant> )

They changed the themes :-(
I could not find an alternative theme which looked like it was, I liked.
<rant> Why can't things that are good not be left alone?</rant>
<rant>Why has text to be made less readable by making it gray on an often a bit lighter gray background? Often it is not about looking nice but about usability.</rant>
<rant>Often new features are in favor of a better intuitive use</rant>

I tried to make my own theme some time ago. It was not easy. Do you have any tips how to do it?
![ThemeCompareStretchBuster](https://user-images.githubusercontent.com/19635343/81585806-2e5d2f80-93a4-11ea-955c-c91dc723da8d.png)

**Comment by elextr** [comment]
> Thanks for the insult. "Very motivating to file anything here".

Not sure what you are referring to.  If its "tiresome" I was just repeating the word you used in the issue title, hence the quotes.

> Why not some information on what went wrong,

You would have to suggest it to Github, complaining to Geany devs might feel good, but it doesn't get you anywhere I'm afraid.

> They changed the themes :-(

Yes distros do that.

> Do you have any tips how to do it?

Well, somebody watching the repo might, but this is the issues for Geany, so it would be better if any such conversation took place on the mailing list.

**Comment by zounp** [comment]
> > Thanks for the insult. "Very motivating to file anything here".
> Not sure what you are referring to. If its "tiresome" I was just repeating the word 
> you used in the issue title, hence the quotes.

It is not the "tiresome" on its own it is the  " erm, "tiresome" " what makes me feel not taken serious, makes it an insult and demotivating for me.
 
> > Why not some information on what went wrong,
> You would have to suggest it to Github, complaining to Geany devs might feel good, but
>  it doesn't get you anywhere I'm afraid.

I do not understand, what I have to suggest to Github?
Yes, if I think it is a Geany issue I complain at Geany otherwise it would be useles 

Thanks to you I know that it is a xfce4 and / or gtk issue. So case closed here :-)
Thanks for the feedback.

**Comment by elextr** [comment]
>  " erm, "tiresome" "

Ahh, well, the use of the phrase is not an insult to _you_, it is indicating a pause for thought about how to describe the theme, following which I used your word "tiresome" as an unusual description, but more polite than how I usually describe many modern distro themes :)

> I do not understand, what I have to suggest to Github?
> Yes, if I think it is a Geany issue I complain at Geany otherwise it would be useles

I was referring to your long parenthetical comment that included ` "Something went really wrong, and we can’t process that file Try again". Why not some information on what went wrong` which IIUC is an issue with you uploading to github, so a github issue, not a Geany issue.

**Comment by zounp** [comment]
Thanks for your explanations and for your work on Geany.
All clear :-)
