### ISSUE TITLE
Symbols Shell Script Functions name parsing

### ISSUE THREAD

**Issue by moocan** [geany/geany#2500]
Hello,

I'm writing some shell scripts and many functions and all my functions are named using `.`, `:`, `::` as `Systemd:Unit::Is.Active()` or `EOI.Task::Cleanup()` `EOI.Task::Cleanup.TempDir()` `File::Get.Owner()` ...

Only the first part of name is listed ... `EOI` `Systemd` `File` many times in `Symbols` tabs under `Functions`.

I know it's not a conventional naming convention but suggested and working.

Is it possible to modify the parsing method somewhere in config files or is it hardcoded ?

Thank you.
Kind Regards

**Comment by elextr** [comment]
Which shell are you using?  

Bash defines:

```
name
A word consisting solely of letters, numbers, and underscores, and beginning with a letter or underscore. Names are used as shell variable and function names. Also referred to as an identifier.
```

so `.` `::` etc are not valid within shell names.

**Comment by moocan** [comment]
Hello,

I'm using bash. I have tested with zsh and it is working too.
I know but it seems to be used and allowed.
I found many years ago things like these ones:
[bash-script-function-names-containing-double-colon](https://unix.stackexchange.com/questions/463560/bash-script-function-names-containing-double-colon)
[what-are-double-colons-in-a-shell-script](https://stackoverflow.com/questions/44558080/what-are-double-colons-in-a-shell-script)
[bash-script-function-names-containing](http://oukyi.blogspot.com/2018/08/bash-script-function-names-containing.html)

Is it possible to modify the parsing method somewhere in config files or is it hardcoded ?

Kind Regards

**Comment by elextr** [comment]
Its hard coded AFAIK.  It follows the Bash and POSIX specification.

And its silly recommending something thats explicitly not allowed by the tools documentation just because it happens to work today, bash could change that at any time.

**Comment by moocan** [comment]
Hello,

Thanks you for your advices.
I understand.

Thank you
Kind Regards

**Comment by codebrainz** [comment]
FTR: https://github.com/universal-ctags/ctags/blob/d28e10d13bcde641631fa72f6e9fe2632e0bfaec/parsers/sh.c
