### ISSUE TITLE
geany / ubuntu crash windows manager on search in document

### ISSUE THREAD

**Issue by yarglah** [geany/geany#2501]
This bug occurs systematically on my system from since a week, even after restarting system.

When I try to search a string in a document, geany crash and also all other running application  applications (Firefox, Virtualbox and VMs, Visual Studio Code) but Terminal(s) survive...

Configuration:
Geany 1.35 ( build May 13 2019)
uname -a: Linux myhost 5.3.0-51-generic #44-Ubuntu SMP Wed Apr 22 21:09:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
-> Ubuntu 19.10, up to date. with GNOME 3.34.2

**Comment by yarglah** [comment]
More info:
Ubuntu 19.10,  up to date.
GNOME: 3.34.2

**Comment by codebrainz** [comment]
> Let me know for more informatios or tests.

If you can reproduce it, it would be useful to see the debug messages in `Help->Debug Messages` and if possible to provide [a backtrace](https://www.geany.org/support/bugs/#other-useful-information).

**Comment by frlan** [comment]
If there is more crashing than Geany (I understood the posting like that)· it's most likely not an Geany-issue. I'd recommend to run a memory test and report this issue to Ubuntu.

**Comment by yarglah** [comment]
> If you can reproduce it, it would be useful to see the debug messages in `Help->Debug Messages` and if possible to provide [a backtrace](https://www.geany.org/support/bugs/#other-useful-information).

Issue occured only when there is no or no more occurence or string 

Here is a gdb trace:
(gdb) run -v
Starting program: /usr/bin/geany -v
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff4f05700 (LWP 10867)]
[New Thread 0x7fffeffff700 (LWP 10868)]
(geany:10863): GLib-GIO-DEBUG: 08:49:44.358: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
Geany-INFO: 08:49:44.436: Geany 1.35, fr_FR.UTF-8
Geany-INFO: 08:49:44.436: GTK 3.24.12, GLib 2.62.4
Geany-INFO: 08:49:44.436: System data dir: /usr/share/geany
Geany-INFO: 08:49:44.436: User config dir: /home/thierry/.config/geany
[New Thread 0x7fffef7fe700 (LWP 10869)]
[New Thread 0x7fffeeffd700 (LWP 10870)]
Geany-INFO: 08:49:44.549: Loaded GTK+ CSS theme '/usr/share/geany/geany.css'
Geany-INFO: 08:49:44.550: Loaded GTK+ CSS theme '/usr/share/geany/geany-3.20.css'
Geany-INFO: 08:49:44.554: System plugin path: /usr/lib/x86_64-linux-gnu/geany
Geany-INFO: 08:49:44.566: Added filetype Arduino (61).
Geany-INFO: 08:49:44.566: Added filetype Scala (62).
Geany-INFO: 08:49:44.566: Added filetype Clojure (63).
Geany-INFO: 08:49:44.566: Added filetype Genie (64).
Geany-INFO: 08:49:44.566: Added filetype Cython (65).
Geany-INFO: 08:49:44.566: Added filetype JSON (66).
Geany-INFO: 08:49:44.566: Added filetype Graphviz (67).
Geany-INFO: 08:49:44.566: Added filetype CUDA (68).
Geany-INFO: 08:49:44.618: Loaded libvte from libvte-2.91.so.0
---> [SKIP openning my files open in previous session 
[New Thread 0x7fffdb98a700 (LWP 10872)]
[Detaching after fork from child process 10873]
[Thread 0x7fffeeffd700 (LWP 10870) exited]
**(geany:10863): IBUS-DEBUG: 08:49:53.993: _connection_closed_cb: Underlying GIOStream** returned 0 bytes on an async read
[Thread 0x7fffef7fe700 (LWP 10869) exited]

Bold message is displayed when bug occured.

**Comment by elextr** [comment]
Umm, a backtrace is typing "bt" when the gdb prompt returns after the crash (as specified in that link), and note it often needs you to press return one or more times to show the whole backtrace.

**Comment by yarglah** [comment]
> Umm, a backtrace is typing "bt" when the gdb prompt returns after the crash (as specified in that link), and note it often needs you to press return one or more times to show the whole backtrace.

geany does not crash after the issue when launched by gdb so I can't run bt.

**Comment by yarglah** [comment]
Problem disappears after ubuntu upgrade to 20.04 (LTS) (Geany 1.36).
