### ISSUE TITLE
Date format no longer respected in Ubuntu 20

### ISSUE THREAD

**Issue by dandv** [geany/geany#2505]
I've installed Ubuntu 20 and the current version of Geany. When I press Shift+Alt+D, the date is always in the `DD.MM.YYYY` format.

This doesn't match my regional settings (English/Canada, trying to get the system to output YYYY-MM-DD), or the setting in Geany:

![image](https://user-images.githubusercontent.com/33569/81997322-4337fe00-9604-11ea-963b-935145d41929.png)

**Comment by elextr** [comment]
The manual says about the date setting shown above:

```
Date
Specify a format for the {date} wildcard. 
```

in templates, not for insert date.  

See `Menu->Edit->Insert Date`.

**Comment by dandv** [comment]
Thanks @elextr, I've set the format via Edit -> Insert date -> Set custom date format.

A bit confused about what "Templates" meant in that dialog, and who uses software manuals noawadays for text editors? :)
