### ISSUE TITLE
Ruby invalid html.erb syntax highlighting

### ISSUE THREAD

**Issue by luigifab** [geany/geany#2507]
I using [geany-on-rails filetype](https://github.com/dejw/geany-on-rails/blob/master/geany/filedefs/filetypes.ruby) (without [styling], I also updated the filetype_extensions.conf) with Geany 1.36 on Debian Testing, but the highlighting does not work with **.html.erb** files.

Perhaps one configuration line is missing somewhere? (I say that because there is no problem with .html.php and .php files)

example.html.erb: **ko**
![ko](https://user-images.githubusercontent.com/31816829/82205739-4e8e7080-9907-11ea-8ae3-6057f80f47ad.png)

example.rb: ok
![rb](https://user-images.githubusercontent.com/31816829/82205759-564e1500-9907-11ea-9fa6-ed3bad1d86cb.png)

**Comment by codebrainz** [comment]
The [Ruby lexer](https://github.com/geany/geany/blob/ea649d8024b14ce55a922e146078ad1bc15533df/scintilla/lexers/LexRuby.cxx) that Geany uses from [the Scintilla project](https://www.scintilla.org/) for highlighting doesn't support embedding Ruby in HTML or vice versa.

If anyone wants to contribute this enhancement to Scintilla, we could update Geany's Ruby (or HTML) filetype to support it once it's merged upstream.
