### ISSUE TITLE
Can we improve the ease of use for plugins?

### ISSUE THREAD

**Issue by dandv** [geany/geany#2508]
I've been using Geany for years and today I recommended it to a friend. He installed it on Ubuntu then asked,

> *Friend:* How do I get spell checking? 
> *Me:* oh, that's a separate plugin, just install it.
> *Friend:* ...how?

Turns out I didn't remember how I installed the plugin. My friend sent me a screenshot of the Plugin manager:

![image](https://user-images.githubusercontent.com/33569/82522006-00cb6100-9add-11ea-8256-f29aa1e54896.png)

No option to search for plugins in a repository.

So I googled "Geany spell check" and pointed him to https://plugins.geany.org/spellcheck.html

But that page doesn't even say how to download or install the plugin:

> Usage
> After installed [sic] successfully

[how?]

Turns out other plugins also assumes the user already knows how to install them: [Markdown](https://plugins.geany.org/markdown.html), [Codenav](https://plugins.geany.org/codenav.html) etc.

I know plugins are 3rd party, but there must be something Geany itself can do. For example, Codenav uses the same English mistake "After installed successfully", which suggests these plugin About pages are cloned from somewhere. A first, simple step, would be to add install instructions to that plugin documentation template.

1. Spell checking is such a common plugin. Can it ship by default, like the plugins in the screenshot above?
2. In general, how can we make it easier to install plugins?

**Comment by elextr** [comment]
Yeah, documentation seems not to be a strong suit with plugin makers, although to be fair quite a number do not have English as a first language.  So copying is a reasonable approach.

On installation, I suspect most plugins in the Geany-plugins collection assume you have installed the whole collection, probably from your distro package.  Certainly it doesn't make sense for each plugin to have install instructions for each distro, and instructions for the collection are only as good as the distro users contributions make them (hint hint :).
