### ISSUE TITLE
Side bar is cut off

### ISSUE THREAD

**Issue by torben656** [geany/geany#2510]
![image](https://user-images.githubusercontent.com/36535433/82659395-36965400-9c5b-11ea-83fc-fa90f2e7762e.png)

This might be a little nuisance, but its still an issue. Dragging the window doesn't work. Using geany 1.36 on Arch Linux LXQT/Openbox

**Comment by elextr** [comment]
This is simply what the GTK toolkit does if the pane is too small to fit its contents, if it won't fit it won't fit, GTK has to do something, so it cuts it off.

If you make the pane wider it won't be cut off.  There is a drag handle between the sidebar and the editor, but whatever theme your disto is using seems to make it invisible :( but possibly the cursor changes when its over it.

**Comment by torben656** [comment]
Oh you're right moving the sidebar makes it visible, thanks!

**Comment by codebrainz** [comment]
Duplicate of #2436
