### ISSUE TITLE
Feature-request: Message-window display toggle hotkey

### ISSUE THREAD

**Issue by kberns** [geany/geany#2511]
I managed to add a hotkey for the sidebar, and it's very nice being able to quickly toggle that one. Would be really nice to have the message-window the same. That way i would get to focus on the text file itself.

Thank you for the great IDE!

**Comment by elextr** [comment]
You can set your own hotkey in preferences keybinding tab toggle message window, its right above toggle sidebar.

**Comment by kberns** [comment]
Ahh. Cool. Ty
