### ISSUE TITLE
Straight white line in geany editor under dark mode

### ISSUE THREAD

**Issue by fightthepower** [geany/geany#2514]
I am using Ubuntu and the latest 1.36 geany. My system is in dark mode and uses a dark theme in geany editor. In my geany editor there is a straight white line on the right side of the screen. It only appears in geany editor and if I change the size of the editor the line also changes. Functionally geany is working fine but that white line is irritating.

![alt text](https://i.ibb.co/Pg4PVXR/1.png)

**Comment by eht16** [comment]
This is actually a feature:
https://www.geany.org/manual/index.html#long-line-marker

You can easily disable it in the preferences dialog -> Editor -> Display.
