### ISSUE TITLE
A custom filetype is ignored

### ISSUE THREAD

**Issue by Kzer-Za** [geany/geany#2515]
I have copied syntax for C (filetypes.c) to filetypes.zsc.conf. However, when I open a file with zsc suffix, there is no syntax highlighting. I know that their (C and ZScript) syntax is close enough, and when I select the filetype manually through the menu, the highlighting is working. I have also tried copying the cyntax from CPP file, and it doesn't work either. Also I know that when I created a custom filetype for SCSS files, everything went without a hitch, and files with scss suffix are recognized and the syntax is highlighted. But for .zsc it is not working for some reason. 

Geany version is 1.36.

**Comment by eht16** [comment]
Did you update the `filetype_extensions.conf`?
https://www.geany.org/manual/index.html#filetype-extensions

**Comment by Kzer-Za** [comment]
Oops! From the time when I registered the highlighting for SCSS I remembered only that I needed to copy the syntax file. Sorry about the false alarm.
