### ISSUE TITLE
Compiler output is difficult to read with Ubuntu dark theme

### ISSUE THREAD

**Issue by MarkuBu** [geany/geany#2520]
Hi,
I'm using Ubuntu 20.04 with the dark theme, but the compiler output is difficult to read. 

![geany](https://user-images.githubusercontent.com/16163058/83320573-385aab80-a249-11ea-915e-eb214c0ab49a.png)

Can I fix that?

**Comment by elextr** [comment]
https://www.geany.org/manual/current/index.html#customizing-geany-s-appearance-using-gtk-3-css
