### ISSUE TITLE
Confusing translation of replace dialog buttons

### ISSUE THREAD

**Issue by Korodny** [geany/geany#2524]
Just [came up](https://debianforum.de/forum/viewtopic.php?f=28&t=177734) in a German forum, where a user described the replace dialog as "cryptic":

The last three buttons in the German replace dialog are labeled "Search", "Replace" and "Replace and Find" ("Suchen", "Ersetzen", "Ersetzen und Finden"). Using a different term to describe the very same action - i.e. "search for next match" - makes an already complicated dialog even less intuitive.

I assume the "Find" instead of "Search" description in the last button was used because all of the letters in "Ersetzen und Suchen" are already used as shortcuts for other gadgets.

IMHO, a better approach would have been to change one of the shortcuts  of the other gadgets, so "Ersetzen und Suchen" could have been used.

**Comment by elextr** [comment]
The English is "Find" "Replace" "Replace & Find" so its the translation thats inconsistent.

**Comment by Korodny** [comment]
Sure, that's why I referred to the translation in the issue's title - am I supposed to report translation issues somehwere else?

Also, the question would be what has a higher priority - keeping keyboard shortcuts the way the are, or fixing a misleading translation?

**Comment by elextr** [comment]
> am I supposed to report translation issues somehwere else?

No here is fine, all it needs is somebody to make a pull request with a suggestion.

> Also, the question would be what has a higher priority - keeping keyboard shortcuts the way the are, or fixing a misleading translation?

Mnemonics (the underscored shortcut letters "proper" name) should be well, mnemonic :grin:, and in particular the main ones for the action buttons.  

In the English version the mnemonics for some of the settings are pretty much not mnemonic, but the main action buttons are, F for _find, R for _replace, and N (think Next) for replace & fi_nd which is fairly mnemonic and matches the find dialog.  So without knowing what the mnemonics in the German version are I would suggest that there is probably an obscure one on the settings you could change without too much grief. But make the main buttons F for _Finden, E for _Ersetzen, and N (Google translate says the German for Next starts with an N) for Ersetzen und Finde_n.

**Comment by frlan** [comment]
@Korodny  I've read the thread in the forum as well as was thinking about it and I'm afraid I did not came up with a better solution for this particular translation. If you like, please suggest a change

**Comment by Korodny** [comment]
@frlan How about this:

The last row of buttons becomes:

- S**c**hließen
- **S**uchen
- **E**rsetzen
- Ersetzen **u**nd Suchen

The only new one being the last one, obviously. "U" is used as a mnemonic for "N**u**r ganze Wörter finden" right now, but since "F" is unused now that we changed the last button, we can change that to "Nur ganze Wörter **f**inden"

**Comment by frlan** [comment]
Sounds good. Will update German translation
