### ISSUE TITLE
make "Go to File..." able to find all open files

### ISSUE THREAD

**Issue by zmike** [geany/geany#2525]
The "Go to File..." command isn't very useful since it's restricted to the directory of the currently-viewed file. It would become incredibly useful if it could be used to access all opened files.

**Comment by elextr** [comment]
>  it's restricted to the directory of the currently-viewed file.

Well, no its not, if its absolute it can be anywhere.

If its relative it looks in the current file dir first, then the project dir, and on Linux in some system include dirs.

But certainly, if its only a name with no directory components then it could also look at the open files as well, but that would need a disambiguation mechanism as its possible to have two files with the same name open.

**Comment by zmike** [comment]
I should maybe have provided a scenario:

I use geany without a project setup, and I'm frequently having to go to the files pane to swap between files because I'm working across large parts of a very large codebase split across repos. Typically I'll have something like 4-5 dozen files open, and I'd like to be able to have a keybind to quickly swap between files that I have open without needing to scroll through the files pane, ideally by starting to type the basename of the file into a popup window, as typing the full, absolute path would likely take more time than just using the Open dialogue due to the number of path components involved.

This could maybe work by adding "open files" as a lookup between current file dir and project dir?

As for disambiguation, I think it'd probably be fine to just show the path in the list of matching files? Perhaps even starting from the component of the full path where the file can be disambiguated.

Thanks for your consideration.

**Comment by elextr** [comment]
Did you try the commander plugin?  IIUC it provides a goto based on typing part names.

**Comment by zmike** [comment]
I'm not sure I've heard of that one? Is it usually packaged on distros with the other plugins, or is it in a separate repo?

**Comment by elextr** [comment]
Its part of the geany_plugins collection, how distros package the collection is up to them, some package each plugin and have a meta to get the lot others the whole collection.

**Comment by zmike** [comment]
Sure, I meant in general. Hadn't heard of the commander plugin before, but it does seem to do exactly what I wanted.

Thanks!
