### ISSUE TITLE
Feature Request - Move Paragraph

### ISSUE THREAD

**Issue by guyellish** [geany/geany#2531]
Firstly: I like Geany more and more - I used EditPlus for years, and needed something to replace it when I began using Ubuntu as much as Windows.
One thing I use very much is moving paragraphs up/down using Keyboard Shortcuts like Ctrl+Alt+Arrow Up/Down
I'm sure that many would find this useful.

**Comment by elextr** [comment]
Triple click selects paragraph, alt+page up/down.
