### ISSUE TITLE
Enable all the editor functions in splitted window?

### ISSUE THREAD

**Issue by fightthepower** [geany/geany#2537]
I am using the plugin `Split Window` to view files in two different editor windows. Its really a very helpful plugin but it lacks many functionality of the main editor window. 

When we open a file in splitted window, we

- Can't use plugins or most plugins doesn't work properly like AutoClose, TreeBrowser

- Can't compile, build or execute

-  Can't `Send selection to terminal`

**Comment by elextr** [comment]
Duplicate of many other split windows issues. See comments on #1523.
