### ISSUE TITLE
Why does Menu > open file kill Geany ?

### ISSUE THREAD

**Issue by abdulbadii** [geany/geany#2541]
A fast and lightweight IDE
                                   "Poliff"
                  (built on or after 2019-09-29)
Using GTK+ v3.24.20 and GLib v2.64.3 runtime libraries

Installed it by pacman
but then if doing Ctrl-O, ie. Menu File -> open file it will only kill Geany instead of its job opening file dialog.
How to solve it?

**Comment by elextr** [comment]
This is a recorded message, please always provide the version of Geany, Glib and GTK (see lines near the top of Help->Debug Messages) and the operating system and version you are using.

**Comment by codebrainz** [comment]
@abdulbadii the first step to solve it would be to [get a backtrace](https://www.geany.org/support/bugs/) so we can see how/why/where it's crashing.

**Comment by abdulbadii** [comment]
Sorry yes it's Linux sysyem bug not the application
