### ISSUE TITLE
"Open with Geany" on Windows sets Geany to default system language

### ISSUE THREAD

**Issue by pgram1** [geany/geany#2545]
https://github.com/geany/geany/blob/aa54866f982390cb5458e3265cedf954b03dd3f1/geany.nsi.in#L248

There should either be a way to pick the language from within the interface preferences and keep it in a global configuration file

or a fix like [this](https://github.com/geany/www.geany.org/blame/master/page_content/documentation/faq.md#L97) should be clear in the documentation

**Comment by elextr** [comment]
@pgram1 As it says on the other [issue](https://github.com/geany/geany/issues/1757#issuecomment-362868750) you pinged its not possible to do it within the app.

I'm not a windows expert, but the faq you linked seems to address the problem from my uneducated reading.  I'm not sure something so specific should go in the manual, although maybe an appendix.

**Comment by pgram1** [comment]
> 
> 
> @pgram1 As it says on the other [issue](https://github.com/geany/geany/issues/1757#issuecomment-362868750) you pinged its not possible to do it within the app.
> 
> I'm not a windows expert, but the faq you linked seems to address the problem from my uneducated reading. I'm not sure something so specific should go in the manual, although maybe an appendix.

Or just be a default language picking option during installation, like in most interfaces. I indeed agree that much less specific information should be a user's problem.

**Comment by elextr** [comment]
> Or just be a default language picking option during installation

Pull requests are welcome.

**Comment by pgram1** [comment]
https://github.com/geany/geany/issues/1757#issuecomment-657167749
