### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by Chayyoo** [geany/geany#2547]
I have been a happy user of Geany for several years now, I love its speed. Recently I'm experiencing regular crashes, with this message:
 [xcb] Unknown sequence number while processing queue
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
geany: ../../src/xcb_io.c:259: poll_for_event: Controletest '!xcb_xlib_threads_sequence_lost' faalt.

Version: Geany 1.36 Using GTK+ v2.24.32 and GLib v2.56.4 runtime libraries
System: linux Mint 5.0.0-32-generic #34~18.04.2-Ubuntu SMP Thu Oct 10 10:36:02 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by elextr** [comment]
X11 is only used by GTK, Geany itself does not use X, so either its a problem with your version of GTK or version of X11.

What is the actual version of LM?

It seems unusual to find a Geany 1.36 on GTK2, most distros provide Geany on GTK3 these days, did you build it yourself?

If so can you try a GTK3 build.

**Comment by Chayyoo** [comment]
Linux Mint Tricia 19.3
Yes I compiled it myself.
I have reverted to the version provided by Mint (Geany 1.32), but it doesn't mention the GTK version it was built with.  I remember with a previous version I had problems scrolling with the arrow up/down keys at the end of files with a large number of lines (> 1 million), but it seems I can't reproduce the problem right now. We'll see what happens.
Does Geany retain its speed with GTK3 ?

**Comment by elextr** [comment]
> but it doesn't mention the GTK version it was built with.

`Menu->Help->Debug Messages` near the top, tells you the version its actually using.

> Does Geany retain its speed with GTK3 ?

Million line files are not really in Geany's main use-case which is human edited files.  It only takes a few tens of thousands of lines before the liveware fails. :grin:  

Even so scrolling of a few million lines shouldn't be a problem _after_ all the loading and analysis is finished.   Do you have wrap lines on? That tends to be slow due to all the analysis needed by Scintilla to decide the wrap, that depends more on the Pango version than GTK.

**Comment by elextr** [comment]
PS just to note, I use home built Geany (Git master, but not materially different from 1.36) built with GTK3 on LM 19.3 with absolutely no instability, which is why I think the problem might be GTK2.

**Comment by Chayyoo** [comment]
It's GTK3:
14:22:36: Geany INFO		: Geany 1.32, nl_BE.UTF-8
14:22:36: Geany INFO		: GTK 3.22.30, GLib 2.56.4
I'll continue with this one.
PS: my big files are only rarely edited manually, usually with find/replace and regexes. I could use the GNU tools (and often do) but it's nice to have an immediate visual result.

**Comment by eht16** [comment]
Closing because probably unrelated to Geany itself.
Re-open if the problem appears again.
