### ISSUE TITLE
[Bug]  Geany doesn't "remember" font size when new file is created

### ISSUE THREAD

**Issue by codinghedgehog-python** [geany/geany#2552]
The title says it all. It would be nice if I could open new file in Geany and wouldn't
have to adjust the font size every time. The bug is now more notable than ever since
people have to adjust font size to see underscores.

**Comment by codebrainz** [comment]
Works for me on Ubuntu and Windows.

Can you provide more information like:
* Operating system and version
* Geany and GTK/GLib version (first few lines of `Help->Debug Messages`)
* Steps to reproduce
* Whether the problem occurs using a clean config dir (`geany -c /tmp/deleteme`)

**Comment by elextr** [comment]
Also see #2502 pinned at the top of the issues for a workaround to the missing underscores.

**Comment by codinghedgehog-python** [comment]
I'm on Ubuntu 20.04

output from the debug log:
```
07:25:44: Gtk MESSAGE	: Failed to load module "canberra-gtk-module"
07:25:44: Geany INFO		: Geany 1.36, en_GB.UTF-8
07:25:44: Geany INFO		: GTK 2.24.32, GLib 2.64.3
```

**Whether the problem occurs using a clean config dir (geany -c /tmp/deleteme)**
Yes it does. I ran the command and I still need to adjust the font size every time I open a new file.

I appreciate the workaround regarding to the issue with missing underscores. I used `line_height=0;2;` as suggested. But for it to kick in I need to zoom the font 3x (I don't know how many pixels is that. It doesn't show anywhere)

I hope I've provided enough info. Feel free to ask for more.

**Comment by elextr** [comment]
You seem to have two problems, missing underscores and font size of a new file.

For the missing underscores issue, the suggested additional spacing (2 pixels) is for "normal" screens, we don't know each users individual resolution, some resolutions may need more spacing so 2 is just a suggestion that works for many.  First, to check its actually working try setting it to 0;100; so its very visible that the setting is working. And restart Geany each change. Then experiment with a setting that makes the underscores visible, but doesn't make your lines too spaced.

I don't understand why you have to adjust the font size of a new file, the editor has only one font size setting that applies to all files, including new ones.  So if you change font size (`Menu->View->Change Font`) it should apply to all files open.

**Comment by codinghedgehog-python** [comment]
OK, so font size sticks now (hurray !)
I can now create new files with underscores visible automatically. `0;100;` didn't seem to make much of difference in comparison to `0;2;` but I'm grateful that I can see the underscores. Thank you for assistance.
