### ISSUE TITLE
[Question]  Adding filetype to config

### ISSUE THREAD

**Issue by codinghedgehog-python** [geany/geany#2558]
From the docs I understand I can override what syntax highlighting will be used on particular filetype.
In my case I'm trying to add `.jsx` extension to `extension=js` within `tools => configuration files => filetype configuration => scripting languages => javascript`
The docs indicate that I need to separate the filetypes with semicolon thus it should look like this  `extension=js;jsx`.
The docs say I need to restart Geany for it to take an effect. No change though. Am I missing something here ?

**Comment by elextr** [comment]
Yep :grin:

**Comment by elextr** [comment]
Oh, want to know what you missed? :grin:

You are editing the wrong file, to say that `.jsx` is to be treated as js add it to the list for javascript in `filetype_extensions.conf`

**Comment by codinghedgehog-python** [comment]
OK, wrong file.
So I'm in `filetype_extensions.conf` file and my line with Javascript looks like this:

`#~ Javascript=*.js;*.jsx;`

That isn't correct, is it ? The highlighting isn't kicking in after restart.

**Comment by elextr** [comment]
no, the #~ is a comment, need to remove it to make it work

**Comment by codinghedgehog-python** [comment]
Yeah, I've thought of that before I replied to you. But no change. With or without the hash sign.
Take a look <a href='https://utcloud.ddns.net/index.php/s/6elaVs0TigP0lLK'>here</a> and <a href='https://utcloud.ddns.net/index.php/s/gtpLAho2YXvCUki'>here</a> Use `geany` as a password for both.

**Comment by elextr** [comment]
Did you uncomment the `[Extensions]` section head as well?

**Comment by codinghedgehog-python** [comment]
That was it ! I didn't. :D  It's working now.
Thank you `elextr` for helping me sorting this out !

**Comment by codebrainz** [comment]
Related #2557
