### ISSUE TITLE
feature request: side panel width memory

### ISSUE THREAD

**Issue by zmike** [geany/geany#2562]
Maybe this already exists in the settings somewhere, but I couldn't find it: I'd like it if geany could remember the width of the side panel (where symbols, documents tabs are) across instances.

Every time geany opens, the side panel is very small and I always have to resize it. It'd be nice if this could be remembered.

**Comment by elextr** [comment]
WFM, and has worked for ever IIRC.

Does Geany remember and re-open the files that are open when its closed?

**Comment by zmike** [comment]
Yes.

**Comment by elextr** [comment]
Well without more information can't help you.

**Comment by zmike** [comment]
I didn't know it was already implemented.

Using v1.36 now. Actually, now that I'm paying more attention to the process, it seems like the window size isn't consistent across restarts, which is likely what's resetting the sidebar size. I'm not certain this isn't an issue with my window manager though, so I'll close this until I can determine it.

Thanks for the quick response!

**Comment by ralf3u** [comment]
@elextr

>WFM, and has worked for ever IIRC.

I don't know how it was before, but in Geany 1.39 it does not work for me.
Could you please reopen this issue?

**Comment by elextr** [comment]
@ralf3u that sounds like a different problem, please start a separate issue and provide the first few lines of `Help->Debug Messages`.

**Comment by ralf3u** [comment]
@elextr

>..., please start a separate issue ...

I just opened #3070.
