### ISSUE TITLE
Auto-closing braces issue (Windows 10)

### ISSUE THREAD

**Issue by nzamsci** [geany/geany#2564]
On the latest version of geany running on Windows 10, matching curly braces will stop working after some time. For example, 

```
int main() {
}

```
will stop placing the matching brace and any new braces created will just have one single brace

`int main() {`

Strange to say the least, a bit of a dealbreaker for me however on using the IDE. The rest is fantastic I just need that feature in my projects.

Thanks!

**Comment by elextr** [comment]
WFM, at least as long as I used it, need more info.

Also please put version numbers, "current version" is only relevant until the next release.

**Comment by nzamsci** [comment]
[https://www.youtube.com/watch?v=g5ejjY8caDk](url)

The version is 1.36. Forgot to show it but all the matching symbol boxes in the completion tab are checked.

I know this guy was having a similar issue.. [https://stackoverflow.com/questions/12925282/is-there-an-auto-close-curly-brackets-plugin-for-the-geany-ide](url)

**Comment by elextr** [comment]
Oh, internal braces, well Geany always refused to close a bracket `({[` if it had a matching `)}]` already.

Are you saying the behaviour has changed recently?  If so can you give a version that "works"?

**Comment by codebrainz** [comment]
@nzamsci you might want to try the [Autoclose plugin](https://plugins.geany.org/autoclose.html). In my experience it works much better than what's built-in to Geany. It's also mentioned in the S/O you linked.

**Comment by nzamsci** [comment]
@codebrainz works like a charm. Thanks
