### ISSUE TITLE
Geany 1.2.7 Failed to rename file after years of working fine

### ISSUE THREAD

**Issue by RonGroen** [geany/geany#2577]
Geany-INFO: Geany 1.27, C
Geany-INFO: GTK 2.24.30, GLib 2.48.2

Saving a file an a samba share gives an error. It has been working for a long time correctly. with commands, cp, rm and mv everything works fine.

11:19:48: This is Geany 1.27.
11:19:48: File /home/aharjg/smb4k/RH1/prive/Feest/testje.txt opened(1).
11:19:52: Error saving file (Failed to rename file '/home/aharjg/smb4k/RH1/prive/Feest/testje.txt.QGYOP0' to '/home/aharjg/smb4k/RH1/prive/Feest/testje.txt': g_rename() failed: File exists).

Same occurs when using Gedit on the samba share, but other software (libreoffice) and commands (mv) work fine.

Please help me

**Comment by elextr** [comment]
If its been working for a long time, something has changed.  So what has changed?  The use of a samba share, what version of samba, where the share is, a setting in Geany, what machine its running on (and you don't mention what operating system Geany is on or the OS of the machine the share lives on is either).

It looks like the clue is in the end of the error message, "file exists".  I'm not a windows expert, but I understand that windows will not rename over an existing file, which is what the message says.

See the PHD thesis [here](https://wiki.geany.org/config/all_you_never_wanted_to_know_about_file_saving) and try other file saving settings detailed there that don't rename over an existing file as `atomic_save` does.

Other software (libre office etc) does not use the atomic save method that writes to a temporary then renames it over the original file.

**Comment by RonGroen** [comment]
It is running on Ubuntu 16.04 and I tried all of the options on PHD thesis. Even removed the geany.conf file to test. I agree, something must have changed. Maybe an Ubuntu update?? I have been experimenting with JAVA... Are the save-options outside the geany package itself? Which one? Can I debug that myself?

**Comment by elextr** [comment]
As noted in the thesis both atomic save and GIO unsafe save are provided by Glib library functions, so we don't control what they do, and the option used when neither is set is built into Geany.  

Are you really sure you tried setting neither option? The code in Geany does no rename, so its strange you are getting a rename error.

**Comment by RonGroen** [comment]
Sorry. I retried the GIO unsafe option an now it works. 
Thank you for you help :-)
