### ISSUE TITLE
[feature request] Sort selected rows

### ISSUE THREAD

**Issue by jesus2099** [geany/geany#2582]
It would be very useful to provide commands to sort selected rows in alphabetical (character code) order (and reverse) or numeric order (and reverse).

**Comment by eht16** [comment]
This can be done with custom commands.
See https://geany.org/manual/#sending-text-through-custom-commands and https://wiki.geany.org/config/customcmds/sort-selection.

**Comment by jesus2099** [comment]
Thank you very much, that looks awesome! I will try that.
