### ISSUE TITLE
Geany and freebasic

### ISSUE THREAD

**Issue by Plutonium5793** [geany/geany#2583]
When using geany with freebasic I find that it does not recognize that 'boolean' is a key word.  Other variable types appear in blue, but 'boolean' appears as normal type.

**Comment by elextr** [comment]
According to the Freebasic [wiki](https://www.freebasic.net/wiki/KeyPgBoolean) boolean is new to freebasic, so somebody needs to make the lexer recognise it.

**Comment by eht16** [comment]
@Plutonium5793 See #2593.
You can easily test the changes yourself: open Tools->Configuration Files->Filetype Configuration->Programming Languages->FreeBasic.
A new file open will open and there edit the `[keywords]` section as in the mentioned PR.
