### ISSUE TITLE
Feature Request: Color Picker with predefined color palette

### ISSUE THREAD

**Issue by hubertmeier** [geany/geany#2595]
Hi,

i switched completely to geany on all my platforms because geany is available for windows, Linux Mint and Raspberry OS and is active in development. On Windows i used pspad and there was a color picker which had predefined colors.

I use the color picker often for html and i try to find every time the same color with the sliders, the result is mostly similar but not the same ... is there a better color picker ?

Thank you

**Comment by eht16** [comment]
> I think the older and newer color selection dialog boxes allow palettes, but I don't think Geany persists them.
Do you think it's possible at all to persist the palettes? After a quick look in the docs I think it's possible to set the palette for the ColorChooser but there is no way to read the palette from the widget (after it might have been changed by the user).

**Comment by codebrainz** [comment]
> Do you think it's possible at all to persist the palettes?

For the good/useful [GtkColorSelection](https://developer.gnome.org/gtk3/stable/GtkColorSelection.html) there are functions to get/set the palette by string.

For the phone-app dumbed-down useless newer one, I believe you are correct.

**Comment by elextr** [comment]
Doesn't save here LM20 (Ubuntu 20.04) Cinnamon Geany 1.37.

**Comment by codebrainz** [comment]
I tested by going to the Terminal preferences and using the goofy colour picker dialog that pops up when you click one of the bg/fg colour buttons. I changed one of the palette colours, saved the prefs and closed and re-opened Geany.

**Comment by elextr** [comment]
Can't even change the pallette in the dinky terminal colour picker.

Can change it in toolbar colour picker (the one the OP is talking about) but it doesn't persist.  Note on LM this is the good version of the picker by default, not the same dinky one as the terminal picker.

Looks like it may depend on the default system/theme/GTK version (GTK 3.24.20, GLib 2.64.3) here.

**Comment by codebrainz** [comment]
In the mobile colour chooser that comes up for colour buttons, you have to tap and hold on a color in the top section and swipe it into one of the palette boxes as the bottom.

The colour picker in the toolbar (that this issue is about) still uses the better but deprecated GtkColorSelection* widgets.

**Comment by elextr** [comment]
@codebrainz the boxes at the bottom are "recent colours" not a palette (though you could use it as such).  Thats probably why its saved in some mystery Gnome hole somewhere, like recent files etc

**Comment by codebrainz** [comment]
Ah....
