### ISSUE TITLE
Editor doesn't show underscores

### ISSUE THREAD

**Issue by cmsigrist** [geany/geany#2608]
The version is: geany 1.36 (built on Mar 22 2020 with GTK 3.24.14, GLib 2.64.1)
And I'm working on Ubuntu 20.04.1. It's not a major bug but it's a bit confusing looking at code where instead of underscores you get whitespaces!

**Comment by elextr** [comment]
Duplicate of the issue pinned at the top of the Github issues.

**Comment by frlan** [comment]
-> #2502
