### ISSUE TITLE
Missing rst2html causes failure of configure run

### ISSUE THREAD

**Issue by frlan** [geany/geany#2628]
Having a system without rst2html:

```
checking for rst2html... no
checking for rst2html.py... no
configure: error: Documentation enabled but rst2html not found.
You can explicitly disable building of the HTML manual with --disable-html-docs,
but you then may not have a local copy of the HTML manual.
```

but ./configure -help tells, it's auto:

```
  --enable-html-docs      generate HTML documentation using rst2html
                          [default=auto]
  --enable-pdf-docs       generate PDF documentation using rst2pdf
                          [default=auto]
  --enable-api-docs       generate API documentation using Doxygen
                          [default=auto]
```

**Comment by elextr** [comment]
Confirm, had the same problem last time I built Geany, needed manual --disable-html-docs

**Comment by frlan** [comment]
With 1.36 release-tarball it was no show stopper

**Comment by elextr** [comment]
The tarball includes HTML docs IIRC, so no rst2html needed for tarballs

**Comment by frlan** [comment]
Hmmmm. It really looks like there is a switch inside the m4 code -- but still auto is not working ;)

**Comment by b4n** [comment]
I didn't check the code, but IIRC we meant to do this.  We are happy without the tool *only* if they documentation is already built (like in a tarball).  IIRC it was to avoid the case where the help wouldn't work.

**Comment by elextr** [comment]
Since help falls back to the online documentation it should be ok to not build it.

**Comment by codebrainz** [comment]
> I didn't check the code, but IIRC we meant to do this.

Yep:
https://github.com/geany/geany/blob/9a8b5c9e27e986ecd41ddbdfcb6548c62fb1e391/m4/geany-docutils.m4#L17

**Comment by frlan** [comment]
I see -- so not really a bug ;)
