### ISSUE TITLE
Unclear text on label

### ISSUE THREAD

**Issue by peter-scholtens** [geany/geany#2635]
The label attached at plugins/saveactions.c:688 is described as "_Filetype to use for newly **opened** files:" But how can a file be opened if it didn't exist on disk yet? Would it not be better to describe it as "_Filetype to use for newly **created** files:". See #2633

**Comment by codebrainz** [comment]
I agree, "newly opened" is confusing when the feature is specifically meant for _new_ files.

Probably the most accurate label would be: "Default filetype to use for new files"

**Comment by peter-scholtens** [comment]
Even better! Agreed.

**Comment by frlan** [comment]
I agree. Will update master branch
