### ISSUE TITLE
geany would not open (Windows 10)

### ISSUE THREAD

**Issue by UBUNTUTHEDISTRO** [geany/geany#2639]
so i recently installed geany since visual studio was too long to install but
after i finished setup, i clicked on the shortcut but it would not open,
i tried to run geany from the start menu, even from e: (the drive i installed geany on) but nothing would work
i have the gtk+ runtime thing installed. i tried it from wsl, but still nothing.
can someone help me? thanks

**Comment by elextr** [comment]
Where did you download it from? What version? how did you get GTK runtime, what version?

**Comment by xbjfk** [comment]
I am having this issue with 1.37 as well, with the bundled GTK runtime. 1.36 works fine, and runs successfully.

**Comment by UBUNTUTHEDISTRO** [comment]
@elextr I downloaded Geany from the official Geany website, idk my gtk+ version, geany 1.37? and i forgot where i got GTK+
maybe i haven't installed GTK+ since i upgraded from 8.1 to 10.

**Comment by eht16** [comment]
If you didn't the GTK runtime yourself but together with the Geany installer, then it's fine.

Could you please open a command line window and execute the following command:
`"c:\Program Files (x86)\Geany\bin\geany.exe" -v`
This will start Geany and opens an additional console window with some debug messages. I assume the console window will close as soon as Geany will close but maybe you can still see something useful.

I have no idea yet what could be wrong and I have only Windows 7 where 1.37 works.

**Comment by Bergamask** [comment]
> 
> 
> I am having this issue with 1.37 as well, with the bundled GTK runtime. 1.36 works fine, and runs successfully.

me too

**Comment by elextr** [comment]
To the OP and the "me too" people.

As few of the Geany devs use Windows 10 you need to try the things suggested and post the results if you want a timely resolution.

**Comment by eht16** [comment]
@ all affected users:

Do you have Geany-Plugins installed?
If so, try uninstalling Geany-Plugins and try again.

If Geany still crashes on startup, please uninstall Geany and try this installer: http://download.geany.org/snapshots/geany-1.37_setup-2.exe

It is exactly the same code as in the 1.37 release but with updated GTK runtime libraries. If we are lucky, it will work.
TBH this is just a guess, as I still have no clue what is wrong.

**Comment by Chicopower** [comment]
Same problem here using v1.37 with Windows 10 v2004 (fresh v1.37 install without any plugin and using the geany-1.37_setup.exe installation)
"c:\Program Files (x86)\Geany\bin\geany.exe" -v
command give no message in the console windows and throw the same error in event viewer as if i try to open geany normaly.

I just uninstalled v1.37 and installed v1.36 and everything work as expected!

Here is my Event Viewer error message when i try to open geany v1.37 with Windows 10 v2004:
Faulting application name: geany.exe, version: 1.37.0.0, time stamp: 0x00000000
Faulting module name: msvcrt.dll, version: 7.0.19041.546, time stamp: 0x7f567a50
Exception code: 0xc0000005
Fault offset: 0x000897fc
Faulting process id: 0x5dfc
Faulting application start time: 0x01d6b152ef0b3186
Faulting application path: c:\Program Files (x86)\Geany\bin\geany.exe
Faulting module path: C:\WINDOWS\System32\msvcrt.dll
Report Id: 22dc37a5-28ce-43b4-b4ce-b25471325789
Faulting package full name: 
Faulting package-relative application ID:

**Comment by lmforget** [comment]
I had the same issue. I downloaded http://download.geany.org/snapshots/geany-1.37_setup-2.exe and it worked fine. I added the plugins after and continued to work.

**Comment by hend217** [comment]
I can confirm the same issue on Windows 10 2004 64 bits, Windows 10 20H2 (32 and 64), Windows 2012 Server R2, Windows 7 32 and 64 bits.
Event viewer: 
```
Faulting application name: geany.exe, version: 1.37.0.0, time stamp: 0x00000000
Faulting module name: msvcrt.dll, version: 7.0.19041.546, time stamp: 0x7f567a50
Exception code: 0xc0000005
```

**Comment by elextr** [comment]
@lmforget thanks for that, everybody else try the `http://download.geany.org/snapshots/geany-1.37_setup-2.exe` version.  (Note the -2).

**Comment by UBUNTUTHEDISTRO** [comment]
i used the -v but the console closed and nothing happened. hmm...

**Comment by Bergamask** [comment]
> To the OP and the "me too" people.
> 
> 
> 
> As few of the Geany devs use Windows 10 you need to try the things suggested and post the results if you want a timely resolution.

My apologies for my comment, my case is a fresh new install on windows 10 without plugin. I'll try the -2.exe version

**Comment by ndroock1** [comment]
I tried the http://download.geany.org/snapshots/geany-1.37_setup-2.exe , but Geany still does not work on Windows 10.

**Comment by Chicopower** [comment]
geany-1.37_setup-2.exe fixed the problem here. Thx!

**Comment by eht16** [comment]
@UBUNTUTHEDISTRO did you also try the `geany-1.37_setup-2.exe` installer?

@ndroock1 are you sure you downloaded and installed the `geany-1.37_setup-2.exe` installer?
I just want to get sure as it seems the updated installer works for other users.

@lmforget and @Chicopower thanks for the feedback!

**Comment by UBUNTUTHEDISTRO** [comment]
i installed geany 1.36 and it works. let this be a lesson to you: old versions are sometimes useful. ok now i have to code goodbye

**Comment by ndroock1** [comment]
> @UBUNTUTHEDISTRO did you also try the `geany-1.37_setup-2.exe` installer?
> 
> @ndroock1 are you sure you downloaded and installed the `geany-1.37_setup-2.exe` installer?
> I just want to get sure as it seems the updated installer works for other users.
> 
> @lmforget and @Chicopower thanks for the feedback!

Yes. I did took setup-2. The original setup is still on the download page! Why?

For me 1.36 does what I need to do.

**Comment by eht16** [comment]
Re-opening as this is not yet resolved until we know for sure that the new installer works.

> > @ndroock1 are you sure you downloaded and installed the `geany-1.37_setup-2.exe` installer?
> > I just want to get sure as it seems the updated installer works for other users.
> > @lmforget and @Chicopower thanks for the feedback!
> 
> Yes. I did took setup-2. The original setup is still on the download page! Why?

Because the installer seem to work for some people but not for all (e.g. you).
Though I don't know what else we could do to debug this. I have access only to a Windows 7 machine and there is works.
@ndroock1 starting Geany behaves the same on the original 1.37 and the setup-2 installer?

@codebrainz do you have a Windows 10 machine?


> For me 1.36 does what I need to do.

This might be fine for the moment but is obviously not a solution.

**Comment by ndroock1** [comment]
> @ndroock1 starting Geany behaves the same on the original 1.37 and the setup-2 installer?

Quite. Nothing happens.

**Comment by ndroock1** [comment]
Let me know if I can do anything to help.

**Comment by codebrainz** [comment]
@eht16 the 1.37 release installer from the website works fine for me on Win10 Pro (10.0.19041 Build 19041).

```
08:12:31: Geany INFO		: Using TCP port number 45937 for IPC
08:12:31: Geany INFO		: Geany 1.37, English_United States.1252
08:12:31: Geany INFO		: GTK 2.24.32, GLib 2.66.2
08:12:31: Geany INFO		: OS: Windows 10 2004
```

**Comment by Bergamask** [comment]
I tried -2.exe version on Win10 2004 build 19041.610 and it works

**Comment by eht16** [comment]
@Bergamask and @codebrainz thanks for the feedback!

@ndroock1 
Ok.
I've got one more installer for you: https://download.geany.org/snapshots/geany-1.37_setup_debug_log.exe
It's the same as before but it will write a logfile to `C:\Users\<username>\AppData\Roaming\geany\logfile.txt`. With a bit of luck there is something useful in it (or it doesn't get created at all, then we know the crash happens very very early).

Additionally, you could try to temporarily rename your config folder to force Geany to start with a default config.
You could also try disabling a firewall if there is one running.

**Comment by Rasbats** [comment]
Same issue here with Win 8.1. No log file made with the debug log version.

Mike

**Comment by ndroock1** [comment]
> @Bergamask and @codebrainz thanks for the feedback!
> 
> @ndroock1
> Ok.
> I've got one more installer for you: https://download.geany.org/snapshots/geany-1.37_setup_debug_log.exe
> It's the same as before but it will write a logfile to `C:\Users\<username>\AppData\Roaming\geany\logfile.txt`. With a bit of luck there is something useful in it (or it doesn't get created at all, then we know the crash happens very very early).
> 
> Additionally, you could try to temporarily rename your config folder to force Geany to start with a default config.
> You could also try disabling a firewall if there is one running.

Will this install has any effect on 1.36? ( I am in a busy project at the moment. Can't afford to jeopardize it. )

**Comment by eht16** [comment]
@ndroock1 
> Will this install has any effect on 1.36? ( I am in a busy project at the moment. Can't afford to jeopardize it. )

I don't think so, it should be safe to try. To start with a fresh config simply rename the Geany config folder, so you can rename it back again later (`C:\Users\<username>\AppData\Roaming\geany`).

@Rasbats could you also try renaming the config folder to see if it changes anything and disable firewall if present?

Both things will probably not help because if the log file isn't created, the crash happens very very early and maybe even before the config is read :(. But I don't have any other ideas left :(.

**Comment by Rasbats** [comment]
Enrico...

Win8.1 was where I had the problem with 1.37 not starting. 
Yesterday I upgraded to Win10 and today before doing anything else the debug version works, after uninstalling 1.36 and installing 1.37.

As a test I renamed config folder and disabled firewall. Geany did not start.

Went back to the old, working config and Geany starts. Logfile from1.37 debug is here:
[logfile.txt](https://github.com/geany/geany/files/5504606/logfile.txt)

**Comment by eht16** [comment]
Oh, great.
I found the cause and it's just a stupid typo in a debug message :(.
If Geany is started without an existing configuration file, we log a message that the default TCP port for IPC is used (#2585). But in this log message I specified the wrong format specified for logging an integer and this leads to a crash.

This is actually independent from the Windows version, it only depends on the existence of a configuration file.

Unfortunately, this does not explain why the "-2" installer worked for some people as the mentioned bug was included in it as well.

**Comment by elextr** [comment]
Presuming you mean user config, probably people it worked for simply continued to use their existing config so they always had one.

**Comment by eht16** [comment]
Yeah but I was wondering about @lmforget, @Bergamask and @Chicopower who had problems with the original 1.37 installer but got it working with the "-2" installer. This might indicate there was additionally an independent problem.

@ndroock1 and @Rasbats could you please try: https://download.geany.org/snapshots/geany-1.37_setup-pr2645.exe - this is the "-2" installer + the mentioned bug fix in #2645.

**Comment by Chicopower** [comment]
In my case, this was the first Geany installation on my machine when i tried 1.37.
Not working then i installed 1.36 and it worked. I was able to use it a little bit and customize some preferences settings.
After that, i uninstalled 1.36 and installed 1.37-2. It worked and my preferences from my 1.36 usage was keeped.

Then, the bug in the code you spotted make sense to me 👍

**Comment by Bergamask** [comment]
I don't know if it helps but what I notice is that 1.37-2 takes more time to load than 1.36.
1.36 opened immediately after the click instead 1.37-2 need some second.

**Comment by codebrainz** [comment]
I noticed the slow startup on Windows since pre-releases of 1.37, I assumed it was something with my computer/Windows. It's not a huge deal, but it certainly seems slower than it ought to be.

Possibly related: https://github.com/geany/geany-osx/issues/20

Startup time in Ubuntu 20.04 seem unaffected.

I guess we should make a new Issue for the slow startup, I will do once I'm back in Windows and have a chance to time/test, if nobody else opens one first.

**Comment by b4n** [comment]
> Yeah but I was wondering about @lmforget, @Bergamask and @Chicopower who had problems with the original 1.37 installer but got it working with the "-2" installer. This might indicate there was additionally an independent problem.

As @Chicopower said, they might all have tried something else in between and then had the config file and wouldn't hit the issue.
But even if they did not, I wouldn't be totally surprised if another set of libraries did not lead to a crash.  I'm not sure how Windows behaves in this regard, but usually reading arbitrary memory like this leads to unpredictable results, not necessarily a crash. Could be that that other set of libraries result in a memory mapping with a zero byte (string terminator) close to the address that gets read before hitting a memory violation.  Or maybe not, but well, I wouldn't bet anything on that horse.  My point is: don't sweat it looking for another problem yet, it's more than likely that #2645 is the answer.  But sure, getting them to try the version with the meaningful fix is a good idea for sure, then we'll have a better idea :)

**Comment by eht16** [comment]
@ndroock1, @Rasbats and all who still had problems: we've just releases Geany 1.37 (https://github.com/geany/geany/releases/tag/1.37.1) with a fix for the startup crash.

**Comment by UBUNTUTHEDISTRO** [comment]
holy crap this is long

**Comment by UBUNTUTHEDISTRO** [comment]
I fixed the problem already but I guess I'm not selfish
