### ISSUE TITLE
Split window plugin: reloading files

### ISSUE THREAD

**Issue by bchretien** [geany/geany#264]
Apparently, the file in the split window cannot be reloaded directly (`Ctrl + R` is only for the file in the main window), and when the split file is updated outside of Geany, the `"The file on the disk is more recent..."` pop-up is not triggered. Switching to the file in the main window is apparently the only way to do that.

I don't know if this is something complicated to implement, but having the same feature as for the main window would definitely be useful :-)

**Comment by kugel-** [comment]
@bchretien This is unlikely to get fixed in the current splitwindow implementation, where basically only some keybindings directly provided by Scintilla work. So the behavior is kind of accepted. If it's still an issue for please speak up, otherwise I'll close this in a week.

**Comment by bchretien** [comment]
@kugel no problem for me, I just wanted to notify the development team ;)
