### ISSUE TITLE
User defined snippets not being detected

### ISSUE THREAD

**Issue by ianmkenney** [geany/geany#2646]
Geany version: 1.36
OS: Linux Mint 20

Copying `/usr/share/geany/snippets.conf` to `$HOME/.config/geany/snippets.conf` and replacing the block

```
# [Python]
# for=for i in xrange(%cursor%):\n\t%cursor%
# if=if %cursor%:\n\t
# elif=elif %cursor%:\n\t
# else=else:\n\t
# while=while %cursor%:\n\t
# try=try:\n\t%cursor%\nexcept Exception, ex:\n\t
# with=with %cursor%:\n\t
# def=def %cursor% (%cursor%):\n\t""" Function doc """\n\t
# class=class %cursor%:\n\t""" Class doc """\n\t\n\tdef __init__ (self):\n\t\t""" Class initialiser """\n\t\tpass
```

with (added one line at bottom)
```
# [Python]
# for=for i in xrange(%cursor%):\n\t%cursor%
# if=if %cursor%:\n\t
# elif=elif %cursor%:\n\t
# else=else:\n\t
# while=while %cursor%:\n\t
# try=try:\n\t%cursor%\nexcept Exception, ex:\n\t
# with=with %cursor%:\n\t
# def=def %cursor% (%cursor%):\n\t""" Function doc """\n\t
# class=class %cursor%:\n\t""" Class doc """\n\t\n\tdef __init__ (self):\n\t\t""" Class initialiser """\n\t\tpass
# customsnippet=customsnippetoutput
```
does not produce the expected output when editing a `.py` file. I restarted Geany after saving the new config file. Writing `customsnippet` and hitting tab just adds whitespace.

**Comment by codebrainz** [comment]
All lines starting with `#` are comments, same as with Python. Try uncommenting at least `[Python]` line and the line you added.

**Comment by ianmkenney** [comment]
Yup that does it. Thanks for the clarification. The confusion stems from another potential issue, which I will open soon. This one is closed though. Thanks!
