### ISSUE TITLE
windows, 1.37.1 , no plugin available

### ISSUE THREAD

**Issue by fyah** [geany/geany#2655]
Hello,

1.37.1 was released but there is no plugins version matching.

trying to install 1.37 G-P results in the following
![image](https://user-images.githubusercontent.com/2546966/98839241-979e2800-2445-11eb-8fae-20f88f2cdd08.png)

**Comment by codebrainz** [comment]
Does it work when you choose to continue?

**Comment by b4n** [comment]
Sounds like we should allow any version matching X.Y.* instead of only X.Y.Z in the GP installer.

**Comment by fyah** [comment]
next message
![image](https://user-images.githubusercontent.com/2546966/98841589-9fab9700-2448-11eb-99fa-2d302b9a8ea2.png)

->OK

plugins are working ok
![image](https://user-images.githubusercontent.com/2546966/98842292-9f5fcb80-2449-11eb-9594-8e40db5d52ed.png)

sorry for the false issue.. I could have tested...

**Comment by eht16** [comment]
> Sounds like we should allow any version matching X.Y.* instead of only X.Y.Z in the GP installer.

Yes but it was too late for 1.37.1. As @fyah noticed in the meantime, the warning is harmless in this case but useful in general and should be loosen up to major.minor.
I took it on my imaginary todo list for 1.38.
