### ISSUE TITLE
[1.37] markdown fonts upset cursor position

### ISSUE THREAD

**Issue by smartavionics** [geany/geany#2662]
Hi, the latest (1.37) geany now has a problem editing markdown files in that the text that is shown in bold font appears to confuse the cursor positioning. i.e. click at some position within some bold text and then a second or so later the cursor jumps from the clicked position to the location that will be altered if you then type. Built on a Ubuntu 16.04.7 system using GTK+ v3.18.9 and GLib v2.48.2 runtime libraries.

As a workaround, is it possible to turn off the font change within the editor while still keeping the mode as markdown?

Thanks.

**Comment by elextr** [comment]
Doesn't happen here:

15:05:46: Geany INFO		: Geany 1.37 (git >= 915cf6e8), en_AU.UTF-8
15:05:46: Geany INFO		: GTK 3.24.20, GLib 2.64.3
15:05:46: Geany INFO		: OS: Linux Mint 20 (ulyana)

Try a different font.

The font face is defined by the colour scheme, perhaps try [one](https://github.com/geany/geany-themes) that does not use bold (or make your own).

**Comment by smartavionics** [comment]
Hi, thanks for the swift response.

Yes, I think it was a font-specific problem. I was using Noto Sans but when I changed to Liberation Sans, the problem went away.

Closing...
