### ISSUE TITLE
New obnoxious default close icon in toolbar icons as of Ubuntu 20.04

### ISSUE THREAD

**Issue by dagelf** [geany/geany#2664]
Does this come from the Gtk3 theme? What's an easy way to revert?

The new close icon is very distracting and looks like errors all over the screen. The old grey one was perfect.

![2020-11-18-092836_4160x2104_scrot](https://user-images.githubusercontent.com/802628/99500323-de7aa900-2982-11eb-894f-10d95043f679.jpg)

**Comment by dagelf** [comment]
Also, does anyone know where this change originated so I can open an issue there? Thanks

**Comment by b4n** [comment]
This directly depends on the GTK icon theme used, which can be configured like the rest of the look & feel in your setup -- which you didn't mention BTW.
That's not something Geany controls, it just requests an icon with a specific name (*close* would be my guess, but I'll have to check), and get whatever image the icon theme has for this.

It looks like the icon theme you use changed that icon in a manner you don't like.  You can then either change icon theme, or change that specific icon (it can be overridden in *~/.local/share/icons* IIRC, details TBD).
