### ISSUE TITLE
Nim configuration is broken

### ISSUE THREAD

**Issue by HJarausch** [geany/geany#2669]
When open a .nim file or creating an project with a .nim file
The Build pull down menu doesn't offer the 'Compile' button.

**Comment by elextr** [comment]
The entries in `[build-menu]` are for `[build-settings]` so they are not recognised.

**Comment by HJarausch** [comment]
So, what can I do?
Why is there a filetypes.python but no filetypes.nim. And why is there a filetypes.Nim.conf
Is there any documentation about these files?

**Comment by b4n** [comment]
> So, what can I do?

Easiest is to replace `[build-menu]` with `[build-settings]` in *filetypes.Nim.conf*.
But basically yes, the Nim filetype we distribute is kind of broken in that regard.

> Why is there a filetypes.python but no filetypes.nim. And why is there a filetypes.Nim.conf

https://www.geany.org/manual/current/index.html#custom-filetypes

> Is there any documentation about these files?

https://www.geany.org/manual/current/index.html#filetype-definition-files

**Comment by HJarausch** [comment]
[filetypes.Nim.conf.txt](https://github.com/geany/geany/files/5577526/filetypes.Nim.conf.txt)
Many thanks, I have attached my current version of filetypes.Nim.conf which works just fine.
Please review and replace the current version by this one,
thanks,
Helmut
