### ISSUE TITLE
Open files not remembered if Geany closed with a project open.

### ISSUE THREAD

**Issue by elextr** [geany/geany#267]
If Geany is closed with a project open it does not save the files that were open before the project to geany.conf, instead it saves the files open in the project.

This is annoying since now closing the project leaves all the project files open since they have become the non-project saved session.

It is slightly complicated by the fact that the session files do not have to be stored in the project file (its a pref).

But if the session files are being stored in the project then Geany should store the files that were open before the project in Geany.conf.

**Comment by kugel-** [comment]
@elextr @scriptum I suggest the following, and will implement it if time allows: 

- Remove the ability to store project sesson files in geany.conf (i.e. remove the preference and enable it unconditionally, it's alredy on by default)
- Store session in geany.conf when opening a project
- Restore session when closing the current project 

The current state is just awkward and I don't really understand what the preference is about (why would you want to turn it off?). And losing the session is extremely annoying.

**Comment by elextr** [comment]
> Remove the ability to store project sesson files in geany.conf (i.e. remove the preference and enable it unconditionally, it's alredy on by default)

Well the option is to store them in project file or not `Edit->Preferences->Miscellaneous->Use project based session files`, but I guess the inverse could be taken to mean store them in `geany.conf`, except it doesn't control that, which is the point of the issue.  

Personally I am happy to remove it and say project session files go in project files and non-project session files go in `geany.conf`, project files are really only named sessions, they are not much use without them unless someone has a reasonable use-case for not doing so?

>Store session in geany.conf when opening a project
> Restore session when closing the current project

@kugel Looks like a good solution to me.  

One thought is the need to try to avoid swapping to the geany session then back to another project session when swapping between two projects.
