### ISSUE TITLE
STLWRT

### ISSUE THREAD

**Issue by smnthermes** [geany/geany#2673]
You should consider using [STLWRT](https://github.com/thesquash/stlwrt) instead of GTK 2. According to its README, "the goal is to be able to run most GTK+ 2 and many GTK+ 3 applications using the same STLWRT library", so supporting both STLWRT and GTK 3 should be relatively straightforward.

Interesting read: https://ubuntu-mate.community/t/horrible-gtk3-gnome-ui-design-is-leaking-into-ubuntu-mate-applications-in-20-04/22028/57

**Comment by b4n** [comment]
We are phasing GTK2 out, and we have GTK3 support for a long time now. And no, we most likely will not switch to a very young library with currently a single contributor based on a fairly old library -- not only I don't think it's a good idea, but we certainly don't have the manpower to pursue fragile rewrites.
