### ISSUE TITLE
jump to def

### ISSUE THREAD

**Issue by hjd3301** [geany/geany#2680]
l.s.
maybe it is available but I can't find it...

Is it possible to create an edit option wich provides a 'jump to' the def you want to edit by double-clicking it's name 

at the moment you have to scroll very much in a larger program....

thanks!

Kind regards,

Harry Dekker

**Comment by elextr** [comment]
Select a name, `ctrl+t`, other options and their shortcuts are available in the right click menu.

**Comment by hjd3301** [comment]
Yes! Gotit...
Ctrl-t + enter
Thanks!

Harry Dekker



Op ma 30 nov. 2020 11:33 schreef elextr <notifications@github.com:
