### ISSUE TITLE
Blue snippets between < and >

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#2682]
Please tell me how to prevent the snippets turning blue between < and > per the attached screen shot?  Thanks!

![image](https://user-images.githubusercontent.com/7548378/101105274-06921b00-35c5-11eb-9098-d3f6483707b5.png)

**Comment by elextr** [comment]
Change the filetype to "None"

**Comment by philiprbrenan** [comment]
Document  ▷  Set File Type  ▷ Miscellaneous  ▷ Config file
