### ISSUE TITLE
When conf files are copied from system to user the section headings should not be commented out ...

### ISSUE THREAD

**Issue by elextr** [geany/geany#2689]
... that way new users don't have to be told to uncomment the heading as well as the setting they need, just the setting line.  

And document this commenting behaviour in the manual.

**Comment by codebrainz** [comment]
Agree. It seemed like a good idea, but is proving troublesome with people who aren't familiar with GLib's keyfile format. At the very least the `[section]` lines shouldn't be commented.

**Comment by techee** [comment]
Fixed by #3413 (apart from the documentation, but IMO this would just add a noise to the manual).
