### ISSUE TITLE
Where is the CHANGELOG?

### ISSUE THREAD

**Issue by dandv** [geany/geany#2701]
I only see one [pre-2011](https://github.com/geany/geany/blob/master/ChangeLog.pre-1-22). It would be helpful to see what's changed recently,
* for returning users who are installing Geany into a new OS
* for those who want to see if the changes vs. the latest version in the Debian repos are worth compiling from source

**Comment by codebrainz** [comment]
The `ChangeLog` is included in the official releases, it's generated from the Git log during `make dist`.

If you don't want to compile Geany first, you can run `git log` from within the Git source tree.

If you don't want to even check-out the Git source tree, you can [browse the history online](https://github.com/geany/geany/commits/master).

Finally, every release is accompanied by release notes which highlight the most important changes between versions and are included in the [`NEWS` file](https://raw.githubusercontent.com/geany/geany/master/NEWS) and can also be viewed through [Github releases](https://github.com/geany/geany/releases) or on [the Geany website](https://www.geany.org/documentation/releasenotes/).

**Comment by rubyFeedback** [comment]
I like https://www.geany.org/documentation/releasenotes/ !

**Comment by codebrainz** [comment]
Closing since same/similar info is available in numerous places.
