### ISSUE TITLE
How modify message background color?

### ISSUE THREAD

**Issue by abdulbadii** [geany/geany#2702]
How do we modify message background color when build is executed to become full black ? Please help is unreadable at all..

**Comment by elextr** [comment]
Do you mean in the "compile" tab?  The background is controlled by your GTK theme, the foregrounds are as per the first 3 listed in https://www.geany.org/manual/current/index.html#customizing-geany-s-appearance-using-gtk-3-css

**Comment by abdulbadii** [comment]
Got the css, now the Gtk theme on Xfce any idea to access the easiest way?

**Comment by codebrainz** [comment]
`Tools` ⮞ `Configuration Files` ⮞ `geany.css`

Put this in it and save:
  
  ```css
.view {
    background: black;
}
  ```

Message background color become full black when build is executed.
