### ISSUE TITLE
Can't multi select use ctrl+mouse-select-click

### ISSUE THREAD

**Issue by abdulbadii** [geany/geany#2704]
How to do multi select, Can't have it to work by use of ctrl+mouse-select-click (just like noptepad++ as same Scintilla)
Or any peculiar way to do it?

**Comment by elextr** [comment]
The only multiple selections Geany supports are rectangular selections, it does not support discontiguous multiple selections.

**Comment by elextr** [comment]
See also #1141 #850 and others

**Comment by abdulbadii** [comment]
reopened
