### ISSUE TITLE
Surprising delay moving the text cursor in snippets

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#2716]
I experience a considerable delay moving the text cursor into the pink cell in snippets from the left using the right arrow key:

![image](https://user-images.githubusercontent.com/7548378/103446151-6e935a00-4c74-11eb-9bf3-17856a8f11ea.png)

`table=<table border="0" cellpadding="10">\n<tr><td>%cursor%\n<tr><td>%cursor%\n<tr><td>%cursor%</table>`

which is surprising in Geany which is well known and  rightly admired for its brilliant presentation and lightening fast response.

**Comment by elextr** [comment]
@philiprbrenan you have been around long enough to know to always post the Geany, GTK, glib and operating systems versions.

Also what filetype are you using for that file, its clearly not `conf`, and try with no plugins enabled.

**Comment by philiprbrenan** [comment]
It was the miniscript plugin that was causing the delay.  I have unplugged it.

**Comment by philiprbrenan** [comment]
Thank you for your  help.
