### ISSUE TITLE
No .conf file for the default color scheme?

### ISSUE THREAD

**Issue by etkaar** [geany/geany#2718]
Is there no .conf file for the default color scheme of geany? In `geany/data/colorschemes` I was only able to find _alt.conf_.

It would be interesting what exactly is possible to change using a colorscheme.conf in `~/.config/geany`.

**Comment by codebrainz** [comment]
For historical reasons, the default colour scheme is in [filetypes.common](https://github.com/geany/geany/blob/d9f8cdbad58d09f0c18ca8acccb49209263018f0/data/filedefs/filetypes.common#L2).

**Comment by etkaar** [comment]
Thank you!
