### ISSUE TITLE
Can't see underscores in Linux Mint 20

### ISSUE THREAD

**Issue by crazyBaboon** [geany/geany#2722]
Using Linux Mint 20 (cinnamon edition), the underscores disappear. 

I can only see them when i zoom in or if i change the default font.

Thanks!

**Comment by abdulbadii** [comment]
It's a **Pinned Issue**, https://github.com/geany/geany/issues/2502

**Comment by crazyBaboon** [comment]
@abdulbadii , thanks but that issue is closed, but the problem is out there!

**Comment by elextr** [comment]
@crazyBaboon did you try the solution given in the pinned issue?

**Comment by elextr** [comment]
Duplicate of #2502
