### ISSUE TITLE
Question: Where are the "Send selection to"/Custom commands stored?

### ISSUE THREAD

**Issue by AdamDanischewski** [geany/geany#2735]
What config file if any stores the "Send selection to"/Custom commands? I have had my custom commands wiped out twice recently, not sure why maybe because of an update?

**Comment by elextr** [comment]
They are stored in your `~/.config/geany/geany.conf` which should not be changed by an upgrade.

As you have provided no information its not possible to help you further.

**Comment by AdamDanischewski** [comment]
It's not being stored there, using Geany 1.36 Using GTK+ v3.24.20 and GLib v2.64.3 runtime libraries. I stored a command for send input to Ctrl - 1, it is not found in the geany.conf file

**Comment by AdamDanischewski** [comment]
My bad guys - mine was located elsewhere and got overridden by something on my mach. Thanks
