### ISSUE TITLE
Geany not responding to certain keys

### ISSUE THREAD

**Issue by subtra3t** [geany/geany#2739]
Geany needs me to press the same key twice to register it once. Note that this only happens on certain keys, like comma or a period.

**Comment by codebrainz** [comment]
Hi @subtra3t, this looks like a duplicate of #1902, #2408, #2472, #2572. It's a good idea to search for existing same issues before posting a new one (I searched "comma" to find those issues), and also to give your operating system and version information.

Try out the solution in [this comment](https://github.com/geany/geany/issues/1902#issuecomment-643657889) and [this comment](https://github.com/geany/geany/issues/1902#issuecomment-661295362) for the fix.

If this is indeed a duplicate, please close it as #1902 is still open. If you have any problems with the solution or additional information to add, you can follow up on #1902 where people who have solved it are probably still getting notifications.

**Comment by subtra3t** [comment]
This does not seem to work for me. And I will close this.
