### ISSUE TITLE
Can't style the caret as the default in Kate

### ISSUE THREAD

**Issue by Digitalone1** [geany/geany#2744]
Hello. I used the Kate text editor by many years and in the last days I wanted to get rid of the last KDE dependencies on my system looking for a GTK alternative. 

Geany is a good text editor, some features are still missing compared to Kate, but I'm going to use it anyway. Unfortunately I'm getting some issues with the style configuration. I'm used to the Kate caret which is not a block by default. As I'm seeing in the documentation, it can be changed in Geany to look as a vertical line, but it's not working.

As stated [here](https://www.geany.org/manual/current/index.html#special-file-filetypes-common), I have to modify the `filetypes.common`.

> the file can be created manually, adding only the settings you want to change

Looking [here](https://www.geany.org/manual/current/index.html#id4) 

```
caret

    The style for coloring the caret(the blinking cursor). 
    Only first and third argument is interpreted. 
    Set the third argument to true to change the caret into a block caret.

    Example: caret=0x000000;0x0;false;false
``` 

But when I decomment the line and set `caret=0x000000;0x0;false;false`, nothing changes. Even if I change the caret width to 0, trying to make it invisible, the settings are not applied. Of course I loaded the new saved configuration, also tried to close and reopen the application, but it's the same.

It's very difficult to understand how to change this settings. Unfortunately also on this point Kate is better, even if having too many graphical preferences can lead to confusion.

Update: I'm using [upstream package](https://archlinux.org/packages/community/x86_64/geany/) on Arch Linux, DE: Gnome Wayland.

**Comment by elextr** [comment]
> I'm used to the Kate caret which is not a block by default. As I'm seeing in the documentation, it can be changed in Geany to look as a vertical line, but it's not working.

Strange that the cursor is a block, by default its a vertical bar, you havn't said what system you have and where you got Geany from or its version, which may say why its a block. [Ok, you added it while I was typing, know nothing about the Arch package, its not something this project makes]

When you made your `filetypes.common` did you include the section name above the `caret=` setting?

**Comment by Digitalone1** [comment]
> Strange that the cursor is a block, by default its a vertical bar, you havn't said what system you have and where you got Geany from or its version, which may say why its a block. [Ok, you added it while I was typing, know nothing about the Arch package, its not something this project makes]

Well, you can see [here](https://github.com/archlinux/svntogit-community/blob/packages/geany/trunk/PKGBUILD) how it's installed.

```
./configure --enable-gtk3 --enable-gtkdoc-header --prefix=/usr
sed -i -e 's/ -shared / -Wl,-O1,--as-needed\0/g' libtool
make
make -C $pkgname-$pkgver DESTDIR="$pkgdir" install
```
 
> When you made your `filetypes.common` did you include the section name above the `caret=` setting?

Sure. Seems like the config is not read or totally ignored (even if the status bar states _configuration file reloaded_)

![Schermata del 2021-02-03 12-28-07](https://user-images.githubusercontent.com/25790525/106740988-69cb1880-661b-11eb-96bf-0ae56c57f044.png)

**Comment by elextr** [comment]
What colour scheme are you using? Possibly it has set `caret=` as well. That would override `filetypes.common`.

**Comment by Digitalone1** [comment]
Yes, it was `dark.conf` colorscheme overriding the filetypes.

Changed it. Thanks.
