### ISSUE TITLE
[Solved] Zooming leads underscore to disappear at various zoom factors

### ISSUE THREAD

**Issue by aaal** [geany/geany#2759]
Hi, I encounter problems with printing underscores on my screen (a 32" with 2560x1440 pixels). At normal zoom factor, they do not appear, I need to zoom in 3 times to see them at last (see the 2 pics joined). I'm using Geany on Ubuntu 20.04 (fully up to date). My version of Geany is 1.36, and it is indicated "construit le Mar 22 2020 ou ultérieurement" and "Utilisant les bibliothèques GTK v3.24.20 et GLib v2.64.6". Maybe the bug is not present any more in the latest version, but I'm not sure I will be able to install and try it... Thanks for reading.
![Bug zoom   underscores Geany - Default zoom - Capture d’écran de 2021-03-08 16-12-04](https://user-images.githubusercontent.com/1187586/110341188-5f40dc00-802a-11eb-8a18-c3aa3786a32c.png)
![Bug zoom   underscores Geany - Zoomed in 3 times - Capture d’écran de 2021-03-08 16-12-20](https://user-images.githubusercontent.com/1187586/110341439-a038f080-802a-11eb-8161-c0f0607f34f0.png)

**Comment by dmaphy** [comment]
Please have a look at the pinned issue https://github.com/geany/geany/issues/2502

**Comment by aaal** [comment]
Thanks. I first missed it, but I read it since, and the line_height parameter does not do the trick, nor the font change to DejaVu Sans. I successfully got underscores back with ugly (to my humble personal opinion) Courier New Regular font. I'm currently searching for more comfortable fonts.

**Comment by aaal** [comment]
Ubuntu Mono Regular does the job. Sorry for the noise, I will try searching harder next time, I swear.

**Comment by aaal** [comment]
I missed https://www.geany.org/documentation/faq/#geany-does-not-display-underscores-anymore.
The line_height trick has not work with my 1.36 on Ubuntu 20.04. Changing font to Ubuntu Mono Regular worked.
