### ISSUE TITLE
geany doesn't detect certain function symbols depending on macro before it

### ISSUE THREAD

**Issue by lpcszLewis** [geany/geany#2763]
Hi, Im using geany 1.37.1 on Windows 10 Pro 64-bit. I did some searches for this issue and haven't found anything related. I have noticed that geany doesn't detect certain function symbols depending on what kind of macro is before it.
For Example:
detected - WINAPI AllocConsole(void);
not detected- WINAPI_(ULONG) GetCurrentProcessId(void);

i have included the screenshot of where GetCurrentProcessId() should be but isn't.
Thanks.
![image](https://user-images.githubusercontent.com/80648916/111091765-670cee80-850a-11eb-8a6e-f23d80c5eeea.png)

**Comment by elextr** [comment]
The symbol parsers do not read include files (presumably where your macro is defined) so they don't know its a macro and even if its local they don't get expanded.

Your example looks like `function(something) another_function(void)` which is incorrect syntax and so `another_function()` is not parsed as a symbol.

**Comment by lpcszLewis** [comment]
Ah that explains it then. I thought, after looking through symbol.c, it looked like geany might be using gcc to preprocess the file before parsing symbols but I didnt dig to deep. I suppose ill change my macros to the couple different cases where winAPI doesnt return int. Thanks for your reply.

**Comment by elextr** [comment]
The C preprocessor is used for the offline making of tag files that can combine a whole library of includes, not the as-you-type generation of symbols which has to be fast so its not intrusive.
