### ISSUE TITLE
Feature request: "Copy file path" in File menu or tab

### ISSUE THREAD

**Issue by 00cpxxx** [geany/geany#2770]
Hi, I'm looking for a way to copy the file path of the currently opened file either in the File menu or right-clicking the file tab name. I wonder if it is possible to do a plugin for that or if it requires a change in the core, or even if this feature already exists and I don't know where.

Why I need that?
To simplify attaching files to chats/emails where I finished the edition and to avoid browsing all the way inside the other program.

**Comment by elextr** [comment]
See https://plugins.geany.org/addons.html copy file path.

**Comment by 00cpxxx** [comment]
Feeling very stupid, sorry for the waste of time.
