### ISSUE TITLE
Can Geany be limited to a single instance?

### ISSUE THREAD

**Issue by 07416** [geany/geany#2777]
~~[`--no-new-instance`](https://github.com/geany/geany/pull/1128) can be passed from the shell, but it may not be possible to make use of the command with many file explorers for instance.~~

Is there a global setting to control this?

**EDIT**: Sorry, I forgot https://github.com/geany/geany/discussions

**Comment by elextr** [comment]
```
Geany: Unknown option --no-new-instance
```

There is no such option and it is the default to use the same instance unless `--new-instance` is passed.

**Comment by 07416** [comment]
> There is no such option and it is the default to use the same instance unless `--new-instance` is passed.

I see, Gnome doesn't appear to operate so.

**Comment by elextr** [comment]
@07416 what does Gnome have to do with it?

Also if you provided some information about your system and the version of Geany it might be possible to help you.
