### ISSUE TITLE
Scribble font configuration

### ISSUE THREAD

**Issue by JohnCC330** [geany/geany#2780]
Would it be difficult to have Scribble use the same font as the editor? Or make it configurable separately? I found some old references to this (2015/2019), but no real conclusion. I also looked into `geany.conf` but didn't any related parameters.
I just tried it out copying this (I'm a long-time geany fan, but never got around using scribble. Maybe is was because of this?)

    43:48:31:           CH1
    d8:f9:ff:ff:        -1576       -length of CHx data block (including itself)
    02:00:00:00:        2
    00:00:00:00:        0
    f8:02:00:00:        760

Which shows like:

![As shown in scribble](https://imgur.com/uBqJWgX.png)

The second column is supposed to aligned. Larger hex tables (or disassembly, or just code) look really ugly.

(Using `Geany 1.37`, `GTK+ v2.24.32` and `GLib v2.64.2`)

**Comment by elextr** [comment]
`Menu->Edit->Preferences->Interface->Interface->Fonts->Message Window` sets the font for all message window tabs including scribble.

**Comment by JohnCC330** [comment]
@elextr : Thanks! I (wrongly) interpreted 'Tabs' as referring to the tab labels not the tab's corresponding contents. Anyway, it's "all message window tabs *except the terminal*", which still uses its proper font.

**Comment by elextr** [comment]
> except the terminal", which still uses its proper font.

`Menu->Preferences->Terminal->Terminal->Font`
