### ISSUE TITLE
Not actual version of Geanie in Ubuntu repository

### ISSUE THREAD

**Issue by mdziczkowski** [geany/geany#2783]
I have a question. Does anyone know who provides the actual version of Geany for the Ubuntu repository and/or eventually maintanance it?

**Comment by elextr** [comment]
The Geany package for Ubuntu says "Ubuntu Developers".  

From your title I guess you are concerned that Ubuntu has 1.36 when Geany is 1.37?  That is likely just due to timing, the Geany release of 1.37 in November was just after Ubuntu in October , and Ubuntu does not change versions after release, but hopefully the next release 21.04 will include Geany 1.37 (and plugins collection).

**Comment by mdziczkowski** [comment]
I use a distribution called "FossaDog", with is a connection of Puppy Linux and Ubuntu (fossa) as a LiveUSB.

In it, the latest avaliable version is shown as 1.28-2, even if there is a newer version avaliable.

Ahead of your possible nex question: no, I can't update it to the groovy version because to sucessfully do that, I would need to install it into a hard drive, and, I don't know why, it appeared some strange bootloader issue (with got reported), with makes impossible to boot the installed system, plus there is no newer ISO then the one I had used to make the LiveUSB

**Comment by elextr** [comment]
Well I said all Linux distros are different, and that one is definitely "different" :smile:.  It shows the diversity that makes it impossible for us to provide binaries for all Linuxes.  

The thing is I think you are expecting something that neither Puppy nor Ubuntu offer, upgrading versions of software in existing releases, all they offer is critical bugfixes, not new versions.  And the fact that this particular distro hasn't made a newer release and ISO is not something you should expect Geany or other projects to compensate for.

To get a continually updated distro you need whats called a "rolling" distro that continuously updates things (and occasionally breaks stuff by doing so, thats the tradeoff).  But that as a USB stick I don't know of one.

But its not anything thats a Geany issue, so closing.
