### ISSUE TITLE
The Find and the Replace [ignore case] setting is swapped

### ISSUE THREAD

**Issue by BLH2021** [geany/geany#2787]
(I'm running a Danish version and the English terms may not be precise)

In the Find and the Replace dialog, the [Ignore case] setting is swapped. If I choose to ignore, the case is important and vice versa.

    Geany:
"Poliff"
build 2020-03-22 or later
with libraries GTK+ v3.24.20 and GLib v2.64.6

    OS:
Linux Mint Cinnamon 20

    Computer (my PC is almost 4 years old):
Intel Core i3-7100 Prozessor
Intel HD-Grafik 630
8 Gbyte ram DDR4
120 Gbyte SSD harddisk
1 Tbyte harddisk - Toshiba DT01ACA100
Netcard: 802.11 ac

**Comment by BLH2021** [comment]
I forgot to sign with my name: Bertel Lund Hansen

**Comment by elextr** [comment]
It works correctly in English (if you mean the "Case sensitive" checkbox), so its probably the translation.  Look in https://github.com/geany/geany/blob/master/po/da.po and check, you can search that for the Danish to see the English when reporting.
