### ISSUE TITLE
Highlight function in symbol window not work

### ISSUE THREAD

**Issue by zipotron** [geany/geany#2790]
Hello, I noticed that symbol window shows all the functions (an other symbols) list, with the declaration line number. I miss to see highlight the function where my cursor is. I am a C developer, but not familiar with Geany code, but if you point me where I can find the code is showing the symbol windows with pleasure I would like to contribute and fix it myself.

**Comment by elextr** [comment]
Duplicate of #1348

**Comment by zipotron** [comment]
Thanks!
