### ISSUE TITLE
Very slow opening of files in project with many files, eventual freeze

### ISSUE THREAD

**Issue by sdekrijger** [geany/geany#2791]
I've updated from 1.34 to 1.37.1 (Windows 7) and noticed very slow loading of the open files in a project consisting of many (around 100) files, each file is loaded one-by-one, taking longer and longer until Geany stops responding. I've checked with 1.36 and it has the same kind of issue except files open a little bit faster and there is no freeze. I've returned to 1.34 for now which loads files almost instantly.

**Comment by elextr** [comment]
Duplicate of #2649 fixed by #2747 will be in next release "soon".
