### ISSUE TITLE
geany-debugger Problem!!

### ISSUE THREAD

**Issue by Mauricho** [geany/geany#2796]
Hola, soy un usuario relativamente nuevo en Geany por lo que mucho de lo que conozco lo aprendí hace muy poco tiempo.
Y estoy teniendo problemas, con el debugger de Geany, yo utilizo Ubuntu 20.04.2 LTS en una notbook de 64 bits.
He intentado instalar el plugin debugger desde Synaptic y no me aparece, tambien ejecute el siguiente comando en la consola: 
sudo apt-get install geany-plugin-debugger
Y me sale el siguiente mensaje: 
E: No se pudo obtener un bloqueo /var/lib/dpkg/lock-frontend. Lo mantiene el proceso 12657 (synaptic)
N: Tenga en cuenta que eliminar el archivo de bloqueo no es una solución y puede dañar su sistema.
E: No se pudo obtener el bloqueo de la interfaz dpkg (/var/lib/dpkg/lock-frontend). ¿Hay otro proceso utilizándolo?

Como para concluir quiero instalar, el plugin debugger en Geany pero no estoy pudiendo.
Desde ya muchas gracias, y disculpe las molestias.

**Comment by elextr** [comment]
Please leave all comments in English

**Comment by Mauricho** [comment]
Hi, I am a relatively new user to Geany so much of what I know I learned very recently.
And I am having problems, with the Geany debugger, I use Ubuntu 20.04.2 LTS on a 64-bit notbook.
I have tried to install the debugger plugin from Synaptic and it does not appear, also run the following command in the console:
sudo apt-get install geany-plugin-debugger
And I get the following message:
E: Could not get a lock / var / lib / dpkg / lock-frontend. Maintained by process 12657 (synaptic)
N: Please note that removing the lock file is not a solution and may harm your system.
E: Failed to get the dpkg interface lock (/ var / lib / dpkg / lock-frontend). Is there another process using it?

As a conclusion I want to install the debugger plugin in Geany but I am not able to.
Thank you very much in advance, and sorry for the inconvenience.

**Comment by elextr** [comment]
> E: Could not get a lock / var / lib / dpkg / lock-frontend. Maintained by process 12657 (synaptic)
> N: Please note that removing the lock file is not a solution and may harm your system.
> E: Failed to get the dpkg interface lock (/ var / lib / dpkg / lock-frontend). Is there another process using it?

This has nothing to do with Geany, it is a basic function of the system that you can't run two install processes at the same time.
