### ISSUE TITLE
Markdown syntax highlighting confused by empty image title

### ISSUE THREAD

**Issue by r0polach** [geany/geany#2798]
Geany's markdown syntax highlighting (without the markdown plugin) is confused, when image link without title is used:
```
  ![](media\image21.png)
```
All the following text is highlighted bold (same as the link itself).
![md1](https://user-images.githubusercontent.com/1393254/109849915-38615f00-7c52-11eb-9185-7f63af7c3b81.png)
Also the following markdown syntax is ignored - see ```*Obecné*``` is not in italics.

When I fill in some title to image link
```
  ![abc](media\image21.png)
```
then the highlighting became correct (i.e. only link itself is bold).
![md2](https://user-images.githubusercontent.com/1393254/109849989-4b742f00-7c52-11eb-90d3-83d4109e5f25.png)
Also the following markdown syntax is ok then (*```*Obecné*```* **is** in italics).

The correct behavior is to highlight bold only the link even if its title is empty.

**Comment by rdipardo** [comment]
Patched in Lexilla (i.e., the lexer library split from Scintilla in 5.0.0): https://github.com/ScintillaOrg/lexilla/commit/feb225e72d094531f1bf9148646cd0a177f75200

**Comment by elextr** [comment]
Will come with Scintilla 5 when it stabilises and Geany is updated to use it.

**Comment by rdipardo** [comment]
@eht16, @elextr

This issue can be closed as fixed in the forthcoming Geany.

![Screenshot_2023-10-15_17-11-08](https://github.com/geany/geany/assets/59004801/ece88b02-7ee5-49ba-aeca-31b29e1f5de1)
