### ISSUE TITLE
geany can't open folder

### ISSUE THREAD

**Issue by wujilingfeng** [geany/geany#2801]
I want to view directory tree of one folder just like sublime, but geany doesn't support.

**Comment by elextr** [comment]
If you have a feature request you need to describe it properly, just referencing another tool is lazy and requires people to install another tool to find out what you want.

**Comment by wujilingfeng** [comment]
I'm sorry. I want to view a directory in the left sidebar when i drop a folder to the software.

**Comment by wujilingfeng** [comment]
> If you have a feature request you need to describe it properly, just referencing another tool is lazy and requires people to install another tool to find out what you want.
