### ISSUE TITLE
Please add syntax highlighting support for Component Pascal

### ISSUE THREAD

**Issue by CretinHo** [geany/geany#2806]
The language is here:

https://github.com/k-john-gough/gpcp

You could find the preference there, too.

Currently Geany only supports Pascal's .pas source file but not Component Pascal's .cp source file.

**Comment by elextr** [comment]
You can edit the `filetypes_extensions.conf` file yourself `Menu->Tools->Configuration Files->filetypes_extensions.conf` to add `.cp` to the Pascal extensions.
