### ISSUE TITLE
Update Search for: <keyword-value> when user hits Ctrl+h with exisiting Replace dialog already open

### ISSUE THREAD

**Issue by Keyikedalube** [geany/geany#2808]
Suppose we have a lengthy C code and want to refactor existing variable names:
```c
...
    int x_value, y_value;
...
```
1. Double click `x_value` and press `Ctrl+h`
2. Resize dialog opens with `x_value` set as **Search for:** keyword value
3. Leave the dialog open
4. Now double click `y_value` to highlight it and press `Ctrl+h`
5. Resize dialog is brought back to focus but the **Search for:** keyword isn't updated

I'd like step 5 to update the keyword value with new highlighted value from the editor.

The reason I leave the dialog open is because I want to keep track of the recent keyword that I just replaced without having to undo and redo again when I forget the last changes made to the document.

**Comment by elextr** [comment]
The search dialog was updated to do this in #2697 (after _much_ discussion on that and other issues/PRs) so having replace work the same should be fine if somebody wants to do it.

**Comment by erickpaquin** [comment]
@Keyikedalube , @elextr  Can this change be closed?

**Comment by elextr** [comment]
Yeah, I didn't notice that #2697 did the replace dialog as well.
