### ISSUE TITLE
Geany freezes after saving a file, Kali Linux

### ISSUE THREAD

**Issue by Ahmed-Abdeldayem** [geany/geany#2812]
geany 1.37.1 (built on Nov 13 2020 with GTK 3.24.23, GLib 2.66.2)
Linux kali 5.10.0-kali3-amd64 #1 SMP Debian 5.10.13-1kali1 (2021-02-08) x86_64 GNU/Linux

Using 'Kali Linux', I don't know why after almost every time I save a file(usually Python) or run it(which saves and then runs) Geany freezes for about 2 seconds, and what I mean by 'freezes' is literally freezes, can't move the mouse cursor or write any thing or navigate to another file(No matter how I installed it ,usually using apt , even tried many times to fully uninstall and remove all of its files and then reinstall , with no use).

I don't know if the problem is with Kali more than with Geany, but I would appreciate any help cause just imagine that I have been using PyCharm and  VS Code, but after finding Geany it became by far my favorite and most used editor , but with that extremely annoying bug 'Geany on Kali Linux' it lead me to uninstall Geany for some time.

I do love Geany, such amazing app with just a few megabytes , thanks so much Geany developers and contributors

**Comment by elextr** [comment]
try `geany -c /tmp/non-existant` and then and then open modify and close a file that freezes in normal use.

Also is it #2737? Try all the things there. Or #2658 and try the things there.

**Comment by Ahmed-Abdeldayem** [comment]
Thanks a lot elextr I'm truly grateful.

To conclude:
-Yes indeed ALT+TAB , the Window button or whatever exit Geany screen even for a moment unfreezes for just that time and then come back , of course not a solution
-What is quite acceptable as a solution is using Geany in windowed mode, whatever the window size but NOT a maximized screen
-I didn't try using wayland instead of X11, as my video card is Nvidia , using Kali Linux which usually harder , it would give me a headache
-*- What actually worked and smoothly is what shivensinha4  suggested at #2727  > Wandering Pixel > https://extensions.gnome.org/extension/4028/wandering-pixel/
after enabling the extension, instantly, Geany works just fine, did not see any freeze so far  ( Can easily be controlled , enable or disable)

Thanks again elextr, you are life-saver
