### ISSUE TITLE
Please tell me how to set a short cut key for 

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#2821]
Please tell me how to set a short cut key for the highlighted menu item?  Thanks! 

![image](https://user-images.githubusercontent.com/7548378/121030052-09064500-c7a1-11eb-870d-661e9f72ee7d.png)

**Comment by elextr** [comment]
As you currently have it laid out its not see the [manual](https://www.geany.org/manual/current/index.html#build-menu-keyboard-shortcuts)

But if you used one of the execute commands for execute you would have one spare compile command for upload that can get a keybinding.

**Comment by ntrel** [comment]
Duplicate of #705.
