### ISSUE TITLE
geany yum install in CentOS 7 fails to run with undefined symbol: gdk_wayland_display_get_type

### ISSUE THREAD

**Issue by Alchete** [geany/geany#2828]
CentOS 7 yum install of geany.x86_64 0:1.36-2.el7 does not flag any external dependencies but the binary fails to run with:

"undefined symbol: gdk_wayland_display_get_type"

**Comment by elextr** [comment]
You will need to discuss it with whoever makes the yum packages, the Geany project doesn't make any distro packages and a call to `gdk_wayland_display_get_type` does not exist in this repository.
