### ISSUE TITLE
application choke at every action, typing code, pasting, moving between pages, saving, you name it

### ISSUE THREAD

**Issue by raspi-four** [geany/geany#2833]
Geany 1.36
Ubuntu 20.10
Page sizes < 10Kb
Really bad performance. I must wait any where from 1 to 30 seconds before the app allows me to before the next task. It worked great on Linux Mint. This is a fresh install of Ubuntu within the last month.

**Comment by elextr** [comment]
Likely duplicate of #2658 #2665 and others.  Please try the things suggested there, especially `GDK_BACKEND=wayland geany`

**Comment by raspi-four** [comment]
Thanks, but I moved to another IDE.
