### ISSUE TITLE
Editor tab headers in Windows: is it possible to highlight active tab?

### ISSUE THREAD

**Issue by DimTim-1963** [geany/geany#2834]
In Windows, especially when many editor tabs are open, almost impossible to see which tab is now active.  Is it possible to make the active tab header stand out visually?  Different background color, bold text or something?  Even capitalize will do, if nothing else possible. :)

![Clipboard-1](https://user-images.githubusercontent.com/83489923/123500545-878b2f80-d647-11eb-89ea-37e3ab7e707c.jpg)

Here "fisc.c" is active, but it's hard to tell.

**Comment by elextr** [comment]
AFAIK it is controlled by the GTK theme, not by Geany, so you can probably manipulate that with gtkrc if its gtk2 and css if its gtk3.

**Comment by DimTim-1963** [comment]
Yes, there is a **gtkrc** file here: "C:\Program Files (x86)\Geany\share\themes\MS-Windows\gtk-2.0\gtkrc".  Will try to dig it. :)

**Comment by elextr** [comment]
Try the GTK2 manual if you can find it, seems to have disappeared since GTK4 came out.

**Comment by DimTim-1963** [comment]
Found a custom style here: https://github.com/ndwarshuis/BlackIce/blob/master/gtk-2.0/geany.gtkrc  Already looks better.  Will try to improve it for my taste. :)
**elextr**, thanks for right search direction!

**Comment by elextr** [comment]
@DimTim-1963 NP

I will however take umbrage at the link above claiming we "hard coded" monospace.  The default is monospace, but if its hard coded then why is there `Menu->View->Change Font` for the editor and `Menu->Edit->Preferences->Interface->Interface` having three font setting selectors?  The user can select to use the system font in those if they want the theme to control it (at least here on Linux, on Windows YMMV).

[End grumble]

**Comment by DimTim-1963** [comment]
Agree. :)  Still, the more configurability, the better.  At least for my taste.  And, BTW, Geany ignores lines like **bg[ACTIVE]** and **bg[NORMAL]**, and there is no style selector for default tabs (not changed, not read only etc).  And yes, no option to use system fonts for menus etc in Windows...
Anyway, thanks for good editor!  Yes, there are mighty IDEs like VS Code or Sublime, but they are bloated and even don't support virtual space!  O tempora, o mores...

**Comment by elextr** [comment]
I should perhaps have pointed out earlier (sorry) so you don't spend _too_ much time perfecting it, that the next release for Windows will use GTK3 and so use CSS style themes.

**Comment by DimTim-1963** [comment]
Good news, thank you!  CSS is standard, easier to handle.
