### ISSUE TITLE
The selection count in utf8 on Geany 1.36 on Kubuntu 20

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#2836]
The selection count in utf8 on Geany 1.36 on Kubuntu 20 is incorrect:

![image](https://user-images.githubusercontent.com/7548378/124332991-de828e80-db8a-11eb-96aa-ad9b1808663a.png)

**Comment by elextr** [comment]
Those look like Serif Italic Mathematical letters, Unicode U+1D434 and on, each of which is encoded in UTF-8 as four bytes, hence the selection is 8 bytes.
