### ISSUE TITLE
Windows: Geany doesn't redraw its canvas after start.

### ISSUE THREAD

**Issue by DimTim-1963** [geany/geany#2837]
When I start Geany, and then switch to another window and back, Geany stops redrawing its canvas, I see only the empty OS frame with underlying content:
![image](https://user-images.githubusercontent.com/83489923/124418343-efd2c300-dd63-11eb-959b-7759dedd5422.png)
Then, if I slightly resize the window, or maximize/normalize, it redraws itself, and after that works fine - until the next restart. :)  Must be a GTK problem?

BTW, how can I install a nightly build under Windows?  It doesn't work, complains at missing functions in libs.  Tried to install MSYS2, but it doesn't work either. :)

Geany: 1.37.1.
OS: Windows 7 64 bit Ultimate, QHD display (2560x1440), scaling 150%.

**Comment by elextr** [comment]
> Must be a GTK problem?

Likely.

> BTW, how can I install a nightly build under Windows?

The `ReadMeNightly.txt` file gives instructions, but basically the nightlys are not full releases with installer, they are just test builds, so they have to be unzipped over an existing installation.

**Comment by DimTim-1963** [comment]
> ...basically the nightlys are not full releases with installer, they are just test builds, so they have to be unzipped over an existing installation.

Yes, I know.  I did so - doesn't work.  Complains at missing DLLs or functions in DLLs.

**Comment by elextr** [comment]
Might help if you posted the error messages.

**Comment by DimTim-1963** [comment]
The first one is this:
![image](https://user-images.githubusercontent.com/83489923/124539893-01c96a00-de27-11eb-9ae0-3aeaea31ccd5.png)
I found one in Tor Browser binaries, copied it to Geany\bin.  Then next error appeared:
![image](https://user-images.githubusercontent.com/83489923/124540295-cd09e280-de27-11eb-8a9b-231313c3ca72.png)
Tried to find something like that, but on my system there are 16 such files, all different. :)  Tried the one from Mingw - didn't work (the same error).  Others are mainly 64-bit.  Anyway, how do I find the necessary library, if the name is the same, but functions inside are different?

**Comment by elextr** [comment]
Possibly the version of MSYS and its libraries changed when the windows nightlys went to GTK3. 

Umm, that brings up another point, AFAIK there have been no releases for Windows with GTK3, 1.37.1 is GTK2 AFAICT, but the nightlys are GTK3, so they can't simply be untared on that release.  So what are you "installing" them on?

**Comment by DimTim-1963** [comment]
Yes, exactly!  The last Windows release is based on GTK2.  Well, seems, users like me must wait for official GTK3 release. :)  For now the editor works, and such bugs can be worked around.

**Comment by eht16** [comment]
JFTR: the current nightly builds for Windows are not compatible with the releases (as you already noticed).
I don't think there is any combination of randomly chosed DLL files to make it work, the nightly builds are cross compiled and also with a different toolchain than the release builds.

I hope I will manage to finish a new nightly build setup which can create full installers (GTK3 based), so it would be easy to use or test a nightly build.
