### ISSUE TITLE
geany-addons won't install via chocolatey since the geany version doesn't match.

### ISSUE THREAD

**Issue by poikilos** [geany/geany#2849]
OS: Windows 10

Result of `choco install -y geany-plugins` after installing Geany the same way:
```
Chocolatey v0.10.15
Installing the following packages:
geany-plugins
By installing you accept licenses for the packages.
Progress: Downloading geany-plugins 1.37... 100%

geany-plugins v1.37 [Approved]
geany-plugins package files install completed. Performing other installation steps.
File appears to be downloaded already. Verifying with package checksum to determine if it needs to be redownloaded.
Hashes match.
Hashes match.
Installing geany-plugins...
WARNING: Setup was cancelled.
ERROR: Running ["C:\Users\Jatlivecom\AppData\Local\Temp\chocolatey\geany-plugins\1.37\geany-plugins-1.37_setup.exe" /S ] was not successful. Exit code was '2'. Exit code indicates the following: Setup was cancelled..
The install of geany-plugins was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\geany-plugins\tools\chocolateyinstall.ps1'.
 See log for details.

Chocolatey installed 0/1 packages. 1 packages failed.
 See the log for details (C:\ProgramData\chocolatey\logs\chocolatey.log).

Failures
 - geany-plugins (exited 2) - Error while running 'C:\ProgramData\chocolatey\lib\geany-plugins\tools\chocolateyinstall.ps1'.
 See log for details.
```

If I manually install Geany 1.37 from https://download.geany.org/ then install geany-plugins using chocolatey, the `choco install -y geany-plugins` command automatically upgrades geany to 1.37.1 and installs geany-addons a second time, resulting in the same error and the plugins are not installed.

Note that Chocolatey seems to be the only way to get geany-plugins (<https://plugins.geany.org/install.html> seems to confirm that):
- [ ] I had a hard time finding it since entries in the Geany plugin registry for plugins in geany-plugins (such as <https://plugins.geany.org/spellcheck.html>) don't point to the plugin install URL: https://plugins.geany.org/install.html
  - I tried at least 3 other times, once a few weeks ago or so and more times years ago, and never found the plugin install URL until this time. It was on Bing (down a few in the list) for the following search (I didn't try Bing nor this search the other times):  how install geany plugins for windows

- [ ] Running the geany-plugins install file manually from Windows Explorer reveals a warning dialog that warns that problems will occur if geany-plugins is installed since it is version 1.37 and Geany is 1.37.1. 
  - [ ] This is apparently what prevents silent install, but I actually get an error if I manually use the /S switch:
```
"C:\Users\Jatlivecom\AppData\Local\Temp\chocolatey\geany-plugins\1.37\geany-plugins-1.37_setup.exe" /S
At line:1 char:102
+ ... l\Temp\chocolatey\geany-plugins\1.37\geany-plugins-1.37_setup.exe" /S
+                                                                         ~
You must provide a value expression following the '/' operator.
At line:1 char:102
+ ... l\Temp\chocolatey\geany-plugins\1.37\geany-plugins-1.37_setup.exe" /S
+                                                                         ~
Unexpected token 'S' in expression or statement.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ExpectedValueExpression
```
  - Note that running install from PowerShell (Admin) without the `/S` switch does nothing (neither shows output nor appears nor installs).
  - Note that `choco install -y geany --version 1.37` doesn't work because the version is not on chocolatey (therefore the dependency chain for geany-plugins-1.37 is broken)

## Workaround
1. Install geany-plugins using chocolatey (allow the install to fail, but note the location of the installer in Temp)
2. Uninstall Geany
3. Install Geany 1.37 from https://download.geany.org/
4. Install the temporary file that step 1 produced: "%LOCALAPPDATA%\Temp\chocolatey\geany-plugins\1.37\geany-plugins-1.37_setup.exe"

**Comment by elextr** [comment]
@poikilos the latest versions of Geany is 1.37.1 and plugins is 1.37, so the problem is in the packaging.  This project doesn't make packages, so you need to raise an issue with whoever does.

**Comment by elextr** [comment]
I should add that since Geany 1.37.1 is to fix a crash on some Windows systems its important that version is used, not 1.37.
