### ISSUE TITLE
yaru-theme-icon package requirement missing

### ISSUE THREAD

**Issue by XChikuX** [geany/geany#2852]
Geany requires:
sudo apt install yaru-theme-icon

To be run so there are no warning messages during X11 forwarding.
Eg.
(geany:146): Gtk-WARNING **: 12:50:49.000: Error loading theme icon 'document-new' for stock: Icon 'document-new' not present in theme Yaru

Geany 1.36
Using GTK+ v3.24.20 and GLib v2.64.6 runtime libraries

**Comment by elextr** [comment]
"Icon 'document-new' not present in theme Yaru" what the message says, the theme is incomplete.
