### ISSUE TITLE
Color scheme not spreading to whole window

### ISSUE THREAD

**Issue by Parn23** [geany/geany#2853]
After selecting a color scheme (a dark one in this case) the scheme only takes effect on the editor, where I want it to spread across the whole window, as shown [here](https://geany.org/media/uploads/screenshots/geany_dark_2019-05-20.png). Attached below is an image of my current color scheme configuration.
![image](https://user-images.githubusercontent.com/77811207/126881179-e21c0a10-38ed-4c7f-96fa-57b641c4e577.png)

**Comment by elextr** [comment]
Correct, the theme for the standard UI objects is set by the desktop theme.  The Geany colour scheme sets the colours for the syntactic entities in the editor since they are unlikely to be set by the desktop.
