### ISSUE TITLE
Invisible umlaut dots with font Hack and font size 10

### ISSUE THREAD

**Issue by radioactiveman** [geany/geany#2854]
**Bug description**

Geany does not show the two dots on Umlaut characters like Ä Ö Ü when using the font [Hack](https://github.com/source-foundry/Hack) with font size 10.
Only this size and only capitalized characters are affected.

Other applications like a xfce4-terminal or LibreOffice show the dots with the same font and font size.
Is Geany responsible for the font rendering? May this be a bug in Scintilla?

**Screenshots**

Default settings
![Dots-missing](https://user-images.githubusercontent.com/1301412/126917642-bdbb358c-e220-4a07-a392-80086185a91c.png)

Increased line heights
![Dots-visible](https://user-images.githubusercontent.com/1301412/126917650-c09b72c3-28df-47aa-bd1f-c4ae590858b7.png)

**System**
- Arch Linux
- Geany 1.37.1
- GTK 3.24.24
- ttf-hack 3.003

**Workaround**
Increasing the line height (see [FAQ](https://www.geany.org/documentation/faq/#geany-does-not-display-underscores-anymore)) or using another font helps.

**Comment by elextr** [comment]
Same problem as #2502 pinned issue.

Just for the record I use Hack 10 pt and all the dots show with default settings with a 27" QHD screen but are fainter than 9 or 11 pt indicating that they are partly cut off.  

As explained in the multitude of duplicates of the issue it depends critically on the relationship of points (1/72 inch so an actual size) and screen resolution in pixels per inch on your screen and which way the calculation rounds when converting from floating point fractions of an inch that the font is defined in, to integer pixels on the screen.  Sometimes it rounds down and cuts stuff off, but only on some screens with some font sizes.

At some time in the future a change to the way Scintilla does the rounding may help, but it also may just shift the problem to a different combination of fonts, sizes and screen resolutions, YMMV.  This version has just stabilised, and has significant changes so it may be a while before it gets included in Geany.

Until then the workaround is the correct solution.
