### ISSUE TITLE
tab splitting

### ISSUE THREAD

**Issue by netpipe** [geany/geany#2857]
would like tab splitting / state saving like in codeblocks. i was the developer who came up with the idea for codeblocks.

https://github.com/netpipe/ProIDE/tree/main/Qt i am currently freelancing this version in c++ aswell.

to try it open codeblocks and then get a few tabs open then drag one into a new splitter.

**Comment by elextr** [comment]
Describing features by "Install and open a different IDE and try it" is the height of lazyness, asking others to do the work for you.  Also the C++ IDE advertisement has gotten your post hidden.

**Comment by netpipe** [comment]
well i dont know python well, so i guess thats where it stays unless someone wants to freelance it then.

**Comment by netpipe** [comment]
i think its more that you have 768 other issues currently wrong with it.
