### ISSUE TITLE
GTK 3-ify the Glade file

### ISSUE THREAD

**Issue by elextr** [geany/geany#2860]
When geany.glade is opened in a modern Glade there is a message that it should be checked in Glade 3.8 for deprecated widgets.

Can "somebody" who has Glade 3.8 please check it and post the results so it can be upgraded now GTK 2 is no longer supported.

**Comment by rdipardo** [comment]
For what it's worth, a quick check with glade 3.8.6 found perfect compliance up to and including GTK 2.16:

![GTK+-2 16-OK](https://user-images.githubusercontent.com/59004801/128976372-3f3deb74-211c-4dac-ae10-16c9e857623c.png)

You have to dial back to 2.14 before anything comes up:

![GTK+-2-14-DEPRECATED](https://user-images.githubusercontent.com/59004801/128977202-a32a419f-c1c6-4161-a7f8-353c2bd4a1dc.png)

To reproduce:

1. Fetch a glade-3.8.6 tarball from [here](https://download.gnome.org/sources/glade3/3.8/)

2. Install with:

~~~
sudo apt install libgtk2.0-dev libxml2-dev itstool

 ./configure --prefix=/usr/local \
    --enable-debug=yes \
    --enable-maintainer-mode \
    --disable-gtk-doc-html

make -j4 && sudo make install
~~~

3. Check out 90c6096ed6ea167f9100ce8f74229a3f47acc29a and open `data/geany.glade`

4. Go to Edit > Preferences and run the validator for toolkit version 2.14 (anything later should pass)

5. Check the diagnostics against this list:   [GTK+-2.14.deprecations.log.txt](https://github.com/geany/geany/files/6966154/GTK%2B-2.14.deprecations.log.txt)

**Comment by elextr** [comment]
Thanks.

The one thats important is 2.24 since that "should" have all the GTK-2 deprecations that GTK-3 will remove.  So if its fine there should be ok.

Probably shouldn't be touched until after the next release which is to be soon-ish.  Then it can be re-saved from a current Glade and see what happens :)

**Comment by kugel-** [comment]
Why wait? The next release will only support GTK3, might as well get geany.glade into best shape for GTK3 at the same time.

**Comment by elextr** [comment]
Just to avoid introducing new bugs because it might not get heavily tested pre-release thats all.  With our current manpower limitations its good to avoid having to make a 1.38.1 :-)

**Comment by kugel-** [comment]
I thought the GTK3-only release would be called 2.0

**Comment by elextr** [comment]
Well, this release would have been just a bugfix and some minor additions, might even have been 1.37.2 except "somebody" merged the removal of GTK2 in the meantime :grinning:  

So its gonna be GTK3 only, but that means the windows build needs updating, which is where the holdup is.  

Since not much has changed (after all Geany was GTK3 for ages) it seems 1.38 would be the thing to call it, why tie the Geany version to the version of some mere tool that it uses?  

Back on the topic, I saved geany.glade out of Glade 3.22 and did a diff, most of the changes are minor reorderings, but there are some properties removed, I overwrote an installed geany.glade and Geany starts without errors, but I am not using Geany much ATM to check if all of the GUI works (all of preferences etc) as it used to, any contributions welcome.

**Comment by rdipardo** [comment]
> @elextr, The one that[']s important is 2.24  . . . 

Just confirming it's all square with the 2.24 spec, as of the last revision at e390377:

![GTK+-2.24](https://user-images.githubusercontent.com/59004801/129128927-526f7f5e-8aad-439b-a744-a2d682d8375f.png)

**Comment by elextr** [comment]
@rdipardo thanks

**Comment by erickpaquin** [comment]
@elextr , can this PR be closed?
