### ISSUE TITLE
Geany forcefully saves project session

### ISSUE THREAD

**Issue by drws** [geany/geany#2864]
Geany currently constantly updates `.geany` project files with no option to choose in which state to save the session (and consequently also have an ability for project-wise presets/defaults). This is leading to issues such as #2304 and #2863.

This is a feature request for additional global option under `Preferences > General > Miscellaneous > Projects` so one can disable session autosaving and also add a manual option to do so, probably something along the lines of `File > Save Project`.

Also: Another option in the category _Use project-based session files_  disables using `.geany` files altogether and is not helpful in the case.

**Comment by elextr** [comment]
see comments on #2863

**Comment by drws** [comment]
Based on comments from #2863, the previous behaviour can be restored by the `files.save_config_on_file_change` setting, so this issue is now solved.
