### ISSUE TITLE
Long Line Marker Issue

### ISSUE THREAD

**Issue by tn5421** [geany/geany#2886]
I am currently running Geany 1.36 on Linux Mint 20.2 Cinnamon Edition. 

It seems that the column size doesn't scale properly, or possibly at all, when you change your font size or font face.

I changed my editor font to Ubuntu Regular 14pt and found that the drawn line from Long line market, set at 72 columns, drew the line at 32 characters, give or take.

I am new to geany and bug reporting in general, so I apologize in advance if this is a duplicate, is expected behavior, or is otherwise an invalid report.

**Comment by eht16** [comment]
The long line marker can only be displayed properly when using a fixed width font, i.e. a monospace font.
For all other font types, each columns might have a different width and so there is no fixed vertical line possible across multiple lines.

If you choose a monospace font, I assume the long line markers looks like you expected. If not, please re-open.

**Comment by elextr** [comment]
Ubuntu regular is not a monospaced font, so there is no specific pixel position to draw a vertical line that is the same column in all lines, it depends on the content of the line.  IIRC the position used is a line of spaces which will compress in a non-monospaced font.

If you really want to use a non-monospaced font and still want long line indication, then set the long line to background (Preferences->Editor->Display) which is something that can be shown differently for each text line.
