### ISSUE TITLE
Option to wrap searching / replacing around the document

### ISSUE THREAD

**Issue by vsl7** [geany/geany#2887]
It would be better to add to the search and replace dialog an option whether to wrap around the document (continue from the beginning when the end is reached and vice versa). Asking it each time is inconvenient and makes Geany unusable.

**Comment by eht16** [comment]
We already got that feature: enable "Always wrap search" in the preferences dialog.

![geany_always_wrap_search](https://user-images.githubusercontent.com/617017/132094182-397f30df-2423-457e-aaaa-107bc85824f0.png)

**Comment by vsl7** [comment]
@eht16 That’s right. I was looking through all settings and didn’t recognize this option because of its incorrect Russian translation: “Всегда искать с начала файла”. Correct would be “Зацикливать поиск по документу”. Another problem is that there is no obvious way to change UI language in Geany.

**Comment by elextr** [comment]
The developers of the GTK GUI library Geany uses (and indeed the C language it uses) have in their wisdom decided that programs must always follow the locale set by the LANG environment variable and do not allow program control.  The concept of wanting, for example, an IDE in English to match the programming language, not the users local dialect is not catered for.   Blame the ISO C folks. [end rant]

Therefore you need to set the `LANG` environment variable before you run Geany.  So on Linux you run Geany with:

```
LANG=en_GB.UTF-8 geany
```

I note that the new GTK4 version allows that hard coded automatic to be turned off so the program can set its language to something different to the system setting.  So after somebody made the (major) patches to support GTK4 it might be possible  to have a setting in Geany, although it would probably need a restart to take effect.
