### ISSUE TITLE
warning: explicitly defaulted move constructor is implicitly deleted

### ISSUE THREAD

**Issue by rootkea** [geany/geany#2891]
Hello!

On latest master `clang` throws these warnings:
```
In file included from src/ViewStyle.cxx:26:
./src/Style.h:76:2: warning: explicitly defaulted move constructor is implicitly deleted [-Wdefaulted-function-deleted]
        Style(Style &&) = default;
        ^
./src/Style.h:71:12: note: move constructor of 'Style' is implicitly deleted because field 'font' has a deleted move constructor
        FontAlias font;
                  ^
./src/Style.h:38:2: note: 'FontAlias' has been explicitly marked deleted here
        FontAlias(FontAlias &&)  = delete;
        ^
```

Thanks!

**Comment by elextr** [comment]
That code is from the Scintilla project so needs to be reported there, although you do need to check it still happens because this is Scintilla 3.5 and its now up to 5.1.

Also for this sort of report always specify the compiler version and options you are using.

**Comment by rootkea** [comment]
> That code is from the Scintilla project so needs to be reported there

I tried compiling latest default branch of Scintilla and I didn't see these warnings.

> specify the compiler version and options you are using.

While compiling `geany` I did:
```
$ ./autogen.sh --enable-binreloc --enable-vte --enable-socket --enable-the-force --enable-html-docs --enable-pdf-docs --enable-api-docs --enable-gtkdoc-header --prefix=$PREFIX
$ make -j4
```

And I'm using `clang version 10.0.0-4ubuntu1` with CFLAGS set to `-Wall -g -O0`

**Comment by elextr** [comment]
Ok, so the warning should go away when #2867 is merged and in the meantime its not a problem, its a human warning, just that somebody using `Style` might get confused, but Geany does not use the C++ directly so no matter.
