### ISSUE TITLE
Feature request: allow CTRL+DEL to delete empty spaces alone, not also non-space characters after them

### ISSUE THREAD

**Issue by pgp** [geany/geany#2893]
Sometimes I deal with wrongly-formatted code files, which contain empty spaces at the row end, like in the following;

```
text here;                                    <- (lots of empty spaces here)
```
however, when I press CTRL + DEL starting from the end of the line, the whole last word is deleted together with the empty spaces.

While this clearly makes sense when there's only one space (e.g. I'm deleting word after word in a natural language text), in my scenario it's uncomfortable, I think some additional key combination would be useful in order to delete separately groups of spaces (and groups of tabs maybe), and groups of non-empty characters.

**Comment by elextr** [comment]
`Document->Strip trailing spaces` and do it all in one command?

**Comment by elextr** [comment]
Or `Edit->Preferences->Files->Saving Files->Strip trailing spaces and tabs` and Geany will delete them automatically on saving.
