### ISSUE TITLE
Geany 64-bit full on Windows 10 doesn't have the terminal option

### ISSUE THREAD

**Issue by geuristic** [geany/geany#2900]
The compile and build commands work and so does the execute command when I try them on a c++ file.

However, the integrated terminal is simply not there neither in Message Window, nor in Preferences.

Geany was installed from official website release `geany-1.37.1_setup.exe` and I used `full` option when installing.

![geany](https://user-images.githubusercontent.com/88374207/133924816-f27d6887-6ede-4183-897d-a721efb74cbc.png)

**Comment by eht16** [comment]
Unfortunately, on Windows we didn't find a suitable terminal library yet to be integrated in Geany.
The VTE library we use on non-Windows platforms cannot be used here, so this is a known and intended missing feature.

This might change in the future but it needs someone to implement and/or integrate an embedded terminal solution on Windows.
