### ISSUE TITLE
Error Compiling kotlin 

### ISSUE THREAD

**Issue by ESCANES** [geany/geany#2922]
Compiling a .kt file in geany always give me the error ("Process failed" the system cannot find the file specified )
But it works on my command line
The compile command is :kotlinc "%f" -include-runtime -d  "%e.jar"
And the execute command is :"java -jar %e.jar"(The execute command works But the compile command doesn't work))
 I have been trying for days to get it to work i even used the absolute path of the file but it still doesn't work
I am Using Windows 10
![Screenshot (170)](https://user-images.githubusercontent.com/79951868/136642539-3bacaeca-e9e1-44f4-8f86-eac31d39d884.png)

![Screenshot (169)](https://user-images.githubusercontent.com/79951868/136642477-598a7ded-eaa6-4c48-87f4-e57b50ad0d0e.png)

**Comment by eht16** [comment]
@ESCANES could you solve the problem?

**Comment by Dragaan** [comment]
I'm having the exact problem.  I've been using Geany for a LONG time (~10yrs) and I am easily able to get it configured to compile/build/execute ALL of my other languages (c, c++ (w/ many compilers), java, pascal, javascript (via node), several basics, python, ruby, Go (pauses for like 5-15sec oftentimes, but still works), Fortran.... I THINK that's it..  

Anyway, I've obviously got the process down pat, but the kotlinc command-line compiler just refuses to work in Geany.  Works just fine in any terminal/command prompt (cmd, powershell, cmder, etc.).  Path is set.  Geany just seems to ignore it.  No sound or anything, just "Process failed (The system cannot find the file specified)"

**Comment by Dragaan** [comment]
Trying to learn a little kotlin without having to use IntelliJ along with it is like pulling teeth....
