### ISSUE TITLE
Geany 1.38 (GTK3) UI dark theme for Windows?

### ISSUE THREAD

**Issue by Dim-Tim-1963** [geany/geany#2928]
Is it possible?  I set up my favorite color scheme for the editor, but the rest of UI is very bright "black-on-white".

**Comment by elextr** [comment]
> Now I have to figure out, how to apply it to GTK3... :)

I suspect it doesn't, IIUC the gtkrc file is no longer used, GTK3 theme will be a `.css` file(s) IIUC, like the `geany.css` file that is available for tweaking things (but I doubt it can change a whole theme).

**Comment by Dim-Tim-1963** [comment]
Here https://github.com/vinceliuice/stylish-gtk-theme there's a theme both for GTK2 and GTK3.  The question is how to apply it. :)  BTW, it would be nice to have at least a switch in the settings: light/dark UI theme.

**Comment by Dim-Tim-1963** [comment]
I will try it, thanks!

**Comment by Dim-Tim-1963** [comment]
...Though, the css itself needs tweaking.  For example, option ticks are invisible now (red squares).

**Comment by safarirat** [comment]
"Easy fix" will be just replace "C:\Program Files\Geany\data\geany.css" with yours GTK file.

but it will not change win headler (but it not a problem of gtk :^) )
![https://www.gnome-look.org/p/1267246](https://user-images.githubusercontent.com/23118902/140818962-3e05b8bc-6014-4d5e-be28-6fd7d52ba0db.png)

**Comment by Dim-Tim-1963** [comment]
Yes, it's now quite nice (to my taste), except blue summary string in messages window.  It's hard-coded. :(

![Clipboard-1](https://user-images.githubusercontent.com/42923977/140859821-461d99e4-8214-4612-8cb6-bc2f9fcc1d3d.jpg)

**Comment by elextr** [comment]
I think the "blue" should follow the [`geany-compiler-message`](https://www.geany.org/manual/current/index.html#customizing-geany-s-appearance-using-gtk-css) colour.

**Comment by Dim-Tim-1963** [comment]
> I think the "blue" should follow the [`geany-compiler-message`](https://www.geany.org/manual/current/index.html#customizing-geany-s-appearance-using-gtk-css) colour.

Yes, it really does!  Thanks! :)
![Clipboard-2](https://user-images.githubusercontent.com/42923977/140863492-f9b67961-a321-4d19-a00a-a013326c9cd8.jpg)

**Comment by xbowzone** [comment]
> 

How do you change it?

**Comment by xbowzone** [comment]
> ...Though, the css itself needs tweaking. For example, state of the option ticks (checkboxes) is invisible now (red squares).

How do you change it?

**Comment by Dim-Tim-1963** [comment]
Editing gtk.css, by trial and error. :)  I took _Stylish GTK Theme_ (link is upper in the thread), chose **gtk-Dark-Jade.css** as a base, and edited parts of it, looking at the result, until was satisfied. :)  CSS is huge and almost not commented.  But here is my variant, if you like it.  You can compare it with the base and see what was changed.
[gtk.css.zip](https://github.com/geany/geany/files/7798782/gtk.css.zip)

**Comment by xbowzone** [comment]
Thanks. It doesn't fix all the places but fixed everything in preference which is a big help!

**Comment by elextr** [comment]
#3063 is addressing the default windows (and OSX) theme, so maybe you want to add your 2c there.

**Comment by AndrewIsOffline** [comment]
Sorry for commenting on a dead thread, but for anyone who used the above gtk.css and noticed red squares replacing checkboxes in dropdown menus, the solution is to open up the file, go down to the "Firefox and Thunderbird" section, and comment out all blocks that include "-gtk-icon-source". It seems that the code points to some image files to use, but can't find them, and removing the lines reverts the code to using defaults. As for replacing the images, I still haven't found out how "url" works: it's not relative to gtk.css, and it can't be set to an absolute location.

**Comment by HelloWorldFR** [comment]
Thanks, very usefull

**Comment by cyberhardt** [comment]
not working for latest geany

**Comment by cyberhardt** [comment]
here's how to do it: paste this geany.css [geany.zip](https://github.com/geany/geany/files/11593367/geany.zip) into the \AppData\Roaming\geany folder. The css is the gtk-dark file from https://www.gnome-look.org/p/1013743/. there is no need to change the .css files on geany\data.

![image](https://github.com/geany/geany/assets/107224222/24fe116c-8e6b-4cf6-9e3d-64090255bd07)

**Comment by cyberhardt** [comment]
oh... the checkboxes are all messed up

**Comment by cyberhardt** [comment]
eh.. nevermind, some other things broke as well. devs could release an official dark mode...

**Comment by HelloWorldFR** [comment]
@cyberhardt
Hello, for checkboxes see  AndrewIsOffline's comment. For me its work perfectly.
What are this some other things broken?

**Comment by cyberhardt** [comment]
well, I tried different comment styles, and removing the lines entirely. I also tried putting the .css folder on AppData\Local\gtk, while leaving the others untouched. also didn't work. whatever then

**Comment by HelloWorldFR** [comment]
If its return to light mod, its mean something is wrong in the file

**Comment by cyberhardt** [comment]
> If its return to light mod, its mean something is wrong in the file

sorry, when I put the file on the AppData folder, it did stay on dark mode, but the red boxes issue wasn't fixed (even after commenting the stuff out)

**Comment by HelloWorldFR** [comment]
What is your css file? Can you upload your geany.css?

**Comment by elextr** [comment]
Please upload files to a gist and only put a link here.

**Comment by jake8923948** [comment]
> sorry, when I put the file on the AppData folder, it did stay on dark mode, but the red boxes issue wasn't fixed (even after commenting the stuff out)

in Geany, press "tools" > Configuration Files > geany.css

Ctrl + F 
": image(-gtk-recolor(url("assets/scalable/small-checkbox-unchecked-symbolic.svg")), -gtk-recolor(url("assets/scalable/small-checkbox-unchecked-symbolic.symbolic.png")));"
put #/ at the beginning. Put /# at the end.
Ctrl + S
Close, reopen. Checkboxes work now.

**Comment by jake8923948** [comment]
Hey, how do I remove the line down the middle of the page? 
I assume it's in the CSS code, as stock didn't have this

Thanks!

**Comment by elextr** [comment]
@jake8923948 `Edit->Preferences->Editor->Display->Long Line Marker`

**Comment by cyberhardt** [comment]
> > sorry, when I put the file on the AppData folder, it did stay on dark mode, but the red boxes issue wasn't fixed (even after commenting the stuff out)
> 
> in Geany, press "tools" > Configuration Files > geany.css
> 
> Ctrl + F ": image(-gtk-recolor(url("assets/scalable/small-checkbox-unchecked-symbolic.svg")), -gtk-recolor(url("assets/scalable/small-checkbox-unchecked-symbolic.symbolic.png")));" put #/ at the beginning. Put /# at the end. Ctrl + S Close, reopen. Checkboxes work now.
> 
> [1175×615 png94.3 kB![image](https://user-images.githubusercontent.com/25887548/244973867-e3baf69f-13e6-49c6-9fbc-87a67ecfe868.png)](https://user-images.githubusercontent.com/25887548/244973867-e3baf69f-13e6-49c6-9fbc-87a67ecfe868.png)

it becomes light mode when I do that

**Comment by cyberhardt** [comment]
> If you are on Windows, put the file here if you use installer: "C:\Progral Files\Geany\data\geany.css"
> 
> If not working, can you upload your geany.css?

this doesn't work, it's what I had done at first

**Comment by jake8923948** [comment]
> > in Geany, press "tools" > Configuration Files > geany.css
> > Ctrl + F ": image(-gtk-recolor(url("assets/scalable/small-checkbox-unchecked-symbolic.svg")), -gtk-recolor(url("assets/scalable/small-checkbox-unchecked-symbolic.symbolic.png")));" put #/ at the beginning. Put /# at the end. Ctrl + S Close, reopen. Checkboxes work now.
> 
> it becomes light mode when I do that

as suggested by the other person, upload your css file. or even a snippet of it

I've literally just installed geany, first ever time using it, installed the gtk theme and commented out that line and got checkboxes rather than red squres

**Comment by cyberhardt** [comment]
[geany.zip](https://github.com/geany/geany/files/11716469/geany.zip)
this is my geany css from gtk-dark, this time it is intact, nothing commented out

**Comment by cyberhardt** [comment]
> Put this one in your folder \AppData\Roaming\Geany

haha, nice, it works, but only if you remove both .css folders in Program Files\Geany\data. thanks for that

**Comment by cyberhardt** [comment]
> You should've uploaded your one, so we could see what you commented out Regardless, at least it's solved.

Well, I suppose it is easier to just tell me exactly what I should comment out instead of trying to find errors to fix. this is why I sent the unmodified file.

> I did also say to replace your geany.css with your new css by opening geany.css and replacing everything for the gtk-dark code (which would essentially delete the orignal)

I had done that before. I've specified it in my last comment so that people who come across this thread can easily know what to do without having to read the entire thing.

**Comment by cyberhardt** [comment]
> I mean, the screenshot does show the exact line, the exact commenting out characters and the exact location of the commenting out...... either way, at least you managed

and I had done exactly that. but it didn't work. nor did the Firefox/Thunderbird -gtk-icon-source trick before. idk what HelloWorldFR did different, but he solved it. that's it

**Comment by HelloWorldFR** [comment]
i have just remove all "-gtk-icon-source" line in all file to remove wrong link and avoid red square checkbox.

**Comment by ModernFighter75** [comment]
> > sorry, when I put the file on the AppData folder, it did stay on dark mode, but the red boxes issue wasn't fixed (even after commenting the stuff out)
> 
> in Geany, press "tools" > Configuration Files > geany.css
> 
> Ctrl + F ": image(-gtk-recolor(url("assets/scalable/small-checkbox-unchecked-symbolic.svg")), -gtk-recolor(url("assets/scalable/small-checkbox-unchecked-symbolic.symbolic.png")));" put #/ at the beginning. Put /# at the end. Ctrl + S Close, reopen. Checkboxes work now.
> 
> ![image](https://user-images.githubusercontent.com/25887548/244973867-e3baf69f-13e6-49c6-9fbc-87a67ecfe868.png)

Ok so I did as in the pic but I still have red boxex. I have no idea what the heck I am doing lol. Can you help me.(I have the newest version of geany)

**Comment by qlxxvi** [comment]
Go to your gnome instalation location ~\geany\share\themes\Prof-Gnome\gtk-3.0 and change name of gtk file to 'gtk-dark'.
![Zrzut ekranu 2024-07-22 180406](https://github.com/user-attachments/assets/f0f34b27-0b5c-435b-a4a3-b38ccd6b9511)
![Uploading Zrzut ekranu 2024-07-22 180452.png…]()

**Comment by qlxxvi** [comment]
Go to your gnome instalation location ~\geany\share\themes\Prof-Gnome\gtk-3.0 and change name of gtk file to 'gtk-dark'.
![Zrzut ekranu 2024-07-22 180406](https://github.com/user-attachments/assets/8418aca8-11e2-41b2-8a88-8b2dfb0ac92f)
![Zrzut ekranu 2024-07-22 180452](https://github.com/user-attachments/assets/7ee24396-b4ad-4478-a31d-4e6d6d162cf4)

**Comment by 0av** [comment]
In Windows you can globally use dark theme for GTK3 applications by setting an environment variable `GTK_THEME` with the value `Adwaita:dark`.
