### ISSUE TITLE
Make scrollbar thicker

### ISSUE THREAD

**Issue by DUOLabs333** [geany/geany#2933]
Whenever I'm trying to drag the scrollbar, It takes 2-3 times to hit it. So, it would be nice if it was thicker (or at least, adjustable). Or, there could be some sort of scrollable "Preview" feature like in Kate or Sublime?

**Comment by elextr** [comment]
Scrollbars are controlled by GTK theme not Geany.  Options are:

1. change the GTK theme on your system to one with wider scrollbars
2. edit the GTK tweak CSS ~/.config/gtk-3.0/gtk.css as below (don't do this unless you want it to apply to all apps)
3. edit geany.css (`Menu->Tools->Configuration Files->geany.css`) as below

Add below to CSS (changing the numbers to suit your screen and eyes, those are probably too big but make it visible it worked) and restart Geany.

```
scrollbar slider {
    /* Size of the slider */
    min-width: 20px;
    min-height: 20px;
    border-radius: 22px;

    /* Padding around the slider */
    border: 5px solid transparent;
}
```
