### ISSUE TITLE
Conflicting socket file with different users (using sudo)

### ISSUE THREAD

**Issue by stevenhoneyman** [geany/geany#294]
Running geany as my standard user, it creates "/tmp/geany_socket.xxxxxxx" with rw only for my user. If I leave that window open, and run `sudo geany /root/example.txt` I get:
````
(geany:781): Geany-WARNING **: Geany tried to access the Unix Domain socket of another instance running as another user.
This is a fatal error and Geany will now quit.
````

**Comment by kugel-** [comment]
@elextr @b4n @codebrainz IMO this counts as expected behavior, not a bug. Therefore this can be closed (i think).

**Comment by b4n** [comment]
> The sudo will use the same config as your previous instance.

Actually, it should not.  A properly configured `sudo` would reset `$HOME` and so Geany would use the `sudo`ed user's home (likely `root`'s).  For example, there is no such problem on Debian.

**Comment by elextr** [comment]
> Actually, it should not. A properly configured sudo would reset $HOME and so Geany would use the sudoed user's home (likely root's). For example, there is no such problem on Debian.

Yeah the Ubuntu (and derivatives like mint) don't change the directory or home when `sudo`ing.

I don't think its *properly* there are arguments for both :)

Maybe we should include the user name in the socket name, that would be more secure anyway.

**Comment by stevenhoneyman** [comment]
Arch linux is the same... or something forced me to set it that way at one time (probably google and its horrible build system...)
