### ISSUE TITLE
x86 support again?

### ISSUE THREAD

**Issue by whmsft** [geany/geany#2945]
Yeaterday, i found out that geany's got a new version...

But when i reached the downloads page, i got very very very angry..

Why no more SUPPORT for x86?
Even though there is a minority using x86, but minority still counts..

**Comment by elextr** [comment]
@whmsft Geany is a volunteer project, if nobody volunteered to make 32 bit support then it doesn't happen.  

But nothing is stopping x86 users providing it themselves since AFAIK nothing yet _prevents_ building for x86 assuming the relevant dependencies are also available for x86.
