### ISSUE TITLE
Do you have any plans for supporting Apple Silicon?

### ISSUE THREAD

**Issue by pouyakary** [geany/geany#2969]
As you know apple is planning to eliminate the Intel systems. In one/two years from now it would be very unlikely to see any Intel based Mac. Currently Geany doesn't even open in the M1 macs (or maybe it is the os 12 that is the problem), whatever it is, it would be so amazing to have the Geany back in the mac

![](https://user-images.githubusercontent.com/2157285/139278081-6f849cf0-7101-4933-ab76-54a8f3817465.png)

So my question is that do you have any roadmap for supporting the Apple Silicon?

**Comment by techee** [comment]
I created a ARM version of Geany here:

https://download.geany.org/snapshots/geany-1.38_osx_arm64.dmg

Would you give it a try?

The black screen issue was also fixed in the x86_64 release which is now available from the downloads page.

**Comment by pouyakary** [comment]
@techee on it... ♥️

**Comment by pouyakary** [comment]
![](https://user-images.githubusercontent.com/2157285/140657921-501ac726-3ee3-4cc2-a728-21110acca151.png)

Works awesome :)
