### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by a-seipel** [geany/geany#2974]
After updating the operating system to macOS Monterey, Geany only shows a black screen where previously the editor, the widget and the terminal was. I tried reinstalling but it did not work. Help > Debug Messages opened a seperate, equally black window. I use Geany 1.38.

**Comment by elextr** [comment]
Duplicate of https://github.com/geany/geany-osx/issues/31 

Note there is a separate repository for mac specific material, please open mac issues there.
