### ISSUE TITLE
Segmentation fault if Ctrl+Shift+V pressed

### ISSUE THREAD

**Issue by drws** [geany/geany#2980]
The title more or less scoops the entire problem. Anytime I (accidentally) use `Ctrl+Shift+V`, Geany crashes with _Segmentation fault_.

**Versions:**
* Geany 1.38
* MATE 1.26.0
* GTK3 3.24.30

Also, the crash doesn't happen on a Windows system. I suspect this might come up in the discussion, but I'm not using any additional clipboard managers, except for what MATE does with the clipboard by default.

**Comment by elextr** [comment]
Duplicate of #2813?

**Comment by drws** [comment]
I was searching previous issues in a hurry and missed it. It is a duplicate.
