### ISSUE TITLE
Help -> Keyboard Shortcuts not showing Go to start / end of document  

### ISSUE THREAD

**Issue by sgornick** [geany/geany#2994]
From the Keybindings section of [geany.txt](https://github.com/geany/geany/blob/master/doc/geany.txt) I see:

_Go to end of document. | Ctrl-End
Go to start of document. | Ctrl-Home_

However, within Geany when I do Help -> Keyboard Shortcuts, I don't see these two keyboard shortcuts (under the Go to section).

Both of these are pretty commonly used keyboard shortcuts so I would have expected to see them in the list. 

I'm using Geany v1.3.6.

**Comment by elextr** [comment]
The only place Ctrl-Home and Ctrl-end are documented AFAICT is in the [Scintilla](https://www.geany.org/manual/current/index.html#scintilla-keyboard-commands) keybindings.  As the text says these are inherited from the Scintilla editing widget, they are not Geany keybindings.  

So they cannot be set by Geany and do not show in the Keybindings preference dialog or `Help->Keyboard Shortcuts` list which only reflects those modifiable bindings.
