### ISSUE TITLE
Inconsistent use of "Go to" versus "Goto" in Keybindings doc   

### ISSUE THREAD

**Issue by sgornick** [geany/geany#2995]
In the Keybindings section of [geany.txt](https://github.com/geany/geany/blob/master/doc/geany.txt), there are multiple instances where "Goto" is shown, but "Go to" would be correct.

For example,

_Goto matching brace_ 

However, in the Help -> Keyboard Shortcuts, the text reads:

_Go to matching brace_

So I am suggesting these instances are edited to use "Go to" where appropriate.

**Comment by elextr** [comment]
Pull requests are welcome.

**Comment by Garrett-M-code** [comment]
I submitted a pull request editing the geany.txt file to "Go to" instead of "Goto" just waiting for it to get approved by a maintainer.
