### ISSUE TITLE
Add syntax highlighting implementation for ReStructuredText (reST)

### ISSUE THREAD

**Issue by bittner** [geany/geany#300]
## Problem Description

Syntax highlighting for [reStructuredText](http://docutils.sourceforge.net/rst.html) is prepared in Geany, i.e. the data file [filetypes.restructuredtext](https://github.com/geany/geany/blob/master/data/filetypes.restructuredtext) exists and the [extensions are evaluated](https://github.com/geany/geany/blob/master/data/filetype_extensions.conf#L54) to activate the highlighting mode, but the highlighting implementation is in fact empty.

As a result, there is no highlighting for reST working in Geany at the moment.
## Proposed Solution

Add implementation details in [data/filetypes.restructuredtext](https://github.com/geany/geany/blob/master/data/filetypes.restructuredtext) leveraging other, reliable sources, e.g. [reST language specs](https://git.gnome.org/browse/gtksourceview/tree/data/language-specs/rst.lang) of gtksourceview (used by Gnome's [gedit reST plugin](https://github.com/bittner/gedit-reST-plugin/tree/master/syntax)).

**Comment by andy5995** [comment]
> Add implementation details in [data/filetypes.restructuredtext](https://github.com/geany/geany/blob/master/data/filetypes.restructuredtext) 

That file has been moved since then to [data/filedefs/filetypes.restructuredtext](https://github.com/geany/geany/blob/master/data/filedefs/filetypes.restructuredtext).

I'm working on this ticket atm.

**Comment by cup** [comment]
@andy5995 any update?

**Comment by andy5995** [comment]
No, I'm sorry to report I didn't get anywhere with this. I'll unassign myself from the ticket.

**Comment by eht16** [comment]
Closing as it is unlikely this will happen unless someone will write a Scintilla lexer for reStructuredText.
