### ISSUE TITLE
home and end key do nothing when in split window on the right side

### ISSUE THREAD

**Issue by andy5995** [geany/geany#3047]
While editing a C document in the right-side window, the cursor didn't go to the beginning or end of the line when using the home and end key.

```
00:19:59.095696: GLib-GIO DEBUG	: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
00:19:59.118762: Geany INFO		: Geany 1.39 (git >= 11a1f32f), en_US.utf8
00:19:59.118773: Geany INFO		: GTK 3.24.30, GLib 2.70.1
00:19:59.118796: Geany INFO		: OS: Manjaro Linux
00:19:59.118811: Geany INFO		: System data dir: /home/andy/.local/share/geany
00:19:59.118816: Geany INFO		: User config dir: /home/andy/.config/geany
00:19:59.218196: Geany INFO		: Loaded GTK+ CSS theme '/home/andy/.local/share/geany/geany.css'
00:19:59.218896: Geany INFO		: Loaded GTK+ CSS theme '/home/andy/.local/share/geany/geany-3.20.css'
00:19:59.222820: Geany INFO		: System plugin path: /home/andy/.local/lib/geany
00:19:59.228730: Geany INFO		: Added filetype Clojure (64).
00:19:59.228737: Geany INFO		: Added filetype Nim (65).
00:19:59.228741: Geany INFO		: Added filetype Graphviz (66).
00:19:59.228745: Geany INFO		: Added filetype Groovy (67).
00:19:59.228749: Geany INFO		: Added filetype CUDA (68).
00:19:59.228752: Geany INFO		: Added filetype Meson (69).
00:19:59.228756: Geany INFO		: Added filetype JSON (70).
00:19:59.228760: Geany INFO		: Added filetype Arduino (71).
00:19:59.228764: Geany INFO		: Added filetype Kotlin (72).
00:19:59.228767: Geany INFO		: Added filetype Scala (73).
00:19:59.228770: Geany INFO		: Added filetype Genie (74).
00:19:59.228774: Geany INFO		: Added filetype Swift (75).
00:19:59.228777: Geany INFO		: Added filetype Cython (76).
00:19:59.228781: Geany INFO		: Added filetype TypeScript (77).
00:19:59.241050: Geany INFO		: Loaded libvte from libvte-2.91.so
00:19:59.256054: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/debugger.so (Debugger)
00:19:59.259442: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/filebrowser.so (File Browser)
00:19:59.260744: SpellCheck DEBUG	: Initializing Enchant library version 2.3.1
00:19:59.263159: (null) WARNING	: Error loading plugin: libhspell.so.0: cannot open shared object file: No such file or directory

00:19:59.263312: (null) WARNING	: Error loading plugin: libnuspell.so.5: cannot open shared object file: No such file or directory

00:19:59.263494: (null) WARNING	: Error loading plugin: libvoikko.so.1: cannot open shared object file: No such file or directory

00:19:59.263527: GLib DEBUG	: setenv()/putenv() are not thread-safe and should not be used after threads are created
00:19:59.266247: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/spellcheck.so (Spell Check)
00:19:59.266920: Geany INFO		: Loaded:   /home/andy/.local/lib/geany/splitwindow.so (Split Window)
00:19:59.271803: Geany INFO		: unknown : None (UTF-8)
```

**Comment by andy5995** [comment]
@elextr There are some [other split window issues](https://github.com/geany/geany-plugins/issues?q=is%3Aissue+is%3Aopen+split+window) in the geany-plugins repo you may want to transfer to here as well.

**Comment by elextr** [comment]
@andy5995 thanks, of the ones in your search results only #600 seemed to actually be about split window plugin (although I didn't check exhaustively)

**Comment by CouldBeThis** [comment]
I found this looking for something else but will confirm unexpected behaviour. Sorry I am not clear if this is to go here or in the other repo but this is where existing discussion is.

The bottom or right hand pane does not accept commands properly. No matter where the cursor is (which pane has focus), for example:

* `ctrl`+ `f` - find works only for primary window
*  `ctrl`+ `z` - undo only works in primary window; very confusing especially when different documents are opened
* cannot modify options in secondary window such as change font size, show/hide line numbers

also:

* application of `geany-document-status-changed` a bit weird.. if `fileA` is split, then modified, the status changes to indicated unsaved changes. But if you switch to `FileB`, this goes away. Furthermore the `File > Save` is greyed out and seems not to be possible to save. I have not investigated this thoroughly to find out what if anything is happening to the changes. Autosave? 

Sadly I have no ability to do anything about fixing these. Just leaving the info here in case helpful to someone. 

About:

> "Sulamar"
> (built on or after 2021-10-09)
> Using GTK+ v3.24.33 and GLib v2.72.0 runtime libraries
