### ISSUE TITLE
Raku comment #`{comment} not recognized properly

### ISSUE THREAD

**Issue by ToddAndMargo** [geany/geany#3053]
Fedora 35
geany-1.38-1.fc35.x86_64

Bug:  geany is turning the top open { bracket blue instead of the second open bracket  #`{ blue when the first close bracket } is highlighted.   

This bug really makes find missing closing brackets a pain in the neck!

```
sub GetWindows10Build() {
   my $SubName = &?ROUTINE.name;
   PrintRedErr( "$SubName not yet implemented\n" ); return;  
#`{
      multi line comments go here
  }

}
```

**Comment by elextr** [comment]
Raku is not a language Geany supports, so it does not know about Raku #\` comments, only Perl comments.
