### ISSUE TITLE
RFE: please add support for Perl6 (Raku)

### ISSUE THREAD

**Issue by ToddAndMargo** [geany/geany#3054]
Request for Enhancement: please add support for Perl6 (Raku)

**Comment by rdipardo** [comment]
A Raku lexer was added to upstream Scintilla some time ago: https://sourceforge.net/p/scintilla/feature-requests/1328/

You'll notice that Geany includes only a curated subset of upstream lexers: https://github.com/geany/geany/tree/master/scintilla/lexilla/lexers

Getting Raku into Geany would require a PR similar to these recent examples:

- https://github.com/geany/geany/pull/2584
- https://github.com/geany/geany/pull/3012

The main difference here is that the lexer module [is already written](https://github.com/ScintillaOrg/lexilla/blob/efd741310e9bd870811ec55940d05ff8d6115ef3/lexers/LexRaku.cxx#L1); the main job would be creating a tags parser and a file definition for Raku.

**Comment by rdipardo** [comment]
@ToddAndMargo, if you're still interested in having a builtin Raku file type, you can build a custom Geany from @techee's [PR][0], like this:

~~~sh
[ ! -d geany ] && git clone -b perl6 https://github.com/techee/geany.git
cd geany
NOCONFIGURE=1 ./autogen.sh
mkdir -p _build _build/share/geany/

pushd _build
CFLAGS='-g -O0' \
../configure --prefix=`pwd` \
        --disable-html-docs \
        --disable-pdf-docs \
        --disable-api-docs \
        --disable-gtkdoc-header \
        --enable-binreloc=no
make -j2
export LD_LIBRARY_PATH=`pwd`/src/.libs
popd

cp -ru data/* _build/share/geany/
`pwd`/_build/src/.libs/geany -v
~~~

*Note*
If you're on distribution that uses 'apt', you may need to run this first:

    sudo apt install -y --no-install-recommends \
        autopoint \
        ccache \
        gettext \
        libtool \
        libgtk-3-dev


[0]: https://github.com/geany/geany/pull/3169

**Comment by ToddAndMargo** [comment]
Hi Rdipardo,

What is the release number that this first appears in?  (If I can give Fedora the release number, they will spin a new RPM for me.)

Thank yoU!

-T

**Comment by b4n** [comment]
@ToddAndMargo It's not in any release version yet, it'll be in 2.1 whenever that comes out.  In the meantime, it's in Git master now.
