### ISSUE TITLE
Find dialog Search criteria not updated on CTRL+F

### ISSUE THREAD

**Issue by ldelaprade** [geany/geany#3057]
Geany 1.36
(built on or after Mar 22 2020)
Using GTK+ v3.24.20 and GLib v2.64.6 runtime libraries

When 'Find' dialog is opened, 
Go back to text editor tab and double click some word you'd like to find other occurences if any.
'Find' dialog regain focus but search zone is still filled with old value

**Comment by elextr** [comment]
The find dialog does not follow the selection deliberately so you don't lose the search string if the editing you do between finds happens to include a selection.  To change the search string just select it and type CTRL+F again, which will also open or re-focus the dialog.

**Comment by alexnerd123** [comment]
I actually have a slightly similar issue to that. When I select a word and ctrl-F, I get the find dialogue with the word in it. Great!

But if I want to change my search term, if I just click away from the search box (leaving it open in the background), select a new word, and ctrl-F again.... then the search box comes back, but with the old word highlighted. Its a bit annoying. I've gotten into the habit of hitting esc to close the find dialogue before ctrl-F-ing a new word. This way, geany picks up my new word on a fresh ctrl-F.

Its a minor inconvenience, but nonetheless

I can replicate it all day on 1.36

I just tried to replicate it on 1.38..... but worse!!!! If I try to click away from the search box, its forever, ever more, ever, GONE. I can't get it back. Ctrl-F-again "greys out" geany, as if another program has focus, but theres no search box. I can actually see it disappear when I hit ctrl-F the second time (its not "behind" geany or anything). The only way to get it back, is to ctrl-F several times to give keyboard focus to this "phantom" search box, and hit escape to close it out. Then, a ctrl-F will bring it back...... once..... until the cycle repeats!

**Comment by elextr** [comment]
To be clear, IIRC the behaviour of the search has changed since 1.36 to the behaviour I described, ie where ctrl-f will copy the selection even if the dialog is still open, not sure if it was 1.37 or 1.38.

@alexnerd123 your problem has nothing to do with this issue, please open a new one, and provide information about your system.
