### ISSUE TITLE
Define word separators for double clicking text

### ISSUE THREAD

**Issue by konomikitten** [geany/geany#3068]
I want to be able to change the behaviour of double click to select a single word when underscores are used as word separators. Currently if I double click `this_is_a_test` in geany the whole entire sentence is selected. I want to be able to double click and select only the words in it. This isn't a problem for dashes `this-is-a-test` double clicking any word in this test selects only the word. I read through #492 but that seemed to be for keyboard interactions not mouse interactions.

**Comment by elextr** [comment]
Works here for C (and dashes don't work).  This is a per language setting in the language filetypes file.

**Comment by konomikitten** [comment]
@elextr this was in just a normal text file aka no filetype. I tried all the steps in the other mentioned bug report but double click for me still includes underscores. I'll double check when I get home though i n case I missed a step.

**Comment by elextr** [comment]
Same for text file (filetype `None`) here.  Check the filetype in the status bar.  Maybe you have edited your `filetypes.common`?

**Comment by konomikitten** [comment]
I got it working turns out I'd left the `_` in `wordchars`. For anyone finding this in the future you need to add characters to `wordchars` for selections. Sorry for the noise and thank you for the help.
