### ISSUE TITLE
For `⸪` shows `⸬` | for `⸫` shows `⸪` | for `⸬` shows `⸫`

### ISSUE THREAD

**Issue by Uzivatel919** [geany/geany#3069]
Geany interchanges UTF-8 glyphs:

  ⬥ 2E2A ⸪ TWO DOTS OVER ONE DOT PUNCTUATION
  ⬥ 2E2B ⸫ ONE DOT OVER TWO DOTS PUNCTUATION
  ⬥ 2E2C ⸬ SQUARED FOUR DOT PUNCTUATION

It maps as follows:
|Number|Glyph|
|--|--|
|2E2A ⇛ 2E2C|**⸪** ⇛ **⸬**
|2E2B ⇛ 2E2A|**⸫** ⇛ **⸪**
|2E2C ⇛ 2E2A|**⸬** ⇛ **⸫**

---

See http://unicode.org/charts/PDF/U2E00.pdf.

**Comment by elextr** [comment]
Displays correctly here, likely your font is the problem.

```
(null): Geany INFO		: Geany 1.39 (git >= b7558417), en_AU.UTF-8
(null): Geany INFO		: GTK 3.24.20, GLib 2.64.6
(null): Geany INFO		: OS: Linux Mint 20 (ulyana)
```

`View->Change Font` `DejaVu Sans Mono Book 10 pt`

**Comment by Uzivatel919** [comment]
@elextr, no and yes. Problem is not in font. I verified it and there is problem somewhere else. For instance upon pasting into Mozilla Thunderbird I got right glyph while pasting into the LibreOffice Writer produces same result as pasting into the Geany.

**Comment by elextr** [comment]
You need to ensure that each application is using the same font.

Also always provide the information I provided above, and which font each app is using.

**Comment by Uzivatel919** [comment]
It is not font nor encoding. If you are interested try follow up with https://bugzilla.opensuse.org/show_bug.cgi?id=1194067.

**Comment by elextr** [comment]
As I said, it works here, neither this nor the suse bug report provide any useful information to reproduce the problem. What version of Geany? What versions of GTK and Glib? What font and size?

**Comment by Uzivatel919** [comment]
I am providing you info but I told I made experimetns with fonts that rendered font nor encoding as cause.

`geany 1.34.1 (built on 2019-06-01 with GTK 3.24.20, GLib 2.62.6)`

I tried in Geany for instance:
⭑ DejavVu Sans Mono Book 9 + UTF-8
⭑ DejavVu Sans Mono Book 9 + WINDOWS-1252
⭑ DejavVu Sans Mono Book 13 + WINDOWS-1252
⭑ Courier Regular 16 + UTF-8
⭑ Courier Regular 9 + UTF-8

All the same.

**Comment by elextr** [comment]
Ok, well as I said it works here with DejaVu fonts (I don't have courier) and it works with both 1.36 and 1.39 (current git).  And we have exactly the same version of GTK.

Thanks for trying the encoding, but as you found, it is unlikely to have any effect because the Geany buffer is always UTF-8 no matter the file encoding.  It might impact the ability to save the characters though.

So the things that are different are that its a very old Geany at 1.34 although I am not sure that was so terribly different to 1.36 which works here. Is it possible for you to try a newer version? I thought someone was building Geany on the Suse Open Build Service but maybe they stopped.

Otherwise its something about Suse vs Mint, IIUC Suse is Qt/KDE based and Mint is GTK/Gnome based so maybe there is something happening in the Suse backends behind GTK.  Not sure how you could track it down.

**Comment by elextr** [comment]
@Uzivatel919 how did you enter the code points? Did you use the KCharSelect as per the bug report?  If so try entering with Geany's own unicode entry, ctrl+shift+u type the code 2e2a and enter.

**Comment by Uzivatel919** [comment]
> @Uzivatel919 how did you enter the code points? Did you use the KCharSelect as per the bug report? If so try entering with Geany's own unicode entry, ctrl+shift+u type the code 2e2a and enter.

Great hint. I did as you told and it exhibits faulty mapping. 

Btw, I tried more approaches but all go through clipboard.

**Comment by elextr** [comment]
> Great hint. I did as you told and it exhibits faulty mapping.

To be clear, which is faulty, the Geany entry or KCharSelect?

**Comment by Uzivatel919** [comment]
> To be clear, which is faulty, the Geany entry or KCharSelect?

KCharSelect and Clibpoard are fail less.

> Is it possible for you to try a newer version?

I tried `geany 1.38 (built on 2021-11-05 with GTK 3.24.20, GLib 2.62.6)` from https://ftp.lysator.liu.se/pub/opensuse/repositories/GNOME:/Apps/openSUSE_Leap_15.3/ repository but result is the same.

> I thought someone was building Geany on the Suse Open Build Service but maybe they stopped.

Yes, geany 1.34.1 is newest available from OpenSUSE repository.

**Comment by elextr** [comment]
So ctrl+shift+u type the code 2e2a and enter displays the four dot glyph?  

That does not happen here, so its likely something that is particular to Suse, remember the bug report noted other applications that have the same problem.

**Comment by Uzivatel919** [comment]
> So ctrl+shift+u type the code 2e2a and enter displays the four dot glyph?

Yes, exactly. After _Enter_ hit, it produces `⸬ ` instead of `⸪`.

**Comment by elextr** [comment]
AFAIK none of the regular Geany contributors use suse, not sure how to help you further, maybe one of the other problem applications can.

**Comment by Uzivatel919** [comment]
> AFAIK none of the regular Geany contributors use suse, not sure how to help you further, maybe one of the other problem applications can.

Since it is just issue with these rare glyphs and I reported it also SUSE, I guess I need no more assitance.
