### ISSUE TITLE
Reload configuration not works

### ISSUE THREAD

**Issue by 221V** [geany/geany#3085]
Reload configuration not works --
https://askubuntu.com/questions/112217/prolog-files-recognized-as-perl
i have this problem, i change filetype_extensions.conf, save changes, click reload, reopen geany and nothing changes!

i change next line in config
```
#~ Perl=*.pl;*.perl;*.pm;*.agi;*.pod;
```
to
```
#~ Perl=*.perl;*.pm;*.agi;*.pod;
#~ Prolog=*.pl;
```
but geany continue think that *.pl in Perl !!!

how to switch it to Prolog??
help me please!
thank you!

**Comment by elextr** [comment]
1. the lines you are editing are commented out (the `#~`), so no change will have any effect, and likely the header is also commented out
2. there is no Prolog filetype anyway

**Comment by 221V** [comment]
oh ok, i understand that is comments, thank you

now edit and save
```
Perl=*.perl;*.pm;*.agi;*.pod;
None=*;*.pl;
```
and reload config,
but Geany continue thinking i have Perl file with Perl highlight ...

so how i can change highlight to nothing? ((

**Comment by elextr** [comment]
Is the heading `[Extensions]` uncommented?

**Comment by 221V** [comment]
wow! thanks!)))
