### ISSUE TITLE
Prolog highlight for .pl files

### ISSUE THREAD

**Issue by 221V** [geany/geany#3086]
Prolog highlight for .pl files feature request --

https://sourceforge.net/p/geany/feature-requests/325/
there was one in 2009, now is 2022,
and no Prolog highlight right now :(

thank you!

**Comment by elextr** [comment]
Geany is a volunteer project, and nobody volunteered it.

**Comment by 221V** [comment]
ok, so how i can add Prolog highlight?
where i need to look, what to add, edit etc?

can you give some hints, if you know it, please?
thank you!

**Comment by elextr** [comment]
See the manual and the HACKING file.

Highlighting is provided by the Scintilla editing widget Geany uses which does not support Prolog, so it would need to be added there (written in C++), see https://www.scintilla.org/Lexilla.html.

For symbol parsing Geany uses the parsers from the Universal Ctags project which also does not support Prolog.  There was an attempt to add it but it appears to have been abandoned, see https://github.com/universal-ctags/ctags/issues/2628

**Comment by 221V** [comment]
thanks, but C++ is too hard way for me now,
i see more easy one -- erlang highlight for my prolog files,
maybe be not full but enough  for me now :)
