### ISSUE TITLE
geany always clear excute permission

### ISSUE THREAD

**Issue by eexpress** [geany/geany#3104]
Every time I **save** a file, the software clears the execution permission. Whether bash or perl. Of course all those files had excute permission set before edit.

```
⭕ geany --version
geany 1.37.1 (built on 2021-04-03 with GTK 3.24.25, GLib 2.68.0)
⭕ touch xx
⭕ chmod +x xx
⭕ ls xx
-rwxrwxr-x 1 eexpss 0 01-18 22:39 xx
⭕ geany xx
⭕ ls xx           <------------------------------------------------- HERE
-rw-rw-r-- 1 eexpss 3 01-18 22:39 xx
⭕ cat /etc/issue
Ubuntu 21.10 \n \l
⭕ apt list --installed geany*
Listing... Done
geany-common/impish,impish,now 1.37.1-3 all [installed,automatic]
geany-plugin-autoclose/impish,now 1.37+dfsg-6build1 amd64 [installed]
geany-plugin-automark/impish,now 1.37+dfsg-6build1 amd64 [installed]
geany-plugin-git-changebar/impish,now 1.37+dfsg-6build1 amd64 [installed]
geany-plugins-common/impish,now 1.37+dfsg-6build1 amd64 [installed,automatic]
geany/impish,now 1.37.1-3 amd64 [installed]
⭕ cat /etc/mtab |g home
/dev/nvme0n1p8 /home ext4 rw,nosuid,nodev,relatime 0 0
```

**Comment by elextr** [comment]
Which file saving method are you using?  Atomic file saving creates a new file and renames it over the old one, so it gets the new-file permissions of the directory, see [here](https://wiki.geany.org/config/all_you_never_wanted_to_know_about_file_saving) for more info.

**Comment by eexpress** [comment]
> use_gio_unsafe_file_saving This is on by the default

but in my config, `use_atomic_file_saving` is checked. I never know this option...

anyway, it can be normal now. thanks.

**Comment by elextr** [comment]
But new versions of Geany do not modify the user config, so you either have a config so old that the GIO option did not exist and the atomic option was default (I mean _really_ old, so unlikely) or you accidentally changed the setting clicking around in `Edit->Preferences->Various` at some point and it was preserved in your user config.
