### ISSUE TITLE
Install fails for custom folder

### ISSUE THREAD

**Issue by richardFK** [geany/geany#3106]
Geany 1.38  Windows 10 x64

When installing in CUSTOM FOLDER  (G:\c;\Program Files\) to save space on my C:\ drive -  get the following error:-

geany.exe - System Error

X The code execution cannot proceed because libgeamy-0.dll was not found. Reinstalling the program may fix this problem.

The install was successful for the DEFAULT folder C:\Program Files\

**Comment by eht16** [comment]
Cannot reproduce. I installed Geany 1.38 to `Z:\somefolder\Geany` and it worked flawlessly.

Your folder looks strange though, the semicolon in the path might be the problem. The semicolon is used as a path seperator on Windows, i.e. you basically specify two paths at once.

![geany_windows_custom_location](https://user-images.githubusercontent.com/617017/150675376-7ecd4318-f031-4c6e-b115-06c4b3b8441a.png)
