### ISSUE TITLE
pulldown menu items not immediately selectable after having just been clicked

### ISSUE THREAD

**Issue by arinar** [geany/geany#3112]
I'm using Geany 1.38 on Windows 10. (built on or after 2021-10-09, Using GTK+ v3.24.30 and GLib v2.70.0 runtime libraries)

When hovering over menu items they are initially not selected. This happens right after the same item has previously been clicked.

![gif_25-01-22_11-15-56](https://user-images.githubusercontent.com/5115734/150958852-4220e507-3252-40a1-8972-c2f64c75f974.gif)

First noticed first when invoking a specific plugin feature (Line Ops, Sort Lines) multiple times in succession. However, it can be reproduced for other menu items including non-plugin ones.

I think it is a general issue in how gtk is utilized in geany. But could also be a gtk issue on windows. Or combinatio
n of both.
I have no way to investigate right now.

**Comment by elextr** [comment]
Can't reproduce on Geany on Linux, so probably GTK on Windows.

**Comment by eht16** [comment]
Just tested and I can reproduce it on Windows.
`gtk3-demo` and `gtk3-demo-application` behave exacrly the same, so I'm pretty sure this is a GTK+Windows issue.
