### ISSUE TITLE
Different feature between GUI and CLI.

### ISSUE THREAD

**Issue by mianqi2016** [geany/geany#3113]
I used Geany 1.37 om Ubuntu 20.04, when I compiled such code(Line 34), there was different prompts between GUI and CLI:

Inside GUI, there was a red wave line under Line 34 ( int v2[10]; ) , and I heard an alert from PC:
![image](https://user-images.githubusercontent.com/22947586/151089580-954ed53d-27b2-463a-b7fb-1f7aaed52908.png)

While, inside CLI, it was OK:
![image](https://user-images.githubusercontent.com/22947586/151089545-72f7576f-6127-4d7b-ba90-56f471b76933.png)

**Comment by elextr** [comment]
What was the error on line 34?

Note that the default C++ compile and build in Geany uses -Wall, try that on the command line.

**Comment by mianqi2016** [comment]
I saw it in "Set Build Commands", if I didn't descend the warning level, how to fix it? I tried "int v2[10];" "int v2[] = {0, 1, 2, 3, 4, 5, 6, 7, 8, 9};" "int v2[];", none of them works.

**Comment by elextr** [comment]
This is not a problem with Geany, its how the C++ compiler works and what is wrong with your code is off topic for this project.  Especially as you have not actually provided what the actual warning is.
