### ISSUE TITLE
[Enhancement request] I hope markdown support in comment

### ISSUE THREAD

**Issue by eexpress** [geany/geany#3118]
Normally the comments are not rigid. If you can introduce a subset of markdown to it, such as `inline code` or `underline`, it will be clearer and more comfortable.

**Comment by elextr** [comment]
What is this relevant to??

**Comment by eexpress** [comment]
`Enhanced features`

**Comment by elextr** [comment]
> Normally the comments are not rigid.

Comments in what?

**Comment by eexpress** [comment]
It hard to express, I want like this in the picture. Make some keywords more eye-catching in comments. To me, comments are very important for later review.
![xx](https://user-images.githubusercontent.com/700793/153531079-472311a9-c253-489a-a61b-c92fbcf4f1e0.png)

Or maybe some effect can do in `colorschem` conf, but I don't know what those define exactly means.
```
comment=comment_grey
comment_doc=docstring_green
comment_line=comment
comment_line_doc=comment_doc
comment_doc_keyword=comment_doc,bold
comment_doc_keyword_error=comment_doc,italic
```

**Comment by eexpress** [comment]
For the first time, I knew about the liblexilla library. I seems cannot do it right now. Thanks anyway.
