### ISSUE TITLE
When could Raku, Nim and others lexers be ready

### ISSUE THREAD

**Issue by abdulbadii** [geany/geany#3124]
When will Raku, Nim or other pretty new programming languages lexers be ready ?
Already some time waiting..
Or show clearly how to make such lexers in step by step mini tutorial
Please help.

**Comment by elextr** [comment]
> When will Raku, Nim or other pretty new programming languages lexers be ready ?

Current Geany (1.38) provides both lexical highlighting (ie it has a lexer) and symbols (it has a parser) for Nim, but you have not provided any information on the version you are using.

For Raku, there is a lexer in upstream Lexilla, but somebody who wants it has to add the language as a Geany filetype.  Geany is an entirely volunteer project, nothing happens unless somebody contributes it, and it would seem that nobody has time and interest and ability to contribute a Raku filetype.  The process requires C coding, is described in HACKING, and you can look at the recent addition of GCscript in #3012.
