### ISSUE TITLE
Lexilla license not installed

### ISSUE THREAD

**Issue by elextr** [geany/geany#3126]
The lexilla license file does not appear to be installed with the default autotools build.

**Comment by eht16** [comment]
The installed Scintilla license file `ScintillaLicense.txt` begins with:

> License for Lexilla, Scintilla, and SciTE

Might this be enough?
If we are not sure, I agree we should install the Lexilla license additionally.

**Comment by elextr** [comment]
You expect me to _read_ the License!!!! :grin:  The licenses are the same for Lexilla and for Scintilla ATM, but they are separate files in different repositories so in theory could differ.  So the suggestion was simply based on the fact that the meson build installed the Lexilla license file.

**Comment by kugel-** [comment]
My meson PR includes a change so that the license is also installed for autotools builds

**Comment by elextr** [comment]
> My meson PR includes a change so that the license is also installed for autotools builds

:+1:

**Comment by eht16** [comment]
Ok. I'll have a look at the autotools part.

**Comment by eht16** [comment]
I guess we can close this since Meson is merged and the Lexilla license is installed now also via Autotools.
![geany_lexilla_license](https://user-images.githubusercontent.com/617017/162611469-12b713d0-0117-485f-bd72-ab026101387c.png)

**Comment by elextr** [comment]
Done
