### ISSUE TITLE
Following lines of multiline function signatures ignored in doc-help

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [geany/geany#3131]
I have no 3rd party plugin activated. This is pure Geany. :)

But it is great that Geany does recognise the signatures of Python functions and methods while typing them somewhere. Geany then shows me the signature (all parameters) in an extra small window beside the cursor. Sorry I missed the correct term for that.

This works for signatures like that:
```Python
def parallize_data_frame_job_by_pool(df, worker_func, worker_args=None, n_cores=None):
   pass
```

But not for that:
```Python
def parallize_data_frame_job_by_pool(df,
                                     worker_func,
                                     worker_args=None, # tuple(),
                                     n_cores=None):
```

In the last case Geany only shows me `parallize_data_frame_job_by_pool(df`.

**Comment by eht16** [comment]
This will be fixed by #3031 which is going to be merged soon.
