### ISSUE TITLE
geany compilation failed

### ISSUE THREAD

**Issue by Aldrinff** [geany/geany#3132]
in geany 1.38 when ever i compile its showing>>  process failed(systemm cannot find file specifyed) 
i am new to this i dont know anything plzz help......

![image](https://user-images.githubusercontent.com/89537585/156123378-08125ddd-82a1-4d66-8967-f427d8e1f611.png)

**Comment by elextr** [comment]
Geany does not include compilers, have you installed one?

**Comment by Aldrinff** [comment]
nop i didnt how to download it bro @elextr

**Comment by elextr** [comment]
Websites for compilers will provide instructions to install.

**Comment by Aldrinff** [comment]
bro can u send the link to install @elextr

**Comment by elextr** [comment]
I suggest you google a website that teaches the programming language you want to learn and provides instructions on installing what you need.

**Comment by Aldrinff** [comment]
@elextr  tnx bro all set very very very tnx bro  <3
