### ISSUE TITLE
Many "No disk" messages when trying to open a file

### ISSUE THREAD

**Issue by HJvT** [geany/geany#3135]
When trying to open a file, either by menu or ctrl-o, the message:
```
  Windows - No disk
  Exception Processing Message 0xc0000013 - Unexpected parameters
```
appears; clicking on "cancel" or "continue" results many times in the same error message window. In the end, it is possible to open a file.

OS: Windows 8.1
Geany version: 1.38

**Comment by elextr** [comment]
LMGTFY - https://answers.microsoft.com/en-us/windows/forum/all/windows-no-disk-exception-processing-message/b1a67525-d5e8-46ae-9801-6b169547e656

**Comment by elextr** [comment]
If Geany works after you remove some unspecified driver then that driver is at fault, not Geany that just happens to perform an action that triggers the faulty driver.

**Comment by HJvT** [comment]
The driver is necessary for the functioning of the computer and automatically restored at reboot. It is is a driver for hard disks and SSDs; it is a product of Microsoft. As I stated before, earlier versions of Geany had no problem with it. I just tried Geany 1.37.1 again; it can open files without all these error messages, so the only explanation is, that the messages are caused by something that is changed in Geany 1.38.

**Comment by elextr** [comment]
Please provide the line from `Help->Debug messages` containing the Glib and GTK library versions for your copies of 1.37.1 and 1.38.  IIRC the major version of GTK changed from 2 to 3 between those releases.  I vaguely recall GTK3 may scan for devices to populate the open dialog in a way that GTK2 didn't, thus triggering your faulty driver.

But nobody else is reporting this problem with Geany 1.38 on windows, so its something related to the way your system is set up.  Since nobody else is having the problem, nobody can look at it to identify what action is triggering the messages. So you will have to debug it yourself, and by concentrating on Geany being the actual problem, rather than just the trigger, means you are likely to miss the real cause, and the proper solution (which after all is the desired end point).

**Comment by HJvT** [comment]
Here are the debug files:
[Debugmessages1.37.1.txt](https://github.com/geany/geany/files/8231545/Debugmessages1.37.1.txt)
[Debugmessages1.38.txt](https://github.com/geany/geany/files/8231546/Debugmessages1.38.txt)
Windows log files contain no further info.

**Comment by elextr** [comment]
Your debug messages show a lot of files are opened when Geany is started.  If no error messages occur when those are opened then it suggests that my suggestion above that its the open dialog that is triggering the dodgy driver.

**Comment by HJvT** [comment]
I used to have many more files open when I was working daily with Geany 1.37.1. Here is a debug log, made after opening 103 files in Geany 1.37.1.

[Debugmessages1.37.1.a.org.txt](https://github.com/geany/geany/files/8233678/Debugmessages1.37.1.a.org.txt)
1

There may be people having the same problem, but did not know how to write a bug report, or did not want to. I considered switching to another editor before writing this report. Others might have switched to another editor.

**Comment by elextr** [comment]
> I used to have many more files open

Its nothing to do with the number of files, if there are no error messages when starting it shows the problem has nothing to do with opening files, its the open file dialog, which as I said is in a library this project does not control.

That is also the conclusion that [this](https://bugs.launchpad.net/homebank/+bug/1740986) GTK app came to.

> There may be people having the same problem, but did not know how to write a bug report, or did not want to. I considered switching to another editor before writing this report. Others might have switched to another editor.

Possibly, or not.  Although none of the Geany developers use Geany on windows (even the guy who kindly makes the releases for windows), they do test it and have not seen the problem.  Unfortunately unless someone is able to provide a way of reproducing the problem, all we have available is that it only happens on your system, which we can't access, so can't do anything.
