### ISSUE TITLE
Geany won't run program until opened twice

### ISSUE THREAD

**Issue by aero1016** [geany/geany#3143]
After compiling and building a c-file on windows 11, when I execute the program, the terminal opens and is blank with the blinking cursor in the top left corner. I cannot input anything into the terminal and using ctrl c, closing the window, or stopping the program on geany eventually closes the window after a few seconds of loading. However, after exiting the terminal and running the program for a second time, my c-file runs fine and displays perfectly.

**Comment by eht16** [comment]
@aero1016 did this work for you? Can we close this issue?

**Comment by aero1016** [comment]
yes
