### ISSUE TITLE
Read-only button's location

### ISSUE THREAD

**Issue by yashpalgoyal1304** [geany/geany#3147]
i think read-only button is more suited under "File" menu, rather than "Document". what are your thoughts?

![image](https://user-images.githubusercontent.com/19423063/161387167-ffbf1a40-cf5d-4f35-aa50-bc629a119e83.png)

![image](https://user-images.githubusercontent.com/19423063/161387145-9509ddb7-38ba-49a9-87c1-00d950bb4bbb.png)

Geany: 1.38

**Comment by elextr** [comment]
Readonly does not apply to the file, it applies to the in memory document, so it is in the correct menu.

**Comment by eht16** [comment]
I agree with @elextr.

**Comment by yashpalgoyal1304** [comment]
umh, i think that:

+ document
contains the properties which are directly related to contents of the
document, so,
    * the language it is written in,
    * spaces it will contain,
    * how it's read
    * and so on.

while the

+ files menu
contains the operations related with file management, like
    * reading (open),
    * writing (save),
    * reverting (reload),
    * what more, the "properties" option under "file" contains the superset
of "read-only" as file mode/permissions
    * so, read-only felt to be fitting there

but okay. thanks for input :smile:

elextr wrote:

> Readonly does not apply to the file, it applies to the in memory document,
> so it is in the correct menu.
>
