### ISSUE TITLE
stash_group_add_string() doesn't handle default value anymore

### ISSUE THREAD

**Issue by eht16** [geany/geany#3149]
Since some time, `stash_group_add_string()` does not set the passed default value to the setting any longer if the setting is not found.

This might be related to cf77c8c0f1f0cc6ad7bf3132ea1d59639a7a83e7.

There is a real implication of this:
I noticed crashing Geany when the VTE setting `follow_path` is `true` and `send_cmd_prefix` is not set. This results in `vc->send_cmd_prefix` being `NULL` which then leads to crashes when commands are to be executed in the VTE (it should not crash even then, a fix for the VTE issue will follow).

But the root cause here is that it seems that the passed default `stash_group_add_string()` is ignored.

@kugel-, could you maybe have a look?

**Comment by eht16** [comment]
Just noticed, even if `send_cmd_prefix` is set in the config, its value is not read properly and `vc->send_cmd_prefix` remains `NULL`.

**Comment by kugel-** [comment]
So you you think stash_group_add_string is buggy or this issue is only with the send_cmd_prefix pref?

In #3151 the commit be739e28a6e29aeb08912af36620a4fb78b31176 was identified as first buggy commit, but that doesn't change stash_group_add_string as far as I can tell.

**Comment by elextr** [comment]
See possible patch posted to #3151

**Comment by eht16** [comment]
> So you you think stash_group_add_string is buggy 

This was my first guess but it seems wrong.

> In #3151 the commit [be739e2](https://github.com/geany/geany/commit/be739e28a6e29aeb08912af36620a4fb78b31176) was identified as first buggy commit, but that doesn't change stash_group_add_string as far as I can tell.

Yeah, be739e2 is more relevant and the patch in #3151 fixes reading the VTE settings for me.

**Comment by eht16** [comment]
Closing this one in favor of #3151.
