### ISSUE TITLE
Request: Texi texinfo files template to color code segments

### ISSUE THREAD

**Issue by estatistics** [geany/geany#3150]
Request: Texi texinfo files template to color code segments

I would like to translate texi  - texinfo files. However, no template in geany exists to color code segments. 
So this is a request.

Also, Is there a possibility when side-by-side panes are activated to lock them? How? Otherwise is also a request. 

thanks

**Comment by elextr** [comment]
No filetype exists for texinfo files so no highlighting is available, you could try creating a custom filetype (see the Geany manual) if any existing syntax highlighters are "good enough".

If no existing highlighting is suitable then, since the Lexilla highlighting library does not have a texinfo highlighter, one would need to be added to Lexilla in C++.

**Comment by elextr** [comment]
What do you mean "lock" side by side panes?

**Comment by estatistics** [comment]
So two files are open side by side but one vertical bar will move upward or downward in sync both files. 

This will be useful in translation project eg. horizontal comparison of english text with eg. spanish translated text without needing to move up / down two bars for syncing text for eyes.

**Comment by estatistics** [comment]
I have this file from textadept editor in lua format for highlighting texinfo text. 
It is hard to be implement into geany? 
If not, can you guide me?

[texinfo.txt](https://github.com/geany/geany/files/8438414/texinfo.txt)

**Comment by elextr** [comment]
> So two files are open side by side but one vertical bar will move upward or downward in sync both files.

It is not currently possible, and may be tricky as the scrolling is provided by the Scintilla editing widget we use, not Geany code, so there is a set of scroll controls for each side by side widget.  It may be possible to transfer position from one to another, but "somebody" has got to figure out how and implement it, and handle when its not the same file in both widgets, and ...

For custom filetypes, see the manual and examples like `data/filedefs/filetype.Scala.conf` `data/filedefs/filetype.JSON.conf` etc (basically any `filetypes.xxxx.conf` is a custom filetype).  I don't know texinfo so can't suggest what existing highlighter may be suitable.

> I have this file from textadept editor in lua format for highlighting texinfo text.
> It is hard to be implement into geany?

The highlighter is not part of Geany, it is part of the [Lexilla](https://github.com/ScintillaOrg/lexilla) project (a sister of the Scintilla project, see above) that Geany is only one user.  It has to be implemented in C++ so "difficult" depends on your fluency with C++.

**Comment by estatistics** [comment]
thanks
