### ISSUE TITLE
Option to allow replacing a sequence of characters by a line break

### ISSUE THREAD

**Issue by maettu-this** [geany/geany#3152]
I have a string like this: `123\r\nABC\r\nXYZ`

And would like an option like "replace ... by line break" allowing me displaying this string as, or converting this string to:
```
123
ABC
XYZ
```

**Comment by eht16** [comment]
This is already possible with Find->Replace.
For the find string you must escape the backslash and the option 'Use escape sequences' must be enabled.

E.g.:
![geany_replace_linebreaks](https://user-images.githubusercontent.com/617017/162278107-889b5c96-6333-4d58-949e-7edd5ff9f98c.png)
