### ISSUE TITLE
Global C Variables with "_Alignas" are not Recognized

### ISSUE THREAD

**Issue by DevynCJohnson** [geany/geany#3154]
**Version:** I am using the latest master-branch code as of today (Commit d9fbb8d).

I attached two screenshots to demonstrate the bug. Notice the variable list on the right in both images. In the first image, `gpio_pool` is not listed, but once `_Alignas` is removed, then `gpio_pool` appears in the variable list.

**With `_Alignas`:**

![Img_1](https://user-images.githubusercontent.com/4014076/162428828-857b62b4-fcdf-4b3b-b2d0-6837a231f379.png)

**Without `_Alignas`:**

![Img_2](https://user-images.githubusercontent.com/4014076/162428830-ff5414e8-98c9-43a3-a1db-261ec59737b3.png)

**Comment by elextr** [comment]
Appears to be fixed in current Git, probably by #3032.  If after the next release the problem remains feel free to re-open this.

**Comment by DevynCJohnson** [comment]
The pull-request you referenced was merged into the master branch on December 18, 2021. I am using the latest master-branch code as of today. Are you suggesting that there is another fix already on the way?

**Comment by elextr** [comment]
Alignas worked for me with git master, provide a minimal example of a source that compiles but shows the bug.
