### ISSUE TITLE
Position of drop-down menus with multi-monitors.

### ISSUE THREAD

**Issue by mmz65** [geany/geany#3180]
I have three monitors on my computer.
I have geany version 1.33 installed.  When I click any of the tabs, File, Edit, etc. the drop-down menu occurs just below the menu item.
I just installed geany version 1.38 tonight.  When I click on a menu item it opens on a different monitor.  In my case to the right of the geany editing window.

If you should need more info, just ask.

Thank you,

Mark

**Comment by elextr** [comment]
Always provide the top few lines of `Help->Debug Messages` with Geany version, GTK/Glib versions, and OS.

**Comment by mmz65** [comment]
Thank you for enlightening me. 

There are no "Debug" or "Error" messages. 
Using Geany 1.38 with GTK+ v3.24.30 and GLib v2.70.0 runtime libraries

OS is windows 11 build 22000.613 of version 21H2

Thank you again

**Comment by elextr** [comment]
Geany 1.33 was a GTK 2 build, but 1.38 is a GTK3 build, so probably there is some problem in GTK 3.24.30 on Windows 11.  

Unfortunately there is no official testing of Geany releases on Windows 10 or 11, let alone on multi-monitor setups.

If you can build Geany on windows it would be great for you to test different versions of GTK3.  I'm not a Geany windows user so can't help you with that, not sure if there is anyone who builds on 10 who might help, I doubt anyone does on 11.

**Comment by mmz65** [comment]
I have given this a lot of thought.  I have programed a lot on Linux but very little on Windows.  On Windows I have only used Python 2.7x.

So, I will have to decline your offer.  I hope you are able to find someone for this.

Mark
