### ISSUE TITLE
Python showing input() as invalid syntax

### ISSUE THREAD

**Issue by Linux-User12** [geany/geany#3188]
I don't know why this happens with Geany. but the input function shows up as an invalid syntax in the terminal for some reason.
![screen08](https://user-images.githubusercontent.com/104681349/166132456-75b1781c-0228-4b5d-b8dd-1da32c4d261f.jpg)
![screen09](https://user-images.githubusercontent.com/104681349/166132529-d657f655-6207-4645-b314-c94c02effc94.jpg)
 I tried the same code with Visual studio code and it executed just fine.
I'll show a screenshot.

**Comment by elextr** [comment]
To be clear, Geany doesn't say its invalid syntax, Python does.

```
Python 3.8.10 (default, Mar 15 2022, 12:22:08) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> name = "blah"input("blah")
  File "<stdin>", line 1
    name = "blah"input("blah")
                 ^
SyntaxError: invalid syntax
>>> 
```

**Comment by elextr** [comment]
And for me code produces the same error:

```
lex@fred77:/data/nexciidoc/attic$  /usr/bin/env /usr/bin/python3 /home/lex/.vscode/extensions/ms-python.python-2022.4.1/pythonFiles/lib/python/debugpy/launcher 37457 -- /tmp/foo.py 
  File "/tmp/foo.py", line 1
    name = "blah"input("blah")
                 ^
SyntaxError: invalid syntax
```
