### ISSUE TITLE
Tag parsing problem on C++ code with extern "C" block

### ISSUE THREAD

**Issue by sergey-gru** [geany/geany#3189]
In this fragment of C++ code geany found: main function only.

```C++
#include <iostream>

int main(int argc, char **argv)
{
	return 0;
}

extern "C"
{
    void f() {}
}
```

Geany 1.38 (build 2021-09-01 or later) Windows
Used GTK+ v3.24.30 and GLib v2.70.0 runtime libs

I've read this issue #349 and checked it again.

**Comment by elextr** [comment]
Fixed in latest Git
