### ISSUE TITLE
Icons that geany uses might be renamed in GNOME 42

### ISSUE THREAD

**Issue by Davidy22** [geany/geany#3198]
Screenshot and ongoing report against Fedora 36 here: https://bugzilla.redhat.com/show_bug.cgi?id=2072686

I suspect some amount of icons have been renamed in GNOME 42. May need to set fallbacks to avoid the wasteland of missing icons.

**Comment by elextr** [comment]
Geany uses GTK stock icons, not Gnome icons.  Yes stock icons are deprecated, but they are not removed, as evidenced by Geany compiling on that version of Fedora.  So pass the message back to Fedora to fix the stock icons.

**Comment by elextr** [comment]
To be clear stock icons are referenced by a `#define` in the GTK headers, not by a name.  Fedora should fix Gnome to map the icon names to the `#define` properly.

**Comment by Davidy22** [comment]
Actually my geany compiled from source on fedora 36 was carried over from the version I compiled from source on 35. I did do a recompile to confirm that it does still compile from source on 36.

**Comment by elextr** [comment]
Thanks for checking it compiles, I had assumed you were using a version distributed by Fedora which would have been re-compiled also.

**Comment by elextr** [comment]
@Davidy22 just to confirm, the version you compiled on Fedora 36 still does not show the icons?

**Comment by Davidy22** [comment]
Icons are not present in the fresh compiled version

**Comment by eht16** [comment]
@Davidy22 do you see any suspicious messages or warnings in Help->Debug Messages?

**Comment by jerryd** [comment]
I am glad you folks are looking into this one.  I was about to submit a new issue on this.  If you get a work around or fix I would be happy to test. So fustrating, but these things happen.

**Comment by eht16** [comment]
@jerryd are you experiencing the same problem?
If so, can you post the first lines with GTK and OS version from Help->Debug Messages and check if there are any messages related to the problem?

**Comment by jerryd** [comment]
08:37:49.460899: GLib-GIO DEBUG	: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
08:37:49.544756: GLib DEBUG	: unsetenv() is not thread-safe and should not be used after threads are created
08:37:49.560224: GLib-GIO DEBUG	: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
08:37:49.603071: Geany INFO		: Geany 1.38, en_US.UTF-8
08:37:49.603091: Geany INFO		: GTK 3.24.33, GLib 2.72.1
08:37:49.603144: Geany INFO		: OS: Fedora Linux 36 (Workstation Edition) ()
08:37:49.603153: Geany INFO		: System data dir: /usr/share/geany
08:37:49.603160: Geany INFO		: User config dir: /home/jerry/.config/geany
08:37:49.859331: Geany INFO		: Loaded GTK+ CSS theme '/usr/share/geany/geany.css'
08:37:49.861578: Geany INFO		: Loaded GTK+ CSS theme '/usr/share/geany/geany-3.20.css'
08:37:49.870445: Geany INFO		: System plugin path: /usr/lib64/geany

I also just noticed some gtk related patches coming in on F36 this morning, but they do not seem to fix this.

**Comment by jerryd** [comment]
I noticed that if I delete the local geany config folder in my home directory, on first start, geany does show the icons. After this, they go if I exit and then open geany again.

**Comment by techee** [comment]
I noticed the same problem with the macOS build when I tested meson - I assumed it was something with meson and wanted investigate later but it's probably something different.

When launched from the command-line, I get lots of messages like this:
```
(geany:33653): Gtk-WARNING **: 21:32:36.763: Error loading theme icon 'document-open' for stock: Icon 'document-open' not present in theme Adwaita
```
Appears to be this

https://gitlab.gnome.org/GNOME/adwaita-icon-theme/-/issues/184

and the linked GTK issue.

**Comment by elextr** [comment]
Ok, looks like GTK (not Gnome) might have removed the icons by accident and has now fixed it, if anybody can build GTK please test.  Might not get in Fedora 26 though, but maybe it will be a fix soon after.

**Comment by Davidy22** [comment]
I'm checking the log and it looks like the linked patch missed the window for the 42.0 release, I can report back after I see a .1 come down the pipe. Alternately I notice that these missing icons are being titled "legacy," maybe time for a switch to the shiny gnome 40 style icons in geany?

**Comment by elextr** [comment]
IIUC they are "legacy" in that they are for the deprecated stock icons interface.  That is one of many issues to be addressed if Geany ever supports GTK4, but no GTK experts have even opened a discussion on how to do it, let alone contributed the changes.

Geany is not a Gnome application, it is a GTK application, and as such works on many systems, not just Gnome ones, so Gnome icons are not available on many of them. And these are just the fallback icons if whatever theme your system uses does not provide them.  

On my Mint Cinnamon here, all Mint themes provide a version of the icons used by the Geany toolbar that change with the desktop theme and so match that theme nicely.  Fedora might do that for non-Adwaita themes, I don't know, but clearly it falls back to GTK if Adwaita is selected.

**Comment by jerryd** [comment]
It has been fixed on Fedora 36 distro with an update that brought in the gtk icons.

**Comment by elextr** [comment]
Thanks @Davidy22 and @jerryd
