### ISSUE TITLE
Problem with globbing on generating Geany global tags

### ISSUE THREAD

**Issue by elextr** [geany/geany#3205]
I can't get globbing to work (see comments on #3204):

```
lex@fred77:/tmp/temp$ ~/tmpgeanym/bin/geany -g -P tagsfile.C.tags "file*.h"
Unable to read file: Failed to open file “file*.h”: No such file or directory
Failed to create tags file, perhaps because no symbols were found.
lex@fred77:/tmp/temp$ ~/tmpgeanym/bin/geany -g -P tagsfile.C.tags "\"file*.h\""
Unable to read file: Failed to open file “"file*.h"”: No such file or directory
Failed to create tags file, perhaps because no symbols were found.
lex@fred77:/tmp/temp$ 

```

```
10:02:00: Geany INFO		: Geany 1.38 (git >= c8c8371e3), en_AU.UTF-8
10:02:00: Geany INFO		: GTK 3.24.20, GLib 2.64.6
10:02:00: Geany INFO		: OS: Linux Mint 20 (ulyana)
```

**Comment by elextr** [comment]
Its likely that everybody who uses globs is on Linux does not quote the quotes, and so the globs are interpreted by the shell so the code [here](https://github.com/geany/geany/blob/37d20a823fb1bca67cea57ef73aa9e64009d8138/src/tagmanager/tm_workspace.c#L456) is never used and maybe we can remove it?

**Comment by eht16** [comment]
Agree on removing it (AFAIU).
FTR, the commit introducing this feature is: https://github.com/geany/geany/commit/369c7bb51ca200aa80765ee28b4a9c56ee6284c2.

**Comment by elextr** [comment]
As it was introduced by Ntrel, is it needed on Windows?  Do Windows shells expand globs?  Do they remove quotes?  As its not documented has anyone ever used it on Windows?

**Comment by eht16** [comment]
I don't know how Windows shells (cmd.exe, PowerShell, whatever else there might be) handle quotes and globbing.

But I think it can be removed, nowadays it's very easy to get a Bash or similar good shell running on Windows and so this special handling in our code is probably not necessary anymore.

**Comment by elextr** [comment]
Ok, sounds a solution to me.
