### ISSUE TITLE
Suddenly highlighted bar in auto completion disappeared

### ISSUE THREAD

**Issue by abdulbadii** [geany/geany#3211]
Help me out, after update latest Arch (perhaps problem on gtk3), then suddenly the highlighted bar in auto completion disappeared

```
Geany 1.38
Using GTK+ v3.24.34 and GLib v2.72.1 runtime libraries

```
Please guide to right way to solve

**Comment by elextr** [comment]
If by "highlighted bar" you mean highlighting the selected item then it works for me 1.38 on Mint

09:30:23: Geany INFO		: Geany 1.38 (git >= c8c8371e3), en_AU.UTF-8
09:30:23: Geany INFO		: GTK 3.24.20, GLib 2.64.6

The autocomplete list is a normal GTK treeview and the selection is normal GTK select, so its style is set by GTK.  Perhaps your Arch updated the GTK theme you are using so highlighting is not visible.

**Comment by abdulbadii** [comment]
Adwaita-dark theme has that

Now solved after switch to Artix-dark
