### ISSUE TITLE
Project File Clears When Closing

### ISSUE THREAD

**Issue by puzzling2022** [geany/geany#3212]
Created a project. Added a header and source file. Closed project. Always have to re add source files after closing project.
Was wondering if this is normal or a problem with my computer.

**Comment by elextr** [comment]
> Always have to re add source files after closing project.

What happens if you re-open the project?

**Comment by puzzling2022** [comment]
Starts with untitled but doesnt load headers and source. 
The project file list in the project file clears when closing project on my computer.

**Comment by elextr** [comment]
WFM

1. Open Geany, no files open
2. Create project "foo" everything else default
3. Open two random files
4. Close project
5. Files close
6. Open Recent project foo.geany
7. files open again

Exactly what steps are you using?

**Comment by puzzling2022** [comment]
I'll test this in the morning but I think I tried that several times already. Only difference is I have my project in desktop folder so I change the path.

**Comment by puzzling2022** [comment]
Same thing even using default directory. Project list clears when closing project. Ill just never close project or try reinstalling operating system and see if that fixes.

**Comment by elextr** [comment]
Please post the lines near the top of `Help->Debug Messages` that give Geany, GTK, Glib and (on newer geany versions) OS.

```
17:22:51: Geany INFO		: Geany 1.38 (git >= 920ca78a4), en_AU.UTF-8
17:22:51: Geany INFO		: GTK 3.24.20, GLib 2.64.6
17:22:51: Geany INFO		: OS: Linux Mint 20 (ulyana)
```

**Comment by puzzling2022** [comment]
Geany 1.37 CUTF-8
GTK  3.24.28
GLIB 2.68.3
Alpine 3.14

One thing i noticed after reinstalling alpine, compiler, and geany is the project I had in geany was in project list even though project was not on hard drive. I installed without wiping drive.

**Comment by puzzling2022** [comment]
It worked properly when closing in project menu item but clears when right clicking the project and selecting close.

**Comment by puzzling2022** [comment]
Worked properly once. Now the source and headers remain in ide after closing in menu.

**Comment by elextr** [comment]
> One thing i noticed after reinstalling alpine, compiler, and geany is the project I had in geany was in project list even though project was not on hard drive. I installed without wiping drive.

The recent projects list is stored in your user config which is not cleared by installing or upgrading.

 > It worked properly when closing in project menu item but clears when right clicking the project and selecting close.

Right clicking the project where and selecting close?

**Comment by techee** [comment]
I believe this is fixed by the session-related patches of Thomas plus https://github.com/geany/geany/pull/3898. Closing.
