### ISSUE TITLE
Get nested section showing correctly in the panel of symbols 

### ISSUE THREAD

**Issue by terapackets** [geany/geany#3223]
Geany is my favorite editor.  I recently started using markdown to keep notes. However, it appears that I can't get nested sections working (see the snapshot).   A couple of issues

- The "#" is not removed in the title of the section
- "##" doesn't make a section as subsection, it appears at the same level as the (what's supposed to be) "parent" section

Any ideas?  Thanks in advance

![image](https://user-images.githubusercontent.com/40048070/174504102-84a66ecc-10b3-4ad8-8881-5a9f4da6b837.png)

20:41:06: Geany INFO		: Geany 1.32, en_US.UTF-8
20:41:06: Geany INFO		: GTK 3.22.30, GLib 2.56.4
20:41:06: Geany INFO		: System data dir: /usr/share/geany

It's on Ubuntu 18.04

**Comment by elextr** [comment]
WFM with

```
09:26:13: Geany INFO		: Geany 1.38 (git >= c8c8371e3), en_AU.UTF-8
09:26:13: Geany INFO		: GTK 3.24.20, GLib 2.64.6
09:26:13: Geany INFO		: OS: Linux Mint 20 (ulyana)
```

Always paste the those three lines from `Help->Debug messages` so we know what version you are using.

**Comment by elextr** [comment]
Looking at the issue title (please always describe completely in the text), if by "working" you mean show in the symbols pane then nested sections seem to show.

**Comment by terapackets** [comment]
Thanks @elextr  for the reminder, it's updated. Please let me know if there are other things needing update.

**Comment by elextr** [comment]
> "##" doesn't make a section as subsection, it appears at the same level as the (what's supposed to be) "parent" section

Ahh.

Fixed in current Git.

**Comment by terapackets** [comment]
@elextr  Which branch is it fixed?  Is it possible to download an executable version? I also have a windows PC (provided by company) where there is no build environment.  Thanks

**Comment by elextr** [comment]
Fixed in master, it is not released yet, but you can try the [nightly builds](https://geany.org/download/nightly-builds/) at your own risk.

**Comment by terapackets** [comment]
Really appreciate your super fast response @elextr !
