### ISSUE TITLE
modifiers (ctrl / shift) + mouse wheel don't work under wayland

### ISSUE THREAD

**Issue by Arnaudv6** [geany/geany#3226]
On linux, wayland (without xwayland), be it with weston or sway,
ctrl + mouse wheel will not zoom / zoom out
shift + mouse wheel will not scroll horizontally.

**Comment by Arnaudv6** [comment]
Also this is the place to say thanks for this awesome project: I use geany every day since 10 years I think, and I love it more than any editor/IDE.

**Comment by elextr** [comment]
Scroll wheel actions in the edit window are handled by the Scintilla widget.  It appears that Wayland reports all scroll wheel movements as smooth scrolling, not normal scrolling.  Scintilla has code to differentiate that, but has to be built on a system with GDK that advertises Wayland support and has to detect Wayland at runtime as well before that code is used.  But if it is not then IIUC the scroll wheel inputs will be lost.

So it depends on where you got your Geany from and where it was built.

**Comment by Arnaudv6** [comment]
OK, this helps, thanks @elextr. I indeed have the same problem with SCiTe.
Will ask upstream if there is an env var or so to work-around. Closing

**Comment by Arnaudv6** [comment]
Nope, sorry. I lost interest and switched to [micro](https://github.com/zyedidia/micro).
Hopefully that will prove future-proof.

**Comment by tobip** [comment]
Alright, thanks. micro is awesome! But also doesn't allow shift + scroll haha

**Comment by Arnaudv6** [comment]
right :smile:
