### ISSUE TITLE
Current state and plans of front-end development in Geany

### ISSUE THREAD

**Issue by martonlente** [geany/geany#3229]
Hello,

I'm new to Geany, and I really like the core application. I agree that it hits the sweet spot between features and simplicity (as the website intro suggests), however I'm surprised that out-of-the-box how hardly it's suitable for front-end development. I put quite some time to configure Geany for better front-end development support and also created a new repo for it: [geany-config-front-end-development](https://github.com/martonlente/geany-config-front-end-development) (improving an old one), but it's still far from perfect.

I've some concrete questions to someone who knows Geany as a product better than I do:
- Geany supports adding Global tags files, and the documentation suggests to use the Tagmanager format. **Using Geany, from what source should users generate global tags files for the cleanest possible results,** and least manual work e.g. for generic autocompletions support for CSS3 and JavaScript ES6, or libraries like jQuery?
- Geany is a mature product, but without shipping these configuration files (filedefs for popular files like LESS and SCSS, and tags and snippets for CSS, HTML and JS), it might feel very incomplete for many. **What's behind the decision not shipping these files by default** (which to me – maybe naively – seems like a small contribution to a complex application, but one that would hugely improve its usability)?

I'm asking these primarily from curiosity, and to find out the best possible way of contribution if I keep improving the repository above.

Thanks in advance,
Márton Lente

**Comment by elextr** [comment]
First of all, Geany is a volunteer project, "plans" only exist in the minds of those who contribute.  Support for any specific use-case needs someone to contribute it, so its not "surprising" that it has less support for web front end development if nobody has contributed it.

Also as Geany is written in C, most of the contributors are C programmers, so they can have problems understanding requirements for support for the non-C languages, and humans tend to reject what they don't understand, even improvements for C++.

For tags files, Geany now reads ctags format files, and might soon transition to the ctags library to do so, see #3049.  So any tool that generates compliant ctags format should be usable after that is merged.  There are lots of tags files on the [wiki](https://wiki.geany.org/tags/start) including Js and Jquery.  

Geany supports about 60 programming languages and 10 markups, shipping tags for all the languages and standard and popular libraries would be huge, the tags automatically included are mostly those for Geany development (C, HTML & Php for Geany website) and ones that snuck in in pre-history and are retained for backwards compatibility.  The same argument goes for included snippets.

Anybody can contribute to the wiki (just be patient with the account approval bot, its a human so it may be slow :-), just don't overwrite existing contributions, even if you think yours are better for the same thing, just add them as additional, overwrites may be reverted.

**Comment by martonlente** [comment]
Hello,

Thanks @elextr for the detailed clarifications! :slightly_smiling_face: 

It's good news that Geany is about to transition to the ctags library soon – as far as I understand it opens up a more maintainable way of managing / maintaining tags.

I understand the language support limitations, though I still think it would be hugely beneficial to the product to ship at least the currently available 'best' config helper files for popular languages, that are scattered around the internet. For a new user who wants to configure Geany for productive web development work, it might currently take days of research to bring the software to a usable level. Bundling the existing support files for popular languages I think would really make sense. (I know how open source works, and I'm only speaking from the product's perspective – it isn't a critique whatsoever.)

I might archive the repo above until I do further research.

**Comment by elextr** [comment]
> at least the currently available 'best' config helper files for popular languages

Two comments:

1. what is "popular", C, C++, Javascript, Go, Rust, Typescript, etc etc
2. what is "best", its irrelevant if its not for the language the user uses, it just wastes their time downloading it.

It totally depends on the users use-case, the items you have suggested are totally useless to me, and something I might want like Boost++ is useless to you.

> to ship

The Geany project does not "ship" anything except an installer for Windows because there is no alternative source for it, and how long that will continue unless some more contributors step up is unknown since the very nice guy who does it no longer uses it on Windows himself.  

Similarly a contributor provides one for Macos, but it is in a separate repository, not "part" of Geany.  For all other systems it is not provided by the Geany project.  

But there is nothing stopping those distributing Geany or people like you from distributing or accumulating additional material to configure it for specific use-cases, but its not the projects intention to favour specific user groups.
