### ISSUE TITLE
Build enum members not documented in the plugin API

### ISSUE THREAD

**Issue by elextr** [geany/geany#323]
The enums used to access the build commands were added to the plugin API.  But the individual members were not doxygen documented so are _technically_ not in the API (though that doesn't stop the C compiler using them :)

This issue is a TBD reminder.

**Comment by eht16** [comment]
@elextr do you remember what exactly was missing here?
Looking at https://www.geany.org/manual/reference/build_8h.html, it seems most enums are documented (maybe in the meantime).

**Comment by elextr** [comment]
Ummm, yeah, happened in the meantime, closed
