### ISSUE TITLE
I am unable to find Makefile.am

### ISSUE THREAD

**Issue by brewmanz** [geany/geany#3233]
In [https://geany.org/manual/hacking.html](url) (dated 2016-07-26 18:15:59Z) under `[filetypes.* configuration file](https://geany.org/manual/hacking.html#id32)`
it mentions
`Don't forget to add the newly created filetype file to data/Makefile.am`
but I cannot find `Makefile.am` anywhere on my Ubuntu 20.04 computer when filtered by (case ignored) `geany`.
I am using `geany 1.36 (built on 2020-03-22 with GTK 3.24.14, GLib 2.64.1)`
I realise that that is 2 years old, but would mention that it's the latest that Ubuntu 20.04 LTS seems to know about.

**Comment by elextr** [comment]
Assume your reference is [this](https://geany.org/manual/dev/hacking.html#filetypes-configuration-file), it doesn't link.

Hacking (and Makefile.am) is for working on Geany source, so you need to get Geany source.  An install from a distro won't have source.

But the section I noted above is for adding a builtin filetype, needing code changes in Geany (which you would not be able to make without source anyway) not a custom filetype as discussed in #3232.  

So I suspect this is not what you want to do.

Yes Ubuntu LTS is well long term stable, ie it doesn't update to newer versions, those go to the non-LTS first.

**Comment by brewmanz** [comment]
Thanks for that. It's just difficult finding which bits are relevant when comments say `# For complete documentation of this file, please see Geany's main documentation`; technically true but practically not helpful. 
I may yet resort to forking the source, but still got a few more rabbit holes to jump down before I exhaust custom filetypes.

**Comment by elextr** [comment]
I assume you are still working on Awk.  There is no awk specific lexer in lexilla, so (unless you write one) you are stuck using a lexer that is "close enough".  So the only reason to add a built-in type for awk would be to get the ctags symbol parser for awk.  I'm not sure how up-to-date Hacking is about adding a parser, probably best to examine any recent PRs that do it.

**Comment by brewmanz** [comment]
I'm currently working on making an 'awk profile that looks perl with extra/different keywords' approach.

**Comment by kugel-** [comment]
I think the original issue is resolved.
