### ISSUE TITLE
Session lost when upgrading from 1.38

### ISSUE THREAD

**Issue by b4n** [geany/geany#3236]
I just pulled and built master, and installed it over my previous (olde…) 1.38 (git >= 75d3c9f12) (my head was actually at 11a1f32fd490b3918d069f0d05cca5bbc6c4b5ad, not 100% sure what was really installed, but it ough to be very close to 1.38).

Anyway, when restarting Geany, it didn't restore any file from my session.  I see *No user session file found, trying to use configuration file.* but nothing gets loaded then, although my *geany.conf* does 120 `FILE_NAME_%d` entries.

I didn't investigate yet and unfortunately don't have time to right now, but I guess it has to do with session-split not properly falling back somehow.

**Comment by eht16** [comment]
Yeah, I had similar problems with the list of active plugins (https://github.com/geany/geany/pull/3183#issuecomment-1111138041).

@kugel- promised to provide some sort of migrtion before releasing. I added a corresponding TODO in the project https://github.com/geany/geany/projects/4.

**Comment by kugel-** [comment]
@b4n's case should work, there seems to be a bug.

But generally, the current planning is to have a one-time migration if session.conf doesn't exist yet to cover upgrading from 1.38 to the next release (i.e. read all "session prefs" from geany.conf as if it were session.conf). After that, if session.conf already exists, no further migration is planned. I.e. if you track GIT master.

**Comment by kugel-** [comment]
@kugel- I looked into this and created a fix, see #3264
