### ISSUE TITLE
Syntax highlighting within things like strings and backticks

### ISSUE THREAD

**Issue by Lantizia** [geany/geany#3248]
Hi,

This has come up before on the Sourceforge site (since 2011) but it seems GitHub is now the place to log issues... and it's also come up on Stack Exchange too...

[https://sourceforge.net/p/scintilla/feature-requests/815/](https://sourceforge.net/p/scintilla/feature-requests/815/)
[https://stackoverflow.com/questions/20190275/geany-syntax-highlighting-in-double-quotes](https://stackoverflow.com/questions/20190275/geany-syntax-highlighting-in-double-quotes)

And what is interesting about the content of those two pages is...

a) The SourceForge feature request got labelled as it being a thing that Scintilla / Lexilla needed to fix... and yet...
b) A Notepad++ user on Stack Exchange notes that Notepad++ copes with this just fine (and they also use Scintilla), so is this a workaround they have (in which case, can Geany work around this too?) or has Scintilla / Lexilla since improved?
c) Another Stack Exchange user reports this has been fixed since version 1.23.1... and yet I'm running 1.38 and the issue is still there.

This feature would be particularly handy when working with shell scripts when often you've got variable names in double quoted stings or you've got code in backticks or subshells (e.g. foo=$(echo "this $stuff should $be highlighted") or foo=\`echo "this $stuff should $be highlighted"\`).

If this has been raised on GitHub already, please mark this as a dupe... although I couldn't find anything myself.

**Comment by elextr** [comment]
Using the Perl example from the SO quoted above, `$newvar` is styled differently to the rest of the string by the current git Geany.  Because Scintilla/Lexilla newer than 3.x required a newer C++ compiler version than some older stable distros provided, Geany did not update to version 5 until after 1.38 was released.

Closing as completed
