### ISSUE TITLE
Bookmarks lost on Copy/paste operation

### ISSUE THREAD

**Issue by 00AR** [geany/geany#3249]
OS: Ubuntu 22.04 LTS
Geany 1.38
Using GTK+ v3.24.33 and GLib v2.72.1 runtime libraries

**Issue:**
When some lines are copied, and pasted on a new line, bookmarks are not preserved and shown on the pasted text.
For example: 
![Screenshot from 2022-08-10 21-19-40](https://user-images.githubusercontent.com/96364226/183977053-1946d3bd-940c-463e-8c89-d3de9738db96.png)

In the above image, **line 9 and line 11** should have been bookmarked automatically.  

**Expected behavior:** when copied lines are pasted on a new line, then bookmarks should be preserved and applied on respective lines automatically.
For example:
![Screenshot from 2022-08-10 22-42-21](https://user-images.githubusercontent.com/96364226/183977108-b0b6e085-de75-4a39-b1c7-1b5440fa637d.png)

Lines 9 and 11 are automatically bookmarked along with the pasted text when keybinding "ctrl + V" is pressed.

**Comment by elextr** [comment]
Copy and paste is only intended to copy/paste file contents, it does not and is not intended to copy metadata such as bookmarks which are not part of the file text.

Closing as invalid.
