### ISSUE TITLE
unnecessary "*" in the code, beside the comment.

### ISSUE THREAD

**Issue by NilankanBetal** [geany/geany#3252]
https://github.com/geany/geany/blob/34ce1724a510e86f197ec14d60e89f6bc10eb440/src/tagmanager/tm_source_file.c#L115

**Comment by elextr** [comment]
This is a [doxygen](https://doxygen.nl/) comment used to generate the plugin API documentation.

Closing, not an error

**Comment by NilankanBetal** [comment]
Okay.

**Comment by NilankanBetal** [comment]
Okay, sorry, I was unaware about this before.
