### ISSUE TITLE
geany plugins install on AlmaLinux release 9.0 (Emerald Puma)

### ISSUE THREAD

**Issue by aliaj00** [geany/geany#3260]
Hi Guys,

i have installed geany from:
Last metadata expiration check: 0:37:25 ago on Mon 22 Aug 2022 11:40:15 AM EDT.
Installed Packages
Name         : geany
Version      : 1.38
Release      : 2.el9
Architecture : x86_64
Size         : 9.8 M
Source       : geany-1.38-2.el9.src.rpm
Repository   : @System
From repo    : epel
Summary      : A fast and lightweight IDE using GTK3
URL          : http://www.geany.org/
License      : GPLv2+ and MIT
Description  : Geany is a small and fast integrated development environment with basic
             : features and few dependencies to other packages or Desktop Environments.
             : 
             : Some features:
             : - Syntax highlighting
             : - Code completion
             : - Code folding
             : - Construct completion/snippets
             : - Auto-closing of XML and HTML tags
             : - Call tips
             : - Support for Many languages like C, Java, PHP, HTML, Python, Perl, Pascal
             : - symbol lists and symbol name auto-completion
             : - Code navigation
             : - Simple project management
             : - Plugin interface
but there are no plugins available.

then i downloaded the one from the git repo and running the ./autogen fails with:
hecking for xgettext... (cached) /usr/bin/xgettext
checking for catalogs to be installed...  be ca da de el es fr gl it ja kk nl pt pt_BR ru tr uk zh_CN
checking for pkg-config... /usr/bin/pkg-config
checking pkg-config is at least version 0.9.0... yes
checking for GEANY... no
configure: error: Package requirements (geany >= 1.29) were not met:

Package 'geany', required by 'virtual:world', not found

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables GEANY_CFLAGS
and GEANY_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.

i have the lib on:
#locate libgeany.so
/usr/lib64/libgeany.so
/usr/lib64/libgeany.so.0
/usr/lib64/libgeany.so.0.0.0

geany executable:
# which geany
/usr/bin/geany
geany version:
# geany --version
geany 1.38 (built on 2022-01-20 with GTK 3.24.31, GLib 2.68.4)

Is this a bug?

**Comment by elextr** [comment]
Packages are not made by the Geany project, you need to query the distro, but some general comments:

1. plugins are normally in a separate package (and/or individual packages each), although the "core" plugins are usually included.
2. many distros have a separate "dev" package for Geany, and you need that to build plugins.

**Comment by frlan** [comment]
I'm closing this issue
