### ISSUE TITLE
Feature Request: Press the ALT key to hide/show (toggle) the menu bar

### ISSUE THREAD

**Issue by Yekutiel** [geany/geany#3270]
I would like to press the ALT key to hide/show (toggle) the menu bar.

This feature exists in the text editor named **xed**. Here's the code apparently used to do so in **xed** [Add an option to hide the menubar](https://github.com/linuxmint/xed/commit/1252eb73b34cd440cb1f8c1e01dc5c3fb4881b90).

**Comment by Yekutiel** [comment]
I solved my problem by following these instructions... https://github.com/geany/geany/issues/633#issuecomment-1030634638

Good grief! I read the absurd debate at https://github.com/geany/geany/issues/633 and thought to myself, "Yeah, many FOSS devs are self-centered jerks!"

Who do you think is actually using Geany? 85 year old grandmas? Geany isn't a tool for the masses. Sheesh. Think of the audience.

Also, put in a command that users can run from a terminal like `geany --toggle_menu_bar`. That way if users forget the keybinding, if they  search on Google for something like, "How can I display my menu bar in Geany" they will find `geany --toggle_menu_bar`. Over time `geany --toggle_menu_bar` would likely become the top search result.

The inane debate about whether to include this functionality or not, is utterly absurd. The feature should be included. Simply have users type something like, "I realize I'll need run `geany --toggle_menu_bar` in a terminal if I forget by keybinding.

Self-centered FOSS devs. SMH.

**Comment by kugel-** [comment]
Happy you found a solution that works for you. Now you can leave this peaceful place and harass someone else.

**Comment by Yekutiel** [comment]
Ah yes. Another delightful FOSS developer!
