### ISSUE TITLE
[Feature Request] Git Bash as the VTE for Windows version of Geany

### ISSUE THREAD

**Issue by zhaolinlau** [geany/geany#3279]
Since Git Bash supports Linux, Windows and Mac, is that possible to add Git Bash as VTE for Geany?

**Comment by elextr** [comment]
VTE is a terminal emulator widget, Git bash is a shell, that runs inside the terminal emulator.  As such, no, git bash cannot replace VTE (which isn't available for Windows in any case).

On platforms where VTE is supported you can run git bash in the VTE by setting it as the shell in `Menu ->Edit->Preferences->Terminal->Shell`

**Comment by zhaolinlau** [comment]
> VTE is a terminal emulator widget, Git bash is a shell, that runs inside the terminal emulator. As such, no, git bash cannot replace VTE (which isn't available for Windows in any case).
> 
> On platforms where VTE is supported you can run git bash in the VTE by setting it as the shell in `Menu ->Edit->Preferences->Terminal->Shell`

Geany(Windows version) doesn't have Terminal option in the Preferences

![image](https://user-images.githubusercontent.com/68846168/188817619-5f9ddcfe-8476-46fa-b17a-f040bd713352.png)

**Comment by elextr** [comment]
> On platforms where VTE is supported...

I noted above it that VTE is not available for Windows, so its not supported in Windows.

**Comment by zhaolinlau** [comment]
> > On platforms where VTE is supported...
> 
> I noted above it that VTE is not available for Windows, so its not supported in Windows.

ops sorry, didnt see that
