### ISSUE TITLE
"Rename" should preserve timestamp if file had no changes 

### ISSUE THREAD

**Issue by cousteaulecommandant** [geany/geany#3281]
If a file hasn't been modified, "Rename" should (in my opinion) only move the file to the new location, without affecting its "modified" time.
(This would be equivalent to closing the file, moving it manually, and then opening it again, but in a single step.)

**Comment by elextr** [comment]
Geany rename uses the OS `rename()` function (via Glib g_rename) and that sets the times, Geany does not directly control the times.  The `rename()` function is a POSIX function.

The POSIX standard notes about `rename()` "Some implementations mark for update the last file status change timestamp of renamed files and some do not. Applications which make use of the last file status change timestamp may behave differently with respect to renamed files unless they are designed to allow for either behavior."

So its undefined if the OS sets the time, and its not anything Geany can control.
