### ISSUE TITLE
Feature request: incremental filtering

### ISSUE THREAD

**Issue by data-man** [geany/geany#3294]
SciTE has this feature:

![ksnip_20220510-083755](https://user-images.githubusercontent.com/1754269/190567826-74a7e0b4-e955-4e09-b998-16b54f5fb69d.png)

![ksnip_20220510-084123](https://user-images.githubusercontent.com/1754269/190567890-d74b3082-6458-4ea1-87c1-1733817130c5.png)

**Comment by elextr** [comment]
The version of Scite available on my distro does not have any "filter" capability, so I presume its a fairly recent capability.

Do not point at other tools features, requiring others to install them to find out what you are talking about. It is unlikely to get a response.

If you are proposing a feature describe the behaviour you are proposing.

**Comment by data-man** [comment]
> The version of Scite available on my distro does not have any "filter" capability, so I presume its a fairly recent capability.

SciTE, Released 23 September 2021.
>* Add filter view and filter mode for replace strip. [Feature #1249](https://sourceforge.net/p/scintilla/feature-requests/1249/).
>* For incremental searches and filter view, remember each search in the history combo-box. However, searches that are a prefix or suffix of the most recent history item replace that item so that typing or backspacing doesn't fill the history with partial values.

> If you are proposing a feature describe the behaviour you are proposing.


https://user-images.githubusercontent.com/1754269/190578360-66861c66-d580-453b-a77b-a0566473f9c2.mp4

**Comment by elextr** [comment]
> SciTE, Released 23 September 2021.

Ok, thats too new for my LTS distro.

I said "describe", the video does nothing to explain what the requirements of the feature are and leaves me guessing whats happening.

IIUC what you want is to perform an incremental search (which would select the next match and mark all other matches as the search text is typed) but then show only lines that contain a match?

Geany does not have an incremental search which would be a prerequisite for such a filter, and would be a good addition by itself.  

The current searching facilities are fairly old fashioned and could do with an update, even if its only for text and not regex searches.  IIRC there have been discussions about adding it in the past, but nobody came up with an implementation and associated UI (or not an acceptable one).

**Comment by techee** [comment]
> IIUC what you want is to perform an incremental search (which would select the next match and mark all other matches as the search text is typed) but then show only lines that contain a match?

I just tried and this is what the feature does - it removes lines not containing the entered text. For a file with a number from one to nine on each file, one gets this after filtering for 'e':

<img width="296" alt="Screen Shot 2022-09-16 at 11 42 02" src="https://user-images.githubusercontent.com/713965/190609160-a2d7783a-9a83-404a-b095-21ae4f4300dc.png">

Could probably be implemented in a non-incremental manner too.

> The current searching facilities are fairly old fashioned and could do with an update, even if its only for text and not regex searches. IIRC there have been discussions about adding it in the past, but nobody came up with an implementation and associated UI (or not an acceptable one).

I personally prefer normal search to the incremental one but I understand why it may be preferred by others. If it gets implemented, we could keep both versions like SciTE does: "Find" and "Incremental Search".

**Comment by elextr** [comment]
> we could keep both versions like SciTE does: "Find" and "Incremental Search"

Agree, adding an upgrade doesn't mean removing the existing facilities.
