### ISSUE TITLE
Move sidebar's tabs to message window

### ISSUE THREAD

**Issue by valeriosetti** [geany/geany#3308]
I would like to have the Tree Browser plugin and Symbols tab shown at the same time on the UI. In order to achieve this configuration I would say that a possibility is to keep the Tree Browser on the sidebar, while moving the Symbols one to the message window. Isn't it?
Is there a way to get this configuration? Because I tried to search both on the manual and online, but I didn't find a way to do this...

**Comment by elextr** [comment]
There is currently no way of doing this.  IIRC there was a suggestion to have more than one sidebar and allow tabs to be split across them.  This becomes even more useful when using a plugin that adds its own additional sidebar tab.

Unfortunately nobody ever implemented it AFAIK.

**Comment by valeriosetti** [comment]
Too bad :(
Thanks for your reply!
