### ISSUE TITLE
Geany for ubuntu: no output terminal pop after running and compling c++ codes

### ISSUE THREAD

**Issue by chuanchang** [geany/geany#3317]
Using virtualbox 7.0 to install ubuntu linux then run and compile hellow world c++ code with geany, 
and then there is no output terminal window pop.

$ geany -V
geany 1.36 (built on 2020-03-22 with GTK 3.24.14, GLib 2.64.1)

$uname -a
Linux ubuntu 5.15.0-52-generic #58~20.04.1-Ubuntu SMP Thu Oct 13 13:09:46 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by elextr** [comment]
Have you installed the terminal program set in `Edit->Preferences->Tools->Terminal` or reset the setting to a terminal that is installed?  Some distros do not install xterm by default.

**Comment by chuanchang** [comment]
> 
Hey elextr, It's okay to run the same c++ codes with Code::Blocks in the same ubuntu virtualbox VM, you mean I need extra configuration in geany? thanks a lot!

**Comment by chuanchang** [comment]
BTW, the xterm has been installed in customized ubuntu linux.

**Comment by chuanchang** [comment]
Need I enable 'Executue programs in the VTE' in Terminal configuration? thanks!

**Comment by chuanchang** [comment]
> Need I enable 'Executue programs in the VTE' in Terminal configuration? thanks!

Although there is no terminal window pop for inputing or debugging, it works after enabling  'Executue programs in the VTE', thanks a lot!
