### ISSUE TITLE
Cannot paste to a Qt app under KDE

### ISSUE THREAD

**Issue by alex65536** [geany/geany#3320]
I am using Geany 1.38 under KDE Plasma. If I try to copy some text from Geany and paste it into a KDE app, then nothing is pasted.

The issue only happens with the main text editor, as copying and pasting the text from Notes or Terminal works fine. Seems that there is something with Scintilla, as SciTE fails to paste into Qt apps either.

**Comment by elextr** [comment]
> as SciTE fails to paste into Qt apps either.

Then check if Scintilla has recently fixed anything in that area https://sourceforge.net/projects/scintilla/ otherwise report it there.

**Comment by alex65536** [comment]
I have reported the bug upstream:

https://sourceforge.net/p/scintilla/bugs/2361/

IDK whether this issue should stay open now, but I intend to reopen it when the bug will be resolved on the Scintilla side.
