### ISSUE TITLE
'Go to symbol definition' not working for modern C++ function declaration.

### ISSUE THREAD

**Issue by Gweno** [geany/geany#3325]
The  'Go to symbol definition' functionality works well for the classic way when jumping from a definition from/to a declaration written in the traditional way with the type in front of the function.
But it doesn't if the type is 'auto',
Example with C++ source file and a header file:
`//myfunctions.cpp
#include "myfunctions.h"
auto myNewFunction()->void{
    // do someting;
}
void myOldFunction(){
    // do something;
};

//myfunctions.h
auto myNewFunction()->void;
void myOldFunction();
`
Definition of "myNewFunction" not found.
So the work around is to "Find Document usage" and pick the definition in the header but I really like to CTRL+T or CTRL left click to jump to/from defintion/declaration.
Thank you

**Comment by elextr** [comment]
Works with latest Git Geany `Geany 1.38 (git >= 967e00450), en_AU.UTF-8`
