### ISSUE TITLE
rename documents

### ISSUE THREAD

**Issue by yashpalgoyal1304** [geany/geany#3326]
### what is it
having an option to rename documents from within geany will help a lot

### what does it address
the problem of renaming externally, then having to close the existing "not found" file tab in geany (https://github.com/geany/geany/issues/1994) then reopening the renamed one

### where can it be implemented
* in the documents sidebar panel - the files plugin should use it too
* ~~in the context meny of the tab bar maybe?~~
* ~~in the files menu maybe?~~

**Comment by yashpalgoyal1304** [comment]
wait, https://github.com/geany/geany/issues/3281 - seems geany already has rename, but where?

**Comment by elextr** [comment]
`File->Save As` use the `Rename` button.

**Comment by elextr** [comment]
Closed as existing

**Comment by yashpalgoyal1304** [comment]
> `File->Save As` use the `Rename` button.
> Closing as existing

umh, i really think that an entry for this should be added to the context menu of documents or files tab on sidebar
