### ISSUE TITLE
Show keyboard shortcuts in the hover tooltips for icons on toolbar

### ISSUE THREAD

**Issue by yashpalgoyal1304** [geany/geany#3328]
* Currently, the tooltips show only the description, 
* if the keyboard shourctut feels too much space taking, then the short notation can be used as hints - like for example: `^↑s` for `ctrl+shift+s`

https://user-images.githubusercontent.com/19423063/200189329-02dc1c92-87da-429c-88ab-d1249b63c26b.mp4

**Comment by elextr** [comment]
Well, most of the toolbar buttons don't actually have shortcuts.  AFAICT only colour chooser and focussing the search entry have shortcuts.

Certainly some buttons activate the same functionality as menu items, most of which do have shortcuts (but not "New from template" for example), but some toolbar buttons have slightly different functionality, eg search uses its own entry, not the find dialog, and it does have its own shortcut to focus that entry.

Currently all toolbar tooltips are hard coded static strings, but keybindings are changable, so "somebody" would have to add code to update the shortcut dynamically, either as the keybinding is changed or as the tooltip is displayed.

**Comment by yashpalgoyal1304** [comment]
> Well, most of the toolbar buttons don't actually have shortcuts. AFAICT only colour chooser and focussing the search entry have shortcuts.
> 
> Certainly some buttons activate the same functionality as menu items, most of which do have shortcuts (but not "New from template" for example), but some toolbar buttons have slightly different functionality, eg search uses its own entry, not the find dialog, and it does have its own shortcut to focus that entry.

well, that makes sense
