### ISSUE TITLE
Unable to locate a Java Runtime that supports javac

### ISSUE THREAD

**Issue by maddalena06** [geany/geany#3331]
Hello community.
I'm Maddalena, a third-year high school student.

At school I am learning Java with Geany.
To practice,  I installed Geany 1.38 on my MacBook Pro M1 MacOS Big Sur 

I have a problem and I don't know how to fix it:

"The operation could’t be completed. Unable to locate a Java Runtime that support javac. Please visit http://www.java.com/ per information on installing java"

From the java site I downloaded java and then installed it but it doesn't work. When I run the Geany compiler it doesn't work.

Please help me and tell me step by step what to do.

Thank you very much. 

<img width="836" alt="Schermata 2022-11-09 alle 21 39 00" src="https://user-images.githubusercontent.com/117862880/200937130-9736aabb-14da-4790-a925-91ec3a69d573.png">

**Comment by elextr** [comment]
Does the `javac` command work at the command line?

**Comment by maddalena06** [comment]
Hi alextr, 
I opened the terminal and typed javac.
Please could you tell me step by step what to do?
Thank you very much. 


<img width="567" alt="Schermata 2022-11-10 alle 22 08 16" src="https://user-images.githubusercontent.com/117862880/201206556-7da88d1f-8182-4166-979a-d2d695b283ce.png">

**Comment by elextr** [comment]
The problem would appear to be with the install of java, not anything to do with Geany.  Not sure there are any java experts in the Geany community, you might be better to ask on a java forum.

**Comment by maddalena06** [comment]
Thank you.
