### ISSUE TITLE
Feature Request: Preference option for file display size

### ISSUE THREAD

**Issue by paxmanchris** [geany/geany#3344]
Correct me if I am wrong be it seams that open file names max display length is essentially hard coded to 30. So my feature request is to be able to set this number as a preference.

what I have found if I am reading the code correctly. The code related to this is in [document.c](https://github.com/geany/geany/blob/master/src/document.c#L412)

In this function,  it checks for the length you want and defaults to 30 if it is lower than 0
**document_get_basename_for_display**
```
if (length < 0)
		length = 30;
base_name = g_path_get_basename(DOC_FILENAME(doc));
short_name = utils_str_middle_truncate(base_name, (guint)length);
```

and this function simply just calls it with `-1`. I believe this is where a preference should be referenced instead

**document_update_tab_label**
```
short_name = document_get_basename_for_display(doc, -1);
```

**Comment by elextr** [comment]
I don't know why it is truncated, its lost in the mists of time, maybe one of the Geany elephants with long memories might know.  

Possibly because long filenames could make it hard to navigate directly by clicking tabs since only a few would show, but thats what the right click menu is for, and its not truncated AFAICT, or the document page in the sidebar.

There are three places that `document_get_pathname_for_display()` is called and its in the plugin API, so it can't change, but yes having the relevant calls reference a new setting is ok, PRs are welcome.

**Comment by eht16** [comment]
> I don't know why it is truncated, its lost in the mists of time, maybe one of the Geany elephants with long memories might know.

It was requested a "few" years ago :)
https://sourceforge.net/p/geany/bugs/298/
 
> There are three places that `document_get_pathname_for_display()` is called and its in the plugin API, so it can't change, but yes having the relevant calls reference a new setting is ok, PRs are welcome.

+1
This could be a good starter task for someone trying to contribute and/or get familiar with the code.

@elextr do we want to introduce a new label for things like "easy to start with"?

**Comment by elextr** [comment]
> It was requested a "few" years ago :)

Ahh, but the reason given in the SF bug `... tab for this and __all others__ files is too big...` doesn't happen now, in GTK3 tabs are different sizes, so only the long filename gets big.  Or maybe its a setting in my theme?  Anyway its possible.

Note its `document_get_basename_for_display()`, not `document_get_pathname_for_display()`, my bad.

I was gonna suggest -1 mean "don't truncate" but although Geany doesn't use that, many plugins do :-( but setting it to a very big number would be effectively the same so no need.  The setting default could be 100000 or similar.

> do we want to introduce a new label for things like "easy to start with"?

Done, wording stolen from similar Julia label, and coloured green for go :)
