### ISSUE TITLE
Idea: Submenus for the "New" Menu

### ISSUE THREAD

**Issue by DevynCJohnson** [geany/geany#3357]
In Geany's `./template/files/` directory, I think it would be useful to be able to have subdirectories containing files that a user may want to group together and then such files would appear under a submenu of the "New" menu.

The use of this would be for people like me that have numerous templates and especially multiple related templates (like various C or Python templates). One may put their Python files (for example) in a directory called "Python" under `./template/files/` and then the "New" menu would have a "Python" submenu that lists all of the templates in that directory.

**Comment by elextr** [comment]
Sounds reasonable, but "somebodys" got to do it.

**Comment by DevynCJohnson** [comment]
@elextr , so are you saying that new features do not grow on trees‽ (^u^)

**Comment by elextr** [comment]
Nor are found down the back of couch cushions :-)

The use of "somebody" (in quotes) is a Geany project idiom started in the mists of history, and has the subtext "doesn't have to be you you, but very unlikely to be me", as well as a gentle reminder of the above sayings as they relate to a purely volunteer project.

**Comment by ntrel** [comment]
I've implemented adding submenus for any filetype that has more than one matching file template. Then the submenus just work without people having to create subfolders.

**Comment by DevynCJohnson** [comment]
@ntrel , awesome. Thanks! How soon until this is merged?

**Comment by ntrel** [comment]
Now merged.
