### ISSUE TITLE
Problem with Dark Menus in  MsgWindow Tab Compiler

### ISSUE THREAD

**Issue by tuxd3v** [geany/geany#3359]
Hello all,
I am using geany v 1.37.1 in Debian 11.
I am using a dark scheme color on my Desktop, when I try to compile a project...I can't see the content of the message window tab <Compiler>
https://ibb.co/2FVKGMP

And I need to see the errors, obviously..

The same way that you provided color options for the Message Window tab Terminal, can you provide the same option for Tab Compiler ??
In that way I would be able to see the compiler output.

Now because it will take a lot of time until I get a new version with that option, to choose background/foreground colors to message window tab Compiler...is there any option that helps me to change the colors used for the compiler output??
I mean some config file or so...otherwise, I can't use geany :(

Thanks in Advance
tux

**Comment by elextr** [comment]
https://www.geany.org/manual/current/index.html#customizing-geany-s-appearance-using-gtk-css

**Comment by eht16** [comment]
Additional note: with the next Geany release (though no release date yet), we changed the default colors in #3013. Maybe see the PR details for the colors as inspiration.
