### ISSUE TITLE
Fortran function random_init not highlighted 

### ISSUE THREAD

**Issue by waynelapierre** [geany/geany#3362]
The Fortran function random_init is not highlighted in f90 files.

**Comment by elextr** [comment]
f90? google says its [fortran 2018](https://gcc.gnu.org/onlinedocs/gfortran/RANDOM_005fINIT.html)

**Comment by waynelapierre** [comment]
Yes, it was introduced in the 2018 standard. All modern Fortran files use the .f90 extension.

**Comment by elextr** [comment]
Ok, well the list of names in `filetypes.fortran` hasn't been updated since 2014 so I suspect "somebody" who uses/knows fortran needs to bring it up to date.

Older names should be left in the list so it supports older versions too, even if they have been removed in newer standards.
