### ISSUE TITLE
Unexpected dead key with Colemak

### ISSUE THREAD

**Issue by Aran-Fey** [geany/geany#3364]
For some reason, when I use the colemak keyboard layout, the asterisk (`*`) is a dead key in Geany. As you can imagine, that is *very* annoying when programming. Geany is the only app that has this problem.

Geany version: 1.37.1
OS: Windows 10
Colemak: Installed from [here](https://colemak.com/Windows#Version_with_Caps_Lock_as_Backspace) (version with caps lock as backspace)

**Comment by elextr** [comment]
Geany does nothing with keys, its all done by the OS and GTK.  IIRC 1.37 for Windows was released with GTK 2 which isn't being updated any more, so if it knows about Colemak or if its just getting confused I don't know.  Looks like the latter though.

You could try Geany 1.38 that uses GTK 3.

**Comment by Aran-Fey** [comment]
Upgrading to 1.38 solved the problem, thanks!
