### ISSUE TITLE
error while loading shared libraries: libtiff.so.5

### ISSUE THREAD

**Issue by abdulbadii** [geany/geany#3367]
After most package updates on Arch, came up:

`geany: error while loading shared libraries: libtiff.so.5: cannot open shared object file: No such file or directory`

Anyone familiar solving such?

**Comment by elextr** [comment]
AFAICT libtiff is not used by Geany or plugins.  Perhaps the latest GTK needs it?

**Comment by abdulbadii** [comment]
Yes, It's OS package installlation management problem not Geany. solved now
