### ISSUE TITLE
Add Modula lexer

### ISSUE THREAD

**Issue by 2cls0f** [geany/geany#3373]
Lexilla has Modula lexer:

https://github.com/ScintillaOrg/lexilla/blob/master/lexers/LexModula.cxx

But Geany doesn't ship with it.

**Comment by 2cls0f** [comment]
Modula-2 source file extension: .def, .mod
Modula-3 source file extension: .i3, .m3, .ig, .mg

**Comment by elextr** [comment]
A lexer has to be added as a built-in filetype.  "Somebody" has to make a pull request doing that, but modula is pretty much a historical language and this is the only request that github has, and the mailing list archives have no references to modula either, so not sure how likely it is that the PR will be accepted.

**Comment by 2cls0f** [comment]
> A lexer has to be added as a built-in filetype. "Somebody" has to make a pull request doing that, but modula is pretty much a historical language and this is the only request that github has, and the mailing list archives have no references to modula either, so not sure how likely it is that the PR will be accepted.

filedefs?

**Comment by elextr** [comment]
See for example https://github.com/geany/geany/commit/90c6096ed6ea167f9100ce8f74229a3f47acc29a which was adding Julia, see #2584.  That language has a ctags parser that doesn't exist for modula, so it will be simpler but much will still be needed.  See also HACKING although its getting a bit outdated.
