### ISSUE TITLE
Build command cannot find my scripts

### ISSUE THREAD

**Issue by d-adamson** [geany/geany#3381]
I created some scripts in a directory and added this to my PATH environment variable.

In the Geany terminal, I can execute the script and it uses my search path like normal.
![image](https://user-images.githubusercontent.com/7835990/215599946-2a4290c1-90a0-4119-afeb-56c7efdb002c.png)

However, if I put this script as a Build command, Geany cannot find it. Any ideas?
![image](https://user-images.githubusercontent.com/7835990/215600492-36d8c83f-9ad1-4e2d-a788-f46e1978540c.png)

![image](https://user-images.githubusercontent.com/7835990/215600892-5f736d4d-f2bf-4c39-a1e8-d577961a57d8.png)

**Comment by elextr** [comment]
Did you start Geany from a shell that will read the file where you set the PATH?

**Comment by d-adamson** [comment]
Thanks that worked!
I had been launching it from the menu (Linux Mint 21).
Why is the behavior different between the two launching from the cmd line or the menu?

**Comment by elextr** [comment]
The shell in the terminal window is an interactive shell, it reads startup files like any other interactive shell.

The execute commands are run by a shell script with `#!/bin/sh`, so the shell is non-interactive, so it does not read any startup files, so the PATH is that inherited from the environment that Geany is started in.

By default menus do not run commands in interactive shells (or often any shell) so the PATH is inherited from the process running the menu, and that is started from the logind so its not likely to have read the users shell startup files.

You probably can edit the menu entry to run Geany in a shell, you may have to add an option to make it interactive depending on which startup file you edited.

**Comment by d-adamson** [comment]
Thanks for the detailed and quick response.
I'll play around with it. Not such a big deal knowing it can be launched from the command line.

**Comment by d-adamson** [comment]
Seems to be working now! :)
Added the path to my scripts in ~/.profile rather than in ~/.bashrc
From ./profile, the PATH is passed to all scripts (interactive and non-interactive).

Might be worth a short paragraph in the Geany documentation.

Thanks again for your help!
