### ISSUE TITLE
underscores do not show in the editor

### ISSUE THREAD

**Issue by tux2bsd** [geany/geany#3383]
underscores do not show in the editor, you can find them with ctrl+f (if you know they are there) but you can't see them

ii  geany          1.36-1build1 amd64        fast and lightweight IDE
PRETTY_NAME="Ubuntu 20.04.5 LTS"
(xfce xubuntu)

I use a relatively stock OS install, no custom fonts in the DE etc

**Comment by elextr** [comment]
Duplicate of #2466 and half a billion others
