### ISSUE TITLE
Need own keyboard shortcuts for commands for compiling and running projects

### ISSUE THREAD

**Issue by GizehFire** [geany/geany#3385]
**[build-menu]** _(geany.conf)_
(..)
**NF_03_CM=**
(..)

How can I define my own shortcut key for NF_03_CM?

**Comment by elextr** [comment]
Keybindings are only available for the basic commands.  

IIRC the problem is the keybindings code cannot handle dynamic changes to the number of entries for a section.

**Comment by ntrel** [comment]
As a workaround you can set an underlined character for the command label e.g. _d and then use Alt-B then D to run the command - assuming your build parent menu item is called Build and not translated.

**Comment by ntrel** [comment]
Duplicate of #705.
