### ISSUE TITLE
Don't insert * on comment continuation if previous line doesn't start with *

### ISSUE THREAD

**Issue by danpla** [geany/geany#3386]
Suppose I need to add text to a comment written in the following style:
```
/*
First line
Second line
Third line
*/
```
When I add a new line, it should be clear that I don't want automatic `* ` since the previous line doesn't have it, yet Geany still inserts it.

**Comment by elextr** [comment]
`Edit->Preferences->Editor->Completions->Automatic continuation of multiline comments`

**Comment by danpla** [comment]
Disabling the continuation altogether is not convenient. I still want it for the common case like:
```
/**
 * First line
 * Second line
```

**Comment by elextr** [comment]
Well, if "somebody" contributed a properly documented third option besides on and off it might be accepted.

**Comment by danpla** [comment]
But why not just check the previous line? Is there a practical reason to add `* ` even if the previous line doesn't have it?

**Comment by elextr** [comment]
Ok, I guess if you manually delete the * you can manually add it back if you want it, but then it _must_ be documented, I'm sick of getting complaints about "magic" behaviour that has not been documented. [end rant, not at you]

**Comment by ntrel** [comment]
@elextr could you make an issue for undocumented behaviour please, maybe with a checklist. Unless it exists already. No promises but I will try to add documentation at least for any feature I added.

**Comment by elextr** [comment]
@ntrel thanks for the offer, will make an issue when I get a chance.

**Comment by ntrel** [comment]
@elextr I've also made a project for underdocumented stuff:
https://github.com/orgs/geany/projects/2/

If you make an issue please add it to that project.

**Comment by danpla** [comment]
Thanks!
