### ISSUE TITLE
The editor inserts a quote too  much

### ISSUE THREAD

**Issue by SandorBy** [geany/geany#3426]
Hi

I am learning C with Geany. When I write a function call like:
puts("
then Geany inserts a quote too much so that there are three:
printf(""");

The brackets are ok.
I am using Geany 1.38 on Linux mint.

Thank you for this nice editor
Sandor

**Comment by elextr** [comment]
`Edit->Preferences->Editor->Completions->Autoclose quotes and brackets` untick as uppropriate.

**Comment by elextr** [comment]
You probably have _both_ Geany autoclose and the Autoclose plugin set to autoclose.
