### ISSUE TITLE
printing is faint

### ISSUE THREAD

**Issue by stephenboston** [geany/geany#3429]
`geany 1.38 (built on 2022-08-05 with GTK 3.24.34, GLib 2.72.3)`
6.1.8-arch1-1
brother  dcpl2550dw

Page header prints well but text body is very faint. Set to DPW1200.

**Comment by elextr** [comment]
The text body is printed with the styling it has on screen, so trying different styles might find an improvement.

**Comment by stephenboston** [comment]
Ah yes. I had a dark BG with light text . I switched to default for printing and -- just as you say. 

Thank you.
