### ISSUE TITLE
Crt-shif-V crashes Geany on Ubuntu

### ISSUE THREAD

**Issue by xavier8854** [geany/geany#3430]
If you inadvertently type Crtl-shif-V instead of Crrl-V (easy done when you switch from Terminal), Geany crashes

The crash report is attached, minus the coredump wich may or not contain sensitive information
[geany-crash.zip](https://github.com/geany/geany/files/11001286/geany-crash.zip)

**Comment by elextr** [comment]
Duplicate of #2813 and #3190 and fixed by #3091
