### ISSUE TITLE
Will there be possiblity to dock the Message Window at the right side of the Geany window?

### ISSUE THREAD

**Issue by donaastor** [geany/geany#3444]
At several occasions, I noticed that it would be really useful a lot, but unfortunately I can't find a way to do it. Are there others who think the same?

**Comment by elextr** [comment]
`Edit->Preferences->Interface->Interface->Message window->Right` ?

**Comment by donaastor** [comment]
> `Edit->Preferences->Interface->Interface->Message window->Right` ?

oops... thank you!
