### ISSUE TITLE
Non-plugin API accessable from plugins

### ISSUE THREAD

**Issue by eht16** [geany/geany#346]
Jiří and me just noted that for some reason it seems like Geany functions which are not part of the plugin API are exported to plugins.

We noticed it by this commit: aef37b05aecd85e527acd6d8c07629ab602b8b3b

There document_show_tab() and document_grab_focus() were added while not being part of the plugin API but still while compiling and linking no errors were spotted (that's sort of ok as the document.h header clearly declares the function also for plugins).

But on Linux, we could even load the plugin successfully and the functions are actually called without an error (I had expected to see 'unknown symbol document_grab_focus...').

Interestingly, on Windows it already breaks at linking, see the end of http://nightly.geany.org/win32/build_win32_plugins_stderr.log.

Does anyone have an idea if anything has changed regarding linking and/or how plugins access Geany's exported API?

Compiling Geany with gcc and its option -fvisibility=hidden, fixes the problem, then we get 'undefined symbol: document_show_tab' as expected.
Maybe the gcc default for that option has been changed?
We were testing with gcc 4.8 and 4.9 on Linux.

Any ideas?

**Comment by b4n** [comment]
Hum, now with GEANY_PRIVATE and linkage-cleanup, I guess this can be closed?  feel free to reopen if I missed some part not yet addressed.
