### ISSUE TITLE
Parse C/C++ tags wrapped in an extern "C" {...} block

### ISSUE THREAD

**Issue by ntrel** [geany/geany#349]
Geany fails to parse tags wrapped in an `extern "C" {...}` block, even in C++. The construct should be recognised for the C parser also, so this pattern is supported:

``` c
#ifdef __cplusplus
extern "C"
{
#endif

extern int i; // should be parsed as a global

#ifdef __cplusplus
}
#endif
```

**Comment by codebrainz** [comment]
I'm having this issue too, on Windows 10, types are not highlighted correctly inside `extern "C"` blocks (whether guarded or not). For example,

```c
#ifdef __cplusplus
extern "C" {
#endif
typedef struct SomeStruct SomeTypedef;
struct SomeStruct
{
    int x;
};
#ifdef __cplusplus
}
#endif
```

Doesn't highlight the type name "SomeTypedef" in C, but it does for the "SomeStruct". If I switch the filetype to C++, neither type is highlighted.

It must be Windows-specific, I know this works fine Linux for sure.

**Comment by elextr** [comment]
Confirm that like @b4n the test code used by @codebrainz works fine on linux.

**Comment by codebrainz** [comment]
As a workaround, putting the `extern "C" {` in a separate header a la `G_BEGIN_DECLS` fixes tag parsing inside the block.

**Comment by eht16** [comment]
Just for the record, I tested the code snippet on Windows with the ctags binary we ship with Geany-Plugins (originating from the MSYS2 ctags package) and this binary also does not parse the extern variable.
Still no clue what could cause the different behaviour in parsing on Windows :(.

**Comment by masatake** [comment]
As far as trying the input directly with u-ctags, it captures all expected tags.

**Comment by techee** [comment]
@eht16 Did the new cxx parser fix this issue on Windows?

**Comment by eht16** [comment]
It does!
![geany_windows_externc](https://user-images.githubusercontent.com/617017/147881159-9640e60b-5534-449d-8163-b11bc2e2d90e.png)

I guess we can close this now.

**Comment by techee** [comment]
Good, one more mysterious bug away.

**Comment by kugel-** [comment]
Maybe have a unit test for this?

**Comment by techee** [comment]
> Maybe have a unit test for this?

Yeah, but parser problems should mostly be business of uctags now. And I think the new cxx parser is tested quite well there.
