### ISSUE TITLE
Problem with moving cursor of Persian/Arabic texts

### ISSUE THREAD

**Issue by mskf1383** [geany/geany#3504]
Hi
Cursor can't move on Persian/Arabic texts correctly and it is unusable:
![Peek 2023-05-18 20-47](https://github.com/geany/geany/assets/50908329/cc6fdac7-b761-4109-b77b-5e01061b965f)

Gnome Text Editor doesn't has this problem:
![Peek 2023-05-18 20-53](https://github.com/geany/geany/assets/50908329/d09ea065-8c24-4a0d-a098-74126c930882)

Also Persian/Arabic is RTL and adding/deleting text, should be like this:
![Peek 2023-05-18 21-01](https://github.com/geany/geany/assets/50908329/7297cbf5-fff4-45f9-bd4d-82f13b5e2908)

**Comment by elextr** [comment]
Geany uses the [Scintilla](https://www.scintilla.org/) editing widget which unfortunately states in its documentation "Scintilla provides only limited experimental support on Windows for right-to-left languages like Arabic and Hebrew. While text in these languages may appear correct, interaction with this text may not work correctly as occurs with other editors.".

I would have expected the cursor to jump to the right and go backwards not move LTR in RTL text, so even Gnome editor is not totally correct.  

I'm sure contributions to Scintilla would be welcomed.

Closing as its not something Geany can improve until Scintilla is improved.
