### ISSUE TITLE
Problem with Chinese display

### ISSUE THREAD

**Issue by DarkgreenWorld** [geany/geany#3526]
![{464BD2C3-D2A8-4cd8-ADE3-925F52F8647D}](https://github.com/geany/geany/assets/139338389/772cce75-9c8b-4179-ac29-950aabaf7918)
How incomprehensible this is! Blue Chinese can be displayed normally, while red cannot!

**Comment by elextr** [comment]
Please don't cross post, see response on geany-plugins.
