### ISSUE TITLE
Build  geany & geany-plugins on windows(using MSYS2), but geany.exe can not find and load any geany-plugins

### ISSUE THREAD

**Issue by baoliubin** [geany/geany#3532]
Hi, Dear experts:\
&emsp;&emsp;I'm glad to be able to use this lightweight IDE on Win10 ):\
&emsp;&emsp;I'm very interested in it and hope to expand its functionality, so I'm first try to build geany & geany-plugins on windows, following https://wiki.geany.org/howtos/win32/msys2 titles of **Initial Setup**&**Geany Compilation**&**Geany-Plugins Compilation**.\
&emsp;&emsp;After I finished compiling, I was able to run **geany.exe**, but I couldn't find any plugins through the plugin gear manager. I checked the compiled product, it was found that the compiled products of geary plugin are both **. a** and **. la**. Then I referred to **Creating a GTK runtime bundle** try to fix this problem, but it is not work. \
&emsp;&emsp;After that, I tried to directly install gear and gear plugin using the installation package linked on the official website(https://download.geany.org/geany-1.38_setup.exe https://plugins.geany.org/geany-plugins/geany-plugins-1.38_setup.exe), I found that all plugins are basically **. dll** or **. dll. a** suffixes.\
&emsp;&emsp;What should I do to solve this problem or how did you compile and use geany and geany-plugin under Win10？

**Comment by baoliubin** [comment]
I can not get any help for this problem

**Comment by elextr** [comment]
All Geany contributors are volunteers, all contributions are in their own "spare" time.  Very few contributors build Geany on Windows, so posing a question that only a small number of contributors can answer and expecting a reply in two days, which are weekday working days, not "spare" time days was never likely to succeed.

**Comment by baoliubin** [comment]
@elextr thank you. Perhaps I was too eager to seek answers and neglected the time freedom of contributors, as work and life have already put a lot of pressure on everyone, which is my negligence.

**Comment by eht16** [comment]
@baoliubin sorry for the late answer.
It might help or might not but it's worth a try:
Set the environment variable "lt_cv_deplibs_check_method" to "pass_all", e.g. by executing the following command in the same shell where you compile Geany afterwards:
```export lt_cv_deplibs_check_method='pass_all'```

For details see https://github.com/geany/geany/issues/3461.

**Comment by baoliubin** [comment]
thank you very much



---- Replied Message ----
| From | Enrico ***@***.***> |
| Date | 10/15/2023 17:46 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [geany/geany] Build geany & geany-plugins on windows(using MSYS2), but geany.exe can not find and load any geany-plugins (Issue #3532) |

@baoliubin sorry for the late answer.
It might help or might not but it's worth a try:
Set the environment variable "lt_cv_deplibs_check_method" to "pass_all", e.g. by executing the following command in the same shell where you compile Geany afterwards:
export lt_cv_deplibs_check_method='pass_all'

For details see #3461.
