### ISSUE TITLE
Geany 1.38 on Debian Bookworm issue

### ISSUE THREAD

**Issue by kthywise209** [geany/geany#3567]
Hi,

i am using Debian 12 and Geany 1.38 for Python 3 programming. I use Cinnamon Desktop; However the issue persists in both Cinnamon and GNOME Desktop environments.

1. Set build Commands: 
a) "Compile" is set to: **python3 -m py_compile "%f"**
b) "Execute" is set to:  **python3 "%f"**
c) "Make", Make Custom Target each set to: **make**
d) "Make Object" is set to: **make %e.o**

2. Edit --> Preferences -->Tools:
a) Terminal is set to: **x-terminal-emulator -e "/bin/sh %c"**
b) Browser is set to: **sensible-browser**
c) Grep is set to: grep

**Issue**:on hitting F5 to execute/run code results in a terminal window popup launching and disappearing almost instantly. Will appreciate help with resolving the issue.

**Comment by elextr** [comment]
>  x-terminal-emulator -e "/bin/sh %c"

%c is not used

**Comment by kthywise209** [comment]
> > x-terminal-emulator -e "/bin/sh %c"
> 
> %c is not used

Thanks. what would be the configuration to spawn a terminal window for each F5 and have it persist with output of the program?

**Comment by elextr** [comment]
https://www.geany.org/manual/current/index.html#substitutions-in-commands-and-working-directories

**Comment by elextr** [comment]
Oh wait, thats not a build command, ignore my last.

As a tools command it should be right.  Presumably the reason it snaps closed is that `x-terminal-emulator` doesn't understand the -e "/bin/sh path_to_script", unfortunately thats not the Geany default command which uses dear olde `xterm`, which works here so not sure what the problem is.

Probably the distro changed the default from `xterm` (unless you did) but hasn't got the options right for it.

**Comment by elextr** [comment]
You could try running Geany in a terminal to see if `ex-terminal-emulator` puts any message to stderr.

**Comment by kthywise209** [comment]
> Oh wait, thats not a build command, ignore my last.
> 
> As a tools command it should be right. Presumably the reason it snaps closed is that `x-terminal-emulator` doesn't understand the `-e "/bin/sh path_to_script"`, unfortunately thats not the Geany default command which uses dear olde `xterm`, which works here so not sure what the problem is.
> 
> Probably the distro changed the default from `xterm` (unless you did) but hasn't got the options right for it.

echo $TERM  produces _xterm-256color_

**Comment by elextr** [comment]
_xterm-256color_ is a compatibility statement, not an application name, and most terminal emulators set that these days.

IIRC `x-terminal-emulator` isn't a program, its a link to something thats a link to a program, so you need to find what it actually is running and how to pass a command to run a script in a shell.

**Comment by kthywise209** [comment]
> _xterm-256color_ is a compatibility statement, not an application name, and most terminal emulators set that these days.
> 
> IIRC `x-terminal-emulator` isn't a program, its a link to something thats a link to a program, so you need to find what it actually is running and how to pass a command to run a script in a shell.

many thanks
