### ISSUE TITLE
Is --read-only not implemented with files loaded by a project files?

### ISSUE THREAD

**Issue by OneArb** [geany/geany#3577]
I like to view different files within a single project in several geany instances.

In order to avoid confusions I'd like to open an entire project --read-only and edit within a single instance.

`geany -ir myproject.geany`

Is the feature yet to be implemented?

**Comment by elextr** [comment]
A project stores the readonly status of files when it is saved and reloads with the same status.  Overriding that from the command line is not implemented.

**Comment by OneArb** [comment]
I can reopen the document in a new instance and set the read only flag in the new instance.
This way I can have one editable window and one read only side by side.

Thanks

**Comment by OneArb** [comment]
I can reopen the document in a new instance and set the read only flag in the new instance.
This way I can have one editable window and one read only side by side.

Thanks
