### ISSUE TITLE
Linux light themes render geany toolbar icons invisible

### ISSUE THREAD

**Issue by ineuw** [geany/geany#3601]
I am using Geany in Linux Mint and Kubuntu, so I am comfortable with KDE and GTK. This problem is identical in both, and has nothing to do with a selected color scheme. Dark system themes are not always preferred.

![231011_0533_toolbar_icons_are_invisible_in_Kubuntu_light_themes](https://github.com/geany/geany/assets/10367016/59a0612a-d439-44be-b4ac-e99b3ef2f214)

**Comment by elextr** [comment]
All toolbar icons are standard icons and their selection and rendering is up to the GTK theme.  On Linux Mint using Mint-Y theme I can get the effect you show by setting the icons to Mint-Y-dark using the desktop preferences.  Its not something Geany can control.

**Comment by ineuw** [comment]
I found the reason but wasn't quick enough to let you know what causes the problem and cancel the post. Kubuntu's incorrectly defined group rights blocks standard geany from accessing the system icons. I noticed the difference when I used "sudo geany" to edit the **/etc/sudoers file**. I hope this helps others. 

I reported the bug to KDE because this affects system components as well, not just geany.
