### ISSUE TITLE
Prefs: move "virtual spaces" to the "Features" tab

### ISSUE THREAD

**Issue by b4n** [geany/geany#3605]
As @techee (IIRC) mentioned somewhere, the *Editor→Display* tab is getting crowded to the point it makes the prefs window grow. I suggest moving the *Virtual spaces* section to the *Editor→Features* tab that not only has room, but also seems more fitting to me – it's not a display thing, it's how the editor behaves, isn't it?

**Comment by elextr** [comment]
Its both visual and behaviour IIUC, so agree its fine to move.

**Comment by techee** [comment]
Sounds good.

**Comment by techee** [comment]
By the way this is how the settings page looks on my (older) Dell XPS 13 on Windows 11:

![Screenshot 2023-10-20 154048](https://github.com/geany/geany/assets/713965/8ce59fb4-9123-4f58-ae72-0b41de0c3ea3)

The top of the window is aligned with the top of the screen and at the bottom one has to guess which button is which to confirm the dialog.

**Comment by elextr** [comment]
@techee plug in a bigger screen, or better get a theme that doesn't include so much padding.  Or both :grinning: 

Seriously though, compared to my MS Surface  tablet (no it doesn't have Geany) it does look quite expanded.  The tablet (in landscape) fits many more lines than that, what font size are you using?

**Comment by techee** [comment]
> @techee plug in a bigger screen, or better get a theme that doesn't include so much padding. Or both 😀

Or none of these and use my normal solution "don't use Windows" :-) Testing Geany was just a good opportunity to install one and half years worth of updates...

> Seriously though, compared to my MS Surface tablet (no it doesn't have Geany) it does look quite expanded. The tablet (in landscape) fits many more lines than that, what font size are you using?

The "recommended" scale for the (HiDPI) screen is set to 300% and yes, everything is quite big. But when changed to 250%, everything gets really small so I don't know how it's calculated.

> Edit: or is the dell a reeeeely small screen?

It's an older model with 16:9 screen, the newer ones have 16:10 so I think that would be just enough to fit the preferences dialog there.

Anyway, back to "not using Windows" again...

**Comment by elextr** [comment]
> Anyway, back to "not using Windows" again...

That is of course another solution.

But really the point was, is it a common problem?  Or is it only rare systems with silly themes that have the problem?

Of course the solution suggested by @b4n will work for now, until this or another of the dialogs expands again.

**Comment by eht16** [comment]
Yes, it won't solve the crowded dialog problem until the end of time but at least for now :).

@b4n's argument that the setting itself is more a behavior setting than a visual only setting still counts and so I think we should do it.
