### ISSUE TITLE
Force meson to use the ".so" extension instead of ".dylib" for plugins on macOS

### ISSUE THREAD

**Issue by techee** [geany/geany#3606]
Is there a way to set the file extension for the plugins built using `shared_module()`? On macOS it defaults to ".dylib" but Geany expects that the extension is ".so" so these plugins don't load. geany-plugins still use autotools which produce ".so" those load alright.

Not critical for the release, I'll revert to using autotools for this release but it would be good to figure this out for the future.

**Comment by elextr** [comment]
Probably should use `.dylib` on mac, that will prevent plugins built for linux being visible.

If anyone (except you) is using autotools on mac they can submit a patch to add a rename step for the `.so`s.

**Comment by techee** [comment]
> Probably should use .dylib on mac

But Geany won't load them. And geany-plugins are still using autotools and generate ".so". So I think it would be easier if meson could generate ".so" instead of ".dylib" so we'd have the same extension coming both from geany and geany-plugins.

**Comment by elextr** [comment]
> But Geany won't load them. 

Sure, there is a minor matter of mac specific patching needed.

> And geany-plugins are still using autotools and generate ".so". 

Ditto

I was thinking of people who download plugins from the internet, most will be for linux, will they work? I guess so far there has been no complaint, so maybe mac people don't download stuff from the internet?

**Comment by elextr** [comment]
Maybe https://mesonbuild.com/Reference-manual_functions.html#library_name_suffix

**Comment by techee** [comment]
> Maybe https://mesonbuild.com/Reference-manual_functions.html#library_name_suffix

Cool, thanks, that appears to be it, I'll test.

> I was thinking of people who download plugins from the internet, most will be for linux, will they work? I guess so far there has been no complaint, so maybe mac people don't download stuff from the internet?

I bundle most of the plugins (that don't have any too-hard-to-build dependencies like webkit) as part of the Geany bundle and they work. I just need the plugins from geany-plugins to have the same extension as those that are built with Geany. But the above link looks promising.
