### ISSUE TITLE
Restoring the session does not restore the current file or files order when tabs_order_beside is enabled

### ISSUE THREAD

**Issue by b4n** [geany/geany#3609]
Restoring the session (from my upgraded ~/.config, which has seen all versions since the dawn of time^W^W^W^W I started using Geany) restores the files, but not:

* the order
* the current file

It kinda looks like the first element is right, but the reset is sort of loaded in reverse… Might have something to do with the option on where new tabs are opened?

**Comment by b4n** [comment]
Yeah, it happens if `next to current` is checked.

**Comment by b4n** [comment]
hum… it's bad, but I'm wondering for how long this existed.  I didn't bisect, but quickly going through this code seems to suggest it's nothing recent (yet, I might be wrong).

**Comment by elextr** [comment]
Given that it is done in `notebook_new_tab()` which all file creates use I would guess its been happening since that option was added by https://github.com/geany/geany/commit/fdd451f0d4c702d97f398176b41cc2baebe5ee49 (note see the "by" author name :-D
