### ISSUE TITLE
Context menu item "_Join Lines" missing translation

### ISSUE THREAD

**Issue by scootergrisen** [geany/geany#3621]
I right click in the pane with a open file and select Format.
The first option Join Lines is not using the translated string.

![billede](https://github.com/geany/geany/assets/1836590/0cd66b69-fb0c-41c1-baaf-90769645618b)

```
#: ../data/geany.glade.h:372 ../src/keybindings.c:508
msgid "_Join Lines"
msgstr "_Sammenføj linjer"
```

I don't see the string "_Join Lines" in the locale/da/LC_MESSAGES/geany.mo released with Geany 2.0.

> Windows 7.
> Geany 2.0.
> "Pryce"
> (bygget Oct 19 2023 eller efter)
> Med afviklingsbibliotekerne GTK+ v3.24.34 og GLib v2.72.3

**Comment by scootergrisen** [comment]
"Join Lines" is in context menu Help > keyboard shortcuts dialog.
That string does not seem to be able to translate.
"_Join Lines" is in the po file but not "Join Lines".

![billede](https://github.com/geany/geany/assets/1836590/a4f0e596-debc-4fe3-854e-197a3fe1f645)

**Comment by eht16** [comment]
Very likely sasme cause as in #3620 :(.

**Comment by scootergrisen** [comment]
"_Join Lines" is not translated in latest release.
The status bar translation is still not translated so i guess its not the same cause.
