### ISSUE TITLE
Menu item string "Without encoding (None)" is not fully translatable

### ISSUE THREAD

**Issue by scootergrisen** [geany/geany#3624]
"None" in the menu item at the bottom is not translatable.
Perhaps the " (None)" part could just be removed since it already says "Without encoding".
![billede](https://github.com/geany/geany/assets/1836590/96b5c222-8e41-443b-9190-8eef275d0bd8)

> Windows 7.
> Geany 2.0.
> "Pryce"
> (bygget Oct 19 2023 eller efter)
> Med afviklingsbibliotekerne GTK+ v3.24.39 og GLib v2.78.0

**Comment by eht16** [comment]
I agree with removing "(None)" from the string as it is redundant and making it translatable does not give any value.
See #3640.
