### ISSUE TITLE
Make Custom Date Format dialog less wide

### ISSUE THREAD

**Issue by scootergrisen** [geany/geany#3625]
This dialog is really wide.
It's not possible to select the text with the URL so it might not be so nice having to visit that URL by typing what you see manually.
![billede](https://github.com/geany/geany/assets/1836590/c04faf68-9c5d-4ed7-89a4-142357193ad1)
![billede](https://github.com/geany/geany/assets/1836590/5ba75c0b-1bb0-40a7-b64b-cfd6ace98cb7)
Perhaps make the URL into a link (like in the About dialog) and not having to show the URL but a link text instead.
Maybe something like this.
Maybe add an icon to show its a link being opened in a web browser.
![billede](https://github.com/geany/geany/assets/1836590/df71345c-918d-413f-a15a-e98751e3c3e9)

> Windows 7.
> Geany 2.0.
> "Pryce"
> (bygget Oct 19 2023 eller efter)
> Med afviklingsbibliotekerne GTK+ v3.24.39 og GLib v2.78.0

**Comment by intact** [comment]
Preferences / Templates / Date use tooltip for that conversion specifiers info.

**Comment by elextr** [comment]
Here that dialog is no wider than the default width of Geany, but depends on theme.  Maybe someone can persuade GTK to use multiple lines for the message.

GTK does not support links in messages IIUC.
