### ISSUE TITLE
`Use Windows native dialogs` is broken

### ISSUE THREAD

**Issue by iahung3** [geany/geany#3627]
You checked it, click `OK` or `Apply` then `OK`. You open `Preferences` again, and it's automatically unchecked. I tried to exit Geany and launch it again, doesn't make any differences. `Use Windows native dialogs` will always be automatically unchecked.

**Comment by elextr** [comment]
What version og Geany?

**Comment by elextr** [comment]
For Geany 2.0 note https://github.com/geany/geany/pull/3219 has happened, and explains why the setting still present (to not break plugin API).

**Comment by iahung3** [comment]
> What version of Geany?

Geany 2.0.

**Comment by kugel-** [comment]
Still a bug if the pref is still on the UI

**Comment by eht16** [comment]
Yes. I was very surprised as I jst noticed it is still in the Glade file.
Sorry, will remove it soon.

**Comment by elextr** [comment]
If the setting is in `geany.glade` how come it doesn't show on Linux?

**Comment by eht16** [comment]
> If the setting is in `geany.glade` how come it doesn't show on Linux?

If you have a close look at the changes in #3791, your question will be answered :D.
