### ISSUE TITLE
"Name" and "Value" is not translatable in Preferences dialog

### ISSUE THREAD

**Issue by scootergrisen** [geany/geany#3628]
"Name" and "Value" is in the po files but not used here.
![billede](https://github.com/geany/geany/assets/1836590/c9fb6a92-f1fa-45b6-9edb-6f3dd629596b)

> Windows 7.
> Geany 2.0.
> "Pryce"
> (bygget Oct 19 2023 eller efter)
> Med afviklingsbibliotekerne GTK+ v3.24.39 og GLib v2.78.0

**Comment by elextr** [comment]
They are marked for translation https://github.com/geany/geany/blob/f86c4de5863d1a2609345a045d7cfff5c35651b4/src/stash.c#L1219 (and value a few lines below) and is translated https://github.com/geany/geany/blob/f86c4de5863d1a2609345a045d7cfff5c35651b4/po/da.po#L399, maybe its the same issue as the other ones.

**Comment by eht16** [comment]
Good catch!
I'm a bit surprised that this wasn't noticed earlier. Anyway, #3634 should fix it.
