### ISSUE TITLE
Maybe the default sidebar width is too narrow

### ISSUE THREAD

**Issue by scootergrisen** [geany/geany#3630]
There is enough room to show everything in the picture but some of it is clipped of to the left.

![billede](https://github.com/geany/geany/assets/1836590/f4d29067-6915-42f4-a9bf-ba4885777212)

> Windows 7.
> Geany 2.0.
> "Pryce"
> (bygget Oct 19 2023 eller efter)
> Med afviklingsbibliotekerne GTK+ v3.24.39 og GLib v2.78.0

**Comment by elextr** [comment]
It depends on the theme, the sidebar width is set in pixels, but the number of pixels depends on the font and size and the size of a pixel, which is a function of your screen which we don't know.

Also there seems to be a lot of space to the right of Documents label, normally it should only be the same as the space to the left, plus enough for the vertical scrollbar plus enough for the pane handle.  Maybe something in the theme is adding padding.

But I doubt anybody keeps the default Geany size, so it probably won't hurt to increase the sidebar default pixel count.

**Comment by eht16** [comment]
Well, easy enough. #3637 increases the default sidebar width to about 25% of the default window width.

We could also think about increasing the default window altogether, this is how it looks like with Adwaita now:
![Screenshot_2023-10-22_10-56-53](https://github.com/geany/geany/assets/617017/4cde44a6-2d64-4ca9-8a9b-4faaa0b4fce4)
OTOH, as @elextr said, most people won't use such small windows anyway.

**Comment by jeremy-coleman** [comment]
on windows it looks like this by default

<img width="838" alt="image" src="https://github.com/geany/geany/assets/25135855/54c55d86-15de-469f-9ac9-a49f0754f533">

and fullscreen

![image](https://github.com/geany/geany/assets/25135855/88a13216-f493-4058-93d3-6687b79b8e6e)

completely fresh install.

**Comment by scootergrisen** [comment]
Dynamically truncating and adding "..." at the end of text where there is not enough room to display all the text would be nice.
![billede](https://github.com/geany/geany/assets/1836590/006f8eb3-9693-4f43-ac9e-7da74fc38849)

**Comment by elextr** [comment]
As @b4n said on #3637 the default width of the search entry is too big, on one of my systems it stops the notebook from hiding the documents tab and showing the tab scroll arrows.

If that was changed and "somebody" made a PR to set ellipsize on the tab labels and the "no symbols found" text then it might be accepted, but seems low priority to me given #3637 increases the initial size of the sidebar to improve the first impression, and after that its in the users hands.

**Comment by elextr** [comment]
If "somebody" made a PR to set ellipsize on the appropriate labels it might get accepted.

**Comment by eht16** [comment]
As said in #3637, the default sidebar width is increased so that it should match better the default window size.
Further improvements like modifying the entry's minimal size or ellipsizing the tab labels can be done separately if someone considers it important enough.
