### ISSUE TITLE
Toggeling Line Breaking seems to not do anything

### ISSUE THREAD

**Issue by scootergrisen** [geany/geany#3631]
If I toggle Document > Line Breaking I don't see any differences.
Is it perhaps not working?

> Windows 7.
> Geany 2.0.
> "Pryce"
> (bygget Oct 19 2023 eller efter)
> Med afviklingsbibliotekerne GTK+ v3.24.39 og GLib v2.78.0

**Comment by elextr** [comment]
That setting does not do anything immediate, it turns on breaking while typing, but you have to type past the limit.

Reflow does (re)breaking of the selected lines.
