### ISSUE TITLE
indentation: curly braces difference js x php (review all languages that use them?)

### ISSUE THREAD

**Issue by osergioabreu** [geany/geany#3655]
If I write an "if" in javascript that use curly braces, the behavior of Geany if fine, as it closes the curly brace exactly in the direction of the opening if. BUT when I do this in a PHP file, the closing curly brace is put one TAB to right, forcing the user to delete the extra TAB. Should it be reviewed in all languages that use curly braces (ex: also C ) ?  Although it is not a severe problem, it is at least an inconsistency in Geany behavior, since different languages show different closing indentation, it distances the software from perfection.

Right behavior (ex: javascript)
 
      if ( acondition == 1 ){
         code;
      } // <--- closing auto indentation ok in javascript

Geany with PHP file now is doing this:

      if ( $acondition == 1 ){
          code;
          } // closing bad auto indentation

**Comment by b4n** [comment]
Works for me, be it with *current characters* or *matching brace* indentation methods.  Note however that auto-indentation here will not happen if you have something on the right of the cursor when typing the closing brace.

What is you version of Geany?  Does disabling plugins help? (`geany -p`)  Maybe try a fresh configuration (`geany -c /tmp/tempconf`)

**Comment by osergioabreu** [comment]
I can not reproduce it anymore, please remove the topic untill I can reproduce, and I will recreate. I saw the bug once but I can not reprocuce right now. Please delete the topic. Tks

**Comment by osergioabreu** [comment]
new information:
if I open the if with the open and close bracks, could geany put the closing at the correct place? So it is a feature request. Type:

    if ( true) {}  
Back the cursor 1 char, to be between the curly braces and press ENTER.

**Comment by osergioabreu** [comment]
Desire behavior is:
1- Add an empty line with one indentation
2- Put the } one line below this line at direcition of  IF
3- Back the cursor at the blank line above, at indentation code.
