### ISSUE TITLE
Bad owner or permissions on /etc/ssh/ssh_config.d/ Could not read from remote repository.

### ISSUE THREAD

**Issue by jkemp814** [geany/geany#3679]
Hello everyone,

There is a problem while trying to use the integrated terminal. I have bash as shell. When using 'git push' or 'git pull,' I get an error message:

Bad owner or permissions on /etc/ssh/ssh_config.d/50-redhat.conf
fatal: Could not read from remote repository.

When I use git status it seems to read the remote repository, although I have GitHub return:
On branch main
Your branch is up to date with 'origin/main'. 

When in fact it's not 'up to date'

I'm using Fedora Linux 39 Silverblue with Geany 2.0 Flatpak version. (maybe this is the problem?)

All permissions are correct in my .ssh folders and the files within that folder. Everything works using external terminal, or other code editors. I prefer to use Geany.

Any suggestions?

**Comment by elextr** [comment]
Try starting Geany from the command line and see if there are any messages.

**Comment by jkemp814** [comment]
Well, it's a flatpak, but I'll give it a try.

**Comment by jkemp814** [comment]
After running flatpak run org.geany.Geany, switching to a git folder and running 'git pull' in the intergrated terminal I get the same error message:

Bad owner or permissions on /etc/ssh/ssh_config.d/50-redhat.conf
fatal: Could not read from remote repository.

Why it is looking in that folder and file for authentication, which do exist, i.e. 50-redhat.conf, I don't know.

**Comment by elextr** [comment]
I am afraid this project does not make the flatpack so we have no idea what restrictions or configurations that has.  You will have to communicate with Fedora about it.

**Comment by jkemp814** [comment]
I will try and layer Geany using rpm-ostree and see if that makes a difference. There are post on Reddit within a few days speaking about the same error message using SSH on Fedora Silverblue. 

Thanks for the responses.
