### ISSUE TITLE
How to prevent Geany from making dot underscore "._" files for every modified file on foreign volumes?

### ISSUE THREAD

**Issue by that-ben** [geany/geany#3685]
Is there a way for Geany to stop producing a dot underscore file such as ._example.php whenever I save example.php ? I'm working on a Windows volume and I understand macOS will make some system files on foreign drive formats, but I would like to know if at least Geany could edit the file and not create a side file for every file I edit with it?

**Comment by elextr** [comment]
Do you have the autosave plugin enabled?

**Comment by that-ben** [comment]
I'm new to Geany and I currently do not have any plugins installed at least not any that I did, I only have the vanilla/default Geany 2.0 install.

**Comment by elextr** [comment]
Well, Geany does not enable any plugins by default.  When you say "foreign" volumes, what do you mean?  Do those files appear when editing a file in a local drive like C:?

**Comment by that-ben** [comment]
By foreign, I specifically mean USB attached NTFS drives.

**Comment by elextr** [comment]
Oh, I thought you were on windows from your reference to notepad++ in another post.  

It sounds like you know what the problem is, it is not Geany that makes those files, its macos.  So you need to find where the setting for that is in macos.  AFAIK other mac folks don't have the problem, but maybe they don't edit files on NTFS drives.

**Comment by that-ben** [comment]
Yes, I'm migrating from Windows to Mac with at least 20TB worth of SATA drives full of various program sources that I want to continue developing, mostly web apps.  I'm not quite ready to convert those SATA drives to APFS, so in the meantime I have to continue working with NTFS and for the most part it works great, except that anything that I save with Geany produces a dot underscore file on its side, which is extremely annoying.  Since I'm migrating from Windows to macOS, I'm investigating Geany, trying to see if it can replace NotePad++, that's why you see me mentioning NotePad++ here and there.  There are some things it apparently can't replace NotePad++ for though.

**Comment by elextr** [comment]
Well AFAGCT Apple doesn't support NTFS writing, so you must have some third party software to do it.  Just to be clear Geany does _not_ create those files and cannot control any software that does.

**Comment by that-ben** [comment]
Yes, it's macFUSE with the ntfs-3g driver.  I was trying to see if anything could be tweaked in Geany to prevent that from happening.  Thanks anyway.
