### ISSUE TITLE
Keyboard input during "Save as..." defaults to folder search

### ISSUE THREAD

**Issue by teovilo** [geany/geany#3691]
When using the Save As dialog and after browsing to the save location, keyboard input defaults to the search feature despite the Filename text input being highlighted blue. This is non-intuitive and inconsistent with other software.

**Comment by elextr** [comment]
This is normal behaviour of the GTK toolkit.  The focus is on the filename field when the dialog is opened, but moves to the list when a directory there is clicked and when the list is focused typing activates the list search facility.  The focus must be returned to the filename field by tabbing or clicking to type in it.

The blue outlining of the filename field is done by your theme, not by Geany, here the field is only outlined in green when it is focused, but it seems your theme leaves it outlined in all states, perhaps it indicates focus in another way?

**Comment by teovilo** [comment]
Once I've browsed to the directory I want, I should able to enter the filename without clicking anywhere. This is the convention that everyone expects. File/folder searching should be the function that requires clicking somewhere.

**Comment by elextr** [comment]
As I said, this is the standard behaviour of GTK AFAIK, they expect you to type the filename then select where to put it.  You will need to discuss it with the GTK folks.

All GTK apps I tried do the same, even Vscode for Linux which uses the GTK default save as dialog.
