### ISSUE TITLE
Allow to disable: Are you sure to replace in the whole session?

### ISSUE THREAD

**Issue by luigifab** [geany/geany#3702]
With Geany 2.0 there is a new question for **Search and Replace** dialog:

**Are you sure to replace in the whole session?**

![image](https://github.com/geany/geany/assets/31816829/6121a941-0a21-4dd3-866b-7caa1861b71b)

I'm against, this is unacceptable for me.
Is there, or can you add an option to disable it?

**Comment by elextr** [comment]
The "In Session" function is not new, all that is new is the warning message, added [here](https://github.com/geany/geany/commit/295f59da91d2a2c08a5289d56d30f3caa2d2d507).

The "In Session" replace although it has been available for at least 15 years (as far as I looked).

There is no option to disable it, just don't use it, or say "no" to the warning dialog.

**Comment by b4n** [comment]
@elextr are you sure you didn't understand the request upside down? I understand as the OP asking to disable the warning and get back the older behavior of not asking confirmation.

**Comment by elextr** [comment]
> @elextr are you sure you didn't understand the request upside down? I understand as the OP asking to disable the warning and get back the older behavior of not asking confirmation.

Good question, could be either, but hey, "somebody" can follow the usual Geany approach of adding another option :-)

**Comment by luigifab** [comment]
Yes I would like to disable the warning.

**Comment by eht16** [comment]
A new various pref to disable the confirmation dialog is added in #3851.

**Comment by stefanct** [comment]
Don't ever introduce obstructions to common and established workflows (my muscle memory is indeed trained on this for >>10 years) without a way to disable them ffs. The cherry on the cake is elextr in his usual completely ignorant style being incapable of even understanding the issue. Good thing is that the geany shipped with debian trixie segfaults so much (plugin bugs AFAICT) that I have to rebuild it myself anyway, yay, productivity. Thanks eth16 for the fix!

Edit: Geany 2.1-1 (including the fix) from Debian Forky (including the fix) works fine in Trixie and has minimal dependency problems.

**Comment by b4n** [comment]
> Good thing is that the geany shipped with debian trixie segfaults so much (plugin bugs AFAICT) that I have to rebuild it myself

Would you care to elaborate?  if there's a critical bug in Trixie it might be something @hyperair can fix with a backport or something, if it is known.

**Comment by stefanct** [comment]
Not at this moment as it has not annoyed me just enough to look into it in detail and I cannot reproduce it 100% of the time either. I am also certain it's "just" in plugins not the main package. But I'll report it on the debian tracker once I find out more.
