### ISSUE TITLE
required gtk+ version 3.20, current version is 2.24

### ISSUE THREAD

**Issue by arteze** [geany/geany#3708]
Geany asks me for version 3.20, but it says I have 2.24... Gtk3 is installed and Gtk4 too.
How do I know which system file version 2.24 comes from so I can change it?

```sh
(geany:23563): Geany-ERROR **: 19:46:30.998: Cannot create user-interface: /usr/share/geany/geany.glade: required gtk+ version 3.20, current version is 2.24
`trap' para punto de parada/seguimiento
```
And a window appears:
```sh
Geany no puede iniciarse.
/usr/share/geany/geany.glade: required gtk+ version 3.20, current version is 2.24
```

**Comment by elextr** [comment]
what is the output of `geany --version` ?

**Comment by arteze** [comment]
I have this
```sh
geany 1.27 (compilado el día 2016-07-10 conGTK 2.24.30, GLib 2.46.2)
```

**Comment by arteze** [comment]
True, I hadn't realized. I already solved it by updating to the new version.

I had to do it manually because it didn't work with ArchLinux's pacman.
```sh
geany 2.0 (compilado el día 2023-10-23 conGTK 3.24.38, GLib 2.78.0)
```
