### ISSUE TITLE
geany ver2.0 still indentation problem: tab and space

### ISSUE THREAD

**Issue by creatxrgithub** [geany/geany#3710]
now it's no problem with chinese
 character and alphabet.

it's the problem with tab and spaces.

someone could try with indentation with 3 spaces, 4 spaces, 6 spaces, 7 spaces, 8 spaces.

at first, i think it's because to show a space between tabs, it's why it seems that it's ok with 3 spaces.

buy if you try tab's width is 8 spaces (less or more one space), you'll find it's cannot get well indentation.

test strings:

`測試測試測試測試測試測試測試測試測試測試測試測試
testtesttesttesttesttesttesttesttesttesttesttest
1122334455667788990011223344556677889900
abcdefghijklmnopqrstuvwxyz
ABCEEFGHIJKLMNOPQRSTUVWXYZ
					
abcdefghijklmnopqrstuvwxyz`

![shot-2023-12-03_13-32-12](https://github.com/geany/geany/assets/27437178/4f848a77-d5e7-4c02-87c4-0dac49216f68)
![shot-2023-12-03_14-13-53](https://github.com/geany/geany/assets/27437178/2914396c-964f-417a-a79e-3c7eef40fe55)
![shot-2023-12-03_14-15-01](https://github.com/geany/geany/assets/27437178/2df16cd7-3620-4426-a723-f61784451b70)

**Comment by elextr** [comment]
Hint, monospaced, the width of tabs shown is the width of the specified number of ASCII space characters in the current default font.  

With non-monospaced fonts that may be less than the width of the same number of other characters, and that width may depend on the number of spaces in a row.
