### ISSUE TITLE
non-deterministic anon_struct

### ISSUE THREAD

**Issue by bmwiedemann** [geany/geany#3717]
While working on [reproducible builds](https://reproducible-builds.org/) for [openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds), I found that our `glfw` package varies in every build since the upgrade to geany-2.0

I extracted this minimal reproducer:

```bash
cat > test2.c <<EOF
typedef struct {
  struct
  {
  } __value32;
} __atomic_wide_counter;
EOF
for i in 1 2 ; do geany -g glfw.c.tags test2.c ; md5sum glfw.c.tags ; done | sort -u | wc -l
2
```

The output differs thusly:
```diff
-__value32�64�__atomic_wide_counter�0�__anonceed23430108::anon_struct_1
+__value32�64�__atomic_wide_counter�0�__anone35807a60108::anon_struct_1
```

I think, there is the same problem with anon unions.

Please make output deterministic.

**Comment by elextr** [comment]
This generated name is created by the ctags CXX parser [here](https://github.com/geany/geany/blob/512e88df8d97284c191459450bce4dd7877b9c2b/ctags/main/parse.c#L4795).

The value of `parser -> anonymousIdentiferId` is incremented a few lines above, so I suspect its intended to count anon structs and give them incrementing names, but probably it isn't being properly initialised to zero at startup. @techee?

**Comment by techee** [comment]
> This generated name is created by the ctags CXX parser [here](https://github.com/geany/geany/blob/512e88df8d97284c191459450bce4dd7877b9c2b/ctags/main/parse.c#L4795).

And then we rename these in this nice function:

https://github.com/geany/geany/blob/512e88df8d97284c191459450bce4dd7877b9c2b/src/tagmanager/tm_ctags.c#L246

It seems nested anonymous tags aren't handled correctly - I'll have a look at it.
