### ISSUE TITLE
Whitespace before beginning of line

### ISSUE THREAD

**Issue by vincele** [geany/geany#3725]
The attached screenshot (taken from a `geany -c /tmp/blah` invokation) shows an empty blank space before the beginning of the text line.

![2023-12-18-202053_2560x1440_scrot-edited](https://github.com/geany/geany/assets/645242/0be01031-1f7d-4597-a0a2-a0654798beda)

This was not present before. I dunno if my distro (void) updated geany recently, but this is my likely candidate for the sudden appearance of that annoying whitespace.

Is there a way to disable it ?
Or if this is a case of PEBKAC, please tell me.

**Comment by cwendling** [comment]
*Edit → Preferences → Editor → Features → ☐ Code Folding*, that's not new though :slightly_smiling_face: 
You can also hide the marker margin that can be toggles in *View → ☐ Show Markers Margin* (although beware that if there are markers, they'll be displayed inline usually as background color for the line).

**Comment by vincele** [comment]
OK, thanks. Maybe not new, but it suddenly changed from under my feet... Maybe a distro glitch
