### ISSUE TITLE
Debian "sensible-browser" ignores the preferences of the x-www-browser file in Linux Mint.

### ISSUE THREAD

**Issue by ineuw** [geany/geany#3729]
These are the values in the /var/lib/dpkg/alternatives. But, the **/usr/bin/sensible-browser** never selects Firefox. Only either of the chrome based browsers, regardless of the assigned values.

```
auto
/usr/bin/x-www-browser

/opt/firefox/firefox
300
/usr/bin/vivaldi-stable
10
/usr/bin/google-chrome-stable
10
```

**Comment by elextr** [comment]
This isn't anything to do with Geany, maybe file elsewhere?

**Comment by ineuw** [comment]
Thanks. I needed to know.
