### ISSUE TITLE
Limit the size of GUI icons

### ISSUE THREAD

**Issue by arteze** [geany/geany#3730]
I accidentally ran a command that messed up the icon system for me.

Now because of this, I would like Geany to have the ability to limit the size of GUI icons.

![Screenshot(2)](https://github.com/geany/geany/assets/3245767/8a0ddd8f-b7d5-4e1b-a5c2-824ef15ddcf9)

**Comment by elextr** [comment]
The size of icons is determined by the GTK toolkit, not Geany, you could see what GTK CSS can do.

Since you didn't admit what you actually did to screw up your icons it might not be able to reduce the size.

**Comment by arteze** [comment]
Fortunately the command was saved in the bash history, what I did was this:

```sh
cd /usr/share/icons/flat-remix/places/small
ln -svr /usr/share/icons/Neu/128x128/actions/* .
```
I think that's what ruined it.

**Comment by arteze** [comment]
It looks better now, I think the problem is solved, or if something is going to be implemented I leave the topic open, otherwise I close it, as preferred.

![Screenshot(3)](https://github.com/geany/geany/assets/3245767/e0d69f22-c811-4193-8ec2-661ff277b4e4)

**Comment by elextr** [comment]
I think you have told the system that 128x128 icons are "small" so GTK uses them when told to use "small" icons

a. probably nothing can limit them, they are bitmap icons that can't be resized, no graphics toolkit has a whole bitmap image scaling tool (think Photoshop or Gimp) built in, only SVG icons are scalable (because they are Scalable Vector Graphics :-) 

b. you should fix the problem, by removing those links, not try to keep a broken system

**Comment by elextr** [comment]
Closed as not Geany

**Comment by arteze** [comment]
Another problem I have is that when I touch the open file button, it shows me a window to choose folders, and it shows me the wifi icon of the sda1 sda2 drive, do you know which file the icon refers to?

**Comment by elextr** [comment]
Nobody can see your system, or knows its arrangement, when asking questions like that you need to provide enough information to be able to understand it.

"sda1" and "sda2" usually refer to the raw disk partitions on a Linux system, not a file.

**Comment by arteze** [comment]
I already discovered it, it is:
```sh
/usr/share/icons/flat-remix/places/small/folder-remote-symbolic.svg
```
![Screenshot(5)](https://github.com/geany/geany/assets/3245767/abd9275f-8f21-4e11-b8fb-2576ff91a466)

It turns out that sda1 is a mounted volume and not a remote folder.

I already changed it for this one.

```sh
/usr/share/icons/flat-remix/places/small/drive-harddisk-symbolic.svg
```

![Screenshot(6)](https://github.com/geany/geany/assets/3245767/57c56a00-89c3-4856-997e-e38ea1652b22)

**Comment by elextr** [comment]
First, please do not spam all those watching this repository with massive listings, file contents, or other large content, place those in a Gist and put a link in the post here.

To emphasise, it is your GTK theme that specifies the icons on buttons, not Geany.  My theme has no icons on "View", "Cancel", or "Open".

As "View" is an additional button in addition to the standard "Cancel" and "Open" buttons its likely that the icon theme does not have a suitable icon and/or the theme you use does not map it to the button.  You can make tweaks to the GTK CSS by editing `Tools->Configuration Files->geany.css`, details [here](https://docs.gtk.org/gtk3/css-overview.html)

**Comment by arteze** [comment]
I understand, I already added the gist.

I'll have to study the CSS thing.

My whole system just ruined, but I have a backup, if I repair it I'll look at the CSS.
