### ISSUE TITLE
Silent Installation of Geany

### ISSUE THREAD

**Issue by metaad** [geany/geany#3734]
Hi,

I am trying to install Geany version 2.0 silently on windows 10 64Bit VM.
Please let me know if there are any parameters to install\select following features silently.

<img width="368" alt="image" src="https://github.com/geany/geany/assets/106653425/bba1d3a3-f7be-4fe2-9b88-a3c56a0208af">

**Comment by metaad** [comment]
Also old and new versions coexists. Is there any way to upgrade it silently?

<img width="476" alt="image" src="https://github.com/geany/geany/assets/106653425/4dae57a1-c252-4dfa-8fa2-7a360ad9c52d">

**Comment by metaad** [comment]
So if we uninstall previous version before installing the new one will it retain user's setting if any? and those same settings can be applied to new version after installation?

**Comment by elextr** [comment]
AFAIK the user configuration is normally in a user directory and isn't touched by the installer/uninstaller.  The configuration arrangement has recently changed, but a newer Geany should read the old configuration on opening and write the new one, but an older Geany will of course not know about a newer configuration arrangement.

**Comment by eht16** [comment]
I forgot to answer the question from the OP:
> Please let me know if there are any parameters to install\select following features silently.

There is no way to select/deselect components with the silent installer.
