### ISSUE TITLE
Set Build Command screen is to large can not click ok

### ISSUE THREAD

**Issue by roxanne562001** [geany/geany#3735]
I am using Geany 2 on LMDE 6 Cinnamon desktop. On a Laptop PC
The problem I am having is the Set Build screen bottom is bellow the monitor. In other words I change the set build items but I can not check the ok button because it is below the screen. I have tried every thing I can think of to reduce the size in order to get to the bottom. I was using Ubuntu 18.04 on the same laptop before and the Set build menu worked fine. Any insight would be appropriated. I love Geany and hope I can get it working on LMDE 6.
Thanks
Roxanne

**Comment by elextr** [comment]
The question is what is making it so high?  Everything is controlled by the GTK theme, which are you using?

**Comment by roxanne562001** [comment]
I am not sure I will look at it this evening. What ever theme it comes with on a fresh install. I never changed the theme. I was able to work around the problem last night by using the tab key and shift tab to move the cursor to the ok button and apply my settings.

**Comment by elextr** [comment]
The Mint menu (lower left corner) `Preferences->System Settings` then `Themes` and also check that no `Accessibility` is selected (some of those make stuff bigger), and that `Fonts` have a reasonable size (eg 10 pt) and multiplication factor of 1.
