### ISSUE TITLE
Caret position issues on Wayland

### ISSUE THREAD

**Issue by OpusElectronics** [geany/geany#3736]
I'm using Geany 2.0 on KDE/Plasma 5.27/Wayland and have been facing annoying issues with the caret position.
In some cases (I have not quite yet found the minimum steps to reproduce it though from a fresh start of Geany), the caret will either disappear altogether, or the text will not scroll to the correct position.

One typical way it happens is when scrolling multiple pages (so that the caret gets out of view) and clicking in the document to place the caret in the new position. When the issue arises, when clicking on the new position, the document will scroll back to the previous position of the caret. It doesn't usually happen until Geany has run for a while. Again not sure what exactly triggers it, but when that starts happening, it keeps doing that until Geany is quit and restarted.

Likewise, when doing searches, if the search has reached the end of the document and we agree to keep searching from the start of the document, then the document will not scroll to the position of the found occurence, but will stay where the caret originally was, and the caret disappears.

I'm not sure exactly how to give more information than this. It's easy to reproduce after a while in my case, but the minimal steps are not obvious (except that it eventually happens after some use.)

I had a similar issue with Geany 1.38 before upgrading to 2.0, so it's not new to the 2.0 version (but was kind of hoping it would fix it).

I have the "project organizer" plugin enabled, if that could make a difference.

**Comment by elextr** [comment]
> I had a similar issue with Geany 1.38 before upgrading to 2.0, so it's not new to the 2.0 version (but was kind of hoping it would fix it).

Probably not if it was not reported.

Is Geany running on Wayland or Xwayland?  There have been issues with Xwayland in the past, make sure its using Wayland directly which has often worked better by `GDK_BACKEND=wayland geany`.

**Comment by OpusElectronics** [comment]
Thanks, I was running it without setting the GDK_BACKEND env. variable, so I'm guessing it was by default using Xwayland?
I'm gonna test with this and will report back.

**Comment by OpusElectronics** [comment]
I've tested with ```GDK_BACKEND=wayland``` set, and it seems to solve all those caret issues on Wayland so far.
So, thanks for the tip.

**Comment by elextr** [comment]
As the Wayland feature set is (deliberately) a subset of X11, XWayland has to try and synthesise missing features if something (like GTK) uses them, and its not always possible or perfect.
