### ISSUE TITLE
can't start geany on wayland

### ISSUE THREAD

**Issue by coutouly** [geany/geany#3751]
it works on open box but not in wayland compositor.
geany -v
(geany:12218): GLib-GIO-DEBUG: 11:27:56.092: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(geany:12218): GLib-GIO-DEBUG: 11:27:56.092: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(geany:12218): dconf-DEBUG: 11:27:56.092: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
(geany:12218): dconf-DEBUG: 11:27:56.092: watch_fast: "/org/gnome/desktop/peripherals/mouse/" (establishing: 0, active: 0)
(geany:12218): dconf-DEBUG: 11:27:56.092: watch_fast: "/org/gnome/desktop/sound/" (establishing: 0, active: 0)
(geany:12218): dconf-DEBUG: 11:27:56.092: watch_fast: "/org/gnome/desktop/privacy/" (establishing: 0, active: 0)
(geany:12218): dconf-DEBUG: 11:27:56.092: watch_fast: "/org/gnome/desktop/wm/preferences/" (establishing: 0, active: 0)
(geany:12218): dconf-DEBUG: 11:27:56.092: watch_fast: "/org/gnome/desktop/a11y/" (establishing: 0, active: 0)
(geany:12218): dconf-DEBUG: 11:27:56.092: watch_fast: "/org/gnome/desktop/a11y/interface/" (establishing: 0, active: 0)
(geany:12218): dconf-DEBUG: 11:27:56.095: watch_established: "/org/gnome/desktop/interface/" (establishing: 1)
(geany:12218): dconf-DEBUG: 11:27:56.095: watch_established: "/org/gnome/desktop/peripherals/mouse/" (establishing: 1)
(geany:12218): dconf-DEBUG: 11:27:56.095: watch_established: "/org/gnome/desktop/sound/" (establishing: 1)
(geany:12218): dconf-DEBUG: 11:27:56.095: watch_established: "/org/gnome/desktop/privacy/" (establishing: 1)
(geany:12218): dconf-DEBUG: 11:27:56.095: watch_established: "/org/gnome/desktop/wm/preferences/" (establishing: 1)
(geany:12218): dconf-DEBUG: 11:27:56.095: watch_established: "/org/gnome/desktop/a11y/" (establishing: 1)
(geany:12218): dconf-DEBUG: 11:27:56.095: watch_established: "/org/gnome/desktop/a11y/interface/" (establishing: 1)
(geany:12218): Gdk-DEBUG: 11:27:56.112: Compositor prefers decoration mode 'server'
(geany:12218): GLib-DEBUG: 11:27:56.113: unsetenv() is not thread-safe and should not be used after threads are created
(geany:12218): GLib-GIO-DEBUG: 11:27:56.118: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
Geany-INFO: 11:27:56.143: Geany 2.0, unknown
Geany-INFO: 11:27:56.143: GTK 3.24.41, GLib 2.78.4
Geany-INFO: 11:27:56.143: OS: Archcraft
Geany-INFO: 11:27:56.143: System data dir: /usr/share/geany
Geany-INFO: 11:27:56.143: User config dir: /home/lucile/.config/geany
Geany-INFO: 11:27:56.212: Loaded GTK+ CSS theme '/usr/share/geany/geany.css'
Geany-INFO: 11:27:56.214: System plugin path: /usr/lib/geany
Geany-Message: 11:27:56.214: No user config file found, trying to use global configuration.
Geany-Message: 11:27:56.214: No user session file found, trying to use configuration file.
Geany-INFO: 11:27:56.217: Added filetype Arduino (65).
Geany-INFO: 11:27:56.217: Added filetype Scala (66).
Geany-INFO: 11:27:56.217: Added filetype Clojure (67).
Geany-INFO: 11:27:56.217: Added filetype JSON (68).
Geany-INFO: 11:27:56.217: Added filetype CUDA (69).
Geany-INFO: 11:27:56.217: Added filetype Cython (70).
Geany-INFO: 11:27:56.217: Added filetype Nim (71).
Geany-INFO: 11:27:56.217: Added filetype Groovy (72).
Geany-INFO: 11:27:56.217: Added filetype Genie (73).
Geany-INFO: 11:27:56.217: Added filetype Graphviz (74).
Geany-INFO: 11:27:56.217: Added filetype Kotlin (75).
Geany-INFO: 11:27:56.217: Added filetype Swift (76).
Geany-INFO: 11:27:56.217: Added filetype Meson (77).
Geany-INFO: 11:27:56.217: Added filetype TypeScript (78).
Geany-INFO: 11:27:56.226: Loaded libvte from libvte-2.91.so
Geany-INFO: 11:27:56.231: unknown : None (UTF-8)
(geany:12218): GLib-DEBUG: 11:27:56.283: g_unix_open_pipe() called with FD_CLOEXEC; please migrate to using O_CLOEXEC instead

**Comment by elextr** [comment]
Try `GDK_BACKEND=wayland geany -v`

**Comment by coutouly** [comment]
it doesn't work .

GDK_BACKEND=wayland geany -v
(geany:34230): GLib-GIO-DEBUG: 12:10:03.673: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(geany:34230): dconf-DEBUG: 12:10:03.673: watch_fast: "/org/gnome/desktop/interface/" (establishing: 0, active: 0)
(geany:34230): GLib-GIO-DEBUG: 12:10:03.673: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(geany:34230): dconf-DEBUG: 12:10:03.673: watch_fast: "/org/gnome/desktop/peripherals/mouse/" (establishing: 0, active: 0)
(geany:34230): dconf-DEBUG: 12:10:03.673: watch_fast: "/org/gnome/desktop/sound/" (establishing: 0, active: 0)
(geany:34230): dconf-DEBUG: 12:10:03.673: watch_fast: "/org/gnome/desktop/privacy/" (establishing: 0, active: 0)
(geany:34230): dconf-DEBUG: 12:10:03.673: watch_fast: "/org/gnome/desktop/wm/preferences/" (establishing: 0, active: 0)
(geany:34230): dconf-DEBUG: 12:10:03.673: watch_fast: "/org/gnome/desktop/a11y/" (establishing: 0, active: 0)
(geany:34230): dconf-DEBUG: 12:10:03.673: watch_fast: "/org/gnome/desktop/a11y/interface/" (establishing: 0, active: 0)
(geany:34230): dconf-DEBUG: 12:10:03.675: watch_established: "/org/gnome/desktop/interface/" (establishing: 1)
(geany:34230): dconf-DEBUG: 12:10:03.675: watch_established: "/org/gnome/desktop/peripherals/mouse/" (establishing: 1)
(geany:34230): dconf-DEBUG: 12:10:03.675: watch_established: "/org/gnome/desktop/sound/" (establishing: 1)
(geany:34230): dconf-DEBUG: 12:10:03.675: watch_established: "/org/gnome/desktop/privacy/" (establishing: 1)
(geany:34230): dconf-DEBUG: 12:10:03.675: watch_established: "/org/gnome/desktop/wm/preferences/" (establishing: 1)
(geany:34230): dconf-DEBUG: 12:10:03.675: watch_established: "/org/gnome/desktop/a11y/" (establishing: 1)
(geany:34230): dconf-DEBUG: 12:10:03.675: watch_established: "/org/gnome/desktop/a11y/interface/" (establishing: 1)
(geany:34230): Gdk-DEBUG: 12:10:03.686: Compositor prefers decoration mode 'server'
(geany:34230): GLib-DEBUG: 12:10:03.686: unsetenv() is not thread-safe and should not be used after threads are created
(geany:34230): GLib-GIO-DEBUG: 12:10:03.690: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’
Geany-INFO: 12:10:03.706: Geany 2.0, unknown
Geany-INFO: 12:10:03.706: GTK 3.24.41, GLib 2.78.4
Geany-INFO: 12:10:03.706: OS: Archcraft
Geany-INFO: 12:10:03.706: System data dir: /usr/share/geany
Geany-INFO: 12:10:03.706: User config dir: /home/lucile/.config/geany
Geany-INFO: 12:10:03.786: Loaded GTK+ CSS theme '/usr/share/geany/geany.css'
Geany-INFO: 12:10:03.788: System plugin path: /usr/lib/geany
Geany-Message: 12:10:03.788: No user config file found, trying to use global configuration.
Geany-Message: 12:10:03.788: No user session file found, trying to use configuration file.
Geany-INFO: 12:10:03.791: Added filetype Arduino (65).
Geany-INFO: 12:10:03.791: Added filetype Scala (66).
Geany-INFO: 12:10:03.791: Added filetype Clojure (67).
Geany-INFO: 12:10:03.791: Added filetype JSON (68).
Geany-INFO: 12:10:03.791: Added filetype CUDA (69).
Geany-INFO: 12:10:03.791: Added filetype Cython (70).
Geany-INFO: 12:10:03.791: Added filetype Nim (71).
Geany-INFO: 12:10:03.791: Added filetype Groovy (72).
Geany-INFO: 12:10:03.791: Added filetype Genie (73).
Geany-INFO: 12:10:03.791: Added filetype Graphviz (74).
Geany-INFO: 12:10:03.791: Added filetype Kotlin (75).
Geany-INFO: 12:10:03.791: Added filetype Swift (76).
Geany-INFO: 12:10:03.791: Added filetype Meson (77).
Geany-INFO: 12:10:03.791: Added filetype TypeScript (78).
Geany-INFO: 12:10:03.801: Loaded libvte from libvte-2.91.so
Geany-INFO: 12:10:03.806: unknown : None (UTF-8)
(geany:34230): GLib-DEBUG: 12:10:03.846: g_unix_open_pipe() called with FD_CLOEXEC; please migrate to using O_CLOEXEC instead

**Comment by elextr** [comment]
Don't know, all the messages from Geany itself look perfectly normal, so its seems GTK and the Wayland server are giving each other indigestion.  

Without having a system to replicate the problem (Wayland works for others just fine on Gnome/KDE) its hard to say whats wrong, but it looks to be within GTK/GDK and the [unsepcified]Wayland server so its hard to advise what to look for.

**Comment by coutouly** [comment]
I use hyprland . It works well until an système update. I dont know where to look for..
Any help would bé apriciate
