### ISSUE TITLE
MSYS2 package for Geany

### ISSUE THREAD

**Issue by iahung2** [geany/geany#3756]
Please help.

https://github.com/msys2/MINGW-packages/issues/19704

https://github.com/msys2/MINGW-packages/pull/19963

**Comment by elextr** [comment]
The Geany project does not make packages, each platform has its own rules and often patches to fit into.  The project does not have resources/expertise to support all platforms.

But the project does make a [Windows installer](https://download.geany.org/geany-2.0_setup.exe) which bundles all the required dependencies (GTK etc) and IIUC is based on msys.  This is provided by one person and its unlikely that they will have the effort available to support another windows package.

**Comment by iahung2** [comment]
> But the project does make a [Windows installer](https://download.geany.org/geany-2.0_setup.exe) which bundles all the required dependencies (GTK etc) and IIUC is based on msys. This is provided by one person and its unlikely that they will have the effort available to support another windows package.

What very ironically is Geany on Windows is built using MSYS2, but Geany source code will not built out of the box on MSYS2.

**Comment by rdipardo** [comment]
> Geany source code will not built out of the box on MSYS2.

See https://github.com/geany/infrastructure/tree/master/builders#windows-mingw64-build

**Comment by elextr** [comment]
@rdipardo thanks, I was looking for that and couldn't find it.  Looks like I was unwittingly technically accurate, it builds _with_ msys packages on debian, not _on_ msys :grin:.

But maybe looking at that could show the folks trying to make an msys package what is missing in their environment.

**Comment by eht16** [comment]
JFTR, I commented on https://github.com/msys2/MINGW-packages/pull/19963.
Using Meson to build Geany on Windows at this point is very risky and the experiences the people described confirm the early stage of Meson support in Geany on Windows. No surprise.
