### ISSUE TITLE
xsession errors

### ISSUE THREAD

**Issue by duck7000** [geany/geany#3768]
my xsession error file is flooding with this warnings/errors, i mean hunderds

```
(geany:14905): Gtk-CRITICAL **: 21:00:38.936: _gtk_css_image_get_surface: assertion 'surface_height > 0' failed

(geany:14905): Gtk-CRITICAL **: 21:00:38.936: _gtk_css_image_get_concrete_size: assertion 'default_width > 0' failed
```

Next to those these are also in xsession related to geany:

```
(geany:14815): Gtk-WARNING **: 20:58:15.487: Negative content height -5 (allocation 1, extents 3x3) while allocating gadget (node entry, owner GtkEntry)

(geany:14815): Gtk-WARNING **: 20:58:15.487: Negative content width -1 (allocation 1, extents 1x1) while allocating gadget (node scrolledwindow, owner GtkScrolledWindow)

(geany:14815): Gtk-WARNING **: 20:58:15.487: Negative content width -17 (allocation 1, extents 9x9) while allocating gadget (node entry, owner GtkEntry)

(geany:14815): Gtk-WARNING **: 20:58:15.487: gtk_widget_size_allocate(): attempt to allocate widget with width 13 and height -23

(geany:14815): Gtk-CRITICAL **: 20:58:15.487: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar

```
This is on EndeavourOS xfce  (Arch linux like Manjaro)
Geany version 2.0 non git version
Using GTK+ v3.24.41 and GLib v2.78.4 runtime libraries

**Comment by elextr** [comment]
These look very similar to the messages that appear on the terminal when the plugin manager is opened.  I am told by those who should know that its harmless, and is due to GTK changing its layout algorithm back in the unstable days in a way that broke working code.  Perhaps you can try and see if they occur when the plugin manager dialog is opened.

**Comment by duck7000** [comment]
Sure i believe that it is harmless, but the main problem is flooding xsessions file, after a few hours of using geany the file grows exponential.

So it would be very nice if those errors could be solved so xsession file does not grow so big?

if i start geany on the terminal those errors are there (like 20-50 times) without opening the plugin manager

**Comment by elextr** [comment]
On Linux Mint I get no Geany xsession errors at all so have nothing to "fix", and AFAIK no regular Geany contribs use Arch any more so they may not get any either.  Being bleeding edge Arch, Is your X Xorg or Xwayland?

**Comment by duck7000** [comment]
I use Xorg

Ah well if none of the geany devs uses Arch that explains a lot i guess but still why Linux Mint doesn't have any warnings and Arch do remains the question. Apparently on Arch there are differences?

Is there any solution to stop those errors to be in xsessions file?
I don't think that simply stating it works on Mint so nothing to fix is too short, but if none of the devs uses Arch i understand that this never occurs to them.

**Comment by elextr** [comment]
> why Linux Mint doesn't have any warnings and Arch do remains the question. Apparently on Arch there are differences?

Afraid I have no idea what is different except the version of xorg and maybe GTK and maybe options they use, I am using a LTS distro, but Arch is bleeding edge.

> Is there any solution to stop those errors to be in xsessions file?

Don't know, possibly xorg docs might help, one would think there is a way to limit it?

> I don't think that simply stating it works on Mint so nothing to fix is too short, but if none of the devs uses Arch i understand that this never occurs to them.

"nothing to fix" is short (pun intended) for "cannot reproduce, so cannot debug, so cannot find a fix, and so cannot test any fix that is found" ;-)

**Comment by duck7000** [comment]
well yes you are right, thanks

**Comment by intact** [comment]
Your gtk theme probably do that

**Comment by duck7000** [comment]
@intact
that might be the problem, never thought of that.
I use Matcha theme

**Comment by duck7000** [comment]
I tried the standard adwaita theme.. no more errrors or warnings from Geany anymore!

so now i finally know why, thanks a lot!

**Comment by intact** [comment]
they probably use negative margins or paddings and (probably empty) element ends up with negative dimensions

**Comment by duck7000** [comment]
Normally i report issues to the developer but this developer never responded to my previous issue about margins not correct (and probably related to this problem as well)
So i decided to keep using Adwaita for now
