### ISSUE TITLE
Python print() doesn't work well.

### ISSUE THREAD

**Issue by Independent-X** [geany/geany#3772]
**Problem:**
Maybe because Microsoft updates cmd.exe and makes it buggy. Using:
`py "%f"`
to execute can cause the python print() function missing data. 

For example, you can see from this screenshot:

![image](https://github.com/geany/geany/assets/58306791/915f6b8c-7760-47a5-8089-09975093aac2)

The output has been cut off and it only contains the 17th row to 30th row. 

**Resolution:**

Using
`PowerShell.exe py "%f"`
to execute will not causing these problem.

Please set the default execute command to `PowerShell.exe py "%f"`, instead of `py "%f"`.

**Comment by eht16** [comment]
On my old Windows 7, a "cmd.exe" is opened and the full output is available and there is a scrollbar to see the first lines of the output.

Changing the default execution command to "PowerShell" seems wrong and would require that PowerShell is installed.
Maybe you can check if the cmd.exe of newer Windows versions can be configured to show a scrollbar

**Comment by Independent-X** [comment]
No, there is a scrollbar and... if I scrolls it, cmd.exe will show more buggy informations.
![image](https://github.com/geany/geany/assets/58306791/9f488d5c-13a0-4535-a02f-e5fe9d774268)

The bug seems only happens when I execute the program with geany. If I type the execute command in cmd.exe, the output is not buggy.
![image](https://github.com/geany/geany/assets/58306791/6367a991-fbfa-4023-b1f4-15241ddffe5c)
