### ISSUE TITLE
Dark variant of Geany's default UI theme on Windows `Prof-Gnome`

### ISSUE THREAD

**Issue by iahung3** [geany/geany#3783]
Turn on the dark variant: create the file `settings.ini` in `C:\Users\[username]\AppData\Local\gtk-3.0` (create the folder `gtk-3.0` if it doesn't exist) with the content:

```
[Settings]
gtk-application-prefer-dark-theme = true
```

Well, now you can try the Geany's default dark UI theme on Windows. The only problem is, it sucks. But it's the only thing we have out of the box. GTK experts and Geany experts, please chime in and tweak it. I'm very willing to test. Thank you.

**Comment by elextr** [comment]
Always put version of Geany and platform (Windows) on first posts, unless someone notices the `C:` they have no idea you are on windows.  There are many people who are only occasionally respond here and relying on them to remember your platform or even to have read your other posts won't work.  Make it easy for them and you will get more help.

> The only problem is, it sucks. 

I bet someone loves it, and you just called their baby ugly. :grinning: Thats the problem with themes, they are personal preference.

The theme is copied from one available on the web that is licensed to allow us to use it as a base and the light version was close(ish) to looking like windows.  Its not one we made.  As I noted elsewhere, we then had a lot of discussion about it and (IIRC) made some changes, but I'm not sure we even considered the dark variant, certainly I never knew it existed.

Thanks for the offer to test, at least that means there is a regular Windows user to do so, the rest of the contributors do not use Geany on Windows (or not regularly anyway).

So let the :bike: :house: begin.
