### ISSUE TITLE
How to hide mouse cursor on Linux

### ISSUE THREAD

**Issue by abdulbadii** [geany/geany#3788]
How, on Linux, do we have geany will automatically hide the mouse pointer when it's still and  a key is being pressed , for quite time till the pointer begins again getting moved

Linux DE: Xfce, GTK or Qt, X11 or wayland

**Comment by elextr** [comment]
AFAIK there is no such capability in Geany.

**Comment by abdulbadii** [comment]
neither me, that's why said, specified, `Linux DE: Xfce, GTK or Qt, X11 or wayland`

one X11:
https://github.com/jcs/xbanish

**Comment by elextr** [comment]
That has nothing to do with Geany so why have you raised an issue here?
