### ISSUE TITLE
Python print() doesn't work well.

### ISSUE THREAD

**Issue by Independent-X** [geany/geany#3798]
There was a mistake in my formal issue#3772.

Python print() will be buggy if I use execute command
```
py "%f"
```
and print too many rows at one time.

**Bug Example**

For example, the picture below shows the output of
```
for i in range(40):
	print(i,"test test test")
```

Execute with geany's execute button:
![image](https://github.com/geany/geany/assets/58306791/9f488d5c-13a0-4535-a02f-e5fe9d774268)

Type the execute command in cmd.exe:
![image](https://github.com/geany/geany/assets/58306791/6367a991-fbfa-4023-b1f4-15241ddffe5c)

#System Version
Windows 11 22H2
Version 10.0.22621.3296
Windows Feature Experience Pack 1000.22687.1000.0

_Originally posted by @Independent-X in https://github.com/geany/geany/issues/3772#issuecomment-2016544156_

**Comment by elextr** [comment]
Geany just starts the program, it actually runs as a separate process entirely under windows so this has nothing to do with Geany and there is nothing we can do to change the behaviour.  Perhaps look on Windows forums I think I have seen reference to something similar elsewhere.

**Comment by eht16** [comment]
I cannot reproduce this (similar to #3772).

Either it is related to Windows 11 vs my Windows 7 or some settings. But as @elextr said, Geany just starts the configured command.
