### ISSUE TITLE
[Feature request] Show the full path of opened files in geany

### ISSUE THREAD

**Issue by rubyFeedback** [geany/geany#3800]
So I recently decided to abandon my old gtk2-based editor after some +15 years,
largely because I can no longer compile gtk2 from source, for reasons related
to the glib stack (something has been deprecated and I don't know the workaround,
but I can no longer wait for anyone upstream patching gtk2, so I now took the
full dive finally).

I toyed with the idea of using sublime, but I think I am less likely to adjust sublime towards
behaviour I am quite used to, as opposed to geany, which is open source. So I'll give
geany a more serious try this time. I used it in the past before already, e. g. for C++ files, 
and I even remember Enrico (I think? the original dev) but I have not yet used geany for
**all** (text) files. Right now I am using geany for ALL files.

There are many small issues but I don't want to spam the issue tracker with tons
of ideas that are possibly only for my own use case. Nonetheless I hope to be
able to convince the geany devs towards more flexibility in general, via options
and preferences we could toggle as-is. Geany already supports quite many 
options, so I hope we can support even more options - if they make sense.

Alright - now to the issue here.

First, have a look at this screenshot:

https://i.imgur.com/mWzOafF.png

You can see the open files. Evidently I am currently modifying a german exam
question test for evolution of hominids / hominidae :D - the key issue, though,
is the pop-up widget that shows the opened files.

The currently selected file is shown in bold - that is nice.

However had, often I can not tell WHERE the files are. Some may be same-named
or similarly-named, so I would like to also have the option to show the full path
right there (left-padded, e. g. all are aligned towards the left-side, but on the
right side we may allow overflow; the full widget width would thus be determined
by the file with the longest name.)

I am very much used to that behaviour from my old editor, where I can see the
full path at all times.

So, my issue request would be for geany to add an option to show the FULL 
path instead, rather than the truncated path (in ruby, the filename itself
would be obtained via File.basename(), so instead I would be looking for
File.absolute_path() - not sure how C does this but perhaps gtk has some 
method that shows the full path).

In the option dialogue, we would then have to add a new entry at
**Preferences -> Files**; perhaps call it, as a check-button, "Show full
path of files". This would NOT be the default, so everyone could enjoy
the current behaviour of geany, rather than adjust to the one proposed
in this issue request.

As for a more objective rationale for this feature: we would instantly
know where the file resides at. (Actually, my old editor not only made
the current file bold, but used different colours too. But I am perfectly
fine without colours here too, I just need the feature that I know the
full path at all times, as this is less confusing to me than merely the
short-filename itself as such.)

**Comment by ralf3u** [comment]
>However had, often I can not tell WHERE the files are.

Do you know that if you go with the mouse over a tab-title, the full path will appear?

**Comment by neoh4x0r** [comment]
> > However had, often I can not tell WHERE the files are.
> 
> Do you know that if you go with the mouse over a tab-title, the full path will appear?

You can also use the **Tree Browser / File Browser** plugins to browse the directory where the current file is stored.

I personally prefer the Tree Browser because I can right-click on a file and copy the full path.

**Comment by neoh4x0r** [comment]
I think showing the full path on the notebook context menu would present a major problem because the menu text would go off-screen. The full path could be shown using an ellipse-truncation method, but you wouldn't see the full path then anyway.

**Comment by elextr** [comment]
@neoh4x0r 

> I personally prefer the Tree Browser because I can right-click on a file and copy the full path (...and to my knowledge this ability is not available anywhere else).

Since you are enabling plugins :-) the Addons plugin adds a menu item to Tools to copy filepath of the current document and it can be keybound no need for Tree Browser.

**Comment by elextr** [comment]
As noted by @neoh4x0r making the tabs show the whole path will make them too big to fit more than a few.

There are a number of alternativess, as noted by @ralf3u the full path is shown by hovering on the tab, as noted by @neoh4x0r the various tree/file browser plugins show the full trees, and I will add a note that the builtin `Document` sidebar also shows the path to the open tabs.

So its unlikely that another option to show the same info will be accepted.

**Comment by spazmodic** [comment]
Agree. Would be nice if there was an option to display full filepath of currently open document at the bottom of the window. This is something other text editors/readers etc. have. Another workaround is: for current document, open message window, add one white space, save the document, and view the filepath of this new change appear in the message window. It's good to set a shortcut to show/hide message window for this purpose. A bit messy, but works.
