### ISSUE TITLE
[Small bug] (I think): geany appends a newline upon saving a file

### ISSUE THREAD

**Issue by rubyFeedback** [geany/geany#3801]
I have in Edit -> Preferences set 
"Ensure new line at file end"
clicked off, e. g. the checkbox has no checked-arrow there.

Yet upon saving the file (a .rb file), geany still appends a newline there.

Does this work for other folks?

Irrespective of whether this is a bug or not, I'd like to see this behaviour
not be enabled by default. Reason being that an editor should be 
"what you type is what you get" rather than automatically append
the file content by default. (It's ok to have this as an option of course,
but it should not be the default.)

If there was an old discussion about this behaviour perhaps someone
can provide a pointer to it.

**Comment by elextr** [comment]
I see you found #2560, see there.
