### ISSUE TITLE
Remove all items of the tab-switcher except the tab-titles

### ISSUE THREAD

**Issue by ralf3u** [geany/geany#3806]
**Steps to reproduce**
open Geany
press Shift+F10

**Result**
The tab-switcher appears with some entries that ar not tab-titles. The entries are:
```
Open in New Window
Close
Close Other Documents
Close Documents to the Right
Close All
```

**Expectation**
Only tab-titles should appear in the tab-switcher.

**Remark I**
The items disturb specially for small screens when using a lot of tabs, because one need to scroll through the tab-switcher to find the right tab-title. I can remember that in the editor Notepad++ there were only tab-titles in the tab-switcher and that was fine. Till today I never used the items of the tab-switcher. If you don't want to remove the items of the tab-switcher, then it would be good to offer the items as option in the Preferences. Maybe the items should be deactivated by default.

**Remark II**
Maybe it would be good to offer two different tab-switchers. One tab-switcher with the items appears directly next to the mouse when you right-click on a tab-title. The second tab-switcher without items would appear when pressing the shortcut Shift+F10, and would appear always centered (horizontally and vertically) in the window (like once in the editor Notepad++), because it is the best position for switching tabs and the best position for an enlargement of the list.

**System**
Lubuntu 23.10
Geany 1.38

**Comment by ralf3u** [comment]
Please delete this issue because I just recognized that there is a tab-switcher in Geany without items when pressing **Ctrl+tab.**

I'm sorry for this report.

**Comment by elextr** [comment]
We don't delete issues, and we try to encourage people to search open _and_ closed issues before posting, so all issues are kept because even this one answers a question.
