### ISSUE TITLE
visual design

### ISSUE THREAD

**Issue by kr5jv1** [geany/geany#3810]
Hi, at the moment my Geany displays code blocks in a similar way 
![3_3](https://github.com/geany/geany/assets/93582086/61a14f49-9d93-45a3-abec-4220bb16ff9c)

I want to achieve such a design

![1_1](https://github.com/geany/geany/assets/93582086/afde20af-7fca-438d-928d-29c05e9441ac)
![2_2](https://github.com/geany/geany/assets/93582086/cce742de-270d-42f7-8494-9b806e02c526)

I would be extremely grateful to the community for any manuals or howto on this topic. P.S. I am not an experienced Geany user

**Comment by elextr** [comment]
For alternative colour schemes see [geany-themes](https://github.com/geany/geany-themes)

**Comment by kr5jv1** [comment]
> For alternative colour schemes see [geany-themes](https://github.com/geany/geany-themes)

This partially solved my difficulty. It remains to configure the opening / closing "{ }"

**Comment by elextr** [comment]
[brace_good, brace_bad](https://github.com/geany/geany/blob/1735daeb2cff6022cf9f5da6b13d6f2340cca6e1/data/filedefs/filetypes.common#L112)

**Comment by kr5jv1** [comment]
> [brace_good, brace_bad](https://github.com/geany/geany/blob/1735daeb2cff6022cf9f5da6b13d6f2340cca6e1/data/filedefs/filetypes.common#L112)

Thanks for the help
