### ISSUE TITLE
Meaning of "Value: 0" in terminal seems to be undocumented

### ISSUE THREAD

**Issue by Gitoffthelawn** [geany/geany#3822]
When running Geany (v1.38) from the terminal, Geany issues the string `Value: 0` to the terminal.  This almost looks like a return value, but it appears as soon as Geany is launched (not when it terminates).

I searched the Geany documentation and did not find an explanation for the meaning of this value or an official way to instruct Geany to suppress it.  I did find that redirecting standard output to `/dev/null` did hide the seemingly undocumented message: `geany > /dev/null`

Is this message intentional or a bug?  If it's intentional, what is the meaning?  Can it be added to the documentation (or did my search simply not find it)?  Is there a Geany option to suppress it?  Can one be added?

**Comment by elextr** [comment]
Doesn't happen here.  Try `geany -p` to see if its a plugin.  If it is start with only one at a time enabled until you find which one then report on the geany-plugins repo.

**Comment by Gitoffthelawn** [comment]
> Doesn't happen here. Try `geany -p` to see if its a plugin. If it is start with only one at a time enabled until you find which one then report on the geany-plugins repo.

Thank you.  It's a plugin.  I will narrow it down to determine which one it causing that output and then report on `geany-plugins` repo if appropriate.  Thanks again.

**Comment by Gitoffthelawn** [comment]
I determined it is the Line Operations (AKA `lineoperations`) Geany plugin.  I posted an issue report in the corresponding repo: https://github.com/geany/geany-plugins/issues/1322

At least for now, is there any harm in redirecting Geany's standard output to `/dev/null` (i.e. `geany > /dev/null`)?

**Comment by elextr** [comment]
It not going to be harmful, just you will miss any other messages that come from libraries like GTK, although most of them should be stderr not stdout.  And after all when Geany is run from the desktop menu stdout/stderr messages are usually lost, so its no worse.

**Comment by Gitoffthelawn** [comment]
> It not going to be harmful, just you will miss any other messages that come from libraries like GTK, although most of them should be stderr not stdout. And after all when Geany is run from the desktop menu stdout/stderr messages are usually lost, so its no worse.

Thank you.  I appreciate it.
