### ISSUE TITLE
JavaScript ctags doesn't handle IIFE pattern

### ISSUE THREAD

**Issue by CraigKelly** [geany/geany#383]
For instance, the symbol list is populated correctly from:

```
function x(){
    var y = function() {};
}();
```

But this results in an empty symbol list and the warning "Warning: ignoring null tag in [file]":

```
(function x(){
    var y = function() {};
})();
```

Frankly, I tried to find a quick fix by modifying skipArgumentList in tagmanager/ctags/js.c, but just ran out of time.

**Comment by b4n** [comment]
I think this has been fixed by one of the numerous changes to the javaScript parser since the time.  Feel free to reopen if relevant.
