### ISSUE TITLE
JSON syntax highlighting

### ISSUE THREAD

**Issue by nisargjhaveri** [geany/geany#384]
I cannot find any default JSON file-type support. It would be useful to add it by default.

**Comment by eht16** [comment]
Setting the filetype to JavaScript for JSON files works pretty good.

For full support, we would need a Scintilla(www.scintilla.org) lexer to support JSON highlighting.
Though the JavaScript highlighting works well enough, IMHO.

You can easily add a custom filetype to permanently make Geany opening JSON files as JavaScript. For details see http://wiki.geany.org/config/json.

If you heavily disagree, please re-open.

**Comment by nisargjhaveri** [comment]
I still think that there should be out-of-the-box JSON support as JSON is now a widely used file-type and not everyone want/able to configure Geany like the suggested methods.

I agree that it works perfectly with JavaScript highlighting. Can we just add those config options by default?

**Comment by b4n** [comment]
> I still think that there should be out-of-the-box JSON support as JSON is now a widely used file-type and not everyone want/able to configure Geany like the suggested methods.

Agreed, that's something worth having by default.  We could easily distribute the/a JSON (custom) filetype.

If we want to go further, I also added JSON tag parser to CTags recently, so we could also add this -- but this means a full-blown built-in filetype.

BTW, latest Scintilla has support for folding on `[]` in the JavaScript lexer, so it gives better folding for JSON.

**Comment by eht16** [comment]
@b4n correct me if I'm wrong: couldn't we just add the JSON tag parser and reference it from the custom JSON filetype using the "tag_parser" setting? It would be probably new that we would have a tag parser which is not used by any builtin filetype but this probably is not that bad. We probably just to document it at some place to not remove the tag parser from Geany in 5 months because we think it is not used :).

**Comment by b4n** [comment]
> @b4n correct me if I'm wrong: couldn't we just add the JSON tag parser and reference it from the custom JSON filetype using the "tag_parser" setting?

I think currently what is used to reference a parser in the *tag_parser* setting is the name of the *filetype* that has it, so it wouldn't work.  But I'll give it a look, it's indeed a good idea if it works.

**Comment by b4n** [comment]
OK, reading the code suggests I'm wrong and it uses the CTag name, so your solution would work just fine.

**Comment by b4n** [comment]
See #415

**Comment by mozzbozz** [comment]
Well, nice that you've added a complete new(?) JSON parser, but at least for now (as a workaround until it is included in the next release), you can use the YAML filetype which works quite well - including collapsing parts of the JSON tree etc. - they are not the same but really similar. I've used the YAML parser for quite some time now and was happy enough with it to not file a bug here ;)

**Comment by MikePryadko** [comment]
Hi everyone!
I can't understand: is THAT
![geany_json](https://user-images.githubusercontent.com/31248040/74051160-858be680-49e8-11ea-9cb5-f1d5a1c68f5b.png)
a "good" highlighting..??
Version (from ubuntu repository):
![geany_version](https://user-images.githubusercontent.com/31248040/74051325-c683fb00-49e8-11ea-9273-77f98a8ba393.png)
IMHO it should looks like that:
![good_json](https://user-images.githubusercontent.com/31248040/74051699-8113fd80-49e9-11ea-8464-c519e198b4b7.png)

How can I help you..?

**Comment by elextr** [comment]
@MikePryadko you can help by:

1. upgrade to the current version built from source (not that I think its any better, but its a prerequisite for the next step, and reporting problems on very old versions on closed issues is rarely effective)

2. write the C code to make JSON a full filetype so you can add the JSON highlighting lexer from Scintilla (assuming that does what you want).  Currently JSON uses Javascript which uses the C highlighter.  Pull requests are welcome.

**Comment by MikePryadko** [comment]
@elextr look what I found: https://sourceforge.net/p/scintilla/feature-requests/1140/
After it I've installed SciTE and BAM! it highlights JSON correctly!
![scite](https://user-images.githubusercontent.com/31248040/74081824-3b484b00-4a64-11ea-9d86-0422f60943e2.png)
![scite_version](https://user-images.githubusercontent.com/31248040/74081830-400cff00-4a64-11ea-9e2a-1170477f74c7.png)
Current version of scintilla is 4.3.0 - maybe you should update it in geany..?)

**Comment by elextr** [comment]
> Current version of scintilla is 4.3.0 - maybe you should update it in geany..?)

Pull requests are welcome.

**Comment by b4n** [comment]
> > Current version of scintilla is 4.3.0 - maybe you should update it in geany..?)
> 
> Pull requests are welcome.

Actually no, they aren't for updating Scintilla (because it's an automated process and it's hard to review).

This said, there is no need to update Scintilla, it's just that we don't use (or build) the JSON lexer, but it exists.  We could build the lexer and use it for JSON.  And for that, PR are welcome indeed :slightly_smiling_face:

**Comment by elextr** [comment]
@b4n, agreed https://github.com/geany/geany/issues/384#issuecomment-583663995
