### ISSUE TITLE
Unable to "Build" using Geany

### ISSUE THREAD

**Issue by Farticus6969** [geany/geany#3863]
I am writing a program that uses gtk. I'm starting off easy to get the hang of Geany as my real target will be the Raspberry Pi's. There was a video on youtube eliminating the "gtk.h not found" issue (https://www.youtube.com/watch?v=-p5e-rZC64w), the program now compiles fine on my Ubuntu 20.04 machine.
.
When it come time to "Build" I always get this error message(/bin/sh: -c: line 1: unexpected EOF while looking for matching `"').
The Edit-Preferences-Tools-Terminal option is the default:
.
xterm -e "/bin/sh %c"
.
fatal error. Any idea would be most appreciated.
Thanks in Advance,
Bill

**Comment by elextr** [comment]
The terminal setting has nothing to do with the Build command.  The default build command for C does not use "/bin/sh". What have you set the build command to?

**Comment by Farticus6969** [comment]
ALL settings are default with the exceptions mentioned in that youtube
video. I'm having the same issue with Code::Blocks.

Ubuntu 20.04 LTS
Geany 2.0 Build date: 4-26-2024 from the repository.
Code::Blocks 20.03 also from repository.
Gtk+ 2.0 & 3.0 are installed and verified as well as being found on the
harddrive (admin:/// trick).

Never had an issue using Anjuta 3.34.0 .

Figured I'd use the laptop to get the rough code written and then transfer
the code to the Raspberry Pi's for their specific functions as a Master
controlling Arduinos to do the "grunt work".

Thanks for the quick comeback,
Bill

**Comment by elextr** [comment]
> ALL settings are default with the exceptions mentioned in that youtube video.

You are asking for help, so requiring people to watch a video to be able to help you means you have reduced the number who will bother, they simply don't have time.

As I said, the default "Build" operation for C language does not use `/bin/sh` so either you have changed something or you are not performing a "Build" operation.

**Comment by elextr** [comment]
Try a space between the `"%f"` and the text you added.

**Comment by Farticus6969** [comment]
No change. Still vigorously researching on my end.
Luckily I brought my laptop with me to the hospital so I've got plenty of
time (no improvement in 3 days).

Thanks again,
Bill

**Comment by elextr** [comment]
Well, the original error message indicates the backticks don't match, maybe post the text from the build command entry (not from the website) on a line by itself with a line of ``` before and another after it so its not recognised as markdown.  If we can't see exactly what you are inputting again we can't help.  Also post the error message each time just in case there is some subtle difference you missed.

**Comment by Farticus6969** [comment]
I've went over that line character by character (added the space as you
recommended), all backticks are matched (unless I'm missing something, new
to Linux programming never had this issue with windoze). The line cut &
pasted from the "Set Build Commands" is:

*gcc -Wall -o "%e" "%f“ `pkg-config --cflags gtk+-3.0`
-DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_0 `pkg-config --libs gtk+-3.0`*

I need this to be a Linux program as I will be using it on a Pi, the
Arduino software I had no problem with. I've gone over the Geany
documentation heavily, understand a bit more, compiles fine to the .o file
but no further.

Can't thank you enough for the pointers,
Bill

**Comment by Farticus6969** [comment]
Forgot - Error Message always:

*/bin/sh: -c: line 1: unexpected EOF while looking for matching `"'*

**Comment by Farticus6969** [comment]
Using Synaptic I just re-installed all the files for gtk+ 3.0 wondering if
something got messed up from a long time ago. No improvement.

**Comment by elextr** [comment]
Ok, your problem is that for some reason the website has a `*` at the start and end of the command, those should not be there.

**Comment by elextr** [comment]
Also I presume its all one line in the build command entry?

**Comment by elextr** [comment]
Note that the problem is nothing to do with Geany (or codeblocks) its the command you are entering.  The best approach is to get commands to work in the command line and then paste them into tools.

**Comment by Farticus6969** [comment]
Yes - one line.
I ran that line through a text editor & word processor I did not see a
single * in it.

The compile part works fine.

Just manually upgraded gcc (9.04 to 11, maybe something was outdated, no
luck). Wish I knew which file was the issue and where to look, only have
one "c" file I copied from the gtk+ website to get starter and it compiles
fine.

So sorry to keep bothering you,
Bill

**Comment by elextr** [comment]
Please post the string from the build entry in github, not via email, the string you have posted [here](https://github.com/geany/geany/issues/3863#issuecomment-2091366390) starts and ends with `*`.

**Comment by Farticus6969** [comment]
I went back to the link you mentioned, Yes it does have the beginning and
ending stars I never placed them in the edit window. What I have in the
entry lines DO NOT. I've attached a screenshot of my

*Geany -> Set Build Commands*

window.

Thank you again.

**Comment by elextr** [comment]
Your image did not come through.  

As I said above, you should interact via the github website.  Github is not a mailing list, it is a website, and emails are largely intended for notifications.  Although you can post via email the variation in the behaviour of mailing tools means many features are missing or stripped from email posts.

Also edits are not notified via email, so if a poster makes a mistake and edits their post to reverse the meaning (eg add a missing "not") you will not know when you reply to the initial post.  Eg if they say "I like cats[^1]" and then edit it to "I do not like cats" you will only see the first and your email reply of "me too" will indicate the opposite of your intention.

[^1]: substitute any contentious topic for "cats"

**Comment by Farticus6969** [comment]
I tried to edit 3863 and post last email and it's screenshot but it is
flagged as closed.

Can it be changed back to open or do I need to start a new issue
referencing 3863?

**Comment by Farticus6969** [comment]
Using github is a hit-or-miss thing with me as I usually don't have internet  access. Only reason I do now is I'm in the hospital soon to be transferred back to the Wound Care Center, that's why I've been using email not understanding that would force a "Closed" status. Hopefully This will re-open it. I am resubmitting the lost screenshot.

Thanks again,
Bill

![Screenshot from 2024-05-03 02-38-31](https://github.com/geany/geany/assets/168656611/95e4799a-24b7-46f6-803c-1f391f42483d)

**Comment by Farticus6969** [comment]
I did enter a comment, don't know if that will re-open #3863.
First time using github except to download dban, knoppix std & chirp, never
to ask for help.

Thanks,
Bill

**Comment by b4n** [comment]
> ```shell
> gcc -Wall -o "%e" "%f“ `pkg-config --cflags gtk+-3.0` -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_0 `pkg-config --libs gtk+-3.0`
> ```

The issue you have is that the 4th quote (after the `%f`) is not an ASCII quote, but U+201C *Left Double Quotation Mark*.  Just replace the command with:
```shell
gcc -Wall -o "%e" "%f" $(pkg-config --cflags gtk+-3.0) -DGDK_VERSION_MIN_REQUIRED=GDK_VERSION_3_0 $(pkg-config --libs gtk+-3.0)
```

and you'll be on your way (I also replaced the `\`\` with `$()` because it can be nested, and generally creates less problem when you modify the command -- but functionally it's the same here).

**Comment by elextr** [comment]
> The issue you have is that the 4th quote (after the %f) is not an ASCII quote, but U+201C Left Double Quotation Mark. Just replace the command with:

Wow eagle eyed!! :eyes:

**Comment by Farticus6969** [comment]
THANK YOU!!!

~Ubuntu~

**Comment by Farticus6969** [comment]
THANK YOU!!!

~Ubuntu~
