### ISSUE TITLE
Windows: allow forward slashes (/) instead of backslashes (\) in "Open file" dialog

### ISSUE THREAD

**Issue by cousteaulecommandant** [geany/geany#3868]
On Windows, when I open a file, press Ctrl-L, and enter a relative path using forward slashes (`/`) instead of Windows's official backslash path separator (`\`), Geany doesn't understand that and produces a confusing error message.

Specifically, if I go to `C:\Users\cousteau\` and enter `AAA/BBB/ccc.txt`, I get "Error: couldn't find `C:\Users\cousteau\AAA\BBB\AAA\BBB\cc.txt`.  Note that the directory part (`AAA/BBB/`) appears twice, but other than that it looks like Geany is somewhat able to parse the path.  If instead I enter `AAA\BBB\ccc.txt`, Geany will open `C:\Users\cousteau\AAA\BBB\cc.txt` without complaining.

This is a bit inconveniencing because I often work with Unix-like environments (Git bash shell, MinGW, MSYS, WSL, tools and languages that ignore Windows's odd decision to use backslashes and use the usual `/` instead, etc), so whenever I get a file name (e.g. after running `find` on bash) the path is specified using forward slashes.  I'd love to be able to just copy-paste that in Geany and have it open without manually replacing every `/` with `\`.

**Comment by elextr** [comment]
Version of Geany, what version of GTK?

AFAICT you are operating totally within the GTK open file dialog, it does the munging of typed input with open directory and Geany can only read the results.  So we can't control that behaviour.

**Comment by cousteaulecommandant** [comment]
Geany 2.0 | GTK+ v3.24.39 | GLib v2.78.0

I just tried with a different GTK program (gtkwave) and it doesn't support `/` either, so you're probably right.  Pity.

**Comment by b4n** [comment]
I guess #3861 will help with this?

**Comment by eht16** [comment]
I guess so as well.
@cousteaulecommandant with current GIT master (installers can be found on https://nightly.geany.org/mingw64/) and with the release, you can enable native Windows file open/save dialogs, maybe these offer better navigation aids.

Apart from that, I agree with @elextr that we probably cannot modify the GTK file chooser dialogs.

So closing, re-open if you disagree.
