### ISSUE TITLE
python has "pyi" and Geany do not know how to insert Comments

### ISSUE THREAD

**Issue by osergioabreu** [geany/geany#3873]
Python has different extension files. Apart from .py it has one with an "i" at the end: ".pyi" files.

 How to configure Geany to allow Format > Comment in types Geany do not recognize? How would I configure for a new filetype wheter to use // or # or " in comments ?

**Comment by eht16** [comment]
> If somebody wants to make a PR adding the `.pyi` extension it probably would be accepted.

Here we go #3976.
