### ISSUE TITLE
I have just solved the socket problem in my computer.

### ISSUE THREAD

**Issue by osergioabreu** [geany/geany#3880]
As the conflict was between my normal user and root (which **all linux users will have**)  I decided to take action:

1) Wrote a Perl script that finds the owner of the file passed in the argument
If is root, appends a **sudo** in front of the command
2) Replaced "geany %F" in usr/share/applications/geany.desktop to open my script "gia %F"  instead of geany, as the intelligence is in my script.

Problem Solved! Couldn't this be done by Geany?

**Comment by b4n** [comment]
Short answer is "no".

If this "solved" the issue you mentioned in #3871 it is probably just that you started Geany with sudo, and quit it cleanly.  It thus removed the problematic socket file, allowing subsequent non-sudo runs to work properly.  The issue you had was a leftover file *not owned by your user in your user's homedir*, and generalizing this behavior is just gonna widen the amount of files that might end up root-owned in your homedir.

The real solution would be to have a sudo configuration that doesn't lead to root writing files in your homedir. I believe Ubuntu has had this issue for basically forever, which I don't understand; but I guess they have their reasons.

Then, we can't do this for several reasons:
* `sudo` is likely to ask for a password, which it's not gonna get if run outside a terminal.
* `sudo` exists for a reason:
  * if you just want to always be root, just use the root account to start with. **:warning: I wouldn't recommend it though.**
  * on the contrary, if you want to modify a root-owned file from your sudo-enabled user, just prefix the command with `sudo` so you're explicit with yourself what you're doing.
* lastly, the Geany team does **not** endorse running Geany as root.  Of course you can do this, but consider it unsupported and dangerous.

---

A pretty interesting solution to editing files as root is gvfsd-admin: basically you can use the URI `admin:///path/to/file` and the system asks for permission to edit this file from a non-root app.  This works with e.g. GEdit and Pluma.  It doesn't in Geany (yet?) for technical reasons we might or might not want to change, but it possibly could if really editing root files with an IDE-like app seem useful enough to enough people.

**Comment by elextr** [comment]
@b4n IIUC using gvfs would add lots of other capability, eg access to networked files.  

There were a couple of attempts, #963 got a lot of comments, but in the end was not merged, and #1414 got only one comment.

Both now have conflicts so I guess "not planned" is a reasonable response.
