### ISSUE TITLE
Missing key binding for [Alt] + [Home]

### ISSUE THREAD

**Issue by nepa** [geany/geany#389]
In the key bindings dialog, there are options for:

Go to end of line: [End]
Go to end of line: [Alt] + [End]
Go to beginning of line: [Home]

But there is no option for:

Go to beginning of line: [Alt] + [Home]

I want to switch the "go to x of line" and "go to x of _visual_ line" options, but I can't, since one option is missing. Could you please fix that?

**Comment by vstepaniuk** [comment]
What about the Ctrl+Home? Can't find a "Go to Start of Document".

**Comment by elextr** [comment]
https://www.geany.org/manual/current/index.html#scintilla-keyboard-commands

**Comment by vstepaniuk** [comment]
> at least in the development version there is the four keys:
> 
>     * Go to Start of Line (`Home`)
> 
>     * Go to End of Line (`End`)
> 
>     * Go to Start of Display Line (`<Alt>Home`)
> 
>     * Go to End of Display Line (`<Alt>End`)
> 

So why there is no "Go to Start of Document" in the Keybindings settings?

**Comment by elextr** [comment]
> So why there is no "Go to Start of Document" in the Keybindings settings?

Because as the link above says, its built into Scintilla, the editing widget, its not Geany functionality so its not in the keybindings.
