### ISSUE TITLE
Inaccurate German translation for "go to end of line"

### ISSUE THREAD

**Issue by nepa** [geany/geany#390]
In the German translation of Geany, in the key bindings section, there is one term that is used for two options. Since the options are different, they should not be named equally.

The inaccurate translation is:
"Gehe zum Zeilenende"

It should be fixed this way:
Go to end of line = "Gehe zum Zeilenende"
Go to visual end of line = "Gehe zum visuellen Zeilenende" [NEW]

For the other way round, it would be:
Go to beginning of line = "Gehe zum Zeilenanfang"
Go to visual beginning of line = "Gehe zum visuellen Zeilenanfang" [NEW]

**Comment by elextr** [comment]
@frlan has the translation upgrade during 1.25 release fixed this?

**Comment by elextr** [comment]
@frlan should this still be open?

**Comment by nepa** [comment]
In Geany 1.31 the translation is still not consistent:

Gehe zum sichtbaren Zeilenbeginn
Gehe zum angezeigten Zeilenende

Instead of:

Gehe zum sichtbaren Zeilenbeginn
Gehe zum sichtbaren Zeilenende

So no, this issue is not resolved yet.

**Comment by frlan** [comment]
Just did not see it ;)

**Comment by frlan** [comment]
Should be fixed with deff041a
