### ISSUE TITLE
Can't find file while trying to run Julia script files

### ISSUE THREAD

**Issue by oOosys** [geany/geany#3908]
Linux Mint 21.2 Xfce, Geany 2.1 ( Yage )

Something strange is going on while trying to run Julia script files: 

1) the .jl extension is removed: so running an "x.jl" with `EX_00_CM=julia "%f"` in "filetypes.julia" results in: file x not found. 
2) if the script file name is x.jl.jl and there is a file x.jl present in the directory, but not marked as executable then there is another error message: 'Permission denied' . 

If the x.jl file is marked as executable and the script file name in Geany is x.jl.jl then the Julia script file "x.jl" will be executed and prints results to the console prompt. 
 
The filetypes.python file structure does not differ from filetypes.julia, but Python scripts run OK without being marked as executable and are found as they are. 

What could be the reason for this weird behavior and how to fix this issue, so that Julia scripts could be run using F5 in Geany?

**Comment by elextr** [comment]
You should always post version of Geany and your OS (and desktop if Linux).

If you only put the `EX_00_CM` in the config file it will be ignored, so its still using "./%e" as the command.  You need to put the name and working directory settings as well.  Maybe configure it on the GUI (Build->Set build commands) and copy the settings from your user config to the filetype config.

**Comment by oOosys** [comment]
The GUI-way solved the issue writing to the filetypes.julia: 
```
[build-menu]
## USE the Geany MENU: 
#						»Build	»Set Build Commands 
# to configure the	filetypes.julia	file
# %f will be replaced by the complete filename
# %e will be replaced by the filename without extension
# (use only one of it at one time)
EX_00_CM=julia %f
EX_00_LB=_Execute
EX_00_WD=
```
(The comments are changed manually by editing the text)

This solved the issue and now Julia scripts run as Python scripts do. Thanks for the very fast response :) which solved the issue.
