### ISSUE TITLE
filetypes.julia setting of indentation Tab width and usage of Tab

### ISSUE THREAD

**Issue by oOosys** [geany/geany#3914]
I have in my Geany 2.1 Preferences set Tab width to 8 and to usage of Tabs. In Lua, Shell and Python scripts Tabs are inserted on Tab-key. I have changed all on the system available filetypes.julia files to width=8 type=1, but nothing helps. On Tab in *.jl files I am getting four spaces as result of using the Tab key on the keyboard. 

Any idea what might be the reason and how to achieve insertion of actual Tabs in Julia script files?

**Comment by elextr** [comment]
WFM, don't forget there are project settings which can override default, although document settings should override those, but you have to set them manually for each document.

**Comment by oOosys** [comment]
I am not using Projects at all in Geany, so I was not aware that this might have any effect here. 
Now just out of curiosity I have clicked in the [Project] Menu the item "Apply default indentation" and ... Tabs now are inserted in the loaded Julia script file like in all other files. 
OK ... I don't need to understand this, do I? The issue seems to be solved by this click, so I am happy also without understanding why it occurred in first place and why now does it work as expected now after such click ...

**Comment by elextr** [comment]
> OK ... I don't need to understand this, do I?

Ditto, Geany indentation handling has "evolved" over time, and like all evolved organisms it is not the optimal implementation that might be arrived at by design from scratch, and so it has dark and dingy corner cases. :disappointed:

**Comment by elextr** [comment]
Oh, just one other comment, changing settings does _not_ change the contents of the files, you have to explicitly instruct Geany to change existing contents, which you did with "Apply default indentation".

**Comment by oOosys** [comment]
Usually indentation and Tab-handling are two independent things as Tabs are used not only for indentation but anywhere ...
OK ... I am using same setting ( 8 chars wide Tab, no space insertion on Tab) everywhere, so I don't probably need to worry about "dark corner cases". 
I am just naively assuming now that Julia scripts were a "new" kind of files I have started to use in Geany so after setting the Tabs to default once it should now stay that way and work as in all other file types ...
