### ISSUE TITLE
[FR] Portable Windows builds

### ISSUE THREAD

**Issue by sdasda7777** [geany/geany#3915]
Hi, would it be possible to provide portable builds for Windows? In the releases there seems to be only an installer, which may not be desirable.

**Comment by iahung2** [comment]
Already exists, but simply not listed on the download page:

https://portableapps.com/apps/development/geany_portable

**Comment by elextr** [comment]
Yes it is, under third party packages because it is not made by the Geany project.

**Comment by eht16** [comment]
Basically you don't need a third party package.
In https://github.com/geany/www.geany.org/pull/52 I described how to get Geany running portable with a simple Batch script.

@sdasda7777 if you like, feel free to try it and report back whether it works.

**Comment by pa-0** [comment]
I notice the batch script you include sets the environment variable for `%XDG_CONFIG_HOME%` in addition to running geany.exe with`--config=./config/geany`.  Are both of these steps necessary?  

I know of (and use) at least a handful of relatively popular Windows programs that respect the XDG specs/variables (yes, on Windows too), so I can see this causing issues for myself and others.  Please correct me if I am wrong about this.

**Comment by elextr** [comment]
How does respecting XDG_CONFIG_HOME guarantee to point to the portable directory tree, eg a USB that was plugged in with Geany?

This is intended to be portable not installed, and install will respect XDG_CONFIG_HOME IIUC.

**Comment by RoyiAvital** [comment]
It would be great if the `exe` just checks if `.config` resides in the same folder as the executable and if it does, use it.
Can it be done?
