### ISSUE TITLE
Can't disable option to strip spaces

### ISSUE THREAD

**Issue by M-And-M-s** [geany/geany#3942]
In Edit -> Preferences -> Files -> Saving files there is an option named "Strip trailing spaces and tabs". Even if I disable it, Geany still strips spaces at the end of every line everytime a I save a file. I am using Geany 2.0 for Windows but Geany 1.36 for Windows was exactly the same.

**Comment by elextr** [comment]
Both 1.36 and 2.0 work for me on Linux Mint.

**Comment by M-And-M-s** [comment]
I am really sorry, looking at the source code I found that I had misunderstood the settings.

I was inside a project and I didn't know that the "Strip trailing spaces and tabs" option for projects must be set in Project -> Properties.
I thought the the Edit -> Preferences -> Files settings was global and always valid, but the Project -> Properties settings overwrites the others.

So, no bugs at all. I hope this can help someone else.
