### ISSUE TITLE
How to find and replace new lines?

### ISSUE THREAD

**Issue by chatchoi** [geany/geany#3959]
### Discussed in https://github.com/geany/geany/discussions/3955

<div type='discussions-op-text'>

<sup>Originally posted by **chatchoi** September 19, 2024</sup>
I typed `\n`, tried both regular expressions with multi-line matching and escape sequences. None of them worked.

I'm using Geany on Windows via PortableApps.

p/s: The file itself is UTF16-LE (with BOM), with Windows line endings (CRLF).</div>

Note: making it an issue, because it seems no one cares about my thread in Discussions.

**Comment by elextr** [comment]
> Note: making it an issue, because it seems no one cares about my thread in Discussions.

All Geany contributors are volunteers, if they don't have time at some point there may be a delay.

If the file is CRLF line ends then search for that not just the LF.

**Comment by chatchoi** [comment]
> If the file is CRLF line ends then search for that not just the LF.

OK. Search for `\r\n` instead of just `\n`.
