### ISSUE TITLE
Add support for the Objeck language

### ISSUE THREAD

**Issue by chatchoi** [geany/geany#3963]
There is a custom file type syntax highlighter for Objeck here:

https://github.com/objeck/objeck-lang/tree/master/docs/syntax/geany

But there is no official lexilla lexer yet. There is an open FR on lexilla's repo:

https://github.com/ScintillaOrg/lexilla/issues/121

The OP summed the problem with the custom file type syntax highlighter pretty well. But he is wrong about the similarity between Objeck and C/C++. They are both curly braces languages but they are not really similar. I think Objeck needs its own lexer.

I don't know which languages most resemble Objeck, but using the C ctags parser for Objeck seems to not work well, too.

**Comment by elextr** [comment]
Well, "somebody" needs to create the Lexilla highlighter, and/or the ctags parser.  Lexilla and uctags are different projects to Geany.  Geany just leverages their products, it does not maintain them.  You would probably do better to raise the requests on Lexilla and uctags respectively they have experts on those.

**Comment by chatchoi** [comment]
@techee Can you help with this? You are the Lexilla expert of this project.

**Comment by techee** [comment]
> @techee Can you help with this? You are the Lexilla expert of this project.

I'm afraid I'm not sufficiently motivated to write the lexer myself, sorry. I did this (also thanks to Notepad4 lexer's existence) for languages that appear at the top places in

https://madnight.github.io/githut/#/pull_requests/2024/1

(plus Zig which isn't there yet but which is quite big when you have a look at its pages and various projects written in it) and where I felt that Geany lags behind other editors in terms of "new" language support.

When you look at https://github.com/objeck/objeck-lang, this is just a one man's project (which means it will cease to exist when this single guy decides he isn't interested any more) and it has yet to prove it's "better" than other existing languages. So for me it's a too niche language to spend time on it.
