### ISSUE TITLE
FR: setup Nightly build

### ISSUE THREAD

**Issue by Curculigo** [geany/geany#3971]
Like this: https://github.com/AdeptLanguage/Adept/releases/tag/Nightly

Or this: https://github.com/pragtical/pragtical/releases/tag/rolling

I'm very excited with the upcoming Geany 2.1 but I can't compile the latest code from source. I have only 4GB of RAM and running old legacy Windows. If you can setup Nightly build I can help you test the latest code. Please consider. Thank you.

**Comment by elextr** [comment]
https://geany.org/download/nightly-builds/

**Comment by mh466lfa** [comment]
Where is Geany Plugins? The page above doesn't have Geany Plugins.

**Comment by elextr** [comment]
The lower 4 entries in the table are clearly labelled "plugins".

**Comment by mh466lfa** [comment]
I'm sorry :smile:
