### ISSUE TITLE
Add to the shortcut "Toggle Sidebar" a command like "IF editor is disabled THEN enable editor" to avoid an empty tab

### ISSUE THREAD

**Issue by ralf3u** [geany/geany#3979]
**Foreword**
Thanks to the plugin `Preview` (https://github.com/xiota/geany-preview/) one can see live in a tab of the sidebar the result of an HTML-document. And thanks to the plugin `Lua Scripts` there is at the moment the possibility to press a shortcut to toggle between only-editor-view (the sidebar is disabled) and only-sidebar-view (the editor is disabled).

**Issue**
If the only-sidebar-view (the editor is disabled) is visible, and if I press the shortcut `Toggle Sidebar`, then there is a completely empty tab because editor and sidebar are both disabled. A completely empty tab is something that should not happen in Geany.

**Possible solution**
I don't know how to program software, so I write it like this: In the shortcut "Toggle Sidebar" there should be a command with something like "IF editor is disabled THEN enable editor" to avoid a completely empty tab.

**System**
Lubuntu 24.04
Geany 2.0

**Comment by b4n** [comment]
IMO that sounds like something the aforementioned plugin should try and deal with. Stock Geany will never hide the editor area, so it seems hardly sensible it would have to deal with this edge case.
