### ISSUE TITLE
Wrong font in search box?

### ISSUE THREAD

**Issue by ppw0** [geany/geany#3981]
Hi, can someone help me understand why this monospace font is used in the "Find" dialog?

![image](https://github.com/user-attachments/assets/3f14dce9-9c7a-4463-bf53-066009c4ba2f)

Nowhere in my settings is this font set, not in Geany, not in GNOME, not in ~/.config/gtk-3.0/gtk.css. Is it hard-coded?

**Comment by b4n** [comment]
I think it's in a specific stylesheet somewhere under `/usr/share/geany/` (would have to go to the computer to give exact details, but I think that's documented in the manual). You can override that in your specific stylesheet.

**Comment by ppw0** [comment]
Thank you. The "culprit" lies in ~/.config/geany/geany.css:

```
/* use monospaced font in search entries for easier reading of regexp (#1907117) */
#GeanyDialogSearch GtkEntry /* GTK < 3.20 */,
#GeanyDialogSearch entry /* GTK >= 3.20 */ {
    font-family: monospace; 
}
```

Closing this issue. Thanks again.
