### ISSUE TITLE
[FeatureRequest] Add filename/path textbox to 'open file' dialog

### ISSUE THREAD

**Issue by seniordevel** [geany/geany#3990]
In the 'Open File' dialog box, is there a way to specify the target file/folder path via text-box instead of using the GUI?
eg. /somefolder/../../and_so_on/../somefile
Ideally, I would be able to paste my much longer paths in an input box, and that would be the file that the dialogue opens.

If GTK still does not allow, could you add a button (or at least  a file menu item) with this functionality, e.g. 'Open file from clipboard'?

I always work with very long file paths, but those are available in my clipboard. It is a hassle to use a GUI on the way to the target file step by step. I would like to do this instantly, not needing several minutes.

Thanks for your attention.

**Comment by ralf3u** [comment]
>In the 'Open File' dialog box, is there a way to specify the target file/folder path via text-box instead of using the GUI?

>I always work with very long file paths, but those are available in my clipboard. It is a hassle to use a GUI on the way to the target file step by step. I would like to do this instantly, not needing several minutes.

When the dialog box appears, just press Ctrl+L (L stands for location) (result: an empty field will appear) and then press Ctrl+V to paste the path.

**Comment by seniordevel** [comment]
@ralf3u 
Thank you very much, counter-intuitively, but it works for me.
