### ISSUE TITLE
Feature request: make Symbols index arrow-navigable

### ISSUE THREAD

**Issue by riveravaldez** [geany/geany#4003]
Hi, sorry to bother, just an idea (hope this is the proper place to mention it, if not please let me know).

With markdown files the Symbols tab/panel renders an on-the-fly index following the structure of the text (# header 1, ## header 2, etc.), which is lovely useful but can only be navigated through mouse-clicking.

Any chance to make it also arrow-navigable, so, right-arrow opens the nested sub-headers (and so on, recursively) and left-arrow closes it?

Thanks a lot in advance, kind regards!

**Comment by elextr** [comment]
The symbols pane is up/down arrow navigable, and enter to move the editor to the selected heading.  The up/down arrows move across visible rows.  Expand/unexpand is provided by Shift+left/right arrow.  IIUC all of these are GTK default bindings and Geany has no reason to make them modifyable.

There is a bug in Geany 2.0 which has been fixed that makes the (by default unbound) action to switch to the symbols sidebar now work, will be in next release.

So everything is keyboard usable, switch to Symbols, up/down arrow, shift+left/right arrow to expand/unexpand parts, enter to switch to the editor at current heading.
