### ISSUE TITLE
Toolbar icons still small with large icon setting

### ISSUE THREAD

**Issue by advice2020** [geany/geany#4006]
Linux - Debian Based
GTK based DE

When using the popular icon set Papirus the toolbar icons appear rather small even when set to the highest setting.
Not sure if this is a graphical bug or if this is just the highest icon size made available?
If not a bug if possible can someone move this to the “Ideas” category so it can be viewed as a feature request to increase the size of the toolbar icons.

Thank You

**Comment by elextr** [comment]
The toolbar icons can be set to the size defined by the GTK theme, which may have detailed size control maybe, or to "very small", "small", and "large" but they will only do anything if the icon theme has those sizes and it has become common these days to provide less sizes.

Try and see if you can define GTK CSS to change the icons sizes so long as the icon theme provides a SVG icon that can be resized.

None of these are within Geany control, so it is not a bug in Geany, nor a feature that will be part of Geany.

**Comment by advice2020** [comment]
@elextr 
Ahh okay thank you.
I am aware a little bit about how CSS is used to modify GTK item, this would have been my next approach if this did not work out.  Just thought it was odd that the settings offered ability to change the sizes but nothing was occurring.
I will first temporarily just try some other themes to see if any contain more sizes just to get an idea but then I will see what gtk.css file can change.
Thank You again for verifying this, I will close this.
