### ISSUE TITLE
More possibilities to use shortcuts

### ISSUE THREAD

**Issue by MatthiasGottfried** [geany/geany#4030]
Currently the third section on the Build menu (Execute commands) allows only one shortcut for the first entry. It would be great, if shortcuts are also allowed for more than the first entry.
Use case:
I am programming in python and I often like to execute a python script inside an external terminal. Executing a python script in an external terminal will show all print statements immediately, and will allow me to work inside the python interpreter once the main program is finished (and accessing all by the main program loaded or created modules and libraries).
While developing the first entry on the "Execute commands" section inside the build menu is associated with executing main inside an external terminal.
For testing purposes I have associated the second line for running the current (test) script inside a terminal - but this works only through the menu and not with a shortcut.
The other two sections ("Independent commands" and "Python commands" (in my case)) do have more shortcuts - but cannot be used to start a script in an external terminal.
Using entries of the "Independent commands" section will execute the script - but without printing "print" statements immediately - they got all printed inside the "compiler" window after the main script stopped (and not during the runtime of the script) and will not give me a running python interpreter after the main script stopped.

Therefore - please allow more shortcuts as described 
Thanks a lot.

**Comment by elextr** [comment]
Each of the types of commands, filetype dependent and results analysised , filetype independent and results analysised, and execute execute commands that are run on a terminal so whatever output the execution produces is kept until the user has happily read it.

Each of those sections can have the number of commands for the menu to be set by the user in `Edit->Preferences->Various->build.XXXXX`.  Setting it less than the default numbers will be ignored, hence the default of zeros.

Unfortunately the keybinding dialog is a hard coded dialog, there is no way of handling variations in numbers of commands and so cannot set keybindings for those not hard coded.  This is known for a long time but nobody has had the time and interest to modify the keybinding dialog to support a varying number for build commands.  Any PR contributes is welcome.

This is essentially a dialog of #705 and possibly other issues and older Sourceforge issues.
