### ISSUE TITLE
Title Bar Dark Mode on Windows 11

### ISSUE THREAD

**Issue by GabrielFrigo4** [geany/geany#4036]
I'm using the Prof-Gnome theme to have the dark mode, but the Title Bar is not affected... How do you get me to solve this? Via docido C/C++ it's easy, just use [this](https://learn.microsoft.com/en-us/windows/apps/desktop/modernize/ui/apply-windows-themes)

However I've seen [screenshots](https://github.com/geany/geany/issues/3781) with Geany with the Dark Mode title bar on Windows, so I don't think it's necessary to modify the code

![Captura de tela 2024-11-07 235923](https://github.com/user-attachments/assets/4078f04f-91d3-4cfc-ad3e-8afcb3aa2fa1)

**Comment by b4n** [comment]
You can potentially try setting [`gtk-application-prefer-dark-theme=true`](https://docs.gtk.org/gtk3/property.Settings.gtk-application-prefer-dark-theme.html) in [GTK's settings](https://docs.gtk.org/gtk3/class.Settings.html), see e.g. [our unrelated documentation talking about where this file is](https://www.geany.org/manual/current/index.html#printing-support), or get inspiration from [the web](https://wiki.archlinux.org/title/GTK#Dark_theme_variant).
I don't use neither dark theme nor Windows so I'm not sure if that helps, but it might.

**Comment by GabrielFrigo4** [comment]
> You can potentially try setting [`gtk-application-prefer-dark-theme=true`](https://docs.gtk.org/gtk3/property.Settings.gtk-application-prefer-dark-theme.html) in [GTK's settings](https://docs.gtk.org/gtk3/class.Settings.html), see e.g. [our unrelated documentation talking about where this file is](https://www.geany.org/manual/current/index.html#printing-support), or get inspiration from [the web](https://wiki.archlinux.org/title/GTK#Dark_theme_variant). I don't use neither dark theme nor Windows so I'm not sure if that helps, but it might.

This sounds promising, but where do I put the `gtk-application-prefer-dark-theme=true`?

**Comment by b4n** [comment]
Maybe one of my links help, or maybe https://stackoverflow.com/a/39041558?  Again, I'm not well versed in Windows specifics, but it should be possible to figure it out

**Comment by eht16** [comment]
> > You can potentially try setting [`gtk-application-prefer-dark-theme=true`](https://docs.gtk.org/gtk3/property.Settings.gtk-application-prefer-dark-theme.html) in [GTK's settings](https://docs.gtk.org/gtk3/class.Settings.html), see e.g. [our unrelated documentation talking about where this file is](https://www.geany.org/manual/current/index.html#printing-support), or get inspiration from [the web](https://wiki.archlinux.org/title/GTK#Dark_theme_variant). I don't use neither dark theme nor Windows so I'm not sure if that helps, but it might.
> 
> This sounds promising, but where do I put the `gtk-application-prefer-dark-theme=true`?

This should go into `C:\Users\<YOUR-USERNAME>\AppData\Local\gtk-3.0\settings.ini`. The file and the directory may not yet exist, so just create them.

However, at least on my old Windows 7 the title bar is styled by the OS not the GTK theme. Maybe this changed in newer Windows versions.

**Comment by GabrielFrigo4** [comment]
So, I'm almost sure I saw code to fix this. But the way it is, only in the Windows settings to fix it.
In this case I followed these steps and left it the way I like it
[Enable Dark Title Bars with Custom Accent Color in Windows 10](https://winaero.com/enable-dark-title-bars-custom-accent-color-windows-10/)
