### ISSUE TITLE
Highlight yield keyword in java

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#4051]
**Geany** does not highlight the **yield** keyword in the following legitimate Java:

![GeanyYield](https://github.com/user-attachments/assets/b9801e93-f24f-4c66-84ac-9af5b3a4be4d)

Please could **Geany** highlight the **yield** keyword in Java code?
 
![python_geany](https://github.com/user-attachments/assets/7f60f610-4c3b-49ed-8dbd-8369c13340e9)

**Comment by eht16** [comment]
Current Geany master already has this keyword included, see https://github.com/geany/geany/pull/4014.

You can add it yourself without updating Geany by `Tools -> Configuration Files -> Filetype Configuration -> Programming Languages -> filetypes.java` and add `yield` to the keyword list. Or copy the whole list from the PR above.
