### ISSUE TITLE
Changes to the comment section is [settings] are not applied on a reload config.

### ISSUE THREAD

**Issue by kbmaniac** [geany/geany#4068]
Geany 2.0 on Linux Mint 22

On editing Tools>Configuration Files>Filetype Configuration>Scripting Languages>Filetypes.forth
And reloading config ...

No changes to the comments section is [settings] are applied. Changes to the [keywords] section are applied.

There appears to be a bug.

**Comment by techee** [comment]
Using the latest version from master but e.g. setting `comment_single=#` for forth seems to work. What exactly are you doing?

**Comment by kbmaniac** [comment]
Hello and thank you for your message,

In an ideal world I would need both ( ) and (( )) to be highlighted as
multi line comments in forth.

The documentation is not clear if it is possible to have 2 x multi
line comment "words" so I was trying to get Geany to just recognise (( ))
... but no matter what I do it will not colourise (( )) as a multi line
comment.

The code is always colourised the same with ( ) being colourised correctly
but (( )) not being colourised even with the modified
filetypes.forth telling Geany to colourise (( )).

Interestingly if I add a keyword a little further up filetypes.forth and
reload, that keyword is colourized perfectly so the modified config is
being read.

Kind Regards

Dave Selby

**Comment by kbmaniac** [comment]
Apologies...

Just realised I should have sent you a screenshot of the comments over
multi lines 🤣  but the same applies as in the screenshot I did send.

(()) Is a useful debug feature which allows you to comment out multiple
words including words with ( ) stack comments.


Kind Regards

Dave Selby (Engineer 784)

**Comment by techee** [comment]
OK, these settings don't control styling but what Edit->Command->Comment... uses as the comment character.

If the styling is incorrect, the bug should be reported to https://github.com/ScintillaOrg/lexilla which Geany uses.

**Comment by kbmaniac** [comment]
Ah OK, thank you

I will have a look at Scintilla

Kind Regards

Dave Selby
