### ISSUE TITLE
bug: Powershell heredoc breaks function list on left side panel.

### ISSUE THREAD

**Issue by ivanmara555** [geany/geany#4089]
Hello. I wrote some powershell code in geany 2.0:
```powershell
function a
{
    $i = 1
    Write-Host $i
}
function b
{
    Write-Host b
}
a
b
pause
```
And on left side bar see two function:
![1](https://github.com/user-attachments/assets/550b1f36-63c3-45ed-87cc-44d2ca094918)

Suddenly i add some heredoc to function a:
```powershell
function a
{
    $i = 1
    $heredoc =
@"
""" $i
"@
    Write-Host $heredoc
}
function b
{
    Write-Host b
}
a
b
pause
```
Now on left side bar only one function a: 
![2](https://github.com/user-attachments/assets/06992f90-54ce-4a72-9c2c-757efe0c4683)

Adding heredoc code breaks function list on left side panel !!!

I cat use single quote delimiter `@'` and function list will show correctly. But some times i need use double quoted `@"` to use a subexpression as in example above.

some detail here: [The PowerShell Here-String – Preserve text formatting](https://4sysops.com/archives/the-powershell-here-string-preserve-text-formatting/)

**Comment by techee** [comment]
I'd suggest that you report the problem here: https://github.com/universal-ctags/ctags. The parser comes from there, we just use these parsers in Geany. From a brief look at the parser, handling of `@" "@` is missing there, probably not too hard to implement.
