### ISSUE TITLE
Prevent damaged files due to 100% disk usage

### ISSUE THREAD

**Issue by etkaar** [geany/geany#4092]
Under rare circumstances it can happen that disk usage reaches 100%, e.g. on small virtual servers where a log file gets longer and longer due to an error. Editing a file can then lead to a damaged (truncated) file even if it is the same size after change. This is of course not Geanys fault and Geany will report that, but then the file on disk is already truncated. 

Is it possible for Geany to prevent this?

**Comment by eht16** [comment]
Yes, there is an extensive wiki page describing various configuration sets to handle such cases: [All you never wanted to know about file saving](https://wiki.geany.org/config/all_you_never_wanted_to_know_about_file_saving)
