### ISSUE TITLE
The Help->Donate page is in German

### ISSUE THREAD

**Issue by techee** [geany/geany#410]
I believe this is a good way to discourage anyone outside Germany to send some money :-).

The link goes somewhere to sourceforge which performs the redirect to the German paypal page (using US locale here so it isn't a locale-specific page). There are probably several solutions:

1. Use the same link as on Geany homepage (the Paypal link, the sourceforge one links to the German version - by the way, is there a reason to have both?).
2. Update the link on sourceforge to the English version (if it's possible).
3. Perform the redirect through geany.org/some_donation_link

@eht16 You are probably the only one who can make this change.

**Comment by eht16** [comment]
I don't see a problem here, I can read the donate page very well.

j/k :).

More seriously, I fix the language on the donate page by adding a parameter '&lc=US'. This is not really documented by Paypal or I just couldn't find the proper documentation for this but there is a document "lc" parameter in another context so I just tested it by trial&error and it worked.
Before I ensured all language settings in the account preferences were already set to English.

So, 2. has been done.

But 1. might be the better solution: why having a redirect performed by SF just to get to the Paypal page. And so, we probably should combine 1. and 3.:
we add a redirect on the webserver on geany.org to the Paypal page and use this redirect in the Geany code. This way, we don't have to hardcode the Paypal URL in the Geany code. The Paypal URL might get outdated and/or need to be changed for other reasons. With a rediect on geany.org we have better control over this, also for older releases of Geany.

Objections? @codebrainz @b4n @frlan @ntrel

**Comment by eht16** [comment]
JFTR: Oh, and I'm not the only who could fix that. Any SF project admin is able to do this and the Paypal account can also be accessed by the other team members.

**Comment by b4n** [comment]
fine with me, something on our server sounds best indeed :)

**Comment by techee** [comment]
Great, prepare for a huge amount of donations now (I've just donated $20 to prove you that you get more money with an English page :-)

**Comment by b4n** [comment]
@techee wow, looks like it did work indeed! thanks a bunch ;)

**Comment by eht16** [comment]
@techee you crazy guy :).
Thanks a lot, though absolutely not necessary. You are doing already lots of cool code changes, bug reports and fixes. Awesome.

Back to topic:
* added a redirect for the donate page: http://www.geany.org/service/donate/
* changed the URL in Geany in d5cca3792269160d19530b3af1c63c880adef2d4.
* changed the sidebar on the website: removed SF donate button, changed the URL on the Paypal button to use the same as in Geany

For reference, the redirect on server-side is done in /etc/lighttpd/conf-enabled/50-www.geany.org.conf.

**Comment by codebrainz** [comment]
On 15-01-31 05:46 AM, Enrico Tröger wrote:
> [snip]
> Objections? @codebrainz @b4n @frlan @ntrel
>

Sounds like a good idea to me.

**Comment by codebrainz** [comment]
On 15-01-31 06:56 AM, Jiří Techet wrote:
> Great, prepare for a huge amount of donations now (I've just donated $20 to prove you that you get more money with an English page :-)
>

Awesome, donating code and cash!

Finally a donation shown in a currency that I know the value of! :)
