### ISSUE TITLE
Cannot Execute build command

### ISSUE THREAD

**Issue by don-mpg** [geany/geany#4156]
Cannot execute build command "xterm -e "/bin/sh /tmp/geany_run_script_0ALAZ2.sh"": No such file or directory. Check the Terminal setting in Preferences

Linux Q4OS Trinity

**Comment by don-mpg** [comment]
Thank you for responding.

New error:

Cannot execute build command "x-terminal-emulator -e "/bin/sh /tmp/geany_run_script_DR97Z2.sh"": No such file or directory. Check the Terminal setting in Preferences

**Comment by techee** [comment]
Well, it's pretty much the same error. Apparently `x-terminal-emulator` isn't available on your distribution either. You have to figure out what terminal emulator your distribution uses and set the command accordingly.
