### ISSUE TITLE
Projects -> Recent Projects the list are not selectable

### ISSUE THREAD

**Issue by chadchoi** [geany/geany#4158]
I can see the items in the list, but I can't select any of them.

p/s: Geany Nightly on Windows.

**Comment by techee** [comment]
Works for me:

<img width="631" alt="Screenshot 2024-12-19 at 15 07 19" src="https://github.com/user-attachments/assets/96f10eb7-6ca7-4cde-bde4-592e8b6c4bae" />

The currently opened project is greyed out so you don't re-open it by accident but selecting the other project works and it gets opened.

**Comment by chadchoi** [comment]
I don't notice Projects -> Close button is available, so this means the project is already opened. Geany will not close the project when I close it, so on the next start of Geany the project is still open.

**Comment by techee** [comment]
This is weird, project closing works for me.

**Comment by chadchoi** [comment]
> This is weird, project closing works for me.

It also works for me. I said I don't notice that the Close button is available (that means there is an open project). This is my mistake.
