### ISSUE TITLE
"Bugged" symbol scanning for Pascal

### ISSUE THREAD

**Issue by lebao3105** [geany/geany#4159]
* Geany version: 2.0-2 "Pryce", built around 2024-11-01
* OS: Debian Sid

![image](https://github.com/user-attachments/assets/f9a0b678-d4cc-4ada-8f59-075e924e27d9)

Looking at the screenshot:

* Duplicated `(TFPSH.)WriteHelp`: the one with `TFPSH.` prefix (as it's a class function) points to the function implementation in the same file. One without the prefix points to the declaration as shown in the screenshot (inside the class's `private` section)
* We don't need to worry about `TFPSH.ProcessLine`, it has 2 overloads.
* But `that` symbol, which points to line 24. And line 24 is a comment line, which means the scanner should just ignore the entire line. This does not happen in C++ code.

**Comment by techee** [comment]
If I remember correctly, the Pascal parser is very basic (compared to e.g. the C++ parser). I suggest that you report the problem to the upstream project https://github.com/universal-ctags/ctags from which we take the parsers.

**Comment by lebao3105** [comment]
Tried Geany's latest commit which probably includes a newer Ctag. "that" is not recognized as a function anymore.

**Comment by lebao3105** [comment]
The file's language is Objective Pascal, so that's why no Classes node found in Symbols tree. Closing this now
