### ISSUE TITLE
Geany 2.0 on osx (Mac mini m4) ui interface error!

### ISSUE THREAD

**Issue by at1323** [geany/geany#4161]
macOS Sequoia  version: 15.2
![image](https://github.com/user-attachments/assets/7822f949-f243-4de6-8789-2aca4fc843d6)

UI interface is different with win11 version, and many functions can't use.

**Comment by eht16** [comment]
Could you go into more detail what exactly is the error?
What functions are you missing?

**Comment by at1323** [comment]
I am a new user, I don't know the difference!
But it seems not the same as win11 version, right?

**Comment by eht16** [comment]
Well, the screenshot above looks like Geany.
I don't know what you have seen as "win11 version" which you are referring to. I'd suggested either post a screenshot from the Windows version you use or give otherwise more details about what exactly is your problem.

How did you install Geany on Windows and where did you get the installer from? Same for the macOS version.

**Comment by at1323** [comment]
download from GitHub release

**Comment by at1323** [comment]
![image](https://github.com/user-attachments/assets/5d568f0e-e7a8-4b33-a571-5dc4048cc906)

**Comment by eht16** [comment]
> can not find there splits window, But this feature is different from Windows 11.

"Split window" is a plugin which needs to be activated in the plugin manager (in the menu Tools->Plugin Manager).

I'm not sure what the screenshot is showing and how it could help to better identify the problem :(.

**Comment by at1323** [comment]
In the Windows version, you can find it under Menu -> Tools -> Split, but I can't find it in Geany on macOS, windows version don't need install plugin. 
I'll look into how to install plugins in Geany on macOS.

**Comment by techee** [comment]
> I'll look into how to install plugins in Geany on macOS.

The plugin is part of the binary so no need to install anything - just activate it under Tools->Plugin Manager.

I believe there are no limitations compared to the Windows version - in fact, there are some extras like the terminal.
