### ISSUE TITLE
If last line contains text then a new blank line gets added when saved

### ISSUE THREAD

**Issue by advice2020** [geany/geany#4162]
I imagine this is intentional, but just in case it is not.
I noticed that if you have a document that contains text in the last line number shown, when you go to save that document a new blank line automatically gets added to that document.
Does anyone know if this intentional? or something that needs to be corrected

Thank You

**Comment by techee** [comment]
`Edit->Preferences->Files->Ensure new line at file end`

**Comment by advice2020** [comment]
Ahh, thank you for mentioning this
