### ISSUE TITLE
Where to find the Geany `Default` color scheme?

### ISSUE THREAD

**Issue by chadchoi** [geany/geany#4169]
It's not listed there:

https://www.geany.org/download/themes/

I think it's a good light theme and I want to create my own light theme based on it.

Update: `Alternate` color scheme is not listed, too.

**Comment by techee** [comment]
It's part of the filetypes.common file:

https://github.com/geany/geany/blob/2e8456a00fffc00a128a184c4b5a966848a0b4d0/data/filedefs/filetypes.common#L105

The Alt theme is here:

https://github.com/geany/geany/tree/master/data/colorschemes
