### ISSUE TITLE
Syntax highlighting: transpose operator (Matlab/Octave)

### ISSUE THREAD

**Issue by tmlmt** [geany/geany#427]
Hi,

There is an issue with Matlab/Octave (.m) files, in which the single quote is also used as the transpose operator. Is there a way to take that into account for syntax highlighting ?
For the moment, geany believes that the single quote is the beginning of a string and colors the next characters until it meets a new single quote ...

**Comment by johannes-lange** [comment]
Hi,
I only get that behaviour if the quote is preceded by a space. I.e.,  `v'` works fine, but `v '` behaves like you described. Is this the case for you, too?

**Comment by tmlmt** [comment]
Hmm, yes that's a good point, but it also behaves like this for cell arrays, for instance as in the screenshot attached
![screenshot](https://cloud.githubusercontent.com/assets/10244927/6334318/1db56640-bb94-11e4-973c-9b5ee7467939.png)

**Comment by johannes-lange** [comment]
I never noticed that. The right place to look for the "culprit" should be the [scintilla lexer](https://github.com/johannes-lange/geany/blob/master/scintilla/lexers/LexMatlab.cxx).
A quick check on what emacs does: `vector{i}'` is handled correctly, but the space causes the same problems. So at least one case can obiously be solved somehow ;-)

**Comment by elextr** [comment]
Yes the lexer is the place to look.

Note that Scintilla is a separate project at www.scintilla.org and patches
should be submitted there.

Cheers
Lex

**Comment by tmlmt** [comment]
Thanks guys for pointing that out! Didn't know about scintilla :p 
After doing some research on the links you suggested, I found out that : 
- A ticket and patch for that very bug was submitted on submitted in August 2, 2014 (http://sourceforge.net/p/scintilla/bugs/1629/) and quickly committed (http://sourceforge.net/u/prantl/scintilla/ci/506351b2344d4e8a57d22eca715a9db852d927cd/)
- That patch is included in geany's current Scintilla version (see line 224 at https://github.com/geany/geany/blob/master/scintilla/lexers/LexMatlab.cxx) thanks to b4n updating Scintilla to 3.5.0 pre-release on August 20. Unfortunately that's later than geany's latest release in April of that year.
- I personally installed geany with a simple apt-get install on my Trusty 14.04 and am thus using version 1.23.1 (see http://packages.ubuntu.com/search?keywords=geany&searchon=names)  ! So now I guess I have to jump into git cloning and compiling geany !
Thanks again for your help.

**Comment by elextr** [comment]
To avoid git nightly builds are available (here)[http://nightly.geany.org/].  The debian ones should work on ubuntu.

**Comment by tmlmt** [comment]
Thanks a lot. It worked very well.
