### ISSUE TITLE
Make the VTE shell working directory discoverable on OS X (and BSD)

### ISSUE THREAD

**Issue by techee** [geany/geany#432]
At the moment in vte_get_working_directory() we check the working directory using /proc which might not be available on BSD-based systems. Find a way to perform this check on these systems.

(Ticket for myself once I have time to investigate.)

**Comment by elextr** [comment]
@techee ping :)

**Comment by techee** [comment]
Well, the best thing I could come up with is using lsof (https://github.com/geany/geany/pull/436) but not sure if we should add the code to Geany.

**Comment by elextr** [comment]
Ok, so its still active, and now we have a reference to the ongoing PR :)

**Comment by techee** [comment]
Probably not worth it, closing.
