### ISSUE TITLE
Use system icons for the toolbar

### ISSUE THREAD

**Issue by PerfectCarl** [geany/geany#438]
Could you add an option to use system symbolic icons for the toolbar instead of the built-in that can feel alien depending on the theme installed in your system ?

**Comment by b4n** [comment]
Which icons are you talking about?  We use the theme's ones but for "save all", "close all" and "build", that don't have standard icons.  However, we do so in a way that allows a theme to provide its own icons for these, namely "geany-save-all", "geany-close-all" and "geany-build".

If you know of standard icon names with that semantic, I'm sure we'd be happy to use them.

**Comment by PerfectCarl** [comment]
Those were those icons for which there is no system images. 
Thanks
