### ISSUE TITLE
Check docs for spawn API

### ISSUE THREAD

**Issue by elextr** [geany/geany#440]
Some of the parameters for the spawn API functions are not documented as unused.

This si a reminder issue until it gets done :)

**Comment by zhekov** [comment]
Unless I'm forgetting something, all arguments in all spawn_*() functions are used.

Perhaps you mean utils_spawn()? These were wrappers to g_spawn/win32_spawn with some unused parameters, and are now wrappers for spawn_*() with even more unused parameters. We should deprecate them at some point...

**Comment by elextr** [comment]
Hmmm, not sure what I meant. Forget it then :)
