### ISSUE TITLE
GTK3 version visibility

### ISSUE THREAD

**Issue by elextr** [geany/geany#452]
Since its now fairly stable according to @b4n maybe we should look at documentation for packagers, nightlies and so on to raise the profile.

**Comment by codebrainz** [comment]
See:

https://github.com/codebrainz/geany/commit/8727fec89da53ff6dc539efb3afe8e65e51d596f

**Comment by codebrainz** [comment]
IMO, we can signal "it's ready" to packagers for GTK+ 3 once our Autotools defaults to use it.

**Comment by b4n** [comment]
#524 makes configure autodetect GTK3 (but still prefers GTK2 if both are found and no specific choice was made)

**Comment by LarsGit223** [comment]
@elextr, @codebrainz, @b4n: can this be closed?

**Comment by elextr** [comment]
Not until @b4n makes GTK3 the default :grin:

**Comment by codebrainz** [comment]
It can probably be closed. GTK+3 build is the default in most major distros and since @b4n fixed it, it's also the default on any system that doesn't have GTK+2 development headers installed. The only place it's not default is on non-Linux or olden Linux.

**Comment by b4n** [comment]
@techee thanks for the issues cleanup 😃
