### ISSUE TITLE
Please add an extra line for "./configure" telling the user whether vte will be compiled-in or not. Thanks.

### ISSUE THREAD

**Issue by ghost** [geany/geany#453]
Hi.

The configure script, when you use: --enable-vte option
says this:

Use virtual terminal support     : yes

Could this be changed to:

Use virtual terminal support (VTE)  : yes

instead? It might be less confusing for people perhaps.

VTE source is at:

http://ftp.gnome.org/pub/GNOME/sources/vte/?C=M;O=D

Also, I think if vte is not compiled in, you do not get any
configure line. Perhaps this line should be possible:

"Use virtual terminal support     : no"

then a user can see that VTE will not be compiled.

When I just tried to compile it, I think I did not see
that line.

**Comment by elextr** [comment]
On 4 April 2015 at 12:32, Robert A. Heiler <notifications@github.com> wrote:

> Hi.
>
> The configure script, when you use: --enable-vte option
> says this:
>
> Use virtual terminal support : yes
>
> Could this be changed to:
>
> Use virtual terminal support (VTE) : yes
>
> instead? It might be less confusing for people perhaps.
>

​Pull requests are welcome :)​



> VTE source is at:
>
> http://ftp.gnome.org/pub/GNOME/sources/vte/?C=M;O=D
>
> Also, I think if vte is not compiled in, you do not get any
> configure line. Perhaps this line should be possible:
>
> "Use virtual terminal support : no"
>
> then a user can see that VTE will not be compiled.
>
> When I just tried to compile it, I think I did not see
> that line.
>
​My understanding is that the --enable-vte option compiles the capability
to use VTE into Geany, but its a dynamic library, and actually loading and
using it is a runtime decision, see the --no-terminal command line option.

Also Geany can be compiled with support but run without VTE if it can't
find the library.

Cheers
Lex​

**Comment by andy5995** [comment]
> Also, I think if vte is not compiled in, you do not get any
> configure line. Perhaps this line should be possible:
> 
> "Use virtual terminal support : no"

That's output when `--disable-vte` is used. Don't know if it did when this ticket was opened 3 years ago though. ;)

> Could this be changed to:
> 
> Use virtual terminal support (VTE) : yes

Above, looks like @elextr agreed.
#2028 addresses that.
