### ISSUE TITLE
Split Window copy and paste? 

### ISSUE THREAD

**Issue by pik** [geany/geany#460]
I can find a mention of the problem as far back as http://lists.geany.org/pipermail/plugins-tracker/2011-July/000461.html 

But as of 1.24.1-1 this still does not work. What's the status on this? Is there a reason it would be particularly difficult to add?

**Comment by elextr** [comment]
On 9 April 2015 at 13:30, Alex <notifications@github.com> wrote:

> I can find a mention of the problem as far back as
> http://lists.geany.org/pipermail/plugins-tracker/2011-July/000461.html
>
> But as of 1.24.1-1 this still does not work. What's the status on this? Is
> there a reason it would be particularly difficult to add?
>

​Ummm, yes.

There has been more than one implementation​ over time.  One did it in core
and was pretty big and intrustive, and the maintainer felt it was too much
for the purpose.  There have also been ones as plugins, or simple
improvements but I guess none was sufficiently good for the size of the
change to be committed, or the maintainer just hasn't had time :)

Cheers
Lex

**Comment by pik** [comment]
Thanks for the response. At least for me the big reason to have a split-screen is to be able to copy and paste (and it's a constant gotcha to have the file one is trying to copy from in the split and the wrong selection being copied as a result). 

Do you have a link for one of the implementations that didn't make it in? Would you be open to a pull-request to correct this?

**Comment by elextr** [comment]
#185 is the only PR I can see quickly, but it now has merge conflicts,
probably because of changes since it was last looked at.

@b4n doesn't seem to have PRed his shortcut version, or maybe I missed it.

**Comment by pik** [comment]
It seems like `document_get_current` is the culprit - which gets the current page explicitly from `main_widgets.notebook`, I have no idea what it might or might not break - but perhaps a change worth trying is to have it grab the page for the currently focused widget instead?

**Comment by b4n** [comment]
> @b4n doesn't seem to have PRed his shortcut version, or maybe I missed it.

I don't think I have, but it's there: https://github.com/b4n/geany/tree/splitwindow-refactoring-m

> One did it in core and was pretty big and intrustive, and the maintainer felt it was too much
for the purpose.

Not exactly :)  to be more precise, I felt the implementation was not as clean as I would hope for, and beyond that has some intrusive details needing fixing anyway.

**Comment by pik** [comment]
So messing with `document_get_current()` seems very likely to break things. The hacky solution would just be using `focusw` https://github.com/pik/geany/commit/41ff67f8190ce588bb7065bbe55b489bfdde60c3,  and possibly not using `document_get_current()` at all in the relevant callback.c functions. 
I am not sure about how this check works though: 
```
	else if (IS_SCINTILLA(focusw) && doc != NULL) {
		sci_cut(focusw);
	}
```
Are there times where IS_SCINTILLA(focusw) is true but doc is still null (I'm not really sure when or if that should ever occur, but obviously I'm not familiar codebase) ?

**Comment by elextr** [comment]
On 10 April 2015 at 04:09, Alex <notifications@github.com> wrote:

> So messing with document_get_current() seems very likely to break things.
> The hacky solution would just be using focusw pik@41ff67f
> <https://github.com/pik/geany/commit/41ff67f8190ce588bb7065bbe55b489bfdde60c3>,
> and possibly not using document_get_current() at all in the relevant
> callback.c functions.
> I am not sure about how this check works though:
>
>     else if (IS_SCINTILLA(focusw) && doc != NULL) {
>         sci_cut(focusw);
>     }
>
> Are there times where IS_SCINTILLA(focusw) is true but doc is still null
> (I'm not really sure when or if that should ever occur, but obviously I'm
> not familiar codebase) ?
>

​Without looking at the code I would guess when there is no document open
at all.​

**Comment by pik** [comment]
> ​Without looking at the code I would guess when there is no document open at all.​
@elextr No, I tested that and those callbacks don't seem to be triggered if there is no document open.

**Comment by codebrainz** [comment]
There's likely tons of places that make assumptions about there only being one active/visible Scintilla widget, and/or that use the documents notebook to figure out which document is active and stuff. @kugel- would probably know for sure.

**Comment by pik** [comment]
So on closer inspection the fix to use focusw instead of doc->editor->sci doesn't seem to be so bad (#467), since all of the relevant callbacks call sci_ functions and don't need anything other than the ScintillaObject. 

Getting redo/undo, ctrl+s, find/replace etc. to work would be a little harder - the problem probably being that the ScintillaObject has no pointer back to the document/editor associated with it - therefore to get the corresponding editor or document for a ScintillaObject after a gtk_window_get_focus call requires iterating through all the documents - but pretty much everywhere it is assumed that `main_widgets.notebook` is the only notebook in geany. 
Changing `main_widgets.notebook` to support an array of pointers would also break a lot of stuff, so maybe the simplest solution is to add an additional pointer to the GeanyMainWidgets struct for additional_notebooks, and to modify the relevant callback functions to include checking additional_notebooks as well.

**Comment by erm3nda** [comment]
Was a big fail that window... all other editors (not gedit :=) ) does allow multi panel editing and is one of the two things i miss on Geany. Multi edition and vertical selection (seen on Notepad++). Even if i can autopep8 it, it's cool to being able to select vertical rows :)
