### ISSUE TITLE
waf: signallist.i always recreated on OS X

### ISSUE THREAD

**Issue by techee** [geany/geany#463]
When using waf on OS X the signallist.i file is always recreated no matter whether there have been any changes in the code or not:

```
jhbuild: geany$ ./waf
Waf: Entering directory `/Users/jhbuild/geany/_build_'
[138/244] signallist.i: data/geany.glade -> src/signallist.i
Waf: Leaving directory `/Users/jhbuild/geany/_build_'
'build' finished successfully (0.225s)
```

Interestingly, this doesn't seem to be the case on linux. I've played with waf for a while but without any success (and no indication why this happens). Any ideas?

(This doesn't seem to have any side-effects so it doesn't matter that much, still it shouldn't happen.)

**Comment by b4n** [comment]
Weird indeed… I don't think Waf works on timestamps, but are the time of the sources and target meaningful?
