### ISSUE TITLE
Shared lib loading issues on default Xubuntu 15.04

### ISSUE THREAD

**Issue by vogon-poetic** [geany/geany#480]
I've just installed Xubuntu 15.04 (everything is default) and I've decided to clone the geany repo and have the latest and greatest version of Geany. :) After installing necessary dependencies (`python-docutils` for html documentation and `apt-get build-dep geany` for the rest), then building and installing with make I get the following error:  
```
$ geany
geany: error while loading shared libraries: libgeany.so.0: cannot open shared object file: No such file or directory
```

In `/usr/local/lib` I have the following geany related files/symlinks:  
```
drwxr-xr-x 2 root root      4096 Apr 29 23:29 geany
-rwxr-xr-x 1 root root      1165 Apr 29 23:29 libgeany.la
lrwxrwxrwx 1 root root        17 Apr 29 23:29 libgeany.so -> libgeany.so.0.0.0
lrwxrwxrwx 1 root root        17 Apr 29 23:29 libgeany.so.0 -> libgeany.so.0.0.0
-rwxr-xr-x 1 root root  18243544 Apr 29 23:29 libgeany.so.0.0.0
```

Any ideas as to how to fix this issue would be greatly appreciated.

**Comment by b4n** [comment]
`libtool --finish /usr/local/lib` (or `ldconfig /usr/local/lib`) with the appropriate privileges.

But we need to find out why it isn't done by default, and how to make it happen, because it's like then gazillionth report we have about that in something like two weeks since it landed…
