### ISSUE TITLE
Underscore and camel case as word separator

### ISSUE THREAD

**Issue by Akronix** [geany/geany#492]
Hello.

I'm missing to have a option to treat underscore and/or camel case as word separator.
This is relevant, for example, when I'm doing <kbd>cntrl</kbd> + <kbd>shift</kbd> + arrow key to move between words or <kbd>cntrl</kbd> + <kbd>backspace</kbd> for deleting word behind cursor; many editors support this and many common applications like firefox or nautilus considers underscore as word separator.

I guess this would be a matter of modifying GEANY_WORDCHARS macro in running time.

**Comment by b4n** [comment]
For underscores, depending on how you want it to behave exactly, and whether you want it applied to all filetypes, you can either change the [`whitespace_chars`](http://www.geany.org/manual/#id5) setting to include `_` or the [`wordchars`](http://www.geany.org/manual/#settings-section) one not to include it.

**Comment by Akronix** [comment]
those settings are for filetypes configurations, aren't they? how do I change it for all filetypes?

**Comment by b4n** [comment]
easiest way is to alter `whitespace_chars` in *filetypes.common* to include `_` (*tools->configuration files->filetypes.common*).

**Comment by Akronix** [comment]
@b4n I did that and It didn't work, unfortunately.

**Comment by elextr** [comment]
I think you would also have to set wordchars in your current filetype to not contain _

**Comment by Akronix** [comment]
hi @elextr. All the wordchars appearances in /usr/share/geany as well as in ~/.config/geany are preceeded by a #. That means that they're commented, what should I do? should I uncomment them?

**Comment by elextr** [comment]
IIUC when they are commented out in the filetype it defaults to the macro, @b4n yet another "all languages should be C" assumption?

So you need to uncomment it then change it to override the default macro.

**Comment by Akronix** [comment]
Ok, now it's working.
But they're still two issues:
1. I have to define wordchars in every filetype. I've tried to define wordchars in filetypes.common and in snippets.conf and it works only for unknown document types.
2. There is no way to configure it graphically. I think an entry in various preferences would be desirable.

**Comment by elextr** [comment]
Re-visiting your OP, guess the name of the operations is unclear.  Move/delete etc by "word" really means by "identifier in the current language".  

The method above is just a workaround.  There may be other side effects of varying what the filetype thinks is an identifier character.

Using an alternate definition of "word" probably should be extra operations, not a replacement for the current definitions.  You could then also support CaMeLcAsE.  Pull requests are welcome.

**Comment by Akronix** [comment]
OK, I'll try to fix this and send a pull request in summer holidays. 
I leave this open in the meanwhile.

**Comment by b4n** [comment]
OK I was indeed wrong in my first post it doesn't work only adding `_` to filetype.common's `whitespeace_chars`.  This used to, but was changed in response to https://sourceforge.net/p/geany/bugs/772/

@elextr 
> IIUC when they are commented out in the filetype it defaults to the macro, @b4n yet another "all languages should be C" assumption?

@Akronix 
> 1. I have to define wordchars in every filetype. I've tried to define wordchars in filetypes.common and in snippets.conf and it works only for unknown document types.

This sounds like something we should fix indeed, make the default for *filetypes.common* be the macro, and the default for all other filtypes be the *filetypes.common* value.

**Comment by Akronix** [comment]
:+1:
After you merge #501 y close this and only the camelCase would be left.
I think the camelCase support would be not so trivial, but I've already seen it implemented in Eclipse's editor.

**Comment by Akronix** [comment]
WoW I was using Geany so lively with this new feature that I forgot at all that this was added only since 1.25 after I opened this bug. Thanks!
