### ISSUE TITLE
Symbols in .cu files

### ISSUE THREAD

**Issue by DThought** [geany/geany#494]
C and C++ files have features such as function hinting and struct property autocomplete. CUDA (.cu) files are highlighted in almost exactly the same way, but provide none of these features. Would it be possible to add them?

**Comment by elextr** [comment]
You could try adding the `tag_parser=C` key (here)[http://www.geany.org/manual/current/index.html#tag-parser] to the CUDA filetype to see if it will work.  But perhaps it was left out because it caused problems.
