### ISSUE TITLE
Comment folding in fortran code

### ISSUE THREAD

**Issue by Calu85** [geany/geany#502]
Hi.
I have tried to make geany fold my multilines comments of fortran code, without succes.
I copied filetype.fortran to my local folder and modified this file. I tried adding the lines
`comment_open=!>`
`comment_close=!!`
and also 
`[lexer_properties]`
`fold.comment.fortran=1`

I chose `!>` to make it compatible with doxygen blocks of comments in fortran. Then I tried other combinations but none worked.
Am I missing something? Is this feature not supported for fortran? If not, can it be added? I would be glad to help with this if I can.

**Comment by elextr** [comment]
The folding code for fortran contains the comments

```
	//
	// bool foldComment = styler.GetPropertyInt("fold.comment") != 0;
	// Do not know how to fold the comment at the moment.
	//
```

So I guess its not supported.  The lexer is part of the [Scintilla](http://www.scintilla.org/index.html) project which is the editor we use, but is a separate project.

**Comment by erickpaquin** [comment]
@Calu85 , Is this PR still relevant? If not can it be closed? Thanks.

**Comment by Calu85** [comment]
I think this is no longer relevant.
