### ISSUE TITLE
Contract/Shrink everything option.

### ISSUE THREAD

**Issue by lugon** [geany/geany#508]
I generally find myself going through files contracting the body functions with the little '+' at the margin, so I have a more general perspective of where everything is. This is awkward for large files with a lot of functions and stuff, and I was wondering how hard would it be to have an option 'contract everything' or something like that that contract/shrink the body of all the functions in the file.

**Comment by b4n** [comment]
I guess it'd be as hard as triggering *Document → Fold All* :)  (which you can bind to your linking)

**Comment by lugon** [comment]
Oh my...
