### ISSUE TITLE
Join lines failure

### ISSUE THREAD

**Issue by lucas-bob** [geany/geany#510]
Hello,

No error while compiling Geany 1.25 from source but "join lines" does not appear in menu after assigning a shortcut  and shortcut doesn't work 

uname -a  ===>
Linux BOB 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

./autogen.sh ==>
Install Geany in                 : /usr/local
Using GTK version                : 2.24.23
Enable binary relocation         : no
Build with plugin support        : yes
Use (UNIX domain) socket support : yes
Use virtual terminal support     : yes
Build HTML documentation         : yes
Build PDF documentation          : no
Build API documentation          : no

Configuration is done OK.

make check ==>
Testsuite summary for Geany 1.25

TOTAL: 288
PASS:  288
SKIP:  0
XFAIL: 0
FAIL:  0
XPASS: 0
ERROR: 0

**Comment by elextr** [comment]
Yes, "join lines" is not in a menu, thats bad because it makes it difficult to discover, and assigning a keybinding is not supposed to make it appear in the menu.

But if it is assigned a keybinding it works for me with ccec1fe29.

**Comment by lucas-bob** [comment]
Thank's,
ccec1fe was already applied and i confirm "join lines" keybinding doesn't work.
"Reflow Lines/block" in menu as well as associated keybinding doesn't work too.

**Comment by elextr** [comment]
Both work here, what operating system are you using?

**Comment by lucas-bob** [comment]
Linux Mint 17.1 Cinnamon 64-bit version 2.4.8
Linux kernel: 3.13.0-37-generic

**Comment by elextr** [comment]
Hmm, I'm using Mint 17.0 and cinnamon 2.2 and it works for me. And it
worked on another machine with Mint 17.1, so I don't know.  Are you sure
reflow from the menu doesn't work?

**Comment by lucas-bob** [comment]
Strange...
I disabled all plugins (make distclean; ./configure --disable-plugins; make install) ==> same result.
I disabled all plugins and enabled GTK3 (make distclean; ./configure --disable-plugins --enable-gtk3; make install) ==> same result.
What are your "configure"  parameters ?

**Comment by elextr** [comment]
--enable-gtk3 otherwise default.

Try running with -c /tmp/something_that_does_not_exist to ensure you get a
completely clean config and try that.

**Comment by lucas-bob** [comment]
Did it ==> Same problem...
Full delete geany and reinstall from git ==> Same problem
Very strange....

**Comment by elextr** [comment]
Yes, very strange, lets concentrate on reflow from the menu first.  What are the settings for menu->edit->preferences->editor->features->line breaking column and menu->edit->preferences->editor->display->long line marker enabled and column?  These are the length used for the reflow of text.

What are you expecting reflow to do?  Lets say the columns above are 80 (the default IIRC) if you have say 5 lines of 40 chars and select them, reflow from the menu will re-arrange the content to give you 2.5 lines of 80 chars (or as close as breaking on word boundaries will allow).  Is this not happening for you, and if not what is happening?

**Comment by lucas-bob** [comment]
Now it's fine...
"Long line marker"  was not checked, when checked "Join lines" and "Reflow" are working fine!
Shame on me, thank you for your help and sorry for this waste of time
