### ISSUE TITLE
new realease? 

### ISSUE THREAD

**Issue by oz123** [geany/geany#520]
Hi, 
the latest point release is currently 875 commits behind. There are many bug fixed, and changed. Is it possible to make a new point release ? Can you share a plan when it is going to happen?

Thanks, 
Oz

**Comment by b4n** [comment]
Worse timing ever ;) http://lists.geany.org/pipermail/devel/2015-June/009519.html

**Comment by oz123** [comment]
Indeed, I am not following your mailing list, but thank you for the update! 
And for geany too.
