### ISSUE TITLE
GTK3 Build Command Dialog Issues

### ISSUE THREAD

**Issue by elextr** [geany/geany#528]
Using:

 07:06:06: Geany INFO		: Geany 1.25 (git >= 5e91765), en_AU.UTF-8
07:06:06: Geany INFO		: GTK 3.10.8, GLib 2.40.2

in the build command dialog the following features don't work:

1) no greying of overloadable entries
2) no cursor shows in empty command or working directory entries when clicked on, entries with content and empty regular expression entries work normally

On the same computer, Linux Mint 17.1, Cinnamon 2.4.8 :

08:02:33: Geany INFO		: Geany 1.25 (git >= 15f012c), en_AU.UTF-8
08:02:33: Geany INFO		: GTK 2.24.23, GLib 2.40.2

works perfectly.

[Edit: appears that the cursor is at least partly theme dependent, using Adwaita gives a cursor, but non-flashing]

**Comment by b4n** [comment]
Color fixed (it actually probably never worked on GTK3).  The cursor thing is very odd but probably not really Geany's fault.

**Comment by elextr** [comment]
At least for me cursor is also fixed by above change.
