### ISSUE TITLE
Keybinding the second execute menu item

### ISSUE THREAD

**Issue by arkhebuz** [geany/geany#530]
According to the [manual](http://www.geany.org/manual/#build-menu-keyboard-shortcuts) it should be possible:
> Keyboard shortcuts can be defined for the first two filetype menu items, the first three independent menu items, the first **two** execute menu items and the fixed menu items.

I can't however find any option for that, neither in Geany (1.24.1 from Ubuntu repos), nor in online keybindings list.

Is it possible some other way?

**Comment by elextr** [comment]
Thanks for the report.  Only fixed build entries can have keybindings, but this item in the manual was missed when one execute command was changed from fixed to optional.

Fixed in 54eff298bdff43bf86c40fb12210e2a761abeca6
