### ISSUE TITLE
Renaming of files currently open in editor

### ISSUE THREAD

**Issue by zaroth** [geany/geany#534]
Similar to Notepad++'s `Rename...` option in `File` menu, there is [some (1)](http://blogs.dailynews.com/click/2008/06/06/one-thing-i-wish-geany-could-d/) [demand (2)](http://softwarerecs.stackexchange.com/questions/20652/geany-plugin-to-easily-rename-a-file) for a feature like this.

**Comment by elextr** [comment]
On 26 June 2015 at 20:42, Lukasz Dobrogowski <notifications@github.com>
wrote:

> Similar to Notepad++'s Rename... option in File menu, there is some
> <http://blogs.dailynews.com/click/2008/06/06/one-thing-i-wish-geany-could-d/>
> demand
> <http://softwarerecs.stackexchange.com/questions/20652/geany-plugin-to-easily-rename-a-file>
> for a feature like this.
>

​Menu->File->Save​ As and select the "Rename" button.

Cheers
Lex

**Comment by zaroth** [comment]
Oh, thanks. It didn't occur me it can be hidden behind the dialogue window.

**Comment by codebrainz** [comment]
I had a PR to improve it, but it's been a while since I worked on it:
https://github.com/geany/geany/pull/138
