### ISSUE TITLE
warning about usage of deprecated functions with gdk-pixbuf 2.32

### ISSUE THREAD

**Issue by frlan** [geany/geany#546]
When compiling Geany with gtk 2.24 I'm getting some messages about deprecated functions usage:

Using GTK version                                              : 2.24.28 
Compiling Git revision                                         : aa40250 

In file included from ../src/about.c:34:0:
	../src/gb.c: In function ‘load_images’:
	../src/gb.c:1690:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[0] = gdk_pixbuf_from_pixdata(&pic1, FALSE, NULL);
	  ^
	../src/gb.c:1691:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[1] = gdk_pixbuf_from_pixdata(&pic2, FALSE, NULL);
	  ^
	../src/gb.c:1692:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[2] = gdk_pixbuf_from_pixdata(&pic3, FALSE, NULL);
	  ^
	../src/gb.c:1693:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[3] = gdk_pixbuf_from_pixdata(&pic4, FALSE, NULL);
	  ^
	../src/gb.c:1694:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[4] = gdk_pixbuf_from_pixdata(&pic5, FALSE, NULL);
	  ^
	../src/gb.c:1695:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[5] = gdk_pixbuf_from_pixdata(&pic6, FALSE, NULL);
	  ^
	../src/gb.c:1696:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[6] = gdk_pixbuf_from_pixdata(&pic7, FALSE, NULL);
	  ^
	../src/gb.c:1697:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[7] = gdk_pixbuf_from_pixdata(&pic8, FALSE, NULL);
	  ^
	../src/gb.c:1698:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[8] = gdk_pixbuf_from_pixdata(&pic9, FALSE, NULL);
	  ^
	../src/gb.c:1699:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[9] = gdk_pixbuf_from_pixdata(&pic10, FALSE, NULL);
	  ^
	../src/gb.c:1700:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[IMAGE_BUTTON_UP] = gdk_pixbuf_from_pixdata(&bup, FALSE, NULL);
	  ^
	../src/gb.c:1701:2: warning: ‘gdk_pixbuf_from_pixdata’ is deprecated (declared at /usr/include/gdk-pixbuf-2.0/gdk-pixbuf/gdk-pixdata.h:119) [-Wdeprecated-declarations]
	  icons[IMAGE_BUTTON_DOWN] = gdk_pixbuf_from_pixdata(&bdown, FALSE, NULL);
	  ^

**Comment by codebrainz** [comment]
Compile with `make CFLAGS="-DGLIB_DISABLE_DEPRECATION_WARNINGS"`.

**Comment by frlan** [comment]
Was using waf for above.

**Comment by codebrainz** [comment]
Whichever way for Waf then, maybe like `CFLAGS="-DGLIB_DISABLE_DEPRECATION_WARNINGS" ./waf configure`. IMO we should add this to the build systems, if someone really cares about what GTK+ deprecated this week, they can undefine it on the command-line still. The problem is much worse with GTK+ 3.

**Comment by elextr** [comment]
On 2 July 2015 at 17:46, Matthew Brush <notifications@github.com> wrote:

> Whichever way for Waf then, maybe like CFLAGS="-DGLIB_DISABLE_DEPRECATION_WARNINGS"
> ./waf configure. IMO we should add this to the build systems, if someone
> really cares about what GTK+ deprecated this week, they can undefine it on
> the command-line still. The problem is much worse with GTK+ 3.
>
​Agreed.  If only I knew how our build systems worked, maybe if I threaten
to do it, somebody who knows will do it to avoid cleaning up the mess :)​

​Cheers
Lex​

**Comment by b4n** [comment]
> When compiling Geany with gtk 2.24 […]

This is actually not GTK, but gdk-pixbuf, which deprecated [gdk_pixbuf_from_pixdata()](https://developer.gnome.org/gdk-pixbuf/unstable/gdk-pixbuf-Inline-data.html#gdk-pixbuf-from-pixdata) in 2.32.

(and see where those warnings come from)

> IMO we should add this to the build systems. If someone really cares about what GTK+ deprecated this week, they can undefine it on the command-line still.

You need to document it then, as it's a lot easier (IMO) to find the compiler warning than adding `-USOMEDEFINE` to `CPPFLAGS` or whatnot.
Also, we probably should *not* do this for GTK 2.x (I mean, GTK itself), now we depend on the latest version.  Don't buy that conspiracy theory: no, they don't deprecated everything in GTK 2.24.

> It masks valuable compiler warnings and prevents using `-Werror` without having to tweak a bunch of other flags. The problem is much worse with GTK+ 3.

`-Wno-deprecated-declarations` isn't really '"a bunch", especially if you're already sneaking `-Werror` in :)  BTW, we have some not-yet-fixed (totally harmless) issues with `-Wwrite-strings`, which is a whole lot more interesting that deprecations.

**Comment by codebrainz** [comment]
> Also, we probably should not do this for GTK 2.x (I mean, GTK itself), now we depend on the latest version. Don't buy that conspiracy theory: no, they don't deprecated everything in GTK 2.24.

But we don't really give a damn if GTK+ deprecates GTK2 stuff. In the few rare cases anybody does, like us when porting, we can turn the warnings back on (or even add a build-system option like `--enable-g-deprecated` or something.

> -Wno-deprecated-declarations isn't really '"a bunch"

No, but IIUC then it will clobber all real warnings about using deprecated functions that aren't part of GTK+ and friends, like the stdlib, posix, win32, and such stuff that might use the deprecation attribute of GCC.

**Comment by b4n** [comment]
The code generating the warnings reported here no longer exist, so the report itself is obsolete.  Further discussion on it might not, though.
