### ISSUE TITLE
Feature request: please add code map

### ISSUE THREAD

**Issue by Yanpas** [geany/geany#549]
what I mean (in Notepad++ on the right):
![docmap](https://cloud.githubusercontent.com/assets/7345761/8503583/215bd134-21ca-11e5-92b5-d699ddf06b39.png)

**Comment by b4n** [comment]
https://github.com/geany/geany-plugins/tree/master/overview

**Comment by Yanpas** [comment]
Can't build plugin on your link, but I have found another one https://github.com/codebrainz/overview-plugin. Buggy, but works somehow. It seems to me that this is not fork, independent plugin.

So how to build your plug-in? Error output https://gist.github.com/Yanpas/4f7ce7c4134790c2eebe
I was building: 
```
./autogen.sh --disable-geanygendoc --disable-projectorganizer --disable-geanyprj
./configure --disable-geanygendoc --disable-projectorganizer --disable-geanyprj
make
error
```

**Comment by Yanpas** [comment]
Do https://github.com/codebrainz/overview-plugin/issues/9 exist in this pugin too?

**Comment by b4n** [comment]
> Can't build plugin on your link, but I have found another one https://github.com/codebrainz/overview-plugin. Buggy, but works somehow. It seems to me that this is not fork, independent plugin.

It is the same one, just in the unified repository.

> So how to build your plug-in? Error output https://gist.github.com/Yanpas/4f7ce7c4134790c2eebe
I was building: 

Yeah you need a pretty recent version of Geany for this to work AFAIK.  But probably @codebrainz will better be able to tell you.

**Comment by b4n** [comment]
> Do codebrainz/overview-plugin#9 exist in this pugin too?

Not sure, but I don't think I saw that when I tested it

**Comment by Yanpas** [comment]
Plugin is very young, doesn't even exists in Debian sid repo, but EXISTS! :)

**Comment by codebrainz** [comment]
@Yanpas did you get it building? Depending on your OS it might work against Geany's last release, but it should definitively work against Geany from Git (which is due to be released soon, and so with the plugins, so Overview should start getting packaged soon after I think).

**Comment by Yanpas** [comment]
No, I wasn't able to build it on virtual machine from github.com/geany/geany-plugins with geany 1.24+dfsg-5 but I built it succesfully from https://github.com/codebrainz/overview-plugin

**Comment by Yanpas** [comment]
@codebrainz where to report bugs of this plugin? codebrainz/overview-plugin or here?
Ctrl+tab doesn't work... BTW confirm wrong tab names and impossibility to go to line

**Comment by codebrainz** [comment]
> No, I wasn't able to build it on virtual machine from github.com/geany/geany-plugins with geany 1.24

Are you sure it wasn't the GeanyLua (different plugin) compilation errors [from your paste](https://gist.github.com/Yanpas/4f7ce7c4134790c2eebe#file-gistfile1-sh-L1)?

The errors in your paste for Overview plugin are somewhat expected if you aren't using version of Geany from Git. If you have a Linux distro where symbols are exported by default (most/all), it should've still linked though, due to [some hack](https://github.com/codebrainz/overview-plugin/commit/f7aa8491a95769448f5465e6ff016ec9be025f94) I added to try to temporarily allow using the plugin with latest released version of Geany (1.24).

If it doesn't build as part of the Geany-Plugins project I'm a bit worried as we are releasing soon and so it might make it cause problems or not get packaged for various distros.

**Comment by codebrainz** [comment]
> where to report bugs of this plugin?

It doesn't much matter. Using the fork in the geany-plugins repo will get your Issue more views, but I personally watch both and if you want to contribute fixes for the issues you have, it might be easier to vet them through the "upstream" (where I put the plugin originally) repo.

**Comment by Yanpas** [comment]
@codebrainz 
1.Yes, seems that that was geanyLua plugin errors. But without lua plugin I can't build whole plugins. And I haven't tried to build geany-plugins with latest git geany version. I may try if you want.

2. Ok, I will report bug here.
