### ISSUE TITLE
Overview plugin disables all hotkeys

### ISSUE THREAD

**Issue by Metotron** [geany/geany#571]
I have openSUSE 13.2 (Harlequin) (i586)
I make geany from git with this parameters of geany-plugins:
--disable-debugger --disable-devhelp --disable-geanygendoc --disable-geanylatex --disable-geanylipsum --disable-defineformat --disable-geanyctags --disable-geanydoc --disable-geanyinsertnum --disable-geanylua --disable-geanymacro --disable-geanyminiscript --disable-geanysendmail --disable-geanypg --disable-geniuspaste --disable-markdown --disable-multiterm --disable-pohelper --disable-pretty_printer --disable-scope --disable-shiftcolumn --disable-spellcheck --disable-updatechecker --disable-xmlsnippets --disable-geanypy
When I use overview plugin alone or in combination with other, I can not use any hotkeys except overview hotkeys (I use alt+m).

**Comment by elextr** [comment]
Is this when the focus is on the overview widget or on the editing widget?
