### ISSUE TITLE
Rename "go to tag definition" and friends to "go to symbol definition"

### ISSUE THREAD

**Issue by techee** [geany/geany#579]
I believe we shouldn't expose to users the fact we use some library called ctags for parsing files which calls the parsed symbols "tags". For users, a tag is ```<this>``` and it may be not obvious what this feature does. Moreover, when translated, it gets even more misleading - in the Czech translation it's called something like "go to marker definition".

I'd suggest to use the word "symbol" in the UI (we already have the Symbols tab in the sidebar and this would make things more consistent).

**Comment by elextr** [comment]
Yes, "tag" is now some HTML thingy for the internet generation.  Calling it "symbol" in all the user facing stuff would be better, who is gonna do the manual :)

**Comment by eht16** [comment]
:+1: 

Should we also rename --generate-tags or might this be ok because at this point it is already quite technical, even for the end user, and so is properly named as tag?

**Comment by techee** [comment]
@eht16 Good question. I've already started with the renaming and there are also the *.tags files with global tags (within the "tags" directory) and it feels a bit more natural to keep them calling "tags files" as these are closer to what ctags generates. With this the --generate-tags could be left as it is.

In the documentation here

http://www.geany.org/manual/current/index.html#tags

the section would be called "Symbols", there would be subsections "Global Symbols" and "Workspace Symbols" and so on, but everything mentioning "tags file" would be kept as it is.

The "tags files" containing "symbols" might be a bit confusing, on the other hand I think the *.tags files are a more "power user" feature not used so frequently and to learn how to generate them users probably need to read the documentation which should explain the naming.  I have no strong opinion on this though, we could also call the files "symbols files" but then we'd have "symbols files" with the *.tags extension inside the tags directory we should probably keep for backwards compatibility.

**Comment by eht16** [comment]
I think also the tags files and their generation are rather "power user" features and so the rather technical term "tag" reflecting the relation to ctags makes sense.
PR #582 is nice!

**Comment by elextr** [comment]
The `.tags` extension of the symbol files relates to their internal formats (ctags and tag mangler) so its ok for it to remain when we are talking about the files or generating them.

The docs just have to explain that.

**Comment by b4n** [comment]
Agreed with both the issue and that we should keep `.tags` files alone (and the `--generate-tags` option seem good enough to me)
