### ISSUE TITLE
Missing PHP functions in code hints

### ISSUE THREAD

**Issue by Nisto** [geany/geany#584]
I noticed `mysqli_connect()` is missing from the PHP hint/completion list. I don't know if there are other functions missing, but the other mysqli_* functions seem to be there...

**Comment by scriptum** [comment]
Try to update tags from here: http://wiki.geany.org/tags/start?s[]=tags
This file has `mysqli_connect`:
http://wiki.geany.org/_media/tags/phpfull-5.3.5.php.tags

**Comment by Nisto** [comment]
Thanks, but the two tag files there are missing a lot of functions as well unfortunately. I guess I will just have to update the files manually as I go... I was hoping everything would be more up to date since I last tried Geany some year or two ago, but oh well, can't have everything I guess.

**Comment by elextr** [comment]
I guess no PHP users contributed their updates back, hint, hint.

**Comment by codebrainz** [comment]
The tags that come with Geany are updated by [a script](https://github.com/geany/geany/blob/master/scripts/create_php_tags.php) which (IIRC) reads the tags from some "official" PHP symbol listing. If stuff is missing, most likely the tags just need to be regenerated or the "official" source is wrong. According to Git log, the PHP tags haven't been updated in 2 years.

**Comment by codebrainz** [comment]
If anyone is curious, [this is the diff](https://gist.github.com/codebrainz/70500dd9651bbbe92a4a) with regenerated tag file.

**Comment by elextr** [comment]
The script above accesses a list from SVN which is no longer maintained and PHP has moved to Git.

Some PHP expert needs to identify a new canonical source of function definitions and update the script as appropriate.

**Comment by DThought** [comment]
The closest replacement seems to be http://doc.php.net/downloads/json/php_manual_en.json. The tags generator script just needs to be updated to parse JSON.

The human-readable version is at http://php.net/manual/en/indexes.functions.php.

**Comment by eht16** [comment]
PR#603 could solve this.
I rewrote the creation script, though this time in Python because of better knowledge.
It should basically generate the same results, just from the up to date JSON upstream source.

@DThought thanks for the link.

The resulting tags file can be downloaded from https://raw.githubusercontent.com/eht16/geany/create_php_tags_update/data/php.tags for testing.

**Comment by eht16** [comment]
@Nisto would you mind testing?
Just download the file https://raw.githubusercontent.com/eht16/geany/create_php_tags_update/data/php.tags and save it to `~/.config/geany/tags`
