### ISSUE TITLE
Methods and classes tree view incorrect in Ruby when using a method directly on the end statement

### ISSUE THREAD

**Issue by jeroenvriesman** [geany/geany#587]
The tree view of methods and classes does not recognize "end.all?" (or any other end statement with a method applied directly) as an end statement in Ruby.
See attached screen-shots.
![ruby_end_not_ok](https://cloud.githubusercontent.com/assets/1464829/8850598/b0d6bfb6-3149-11e5-9ffc-aa7414ceb8f3.png)
![ruby_end_ok](https://cloud.githubusercontent.com/assets/1464829/8850608/bc3804e6-3149-11e5-8855-2f61ccb3aa21.png)

**Comment by jeroenvriesman** [comment]
Geany version 1.25, ubuntu

**Comment by b4n** [comment]
I fixed this in U-Ctags a while ago but forgot to import the changes back into Geany, sorry.  Now fixed.
