### ISSUE TITLE
Shortcut for "Use multi-line matching" is the same for "In Selection" (l)

### ISSUE THREAD

**Issue by konsolebox** [geany/geany#589]
The shortcut for "Use multi-line matching" is the same for "In Selection" (l) in the Replace dialog box.
Please consider changing it to m instead.

Here are the lines to consider in search.c:

	check_multiline = gtk_check_button_new_with_mnemonic(_("Use multi-_line matching"));
	button = gtk_button_new_with_mnemonic(_("In Se_lection"));

**Comment by b4n** [comment]
Hell!  Mnemonic are very annoying that way…

"Use multi-line matching"…  we can't use `u`, it's used for "Use regular expressions";  `s` is for "Search for"; `e` is for "Use escape sequences".  `m` is for "Mark" (in the Search dialog); `l` for "In Selection"; `t` for "Match from start of word"; `i` for "In Document"; `n` for "Replace & Find"; `a` for "Case sensitive"; `c` for "Close"; and `h` for "Replace with".

This leaves us only `g`…  It's not very obvious, but that's the only solution unless we also change another mnemonic (which might be just as complex, and might be more established in the user's habits).

**Comment by codebrainz** [comment]
I don't find duplicates that annoying, you just have to press one extra key to select the duplicated thing and at least it's a logical key. That said, I don't use mnemonics for speed (or much at all), I use them when my mouse is busted or non-existent and I need an intuitive way to traverse the UI :)

**Comment by konsolebox** [comment]
I didn't notice Mark from Find dialog. Yes, `g` would be good.
