### ISSUE TITLE
Windows native dialogs are no longer resizeable

### ISSUE THREAD

**Issue by KevFerguson** [geany/geany#591]
Windows Native dialogs are no longer re-sizeable since updating from 1.24.1 to 1.25. I've toggled the setting to see if that might help, but to no avail.

**Comment by codebrainz** [comment]
Might be related to (and fixed with) PR #583

**Comment by KevFerguson** [comment]
Yep, it certainly was! I installed the latest nightly and dialogs are once again resizeable. Will comment on other ticket.
