### ISSUE TITLE
Color Chooser (Windows) changes across installs - IGNORE/DELETE

### ISSUE THREAD

**Issue by Kratoklastes** [geany/geany#594]
MY BAD... 'Use Windows Native Dialogs' was enabled on Win7. Wasn't me... 

Not a 'bug' as such (and not a 'feature request' either) - but an observation that installing geany 1.24 (from the same win installer - geany-1.24_setup.exe dated 20150429 ) across Windows platforms, results in 2 different versions of the Color Chooser (screenshots below). 

There's nothing on StackExchange (although I'll post this there, too). [This SE question](http://stackoverflow.com/questions/4430410/program-or-script-to-see-hex-triplets-in-their-actual-color/4430442#4430442) shows that my preferred version (the one I get on the Windows Server install) is the one that ubuntu users will see.

### Desktop (Windows 7 Ultimate 64-bit) 
<img width="585" alt="2015-07-30_08h31_06" src="https://cloud.githubusercontent.com/assets/11623509/8971614/57e57fe0-3695-11e5-9db4-15f1e5f48243.png">

### VPS (Windows Server 2008R2)
<img width="657" alt="2015-07-30_08h31_41" src="https://cloud.githubusercontent.com/assets/11623509/8971622/7327d2ee-3695-11e5-83fa-da5c240201d5.png">

**Comment by elextr** [comment]
It looks like the desktop is using the native dialogs, I believe there is a setting in preferences to use GTK or native windows dialogs.

**Comment by codebrainz** [comment]
@Kratoklastes you'll probably want to switch this back once Geany is shipping with GTK+ 3 as the colour dialog has been dumbed down so much as to be nothing but a tablet toy.

![colorchooser](https://cloud.githubusercontent.com/assets/181177/8973404/3d926558-3619-11e5-90c2-236f114ef8f1.png)
