### ISSUE TITLE
Unnecessary trailing spaces added after reflow (ctrl+j)

### ISSUE THREAD

**Issue by lazka** [geany/geany#601]
Not sure if my usecase is different but this has bugging me for some time.

Assume I have

```
dssssddddddddddddddddddddddddddddddddddd dssssddddddddddddddddddddddddddddddddddd
dssssddddddddddddddddddddddddddddddddddd dssssddddddddddddddddddddddddddddddddddd
```

I select both lines and hit ctrl+j I get

```
dssssddddddddddddddddddddddddddddddddddd 
dssssddddddddddddddddddddddddddddddddddd 
dssssddddddddddddddddddddddddddddddddddd 
dssssddddddddddddddddddddddddddddddddddd
```

The first three lines have trailing spaces. I remove them and add one character to the second line and hit ctrl + j again (aka edit typo and reflow), I get again three new trailing spaces:

```
dssssddddddddddddddddddddddddddddddddddd 
dssssdddddddddddddddddddddddddddddddddddX 
dssssddddddddddddddddddddddddddddddddddd 
dssssddddddddddddddddddddddddddddddddddd
```

I'd like to have no trailing spaces in all those cases, or at least preserve the spaces from the original selected text.

thanks

**Comment by elextr** [comment]
Geany currently strips the trailing spaces on reflow if either of Menu->Preferences->Editor->Features->Newline strips trailing spaces or Menu->Preferences->Files->Strip Trailing Spaces and Tabs is set.

**Comment by lazka** [comment]
"Newline strips trailing spaces" works for me, thanks.
