### ISSUE TITLE
comment lines loose hash in copy/paste

### ISSUE THREAD

**Issue by J-Dunn** [geany/geany#602]
In both linux primary buffer selection and context menu copy, comment lines introduced by a hash mark loose the hash and are pasted as non comment lines. 

If the first line selected also begins with a hash the bug does not seem to occur. 

It is unclear why the hash character would be stripped in any circumstance. 

Geany 1.22

**Comment by elextr** [comment]
Unable to reproduce on Geany 1.25, please try a newer version (1.22 is several years and several releases old and is unsupported) or provide more detailed instructions that allow the problem to be reproduced on a newer version.

**Comment by J-Dunn** [comment]
Confirmed: no longer happening in 1.24.1 

Closed.
