### ISSUE TITLE
Nothing happens if change font style

### ISSUE THREAD

**Issue by fordanov** [geany/geany#608]
If I choose any font style  (View -> Change Font) and press "apply" button, there are nothing happens.

**Comment by elextr** [comment]
need some more information, version of geany, platform etc.

**Comment by fordanov** [comment]
I use Linux mint 17.1
I built Geany from source.
It's issue in both version. 1.24.1 and 1.25

@elextr wthat happens in in your case?

**Comment by elextr** [comment]
Works for me, note it works if you change the font, if you just change some font characteristics (like choosing bold) it will have no effect since those are overridden by the style characteristics from the syntax highlighting.

**Comment by elextr** [comment]
Closed since can't reproduce and no more information provided, if more info becomes available on how to reproduce please post here
