### ISSUE TITLE
Wobbly margin

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#614]
![screenshot from 2015-08-17 22 35 40](https://cloud.githubusercontent.com/assets/7548378/9316977/7d8a8ffc-4530-11e5-9125-e5c1b1bc6d1d.png)

I think Geany is marvellous and that it is well worth fixing this minor problem.

**Comment by b4n** [comment]
Looks like something is changing the font of some characters to a non-monospace bold font (`p`, `o`, `a`, `s`, `sx`, etc.), resulting in wider characters.  This then leads to misalignment -- which is actually not a bug, as Sicnitlla (our editing component) explicitly supports proportional fonts.

Which version of Geany do you have, and which plugins?  I never saw such highlighting of seemingly random letters.

**Comment by philiprbrenan** [comment]
Thanks for your response.

Built on or after 2015-07-13.  No plugins. Ubuntu 14

I am using unicode characters via snippets as below.  I accept that within
the word the characters will not align vertically due to their different
sizes, but it would be wonderful if the comment margin could be aligned
regardless. The ability to easily express oneself via unicode identifiers
in Geany using this technique is one of the many, many things that makes
Geany so much better than Eclipse or IntelliJ for developing Android apps.

alpha=𝝰
beta=𝝱
gamma=𝝲
delta=𝝳
psilon=𝝴
zeta=𝝵
eta=𝝶
theta=𝝷
iota=𝝸
kappa=𝝹
lamda=𝝺
mu=𝝻
nu=𝝼
xi=𝝽
omicron=𝝾
pi=𝝿
rho=𝞀
sigma=𝞂
tau=𝞃
upsilon=𝞄
phi=𝞅
chi=𝞆
psi=𝞇
omega=𝞈
AA=𝗔
BB=𝗕
CC=𝗖
DD=𝗗
EE=𝗘
FF=𝗙
GG=𝗚
HH=𝗛
II=𝗜
JJ=𝗝
KK=𝗞
LL=𝗟
MM=𝗠
NN=𝗡
OO=𝗢
PP=𝗣
QQ=𝗤
RR=𝗥
SS=𝗦
TT=𝗧
UU=𝗨
VV=𝗩
WW=𝗪
XX=𝗫
YY=𝗬
ZZ=𝗭
aa=𝗮
bb=𝗯
cc=𝗰
dd=𝗱
ee=𝗲
ff=𝗳
gg=𝗴
hh=𝗵
ii=𝗶
jj=𝗷
kk=𝗸
ll=𝗹
mm=𝗺
nn=𝗻
oo=𝗼
pp=𝗽
qq=𝗾
rr=𝗿
ss=𝘀
tt=𝘁
uu=𝘂
vv=𝘃
ww=𝘄
xx=𝘅
yy=𝘆
zz=𝘇
AAA=𝔸
BBB=𝔹
CCC=𝔺
DDD=𝔻
EEE=𝔼
FFF=𝔽
GGG=𝔾
HHH=𝔿
III=𝕀
JJJ=𝕁
KKK=𝕂
LLL=𝕃
MMM=𝕄
NNN=𝕅
OOO=𝕆
PPP=𝕇
QQQ=𝕈
RRR=𝕉
SSS=𝕊
TTT=𝕋
UUU=𝕌
VVV=𝕍
WWW=𝕎
XXX=𝕏
YYY=𝕐
ZZZ=𝕑
aaa=𝕒
bbb=𝕓
ccc=𝕔
ddd=𝕕
eee=𝕖
fff=𝕗
ggg=𝕘
hhh=𝕙
iii=𝕚
jjj=𝕛
kkk=𝕜
lll=𝕝
mmm=𝕞
nnn=𝕟
ooo=𝕠
ppp=𝕡
qqq=𝕢
rrr=𝕣
sss=𝕤
ttt=𝕥
uuu=𝕦
vvv=𝕧
www=𝕨
xxx=𝕩
yyy=𝕪
zzz=𝕫

Thanks,

Phil

Philip R Brenan

**Comment by b4n** [comment]
Hum, I see.  Well, I don't really see what the editor can do here, as you use spaces for alignment, and a space is a character with a defined width.

I see two workarounds:

1. Use a monospaced font that contains all these characters.  DejaVu Mono supports some of those (i.e. `𝝱`, but not `𝗚`), maybe some other will support more -- but maybe not, unfortunately.
2. Align the comments with tabulations.  This way the slight misalignment will be recovered by the tab stop positions:
  
  ```
(𝗚asdf);	a𝝱	𝗚	// asd
+ asdf		a𝗚	𝝱	// asd
+ asdf		a𝗚      𝝱	// asd
+ asdf		a𝗚 s d f𝝱	// asd
```
  (well, Firefox gets the tab stops slightly wrong, but whatever)
  (FWIW, GEdit behaves even more strangely, having the spaces right after `𝝱` and `𝗚` very thin)

If there's something else you think the editor should do here, I suggest you to take this to [Scintilla](http://www.scintilla.org/)'s mailing list, as the main author is a lot more knowledgeable about Unicode that I am (and also, most Geany devs follow this ML too).

**Comment by codebrainz** [comment]
Another fix is to either edit the color scheme to remove all the use of bold, or else use this fontconfig file to disable fontconfig's "fake" boldening of fonts (which throws the proportions out of whack):

https://gist.github.com/codebrainz/902717

**Comment by b4n** [comment]
@codebrainz I'm not sure it would help, because it's not a question of boldness, those are just characters not in the font.  𝗚 is actually `U+1D5DA`, not a bold version of `U+0047`.

**Comment by philiprbrenan** [comment]
Yes - I believe you are right.

I think for the moment that I will carry on as I am as I like everything
else the way it is.

Would it be acceptable for me to add a development request such as: *"in
the event that  several spaces followed by the comment chars cross the
right comment margin that the position of the text after the spaces be
adjusted slightly so that everything lines up at the comment margin*"?

I appreciate every-one's willingness to help me.


Thanks,

Phil

Philip R Brenan

On Tue, Aug 18, 2015 at 1:04 AM, Colomban Wendling <notifications@github.com

**Comment by codebrainz** [comment]
> @codebrainz I'm not sure it would help, because it's not a question of boldness, those are just characters not in the font. 𝗚 is actually U+1D5DA, not a bold version of U+0047.

Oh. Here all those characters are bold so I just assumed the usual "fake bold" issue.

@philippwiesemann that feature sounds unlikely to be implemented as it requires special language-specific magic (probably non-trivial too) and is a feature that should probably be implemented in the Scintilla widget that Geany uses (separate project) or by using a better font (ex. GNU Unifont) that contains all the needed glyphs in the same font face. Also, have you tried using tabs? they might make it line up better.

**Comment by b4n** [comment]
@philiprbrenan I think your proposed behavior would be too specific compared to the complexity it would require (see @codebrainz remark).  Also, tabs align fine (for me at least) and are a lot more generic, so I'd rather just suggest using them in such situations.

**Comment by philiprbrenan** [comment]
I have just tried using tabs to line the columns up on Geany (built on or
after 2015-07-13) on Ubuntu using Monospace Font and while the positioning
is close, it is not perfect. Please see the attached.

On Fri, Aug 21, 2015 at 9:12 PM, Colomban Wendling <notifications@github.com

**Comment by b4n** [comment]
@philiprbrenan I'm afraid the attachment didn't make it, GitHub probably filtered it out
