### ISSUE TITLE
[Feature Request] ColdFusion syntax highlighting

### ISSUE THREAD

**Issue by thdoan** [geany/geany#615]
Believe it or not, ColdFusion (CF) is still being used, even in the enterprise (see [Mach-II Framework](https://github.com/Mach-II/Mach-II-Framework/wiki) and [Railo](https://github.com/getrailo/railo/wiki)). Three of the most popular code editors today already have ColdFusion support ([Ace](http://ace.c9.io/#nav=about), [Notepad++](https://bitbucket.org/bbluemel/nppcoldfusion/wiki/Home), [Sublime Text](http://blog.bittersweetryan.com/2012/02/sublimetext-2-now-has-official.html)). It would be nice for Geany to add syntax highlighting support for ColdFusion as well. Here's a high-level summary of the language:

  - CF files can have a `.cfm` or `.cfc` extension
  - CF files can have a mixture of CF, HTML/CSS, and JavaScript code
  - CF tags look like HTML tags, but start with "cf" (e.g., `<cfif><cfelse></cfif>`); for a complete list of tags, refer to the [Tag Summary](https://wikidocs.adobe.com/wiki/display/coldfusionen/Tag+summary)
  - The code inside a `<cfscript>` tag resembles JavaScript, so it can be highlighted using the JavaScript lexer (see [CFSCRIPT ColdFusion Cheat Sheet](http://www.petefreitag.com/cheatsheets/coldfusion/cfscript/))
  - CF variables can be embedded in HTML code using the hash notation if the HTML code is inside the `<cfoutput>` tag (e.g., `<cfoutput><h1>#pageTitle#</h1></cfoutput>`)
  - If the hash character is used inside a `<cfoutput>` tag, then it has to be escaped with another hash (e.g., `<cfoutput><script>var el = document.getElementById('##some-div');</script></cfoutput>`)

**Comment by elextr** [comment]
You could try making a custom filetype based on html, see the manual for details.

**Comment by thdoan** [comment]
Thanks, I'll look into it.
