### ISSUE TITLE
Window re-positioning when opening additional files

### ISSUE THREAD

**Issue by psweber** [geany/geany#616]
geany 1.23.1 (built on May 19 2013 with GTK 2.24.18, GLib 2.37.0)
on Ubuntu 14 LTS, two screens, multiple workspaces

I open a terminal on workspace A, issue 'geany fileOne &', and maximize geany on screen 2.
I open a terminal on workspace B, issue 'geany fileTwo &'.

This opens fileTwo in the former instance of geany, but moves it from screen 2 on workspace A to screen 1 on workspace A.
geany is not relocated if it is not maximized.

Might be related to http://sourceforge.net/p/geany/bugs/1104/

**Comment by elextr** [comment]
Geany has no knowledge of workspaces or screens, so I doubt it can move itself between screens, it only moves itself once when it starts.  More likely the problem is somewhere in your window manager that is moving geany  for some reason.

**Comment by elextr** [comment]
PS SF bug 1104 is about moving when geany is closed and re-opened, not moving when still open.

**Comment by elextr** [comment]
@psweber does this still happen with 1.25, and if it does, what window manager are you using?
