### ISSUE TITLE
File>Properties menu item not available in keybindings

### ISSUE THREAD

**Issue by criptych** [geany/geany#622]
There is no option to set a keyboard shortcut for File>Properties.

This wouldn't normally be much of a problem for me, except for a couple of factors that combine to make it frustrating to quickly view file properties:
 * "Properties" and "Print" both share the accelerator character `P`.
 * Geany (or perhaps GTK?) somehow keeps track of the last menu item selected(?); so the first time I hit Alt+F, P the Properties dialog opens, but the next time the Print dialog opens instead, and so on.

**Comment by elextr** [comment]
On 23 August 2015 at 05:48, criptych <notifications@github.com> wrote:

> There is no option to set a keyboard shortcut for File>Properties.
>

​Not sure why.​



> This wouldn't normally be much of a problem for me, except for a couple of
> factors that combine to make it frustrating to quickly view file properties:
>
>    - "Properties" and "Print" both share the accelerator character P.
>
>
​And astonishingly all the other chars of both print and properties are
already used elsewhere in the menu.​

And things like S and O are standard and we wouldn't want to change those.



>
>    - Geany (or perhaps GTK?) somehow keeps track of the last menu item
>    selected(?); so the first time I hit Alt+F, P the Properties dialog opens,
>    but the next time the Print dialog opens instead, and so on.
>
>
​Thats GTK, Geany only gets the menu activated​, it never sees the chars
typed.

**Comment by criptych** [comment]
> ​Not sure why.​

Nor I.  You can do so for (nearly?) all the others.  This discrepancy is why I filed it as is; there are probably other ways to resolve the situation I described, but for one thing, changing any accelerator keys would likely require changing several of them.
