### ISSUE TITLE
In-cut margin

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#627]
![margin1](https://cloud.githubusercontent.com/assets/7548378/9477544/03fcaeae-4b6b-11e5-822e-a6819aa8c426.png)

May I draw your attention to  the in-cut margin on line 223 at column 80 after alignment with tabs preceding the # comment ?

**Comment by elextr** [comment]
Please provide version of Geany, platform, version of GTK.

**Comment by philiprbrenan** [comment]
Geany: (built on or after 2015-07-13)
3.10.8-0ubuntu1.6


Thanks,

Phil

Philip R Brenan

**Comment by elextr** [comment]
> Geany: (built on or after 2015-07-13)
> 3.10.8-0ubuntu1.6

I assume therefore the platform is some sort of ubuntu?

Note please always post this information on all issues, different people may look at them, and anyway even those who have looked at your previous problems shouldn't have to remember or go look it up.

**Comment by philiprbrenan** [comment]
Ubuntu 14.04.3 LTS

The thing that held me back for years from swapping from Windows to Ubuntu
was the lack of an editor that I enjoyed using. And then I met Geany!

Thanks,

Phil

Philip R Brenan

**Comment by codebrainz** [comment]
Did you change the colour scheme to make spaces invisible? All I see are the markers for tabs, but there's a big spot of no tabs before the tabs at the end of those lines. Have you tried using only tabs and not mixing with spaces?

**Comment by codebrainz** [comment]
Just as a general comment, using strange Unicode glyphs like that instead of ASCII for identifiers is evil. If anyone besides you has to touch that code, and doesn't have a decent Unicode font or editor, they will hate you :)

**Comment by elextr** [comment]
@philiprbrenan I assume you are talking about the background of the comment on line 223 being offset?

Can you provide a short piece of code that exhibits the problem, and if you can try it in the [Scite](http://www.scintilla.org/SciTE.html) editor (after you figure out how to make it show background of comments) that would be good.  Basically this is almost certainly a problem in either Scintilla or the underlying layout library (pango).  Scite is the testbed for Scintilla, so if it shows there as well it definitely points to the problem.

**Comment by elextr** [comment]
Actually this is not a bug, as @codebrainz pointed out on IRC the long line background is defined by a number of characters (unlike the long line line which is a position based on the default space width).  The scintilla docs say "When drawing lines, the column sets a position in units of the width of a space character in STYLE_DEFAULT. When setting the background colour, the column is a character count (allowing for tabs) into the line."  And since you have non fixed width characters, the number of characters to get to the same position on the screen can be different, so the long line background may move.

**Comment by codebrainz** [comment]
@philiprbrenan just to be sure you understood overall issue, I made a screenshot showing. Each line starts with a single space, then contains a single unicode glyph, then `||||<` followed by a description. Notice that the first `|` (pipe) character is at the same "column" on each line (the 3rd column).

![variable_monospace](https://cloud.githubusercontent.com/assets/181177/9484290/2748b30a-4b5f-11e5-980d-168c7cde750f.png)
