### ISSUE TITLE
Uppercase

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#628]
![uppercase1](https://cloud.githubusercontent.com/assets/7548378/9481395/d55efa18-4b81-11e5-9121-33363e85e5a6.png)

Upper-case does not seem to work for some unicode characters. I used  Format, Toggle Case of Selection on: $𝘅, $𝕩 which I hoped would be transformed to: $𝗫, $𝕏

**Comment by elextr** [comment]
I'm afraid you will have to discuss that with the Unicode consortium.  Unicode does not define a case mapping for the bold or double struck characters, see [here](http://www.unicode.org/Public/UCD/latest/ucd/UnicodeData.txt). (hint, the last three fields are uppercase_mapping, lowercase_mapping and titlecase_mapping)

**Comment by philiprbrenan** [comment]
1D400;MATHEMATICAL BOLD CAPITAL A;Lu;0;L;<font> 0041;;;;N;;;;;
1D401;MATHEMATICAL BOLD CAPITAL B;Lu;0;L;<font> 0042;;;;N;;;;;


I see what you mean. If I created an upper-case / lower-case function  that
extended the Unicode standard to perform "obvious" case transformations
which programmers might reasonably expect (or ask for), would that be of
any use?

Thanks,

Phil

Philip R Brenan

**Comment by criptych** [comment]
Sorry if I'm a little off-topic:  the fact that some languages let you use Unicode characters is handy when you need them, but in this case wouldn't it be more practical and readable (and just as many if not fewer bytes) to differentiate similarly-named variables with an ASCII prefix, instead of obfuscating your code with Unicode lookalikes?

**Comment by elextr** [comment]
It would probably be best if you put such a non-standard mapping into a plugin so only those who want it need to load it.

**Comment by b4n** [comment]
I agree with @elextr.  If Unicode doesn't define it, I wouldn't want to add special cases, as it'll likely be wrong for someone else in some other context.  BTW, case alteration is done by Scintilla AFAIK.

But as @elextr said, a plugin could do whichever transformation it wants, and would only affect people wanting them.
