### ISSUE TITLE
Make Use of /tmp

### ISSUE THREAD

**Issue by MathManiac0** [geany/geany#632]
When I was using Geany for my python scripts, I noticed a file that was quickly created and destroyed on the Desktop.  While I don't mind this too much on normal computers, I'm running Linux on RasPi, which uses an sd card.

I propose to move that file in the /tmp folder, which is normally handled in many different flavors of linux as a tmpfs, to be used as RAM. This will increase the access to the file *and* help keep the lifetime of RasPi sd cards (or others).

**EDIT:** Version 1.24.1 on Linux.

**Comment by elextr** [comment]
What version of Geany are you running, 1.25 creates the run script in the system temporary directory.

**Comment by codebrainz** [comment]
What file is it creating? Is it when you are saving a file or running a script or some other time?

**Comment by MathManiac0** [comment]
It happens when I run the script; I believe the file is "script" w/o extensions in the same directory my script is in. I have the latest version of Geany, downloaded from the Ubuntu app store.

**Comment by elextr** [comment]
Menu->help->debug messages shows the version of Geany on the second line.  We don't control and therefore don't know what version distros provide.  But my guess is it would be an older one than 1.25.

The file is probably "geany_run_script" and on 1.25 that is now created in the system temp directory.

**Comment by MathManiac0** [comment]
You're right.. 1.24.1 - Just one update behind..
But how come `apt-get` keeps telling me it's already the newest version?

**Comment by codebrainz** [comment]
@MathManiac0 most likely you're using an old distribution which doesn't have the latest version in its package repositories, or you just forgot to run `apt-get update`.

**Comment by elextr** [comment]
Ubuntu releases on a cycle, if our release happens to fall at a bad time in the cycle it won't get into Ubuntu for up to a year.  And for stable releases, never it seems.

**Comment by MathManiac0** [comment]
@codebrainz I've run that before, as well as explicitly stating it.

Maybe I'm just out of luck for that update. I assume it's the most recent?

**Comment by elextr** [comment]
@MathManiac0 forgot to mention there is a PPA [here](https://launchpad.net/~geany-dev/+archive/ubuntu/ppa) which is usually up to date for both Geany and plugins.

**Comment by MathManiac0** [comment]
I'd rather not use untrusted/unsupported packages...
I'll stick to 1.24.1 until Ubuntu supports 1.25.x

**Comment by codebrainz** [comment]
@MathManiac0 you could also upgrade your Ubuntu to a version that has 1.25 in its repos, otherwise you could be waiting a long time (ex. if it's not ever backported). Another option is to run your scripts in the builtin terminal and disable all that temp. script stuff.

 - [x] Prefs->Terminal->Execute Programs in VTE
 - [x] Prefs->Terminal->Don't Use Run Script

I personally find it much more convenient when it doesn't popup extra windows or make me press a key each time it's executed.

**Comment by MathManiac0** [comment]
I've just downloaded the image a couple days ago. For the second part, I am an extreme beginner to Linux, so please excuse me on what you mean with the tmp scripts.

Finally, for clarification (just in case), I use Ubuntu Mate designed for Raspberry Pi.

**Comment by codebrainz** [comment]
@MathManiac0 the script it's creating, which should go in the `/tmp` directory, is a little wrapper script that runs your script for you, so when your program/script exits, the window stays open and you can see the output. If you use the settings I mentioned, it will run your script in the terminal (VTE) embedded in Geany at the bottom and you don't need that wrapper script, so it won't cause issues wearing out your SD card or whatever.

**Comment by elextr** [comment]
@MathManiac0 well, the PPA maintainer is also one of the maintainers for the official packages, the PPA is because official package updates are so slow, and for Ubuntu LTS versions, basically non-existent.
