### ISSUE TITLE
[feature request] less noisy history for terminal following current file

### ISSUE THREAD

**Issue by donjan** [geany/geany#650]
The "Follow path of the current file" feature is useful, but floods the global bash history with "cd ..." entries. bash and most bash-like terminals will not add a command to the history if an additional whitespace is prepended.
I suggest adding a whitespace in front of "cd ..." (-> " cd ..."), or offering a checkbox to do so, as to reduce the history noise.

**Comment by elextr** [comment]
The space only works if `HISTCONTROL` is set to `ignorespace`.  Instead of setting that you could set `ignoredup` or `erasedup`, see [here](http://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html#index-HISTCONTROL)

**Comment by donjan** [comment]
You're right, it's not the built-in behaviour. But bash on Ubuntu defaults to `ignoreboth` (setting `ignoredups:ignorespace`), which is the reason for opening this issue.
Setting `erasedups` globally is questionable, as you remove lines from any previous and possibly unrelated history chain, which gets confusing if you want to replicate it (especially in a non-Geany context).
I don't see how to set `erasedups` only for the Geany VTE (probably not desirable also in a Geany context): matching a `env` variable in the bash rc doesn't seem very reliable. Diffing `env` for the Geany VTE and a standard interactive session for example gives `VTE_VERSION` only for the latter on this particular machine, and may have side effects in environments set by other programs.
So my feature request stands as in the OP.

**Comment by elextr** [comment]
And Mint 17.2 has no HISTCONTROL set so its certainly not universal.

Setting HISTCONTROL just for the Geany shell won't affect any other shells ... until the history is saved, and then it always was "last closed wins", or at least goes on the end if you are catenating history.  So it was never very reliable which gets saved unless you are more controlled in your logouts/shutdowns than I am.

Since the extra space shouldn't have any negative effects that I know of, if you made a PR with the change it would probably be accepted.

**Comment by b4n** [comment]
http://www.geany.org/manual/#various-preferences, pref `send_cmd_prefix`.
For some reason it seems not to be shown in the Various page, but you can edit the config file manually if you want until this gets fixed.

**Comment by b4n** [comment]
> For some reason it seems not to be shown in the Various page, but you can edit the config file manually if you want until this gets fixed.

Opened #651 with a possible fix.

**Comment by donjan** [comment]
I agree that `send_cmd_prefix` would be the right way to do this, but Geany strips any leading whitespace from the value when exiting (trailing whitespace is preserved) and prevents what I'm trying to achieve.
`send_cmd_prefix= ␣ls␣&&␣␣` (or any number of leading/trailing whitespaces) turns to
`send_cmd_prefix=ls␣&&␣␣`

**Comment by elextr** [comment]
Thats normal keyfile behaviour, any whitespace between = and the value is removed.  Use the \s escape for leading spaces.

**Comment by donjan** [comment]
Spot on, thanks!
