### ISSUE TITLE
Trailing Spaces in Filenames

### ISSUE THREAD

**Issue by friggstad** [geany/geany#657]
If I enter the filename with a trailing space (such as "mycode.cpp "), then Geany will create a file with the trailing space. Should the trailing spaces not be trimmed?

**Comment by b4n** [comment]
I don't think so, no.  It's your right to create a file with whichever name you like, including with trailing spaces.

**Comment by frlan** [comment]
I could think about a warning maybe. But not sure whether it's really useful
