### ISSUE TITLE
Symbols categories in Sidebar for Fortran

### ISSUE THREAD

**Issue by taradrop** [geany/geany#667]
It would be a nice option to have that one could see types/clases/variables and functions/procedures e.g. in separate tree nodes. At least, many people probably use Symbols list for fast navigation between the procedures, functions, methods etc. and rarely jump to types, variables declarations (especially, since that can be often done easily with "Go to Tag definition" or simply Ctrl+T). For instance, it must be a usual thing for one to have many global module variables in Fortran and few subroutines/function that would be much easily jumped between with the above option (while now you should scroll a lot to get to those yellow icons)). Thank you very much for making super cool IDE!:)

**Comment by elextr** [comment]
It is probably language dependent and is determined by the symbol parser, for example for C/C++ the symbols are already divided into functions, structs, variables, macros etc.

**Comment by taradrop** [comment]
Thanks! Indeed, I have just compared with C source and symbols for it organized much better (despite the note "Many improvements to the Fortran tag parser" in 1.24 :). Can one edit some config file (e.g. filetypes.fortran) to change the Fortran parser behavior?

**Comment by elextr** [comment]
> Can one edit some config file (e.g. filetypes.fortran) to change the Fortran parser behavior?

No, its set by the parser code (which comes from the ctags project) written in C.

**Comment by taradrop** [comment]
Update: It seems that the issue of symbols splitting into different categories in Fortran has to do with the basic units parsing, i.e. such as programs and modules. Subprograms/types/variables that are inside them are not split. While one can still write the code outside basic units structures in separate files (symbols are displayed appropriately and categorically then), that is not the best idea (esp. for big programs). Anyways, this issue is probably of low importance due to Fortran popularity.

**Comment by elextr** [comment]
Same thing happens with C++ namespaces, I will close as its unlikely that we can change the way Ctags operates.

**Comment by b4n** [comment]
@elextr it's not CTags'f fault, it's Geany that builds the tree.  We could very well not build a tree and only list symbols flat-out just as if they didn't have a parent/named scope.  It would require some code, but it's totally doable, and if it's something people want might be done at some point.

PS: funnily enough I spent some time improving parsers so they report the necessary info so we can show a tree for more languages, heh :)

**Comment by elextr** [comment]
@b4n, ok, I thought tagmanager structured things in namespaces etc.  But you are right it is possible to re-arrange anything with a mere matter of some programming :)
