### ISSUE TITLE
Waf: Enable C99 support

### ISSUE THREAD

**Issue by b4n** [geany/geany#679]
Now Geany [uses](https://github.com/geany/geany/commit/131b608d5b430df6bb960ecdd63611cb5cda4be8) [C99](https://github.com/geany/geany/commit/ef331759b01a415ba4d09b4940aa052f9ceedf7c), we need Waf to check and enable it.  We currently get build errors with Waf because of this: http://nightly.geany.org/misc/build_gtk224_geany_stderr.log

This was done for Geany-Plugins in https://github.com/geany/geany-plugins/commit/cd59d3877ed2448e92b6c1ae18a7a2baace196b6

**Comment by eht16** [comment]
Hmmm, using the referenced G-P code here is easy enough.
However, I'm wondering what the plans are regarding dropping Waf for the next release, as @kugel- is constantly demanding (https://github.com/geany/geany/pull/524#issuecomment-133769047).

I'm getting tired of judging for Waf and don't mind to drop support for it.
My only concern are the Windows builds. If anyone wants to continue providing the Windows releases in an adequate quality, then let's drop Waf now.
If there are doubts about this, then we maybe should keep it. I personally cannot guarantee providing release-quality Windows builds using MSYS2.

**Comment by codebrainz** [comment]
> Hmmm, using the referenced G-P code here is easy enough.

Even that is overkill, we could probably just stick a `-std=c99` into the `CFLAGS` and nobody would ever notice. AFAIK all the compilers we support or care about support that (gcc, clang, intel, even watcom and others). MSVC notoriously doesn't support C99 anyway (at least until recently, somewhat), but we don't support that anyway, really, and the referenced code doesn't either, AFAICT.

> My only concern are the Windows builds. If anyone wants to continue providing the Windows releases in an adequate quality, then let's drop Waf now.

How much of it is Waf-specific? Is it the case that if the Autotools build system could generate nice win32 binaries (geany.exe+libgeany.dll, with resources compiled-in, etc), that you could use most of your release process still, or is a lot of it automated by Waf scripting?

It's a pain having multiple build systems sometimes, but IMO quality win32 releases are much more important.

**Comment by kugel-** [comment]
MSYS2 builds are just as high quality has waf ones.

**Comment by codebrainz** [comment]
> MSYS2 builds are just as high quality has waf ones.

what is this in reference to? and what MSYS2 builds?

**Comment by kugel-** [comment]
I refer to the MSYS2 builds I produced and tested.

As a bonus MSYS2 produces fine GTK3 builds as well.

**Comment by eht16** [comment]
My concerns are not only about building the code itself, getting the code compiled into geany.exe and libgeany.dll is easy enough, with autotools, Waf and even hand-written Makefiles.
The fun begins with the stuff around, basically the 'make install' part with all those Windows specials, renaming text files (README, etc.) to *.txt , signing binaries, creating the GTK runtime bundle and last but not least the installer.

If @kugel- can guarantee all this for Geany and Geany-Plugins in the same or better quality than before, then I'd be fine to drop Waf immediately. But if not, we first need to sort remaining problems out.

**Comment by kugel-** [comment]
Heh, now you try to pass the responsibility to me :-) IIRC you wanted to have a look at msys and if/how it can replace waf for win32 builds.

**Comment by eht16** [comment]
To some extend, yes.
The next release is about in four weeks. I, for myself, probably will not be able to port the Windows builds to MSYS2 including plugins in that time completely.

Maybe I said I will have a look, if so, I didn't :(. Did you continue working on the bundle?

In case we won't drop Waf for 1.26, I guess we should declare dropping Waf and finishing MSYS2 support for Geany and plugins as a goal for 1.27 to finally get it done.

**Comment by kugel-** [comment]
I'll be on vacation from 15 to 26, so I don't think I can finish that up in time (there're some higher-priority items on the list too).

**Comment by eht16** [comment]
Ok. My suggestion: let's keep Waf for one more release, 1.26 and then work hard on getting it removed by finishing the MSYS2 support, for Geany *and* plugins.

@b4n, @kugel- agree?

**Comment by b4n** [comment]
Fine with me.  I'd indeed also love to see a single build system to maintain, but I must say I don't have so much motivation (nor real knowledge) to work on Windows builds, so I won't argue anyway :]

@eht16 BTW if you want me to import the C99 thingie I can do it, too.

**Comment by kugel-** [comment]
Fine with me too.

However, MSYS2 creates fine builds today, so you can just set that up and try :-) IIRC the only challange was creating the zip with all of geany's dependencies

**Comment by eht16** [comment]
Ok cool.

@b4n yes, importing the C99 code from plugins to Geany seems fine, especially as it is needed only until we drop Waf.

**Comment by elextr** [comment]
If WAF is going to be dropped, maybe it should give a deprecated message when its run?
