### ISSUE TITLE
Spellcheck context menu - nice to have word suggestions up top

### ISSUE THREAD

**Issue by SmithWillSuffice** [geany/geany#681]
It saves a lot of time if the right click context menu on a misspelt word has the spelling suggestions right up top of the context menu (like I see right now with Firefox and SublimeText and other editors.)

**Comment by elextr** [comment]
This issue tracker is for Geany itself.  Spellcheck is a plugin, part of the geany-plugins collection which has its own issue tracker [here](https://github.com/geany/geany-plugins/issues) and you should request the feature there.
