### ISSUE TITLE
Geany does not work with network drives or a network drive mapped to a local folder

### ISSUE THREAD

**Issue by mazsihej** [geany/geany#689]
Geany does not work with network drives or a network drive mapped to a local folder.
I have my codes on a network drive. The drive is mounted in Windows10 as Z:\...
When I try to run/build, I am getting the error "Failed to change the working directory to "Z:\...."
I tried to create a symbolic link in Windows, mapping the drive to c:\folder with the command 
mklink /d c:\folder \\networkhost\sharename
After that I am getting a popup window saying "Runtime error !..." (screen clipping attached).
![geany error](https://cloud.githubusercontent.com/assets/12762588/10416856/38ff6434-7028-11e5-9779-1681bb500744.png)

**Comment by b4n** [comment]
Which Geany version are you using?  This kinda looks like 1.24, and 1.25 has major improvements regarding running commands under Windows, so it might fix that too.

**Comment by frlan** [comment]
I had seen some similar issues with Windows 7 and smb-Folders complete unrelated to Geany. For some reason -- i didn't investigate more at this time and don't have access to this setup anymore -- I wasn't able to run some installer or general executables from mounted device. My idea was it might be related to some issue with antivirus. To solve it I needed to copy file to local file system. Maybe worth double checking before deep digging into Geany.

**Comment by codebrainz** [comment]
Is it because of that silly Windows bug where you can't `cd` into a folder on another drive, but first have to put the drive letter by itself to switch to that drive and then `cd` into the folder?

Like:
```
C:\Whatever> cd Z:\foo
<doesn't work>
C:\Whatever> Z:
Z:\> cd foo
<works>
```

IIRC there was some code added for Windows to override the normal/shortcut-chosen working directory, maybe it needs to do something fancier?

**Comment by mazsihej** [comment]
It seems that after the update to 1.25 i can use as the working directory the mapped network drive.
