### ISSUE TITLE
blurred displaying when using windows display zoom

### ISSUE THREAD

**Issue by doom-fr** [geany/geany#692]
I have a new PC which has a 13 inch 1920x1080 display. It comes with a W10 display configuration with a zoom of 150% (recommended) for the texts and applications.

It works well for other applications but geany is now blurred. The icon as well. cf image.

Could you do something ??

![image](https://cloud.githubusercontent.com/assets/7809481/10431434/4fc2b0bc-7105-11e5-9f7c-81defb660e54.png)

**Comment by elextr** [comment]
Seems like there are no windows 10 Geany users (yet) that can confirm/help.  I am not aware of any of the developers having W10.

**Comment by doom-fr** [comment]
Ok.
Have you seen my screenshoot ?

**Comment by elextr** [comment]
Well, at least on my screen there does not seem to be much blurriness visible in the screenshot I'm afraid.  Might be more visible on others systems.

In general blurry text (I assume its text you are complaining of) is caused by anti-aliased fonts.  I don't know what fonts are used by GTK on Windows.

**Comment by frlan** [comment]
How did you do the screenshot? Maybe it depends on how the tool is grabbing imaging data as the screenshot looks like it should look like.

**Comment by doom-fr** [comment]
I just do a print screen with the dedicated key.
Here is a new print screen (part of a wqhd, with 200% w10-zoom).
Note that the text in geany is blurred, but the title of the window ("* sans titre - Geany" )
is ok. Think that window's title is powered directly by OS.

Do you see the difference ??
![image](https://cloud.githubusercontent.com/assets/7809481/10693592/866eadcc-7999-11e5-9822-2bdaf0a73fc5.png)

**Comment by codebrainz** [comment]
It sounds like "DPI Virtualization":

https://msdn.microsoft.com/en-us/library/windows/desktop/dn469266%28v=vs.85%29.aspx#dpi_virtualization_and_scaling

Specifically:

> The type of scaling that DPI virtualization uses when scaling up in size is based on pixel stretching. While this enables applications to be appropriately sized, blurriness occurs due to the stretched pixels.

**Comment by doom-fr** [comment]
@Matthew, it seems effectively to be the problem of non DPI-aware
applications.

The good news is that it is the same on windows 8 so maybee Geany project
have users/developpers to test it.

Doom.

2015-10-23 16:26 GMT+02:00 Matthew Brush <notifications@github.com>:

**Comment by acz13** [comment]
Any progress on this? Still getting this on Windows 10

**Comment by elextr** [comment]
@acz13 its not something Geany can influence I don't think, how text is drawn is defined by the GTK library.

You could try to build a GTK3 version of Geany to see if its improved with GTK3.

**Comment by ashimokawa** [comment]
@elextr 
I just built for Windows with GTK3 and it did not help. Just as blurry as the GTK2 Version

(This is just for the record, I won't invest any time for further testing, as I do not use Windows at all)

**Comment by elextr** [comment]
@ashimokawa thanks for testing, @acz13 the issue would need to be taken up with GTK.

**Comment by acz13** [comment]
GTK or GTK#?

**Comment by RT-Git** [comment]
@doom-fr This issue is a common one with Windows on HighDPI displays. Fixed it for me by right-clicking on the Geany Icon->Properties. There, go to the Compatibility Tab and select "Override High DPI Scaling behavior". And in the "Scaling performed by:" dropdown, select Application.

**Comment by doom-fr** [comment]
@RT-Git Thanks for this good solution.

D.

**Comment by ravitripathi** [comment]
@tmssngr Glad it helped. And I do agree with you, this should be handled by the application itself. There is a whole by [article](https://docs.microsoft.com/en-us/windows/desktop/hidpi/high-dpi-desktop-application-development-on-windows) microsoft dedicated to it.

**Comment by tmssngr** [comment]
I would try to use following `geany.exe.manifest`:

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
	<assemblyIdentity
		version="1.33.0.0"
		processorArchitecture="X86"
		name="Geany"
		type="win32" />
	<description>Geany is a fast and lightweight IDE</description>
	<trustInfo xmlns="urn:schemas-microsoft-com:asm.v2">
		<security>
			<requestedPrivileges>
				<requestedExecutionLevel
					level="asInvoker"
					uiAccess="false" />
			</requestedPrivileges>
		</security>
	</trustInfo>

	<asmv3:application xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
		<asmv3:windowsSettings xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">
			<dpiAware>true</dpiAware>
		</asmv3:windowsSettings>
	</asmv3:application>
</assembly>

```

**Comment by elextr** [comment]
@eht16 whatdya think?

**Comment by eht16** [comment]
Tested and it works for me on Windows 7 without a HighDPI system.
@tmssngr do you mind testing http://download.geany.org/snapshots/geany-1.34beta1_setup.exe and http://download.geany.org/snapshots/geany-plugins-1.34beta1_setup.exe? They have the suggested change incorporated. If it works as expected, we could prepare a PR for the change.

**Comment by tmssngr** [comment]
1.34beta 1 looks fine for me - except of the too small icons.

**Comment by eht16** [comment]
Cool. Would you mind creating a PR for the manifest file change?
