### ISSUE TITLE
Make custom date format accessable via snippets

### ISSUE THREAD

**Issue by frlan** [geany/geany#695]
It would be very helpful to have a way to insert custom dates via a snippet. Either using the Edit->Insert Date->Custom Date Format  or via predefining the strftime-syntax inside the snippet itself. 

Usecase:

Inserting a string like: 

    2015-10-14 17:40: operations: flow: 

without typing to much (as it is always the same beside the current timestamp) 

Currently {date} and {datetime} are based upon configuration from http://www.geany.org/manual/current/index.html#template-data 

Therefor these can be reconfigured, but would might conflict with other places the string is used.

**Comment by dmaphy** [comment]
Why don't you just run the date command via the command directive in the snippets.conf? For example I'm doing something like this when writing RPM specfiles:

```
# RPM Spec File specific shortcuts
rlog=* {command:date +"%a %b %d %Y"} %fauthor% - %cursor%%newline%- %cursor%%newline%
```

**Comment by frlan** [comment]
Well. That did the trick wasn't aware of command placeholder. Solved at least my issue.
