### ISSUE TITLE
Update screenshots on website

### ISSUE THREAD

**Issue by lc-guy** [geany/geany#696]
they date back to 2010.

**Comment by elextr** [comment]
There is work under way to replace the whole website.

**Comment by eht16** [comment]
Yeah, I will continue working on that.

Still, contributions for cool screenshots are very welcome.

**Comment by Akronix** [comment]
how/where can we upload screenshots?

**Comment by eht16** [comment]
For now, I'd say just attach them to this issue.

**Comment by Akronix** [comment]
Take a look at these cause I have geany very customized and I don't know if it's suitable to represent how geany is :stuck_out_tongue_closed_eyes:

cleared geany: ![cleared geany](https://cloud.githubusercontent.com/assets/2631430/10543789/2d40c18c-7420-11e5-9fad-7d7b194498b5.png)
powered geany: ![powered geany](https://cloud.githubusercontent.com/assets/2631430/10543788/2d40b138-7420-11e5-89a5-1f9e0d9046b5.png)
geany + split window: ![geany + split window](https://cloud.githubusercontent.com/assets/2631430/10543790/2d444d7a-7420-11e5-89d5-6dc5a637ac98.png)

**Comment by eht16** [comment]
Btw, the screenshots got updated in February 2016 on the current website.
I'd close this issue for now but will come back once the new website got ready.
