### ISSUE TITLE
Documentation for changing color scheme references submenu that does not exist

### ISSUE THREAD

**Issue by davem2** [geany/geany#699]
The help documentation included with version 1.25 states that:

> The Color schemes menu is available under the View->Editor submenu.

There is no submenu in View called Editor. The option to change color scheme is at View->Change Color Scheme.

**Comment by codebrainz** [comment]
Not only was it moved up to the top level of the menu, but it was also made into a dialog. I guess we missed this part of the documentation during a couple changes.
