### ISSUE TITLE
Autocomplete not working at all

### ISSUE THREAD

**Issue by arcmags** [geany/geany#710]
I have no autocomplete functionality at all.  This is repeated on two different machines with identical versions: geany 1.25, GTK 2.24.28, Glib 2.44.1, Xfce 4.12, Linux 4.2.3-1-ARCH

Tried with java, python, bash, and html. 

No plugins are installed and autocomplete is turned on in preferences:

![geany_prefs](https://cloud.githubusercontent.com/assets/5779507/10682827/619dfea6-7900-11e5-8875-5c5dd262212e.jpg)

Geany starts without any errors:

```
$ geany -v

Geany-INFO: Geany 1.25, en_US.UTF-8
Geany-INFO: GTK 2.24.28, GLib 2.46.1
Geany-INFO: System data dir: /usr/share/geany
Geany-INFO: User config dir: /home/magyar/.config/geany
Geany-INFO: System plugin path: /usr/lib/geany
Geany-INFO: Added filetype Cython (61).
Geany-INFO: Added filetype Clojure (62).
Geany-INFO: Added filetype CUDA (63).
Geany-INFO: Added filetype JSON (64).
Geany-INFO: Added filetype Scala (65).
Geany-INFO: Added filetype Genie (66).
Geany-INFO: Added filetype Graphviz (67).
Geany-INFO: unknown : None (UTF-8)
```

Syntax highlight works just fine:

![geany_highlighting](https://cloud.githubusercontent.com/assets/5779507/10683173/a83654a4-7904-11e5-84e5-01c15856906b.jpg)

But no autocomplete.

**Comment by elextr** [comment]
Not sure whats meant to autocomplete in bash and HTML, but Java and Python should work.

When you open a Java or Python file, do you have symbols in the symbols pane?  If so do those autocomplete (at least the names more than 3 chars long)?

The highlighting and the symbol parsing are different things, so its entirely possible one works and one does not, but at least it shows the right language is detected.
