### ISSUE TITLE
Bug with edit_gotolineendvisual=End + show_line_endings=true

### ISSUE THREAD

**Issue by vossenjp** [geany/geany#712]
This has been driving me nuts for a while but I finally figured it out.  If you have:
* keybindings.conf
	* edit_gotolinestart=&lt;Alt&gt;Home
	* edit_gotolineend=&lt;Alt&gt;End
	* edit_gotolinestartvisual=Home
	* **edit_gotolineendvisual=End**
* geany.conf
	* show_line_endings=true

Then hitting `end` on the wrapped part of a long line does a _line-down_ and not an _end_.  If you **set show_line_endings=true** then `end` works as expected and desired.

I'm running Geany 1.25 from the "geany-dev" PPA on Linut Mint 17 but I'm pretty sure this bug has been present thing the whole "gotoline*visual" thing was fixed.

Steps to reproduce:
1. Set config as above
2. Create a file with long lines
3. Go to the first line of a wrapped line, hit `home` and `end` and they should stay on that line as expected
4. Go to the second (last?) line of a wrapped line, `home` should work but `end` should go to the next line instead of the end of this line
5. Set **show_line_endings=false**
6. `end` should not work as expected per the keymap.

Edit: fixed &lt;Alt&gt; markdown - codebrainz

**Comment by vossenjp** [comment]
Oh, I forgot, the show-stopper part is that on a NON-wrapped line, `end` goes to the _next line_ instead of the end when **show_line_endings=true**.  :-(

**Comment by elextr** [comment]
The behaviour is the same in Scite so this is a problem in the Scintilla widget we use which is a separate project (www.scintilla.org), please report it there and post the issue number here for tracking.

**Comment by vossenjp** [comment]
Done: https://sourceforge.net/p/scintilla/bugs/1772/

**Comment by b4n** [comment]
Patch submitted upstream https://sourceforge.net/p/scintilla/bugs/1772/#c336

**Comment by b4n** [comment]
BTW, simplest way to reproduce, with default configuration:

1. Open a file with more than 1 line
2. Show line endings (*View->Show Line Endings*)
3. Hit `<Alt>+Home` (default biding for *Go to End of Display Line*)

**Comment by vossenjp** [comment]
Update per https://sourceforge.net/p/scintilla/bugs/1772/:

Committed fix as [2ce775].
https://sourceforge.net/p/scintilla/code/ci/2ce775c433b4910f2fde53c4b5d89bb16b45e3eb/

Related
Commit: [2ce775]
https://sourceforge.net/p/scintilla/code/ci/2ce775c433b4910f2fde53c4b5d89bb16b45e3eb/

labels: --> scintilla, selection
status: open --> open-fixed
assigned_to: Neil Hodgson
