### ISSUE TITLE
[API request] Inconsistent statusbar when focus is on splitwindow editor.

### ISSUE THREAD

**Issue by Akronix** [geany/geany#720]
Hello.

When someone is using splitwindow plugin and the splitwindow editor has the focus, the status bar still shows the info about the document opened in the main editor. 

We've have talked about this on the mailing list. I was trying to fix this but I need [ui_update_statusbar](https://github.com/geany/geany/blob/master/src/ui_utils.h#L277) to be added to the API so that it is accessible from plugins.

I'll try to add it on my local clone to see if it works and, if so, I'll ellaborate a PR for fixing this.

**Comment by b4n** [comment]
I'm not quite sure adding API to fix the statusbar makes much sense, given all the (IMO, more important) issues splitwindow currently has (basically no action work there, but plain typing).

**Comment by elextr** [comment]
Closed by #724
