### ISSUE TITLE
Geany does not listen to certain auto text replacements (typertask)

### ISSUE THREAD

**Issue by esophagus-now** [geany/geany#725]
This is a weird one; and it might not even be a bug (that is, this behaviour might actually be on purpose).

I am using typerTask, a neat little program for automatic text replacements. It works like this: you tell it text to look out for, and then it will automatically replace it with something. For example:

`/for=for (i = 0; i < ; i++){left}{left}{left}{left}{left}{left}`

This would listen for `/for`, and when it finds it, it replaces is with the string you see there, and "hits the left key" in order to put your cursor where you would be typing the upper bound of this for loop. 

Problem is, for some reason, geany refuses to admit any of these characters:
`[]<>{}`
I know this isn't a coincidence, but it's still strange and I would like to be able to use typerTask with geany.

**Comment by elextr** [comment]
> Problem is, for some reason, geany refuses to admit any of these characters:
[]<>{}

Where does Geany refuse to accept these characters?

**Comment by esophagus-now** [comment]
Everywhere in the program where it accepts text. (Including build configuration, configuration menus, and, of course, in the main editor window.

**Comment by elextr** [comment]
I'm sorry I still don't understand what you mean.   Are you saying you can't type any of `[]<>{}` into the Geany edit window?  

If so try it without the typing program you are using.  If it works then it is more likely that the typing program you are using is causing the problem since it is clearly intercepting the keystrokes.  It may not be passing them to Geany.

**Comment by esophagus-now** [comment]
My apologies. It is just the text replacement program that exhibits this behaviour. Just to be sure we understand each other:

1. The program (typerTask) listens for certain patterns, and replaces them with other ones.
2. Typertask functions correctly (such as in notepad) except for in geany, where geany will not listen to the characters `[]<>{}`.
3. Geany works fine when I type into it normally.

I hope this elucidates the situation. Thank you for your time

**Comment by elextr** [comment]
Your typing program is a proprietary program, we have no visibility of what it does.  All of Geany source code and the source code of the Glib/GTK libraries that do keyboard IO are open source.  You will have to ask the developers of the typing program to identify the problem and either fix their program or submit appropriate changes to Geany or those libraries. Sorry we can't help.

**Comment by elextr** [comment]
I should add that you can of course use the Geany [snippets feature](http://www.geany.org/manual/current/index.html#user-definable-snippets) to provide a similar capability within Geany, you don't need the external program.
