### ISSUE TITLE
Install instructions incomplete

### ISSUE THREAD

**Issue by J-Dunn** [geany/geany#747]
I just did a git clone of geany. I read INSTALL for instructions: 

```
The simplest way to compile this package is:

  1. `cd' to the directory containing the package's source code and type
     `./configure' to configure the package for your system.  If you're
     using `csh' on an old version of System V, you might need to type
     `sh ./configure' instead to prevent `csh' from trying to execute
     `configure' itself.
```

 ./configure: No such file or directory

It seems that I need to run autogen.sh first. This should not need to be guessed or known from experience elsewhere. 

Also: 

./configure  --help 
```
  --enable-html-docs      generate HTML documentation using rst2html
                          [default=auto]
```

The auto fn does not seem to work since this causes a configure error and make files are not produced.
```
configure: error: Documentation enabled but rst2html not found.
You can explicitly disable building of the HTML manual with --disable-html-docs,
but you then may not have a local copy of the HTML manual.
```

**Comment by elextr** [comment]
The problem is that the `INSTALL` and `README` are actually included in the tarballs, which do include `configure`.  As `README` is also visible on github, it probably needs both a section on building from git and building from tarball.

**Comment by J-Dunn** [comment]
Since both README and INSTALL are part of the git archive, either one or both should include instructions for building the code on github. The current tree does not actually contain instructions on how to build it.  It seems that we are agreed that it should.

**Comment by elextr** [comment]
> It seems that we are agreed that it should.

Indeed, pull requests are welcome.

**Comment by J-Dunn** [comment]
I'm new to geany repository. Am I really the best person to write the doc? 

Those who wrote the code or who maintain the project could probably add whatever modifications are required in about 2 minutes. Less time than it would take to vet and/or correct whatever I may submit. 

I've found two flaws and reported them. That is probably the most effective contribution I can make.

Can you comment on the   --enable-html-docs  issue?  It claims to be "auto" but actually causes a fatal error in configure if the underlying package is not present

**Comment by elextr** [comment]
> I'm new to geany repository. Am I really the best person to write the doc?

Thats fine it doesn't have to be you, but the comment is an indication to people looking for something to do that this is likely to be accepted.

I am personally not very autotools literate, so I left that one for someone else to comment.

**Comment by b4n** [comment]
> Can you comment on the --enable-html-docs issue? It claims to be "auto" but actually causes a fatal error in configure if the underlying package is not present

It's subtle :)  It's optional, but defaults to a hard-dependency unless we already have a copy of the HTML manual (e.g. from a source tarball).  There is a comment in the check's source explaining this (*m4/geany-docutils.m4*, *GEANY_CHECK_DOCUTILS_HTML*):
> we require rst2html by default unless we don't build from Git and already have the HTML manual built in-tree

See also 288b4f29d8a62a5cc2baa6f0ddefa6a3fe201ade

**Comment by elextr** [comment]
> There is a comment in the check's source explaining this (m4/geany-docutils.m4, GEANY_CHECK_DOCUTILS_HTML):

Of course!!! Thats where we all look for documentation ;-P

I guess this is a leftover from when the HTML was in in the VCS.

Will create an issue for after 1.26 to update HACKING to separate git build and tabball build sections so the commands and dependencies are clear(er).
