### ISSUE TITLE
Set prefix not being given to executeable

### ISSUE THREAD

**Issue by aruth2** [geany/geany#750]
Hello I am using the source code for version 1.25 with the tarball from here from here: http://www.geany.org/Download/Releases. I tried installing Geany on a system where I do not have root access. It appears that the proper way to do this is to use the --prefix option during configuration:

    $ ./configure --prefix=/home/username/Geany

I proceeded to make and install after this:

    $ make
    $ make install

The files were successfully copied to the correct destination: /home/username/Geany. However, when I try to run the executable, it tried searching for some files in root directories:

    $ /home/username/Geany/bin/geany 
    Geany-ERROR **: Cannot create user-interface: Failed to open file      '/usr/local/share/geany/geany.glade': No such file or directory

Using the --print-prefix option indicates what the error is:

    $ /home/username/Geany/bin/geany --print-prefix
    /usr/local
    /usr/local/share
    /usr/local/lib
    /usr/local/share/locale

 So, the use of --prefix is working correctly in the ./configure, make, and make install commands, however, the executable /bin/geany does not receive the correct prefix. The prefix that the executable uses should be set up correctly during the ./configure call.

**Comment by elextr** [comment]
I assume you are using the 1.25 source tarball from [here](http://www.geany.org/Download/Releases) and I assume you typed `configure` not `configuration`.

That WFM.

Needs more info on exactly what you did.

**Comment by aruth2** [comment]
That's right on both accounts, I'll edit that info in. What more information do you need?

**Comment by elextr** [comment]
I don't know, it WFM.  So there is either something very slightly different in what you did from what you think you did or there is a problem with one of the tools on your system.

Maybe try it again

    mkdir /someabsolutepath; extract the tarball to /someabsolutepath; cd /someabsolutepath/geany-1.25; ./configure --prefix=/someabsolutepath; make install; ../bin/geany --print-prefix

**Comment by aruth2** [comment]
Completely removing the directory and restarting from the tarball worked. I guess doing ./configure and make without the --prefix option which I did during my first attempt prevented it from regenerating files later on. Thanks a lot!!!

**Comment by elextr** [comment]
Ahh, see you did something you didn't mention!!!  To get make to re-do stuff after a config change you need to `make clean; make install`
