### ISSUE TITLE
HACKING needs build docs update.

### ISSUE THREAD

**Issue by elextr** [geany/geany#756]
Since things like the HTML and configure have been removed from VCS the difference between building from GIT and the extra dependencies that needs and building from tarball is getting bigger.  Needs to be made clear.

Or maybe README says how to build from git (since its visible on the github front page) and HACKING or INSTALL says how to build from tarball.  Thoughts?

**Comment by codebrainz** [comment]
I don't think the generated `configure` script was ever in VCS, was it?

The list of dependencies hasn't really changed, the same tools are required to generate the docs AFAIK, only there were `configure` options added to enable/disable building the documentation (documented in the most obvious place `configure --help`), whereas before it had explicit `make` rules to re-generate the docs (IIRC). In both cases building the docs is optional and uses the same tools, unless I missed something.

**Comment by elextr** [comment]
Whatever the history the docs need updating.

**Comment by codebrainz** [comment]
FWIW, there is a little documentation about this [on the website](http://www.geany.org/Download/Git).

Not that I'm against improving the docs in any way, but just as a general observation, some stuff like knowing when using VCS development tree that more files may need to be generated (bootstrap), or that using Autotools to generate a build system requires Autotools, or running configuration script and having it tell you which dependencies needs installing, and then installing them, is by and large not unique to Geany. Someone should write a generic "building development version of open source software" guide :)

**Comment by elextr** [comment]
> Someone should write a generic "building development version of open source software" guide :)

Your offer is accepted :grinning:
