### ISSUE TITLE
Debugger fails with "Error loading file"

### ISSUE THREAD

**Issue by johnbester** [geany/geany#757]
Linux: Ubuntu trusty (3.13.0-68-generic / i686)
Geany 1.25 (built on Jul 13 2015 with GTK 2.24.23, GLib 2.40.2)

Installing from Ubuntu repositories (geany v1.23) caused the same problem, so I tried installing from ppa:geany-dev/ppa. Problem remains. All packages starting with "geany" installed, except for geany-plugin-markdown, geany-plugin-scope.

I have tried debugging a python script, (setting debug target to .py file and .pyc) - both gave me "Error laoding file" when I press the Start button

I then tried debugging a bash script (.sh) - same problem.

Then I downloaded a sample .c source file, compiled it and tried to debug it - same problem.

Starting geany from shell in order to try to get some output or stack trace did not help much. All I got was the following: (output on console immediately after pressing "OK" on "Error loading file" dialog)

(geany:30320): GLib-CRITICAL **: g_string_free: assertion 'string != NULL' failed

(geany:30320): GLib-CRITICAL **: g_string_free: assertion 'string != NULL' failed

(geany:30320): GLib-CRITICAL **: g_string_free: assertion 'string != NULL' failed

(geany:30320): GLib-CRITICAL **: g_string_free: assertion 'string != NULL' failed

(geany:30320): GLib-CRITICAL **: g_string_free: assertion 'string != NULL' failed

(geany:30320): GLib-CRITICAL **: g_string_free: assertion 'string != NULL' failed

(geany:30320): GLib-CRITICAL **: g_string_free: assertion 'string != NULL' failed

(geany:30320): GLib-CRITICAL **: g_string_free: assertion 'string != NULL' failed

(geany:30320): GLib-CRITICAL **: g_string_free: assertion 'string != NULL' failed

(geany:30320): GLib-CRITICAL **: g_string_free: assertion 'string != NULL' failed

(geany:30320): GLib-CRITICAL **: g_hash_table_destroy: assertion 'hash_table != NULL' failed

Is there any way I can get a decent stack trace of what caused the "Error loading file"?

**Comment by elextr** [comment]
This repository is for issues with Geany, both debugger and scope are part of the plugins project not Geany, please re-raise the issue there.

Just FYI debugger works for me for C code (did you set the executable in the target tab?) and I can run the program and set breakpoints by clicking in the edit window, albeit with the same messages as you got.  I don't think debugger supports any other languages besides C/C++ and sadly its unmaintained.

Have never used scope.

**Comment by johnbester** [comment]
Thanks for the quick response. Where do I log a bug for the debugger
    plugin?
    
    On 2015-11-13 13:24, elextr wrote:
    
    
      This repository is for issues with Geany, both debugger and
        scope are part of the plugins project not Geany, please re-raise
        the issue there.
      Just FYI debugger works for me for C code (did you set the
        executable in the target tab?) and I can run the program and set
        breakpoints by clicking in the edit window, albeit with the same
        messages as you got. I don't think debugger supports any other
        languages besides C/C++ and sadly its unmaintained.
      Have never used scope.
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by elextr** [comment]
Note that each plugin in the plugins collection are individually developed and maintained.  Each maintainer can specify how they wish problems reported.

Good news is that there does in fact appear to be a new maintainer for debugger, so just report it to them as specified in http://plugins.geany.org/debugger.html.

**Comment by kugel-** [comment]
@elextr Agree, it's invalid, why don't you just close this?
