### ISSUE TITLE
Inconsistent shift right on tab

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#761]
(1)
![shift0](https://cloud.githubusercontent.com/assets/7548378/11172311/271612fe-8bfd-11e5-9f28-8ffa324ed3b7.png)
(2)
![shift1](https://cloud.githubusercontent.com/assets/7548378/11172312/2719b92c-8bfd-11e5-88ab-a07804f58000.png)
(3)
![shift2](https://cloud.githubusercontent.com/assets/7548378/11172313/271e159e-8bfd-11e5-8800-e8faca63a4fc.png)

I find the shift right feature of <b>Geany</b> very useful. In (1) I selected the two lines of code on lines 2 and 3 and then pressed the <b>tab</b> key to get (2) just as expected.  However when I use a rectangular selection as on lines 4 and 5 and then push the  <b>tab</b> key to shift the selected text, I  get (3) which is very different.  Please consider making the rectangular select behave in a way that is similar to the normal selection when shifted by the <b>tab</b> key.  Thanks!

**Comment by elextr** [comment]
This is working as expected.  The tab key is not a "shift right" key, it is an insert.  It inserts sufficient whitespace so the first non-whitespace after the selection moves to the next tab stop.  Note that this is a normal insert, ie any selection is replaced by the inserted text.  This is normal behaviour for any insert, by typing, by paste, by the tab key.

Simply select a vertical line before the text you want to move, ie where you want the insert, don't select the text you want to move or it will be replaced.
