### ISSUE TITLE
error during compilation - spawn.c

### ISSUE THREAD

**Issue by swattor** [geany/geany#764]
When compiling release geany-1.26 I encounter the following error:

spawn.c: In function 'spawn_async_with_pipes':
spawn.c:625: error: 'G_SPAWN_ERROR_TOO_BIG' undeclared (first use in this function)
spawn.c:625: error: (Each undeclared identifier is reported only once
spawn.c:625: error: for each function it appears in.)
make[2]: *** [libgeany_la-spawn.lo] Error 1

**Comment by frlan** [comment]
@swattor  Can you tell something about your system?

**Comment by swattor** [comment]
It's an x86_64 Centos 6.7 system.

**Comment by codebrainz** [comment]
On 2015-11-19 3:50 AM, swattor wrote:
> When compiling release geany-1.26 I encounter the following error:
>
> spawn.c: In function 'spawn_async_with_pipes':
> spawn.c:625: error: 'G_SPAWN_ERROR_TOO_BIG' undeclared (first use in this function)
> spawn.c:625: error: (Each undeclared identifier is reported only once
> spawn.c:625: error: for each function it appears in.)
> make[2]: *** [libgeany_la-spawn.lo] Error 1
>

What if you change that symbol to `G_SPAWN_ERROR_2BIG`? The alias shown 
in your error message was added in March 2012, so maybe your GLib is too 
old.

Cheers,
Matthew Brush

**Comment by swattor** [comment]
Thanks, that seemed to work. Is this a bug as such or just a quirk of me trying to use such an old system?

**Comment by codebrainz** [comment]
A little of both. The missing symbol was added in 2012, so probably nobody but a centos user would notice :)  But also GLib doesn't always document when stuff was added to their API, so if the symbol is newer than our lowest supported GLib version, probably the developer didn't even notice since it's not mentioned in the docs what version added that symbol.

**Comment by codebrainz** [comment]
@zhekov is that symbol too new?

**Comment by elextr** [comment]
On 20 November 2015 at 12:44, Matthew Brush <notifications@github.com>
wrote:

> @zhekov <https://github.com/zhekov> is that symbol too new?
>

​To save him looking, yes its too new, ​

​we test for glib 2.28 and its not in that.

Should be able to #ifndef #define it in compat easily though.

Cheers
Lex

PS TFL to look what version it *did* come in
​

**Comment by swattor** [comment]
Looks like I have glib 1.2.10

**Comment by elextr** [comment]
On 20 November 2015 at 19:42, swattor <notifications@github.com> wrote:

> Looks like I have glib 1.2.10
>

​Ahhh, it will have to be above (or equal) 2.28​ or Geany would not have
configured.

​Cheers
Lex​

**Comment by elextr** [comment]
On 20 November 2015 at 20:37, Lex Trotman <elextr@gmail.com> wrote:

>
>
> On 20 November 2015 at 19:42, swattor <notifications@github.com> wrote:
>
>> Looks like I have glib 1.2.10
>>
>
> ​Ahhh, it will have to be above (or equal) 2.28​ or Geany would not have
> configured.
>
> ​Cheers
> Lex​
>
>
​PS, you havn't confused with the GIR version?​

**Comment by swattor** [comment]
Oh, sorry - yes my bad. I do in fact have 2.28.8

**Comment by elextr** [comment]
On 20 November 2015 at 21:01, swattor <notifications@github.com> wrote:

> Oh, sorry - yes my bad. I do in fact have 2.28.8
>

​Well, its old, but its technically acceptable to Geany.  So its a bug.

Cheers
Lex​

**Comment by zhekov** [comment]
Must be replaced with G_SPAWN_ERROR_2BIG. That's the symbol in 2.28, and it's still supported in the current 2.47, unless G_DISABLE_DEPRECATED is specifically defined. There should be no need to check the glib version.

So, do I open a PR, or somebody will fix it?

(It would be nice if we switch Geany to protected branches. Currently, creating a PR is too clumsy.)

**Comment by elextr** [comment]
@zhekov Shhhh, don't tell @b4n, but if you open the file in github website and click on the pencil icon at the top it will let you edit it and then create a PR with the change.

**Comment by codebrainz** [comment]
@zhekov you can also use Github's tool "hub", then it's just:

```bash
$ git checkout -b whatever-topic
# hack hack hack
$ git pull-request
```

Though I think we should protect the master branch against force pushes (even if it doesn't solve the problem of difficulty making pull requests at all).

**Comment by zhekov** [comment]
@elextr 

Te-he, I have no Linux on the new machine, and can't test it... If I create the PR as you describe, will the standard compilation tests will be run on it?

@codebrainz 

My impression was that these new "protected branches" are to make some branches (master, releases) writable to the few chosen, and let anyone else create their own branches directly inside geany/geany, simplifying the PR-s. But I haven't read about this in detail...

**Comment by b4n** [comment]
How would committing on the Geany repo itself simplify creating PRs?  Creating a GitHub fork is one click, once.  Then, just add this new remote to your existing Geany clone (the "official" one) (just once, again), and do just like you'd do if you only used that one, but push your feature/pr branches to your own remote.

For example, I'd do:
```shell
(on master) $ git pull --ff--only # get new changes, as usual
(on master) $ git checkout -b my-pr-branch
(on my-pr-branch) $ # do some editing as needed
(on my-pr-branch) $ git commit -a -m "Fix something very important"
(on my-pr-branch) $ git push b4n my-pr-branch # publish my branch on my own fork
```

I guess I totally miss the point, but I fail to see how specifying the remote in the `git push` call is a cumbersome.

**Comment by elextr** [comment]
@zhekov yes PRs made with the github editor are tested by Travis.  Though that won't help in this case since the version of glib it uses is probably too new for the bug to show.

**Comment by zhekov** [comment]
What I do know as "creating a PR" is (generic terminology, not git)

Open GitHub and fork Geany into myname.
Create a branch on github myname.
Fetch geany myname from github.
Switch to branch and edit it.
Commit it.
Open github and create PR.

The details may vary a bit, for example a subsequent fork may be "ff only", but generally it should be something like that. Now we have:

1. geany master
2. myname master on gitgub
3. myname branch on github
4. myname master on the local machine
5. myname branch on the local machine

I cannot help but think that a total of 5 Geany copies are a bit too much for a simple PR. And copies 2-5 are not really related to geany master - "origin master" means myname master. Huh...

If I understood the protected branches correctly, the scheme will be:

1. geany master - protected, writable to leading devs only.
2. geany mybranch on github - writable to myname as creator.
3. geany mybranch on the local machine.

Simpler, real origin, and GitHub PR-s are be used because they are convenient, not required. Though seeing all branches may be a bit too much for the leading devs.

The procedure itself is not much shorter, but there's less room for errors, and syncing is simpler - actually nil, you always start from the current geany master.

**Comment by elextr** [comment]
As I read the protected branches they don't stop you pushing to the master
branch, they just put a few requirements on that.

You still need repo rights to create the branches in the repo.  And that
means you have push rights to the master branch (you just have to meet the
requirements).  So it would only be more convenient for those who already
have access.

Note that some of your steps below are once only, like forking on github
and some should be once only or at least rare like cloning locally.

The steps really are like b4n described.

Cheers
Lex

**Comment by b4n** [comment]
> Now we have:
> 
> 1. geany master
2. myname master on gitgub
3. myname mybranch on github
4. myname master on the local machine
5. myname mybranch on the local machine
> 
> I cannot help but think that a total of 5 Geany copies are a bit too much for a simple PR. And copies 2-5 are not really related to geany master - "origin master" means myname master. Huh...

First off, branches aren't copies, they are just a "pointer" to a particular last commit, so there's virtually no overhead in having a hundred branches.

So, yes GitHub would (probably, but maybe not, depending on how they manage forks) have a second copy of the geany repo under your account, but that's all.  By using a "myname" remote on your local "geany" clone, you don't add any overhead (but a 3-lines entry in *.git/config* to describe your remote).

> The procedure itself is not much shorter, but there's less room for errors, and syncing is simpler - actually nil, you always start from the current geany master.

Again, just add your own remote on a geany/geany clone.  your *master* branch will naturally track geany/geany@master, yet you can push any custom branches you want by a mere `git push myname mybranch`.  And as the *origin* remote (geany/geany) would be read-only, there would be no room for error either, you just couldn't do anything wrong on the real repo, and as *master* would track geany/geany@master, you couldn't even mess with your fork's master with an accidental `git push` on master.

Just clone geany/geany `git clone https://github.com/geany/geany.git geany`, and add your remote `git remote add myname https://github.com/myname/geany.git`, and enjoy a simple life.

**Comment by zhekov** [comment]
> As I read the protected branches they don't stop you pushing to the master
> branch, they just put a few requirements on that.

Indeed, the limitations are very clear... but I somehow read them as "can't have merges by outsiders". Wishful thinking.

> Note that some of your steps below are once only, like forking on github

But you need to sync instead.

> and some should be once only or at least rare like cloning locally.

Each time git gives me some unclear message, or I tried an advanced command and am unsure about my repository state. But yes, it's rare. :)

> First off, branches aren't copies, they are just a "pointer" to a particular last commit,
> so there's virtually no overhead in having a hundred branches.

I didn't mean they are physical, and haven't complained about any machine overhead. They are hard for me, to keep in my head.

> Just clone geany/geany [...]
> add your remote git remote add myname  [...] 
> and enjoy a simple life

Thank you. I will.

**Comment by zhekov** [comment]
Works. Created a simple PR #773 as test. Though the PR itself is real.
