### ISSUE TITLE
Build UI updates missing

### ISSUE THREAD

**Issue by elextr** [geany/geany#765]
A report on the ML noted that the "progress bar" is no longer displayed during builds.

The lines build.c:851-852 in 1.24.1 seem to have been removed in 1.25 with the new spawn update, or have they just been moved somewhere?

**Comment by codebrainz** [comment]
Doesn't it show a modal "please wait" dialog now? I thought I remembered that (I don't use build commands often).

**Comment by elextr** [comment]
No, nor should it, you can still do other things in Geany while a slow build is going on.
