### ISSUE TITLE
Vertical selection of tabs

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#767]
(1) <b>Ctrl + mouse click</b> jumps the to the first open file tab instead of starting a vertical select with the mouse as expected.
![select1a](https://cloud.githubusercontent.com/assets/7548378/11321782/defbf1e8-90c3-11e5-8042-b233254489f5.png)

(2) <b>Ctrl + mouse click</b> does nothing instead of starting a vertical select with the mouse or jumping to an open file tab consistent with (1)
![select1b](https://cloud.githubusercontent.com/assets/7548378/11321780/def7d306-90c3-11e5-8ef4-b62b2853b235.png)

(3) <b>Ctrl + mouse click</b> jumps the to the first open file tab instead of starting a vertical select with the mouse or jumping to a different file tab to be consistent with (1)

![select1c](https://cloud.githubusercontent.com/assets/7548378/11321781/def7ed00-90c3-11e5-8e34-60453ef0782d.png)

(4) Vertical select with <b>alt+shift+arrow keys</b> selects correctly in any column.
![select2](https://cloud.githubusercontent.com/assets/7548378/11321783/defd3e5e-90c3-11e5-8eea-971dcad22393.png)

(5)<b> Ctrl + mouse click</b> does start a vertical select with the mouse as expected as long as there is stuff in column 3 otherwise as per (1).
![select3](https://cloud.githubusercontent.com/assets/7548378/11321784/df021d20-90c3-11e5-93aa-e0c2059334ef.png)

<b>Geany</b> is, in general, very easy to learn because of the orthogonality of its command set - once I have learnt to use one action in one place, the same action works in other places in a consistent manner.  Please consider enabling </b>alt+shift</b> as an action that starts a vertical mouse select just as it does with the arrow keys to maintain this orthogonality.  <b>Thanks!</b>

**Comment by elextr** [comment]
Ctrl-click is "goto tag definition" if on a known name, "goto brace match" if on a brace, see [here](http://www.geany.org/manual/current/index.html#editor).

If it thinks the definition is in another tab it will go to that, hence the tab swap.

Rectangular selections are by ctrl-shift-click.

**Comment by b4n** [comment]
> Please consider enabling alt+shift as an action that starts a vertical mouse select just as it does with the arrow keys to maintain this orthogonality. 

Unfortunately this wouldn't really work, as almost all X11 window manager use Alt+LBM and Alt+Shift+LBM as a mean to move the window, so it basically won't work on Linux.  As @elextr said, Ctrl+Shift+LBM is the shortcut here.
