### ISSUE TITLE
two issues in xp:

### ISSUE THREAD

**Issue by aswjh** [geany/geany#770]
1.cant focus on input field.(if open an other file, it will be ok)
2.double image if click the scroll
![geany1](https://cloud.githubusercontent.com/assets/6280240/11328286/077713c6-917f-11e5-977c-52ab4c290e79.JPG)
![geany2](https://cloud.githubusercontent.com/assets/6280240/11328287/0c15cab2-917f-11e5-940c-23f4f082973a.JPG)

**Comment by elextr** [comment]
What version of Geany?

**Comment by aswjh** [comment]
1.25 and 1.26, 
1.24 is ok

**Comment by aswjh** [comment]
work well in linux and win10

**Comment by codebrainz** [comment]
I don't have an XP to test with. Works for me on Windows 10.

**Comment by eht16** [comment]
Between 1.24 and 1.25 we switched from GTK 2.18 to GTK 2.24 of the embedded GTK bundle. http://www.gtk.org/download/windows.php states that recent GTK versions depend on Windows Vista or later. However, I'm not sure whether this is also true for the now unavailable GTK 2.24 bundle.

Since it seems nobody of us developers has a Windows XP system anymore, I'm not sure how to proceed.

If the GTK 2.24 bundle simply doesn't support Windows XP any longer, we should update the website. Well, even Microsoft says Windows XP is EOL.

**Comment by elextr** [comment]
Well, since we are not going to do a custom build of GTK and dependencies to an old version, we effectively no longer support XP.

**Comment by b4n** [comment]
I have a custom build of 1.26 with GTK 2.24 on a Windows XP VM and it seems to work just fine.

I don't understand the first issue (what field is not working?  how to reproduce it if opening a file works?), and can't reproduce the second.

**Comment by b4n** [comment]
OK, I just tried to use the installed, and it misses *libwinpthread-1.dll*.  After I copied that next to Geany.exe (from my Debian's */usr/i686-w64-mingw32/lib/libwinpthread-1.dll*), it also works fine.

I find it odd I need this but other people can run it just fine though…

**Comment by elextr** [comment]
Everybody is using newer than XP versions of windows, and they include that dll?

**Comment by b4n** [comment]
I doubt it, it looks like a mingw thing…  I tried adding the plugins, and now I also miss *libgcc_s_sjlj-1.dll* for (some, at least git-changebar) plugin(s).  Again, copying it from */usr/lib/gcc/i686-w64-mingw32/4.9-win32/libgcc_s_sjlj-1.dll* worked fine.

Maybe my VM is broken in some way, or the non-gtk installer misses some stuff?

**Comment by b4n** [comment]
OK, I tried in another, cleaner XP VM, and the full installer with GTK works fine.  @eht16 I guess those 2 libs are missing from the normal installer -- well, one from the normal installer, and one from the GP one.

Still, I can't reproduce anything, looks like it works as it should.

**Comment by aswjh** [comment]
Sorry for my poor English.
I customized the toolbar, reduced the items.
problem 1(cant input any character) should be associated with that. 
problem 2 produces when dragging the scroll.

**Comment by codebrainz** [comment]
Those two libs are always required for stuff compiled with Mingw, unless compiled with `-static-libgcc` IIRC. I don't know how far back it's been that those are needed, it could be only newer mingw needs them, or maybe GTK+ (and/or Geany) used to be compiled with static GCC threading/exceptions libraries.

@aswjh what is your regional/language setting on Windows, and are you using special input methods to type into it? I think Scintilla had lots of work done to improve input methods, maybe it introduced a weird bug or something.

**Comment by aswjh** [comment]
Default language is zh_CN, using Chinese Simplified -US KeyBoard, is not special input methods.

**Comment by elextr** [comment]
> I customized the toolbar, reduced the items.
> problem 1(cant input any character) should be associated with that. 

Please always tell us exactly what you changed so we can reproduce it.

**Comment by codebrainz** [comment]
@aswjh can you try to close all Geany instances except one, then disable all plugins, then close the last Geany instance and re-start it? (or if no Geany's are started, run from Command Prompt with `geany -p`). It's possible a plugin is causing some issue.

**Comment by aswjh** [comment]
I tried, problems continue. 
![g6](https://cloud.githubusercontent.com/assets/6280240/11414046/9c5f7b7a-93e8-11e5-9531-27405f49c608.JPG)


input field becomes available after reactivating geany window.

**Comment by eht16** [comment]
> I doubt it, it looks like a mingw thing…  I tried adding the plugins, and now I also miss *libgcc_s_sjlj-1.dll* for (some, at least git-changebar) plugin(s).  Again, copying it from */usr/lib/gcc/i686-w64-mingw32/4.9-win32/libgcc_s_sjlj-1.dll* worked fine.
> 
> Maybe my VM is broken in some way, or the non-gtk installer misses some stuff?

The non-GTK installer actually misses those files. This is because I
added those files one or two releases ago to the GTK bundle folder so
they get included in the full installer.
But indeed they should be included in both installers as they are not
related to the GTK bundle but to the Geany binary itself.

**Comment by eht16** [comment]
Just for the records: here are previews/test builds of the upcoming 1.27 release which is built with the MSYS2 environment:
http://download.geany.org/snapshots/geany-1.27nightly_setup.exe
http://download.geany.org/snapshots/geany-plugins-1.27nightly_setup.exe

This might or might not help with this issue as also the GTK bundle is taken from MSYS2 and so maybe it works better with Windows XP.
Still, Windows is very very old and should be replaced.

**Comment by aswjh** [comment]
Great, 1.27 works well. Thanks.
(BTW, Using XP on virtualbox ^_^)
