### ISSUE TITLE
URL encoded filename in debug messages

### ISSUE THREAD

**Issue by codebrainz** [geany/geany#779]
On Windows if a session file in the project doesn't exist when the project is opened, a message like this shows up in the debug messages:

> Could not find file 'C%3A%5CUsers%5Cme%5CProjects%5Cfoo%5Cbar.cpp'.

Maybe it needs to be [unescaped](https://developer.gnome.org/glib/stable/glib-URI-Functions.html#g-uri-unescape-string), I didn't look at the code yet.

**Comment by elextr** [comment]
Note: happens on Linux too

**Comment by elextr** [comment]
Actually its probably a regression, because I don't think this used to happen

**Comment by J-Dunn** [comment]
This is also happening in the geany project files :   *.geany
```
[files]
current_page=4
FILE_NAME_1=0;None;0;EUTF-8;0;1;0;%2Ftmp%2Fwkg%2Fprojects%2Ffairy.geany;0;2
```

**Comment by elextr** [comment]
> FILE_NAME_1=0;None;0;EUTF-8;0;1;0;%2Ftmp%2Fwkg%2Fprojects%2Ffairy.geany;0;2

These entries are intended to be encoded and have been for some time, they are inside a config file, not a displayed name.  The issue in the OP is that this encoding has leaked to displayed filenames.

Technically all other filenames in config files probably should be encoded, but thats another issue.
