### ISSUE TITLE
More Build-menu Entries

### ISSUE THREAD

**Issue by DevynCJohnson** [geany/geany#782]
I need more build-menu entries that I can configure. I have many syntax/code checkers, lint programs, and analyzers that are specific to various programming languages. Having three filetype-specific and four non-filetype-specific build-menu entries is not enough for me.

I have read http://www.geany.org/manual/#various-preferences and http://wiki.geany.org/howtos/configurebuildmenu . I am wanting to have additional entries in the build-menu besides the default amount provided. I have tried setting "number_ft_menu_items" to "7" in geany.conf and then adding the below code to filetypes.c.

FT_03_LB=Splint
FT_03_CM=splint -I. -hints -checks "%d/%f"
FT_03_WD=

**Comment by DevynCJohnson** [comment]
This is odd. Editing the files did not work (Yes, I did close Geany so that changes can take effect). However, if I change "number_ft_menu_items" via "Edit > Preferences > Various", the changes take effect and work. Although, why would editing geany.conf not work?

**Comment by elextr** [comment]
On 30 November 2015 at 05:17, Devyn Collier Johnson <
notifications@github.com> wrote:

> This is odd. Editing the files did not work (Yes, I did close Geany so
> that changes can take effect). However, if I change "number_ft_menu_items"
> via "Edit > Preferences > Various", the changes take effect and work.
> Although, why would editing geany.conf not work?
>

​You didn't say which file you edited, but if its the standard user config
file, not a project file, ​and you edited it with Geany, then Geany will
overwrite the config file it ​when it is closed.  But changing it in the
menu writes it when its closed.

​Thats why the user config doesn't appear in the tools->configuration files
list, editing it in Geany doesn't work.​


​Cheers
Lex
​

**Comment by codebrainz** [comment]
> Although, why would editing geany.conf not work?

You might get lucky if you do `Tools->Reload Configuration` after editing and saving it.

**Comment by DevynCJohnson** [comment]
@elextr , oh, that makes sense. Thanks.

**Comment by DevynCJohnson** [comment]
99% of computer errors are ID-10-T errors.
