### ISSUE TITLE
On Windows cannot execute grep tool "grep" if target path contain non ascii folder name

### ISSUE THREAD

**Issue by NTMan** [geany/geany#784]
On Windows cannot execute grep tool "grep" if target path contain non ascii folder name

![cannot execute grep tool grep](https://cloud.githubusercontent.com/assets/200750/11464353/9d34a56a-974f-11e5-8c29-fec8e999e1c6.png)

**Comment by elextr** [comment]
What is the version of geany and what locale is geany running as (see line 2 of help->debug messages)

**Comment by NTMan** [comment]
12:18:13: Geany INFO		: Geany 1.26, Russian_Russia.1251
12:18:13: Geany INFO		: GTK 2.24.10, GLib 2.28.8

Also try:
C:\Users\mv.gavrilov>set LANG=en
C:\Users\mv.gavrilov>"c:\Program Files (x86)\Geany\Geany.lnk"
12:20:14: Geany INFO		: Geany 1.26, English_United States.1252
12:20:14: Geany INFO		: GTK 2.24.10, GLib 2.28.8

**Comment by elextr** [comment]
What does the error message shown in the status bar say?

**Comment by NTMan** [comment]
https://translate.google.com/#ru/en/%D0%9D%D0%B5%D0%B2%D0%B5%D1%80%D0%BD%D0%BE%20%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%BE%20%D0%B8%D0%BC%D1%8F%20%D0%BF%D0%B0%D0%BF%D0%BA%D0%B8

Invalid folder name

**Comment by NTMan** [comment]
You can reproduce my problem with folder "борода" from attached archive.[111.7z](https://files.zenhub.io/565c15ebdf514c1402808452)
Uploaded using [**ZenHub.io**](http://www.zenhub.io)

**Comment by eht16** [comment]
Thanks for the test archive, I could reproduce the problem and a possible fix is in #809.

**Comment by eht16** [comment]
This should be fixed now in Geany 1.29 (released today).
We merged #1301 and the Windows installer has a `grep` version from the MSYS2 project bundled which seems to work fine with non-ASCII files and paths.
