### ISSUE TITLE
Geany 1.26 is shipped with a version of grep that doesn't seem to work

### ISSUE THREAD

**Issue by Terry-euclid** [geany/geany#789]
Hi folks,

The find in file dialog generates the following error:

    c:\program files\geany\bin\grep: unrecognized option `--include=*.c'

The fix seems to be to replace the grep.exe file with the GNU version of grep.

This was OK in 1.24 as the user had to supply his own grep command and need to make sure it was OK.

Terry

Fresh install of Geany 1.26 on Microsoft Windows [Version 6.1.7601]

**Comment by Terry-euclid** [comment]
Debug Messages...

15:49:36: Geany INFO		: Geany 1.26, English_United Kingdom.1252
15:49:36: Geany INFO		: GTK 2.24.10, GLib 2.28.8
15:49:36: Geany INFO		: System data dir: C:\Program Files\Geany\data
15:49:36: Geany INFO		: User config dir: C:\Users\terry.EUCLID\AppData\Roaming\geany
15:49:36: Geany INFO		: System plugin path: C:\Program Files\Geany\lib\geany
15:49:36: Geany INFO		: Added filetype Clojure (61).
15:49:36: Geany INFO		: Added filetype CUDA (62).
15:49:36: Geany INFO		: Added filetype Cython (63).
15:49:36: Geany INFO		: Added filetype Genie (64).
15:49:36: Geany INFO		: Added filetype Graphviz (65).
15:49:36: Geany INFO		: Added filetype JSON (66).
15:49:36: Geany INFO		: Added filetype Scala (67).
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\main.c : C (UTF-8)
15:49:36: Geany INFO		: Loaded C:\Program Files\Geany\data\c99.tags (C), 1619 tag(s).
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\eeprom.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\heater.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\i2c_control.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\i2c_mesg.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\i2c_stat.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\interface.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\PC_mesg.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\PCF8591.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\sensor.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\switch.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\timer0.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\trace.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_lam.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_m1.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_m2.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_pickup.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\interface.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_tray.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_lam.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_skew.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_tray.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\DS1803.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\tasks.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\calibrate.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\calibrate.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\DS1803.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\eeprom.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\i2c_mesg.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\timer0.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_pickup.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\PC_mesg.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\status.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\SerialMesg.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\splint.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\powerup.c : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\trace.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\sensor.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\tasks.h : C (UTF-8)
15:49:36: Geany INFO		: D:\projects\E2040\firmware\v1.0\heater.h : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_skew.h : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_m1.h : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\feeder_m2.h : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\i2c_stat.h : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\PCF8591.h : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\diagnostics.c : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\diagnostics.h : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\i2c_control.h : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\powerup.h : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\SerialMesg.h : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\v1.0\motor.c : C (UTF-8)
15:49:37: Geany INFO		: D:\projects\E2040\firmware\V1.0\com.c : C (UTF-8)

**Comment by Terry-euclid** [comment]
Hi Folks,

Can anyone else reproduce this or am I the only person seeing this problem?

To try and reproduce do the following:

  1.	Open a File using Geany V1.26 and Windows
  2.	Select menu option Search / Find in File ...
  3.	Enter some text to search for
  4.	In the Files: dropdown select custom and enter *.c
  5.	Click the Find button

Terry

**Comment by codebrainz** [comment]
I can reproduce. Grep 2.4.2 that shipped with Geany 1.26 doesn't have the `--include` option, must've been added in a later version. I built Grep 2.22 from source and copied it (and dependent libraries) into Geany's `bin` dir and it works, since that version has this option.

**Comment by Terry-euclid** [comment]
Hi,

Thanks for coming back to me.

So can I say as you have reproduced this it is a genuine bug and it will get fixed on the next release?

I'm new to this forum so could you confirm if I need to do anything else to get it flagged to be fixed?

Terry

**Comment by elextr** [comment]
Flagged and milestoned, but thats no guarantee, "somebody" has to actually fix the building of bundle.

**Comment by eht16** [comment]
Yeah, we'll have to include a newer version of grep.exe into the bundle. As the bundle creation will be reworked anyway for the next release, we'll handle it.
See #560

**Comment by eht16** [comment]
Just for the records: no matter whether and what version of grep we ship with Geany, you can always change the grep command in the preferences and so easily choose your own version when desired.

**Comment by eht16** [comment]
@Terry-euclid we've just built test installers for the upcoming 1.27 release. Those contain grep 2.5 from UnxUtils (also a very old `grep` version but newer than the one included in Geany 1.26). This version has the `--include` option.

If you feel like testing, here are the links:
http://download.geany.org/snapshots/geany-1.27nightly_setup.exe
http://download.geany.org/snapshots/geany-plugins-1.27nightly_setup.exe

**Comment by Terry-euclid** [comment]
@eht16 Thanks for tthe updated, I've tested 1.27 nightly and can confirm it now works correctly out of the box, i.e. no need to change grep.

Terry
