### ISSUE TITLE
Single quotes no work in Mac Os X El Capitan

### ISSUE THREAD

**Issue by fraescaya10** [geany/geany#796]
I need write ' &nbsp;&nbsp;&nbsp;' but geany writes ´&nbsp;&nbsp;&nbsp;´ 
- Geany 1.26, en_US.UTF-8
- GTK 2.24.28, GLib 2.44.1
- Mac OS X El Capitan
<img width="1680" alt="screen shot 2015-12-10 at 22 49 42" src="https://cloud.githubusercontent.com/assets/4976683/11735549/55ffe080-9f90-11e5-919b-f812bc086a07.png">

**Comment by elextr** [comment]
Note, was originally Spanish locale, but as shown above, trying in en_US did not help.

**Comment by techee** [comment]
@fraescaya10 Are you using the build from http://download.geany.org/geany-1.26_osx.dmg ? The quotes work fine at least for me (El Capitan too).

**Comment by fraescaya10** [comment]
Yes, I download geany from http://www.geany.org/Download/Releases

**Comment by techee** [comment]
Doesn't it have something to do with the Spanish keyboard then? Just tried it and it seems that the various apostrophes are on the three keys on the right from P (the first one is ´, the second one is ` and finally the third one is ' which is the one you want). If you compare the keys you are pressing to get ' and what's displayed in System Preferences->Keyboard->Input Sources, are you getting something else than expected?

By the way, there are 2 Spanish keyboards: Spanish and Spanish-ISO with different layouts - maybe you want to use the other layout?

**Comment by fraescaya10** [comment]
I have keyboard US International, the problem is with the single quotes, double quotes appear with Shift + ', though slow to appear.
When I press ' in geany appear ´.

**Comment by techee** [comment]
Well, I'm clueless then. It works for me here so I think it might be somehow related to locale or system settings.

**Comment by fraescaya10** [comment]
Ok, I will try different modes of keyboard ...

**Comment by fraescaya10** [comment]
The problem is solved. I had set up the keyboard with the US International but the US is right.
Thank you for your help.
