### ISSUE TITLE
Line Markers Tab

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#798]
Please consider providing a tab that lists all currently set line markers by showing the content of the marked lines so that the desired line can be located with a single glance and then jumped to quickly: I think this will make line markers even more useful.
<b>Thanks!</b>

**Comment by eht16** [comment]
@philiprbrenan check the Addons plugin which provides a "Bookmark list" which pretty much does what you want, I guess.
It adds a side bar tab called "Bookmarks" and lists all lines in the current document which have a line marker set. The list contains the line number as well as the line text.

**Comment by philiprbrenan** [comment]
Perfect - thanks!
