### ISSUE TITLE
File Rename in Document Tab of Sidebar

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#810]
Please consider adding the capability to rename an open file from the Documents side bar.
 
![rename](https://cloud.githubusercontent.com/assets/7548378/11767992/e08f2f30-a1b6-11e5-9666-8c38bb210a7a.png)

<b>Thanks!</b>

**Comment by elextr** [comment]
Adding more file-manager capabilities to the built-in file tabs has been discussed and rejected before.  

The treebrowser plugin from geany-plugins provides a file window with more capabilities than Geany's built-in ones, including rename.
