### ISSUE TITLE
Swapping between Geany and another window

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#817]
Please consider ignoring the first click when one swaps from a window outside <b>Geany</b> when one is, for example, copying information from a web page because the cursor is moved to the click point used to bring <b>Geany</b> to the foreground and away from its carefully pre-placed position designed to optimize the flow of data in from the outside. 

![ignorefirstclick](https://cloud.githubusercontent.com/assets/7548378/11796194/e2c65bfa-a2b2-11e5-8d56-fa2964b82325.png)

<b>Thanks!</b>

**Comment by elextr** [comment]
Geany does not have control over this behaviour.  Instead don't click on the editing widget to raise Geany, use the window manager or click on the window title or somewhere else outside the edit window and the cursor shouldn't move.

**Comment by codebrainz** [comment]
`Alt+Tab` works on Windows, OSX and all Linux DEs I've used, FWIW.

**Comment by b4n** [comment]
I'll be blunt and say we won't implement this.  This would be inconsistent with all other applications I know of, and it's not our role IMO.  If you want this, make it so your WM/graphic server/whatever else don't send the input events for unfocused windows.
Finally, this might be tricky to implement correctly (depending on the event sequence we actually receive, I didn't check), as it'd have to differentiate a event focusing the window from the first after that (what if you focused with the keyboard and then clicked?  you don't want to ignore that), etc.

If really you want this, it maybe me possible to hack it around with a plugin, or more sensibly maybe with a GTK module; but I don't think we want this in stock Geany.
