### ISSUE TITLE
Bookmarks list across multiple files

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#818]
The Bookmarks List capability is very useful. Please consider making it possible to see all bookmarks across all files simultaneously so that one can jump quickly between lines in different files as easily as one can within one file using this excellent feature. 

Bookmarks in one file:
![bookmarkslist1](https://cloud.githubusercontent.com/assets/7548378/11825811/39d9b650-a379-11e5-9f3e-8a6d22f6348c.png)

Bookmarks in another open file:
![bookmarkslist2](https://cloud.githubusercontent.com/assets/7548378/11825812/3bca7832-a379-11e5-847c-5817b60f50d5.png)

<b>Thanks!</b>

**Comment by elextr** [comment]
The bookmarks list is part of the addons plugin which is part of the geany-plugins project, not Geany itself.

This tracker is for Geany itself, please post issues for Geany-plugins on that projects [issue tracker](https://github.com/geany/geany-plugins/issues)
