### ISSUE TITLE
Vertically selecting large numbers of lines

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#819]
Holding <b>alt+shift</b> to start a vertical selection and then holding <b>page-down</b> results in rapidly rising CPU usage and eventual black-out as <b>Geany</b> is starved of CPU.

Please consider making it possible to vertically select a large ranges of lines, for example: the whole file or a large enclosing class in a way that does not trigger this problem. 

![verticalselect](https://cloud.githubusercontent.com/assets/7548378/11827236/97977f9e-a382-11e5-9fbf-7207c6e738c7.png)

<b>Thanks!</b>

**Comment by elextr** [comment]
> Please consider making it possible to vertically select a large ranges of lines, for example: the whole file

Menu->Edit->Select All or ctrl-a

> or a large enclosing class in a way that does not trigger this problem.

click at start of desired selection
scroll to show end of desired selection
shift-click at end of desired selection

**Comment by codebrainz** [comment]
@elextr neither of those do a vertical/block selection.

I just tested this and it only puts CPU at 6% (of a 6-core I7), but it does get quite slow after a few tens of thousands of lines. Either way this is almost surely a performance issue in Scintilla, not Geany, and should be reported [at their bug tracker](http://sourceforge.net/p/scintilla/bugs/), particularly if it can be reproduced in an editor such as Scite (I only have Win32 (non-gtk) version to test with, it performs slightly better than Geany in this case).

**Comment by elextr** [comment]
@codebrainz oops left the ctrl off the last line :)

ctrl-shift-click does a column select.

**Comment by philiprbrenan** [comment]
Scite appears to fail much sooner and the black-out lasts much longer.
![scite](https://cloud.githubusercontent.com/assets/7548378/11830900/72094c34-a3a1-11e5-9ba8-081e7a02d28f.png)

**Comment by elextr** [comment]
@philiprbrenan as @codebrainz said its a Scintilla problem.  BTW he says its alt-shit-click on windows.

**Comment by b4n** [comment]
FWiW, I tried extending a vertical selection with the keyboard (indeed, gets slow over large number of lines) and using the mouse (shift+ctrl+click) which looks reasonable (maybe because it's a single shot).
Anyway, this would be a Scintilla issue, so it'd be better to report to them.  And as a mean to "select a large number of lines" at once, you've got what I believe is a reasonable answer with the mouse solution :)
