### ISSUE TITLE
Geany does not build code

### ISSUE THREAD

**Issue by dr446** [geany/geany#827]
There is an error saying "Process failed (the system cannot find the file specified)"

**Comment by elextr** [comment]
What are the settings for the build command you activated (use Menu->Build->Set Build Commands and post the values for the command you used).

**Comment by dr446** [comment]
No filetype commands. 
Independent Commands:
1) Make: make
2)Make Custom Target...:make
3) Make Object: make %e.o

Execute Commands: 
1) Execute: ./%e

**Comment by codebrainz** [comment]
@dr446 you should customize those to fit your system. For example if you're using "MinGW" toolchain on Windows, `make` is usually called `mingw32-make` and unless you have the path to it in your `%PATH%` environment variable, you'd need to specify the full path to it (likewise with any other tools like that). You probably also have to customize the Execute command to point to wherever your resulting binary ends up, for example by setting the working dir to where your Makefile outputs the binary.

**Comment by elextr** [comment]
@dr446 you didn't say which command you used.

What language are you trying to build?  The fact that there are no filetype commands says the file you have open is not a type recognised by Geany.

If you were running `Make` then do you have a makefile?

**Comment by dr446** [comment]
I am using c++. I now have a c++ file open. 
These are the commands:
C++ Commands:
Compile: g++ -Wall -c "%f"
Build: g++ -Wall -o "%e" "%f"
Lint: cppcheck --language=c++ --enable=warning,style --template=gcc "%f"

Independent Commands:
Make: make
Make Custom Target...: make
Make Object: make %e.o

Execute Commands: 
Execute: "./%e"

I am not sure what command I used - I just pressed build. What is a makefile - Please excuse my lack if knowledge - I am a beginner.

**Comment by elextr** [comment]
Do you have the g++ compiler installed?

**Comment by dr446** [comment]
I installed one now and it works. Thank you for your help!
