### ISSUE TITLE
Right swipe across {

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#840]
Please consider having right swipe across <b><big>{</b></big> select the entire
associated block, whilst left swipe would continue to select just the
<b><big>{</b></big> as it does now. This would be both very useful and very
easy to remember. Thank you for your consideration of this matter.

**Comment by elextr** [comment]
As has been said before, selection is controlled by Scintilla, you will have to ask there first.

**Comment by philiprbrenan** [comment]
Posted to scintilla!
