### ISSUE TITLE
Menu item to load the full path of the current document to the clipboard

### ISSUE THREAD

**Issue by philiprbrenan** [geany/geany#846]
Please consider adding a menu item under Document to load the full path name of the current document to the clipboard as this would, I believe, be very useful for driving other software.  It is possible to obtain this information by using Find Files under Documents or from the Status tab but neither approach is so obvious or convenient.  Thanks very much!

**Comment by eht16** [comment]
This is already possible: the Addons plugin automatically adds a menu item in the Tools menu to copy the file path of the current document to the clipboard. This action is also avaliable as keyboard shortcut.

**Comment by philiprbrenan** [comment]
Very useful. Thanks!

**Comment by broesamle** [comment]
maybe I overlooked something, but in my case it does not...
the addons manager shows the plugin, checked, restarted geany, no menu item :-(

**Comment by elextr** [comment]
@broesamle what version of geany-plugins are you using? The menu item was in geany-plugins 1.26

**Comment by broesamle** [comment]
Thank you for the quick reply! 1.25 -- that explains it :-)
M
