### ISSUE TITLE
Hang on "Reflow" with lots of spaces

### ISSUE THREAD

**Issue by BenWiederhake** [geany/geany#848]
This is the minimal files I could produce that triggers the hang:

	aaaaaaaaaaaa                                                                               bbbbbbb
	aaaaaaaaaaaa                                                                               bbbbbbb

I uploaded this file at http://pastebin.com/CVLxZsrJ

Steps to reproduce:

- Open the given file in geany
- Select from the menu "Edit > Format > Reflow Lines/Block", or simply press Ctrl-J

This behavior can *always* be reproduced, and still happens with the newest version I found on git (`git describe: 1.26.0-14-gd1fcd9f`). This does not seem to be related to #815, but I'm not sure. This does not seem to be related to any other known bug in this bugtracker. This does not seem to be related to any other known bug in [the Debian BTS](https://bugs.debian.org/cgi-bin/pkgreport.cgi?pkg=geany).

Expected behaviour: The text should change in some way. Not sure and don't care how exactly.

Actual behaviour: Geany stops responding and does not write out any status information when being forcefully closed.

Here's a log of gdb trying to show the stacks of all four(?) threads: http://pastebin.com/mA7DRbLg

Here's what your webpage requires for bugreports:

    $ # Filetype: None
    $ LC_ALL=C geany --version
    geany 1.26 (built on 2015-11-24 with GTK 2.24.28, GLib 2.46.2)
    $ file mincrash.txt 
    mincrash.txt: ASCII text

Against, please note that I can still find this bug in the newest version, fresh from git.

**Comment by codebrainz** [comment]
Confirmed on Win10 with latest 1.26 installer release.

(@BenWiederhake thanks for providing such a good bug report.)

**Comment by BenWiederhake** [comment]
:D Thanks, I'm trying my best.

**Comment by elextr** [comment]
Doesn't happen on latest git on Linux Mint 17.3 Cinnamon (Ubuntu LTS base):

10:13:36: Geany INFO		: Geany 1.27 (git >= 27628c0), en_AU.UTF-8
10:13:36: Geany INFO		: GTK 3.10.8, GLib 2.40.2

@BenWiederhake as @codebrainz said, good report, would suggest a couple of improvements.

1) You didn't mention the OS you are using, (though you hint its Debian) and it now seems to vary depending on system (which is strange :)

2) If you built the latest from git, to make the gdb tracebacks useful do `CFLAGS=-g ./configure` to get symbols.

**Comment by codebrainz** [comment]
@elextr I think by default Autotools puts `-g` in `CFLAGS`, not sure what those missing symbols are.

**Comment by codebrainz** [comment]
Confirmed on Ubuntu 15.10. [Backtrace here](https://gist.github.com/codebrainz/1f6f49247698c120e7a7)

**Comment by codebrainz** [comment]
Thought it might be related to GTK2, but I can reproduce with Ubuntu and GTK+ 3.16.7. [Backtrace here](https://gist.github.com/codebrainz/48ce63f927d93defeabd).

**Comment by elextr** [comment]
> @elextr I think by default Autotools puts -g in CFLAGS, not sure what those missing symbols are.

I thought so too, but HACKING says to put it in CFLAGS so I followed the documentation :smile:

**Comment by elextr** [comment]
> Confirmed on Ubuntu 15.10. Backtrace here

Interesting, must be dependent on some setting that we have different, maybe wrap column settings, I have long line breaking 80 and long line column 80.

**Comment by codebrainz** [comment]
@elextr Sounds plausible, you could always try with a fresh config dir. I think I have default long line marker column, and definitively no line breaking enabled.

**Comment by codebrainz** [comment]
FWIW, it never breaks out of [this infinite loop](https://github.com/geany/geany/blob/1.26.0/src/keybindings.c#L2210)

**Comment by elextr** [comment]
Yeah, it depends on the column settings, the default is 72 and fails, my settings of 80 are ok.  But that can probably be affected by the numbers of spaces separating the items.

**Comment by elextr** [comment]
Ok, think I have it, split initially splits the line after the 'a's so the next line starts with lots of spaces, then the "lookup split position" loop backs pos to the start of the line since its all spaces before the split position, the the next loop does nothing since the first character on the line is a space, so it inserts a newline there, and keeps going

**Comment by elextr** [comment]
Maybe it would work if the second loop started at `edge`

**Comment by BenWiederhake** [comment]
@elextr: I built it using `./autogen.sh CFLAGS=-g ./configure` as recommended by `HACKING`, then did a `make install` and confirmed that the right binary is being called. Looking at the backtrace, it's now obvious to me that the "olg" `libgeany.so` was loaded, and thus the missing symbols.

What should have I done instead? Could this be a general problem? Maybe the HACKING needs updating?

**Comment by elextr** [comment]
Unless you specified a prefix to `configure` it should have overwritten the old libgeany.

My recipe that ensures a specific version (and doesn't touch your normal install) is: 

```
mkdir /some/where
cd /some/where
git clone <the url>
cd geany
./autogen.sh --prefix=/some/where
make install
cd ../bin
./geany -c ../config
```

And as @codebrainz said above I'm pretty sure it sets -g itself in that situation.

And just `rm -rf /some/where` when you have finished, nothing is placed outside that tree.

**Comment by elextr** [comment]
Tsk, forgot to say, its quite possible that HACKING needs updating, libgeany is a fairly new thing.

**Comment by b4n** [comment]
OK, the actual problem seem to be that as is the autoindent triggered by newline (expected) will autoindent wider than the original (line start) one, and start messing up everything.

```diff
diff --git a/src/keybindings.c b/src/keybindings.c
index 8913c57..4da0dba 100644
--- a/src/keybindings.c
+++ b/src/keybindings.c
@@ -2247,6 +2249,11 @@ static gint split_line(GeanyEditor *editor, gint column)
                if (!found)
                        break;
 
+               /* don't split on trailing spaces, which would mess up with auto-indent
+                * and possibly lead to infinite loop */
+               while (pos + 1 < lend && sci_get_char_at(sci, pos + 1) == GDK_space)
+                       pos ++;
+
                sci_set_current_position(sci, pos + 1, FALSE);
                sci_cancel(sci); /* don't select from completion list */
                sci_send_command(sci, SCI_NEWLINE);
```

Fixes the lock and some unexpected behavior, but the behavior is probably not great as it'll split very early because of all the spaces.  Maybe we'd like to trim repeated spaces, but that might also be unwanted… not sure.  What do you think?

Also the reflow code has weird behavior regarding tabs, maybe we should also allow splitting on tabs (or even `g_ascii_isspace()`)?

**Comment by codebrainz** [comment]
> Maybe we'd like to trim repeated spaces, but that might also be unwanted… not sure. What do you think?
I don't think we should ever trim inner (not start or trailing) whitespace, unless after re-flowing, it winds up at the end of the line (in which case we could be extra smart and use the "strip trailing whitespace" setting to decide whether to strip it). The code appears to already handle leading indent/whitespace. 

> Also the reflow code has weird behavior regarding tabs, maybe we should also allow splitting on tabs (or even g_ascii_isspace())?

Yes, I noticed the code compares to `GDK_space` which seems a bit weird, but I guess it's probably an ASCII space character (decimal 32). It seems like it would make more sense to consider all (at least ASCII) white space characters. If we wanted to handle it better, we could probably also use [`g_unicode_isspace()`](https://developer.gnome.org/glib/stable/glib-Unicode-Manipulation.html#g-unichar-isspace), but that's a slippery slope.

**Comment by BenWiederhake** [comment]
I like the "strip trailing whitespace" option. This makes interop with other people's editors (e.g. via VCS) much easier.

**Comment by elextr** [comment]
@b4n, no don't strip internal spaces, its common in some parts of the world to use two spaces between the full stop and the start of the next sentence.  It would be annoying if that was changed.

Also there is no need to strip trailing spaces, if the "strip trailing spaces" option is set then they go away when the file is saved anyway.

As for using anything other than ascii spaces for breaking, see the warning on the [link](https://developer.gnome.org/glib/stable/glib-Unicode-Manipulation.html#g-unichar-isspace) @codebrainz posted.

Reflowing something containing tabs is hard to understand, why use a tab internally unless you want something aligned, but then you ask for it to be un-aligned :smile:  I'm not sure what the "right" thing to do is, maybe better to not do anything special.

**Comment by b4n** [comment]
> Also there is no need to strip trailing spaces, if the "strip trailing spaces" option is set then they go away when the file is saved anyway.

Tho it's annoying when it's not enabled, because reflow inserts a *lot* of trailing spaces.

> As for using anything other than ascii spaces for breaking, see the warning on the [link](https://developer.gnome.org/glib/stable/glib-Unicode-Manipulation.html#g-unichar-isspace) @codebrainz posted.

This is kinda irrelevant, it's not worse to use an ASCII version of `isspace()` than only the ASCII space character itself.  Sure, when it comes to real, locale-aware, word breaking, it's highly complicated, but we probably don't really want that anyway, and couldn't either (what language is this?  we don't know, and can only guess English).

> Reflowing something containing tabs is hard to understand, why use a tab internally unless you want something aligned, but then you ask for it to be un-aligned :smile:  I'm not sure what the "right" thing to do is, maybe better to not do anything special.

Well, okay maybe just leave it as is and leave people with the very weird behavior on tabs (probablt because it's *partially* considered spaces: it is for indentation and trailing space purpose, but not in the reflow algorithm itself).

**Comment by b4n** [comment]
here you go, #852
