### ISSUE TITLE
Different colors for warnings and errors

### ISSUE THREAD

**Issue by Yanpas** [geany/geany#864]
Underline color for warnings should differ from color of errors, for example color of erros is red, color of warnings is orange. Currently it's red for both

**Comment by elextr** [comment]
Are you talking about in the compiler window?

**Comment by Yanpas** [comment]
I was talking about editor window, but I guess different font  color in compiler window is a good idea too

**Comment by elextr** [comment]
Will need separate regexes for warnings and code and separation of the built-in decoders.  Not impossible, but "somebody" has to do it.

**Comment by Yanpas** [comment]
Edits should be made in `build.c:966` ( call to msgwin_parse_compiler_error_line )

**Comment by codebrainz** [comment]
Closing because of dupe of #447 and continued in PR #1649 (thanks!)
