### ISSUE TITLE
Markdown markup for fixed font does not work on start of a line

### ISSUE THREAD

**Issue by BenWiederhake** [geany/geany#867]
The following one-liner does exactly what it looks like:

    This is a `hello-world` example.

And so do these two lines, as the linebreak isn't too special in plain Markdown:

    This is a
    `hello-world` example.

However, geany/scintilla/ctags/whatever doesn't recognize the backtick correctly if it happens to be at the start of a line, and wasn't at the start of the line before(?).

Steps to reproduce:

- Open Geany, open a new tab
- Write ``This is a `hello-world` example.`` in a line
- Put the cursor right after the word `a`
- Hit enter. The new line should start with a space, then a backtick
- Press "delete" on your keyboard

Actual behavior: The `hello-world` is no longer shown in the correct color (blue-ish in my case), but as normal text (black in my case; I should still have default syntax colors).

Expected behavior: The `hello-world` should still be in the correct collor, as it is still a valid markup for inline-code.

Note that something fishy is going on, because if you add a newline before the paragraph, then it apparently get's re-parsed correctly, fixing the display.

EDIT: It also fails to markup ``What a nice (`num_deaths == 0`) day!`` correctly, apparently the combination of opening-round-parenthesis and backtick doesn't work, somehow. This does *not* fix itself like the thing above.

**Comment by codebrainz** [comment]
This is a bug in the Scintilla Markdown lexer. [It looks like it might have been fixed already](http://sourceforge.net/p/scintilla/bugs/1766/), but in general syntax highlighting bugs should be submitted to [Scintilla's bug tracker](http://sourceforge.net/p/scintilla/bugs/), as we don't maintain it or modify the Scintilla lexing code.

**Comment by b4n** [comment]
I can't reproduce the bug in the current development version, which includes the fix mentioned by @codebrainz, so I guess it fixes it indeed.

The second issue is apparently different, and isn't fixed in current development version, neither on our side not in Scintilla's.  It would then be worth reporting it to them.

**Comment by BenWiederhake** [comment]
Reopening because of the second part.
Upstream bug is [#1804](https://sourceforge.net/p/scintilla/bugs/1804/)
