### ISSUE TITLE
Add feature: copy filename / copy filepath to clipboard

### ISSUE THREAD

**Issue by stdex** [geany/geany#868]
It would be convenient to append items "copy filename" and "copy filepath" on tabs right click menu.

**Comment by codebrainz** [comment]
This sounds like the same feature as #846, just accessible from a different place in the UI.

**Comment by eht16** [comment]
As said in #846 , copying the file path of the current document is already implemented in the Addons plugin:
http://plugins.geany.org/addons.html#copy-file-path
There is a menu item in the Tools menu as well as a keyboard shortcut. What is missing is the "copy filename" but I'm not sure if it is worth to be implemented. Should be easy enough to be stripped manually from the copied file path.

Re-open if anyone disagrees.

**Comment by adrianog** [comment]
can we the web page http://plugins.geany.org/addons.html#copy-file-path, it doesn't show the name of the plugin "Addons"

**Comment by eht16** [comment]
What exactly do you request? I don't understand the sentence fully.
If it is about changing the website, maybe it is better to open a new issue in the Geany-Plugins repository (https://github.com/geany/geany-plugins).

**Comment by runningopenloop** [comment]
Ah, I think the issue is:
https://plugins.geany.org/addons.html
doesn't state the page is for the "Addons" plugin.

Compare with for example:
https://plugins.geany.org/autoclose.html
This shows a broken image link for autoclose plug at the top.

Generally speaking, all the plugins pages for individual plugins geany could use above the "Contents" a title saying what the plugin name is.

---

So I find myself here because after installing the "geany-plugins-2.0_setup.exe" -- I don't see the addons plugin or the Tools menu option to copy file path.

**Comment by elextr** [comment]
@runningopenloop as @eht16 noted above, addons isn't in this repository, it in geany-plugins so open a new issue on the geany-plugins repository, and in your case make it more than one to separate windows install issues from the website issues which is likely to be the website generating infrastructure which is in the plugins.geany.org repository.

**Comment by adrianog** [comment]
@elextr @runningopenloop @eht16 
https://github.com/geany/geany-plugins/issues/1368

**Comment by eht16** [comment]
> So I find myself here because after installing the "geany-plugins-2.0_setup.exe" -- I don't see the addons plugin or the Tools menu option to copy file path. I guess I had to copy addons.dll from C:\Users<username>\Geany-Plugins 2.0\lib\geany to C:\Users<username>\Geany 2.0\lib\geany
> 
> This doesn't seem right... should the default install directory for the Geany-Plugins 2.0 for windows be same as the install directory for Geany 2.0?

This was already reported in https://github.com/geany/geany-plugins/issues/1321 and fixed in https://github.com/geany/geany-plugins/pull/1324.
