### ISSUE TITLE
CPP suggest and highlight methods from STL

### ISSUE THREAD

**Issue by Yanpas** [geany/geany#876]
Geany lacks of c++ support.
```
std::vector<std::pair<int,char> > a;
a[0].f // geany should suggest "first()" when I'm typing.
```
Also `first` later should be highlighted.
Also is it neccesary to add template closures `< >` pair highlighting ?

**Comment by Yanpas** [comment]
It's not a fix, but something good: https://github.com/lmachucab/geany-std.cpp.tags
Maybe merge this tags with master branch?

**Comment by elextr** [comment]
Have you tried the tags files on the wiki?

Geany does not parse non-global declarations in any language.  

To do so would require a lot more knowledge about the user environment, for C++ that means all of the includes, which means all of the `-I` options in the compile, which means knowing the compile command, knowing and parsing which makefile is being used, which gets you to a heavyweight IDE like Eclipse or Netbeans.  But even those have the problem " oh you don't use a makefile, you use cmake, or scons or something else ... tough". 

Also your example requires knowledge of the type of the expression `a[0]` which means knowing about instantiating the `vector` template which means knowing pretty much all the C++ compiler knows.

Geany itself will almost certainly never do any of these things, but an experiment some time ago showed that it would be possible to use a plugin with `LibClang`, but "somebody" has to do it.

**Comment by codebrainz** [comment]
> Geany does not parse non-global declarations in any language. 

[citation needed]

```c++

struct Foo {
  void some_func() {}
};

struct Bar {
  Foo myfoo;
  void blah() {
    myfoo. <<--- offers non-global Foo::some_func() as completion
  }
};
```

It should work for `std::vector` member functions too if it had tags, but indeed I doubt it can have any clue what to do with the return value from the overloaded `operator[]` on vector, like the `first` member variable of the resulting `std::pair` reference or whatever.

**Comment by codebrainz** [comment]
> Maybe merge this tags with master branch?

The problem is that it's too annoying. C++ stdlib has too many common lower case type names, and Geany/Scintila's type highlighting isn't semantic, so it highlights all uses of those names as types, consider for example:

```c++
std::string map; // highlights 'std', 'string' and 'map' as types
int std; // highlights 'std' as type
void map() {} // highlights 'map' as type
```

**Comment by elextr** [comment]
@codebrainz in your example some_func() is part of the globally defined Foo struct so it works.

What I mean is:

```
struct a { int barbar; };
a an_a;
f(){
    a an_other_a;
    an_a.        <--- barbar suggested
    an_other_a.  <--- nothing suggested
}
```
because `an_other_a` is local.

Totally agree that random selections of symbols (even the STL) should not be forced on users.

**Comment by codebrainz** [comment]
> because an_other_a is local.

@elextr, yeah, I think your statement I quoted should've perhaps more aptly read "Geany does not parse _local_ declarations in any language." It actually parses all kinds of non-global stuff (inside namespaces, nested classes, etc).

**Comment by elextr** [comment]
Actually to be exact, what it doesn't parse is the body of *function definitions*, but irrespective of the semantics the point is that completion doesn't work for such objects and its a big step to make it happen without something like libclang.

**Comment by Yanpas** [comment]
OK, I agree with you, bad idea. Does highlightnig methods have the same story or it is valid request?
For example:
```
struct a 
{
   int x;
   int y;
   int get();
}
a sample_a;
int x = a.x     // 'x' should not be highlighted
int y = a.get() // 'get' should be highlighted as method
```
It seems to be unachievable with `~/.config/geany/filedefs/filetypes.cpp`

**Comment by codebrainz** [comment]
> Does highlightnig methods have the same story or it is valid request?

@Yanpas It would have to be a request to Scintilla project. The Python lexer can do this, but it might not be as easy for C++ lexer as Python uses `def` to define functions, where C++ is a lot harder. One vexing example, which I don't think can be determined without proper parsing of the code, is like:

```c++
static vartype varname(initval);
static returntype funcname(argtype);
```

I'm sure there's many more examples to make distinguishing simple enough for a dumb lexer.

**Comment by Yanpas** [comment]
Got it
