### ISSUE TITLE
Would it be possible to configure the highlighting of matching brackets/braces

### ISSUE THREAD

**Issue by ThosRTanner** [geany/geany#885]
The current highlighting of dark blue (as opposed to black when not selected) is very difficult for me to see. I imagine there's something I can edit, but there's nothing in the documentation and playing with brace_good in filetypes.common didn't appear to achieve much.

Using geany 1.24.1

**Comment by elextr** [comment]
What colour scheme are you using? The default is mid to dark grey.  You would need to edit the colour scheme file.

**Comment by ThosRTanner** [comment]
I'm using the default colour scheme. How would I find the right file to edit?

**Comment by elextr** [comment]
Oh, it looked grey on my monitor. Ok, filetypes.common, the line

```
brace_good=0x0000ff;0xFFFFFF;true;false
```

**Comment by ThosRTanner** [comment]
ohh. I tried that but I'd got too many zeros in the hex number I think (or something). Gave it another try (added a new style as well just to be safe) and it's working great. thanks.

**Comment by that-ben** [comment]
I'm sorry to necro this thread, but under v2.0 how can I set the highlighting (and if possible choose the color) of the matching brace?
<img width="280" alt="Screenshot 2023-11-10 at 1 08 55 PM" src="https://github.com/geany/geany/assets/13210399/8caa7783-3e78-4812-a90d-139d3c8227b3">
