### ISSUE TITLE
Message window tabs: How to display them horizontally or remove?

### ISSUE THREAD

**Issue by henrywright** [geany/geany#887]
Hi guys

I'm using the message window on the right hand side of my screen (see screenshot). How can I either remove the Status, Compiler, Messages, Scribble and Terminal tabs or ideally I'd like to display them horizontally along the top. I'm using an 11.1 screen and could do with the extra space.

Thanks in advance!

![screenshot 2016-01-26 at 11 42 24](https://cloud.githubusercontent.com/assets/1963288/12579728/05246382-c422-11e5-9e52-97d4b294e8ff.png)

**Comment by elextr** [comment]
Menu->edit->preferences->interface->notebook tabs->tab positions->message window.

**Comment by henrywright** [comment]
@elextr you rock! Thanks
