### ISSUE TITLE
Keyboard shortcut to show and hide the Message Window

### ISSUE THREAD

**Issue by henrywright** [geany/geany#891]
Hey guys

I often visit View > Show Message Window to show or hide the Message Window. Is it possible to get keyboard shortcuts for these actions?

**Comment by elextr** [comment]
Yes, look at the keyboard preferences there is a toggle message window you can bind to anything.

But please ask such questions on the mailing list, they are not issues for the tracker.

**Comment by henrywright** [comment]
Great stuff @elextr, I didn't know you could do that.

And sure thing, I'll make sure to ask on the mailing list next time.
