### ISSUE TITLE
Assembly extension .s

### ISSUE THREAD

**Issue by codebrainz** [geany/geany#904]
Anybody mind if I add `*.s` and `*.S` to `filetype_extensions.conf` for `ASM`? It's the extension commonly used by/for GCC/GAS.

**Comment by elextr** [comment]
Seems sensible, matches what it says [here](https://gcc.gnu.org/onlinedocs/gcc-5.2.0/gcc/Overall-Options.html#Overall-Options) except it also mentions `.sx` ?

**Comment by codebrainz** [comment]
I never heard of `.sx` but google lead to [this](http://www.nongnu.org/avr-libc/user-manual/assembler.html):

> As an alternative to using .S, the suffix .sx is recognized for this purpose (starting with GCC 4.3.0). This is primarily meant to be compatible with other compiler environments that have been providing this variant before in order to cope with operating systems where filenames are case-insensitive (and, with some versions of make that could not distinguish between .s and .S on such systems).

If it doesn't clash, I see no reason not to also add it.

**Comment by codebrainz** [comment]
Branch here: https://github.com/codebrainz/geany/commit/39acaaf8ccecca9105a4506db66f82698d6c3cce

**Comment by b4n** [comment]
Sure
