### ISSUE TITLE
Add an option for automatically saving any unsaved / unnamed (new) documents in a cache directory

### ISSUE THREAD

**Issue by CreamyCookie** [geany/geany#905]
This is nice for when the application / the system is crashing, or there is a power outage.

**Comment by b4n** [comment]
I think the Addons plugin from [Geany Plugins](/geany/geany-plugins/) can do just that :)

**Comment by zstojanovic** [comment]
If I understand @CreamyCookie correctly, he is not looking for auto save function but rather wants a "hot exit" feature (and I would like that too).

Hot exit is a feature of some modern editors that preserves unsaved files on quit without prompting the user to save them before quitting. A nicer explanation can be seen here: https://github.com/Microsoft/vscode/issues/101#issue-117679274

I searched in every plugin I could get, but I couldn't find such feature.

**Comment by elextr** [comment]
The use-case seems to have two parts:

1. Saving the session status when the application is shutdown normally.  Saving modified buffers in the Geany config directory and recording that in the session file should be possible if someone wants to make a pull request for it.

2. Preserving state when the application is not shutdown normally, ie crash, logout, system shutdown.  In this case there is no way of saving the status after the abnormal condition has occurred, so any saving needs to happen before the abnormal incident similar to the Saveactions plugin (not Addons as @b4n posted), but not saving over the original file.  That would be a reasonable enhancement to that plugin and again pull requests are welcome.

**Comment by Noitidart** [comment]
I need this. Everytime I close VSCode manually, it is prompting me to save untitled files. If I don't save it, then its not restored. I don't want to save those untitled files, I just use those as scratch notes. If I ctrl+alt+del to force exit then it works, but i prefer not to ctrl+alt+del it.

**Comment by meequz** [comment]
I have came here to ask for the same feature. Preserving unsaved files on exit and restore them on launch would be very useful for productivity.

**Comment by elextr** [comment]
Just needs "somebody" to do it.

**Comment by elextr** [comment]
Ok, @codebrainz and I have had an offline discussion and since it doesn't matter which issue discussion actually continues on this will continue here, but the discussion on #2717 which does (at least to me, @etkaar may disagree) seem to be heading to an implementation, is to be considered to be pasted here (sadly Github doesn't actually allow them to be combined AFAIK).

**Comment by badmin-c** [comment]
> I have came here to ask for the same feature. Preserving unsaved files on exit and restore them on launch would enhance my productivity a lot.

Same here! I love this feature in Notepad++ and would really love to see it in Geany

**Comment by elextr** [comment]
As noted  above, in #2717 its something "somebody" might add to the saveactions plugin, but since Geany is a volunteer project "somebody" has to volunteer a pull request.

**Comment by cactux** [comment]
+1 for this feature request. At work (on ms-windows) I use Notepadd++ which does this, and it is very useful. At home (Linux) I use either Geany or Sublime Text (which has this feature too, but is not open source).
This feature really does give you a kind of peace of mind:
1. The editor do not ask you anymore what you want to do with unsaved files when you close it (either voluntarily or during a crash).
2. When working on a file saved on disk, if modified in the editor, then on reopening the modified and unsaved version is opened for the user.
3. When working on files not yet saved (an "untitled" one), they are also reopened with their content.
Keeping info in an unsaved buffer might be seen as dumb. But it is very useful! I do it often for not important data, which I could build again if needed. Think for example a temporary text conversion between an export and a work in excel or calc. Or a copy paste to remove the formatting between apps.
I'd like to be able to code this, unfortunately I don't have these skills, let's hope someone can do it :)

**Comment by LiquidCake** [comment]
i extended `saveactions` plugin to add this kind of functionality - it is not as seamless as would be if incorporated into core code but works good enough.
Supports points #1 and #3 from this comment https://github.com/geany/geany/issues/905#issuecomment-1501065105
(not #2 though)

PR: https://github.com/geany/geany/pull/3904

https://github.com/geany/geany/assets/9273621/d91235c1-d2a6-46f8-894b-db7941034962

**Comment by techee** [comment]
I'm closing this issue as I believe that the request of the OP, i.e. automatically saving untitled/new documents, is resolved by #3911.

There was also some discussion related to "hot exit" which isn't implemented right now and which would probably require much more work and rewrite Geany's session management - I believe this one can be discussed further in a dedicated issue, e.g. https://github.com/geany/geany/issues/3733
