### ISSUE TITLE
JSON Prettifier plugin in the OSX release

### ISSUE THREAD

**Issue by poorlymac** [geany/geany#913]
Hi,

Could the JSON Prettifier plugin http://plugins.geany.org/jsonprettifier.html please be added to the OSX release.

Thanks
Paul

**Comment by elextr** [comment]
Unfortunately that is a third party plugin, it has not been submitted to be
part of the Geany-plugins collection.

If somebody submits it and its accepted it will be part of the collection
(if it runs on OSX).

**Comment by poorlymac** [comment]
Thanks elextr. FYI I compiled it and it runs perfectly under a homebrew compile of geany. Unfortunately maybe due to code signing it didn't seem to work when putting inside. What would be good is if the Mac app could pull plugins from outside the apps, I even tried setting the Extra Plugin Path to /usr/local/lib/geany/ (where I had my working .so) but it still wouldn't pick up in the Mac App version.

**Comment by poorlymac** [comment]
FYI I added the .so to my app and resigned it but the plugin is still not detected, so code signing is perhaps is not the issue.

**Comment by eht16** [comment]
@poorlymac alternatively, you don't need this plugin to pretty print JSON with Geany. This was never necessary as it is very easy to get it with 'Send selection to' commands.
Details on how to configure Geany to use e.g. Python to pretty print some JSON can be found in the wiki (at the bottom pf the page):
https://wiki.geany.org/config/json

**Comment by poorlymac** [comment]
Hi eht16, that works well thanks, a bit slow compared to the plugin, but definitely good enough. thanks for the idea
