### ISSUE TITLE
Do not write history of terminal commands (support for CLI variables)

### ISSUE THREAD

**Issue by Yanpas** [geany/geany#918]
Geany may use any command line interpreter, but there is no option in settings to set variables for this terminal session. For example I use bash and do not want geany's bash to save all it's `cd`s and program executions to `.bash_history`.

I would like `unset HISTFILE` command would be ran every time I open geany

**Comment by eht16** [comment]
I personally don't think adding support for setting arbitrary environment variables in Geany is necessary.

An easy solution would be to specify a specific RC file to the bash command line in Geany's preferences, like `bash --rcfile /home/username/.bash_geany.rc` and then put anything you need into this RC file and optionally include/source your "real" .bashrc when appropriate.

**Comment by Yanpas** [comment]
Oh, I should have guessed about it

**Comment by b4n** [comment]
@Yanpas there's also an option for prefixing `cd`-like commands Geany sends, meant just for allowing those not to be put in the history: [`send_cmd_prefix`](http://www.geany.org/manual/#various-preferences).
