### ISSUE TITLE
Color scheme bug for Ruby files

### ISSUE THREAD

**Issue by rovf** [geany/geany#927]
The syntax highlighter does not recognize multi-line comments in Ruby and highlights the comment, as if it were executable code. Example

=begin

......

for class 

......

=end

_for_ and _class_ are colored like reserved words.

**Comment by b4n** [comment]
Works for me just fine, what's your Geany version?  Would be quite old, should work for quite some time I think.

![ruby_comment](https://cloud.githubusercontent.com/assets/793526/13432243/0d636c48-dfcd-11e5-9854-9d600778c864.png)

**Comment by rovf** [comment]
Oh, sorry, my mistake! I had a space in front of the equal sign, which I didn't notice. Sorry for bothering.
