### ISSUE TITLE
Javascript Class

### ISSUE THREAD

**Issue by ZatsuneNoMokou** [geany/geany#934]
ES6 have added class system like it is shown in [Mozilla Doc page](https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Classes), could it be possible to have syntax highlight and all?

**Comment by b4n** [comment]
Possible of course, needs someone doing it :)

For the highlighting part, it should be very easy, a mere matter of updating the keywords in *data/filetypes.javascript* to include the new ones.  Grammar didn't change so much AFAIK, so it should be enough.

For the tagging part it'll be a little more works as it'll require updating the parser to really understand those new syntaxes, but it's something that will likely be done by Somebody at some point in the (probably not so distant) future.  S/A https://github.com/universal-ctags/ctags/issues/780

**Comment by ZatsuneNoMokou** [comment]
It would be interesting to support texts like `foo1 ${var1} foo2` too

**Comment by b4n** [comment]
I implemented support for template strings in Universal-CTags, but apparently I never updated the parser in Geany (??).
Will have to backport those indeed.

**Comment by ZatsuneNoMokou** [comment]
I guess, because if I put thing like \`I don't know\` the quote will be considered as a string start but it does not work like that.
Maybe the parser for Javascript haven't been updated, I dunno

**Comment by b4n** [comment]
> I guess, because if I put thing like `I don't know` the quote will be considered as a string start but it does not work like that.

Well, if the example \``I don't lnow`\` it's actually fine to consider it a string -- so long as it doesn't contain `${}`s :)

The highlighting part might be missing completely though, I'm not sure -- that'd be Scintilla.

**Comment by ZatsuneNoMokou** [comment]
It gonna take time to do these 2 things?

**Comment by b4n** [comment]
Importing the CTags fixes should be relatively easy.  Fixing the highlighter will be a lot trickier, esp. because template strings are tricky in the sense they basically require running the parser recursively.

I will import the CTags change "soon", but probably not before next week.

**Comment by ZatsuneNoMokou** [comment]
You'll close this issue when the fix will be done?

**Comment by b4n** [comment]
Yeah, sure.

**Comment by ZatsuneNoMokou** [comment]
I can see the classes are coming soon I guess, there's some news about the quotes?

**Comment by ZatsuneNoMokou** [comment]
The classes have now the color thing, but not displayed in the "classes" part?

**Comment by xuhcc** [comment]
There is an issue on Scintilla bug tracker for template strings support: https://sourceforge.net/p/scintilla/feature-requests/1112/
Someone mentions the `lexer.cpp.backquoted.strings` setting, and it actually works.
Just add this code to your **filetypes.javascript**:
```ini
[lexer_properties]
lexer.cpp.backquoted.strings=1
```

**Comment by Proberts** [comment]
ES6 keywords
[filetypes.javascript.txt](https://github.com/geany/geany/files/642312/filetypes.javascript.txt)

**Comment by ZatsuneNoMokou** [comment]
Can expect backquote support some day?

**Comment by b4n** [comment]
@ZatsuneNoMokou proper one would need someone to take the task and implement it in Scintilla.  If setting `lexer.cpp.backquoted.strings=1` is good enough though, as suggested by @xuhcc, we can do that easily (and you can do that in your own configuration).

I would be interesting to get some testing of using `lexer.cpp.backquoted.strings=1` to see if it's good enough for now, or just confuses a little further.

**Comment by ZatsuneNoMokou** [comment]
Just did it, at least there won't be any annoying effects with stuff like where the quote was considered as a string begin.
```
`L'exemple`
```

**Comment by b4n** [comment]
@ZatsuneNoMokou okay thanks.  This is added in 9fdb014b073f9035bc8df9b843213a9d1e997ccb

**Comment by nahidakbar** [comment]
+1

Not sure if this is still an issue. I am using geany from ubuntu repo. But geany 1.27 seems to be several versions of javascript out of date.

Not a single element in the sidebar is accurate:
![image](https://user-images.githubusercontent.com/3362993/30789795-461df51c-a1eb-11e7-9ba0-1966068aa351.png)

**Comment by elextr** [comment]
@nahidakbar 1.27 is too old to include the change referenced above, you need at least 1.30.1.

**Comment by b4n** [comment]
Even current master doesn't have support for ES6 classes in the symbols tree, we still have to import the changes I made in U-CTags.
