### ISSUE TITLE
Haxe conditionals sometimes break syntax highlight

### ISSUE THREAD

**Issue by programmador** [geany/geany#936]
Haxe (*.hx) file highlight becomes broken starting from the place where conditional occurs
![broken](https://cloud.githubusercontent.com/assets/674995/13553226/9733cb96-e38a-11e5-8451-0989d30445e6.png)
Btw it works if one adds a negation to the condition:
![normal](https://cloud.githubusercontent.com/assets/674995/13553225/972f039a-e38a-11e5-8ff4-6dafb5b68ffe.png)
Actually it's quite an old bug. I think it was there always.

**Comment by kugel-** [comment]
Seems to be a Scintilla bug. Can you report it there also?

**Comment by b4n** [comment]
Not sure it's Scintilla itself, looks like some part are "just" not styled.  Maybe Haxe uses a trick for commented-out preprocessor like C can (disabled by default though), and uses different styles there.

**Comment by programmador** [comment]
Yes, Haxe uses similar to C preprocessor, with similar syntax.
So should I create a bug report at scintilla sourceforge or not?

**Comment by programmador** [comment]
I tried SciTE - it doesn't have haxe support.
FlashDevelop uses scintilla too and I don't think it has any conditionals syntax highlight issues though it's the most popular IDE among Haxe developers.
So are you sure it's a scintilla bug?

**Comment by b4n** [comment]
> So are you sure it's a scintilla bug?

Actually it's not, it's "just" that we don't set the "inactive preprocessor" styles, and anyway Haxe's preprocessor directives are different from C, and we forget to disable preprocessor tracking for Haxe.  Done now.
