### ISSUE TITLE
Warnings when run make install 

### ISSUE THREAD

**Issue by frlan** [geany/geany#962]
```
libtool: warning: relinking 'classbuilder.la'
libtool: warning: relinking 'htmlchars.la'
libtool: warning: relinking 'export.la'
libtool: warning: relinking 'saveactions.la'
libtool: warning: relinking 'filebrowser.la'
libtool: warning: relinking 'splitwindow.la'
libtool: warning: remember to run 'libtool --finish /home/frlan/quellen/geany/geany-1.27/_inst/lib/geany'

```

**Comment by codebrainz** [comment]
IIRC @elextr looked into this before and found it was actually linking twice.

**Comment by techee** [comment]
I was getting the last warning for every plugin from g-p when building on osx.

**Comment by elextr** [comment]
And it occurs when building on Linux, but its harmless.

**Comment by LarsGit223** [comment]
Should this be closed?

**Comment by techee** [comment]
Would be nice if it got rather fixed. What's causing that the libraries get relinked again when installing?

**Comment by elextr** [comment]
AFAICT libtool "magic".

**Comment by kugel-** [comment]
This is normal. Libtool links per default against the uninstalled libgeany.so. Upon make install, it links against the installed libgeany.so (so that you can run the program without installing).

I think it does not do this if the prefix is /usr, but otherwise always (including prefix=/usr/local)

**Comment by techee** [comment]
@kugel- OK, makes sense then. I know this didn't happen when there wasn't libgeany.so so this explains the difference.
