### ISSUE TITLE
Preserve cursor position on reload

### ISSUE THREAD

**Issue by elextr** [geany/geany#969]
Currently on reload the cursor moves to the start, causing a scroll to the start.

The cursor position should be saved and restored if possible (ie if the file is still longer than the position).

Even better would be for the screen position to remain the same, but I'm not sure Scintilla supports that.

My personal use-case is reloading test logs where I want the cursor to go to the previously failing test output so I can check I fixed it, but there are others as well.

**Comment by b4n** [comment]
Ideally a Scintilla undo would restore caret position itself.  But yeah, would be nice even if only for reload.

**Comment by elextr** [comment]
Interestingly if using split-window plugin, on reload one pane goes to the start of the file and the other stays put :)

**Comment by LarsGit223** [comment]
Is this still an issue? If I reload a document the cursor stays where it is (only the visible area of the editor window changes slightly).

**Comment by elextr** [comment]
Hmmm, seems to work, but I can't find what fixed it, must have a bad commit message.  Will close for now, can always re-open later if its still broken.

**Comment by codebrainz** [comment]
It was fixed in ab529561503efe49ca2078d5f50ad60830f15cf3 at one point, but that was quite some time before this Issue was opened.

**Comment by elextr** [comment]
Yeah, more likely somewhere around [here](https://github.com/geany/geany/blob/6e4eece98138d07063962926f4a6f877edbd8bb9/src/document.c#L1613)
