### ISSUE TITLE
Access violation reading location 0x00000000.

### ISSUE THREAD

**Issue by davibail** [geany/geany#989]
Crash description:
Doing some text editing in html with tag highlighting on.

Error:
Exception thrown at 0x75DE8B21 (msvcrt.dll) in geany.exe: 0xC0000005: Access violation reading location 0x00000000.

Call stack:

>   msvcrt.dll!75de8b21()   Unknown
>     [Frames below may be incorrect and/or missing, no symbols loaded for msvcrt.dll]  
>     pairtaghighlighter.dll!66c81ad1()   Unknown
>     libgeany-0.dll!6a168d59()   Unknown
>     libgobject-2.0-0.dll!63c45fd2() Unknown
>     libglib-2.0-0.dll!687e3008()    Unknown
>     libgobject-2.0-0.dll!63c4a41f() Unknown
>     libgobject-2.0-0.dll!63c45fd2() Unknown
>     libglib-2.0-0.dll!687e3008()    Unknown
>     libgtk-win32-2.0-0.dll!61a5f0de()   Unknown
>     libgeany-0.dll!6a1dc0bb()   Unknown
>     libgeany-0.dll!6a1e3ab7()   Unknown
>     libgeany-0.dll!6a1ba057()   Unknown
>     libglib-2.0-0.dll!687f362a()    Unknown
>     libglib-2.0-0.dll!687f39dc()    Unknown
>     libglib-2.0-0.dll!68801820()    Unknown
>     libgtk-win32-2.0-0.dll!61a4c11f()   Unknown
>     libgeany-0.dll!6a17a0d1()   Unknown
>     geany.exe!00402820()    Unknown
>     geany.exe!004013e2()    Unknown
>     [External Code]

**Comment by elextr** [comment]
The crash appears to be occurring in the pair tag highlighter plugin.  The plugins is a separate project with each plugin having its own maintainer.  Please report it to the [plugin maintainer](http://plugins.geany.org/pairtaghighlighter.html) or to https://github.com/geany/geany-plugins/issues.

**Comment by LarsGit223** [comment]
I guess this can also be closed.
