### ISSUE TITLE
Want to implement scintilla: comment.block.at.line.start.python=1

### ISSUE THREAD

**Issue by henrythemouse** [geany/geany#992]
I'd like to have my commented lines in python files be commented at the left margin instead at the first non-whitespace character on the line. This scintilla configuration line should do the trick.

From the SciTE manual:
`Set comment.block.at.line.start to "1" to place block comment symbols at the start of the lines, instead of just before the first non-blank character of the lines.`

I typed it in to the [lexer_properties] area of Geany's  filetypes.python file, but didn't get any change in behavior. I'm wondering if these SciTE variables are compatible with Geany? Does Geany only recognize a subset of these variables? Or am I doing something that is impossible or just plain doing it wrong?

TIA,
Gary

**Comment by elextr** [comment]
That setting is for Scite, not Scintilla.  Geany does not use any Scite code, only Scintilla.

**Comment by henrythemouse** [comment]
Well, I thought SciTE used scintilla code.
Do you know of a similar variable in scintilla code?

**Comment by elextr** [comment]
Sure Scite uses Scintilla, but Scintilla is only the basic editing widget, language things like this are in Scite.

Nearest in Geany might be the [comment_use_indent](http://www.geany.org/manual/current/index.html#settings-section) setting in filetype files.

**Comment by henrythemouse** [comment]
That works. Even though the docs say it only works on single lines, when I just tested, it worked fine on multiple selected lines.

I'm beginning to wonder if there is anything that Geany can't do :-)
Thanks for the help, I withdraw what was once intended to be a feature request.
