### ISSUE TITLE
Minor highlighting issue for "Conf" filetype

### ISSUE THREAD

**Issue by 12345ieee** [geany/geany#996]
Let's start with:
```
andreas@duelitri:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux unstable (sid)
Release:	unstable
Codename:	sid
```
and:
```
andreas@duelitri:~$ geany -V
geany 1.27 (generato il 2016-03-13 conGTK 2.24.30, GLib 2.46.2)
```
(you miss a space after 'con' in the Italian translation, but this is not the issue at hand).

Reproduce the issue with the following script (bash):
```
echo -n a > /tmp/a.conf; for ((i=2; i<=1023; i++)); do echo -n a >> /tmp/a.conf; done; echo \;this is red but it shouldn\'t be >> /tmp/a.conf
```
this generates a file with 1023 `a`, a `;` in the 1024th place and text after the `;`, which, you guessed it, is highlighted as a comment even if it shouldn't be.

The key to this seems to be having a `;` in the 1024th place in the line, I tried several other chars and didn't get the problem, though I didn't try them all systematically.
Same for the "Conf" filetype, tried several and only this one seems to be affected.

Once this bug is triggered, a `;` in place 2048 will make the text black again and so on every 1024 (yay for 10bit overflowing, I guess).

Extremely minor, but though you may want to know.

**Comment by codebrainz** [comment]
I haven't tried to reproduce it, but FWIW, [`;` is a comment](https://github.com/geany/geany/blob/master/scintilla/lexers/LexProps.cxx#L57) in the lexer used for "Config" filetype. I have no idea what "Properties" files are, but it's probably based on INI format, which uses `;` as a comment start character.

In any case, the lexers are maintained upstream in [Scintilla](http://www.scintilla.org/), so you should probably [report bugs/patches there](https://sourceforge.net/p/scintilla/bugs/), unless you have a reason to believe Geany is doing something wrong (ex. if it works in [SciTE](http://www.scintilla.org/SciTE.html), the Scintilla reference editor, but not in Geany).

**Comment by 12345ieee** [comment]
I confirm that the bug is preset in SciTE and is triggered by all 3 the control chars (`;`, `#`, `!`) in the lexer.

This can be closed, I'll report it upstream.

**Comment by elextr** [comment]
@12345ieee you can close issues you create IIUC, but done for you.
